### ISSUE TITLE
Respec seems to be breaking styles and reference links in multiple specs

### ISSUE THREAD

**Issue by yoavweiss** [w3c/respec#1010]
We're seeing respec issues in a few WebPerfWG specs, which makes me suspect Respec is experiencing some issues.

https://github.com/w3c/resource-hints/issues/69 describes the issues seen on [resource-hints](https://w3c.github.io/resource-hints/), but [Preload](https://w3c.github.io/preload/)'s spec shows the same issues.

The "https://www.w3.org/StyleSheets/TR/2017/W3C-ED Failed to load resource: the server responded with a status of 404 (Not Found)" comment makes me think it might be related to the new year (a Y2K17 bug? :D)

/cc @marcoscaceres @dontcallmedom @RByers

**Comment by marcoscaceres** [comment]
heh, seems a [massive number of specs](https://github.com/search?q=org%3Aw3c+useExperimentalStyles%3A+true%2C&type=Code) opted for "experimental styles":

```
 useExperimentalStyles: true,
```

However, true maps to the new year - as the w3c was supposed to release new styles every year. Anyway, easy fix: will just make case "true": 2016.

**Comment by marcoscaceres** [comment]
fixed via 16520e578a74ff2b4a27d4e856c2270d7354abf2. Released in ReSpec 8.0.1
