### ISSUE TITLE
Normative references from informative sections

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#1020]
If a section is marked as informative, but there is a spec reference in that section that is tagged normative, and there is NO OTHER REFERENCE to that external spec that is also marked normative, should the reference be normative?  Should it be marked as informative?   Should there just be a respec warning so the editor can fix it?

**Comment by marcoscaceres** [comment]
Definitely would be good. Sounds like something to add to the linter.

**Comment by riannella** [comment]
Good idea. A respec warning would be sufficient.

**Comment by marcoscaceres** [comment]
We now support this.
