### ISSUE TITLE
Allow linking to fully qualified method name

### ISSUE THREAD

**Issue by alvestrand** [w3c/respec#1024]
In this page:

https://github.com/w3c/respec/wiki/WebIDL-Guide

we see

Similarly, to define the Request.clone() method, you'd write &lt;dfn>Request.clone&lt;/dfn>()</dfn>.

but later:

&lt;p data-dfn-for="Request">
    The &lt;dfn data-lt="clone()">clone&lt;/dfn> method.
    The &lt;dfn>url&lt;/dfn> attribute.
&lt;/p>

Are the parentheses supposed to be inside or outside the &lt;dfn> or the link, or doesn't it matter?

**Comment by marcoscaceres** [comment]
I literally just send a fix for this today 🎉  Let me fix the wiki.

**Comment by marcoscaceres** [comment]
@alvestrand, so, you can just do:

```HTML
<section data-dfn-for="Foo" data-link-for="Foo">
 <pre>
   interface Foo{}
  </pre>
 <dfn>clone()</dfn>
 <p>The <a>foo()</a>...</p>
</section>
```

And it will work. I realized I didn't actually add support for `<dfn>Request.clone</dfn>()` but that's not a nice way of defining things regardless. 

I'm going to get ReSpec to automatically add "data-link-for=" to `<sections>` that have a "data-dfn-for"... but in a few days from now. That will make the whole thing much much much nicer to work with.

**Comment by marcoscaceres** [comment]
fixed idl above.

**Comment by marcoscaceres** [comment]
Btw, which spec are you fixing up? Im happy to help.

**Comment by alvestrand** [comment]
Thanks - the question was whether &lt;dfn&rt;clone()<&lt;/dfn&rt; works the same as &lt;dfn&rt;clone&lt;/dfn&rt;() - the ambiguity still remains in the wiki.

I THINK the example with the parentheses outside is likely to be wrong, since there's only one of it and a dozen of the other, but I'd like to be sure.

WRT "what spec": I'm trying to fix errors in webrtc-stats - seems that dom has already fixed up webrtc-pc.
(in webrtc-stats, I'm quoting a piece of IDL from another spec; 4 out of 5 complaints are about that piece - I'd like to just say "this is IDL but don't bother linking it", but might resort to just putting dfns in the "defined elsewhere" section.)

**Comment by marcoscaceres** [comment]
> Thanks - the question was whether <dfn>clone()<</dfn> works the same as <dfn>clone</dfn>()

It should work the same. If not, that's a bug. 

> - the ambiguity still remains in the wiki.

Actually, `<dfn>Foo.bar()</dfn>` doesn't work... fixing. What does work is just `<dfn>foo()</dfn>`  

> I THINK the example with the parentheses outside is likely to be wrong, since there's only one of it and a dozen of the other, but I'd like to be sure.

It's actually ok... it's for backwards compat.
