### ISSUE TITLE
IE11 Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by tpluscode** [w3c/respec#1025]
ReSpec 8.4.1 fails on IE11 on [this lie](https://github.com/w3c/respec/blob/develop/js/core/utils.js#L53) because apparently the `remove` method is [not supported on IE at all](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove)

**Comment by marcoscaceres** [comment]
Yeah, we don't support IE as we don't have enough resources (and  Microsoft killed it). 

Should work in Edge 13+, however.

**Comment by tpluscode** [comment]
So it's officially an unsupported browser?

**Comment by marcoscaceres** [comment]
Yeah, however, I'm happy to except PRs for any brokeness. Most compat bugs are easy to fix... i just dont have access to a Windows box

**Comment by halindrome** [comment]
FWIW I don't really like not supporting IE11.  I consider this current technology.  And I do have access to a Windows box so I can look and submit PRs as appropriate.

**Comment by halindrome** [comment]
Huh - well, IE 11 also doesn't know about Promise apparently.

'Promise' is undefined

Do we no longer include the polyfill @marcoscaceres ? If so it is going to challenging to make much progress on a PR.

**Comment by marcoscaceres** [comment]
Seems I removed Promise back in August 2016: 
https://github.com/w3c/respec/pull/916

**Comment by halindrome** [comment]
I know that you are trying hard to make respec smaller and faster, but if putting Promise back in would resolve the issue for people who are not yet on Windows 10 - I think it is worth it.  Could even be conditional?

**Comment by marcoscaceres** [comment]
I've been giving this a lot of thought, but I can't see how it could work as we would constantly be having to backport things to IE. So, like, if we polyfilled Promises, then we would then need to polyfill `Object.keys()`, `Array.from()`, and other things that are widely supported in all other browsers, but are never going to be added to IE. 

IMO, we should focus on having great support for Edge instead.

**Comment by dduuu** [comment]
In angular install remove-element using this command (npm install --save element-remove)
and the import remove-element in polyfill (import 'element-remove';)

**Comment by CodeTropolis** [comment]
@dduuu Thank you! `solved Object does not support` remove bug.  IE version: 11.0.9600.19204

**Comment by kajalbh99** [comment]
@dduuu thank you. After wasting a long time . I have resolved this issue on IE 11.

**Comment by saidsoualhi** [comment]
@dduuu Thank you it worked for me on IE 11

**Comment by prabhathAmila** [comment]
https://recalll.co/ask/v/topic/javascript-Object-doesn%27t-support-property-or-method-%27remove%27/5a7bbca51126f4ac718b6019

**Comment by SirArlo** [comment]
@dduuu I love you <3 having to support enterprise websites on this crap browser sucks.
