### ISSUE TITLE
WebIDL - how to have dictionary members and constructor object properties link to same definition?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/respec#1027]
Currently trying to fix recent ReSpec warnings for the Pointer Events spec (x-ref https://github.com/w3c/pointerevents/issues/163), and am coming across a small conundrum: in https://w3c.github.io/pointerevents/#pointerevent-interface the spec defines a dictionary `PointerEventInit` and a constructor `PointerEvent`; both list the same members/properties, and ideally these should link to the single definition for each of them (so for instance, `pointerId` in both the dictionary and the constructor should both link to https://w3c.github.io/pointerevents/#dom-pointerevent-pointerid).

However, this doesn't currently seem possible - `data-dfn-for` / `data-dfn-link` can't take more than a single value, and if I remove it completely I get double the ReSpec warnings because it then doesn't know which WebIDL bit it needs to actually link to the definitions.

Am I simply doing it wrong in the WebIDL definition? (I didn't write that one myself, simply grabbed what was in previous version of the spec)

Or is this a known bug/shortcoming in ReSpec, and I should simply ignore the warnings?

(note that this only refers to warnings 1 - 10, the remaining 11 - 15 warnings were trivial to solve)

**Comment by patrickhlauke** [comment]
Essentially, I want to do the opposite of what's explained here https://github.com/w3c/respec/wiki/WebIDL-Guide#multiple-interfaces-with-same-attributesmethods - I don't want to distinguish between them, I want to point all instances to the same definition.

**Comment by marcoscaceres** [comment]
Ok, so... technically, what ReSpec is reporting is correct... but the solution is not so great. I would suggest moving the dictionary to its own `<section>`  and then for each member, saying that the semantics are the same as for the interface... so:

```HTML
<section data-dfn-for="PointerEventInit">
  <h2><dfn>PointerEventInit</dfn> dictionary</h2>
  <pre class="idl">
            dictionary PointerEventInit : MouseEventInit {
              long pointerId = 0;
              double width = 1;
              double height = 1;
              float pressure = 0;
              float tangentialPressure = 0;
              long tiltX = 0;
              long tiltY = 0;
              long twist = 0;
              DOM pointerType = "";
              boolean isPrimary = false;
            };
          </pre>
  <dl>
    <dt>
      <dfn>pointerId</dfn>
    </dt>
    <dd>See the <a>PointerEvent.pointerId</a> attribute.</dd>
    <dt>
      <dfn>width</dfn>
    </dt>
    <dd>See the <a>PointerEvent.width</a> attribute.</dd>
    <dt>
      <dfn>height</dfn>
    </dt>
    <dd>See the <a>PointerEvent.height</a> attribute.</dd>
    <dt>
      <dfn>pressure</dfn>
    </dt>
    <dd>See the <a>PointerEvent.pressure</a> attribute.</dd>
    <dt>
      <dfn>tangentialPressure</dfn>
    </dt>
    <dd>See the <a>PointerEvent.tangentialPressure</a> attribute.</dd>
    <dt>
      <dfn>tiltX</dfn>
    </dt>
    <dd>See the <a>PointerEvent.tiltX</a> attribute.</dd>
    <dt>
      <dfn>tiltY</dfn>
    </dt>
    <dd>See the <a>PointerEvent.tiltY</a> attribute.</dd>
    <dt>
      <dfn>twist</dfn>
    </dt>
    <dd>See the <a>PointerEvent.twist</a> attribute.</dd>
    <dt>
      <dfn>pointerType</dfn>
    </dt>
    <dd>See the <a>PointerEvent.pointerType</a> attribute.</dd>
    <dt>
      <dfn>isPrimary</dfn>
    </dt>
    <dd>See the <a>PointerEvent.isPrimary</a> attribute.</dd>
  </dl>
</section>
```

**Comment by marcoscaceres** [comment]
Fixed up indenting in code above.

**Comment by marcoscaceres** [comment]
That's the best we can do right now - as anything else will require quite a bit of refactoring of ReSpec (which I don't have time to do right now 😭).

**Comment by patrickhlauke** [comment]
Urgh...I think I may live with the ReSpec warnings for the time being ;)

**Comment by marcoscaceres** [comment]
@patrickhlauke, why? The above solves the problem. It's also much more flexible as it allows you to more clearly differentiate between the dictionary and the interface.

**Comment by marcoscaceres** [comment]
(you want me to send the PR? I don't mind doing it)

**Comment by patrickhlauke** [comment]
> why? The above solves the problem.

but, subjectively, it makes for a lot of redundant content in the spec text...feels like it appeases ReSpec rather than serving any other purpose for authors/developers who read the spec.

**Comment by RByers** [comment]
Yeah, for example DOM doesn't bother having a bunch of boilerplate text saying what all the [EventInit members do](https://dom.spec.whatwg.org/#dom-eventinit-bubbles).  [UI Events does](https://w3c.github.io/uievents/#dictdef-mouseeventinit).

I don't have a strong preference either way but it would be nice to eliminate the warnings (since otherwise we'll be blind to new warnings which are actually useful).  Could we just quickly hack around this by having some dummy definitions inside an element with a display:none style with a comment saying it's a work around for this issue?

**Comment by marcoscaceres** [comment]
> I don't have a strong preference either way but it would be nice to eliminate the warnings (since otherwise we'll be blind to new warnings which are actually useful).

I'm biased, but as a reader, I do prefer that specs define all the IDL things... they are all slightly different and serve different purpose. Tho, yes, the purpose may be self-evident and may not require prose.

> Could we just quickly hack around this by having some dummy definitions inside an element with a display:none style with a comment saying it's a work around for this issue?

The above probably won't work, as it's dependent on what is in the tree. 

However, I can add a pref, like: 

```JS
{
   webidl: {
     noLinkWarnings: true
   }
}
```

Alternatively, we can set a class "no-link-warnings" in the ancestor chain or directly on the `<pre>` element.

**Comment by marcoscaceres** [comment]
@patrickhlauke, @RByers, ok, please add "no-link-warnings" to the the class attr of `<pre class="idl">` to silence the warnings. I didn't implement the global pref as this will probably do for now.

**Comment by patrickhlauke** [comment]
Perfect, thank you
