### ISSUE TITLE
Documentation/wiki: add separate page for `data-lt`

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/respec#1035]
While `data-lt` is explained in https://github.com/w3c/respec/wiki/User's-Guide#definitions-and-linking there is no specific page for it in the wiki (probably under either WebIDL or HTML attributes - something along the same lines as https://github.com/w3c/respec/wiki/data-link-for)

**Comment by marcoscaceres** [comment]
Good suggestion... will try to do it soon.

**Comment by Swapnilr1** [comment]
Closed with https://github.com/w3c/respec/wiki/data-lt
