### ISSUE TITLE
Documentation/wiki: example for `data-merge`

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/respec#1036]
https://github.com/w3c/respec/wiki/data-merge could do with an actual code example

**Comment by marcoscaceres** [comment]
Interesting, I've never used that feature. Didn't even know it existed 💃

**Comment by marcoscaceres** [comment]
@anssiko, looking at ReSpec history, there is some mention of you around data-merge... any idea how it actually works?

**Comment by anssiko** [comment]
I think I added that feature like long time ago (CVS times :-)). As the [docs][1] say, the `data-merge` feature merges separate WebIDL blocks together (common use case: a dictionary and a related interface). This was to address a limitation in the old ReSpec IDL parser that required each interface to be defined in its own IDL block, even if they'd logically fit together.

When all the ReSpec-using specs have migrated to use the Contiguous IDL, `data-merge` can be deprecated. It was relatively broadly used, so it might make sense to check somehow if the feature is still in use and ask to migrate to Contiguous IDL if so.

[1]: https://github.com/w3c/respec/wiki/data-merge

**Comment by marcoscaceres** [comment]
@anssiko, thanks for the history lesson! that's super helpful. 

I've checked ReSpec's source and indeed there is no longer any sign of this code. Seems I must have removed it when I deleted the "oldschool-webidl" module. I've deleted the data-merge page from the wiki.
