### ISSUE TITLE
Non lowercase-only overloaded operations not detected

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#1042]
Operations that are overloaded and have camelCased names aren't detected in the prose by Respec (as currently seen in the [WebRTC editors draft](http://w3c.github.io/webrtc-pc/webrtc.html) which creates some of the [reported ReSpec warnings](https://github.com/w3c/webrtc-pc/issues/978)).

I have an upcoming patch to fix this

**Comment by marcoscaceres** [comment]
I don't know why idl matches are  done in lower case. I think we should make them case sensitive. Can anyone think of a reason? I get why prose definitions would be lcased. But JS APIs are case sensitive - so we should fix this.
