### ISSUE TITLE
data-cite values are case-sensitive

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#1047]
In developing an update to [JSON-LD](http://json-ld.org/spec/latest/json-ld/), I use a `localBiblio` definition for [[JSON-LD]] to reference the develop version. I've noticed that if I use `data-cite="json-ld-api#rdf-serialization-deserialization-algorithms"` it does not use the URL from `localBiblio`. If I use `data-cite="JSON-LD-API#rdf-serialization-deserialization-algorithms"` it links correctly.

Thanks for the cool feature.

**Comment by marcoscaceres** [comment]
Yeah, the IDs are case sensitive. Hope that's ok. I'd rather make things case sensitive were possible to avoid conflicts.

**Comment by marcoscaceres** [comment]
@gkellogg, btw... I have a sneak feature I'm testing out... you can also do:

```HTML
  <p><dfn data-cite="spec#frag">thing</dfn>...
  <p>...<a>thing</a>...
```

And it auto-links "thing" to the correct spec.

**Comment by gkellogg** [comment]
Thanks, that's quite useful too.
