### ISSUE TITLE
Child of informative sections should also be informative

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1052]
This could be a breaking change, so just a proposal... but if a parent section class="informative", then child section  should be informative too. Then the child should opt-out by setting itself to normative.

```HTML
<section class="informative">
  <section>Also informative</section>
  <section class="normative">Opted out!</section>
</section>
```

**Comment by halindrome** [comment]
I think this is the case already, in that hierarchies inherit.  So no, I do not think this is a breaking change.  Nor do I think it is needed.  @plehegar ?

**Comment by marcoscaceres** [comment]
Closing, as contextual citations handler this.
