### ISSUE TITLE
Create Turtle syntax highlighter for highlight.js

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/respec#1063]
Here's how:
http://highlightjs.readthedocs.io/en/latest/language-guide.html

CodeMirror has one that might serve as a handy reference:
view-source:http://codemirror.net/mode/turtle/turtle.js

There are (of course) other RDF serialization formats (N3, TriG, etc) in use at the W3C, but this one's quite common--and unexpectedly absent (as the Web Annotation WG found out last year https://github.com/w3c/web-annotation/issues/260).

If someone wants to kick this off, I'm happy to contribute/test/etc.

Cheers!
🎩

**Comment by marcoscaceres** [comment]
If someone adds a language definition for hljs, then I'm totally happy to add it. A quick hack might be to see if there is something "turtle-like" and either use that or make the appropriate modifications to it. In the mean time, I'm closing this as it's outside ReSpec's scope to create such definition. However, once you find or create an appropriate one, it literally will take 2 minutes to enable it! Good luck!
