### ISSUE TITLE
ReSpec should warn on unstructured/text specref entries

### ISSUE THREAD

**Issue by riannella** [w3c/respec#1082]
For some strange reason, 2 references are not working in our document:
 http://w3c.github.io/poe/vocab/#informative-references

They are [[iso3166]] and [[iso8601]]

And I tried "ISO" as well..

any ideas?

**Comment by marcoscaceres** [comment]
How odd... having a quick look.

**Comment by marcoscaceres** [comment]
I'm not able to reproduce locally, so will need to dig a little deeper. However, the "nanotabs" script is generating errors which maybe related. 

First error: 

 > Mixed Content: The page at 'https://w3c.github.io/poe/vocab/#informative-references' was loaded over HTTPS, but requested an insecure script 'http://www.w3.org/scripts/nanotabs/0.9/nanotabs.js'. This request has been blocked; the content must be served over HTTPS.

Sent a PR. Let's check again once that goes in.

**Comment by riannella** [comment]
Ok...I've removed the nanotabs script (as we don't use it anymore).
Issue remains...I might have to add the references to the local biblio?

**Comment by marcoscaceres** [comment]
> Ok...I've removed the nanotabs script (as we don't use it anymore).

Ok, thanks for eliminating that. 

> I might have to add the references to the local biblio?

Local biblio is empty. 

Still trying to see where else that reference is getting lost and why.

**Comment by marcoscaceres** [comment]
(as a temporary fix, adding it to localBiblio might fix it :) )

**Comment by marcoscaceres** [comment]
Ah, I see what's happened. I forgot that we have these references as unstructured text - so when it gets added to the references database it gets converted into an object... which is kinda amusing: 

![screenshot 2017-02-16 13 07 56](https://cloud.githubusercontent.com/assets/870154/23004116/f695f760-f448-11e6-9f7b-865c3ca5ce1e.png)

As we don't want to support unstructured data in SpecRef anymore, we should fix this there. 

BRB...

**Comment by marcoscaceres** [comment]
Ok, will add the following to spec ref.

```
  "ISO3166": {
    "authors": [""],
    "date": "",
    "href": "http://www.iso.org/iso/home/standards/country_codes.htm",
    "publisher": "ISO",
    "status": "",
    "title": "ISO 3166: Codes for the representation of names of countries and their subdivisions."
  },
  "ISO8601": {
    "authors": [""],
    "date": "",
    "href": "http://www.iso.org/iso/catalogue_detail?csnumber=40874",
    "publisher": "ISO",
    "status": "",
    "title": "Representation of dates and times. ISO 8601:2004."
  },
```

**Comment by riannella** [comment]
here's an update:

        "iso3166": {
            title: "Codes for the representation of names of countries and their subdivisions",
            publisher: "International Organization for Standardization (ISO)",
            status: "ISO 3166-1:2013",
            date: "2013",
            href: "http://www.iso.org/iso/catalogue_detail?csnumber=63545"
        },
        "iso8601": {
            title: "Representation of dates and times",
            publisher: "International Organization for Standardization (ISO)",
            status: "ISO 8601:2004",
            date: "2004",
            href: "http://www.iso.org/iso/catalogue_detail?csnumber=40874"
        }

**Comment by marcoscaceres** [comment]
@riannella thanks! Will add those  now.

**Comment by marcoscaceres** [comment]
@riannella sent PR... just need @tobie to help me with something there:
https://github.com/tobie/specref/pull/330

For other legacy entries, you can use this tool to generate them:
http://marcoscaceres.github.io/bib_entry_maker/

**Comment by marcoscaceres** [comment]
Anyway, that should fix the entries... I'll update ReSpec to warn when a legacy entry type is encountered to encourage authors to update those.

**Comment by riannella** [comment]
great, thanks for your help @marcoscaceres

**Comment by marcoscaceres** [comment]
@riannella, after we merge, you will need to do a "hard reload" of the spec in the browser to get the broken entries to show up - otherwise, they should fix themselves after 24 hours (I make ReSpec refresh the spec's database once a day - or when it detects things have been updated on the server - in the background).

**Comment by marcoscaceres** [comment]
Ok, they are working again 🎉 
![screenshot 2017-02-16 14 10 53](https://cloud.githubusercontent.com/assets/870154/23005716/c5d0db78-f451-11e6-86e5-b2cc645ae80e.png)

**Comment by riannella** [comment]
Yeah..thanks...Now to get the title listed first #857 👍

**Comment by marcoscaceres** [comment]
agree... what's there is pretty terrible. Might just fix that without doing the custom styles.
