### ISSUE TITLE
Make it possible to test errors and warning

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1084]
There is currently no way to hook into the errors and warnings system. Need a means to do that that for testing the linter properly, for instance. A bunch of other modules emit warnings, and it would be good to test those too.

**Comment by devanshbatra04** [comment]
Been thinking over this. 
We could have some debug functions/test functions. They would be very specific to the critical code paths that are most likely to yield an error/warning. 

And then when the user clicks the button to list the warning/error, add a button "Test With Custom Input". 
On clicking it, we could have a modal pop up with a description specific to each such function. 

Should I come up with a mockup?

**Comment by marcoscaceres** [comment]
Can probably avoid the clicking part... I was thinking we could just have callbacks on the configuration objects in the tests... so:

```JS
const ops = {}

const errorPromise = new Promise(r => {
  ops.onError(error){
    expect(error).toBe("whatever");
    r();
  },
});
const warningPromise = new Promise(r => {
  ops.onWarning(error){
    expect(error).toBe("whatever");
    r();
  },
});
const doc = await makeRSDoc(ops);
await Promise.all([errorPromise, warningPromise])

```

**Comment by marcoscaceres** [comment]
Fixed some typos above...

**Comment by devanshbatra04** [comment]
Oh okay. Thanks. 
I guess I misunderstood. Will work on this today.

**Comment by marcoscaceres** [comment]
No problem - you were definitely on the right track :) Eventually we might want to do UI testing.

**Comment by devanshbatra04** [comment]
So I was working on this and figured this was probably not the best approach.
1. This does not give us all the errors and warning to work with. That means we wouldn't be able to test them in conjunction. (One warning/error may be related with another but we have no way of interacting with the two. As both are dealt with by different promises)
2. Also there would be several unnecessary errors. Most of the test documents made by makeRSdoc would not have the SoTD for instance. Resulting in an error.

Here's a solution I came up with. 
create conf flags. collectErrors and collectWarnings. 
This gets automatically applied during tests. 
Add a conditional at ```sub("error")``` and ```sub("warn")``` to collect errors and warnings in globally available Sets. 

During Tests the tester can then 
```javascript
expect(collectedErrors.has("some-error")).toBeTruthy();
expect(collectedErrors.has("some-other-error")).toBeFalsy();
// (and possibly, although I would avoid)
expect(collectedErrors.size).toEqual(3);
```

This way he doesn't have to care about all the other errors popping up and handling them.
(Related to what all required ReSpec features his doc did not have)
