### ISSUE TITLE
Strange bug handling <pre> sections...

### ISSUE THREAD

**Issue by iherman** [w3c/respec#1089]
Consider the short [respec example](https://gist.github.com/iherman/f276d6e695b585212c608608cbd2d1ff). It has a `<pre>` section that include lines like `&lt;...&gt;`. The output of the file, via respec, is as follows:

<img width="667" alt="bad" src="https://cloud.githubusercontent.com/assets/520723/23024383/5f9239e8-f45a-11e6-9e3e-c6b42679c9e5.png">

What happens is that `&lt;...&gt;` is turned into `<...>` which is then swallowed by the HTML rendering. 

_If_ one adds and empty line to the end, plus some text, the display, magically, is o.k.::

<img width="614" alt="good" src="https://cloud.githubusercontent.com/assets/520723/23024579/348c5d7c-f45b-11e6-9ac3-bf4e6bb9ade0.png">

Which is correct (apart from the "rubbish" :-).

Note that if I remove the reference to `respec` and display the remaining HTML, it displays correctly. Ie, it has something to do with respec.

Do I miss some obvious mistake (in which case I have to buy myself a new pair of glasses) or is it a bug?

(I experienced the same thing in Vivaldi as well as Firefox, ie, it does not seem to be browser dependent either.)

**Comment by marcoscaceres** [comment]
d'oh... regression :( Will take a look tomorrow.

**Comment by marcoscaceres** [comment]
@iherman should hopefully be ok now. Thanks for reporting the issue!

**Comment by marcoscaceres** [comment]
oh, wait... gotta release 💃

**Comment by iherman** [comment]
You said it would be tomorrow:-)

Thanks @marcoscaceres!

**Comment by marcoscaceres** [comment]
... heh, sneaky 2-3am bug fix... I mean, what could go wrong?!

**Comment by iherman** [comment]
Just for the records: it works now on my test file! Thanks
