### ISSUE TITLE
Add support for former editors

### ISSUE THREAD

**Issue by MichielBijl** [w3c/respec#1097]
A bit superfluous, but in some cases the editor section can be a bit of a mess. For example, here is the APG’s editor listing:

<img width="714" alt="List of 7 APG editors including 3 previous editors. It shows editor’s name, company, and e-mail" src="https://cloud.githubusercontent.com/assets/5457769/23095714/7d5ef3b4-f606-11e6-8b56-b852a4767c9c.png">

ARIA’s editor listing is a bit better, but that’s mainly because their company names are shorter.

<img width="398" alt="List of 4 ARIA editors. It shows editor’s name, company, and e-mail." src="https://cloud.githubusercontent.com/assets/5457769/23095720/a1b55fe6-f606-11e6-8ce5-170eed60f5b7.png">

To compare that with the cleaner look of the HTML spec editor listing:

<img width="310" alt="Separate lists for 5 current HTML editors and 3 former HTML editors. It lists their name (which is linked to either their email or website) and their company name between brackets." src="https://cloud.githubusercontent.com/assets/5457769/23095727/e16bbf0e-f606-11e6-9e2f-9deba1e0943a.png">

Thoughts about moving towards the HTML look?

**Comment by MichielBijl** [comment]
After forking ReSpec and fiddling about, here is what the APG list could look like:

<img width="597" alt="Separate lists for 4 current APG editors and 3 former APG editors. It lists their name (which is linked to either their email or website) and their company name between brackets." src="https://cloud.githubusercontent.com/assets/5457769/23096103/df640804-f60d-11e6-996a-26e695f643f1.png">

I misused the author object for the former editors list as I was unable to create a new separate list he proper way :x.

**Comment by marcoscaceres** [comment]
@MichielBijl, you want to send over a PR? I think these are good additions.

**Comment by MichielBijl** [comment]
@marcoscaceres will do, need to filter out the things I broke/misused.

**Comment by MichielBijl** [comment]
Any chance you can assign this to me? Keep forgetting to actually do it…

**Comment by marcoscaceres** [comment]
Assigned
