### ISSUE TITLE
New cross-reference feature: warn about missing link in prose?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1106]
A new powerful cross-reference feature was introduced in January:
https://lists.w3.org/Archives/Public/spec-prod/2017JanMar/0011.html

That email says: "The cited spec is also added to the references, of course". This is great, the cited spec needs to appear in the references. However, I think that entry also needs to be referenced somewhere in the prose, meaning there should be text like "It's always beer-o-clock somewhere in the world [BEERTIME]", and not only direct links to the cited spec.

Could ReSpec warn when the new cross-reference feature is used but the spec does not explicitly reference the cited spec, perhaps?

**Comment by marcoscaceres** [comment]
Will add to the linter. 

I'm also working on a module that would automatically create a summary of used terms. That would avoid having Editors having to do the above, as it's quite laborious.

**Comment by marcoscaceres** [comment]
I think `xref` solves for this in 99% of cases, because you have to inline what you are linking to:

```HTML
<p data-cite="DOM">[=Fire an event=].</p>
```

Which discourages redundant usage citations like [[DOM]]. Using [[WHATEVER]] is not really only useful for taking about a spec in general, like "The [[DOM]] spec is great!".
