### ISSUE TITLE
Privacy warning for WG NOTE

### ISSUE THREAD

**Issue by riannella** [w3c/respec#1107]
One of our WG NOTE editor drafts: http://w3c.github.io/poe/ucr/
now shows a respec warning for having no "'Privacy' or 'Security' considerations sections.".

The NOTE is not REC track, so is there a way to stop this?

**Comment by marcoscaceres** [comment]
@riannella restricting to Rec track docs is a good suggestion, will fix.

**Comment by marcoscaceres** [comment]
@riannella, as a quick fix, you can set:

```JS
  lint: false,
```

in your ReSpec config. That should turn off that warning.

**Comment by riannella** [comment]
great, thanks
