### ISSUE TITLE
White screen -- sometimes

### ISSUE THREAD

**Issue by iherman** [w3c/respec#1113]
In some circumstances I have some files that display a blank, white screen. It is not deterministic, though; sometimes it displays properly, sometimes it does not.

I have cut it back into a small example file at: https://www.w3.org/2017/02/rperror/pr.html

the file is relatively minimal. It has a link to a css file, but that is all. The problem is: sometimes it displays properly, sometimes it does not (I tried several times, every time with a shift reload.) It also depends on browsers; it seems to be worse on FF, but the error also happens in Safari or Chrome.

In some cases:-( if one removes a paragraph, or removes the css link, then it improves things. Is there a race condition somewhere?

**Comment by marcoscaceres** [comment]
Confirmed. Seems to be breaking near:

```JS
setAttribute("aria-"
```
in js/core/ui.js

**Comment by iherman** [comment]
You are welcome, @marcoscaceres. Good luck!

**Comment by marcoscaceres** [comment]
patch didn't apply properly... trying again.

**Comment by tidoust** [comment]
Not sure if that's related but note white screen seems to occur everytime both on Firefox and Edge right now (for all specs I tried to load). I don't see any error reported by Firefox in the Console.

**Comment by marcoscaceres** [comment]
@tidoust, yeah, it's related. Just released a patch. Seeing if it's fixed.

**Comment by marcoscaceres** [comment]
heh, can I blame AWS even though it's unrelated?

**Comment by marcoscaceres** [comment]
Ok, fixed. @iherman and @tidoust, can you confirm with a hard reload. The ReSpec version should be 10.5.9

**Comment by tidoust** [comment]
I confirm everything's back to normal, including AWS, @marcoscaceres. Thanks!

Fixing Web specs by making them disappear is a nice feature, though. Worth an opt-in parameter, perhaps? ;)

**Comment by iherman** [comment]
> 
> Ok, fixed. @iherman <https://github.com/iherman> and @tidoust <https://github.com/tidoust>, can you confirm with a hard reload. The ReSpec version should be 10.5.9
> 

I do! Thanks.
