### ISSUE TITLE
document.body is null in respect-w3c-common:14:10169

### ISSUE THREAD

**Issue by andreastt** [w3c/respec#1123]
When loading https://w3c.github.io/webdriver/webdriver-spec.html, it occasionally fails with the following messages being printed in the console:

    error { target: Window, isTrusted: true, message: "Script error.", filename: "https://www.w3.org/Tools/respec/respec-w3c-common", lineno: 0, colno: 0, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, 1 more… }  respec-w3c-common:14:10152
    TypeError: document.body is null[Learn More]  respec-w3c-common:14:10169
    TypeError: e is undefined[Learn More]

Screenshot:

![screenshot-2017-03-01-093026](https://cloud.githubusercontent.com/assets/399120/23453834/c4521b62-fe61-11e6-82a0-c6684c4c1852.png)

Often when reloading, these errors disappear in favour of:

    error { target: Window, isTrusted: true, message: "UnknownError", filename: "https://www.w3.org/Tools/respec/respec-w3c-common", lineno: 13, colno: 1720, currentTarget: Window, eventPhase: 2, bubbles: true, cancelable: true, 1 more… }  respec-w3c-common:14:10152
    UnknownError

But then the spec renders as expected:

![screenshot-2017-03-01-093234](https://cloud.githubusercontent.com/assets/399120/23453880/051ae20a-fe62-11e6-8316-1b63b1d6dd9a.png)

**Comment by andreastt** [comment]
I should add that this occurred recently. I haven’t done a bisect.

**Comment by marcoscaceres** [comment]
@andreastt, should be fixed in 10.5.9 - can you check if it's ok?

**Comment by andreastt** [comment]
We don’t vendor respec, but instead import `
<script src=https://www.w3.org/Tools/respec/respec-w3c-common async class=remove></script>`. It reproduces with 10.5.9 (`window.respecVersion="10.5.9"`).

**Comment by andreastt** [comment]
You can reproduce by loading https://w3c.github.io/webdriver/webdriver-spec.html.

**Comment by marcoscaceres** [comment]
Odd, not hitting it on Mac in Safari, Chrome, or Firefox.

**Comment by marcoscaceres** [comment]
@andreastt oh, wrt the biblio fail - it might be bad data in the database. If you are in Chrome, can you try clearing out the IDB database?

**Comment by andreastt** [comment]
I cannot reproduce in Chrome, and interestingly, I cannot reproduce _reliably_ in my Firefox Nightly. I conferred with @sole (who happens to sit next to me) and it appears… something is wrong with my Firefox profile. Perhaps a corrupt IndexedDB database in the profile?

I am sorry to have troubled you with what appears to be a bug in Firefox and a corrupt profile.

**Comment by marcoscaceres** [comment]
It might be a race condition in ReSpec. It's indeterminate when the script runs, so can sometimes get weird fails (or specref sometimes fails to return bibliographical results). Will poke around a bit more in Nightly to see if I can reproduce.

**Comment by andreastt** [comment]
We couldn’t reproduce with a Nightly with a fresh profile, but of course it may be that ReSpec is missing some error handling for when it believes it has data but the data is corrupt or some such scenario. Unfortunately I don’t know IndexedDB well enough to go poking around, and the devtools _Storage_ tab didn’t list any IndexedDB database. |-:
