### ISSUE TITLE
Ability to crossref examples

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#1124]
The idea is to have something similar to what is supported for sections, so that the following markup

````html
<a href="#ex-some-example" class="exampleRef"></a>
````

will be rendered as

<a href="#ex-some-example" class="exampleRef">Example 123</a>

This would ensure that examples are referred to consistently, without the need of checking whether the number of the referred example changed (because examples were dropped/added/moved elsewhere).

**Comment by marcoscaceres** [comment]
> The idea is to have something similar to what is supported for sections

This sounds interesting, but I'm not sure what you mean by the above? How does one currently do what you propose with sections?

**Comment by andrea-perego** [comment]
Hi, @marcoscaceres .

>> The idea is to have something similar to what is supported for sections

> This sounds interesting, but I'm not sure what you mean by the above? How does one currently do what you propose with sections?

As far as I know, the approach is to use an empty anchor, of class `sectionRef`. E.g.:

````html
<a href="#changes" class="sectionRef"></a>
````

See: https://github.com/w3c/respec/wiki/section

Actually, the requirements for examples are more similar to what done with figures:

https://github.com/w3c/respec/wiki/figure

BTW, it would be nice to have a "table of examples", as there is a "table of figures".

**Comment by marcoscaceres** [comment]
Wow, had no idea. Looks like you don't need the class even. It should be possible to do exactly the same thing without the class and I can use the title attribute for the text content of the link.

**Comment by marcoscaceres** [comment]
Examples are now linkable, so closing.

**Comment by andrea-perego** [comment]
@marcoscaceres , how this could be done? I tried on a local copy of a ReSpec document, adding `<a href="#[exampled-id]"></a>`, but it does not work.

**Comment by marcoscaceres** [comment]
Oh, my bad, I misunderstood. I thought this was about making examples linkable.
