### ISSUE TITLE
Add special status for diff previews

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1126]
With integration of PR diff and previews, it is dangerous that people will start sharing URLs to snapshots. We need to add a special status for those, so they get styled correctly. WHATWG already doing this:

 See: 
https://s3.amazonaws.com/pr-preview/rmisev/url/empty-host-for-file.html

> tobie:  So I'd suggest specStatus=PR&prNumber="{{pull_request.number}}"
> tobie:  You can use this to test them out: https://tobie.github.io/pr-preview/config.html
> tobie: And once you have something satisfying for Respec, it would be amazing if you modified https://github.com/tobie/pr-preview/blob/master/docs/config.html#L91 accordingly
> tobie:  So people get the right default
> tobie:  and we don't end-up with thousands of ED-looking PR in the wild

**Comment by tobie** [comment]
FWIW, I think the modal warning in the WHATWG example above is overkill.

**Comment by marcoscaceres** [comment]
I was thinking the same - having it in the second state (attached to the bottom of the document) by default should be fine.

**Comment by marcoscaceres** [comment]
I've filed a bug on the W3C regarding the style sheet stuff we would need: https://github.com/w3c/tr-design/issues/114

**Comment by dontcallmedom** [comment]
I'm not sure I understand why this needs to be added to the TR stylesheet - wouldn't it be easier to add it to the respec stylesheet?

(as an aside, let's not use specStatus=PR for this - that's already used for Proposed Rec :)

**Comment by marcoscaceres** [comment]
> On 10 Mar 2017, at 8:14 pm, Dominique Hazael-Massieux <notifications@github.com> wrote:
> 
> I'm not sure I understand why this needs to be added to the TR stylesheet - wouldn't it be easier to add it to the respec stylesheet?
> 

We are trying to remove the ReSpec style sheet to normalize with BS also. 

If both BS and ReSpec require a style, then it makes it a candidate for "standardization". 

> (as an aside, let's not use specStatus=PR for this - that's already used for Proposed Rec :)
> 

Heh, good point.
