### ISSUE TITLE
Run "npm run hb:build" before building

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1127]
See http://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html

**Comment by marcoscaceres** [comment]
@palemieux, thanks! will fix!

**Comment by marcoscaceres** [comment]
fixed! Git is "shift-reload"

**Comment by palemieux** [comment]
Thanks. Definitely an opportunity to learn something new everyday.

**Comment by marcoscaceres** [comment]
Reopening because the bug is actually that the handle bars generator is currently not run when we release, which actually caused this issue.
