### ISSUE TITLE
Test process version

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1128]
We are currently lacking tests for the processVersion, which bit us :( Just need a simple test to check that the processVersion is defaulting correctly. Should also refactor the process version to not be a boolean - that's quite terrible.

**Comment by sidvishnoi** [comment]
Closed by 2e838ae and #1480 ?
And delete the wiki page for this also.
I was confused where `processVersion` is being used then I checked year of this issue. Haha.

**Comment by marcoscaceres** [comment]
Good catch! Closing
