### ISSUE TITLE
Switch to some other packaging system

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1129]
Ok, yeah... webpack is pretty awesome. It would take care of a ton of things for us - like automatic import of the dependencies, and we could dump use generators for async/await, instead of ES5 regenerator.

**Comment by nileshgulia1** [comment]
@marcoscaceres  Can I take this?

**Comment by marcoscaceres** [comment]
I don’t think we are quite there. I’ve also been using webpack for another project and kinda concluded that it’s not as awesome as I first thought (configuration is a nightmare). Maybe we should use rollup instead?

**Comment by nileshgulia1** [comment]
> Maybe we should use rollup instead?

Seems a great idea too,adding from me, i give `parcel` also a good option,may be?

**Comment by marcoscaceres** [comment]
Either would be great. Feel free to try them out. Ideally, we would like to see some reduction in bundle size.

**Comment by marcoscaceres** [comment]
Thanks to @nileshgulia1,  we concluded that we should keep our current build system and eventually move to ES modules and native `requires()` in the browser.
