### ISSUE TITLE
Referencing term using @data-lt can get confused

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#1161]
Consider the following:

      <p>
        Define <dfn>bar</dfn> and
        <dfn data-lt="foo-bar" data-lt-noDefault>bar</dfn>
        (which uses <code>@data-lt="foo-bar"</code> and <code>@data-lt-noDefault</code>)
        confuses a reference to <a>bar</a> and <a data-lt="foo-bar">bar</a> (which uses <code>@data-lt="foo-bar"</code>).
      </p>

The last reference to `bar` should get to that defined in `<dfn data-lt="foo-bar" data-lt-noDefault>bar</dfn>`, however, it ends up referencing `<dfn>bar</dfn>`. This becomes an issue when a term is defined within the main body of a document, and also used as a parameter in a WebIDL block using `@data-dfn-for`.

The problem seems to be in link-to-dfn around line 50, which doesn't seem to take into account `@data-lt`, although it could be because `target.for_` is not defined as expected. I'm a bit over my head in determining exactly what should change.

This is fighting the [ShEx spec](https://shexspec.github.io/spec/) [API](https://shexspec.github.io/spec/#the-application-programming-interface), where I'm forced to use an anchor body of `validate.schema` instead if simply `schema`, even though `@data-lt="ShExProcessor.validate.schema"`.

**Comment by marcoscaceres** [comment]
@gkellogg, we would need to teach ReSpec about "schema" as a type (same as we had to teach it about WebIDL). If you are up for it, I'd be happy to at least review.

**Comment by marcoscaceres** [comment]
@gkellogg, also note, there is no shame in using `<a href=#thing>` in ReSpec. It's a bit less convenient, sure, but it's totally ok.

**Comment by gkellogg** [comment]
@marcoscaceres This has nothing to do about ReSpec knowing about "schema", but rather that, if "schema" is defined as a term, as is something like "validate.schema", If I use `<a data-lt="validate.schema">schema</a>`, it ends up referencing the "schema" definition, instead of "validate.schema".

Of course I could use a regular `@href`, but then I don't get ReSpec's error checking, and I'm exposed to some internal naming issues, that shouldn't need to be exposed. The [documentation for WebIDL use](https://github.com/w3c/respec/wiki/data-link-for) specifically discusses using `@data-link-for` to provide scope for references, which results in the same issue, as it ultimately creates a `@data-ld` reference resolving the scope.

The example I provided above should make the issue clear, if you put it in the body of something like [examples/basic.html](https://github.com/w3c/respec/blob/develop/examples/basic.html).

**Comment by marcoscaceres** [comment]
>  The documentation for WebIDL use specifically discusses using @data-link-for to provide scope for references

Yes, that's what is built into the WebIDL module. It does its own linking: 
https://github.com/w3c/respec/blob/develop/src/core/webidl.js#L816

Trying your example in basic.html.

**Comment by marcoscaceres** [comment]
so yeah, something is busted in: 
https://github.com/w3c/respec/blob/develop/js/core/link-to-dfn.js

**Comment by marcoscaceres** [comment]
I won't be able to to get to this for about two weeks, as I'm traveling.

**Comment by gkellogg** [comment]
Ping, this is still biting.

**Comment by marcoscaceres** [comment]
Will try to work on this next. Happy if anyone else wants to pick this up tho.

**Comment by saschanaz** [comment]
@marcoscaceres Suggested fix:

1. Ignore the inner text and only use `data-lt`. An anchor has one single target definition so this should work.
2. Or, support `data-lt-noDefault` for anchors to do exactly same as above but explicitly.

What do you think?

**Comment by marcoscaceres** [comment]
option 1 sounds good.
