### ISSUE TITLE
Line breaks in WebIDL pre sections are ignored/replaced

### ISSUE THREAD

**Issue by royfielding** [w3c/respec#1162]
I am having a hard time rendering an interface that has ridiculously long names:
```
<pre class="idl">
  partial interface Navigator {
    Promise&lt;void&gt; storeSiteSpecificTrackingException (
                    StoreSiteSpecificExceptionPropertyBag properties
                  );
};      
</pre>
```

ReSpec parses the idl and removes the added line breaks, which results in a very long pre section, which is then truncated in mid-name by the W3C stylesheet. Not useful.

A solution would be to keep the embedded line breaks in the post-respec generated HTML. Another solution might be to use something other than pre as a container, such as a horizontally scrollable code block, but that still wouldn't be good for printed copies.

**Comment by marcoscaceres** [comment]
@royfielding, can you try adding "overlarge" as a class and see if it helps?: 

```
<pre class="idl overlarge"> 
```

**Comment by marcoscaceres** [comment]
(You might also think about having shorter names - we usually keep names in the web platform pretty short... `storeSiteSpecificTrackingException()` won't fly and "StoreSiteSpecificExceptionPropertyBag" seems like overkill)

**Comment by royfielding** [comment]
Thanks, overlarge does add a scrolling view for the online page, but the print version is still truncated. I think preserving embedded line breaks would still be preferable, if possible.

Unfortunately, I didn't choose the names. I'll take that advice back to the WG as well, but I figured the issue was worth reporting anyway.

**Comment by marcoscaceres** [comment]
@royfielding, appreciate the report. I'll look at breaking lines correctly when things don't fit. It not something I can fix in the next few weeks, as I'm traveling.

**Comment by marcoscaceres** [comment]
![screen shot 2018-09-16 at 8 15 31 pm](https://user-images.githubusercontent.com/870154/45595337-62285c00-b9ed-11e8-9d2f-f20e64f0b691.png)

Whitespace is respected now by the WebIDL2.js parser.
