### ISSUE TITLE
Saving as HTML includes the save dialog in the resulting HTML

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#1164]
ReSpec => Save => Save as HTML. Open resulting file, see "Save Snapshot" dialog.

**Comment by marcoscaceres** [comment]
I tried locally, but could not reproduce. Could you send me a link to a spec?

**Comment by gkellogg** [comment]
Try https://shexspec.github.io/spec/, save and note the div id="respec-button-save-snapshot-modal" at the end of the saved file. At least it does that using Safari.

**Comment by marcoscaceres** [comment]
thanks! I see it now. Will poke around a bit.

**Comment by marcoscaceres** [comment]
Found it. ... I had:

```HTML
<div class="respec-modal" other="attributes" class="removeOnSave">
```

**Comment by marcoscaceres** [comment]
Travis-CI is acting up a bit... will have to see what's going on tomorrow. But patch is ready and working fine locally.
