### ISSUE TITLE
Example titles incorrectly unescaped

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1173]
Example 46 in the [Spatial Data on the Web Best Practices](http://w3c.github.io/sdw/bp/) specification has a title that includes a `<` character, escaped with `&lt;`. Problem is ReSpec seems to convert that `&lt;` back to a `<` when it generates the actual markup of the example.

The following markup is used:

```html
<pre class="example" title="Discovering links from the &lt;sameAs> service ([N-TRIPLES] format)">
```

It creates the following title (note "sameAs" disappeared): "Example 46: Discovering links from the service ([N-TRIPLES] format)"

Looking at the resulting markup, ReSpec produced a `<sameAs>` tag which obviously does not exist.

**Comment by marcoscaceres** [comment]
So, the right thing to do here is to start treating `title=` as markdown.

**Comment by tidoust** [comment]
Ha! I thought the content of the attribute was supposed to be plain text and that the unescaping was not deliberate. Your comment suggests that it is actually intended. As long as the rule is clear, it works for me!

I don't have anything against markdown but it seems strange to suddenly start using markdown in specs that were otherwise written using markup.

I would propose to update the [example doc page](https://github.com/w3c/respec/wiki/example) to note that the content of the `title` attribute will be treated as markup, and to close this issue. May I do that?

The `<` character would just need to be double-escaped into `&amp;lt;`.

**Comment by marcoscaceres** [comment]
> I don't have anything against markdown but it seems strange to suddenly start using markdown in specs that were otherwise written using markup.

I agree. But a not so great decision was made to abuse the title attribute on things... and this has lead to a bunch of limitations.  

> I would propose to update the example doc page to note that the content of the title attribute will be treated as markup, and to close this issue. May I do that?

Sure, go for it! I don't know exactly when I will add markdown support for title - so it's a good solution for now.

**Comment by tidoust** [comment]
> Sure, go for it! I don't know exactly when I will add markdown support for title - so it's a good solution for now.

OK, I created a separate [`title` attributes](https://github.com/w3c/respec/wiki/title-attributes) doc page and linked to it from the [`ednote`](https://github.com/w3c/respec/wiki/ednote), [`example`](https://github.com/w3c/respec/wiki/example) and [`note`](https://github.com/w3c/respec/wiki/note) pages.
