### ISSUE TITLE
data-cite and multi-pages spec

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#1180]
Is there any way to reference a specific sub-page of a multipage spec using `data-cite`? It would be useful e.g. for HTML5.x.

**Comment by marcoscaceres** [comment]
Had the same problem. See my recently closed bug over at the specref repo. It's automatically done by the HTML spec, but broke the link checker. It's not a ReSpec issue, but I'm unsure how to proceed.

**Comment by dontcallmedom** [comment]
Assuming you're referring to [specref issue 344](https://github.com/tobie/specref/issues/344), it's different from my issue.

What I want is be able to point to e.g. https://www.w3.org/TR/html51/sec-forms.html#the-input-element with `data-cite`.

This could be achieved for instance with `data-cite=!HTML51/sec-forms.html#the-input-element` if respec were to use '/' (or some othre magical separator) as start of an addition parth to the underlying URL (the same way '#' is interpreted).

**Comment by marcoscaceres** [comment]
Using a slash would probably work.
