### ISSUE TITLE
Referencing Tables

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1182]
How does one reference a `table`?

**Comment by marcoscaceres** [comment]
I usually write:

```
<table>
  <caption><dfn>The foo table</dfn></caption>
</table>

<p>As shown in the <a>the foo table</a> ... </p>
```

**Comment by palemieux** [comment]
OK. FYI. This is semantically unexpected (since a table caption is not really a definition), and not specified in the documentation.

**Comment by marcoscaceres** [comment]
Interesting, I'd just assumed that would be semantically fine. I'm open to better suggestions on markup usage.

**Comment by palemieux** [comment]
I would use `id` just like figures:
```
<table id="foo-table">
  <caption><dfn>The foo table</dfn></caption>
</table>

<p>As shown in the <a href='#foo-table'></a> ... </p>
```
