### ISSUE TITLE
Greenkeeper no longer working

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1192]
@dontcallmedom, sorry... seems something happened and Greenkeeper.io is no longer working on this repository? 

Could you click the right buttons from (requires Admin privileges): https://greenkeeper.io

**Comment by dontcallmedom** [comment]
greenkeeper had apparently been installed as an integration (by @tripu or  @deniak I'm guessing?) for @w3c which means that repos now have to be added to the overall configuration for the account - done for this one now.

**Comment by marcoscaceres** [comment]
Thanks @dontcallmedom!
