### ISSUE TITLE
Investigate switching MD parser  to Remarkable

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1207]
https://github.com/jonschlinkert/remarkable

**Comment by jonschlinkert** [comment]
@marcoscaceres I'd be happy to help convert over to remarkable if you want

**Comment by marcoscaceres** [comment]
Oh, that would be awesome, @jonschlinkert! The "magic" happens here:
https://github.com/w3c/respec/blob/develop/src/core/utils.js#L21

And is basically consumed at the following:
 * https://github.com/w3c/respec/blob/develop/src/core/markdown.js#L53
 * https://github.com/w3c/respec/blob/develop/src/core/ui.js#L150

Feel free to ignore this suggestion, but I'd really like to move markdown parsing off main thread to a worker:  
https://github.com/w3c/respec/blob/develop/worker/respec-worker.js

(And we would host the script over on the W3C server)

Which would basically just require turning `markdownToHtml()` to an async function - and `await` on the various call sites:
https://github.com/w3c/respec/blob/develop/src/core/markdown.js#L49

Let me know what you think!

**Comment by jonschlinkert** [comment]
Thanks for the detail! I'll give it a go and see how far I can get, then I'll probably ask some questions. I might need your help/feedback on the worker and where exactly we'll need to use `async`/`await`.

**Comment by jonschlinkert** [comment]
K, I haven't made any changes yet, just pulled everything down, installed deps and ran all three of the test scripts: `test:build`, `test:headless`, and `test:karma`. All tests pass except for the 9th test from `test:headless`.

Just wanted to mention it to have a baseline before I get started.

**Comment by marcoscaceres** [comment]
> I pushed up my work to a branch here in case you have any thoughts/feedback on what needs to be done. thanks

@jonschlinkert, looking good. 

So, my workflow is (multiple console tabs/windows) - apologies if this is self evident already:

```Bash
npm run babel:watch 
```

Start web server: 
```Bash
npm start
```

Then I usually test things in "[examples/basic.html](https://github.com/w3c/respec/blob/develop/examples/basic.html)". 

To enable markdown, add `"format": "markdown"`. You can find details here: 
https://github.com/w3c/respec/wiki/format

But basically, if you add the following and the config option above, you should see it working:
```
    <section>
      ## This is heading
      This is a paragraph, though it is not flush to the left margin.

        * this will be a list item.
        * so will this.
    </section>
```

I have a more detailed [developers guide](https://github.com/w3c/respec/wiki/Developers-Guide
), but hopefully you won't need it. Just explains the architecture a bit.

**Comment by marcoscaceres** [comment]
> All tests pass except for the 9th test from test:headless.

Feel free to ignore that one :)

**Comment by himanish-star** [comment]
I would like to start my work on this

**Comment by himanish-star** [comment]
Starting my work on this! :smiley:

**Comment by marcoscaceres** [comment]
Marked finally got updated to conform with Common Mark and got a bunch of security patches, so we are going to stick with it for now.
