### ISSUE TITLE
Making WebIDL reference normative

### ISSUE THREAD

**Issue by tobie** [w3c/respec#1214]
It seems ReSpec references the WebIDL spec informatively when it uses WebIDL syntax which seems weird. See https://heycam.github.io/webidl/#referencing.

**Comment by marcoscaceres** [comment]
As stated in the link above, a spec author needs to make a normative assertion in the specification that the IDL must be treated as normative: (i.e., there needs to be at least one "[[!WebIDL]]" somewhere in the spec).

When ReSpec sees "[[!WebIDL]]" it automatically treats all references to WebIDL as normative.

**Comment by tobie** [comment]
Well, why doesn't ReSpec handle that for you as soon as you start using WebIDL? Bikeshed does it. It prevents specs like WebRTC only referencING WebIDL informatively.

**Comment by marcoscaceres** [comment]
In a different bug someone complained that they wanted to include IDL non-normatively :(

**Comment by marcoscaceres** [comment]
We could make it a rule that if you have IDL, then too bad - it's normative.

**Comment by tobie** [comment]
So the way Bikeshed handles this is it let's you annotate code blocks as either normative WebIDL or highlighted example code.

**Comment by marcoscaceres** [comment]
Yeah, can do that with `<pre class="example idl">` (but idl is currently not something hljs in ReSpec knows how to deal with)... but that's slightly different.  

I'm of the opinion that we should have it normative by default (it's what I had in the first place... maybe I can just switch it back if it's causing problems).

**Comment by marcoscaceres** [comment]
Our new context-based citation system solves for this automatically.
