### ISSUE TITLE
markdown: Support backticks for webidl

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1217]
Would be nice be able to use triple backticks to denote a WebIDL pre.

**Comment by OrionStar25** [comment]
@marcoscaceres I'd certainly like to work on this! But can you please elaborate a bit more? We need `''' <some WEbIDL pre> ''' ` to show finally onto the doc, right?

**Comment by marcoscaceres** [comment]
@OrionStar25, that would be correct. However, I'm trying to find you something easier. This one has too many dependencies, so might be too challenging if you are just starting out.

**Comment by chaals** [comment]
Seems like however marked.js picks up things marked with <pre>```</pre> doesn't get the language identifier for extra languages added in #1835, either
