### ISSUE TITLE
Github and edDraftURI

### ISSUE THREAD

**Issue by dhvenema** [w3c/respec#1223]
So, github generates the edDraftURI. 

As a user I would expect that when both github and edDraftURI are defined, that the edDraftURI would overwrite the generated github URI. Which it does, so that's good. As a user I would also expect that without github defined and with edDraftURI defined, that edDraftURI would still be present in the header, which is currently not happening.

**Comment by dhvenema** [comment]
Something similar happens with issueBase. When both issueBase and github are defined, I would expect the pre-defined issueBase to be used for both issues created with data-numbers (which it does) and in the participate header section (which it doesn't).

**Comment by marcoscaceres** [comment]
So, at least the edDraftURI issue might be happening in the Geonovum fork:
https://github.com/Geonovum/respec/blob/develop/js/geonovum/templates/headers.html#L29

**Comment by marcoscaceres** [comment]
Talked to dhvenema a bit more. The use case is:

"I have a bug tracker X" but would still like to work on github, but not use GH issues.... so, we need to make `bugTracker` override the issue base and possibly other things.

**Comment by marcoscaceres** [comment]
closing as wont fix, unless it comes up as an issue for some organization.
