### ISSUE TITLE
respec-w3c-common returns "undefined"

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/respec#1225]
Accessing https://www.w3.org/Tools/respec/respec-w3c-common responds with a single lined "undefined" text. Probably something is broken...

**Comment by deniak** [comment]
Yeah, the [build is broken](https://github.com/w3c/respec/blob/develop/builds/respec-w3c-common.js).

**Comment by deniak** [comment]
cc @marcoscaceres

**Comment by marcoscaceres** [comment]
Having a look...

**Comment by marcoscaceres** [comment]
Should be good now.
