### ISSUE TITLE
Dectect when WebIDL overflows

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1237]
Right now, we don't detect when WebIDL overflows. This can be a problem, like in this case:

![screenshot 2017-05-23 15 49 26](https://cloud.githubusercontent.com/assets/870154/26340044/7da7d5c6-3fcf-11e7-9902-c1cfdc6ed1a6.png)
(The SecureContext looks like it's optional!)

When it does, we should set it to "overlarge".

**Comment by saschanaz** [comment]
What do you mean by *set it to "overlarge"*?

**Comment by marcoscaceres** [comment]
In base.css, there is an “overlarge” css class that might help.

**Comment by saschanaz** [comment]
Oh, I see. BTW I see a text wrapping now, is this still an issue?

![image](https://user-images.githubusercontent.com/3396686/35762602-c430af28-08dc-11e8-81cd-424d38286787.png)

**Comment by saschanaz** [comment]
IMO it's probably on purpose, though.

**Comment by marcoscaceres** [comment]
But would it not be best for words in IDL blocks to not break like that? I’d prefer `PaymentOptions` to be on a new line as a single word, and not split.

**Comment by saschanaz** [comment]
Hmm yes, that looks weird.

**Comment by marcoscaceres** [comment]
Leaving this as style issue to be fixed by the w3c.
