### ISSUE TITLE
Timezone affects dates

### ISSUE THREAD

**Issue by sandhawke** [w3c/respec#1256]
publishDate, previousPublishDate, and crEnd (at least) are displaying (and being saved) off by one day. It's set to 2017-06-08 and displays as 20170607.  

Workaround is change system timezone from EST to BST.

Observed in Firefox 53.0.3 and Chromium 58.0.3029.110 on Ubuntu 17.04.

(Amusingly, this comment shows up in github as being made "10 hours from now", now that I've been messing with my system clock and timezone.)

**Comment by marcoscaceres** [comment]
Heh. Sorry about this. I switched to using the system default and `Date.parse()`. But still, it's weird that it's off by one day, as it's just supposed to use the dates gives... date/time is hard.

**Comment by marcoscaceres** [comment]
Oh, wait... those are parsed relative to UTC, which might explain the off by one. I'll poke around and see if the `Intl.DateTimeFormat()` can help. 

Seems one can also do something like: 

```
new Date().toLocaleString("en-US", {timeZone: "America/New_York"})
```

So presumedly, that allows formatting the string as well.

**Comment by marcoscaceres** [comment]
Note to self:

```JS
const w3cDateFormat = new Intl.DateTimeFormat(["en-AU"], {
  year: "numeric",
  month: "long",
  day: "2-digit",
});
```

**Comment by marcoscaceres** [comment]
@sandhawke, you can set real JS date objects for each of those, which will be in your computer's timezone:

```JS
{
  previousPublishDate: new Date("10/10/2010"),
  publishDate: new Date(), // today
  crEnd: new Date().setDate(new Date().getDate() + 91), // in 3 months
}  
```

**Comment by marcoscaceres** [comment]
For "previousPublishDate", you are probably safe using an ISO date string: "2010-11-01" or whatever. But the other two you set them as needed - or set them explicitly through JS. 

I'll leave this open so I remember to update the docs.

**Comment by sandhawke** [comment]
You're saying there's no way for respec to just do the right thing?   This isn't one of those timezone cases that's just weird.  This is simple - the output should be implicitly in whatever timezone the input is considered to be in, so it doesn't matter what zone that is.   It just has to be the same.    Right?

**Comment by marcoscaceres** [comment]
> On 8 Jun 2017, at 8:33 pm, Sandro Hawke <notifications@github.com> wrote:
> 
> You're saying there's no way for respec to just do the right thing?
> 

There is, but I'm just suggesting a quick fix for you. 

> This isn't one of those timezone cases that's just weird. This is simple - the output should be implicitly in whatever timezone the input is considered to be in, so it doesn't matter what zone that is. It just has to be the same. Right?
> 

Yes, but right now it's using UTC because I'm using the Date.parse(). It's not difficult to fix, but I need to find a spare hour to fix it. I usually try to do bug fixes if I'm bored on the weekend or if it's directly affecting a spec I work on. 

If you want to have a go at fixing it, search for "humanDate" in src/core/utils.js.
