### ISSUE TITLE
Custom logos broken?

### ISSUE THREAD

**Issue by ldodds** [w3c/respec#1281]
I've got a specification [here](https://github.com/openactive/modelling-opportunity-data/blob/master/EditorsDraft/index.html) that relies on a custom logo. It's been working OK (there's a previously built version [here](https://www.openactive.io/modelling-opportunity-data/EditorsDraft/).

But I'm currently making local revisions and finding that the logo is now displaying like this:

![screenshot from 2017-06-20 11-01-26](https://user-images.githubusercontent.com/109082/27327937-1fe15b6c-55a8-11e7-9606-0af3aa7edcc4.png)

The generated HTML is correct, but its being added to the document as text, rather than an element.

**Comment by marcoscaceres** [comment]
Oh, sorry about that. I think I forgot to update the CG template in a recent update. I'll fix it later today or first thing tomorrow.

**Comment by ldodds** [comment]
That would be great, I need to publish 4 updated draft documents from our CG today or tomorrow

**Comment by marcoscaceres** [comment]
fix incoming... just waiting for TravisCI to finish
