### ISSUE TITLE
Example titles display incorrectly

### ISSUE THREAD

**Issue by ldodds** [w3c/respec#1282]
The examples in our CG specification originally looked liked this:

![screenshot from 2017-06-20 11-21-55](https://user-images.githubusercontent.com/109082/27328673-d64519be-55aa-11e7-9293-fddb0ec91a94.png)

In the latest respec they're displaying as follows:

![screenshot from 2017-06-20 11-22-12](https://user-images.githubusercontent.com/109082/27328681-e080493a-55aa-11e7-9370-73cbdae9aa85.png)

It looks like the markup has changed from wrapping the titles in a span element, to a paragraph that wraps a span.

**Comment by ldodds** [comment]
This is the markup that I get now:

```
<div class="example-title marker"><span>Example 5</span><p><span style="text-transform: none">: Specifying activities</span></p></div>
```

**Comment by marcoscaceres** [comment]
Ah, that's a missing css rule. Will fix in tge next 24 hours.

**Comment by marcoscaceres** [comment]
@ldodds, do you have a link to the spec that is being affected?

**Comment by ldodds** [comment]
Yes, source is here: https://github.com/openactive/modelling-opportunity-data/blob/master/EditorsDraft/index.html

**Comment by marcoscaceres** [comment]
@ldodds, I've not been able to reproduce the above. Can you check again for me in ReSpec 14.0.10 that I just released? (you can check the version by clicking on the ReSpec pill => About ReSpec)

**Comment by ldodds** [comment]
@marcoscaceres I've just done a hard refresh and the issue seems to be resolved. All displaying fine now (and the logo!).

Thanks for quick turn around.

**Comment by marcoscaceres** [comment]
No problem. Sorry my oversight on the CG logos. Will make sure to add a test for that.
