### ISSUE TITLE
Breaking Change: Preface / Editors / Boilerplate / etc section missing

### ISSUE THREAD

**Issue by awoods** [w3c/respec#1290]
As of https://github.com/w3c/respec/commit/7e28f119062b0fdd4f0fc50299d2dbdb7e69962e the prefatory information is missing.

Was this change intentional? If not, it appears to be a critical bug... or are there release notes that I am missing?

**Comment by marcoscaceres** [comment]
Do you have a link to the spec being affected? Not intentional.

**Comment by awoods** [comment]
http://fedora.info/spec/

**Comment by marcoscaceres** [comment]
@awoods, thanks! Will get that fixed for you.

**Comment by marcoscaceres** [comment]
Ok, PR incoming... it was crashing because of missing `alt:` attribute on the logo :) You might want to add a `alt`, `width`, and `height`. 

Also, I guess you don't want the w3c logo if it's unofficial, right?

**Comment by awoods** [comment]
Thanks, I will update the logo. As for the w3c... either way is fine.

**Comment by marcoscaceres** [comment]
I'm sending a separate PR for making the w3c logo go away. 

Just waiting for TravisCI.... SOOO SLLLOOOWW TODAY!!!!!

**Comment by awoods** [comment]
Thanks for the help with this, @marcoscaceres .
Do you have any idea why the `title` is now squished off to the left?
http://fedora.info/spec/

**Comment by marcoscaceres** [comment]
I think it's just that the fedora logo is a bit too large. We designed the template to only accommodate small logos. Try setting the logo to around 70px in height.

**Comment by awoods** [comment]
Much better.
http://fedora.info/spec/
Thanks again, @marcoscaceres .
