### ISSUE TITLE
Respec not working today

### ISSUE THREAD

**Issue by michael-oneill** [w3c/respec#1294]
The Respec library seems to have a bug today. On Chrome https://w3c.github.io/dnt/drafts/tracking-dnt.html shows a blank screen, on Firefox it does not show the Title or the TOC column.

**Comment by marcoscaceres** [comment]
@michael-oneill, trying to get it going again.

**Comment by marcoscaceres** [comment]
Fix inbound https://github.com/w3c/respec/pull/1296 ... just waiting for tests to finish.

**Comment by marcoscaceres** [comment]
... and we are back!

**Comment by michael-oneill** [comment]
Yay!
