### ISSUE TITLE
IDL parser doesn't seem to like record<K, V>

### ISSUE THREAD

**Issue by beverloo** [w3c/respec#1297]
Basically, when I add the following snipped to a `<pre class="idl">` block the parser seems to stop working:

```idl
dictionary PushSubscriptionJSON {
    record<DOMString, USVString> keys;
}
```

No related information is shared in the error or warning bubbles, but a console error is observed (which admittedly isn't very useful either):

```
regenerator.js:498 TypeError: Cannot read property 'nullable' of undefined
    at f (regenerator.js:498)
    at f (regenerator.js:498)
    at f (regenerator.js:498)
    at regenerator.js:498
    at Array.forEach (<anonymous>)
    at x (regenerator.js:498)
    at regenerator.js:498
    at Array.map (<anonymous>)
    at w (regenerator.js:498)
    at HTMLPreElement.<anonymous> (regenerator.js:498)
```

I'll use @tobie's `pr-preview` integration to get an example illustrating this...

**Comment by beverloo** [comment]
See:
https://github.com/w3c/push-api/pull/269
https://s3.amazonaws.com/pr-preview/beverloo/push-api/record-fix.html#pushsubscription-interface

**Comment by marcoscaceres** [comment]
Thanks! will take a look soon at what's going on.
