### ISSUE TITLE
Spec rendering borked in Edge due to unwrapped "querySelectorAll" calls

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1313]
Edge does not support `forEach` on the structure returned by `querySelectorAll`. These calls need to be wrapped into `Array.from` calls. That's basically done throughout ReSpec code... except:

- in [`src/core/id-headers.js`](https://github.com/w3c/respec/blob/develop/src/core/id-headers.js#L8), because of a [recent change](https://github.com/w3c/respec/commit/c1a7be5890bd8b136418609074dec86cd2e75e8b)
- in [`src/core/utils.js` L291](https://github.com/w3c/respec/blob/develop/src/core/utils.js#L291) because of another [recent change](https://github.com/w3c/respec/commit/81188a8862f96af0b7dcb5de0314768d8f1b7d22) which seems to have dropped the call to `Array.from` on purpose...

The first one breaks the rendering of ReSpec specs in Edge right now, as far as I can tell.

**Comment by marcoscaceres** [comment]
Thanks, fixing...
