### ISSUE TITLE
Respec License

### ISSUE THREAD

**Issue by awoods** [w3c/respec#1317]
I am not seeing a license file or statement on respec. Can you clarify which license applies to this software?

**Comment by marcoscaceres** [comment]
https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document


I'll add an explicit license file. It's currently in the package.json

**Comment by awoods** [comment]
Thanks, @marcoscaceres .
Please feel free to close this issue after a license file has been added.

As a side note, the reason I brought up this issue is because we are now trying to insulate our site/specification from potential changes and breakage caused by referencing the bleeding-edge of respec. We are now serving a local copy and wanted to make sure that that was within the terms of the license.

**Comment by marcoscaceres** [comment]
Should be fine. I'm going to see if I can move ReSpec to a C0 license in the next few months. 

Let me know if you need help setting up a custom profile and tests for your project.

**Comment by awoods** [comment]
Thanks, @marcoscaceres . 

Is your comment about "custom profile and tests" related to the current issue, or https://github.com/w3c/respec/issues/1301 ?

In any case, if you have pointers on how to set up such a profile and tests, I would be interested to explore.

**Comment by marcoscaceres** [comment]
Sorry for the delay, was on vacation
>Is your comment about "custom profile and tests" related to the current issue, or #1301 ?

#1301 I would say. 

> In any case, if you have pointers on how to set up such a profile and tests, I would be interested to explore.

Added some info about custom profiles and testing here:
https://github.com/w3c/respec/wiki/Developers-Guide#custom-profiles

Here is an example of another org using a custom profile:
https://github.com/Geonovum/respec/blob/develop/js/profile-geonovum.js
