### ISSUE TITLE
Warn when href points to undefined id

### ISSUE THREAD

**Issue by futpib** [w3c/respec#1318]
Wouldn't it be super nice if respec warned you when you have an `a[href="#that"]` but no `[id="that"]`? Or maybe I'm not doing referencing right and there is a feature for that (instead of defining `id` attribute explicitly)?

I find it very helpful that respec highlights links like `<a>Something</a>` when there is no `<dfn>Something</dfn>` in the document. Similarly, I wish it highlighted `<a href="#that">...</a>` when there is no `<anything id="that">...</anything>` in the document too!

**Comment by futpib** [comment]
Oh and I'm willing to submit a PR for this, so please let me know if it's desirable.

**Comment by marcoscaceres** [comment]
> Wouldn't it be super nice if respec warned you when you have an a[href="#that"] but no [id="that"]? Or maybe I'm not doing referencing right and there is a feature for that (instead of defining id attribute explicitly)?

**In theory**, you shouldn't need the above, as all referencing is done via `<a data-lt="whatevs">thing</a>` or just `<a>whatevs</a>`. 

**In practice**, however, it might be useful so would certainly welcome a PR (maybe a linter rule?). However, what would be more useful, is the reverse: situations where `dfn` is defined in a document but never used: https://github.com/w3c/respec/issues/904

**Comment by sidvishnoi** [comment]
Closed in favour of https://github.com/w3c/respec/issues/1643 via https://github.com/w3c/respec/pull/1664
