### ISSUE TITLE
No translations link?

### ISSUE THREAD

**Issue by sandhawke** [w3c/respec#1323]
[Pubrules](https://www.w3.org/pubrules/doc/rules?profile=REC) says:

> 
> There must be a link to a translations page. The recommended markup is:
> 
> <p>See also &lt;a href=" http://www.w3.org/2003/03/Translations/byTechnology?technology=shortname"> &lt;strong>translations&lt;/strong>&lt;/a>.&lt;/p> 

Not hard to add by hand, but I'm surprised respec doesn't do it.

**Comment by marcoscaceres** [comment]
Good catch... just sent a PR
