### ISSUE TITLE
Investigate automatic pluralization of defined terms

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1351]
Would be nice to not have to do `<dfn data-lt="things">thing</dfn>` in specs. 

https://github.com/blakeembrey/pluralize

**Comment by vinicius0197** [comment]
Hi @marcoscaceres , I want to work on this bug. Not really sure how to use this `href-less `element that is mentioned [here](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#user-content-definitions-and-linking), though (I imagine that this is the purpose of pluralizing things here). 

I would like to test some examples to try to come up with a solution.

**Comment by marcoscaceres** [comment]
@vinicius0197, thanks for offering to help with this. Unfortunately, I won't be able to provide much help until after the Google Summer of Code stuff is done (few more weeks). 

However, you should poke around: 
https://github.com/w3c/respec/blob/develop/src/core/dfn.js

basically, given a defined concept `<dfn>apple</dfn>`, the pluralize library (above) should give you "apples", so the output should be:
```HTML 
  <dfn data-lt="apples">apple</dfn>
````

And then: 

```HTML
I love  <a>apples</a>.
```

Should link correctly to the definition. 

However, WebIDL defined things should not be pluralized (obviously)! 

Hope that's enough to go on.

**Comment by vinicius0197** [comment]
All right, thanks!

Don't want to bother you much (and if anyone else can give me just some hints, I will be grateful). I wanted to run https://github.com/w3c/respec/blob/develop/src/core/dfn.js and step through the code. My initial approach was just to `npm start` and navigate to a simple example file and try to use developer tools to put some breakpoints in there. I refreshed the page then, but that didn't work (passed straight through all my breakpoints in `dfn.js` , so I suspect this isn't the correct way to do this).

Is there a way that I can run this piece of code and debug it?

**Comment by marcoscaceres** [comment]
@vinicius0197 hopefully [these instructions help](https://github.com/w3c/respec/wiki/Developers-Guide#super-fast-get-up-and-running). I think you are just missing the transpile step for babel, which is why your breakpoints are not showing up... otherwise, it's the browser cache - make sure you disable it from your developer tools.

As of yesterday, I'v added the transpile step to `npm start` - but it's better to have babel watch for changes, so you don't need to keep shutting down the web server all the time as you develop.
