### ISSUE TITLE
Expand <a data-cite></a>

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1352]
Be cute if given an empty:

```HTML
<a data-cite="payment-request"></a>
```

It would expand to:
```HTML
<a href="the url">Payment Request API</a>
```

That would auto handle specs being renamed, etc.

**Comment by marcoscaceres** [comment]
Actually, cooler would be [[[FOO]]] expands out.

**Comment by shikhar-scs** [comment]
@marcoscaceres If you could be a bit more clear, I would like to work on this :sweat_smile:

**Comment by OrionStar25** [comment]
@marcoscaceres I'd like to work on this one, please!

**Comment by goelrohan6** [comment]
@marcoscaceres how do we generate the url for the element ?
can you brief me more with the flow and also point me to the file in which the hack has to be made.
and also can you tell where can I play along with data-cite and see changes?

**Comment by pradeepgangwar** [comment]
@marcoscaceres I would like to work on this.
