### ISSUE TITLE
How to define a method in a partial interface? 

### ISSUE THREAD

**Issue by siusin** [w3c/respec#1356]
We received a warning in the Beacon spec that there is no `<dfn>` for sendBeacon in Navigator,
 see [#47](https://github.com/w3c/beacon/issues/47).

We would like to fix this bug, but the [suggested method ](https://github.com/w3c/respec/wiki/WebIDL-thing-is-not-defined) doesn't really apply to the partial interface `Navigator` here.

Is there a good way to define a `Method()` when the definition of the interface is not in the same spec?

Thanks!

**Comment by marcoscaceres** [comment]
I've tried to fix the documentation to be more clear.

**Comment by siusin** [comment]
Thanks!

**Comment by marcoscaceres** [comment]
I think we solved this, so closing. As always, if you have any suggestions for improving things, let me know!

**Comment by siusin** [comment]
Thank you for looking into this!
