### ISSUE TITLE
RangeError: date value is not finite in DateTimeFormat.format()

### ISSUE THREAD

**Issue by xfq** [w3c/respec#1357]
Spec: https://w3c.github.io/html-media-capture/?specStatus=CR;previousMaturity=CR;previousPublishDate=2017-05-04/;crEnd=2017-06-27;publishDate=2017-08-24

Web Console in Firefox DevTools emits the following error:

```
RangeError: date value is not finite in DateTimeFormat.format()
Stack trace:
e.concatDate@https://www.w3.org/Tools/respec/respec-w3c-common:1:63216
e.run@https://www.w3.org/Tools/respec/respec-w3c-common:1:357180
i/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:67755
n@https://www.w3.org/Tools/respec/respec-w3c-common:1:32665
l/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:33784
o/</e[t]@https://www.w3.org/Tools/respec/respec-w3c-common:1:32841
r@https://www.w3.org/Tools/respec/respec-w3c-common:1:67094
i/</<@https://www.w3.org/Tools/respec/respec-w3c-common:1:67245
i/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:67042
a/</</<@https://www.w3.org/Tools/respec/respec-w3c-common:1:68065
a/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:67362
e/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:68680
n@https://www.w3.org/Tools/respec/respec-w3c-common:1:32665
l/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:33784
o/</e[t]@https://www.w3.org/Tools/respec/respec-w3c-common:1:32841
r@https://www.w3.org/Tools/respec/respec-w3c-common:1:67094
r/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:67198
  respec-w3c-common:1:68755

Linter (no-headingless-sections): All sections must start with a `h2-6` element. <section id="sotd" class="respec-offending-element">  respec-w3c-common:1:180109

All sections must start with a `h2-6` element. Add a `h2-6` to the offending section or use a `<div>`. See developer console. ("no-headingless-sections" x 1)  respec-w3c-common:1:32456
```

-----

* Firefox version: 54.0.1 (64-bit)
* OS: macOS 10.12.6

**Comment by marcoscaceres** [comment]
The "/" after 04 in previousPublishedDate seems to cause the error (as it makes the date malformed). 

Try: 
https://w3c.github.io/html-media-capture/?specStatus=CR;previousMaturity=CR;previousPublishDate=2017-05-04;crEnd=2017-06-27;publishDate=2017-08-24

**Comment by marcoscaceres** [comment]
Working on a patch to gracefully handle the errors, and have ReSpec yell about invalid dates.

**Comment by xfq** [comment]
I see. Thanks for the hint!

**Comment by zeshhaan** [comment]
Safari doesn't support `-` date separator and instead it looks for `/` separator so you can simply add a regex to swap that at the end like this:

```javascript
console.log (new Date('2011-04-12'.replace(/-/g, "/")));
```

**Comment by realstoman** [comment]
Had the same issue and this solved it for me. Thank you @zeshhaan 

> Safari doesn't support `-` date separator and instead, it looks for `/` separator so you can simply add a regex to swap that at the end like this:
> 
> ```js
> console.log (new Date('2011-04-12'.replace(/-/g, "/")));
> ```
