### ISSUE TITLE
Integrate reffy support

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1360]
See: 
https://github.com/tidoust/reffy

would be nice to have it as a linter module.

**Comment by marcoscaceres** [comment]
Will need @tidoust and @dontcallmedom to help me figure out the details. Maybe we can chat about how I could add support at TPAC?

**Comment by tidoust** [comment]
Very happy to discuss that, @marcoscaceres! @dontcallmedom and I will both be at TPAC. I'll try to flesh out some thoughts on ways to do that by then.

**Comment by marcoscaceres** [comment]
Should I be installing Reffy on https://respec.org (it's currently down, don't bother clicking on that link)? or is there a REST interface available somewhere else? I guess I will still need to interface with Reffy from respec.org as to not leak the API key. 

Otherwise, I would need to bake a W3C API key into ReSpec, but that makes it easy for anyone to steal.

**Comment by marcoscaceres** [comment]
I guess we have this via xref now...
