### ISSUE TITLE
Reuse cb() for requestIdleCallback

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1363]
ReSpec modules sometimes have a `cb()` that is currently a no-op... we could basically repurpose the `cb()` to create a `requestIdleCallback()` queue for super low priority stuff.  

```js
export async function run(conf, doc, cb) {
  doSyncStuff();
  // do this stuff when you get spare cycles
  cb(async ()=>{
     // Super low priority ... run after `respecIsReady`
   });
}
```

**Comment by himanish-star** [comment]
@marcoscaceres, I would like to work on this issue. May I ?

**Comment by marcoscaceres** [comment]
Sure, but we need to identify some potential candidates that would make use of this. What would be nice little wins?

**Comment by himanish-star** [comment]
> Sure, but we need to identify some potential candidates that would make use of this

Actually I haven't actually gone into depth in this issue. I am a new contributor to this repo and this issue really caught my interest and I think that I can manage to get this fixed but with some time in hand. It would be really nice if you could guide me a bit regarding this issue. In the meantime I am trying to get familiar with the code

**Comment by marcoscaceres** [comment]
@himanish-star this one might be a bit hard to start with, as it indeed requires understanding subtle behavior in ReSpec (lots of things depend on each other, so if they fall out of sync, things breaks). I'll message you about the issues  you enquired about.

**Comment by himanish-star** [comment]
@marcoscaceres, ya I realized this later on. But can I work on this as a long term issue while at the same time solving other issues which are relatively simpler. Maybe after working on this repo for a week I can start understanding things better

**Comment by marcoscaceres** [comment]
I’ve decided this will make things more complicated
