### ISSUE TITLE
Override logo just adds another logo to the document

### ISSUE THREAD

**Issue by herrjemand** [w3c/respec#1367]
Hey guys, I am trying to override W3C logo with our own logo, but it seems to just add this logo next to ours.

<img width="859" alt="screenshot 2017-08-18 12 26 52" src="https://user-images.githubusercontent.com/1636116/29457124-8c163e60-8410-11e7-9927-389fe7e24636.png">

How do I set it to non-w3c mode anyway?

**Comment by marcoscaceres** [comment]
@herrjemand as this particular profile is set up for W3C specs, I think it always injects the logo and a bunch of things tagged with "W3C" (e..g, above it says "W3C Working Draft",  and it injects the w3c styles for W3C Working Draft, and so on). 

If you want a profile of ReSpec without all the w3c stuff (i.e., a Fido Alliance Profile), you will need to make a custom profile ([small guide](https://github.com/w3c/respec/wiki/Developers-Guide#custom-profiles)). Here is an example of another standards org that's done that (note all the w3c stuff that's disabled):
https://github.com/Geonovum/respec/blob/develop/js/profile-geonovum.js

I'm happy to help you with that, but need to understand what you are trying achieve.

**Comment by TakashiSasaki** [comment]
I added `STYLE `element inside `HEAD `element to hide W3C logo.
It's workaround.
`    <style>
       a.logo {
         display: none
      }
    </style>`

**Comment by marcoscaceres** [comment]
@TakashiSasaki, problem is that you will still end up with W3C stuff - specially if I change things in the profile.

@herrjemand let me know if you have further questions about custom profiles. If you need guidance getting one set up, give me shout here.  Happy to help!
