### ISSUE TITLE
Parenthesis on method dfn-tags when method names are reused across interfaces

### ISSUE THREAD

**Issue by adam-be** [w3c/respec#1369]
I borrowed the snippet below from the docs. If `url` is an attribute, as in the docs example, it work OK. But if `url`is a method, the second definition will be lost and a warning is generated. It works if I add parenthesis to both definitions (`<dfn>url()</dfn>`). Is that required or is this a bug?

```
<section data-dfn-for="Request">
  <p>The <dfn>url</dfn> of <a>Request</a>...</p>
</section>

<section data-dfn-for="Response">
  <p>The <dfn>url</dfn> of <a>Response</a>...</p>
</section>
```

**Comment by marcoscaceres** [comment]
Odd, i can't reproduce the error. I adapted the example in the doc, but it all still links correctly:

```HTML 
<section data-dfn-for="ExampleInterface" data-link-for="ExampleInterface">
  <h2><dfn>ExampleInterface</dfn> interface</h2>
  <pre class="idl">
  interface ExampleInterface {
    void exampleMethod();
    readonly attribute USVString url;
  };
  </pre>
  <section>
    <h3><dfn>exampleMethod()</dfn> method</h3>
    <p>Describe <a>exampleMethod()</a> here...</p>
  </section>
  <section>
    <h3><dfn>url</dfn> attribute</h3>
    <p>Describe the <a>url</a> attribute here...</p>
  </section>
</section>
```

**Comment by marcoscaceres** [comment]
Here is the rendered output of the above, showing the linking: 

![screenshot 2017-08-23 11 08 55](https://user-images.githubusercontent.com/870154/29594400-fd41a656-87f3-11e7-95b5-973eb6690002.png)

@adam-be if you have a more complete document, I can take a look. Maybe add it as a gist or on JS Bin?

**Comment by adam-be** [comment]
Sorry, my description was a bit unclear. I get the warning when *both* defines represents methods with the same name.

See: https://jsbin.com/xuvereyutu/edit?html,output

Strangely enough, the error disappears if I use a non-camel case name for the method.

**Comment by marcoscaceres** [comment]
This works ok tho: https://jsbin.com/lequloloye/1/edit?html,output

(just a adding "()" to the method names... that's the preferred way). But them not lining correctly is when missing "()" is a bug.

**Comment by adam-be** [comment]
Thanks for verifying. I'm currently using parenthesis, and it works fine.

**Comment by saschanaz** [comment]
Can't reproduce anymore via https://jsbin.com/xuvereyutu/edit?html,output. Please reopen if I'm wrong.
