### ISSUE TITLE
Use defined terms list for autolinks in WebIDL when available

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#1372]
ReSpec kindly links to terms it magically knows in WebIDL fragments. But given that (for better or for worse), there are different versions of different specs that can be used as references for some of these terms, it would be best if it would use instead terms that the spec itself defines and references when it does.

e.g. if a spec uses `[CEReactions]` but doesn't define it, then it would use the current default link.

if a spec does `<dfn data-cite="!custom-elements#CEReactions">[CEReactions]</dfn>`, then the WebIDL fragment should link to that `dfn` (or maybe to the link it creates, I'm not sure).

**Comment by dontcallmedom** [comment]
(otherwise, this creates issues such as #1105 where informative references that duplicate normative ones are created)

**Comment by marcoscaceres** [comment]
Yeah :( custom-elements at least, is not great example... as I think (WHATWG) HTML now owns custom elements.

**Comment by dontcallmedom** [comment]
without getting into sadly political considerations, there are any number of other examples that way with DOM, HTML, or even different level/version of a given spec, so I think the feature would be useful in many cases.

**Comment by marcoscaceres** [comment]
I'm happy to revise the list, or we could provide some kind of override.

**Comment by dontcallmedom** [comment]
override is what I was suggesting - i.e. if the term is cite-defined in the spec, use that definition rather than the default one.

**Comment by marcoscaceres** [comment]
I quite like that idea. Should definitely be doable.
