### ISSUE TITLE
Github links should include link to pull requests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1373]
I keep having to click on the issues link to get to the pull requests... it's getting a little boring.

**Comment by OrionStar25** [comment]
Hey, I'd like to work on this issue! Can you please elaborate a bit more though?

**Comment by marcoscaceres** [comment]
@OrionStar25 that's great, and should be pretty easy. 

See the screenshot below of what is actually needed:

![screenshot_2018-02-08_13_19_00](https://user-images.githubusercontent.com/870154/35952160-d0ddb488-0cd2-11e8-8aaf-17a42f14cb80.png)

You basically just need to add one of these objects here:
https://github.com/w3c/respec/blob/develop/src/core/github.js#L117

And add the localization string in English here:
https://github.com/w3c/respec/blob/develop/src/core/l10n.js#L19

And then add a test to check that the value showed up in "tests/spec/core/github-spec.js".

**Comment by marcoscaceres** [comment]
@OrionStar25, if you haven't already, please also see the get started guide for devs https://github.com/w3c/respec/wiki/Developers-Guide

**Comment by OrionStar25** [comment]
Sent a pr 👍
