### ISSUE TITLE
💅-up linked tests  

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1374]
Given that tests names themselves contain details about what kinds of tests they are, we can use that information to make the tests a bit nicer. 

 * [ ] requires secure connection 🔒
 * [ ] manual tests 💪
 * [ ] automated test 🤖

so, it would be like:  manual test (💪),  requires secure connection (🔒) test-name. 

And we can drop the .html part.

**Comment by shikhar-scs** [comment]
If this issue is still up @marcoscaceres may I work on it ?

**Comment by marcoscaceres** [comment]
Sure is! Absolutely, you can take it. Take a look at: https://w3c.github.io/payment-request/

And search for “tests”. You will see what I mean there. There is lots we could do.

**Comment by shikhar-scs** [comment]
Do you intend to say this


![hhiih](https://user-images.githubusercontent.com/25258877/35802841-b2c09598-0a97-11e8-9385-691ca3b94255.gif)

**Comment by marcoscaceres** [comment]
Yep, exactly those.

**Comment by shikhar-scs** [comment]
So, I'll get working with that. Meanwhile could you tell me how to access the specific tags (requires secure connection lock,  manual tests muscle, automated test robot) and all?

**Comment by marcoscaceres** [comment]
Please see the developer guide: https://github.com/w3c/respec/wiki/Developers-Guide

Will send details tomorrow as to where the actual code is. However, it be good to discuss a proposal and do some mock-ups before coding anything. This is mostly UI work, so want to make sure we see something nice/usable before we start coding.

**Comment by shikhar-scs** [comment]
> This is mostly UI work, so want to make sure we see something nice/usable before we start coding.

Sure thing :+1: 

> Will send details tomorrow as to where the actual code is.

I'll try and find them on my own else lookout for it tomorrow :smiley:

**Comment by shikhar-scs** [comment]
@marcoscaceres If you could help here a bit :smile:

**Comment by marcoscaceres** [comment]
Yeah, ping me on IRC.

**Comment by shikhar-scs** [comment]
Sure :+1:

**Comment by marcoscaceres** [comment]
@shikhar-scs, code is here:
https://github.com/w3c/respec/blob/develop/src/core/data-tests.js

The documentation for usage is here:
https://github.com/w3c/respec/wiki/data-tests

The tests for it are here:
https://github.com/w3c/respec/blob/develop/tests/spec/core/data-tests-spec.js

**Comment by shikhar-scs** [comment]
Thanks for that, I'll follow it up soon.

**Comment by marcoscaceres** [comment]
ok, but please run your ideas by me as you go. We are going to try to align with BikeShed, as they are doing something very similar: https://github.com/tabatkins/bikeshed/issues/1116

**Comment by shikhar-scs** [comment]
Sure! Btw, on your name has been missing on IRC at #spec channel

**Comment by marcoscaceres** [comment]
Sorry, went to the gym 💪 My timezone is GMT+10 (Melbourne, Australia).

**Comment by shikhar-scs** [comment]
@marcoscaceres No problem at all. I very easily understand the code now. 

However, I have a doubt. Whenever I make changes to the `href` logic below, it does not reflect on the basic.html file 
https://github.com/w3c/respec/blob/34822ee20dcbbf186e81d9bfbccd66dc3d51913e/src/core/data-tests.js#L25-L31

we can do away with the `.html` part here itself. Also, where can I access the tags related to a test ?

**Comment by marcoscaceres** [comment]
Ah, about it not reflecting, did you do?: 

```
npm run babel:watch
```

That will compile the code for you. I'm around for the next 6 hours or so on IRC. Ping me on there and we can get you up and running.

**Comment by shikhar-scs** [comment]
Oops! completely forgot about that. Thanks for reminding. 
I have college a bit earlier today, so I wont be around that much for a couple of hours. I'll catch up in a while. Thankyou for your help :bowing_man:

**Comment by shikhar-scs** [comment]
@marcoscaceres Can you please tell me again where can I get the tags related to a test ?

**Comment by marcoscaceres** [comment]
@shikhar-scs, I'm not exactly sure what you mean by tags? Can you clarify?

**Comment by shikhar-scs** [comment]
> so, it would be like: manual test (muscle), requires secure connection (lock) test-name.

These

**Comment by shikhar-scs** [comment]
@marcoscaceres As of now, we have this (I have zoomed in for a better view)

![heheheheehehe](https://user-images.githubusercontent.com/25258877/35903544-a905c69e-0c05-11e8-9560-6baf42d63c5c.png)

To prettify it further, we should also remove the dashes I guess. Please review

**Comment by marcoscaceres** [comment]
Looking good, @shikhar-scs.

**Comment by shikhar-scs** [comment]
Should I file a PR for the same ??
