### ISSUE TITLE
Test suite linter should check if test files exist

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1381]
We currently have the ability to add `data-tests` to elements. However, tests often get moved around or deleted... we should have a linter rule that checks that tests actually exist. This requires using the GitHub API to check the Web Platform Tests repository for the existence of the test files. 

Unfortunately, because of quota restrictions, this needs to done through a proxy (i.e., respec.org) ... so we need to query the wpt via GitHub's API through there.

**Comment by sidvishnoi** [comment]
I'll be looking into using GitHub API v4 integration at respec.org this weekend.

**Comment by sidvishnoi** [comment]
@marcoscaceres  Duplicate of https://github.com/w3c/respec/issues/1596?

**Comment by marcoscaceres** [comment]
Duplicate indeed.
