### ISSUE TITLE
marked stripping "*" from pre

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1389]
Given: 
```HTML
<pre class="example">
1 * 2 * 3;
</pre>
```

marked  is stripping the "*" - it converts to `<em>`

**Comment by marcoscaceres** [comment]
Affected spec: https://w3c.github.io/requestidlecallback/

**Comment by OrionStar25** [comment]
Does the spec still have that issue? I can see the "*" in it though.

**Comment by marcoscaceres** [comment]
@OrionStar25, thanks for reminding me, we found a work around for it (using back ticks on *, as shown below):

```markdown
var x = Math.random() `*` r `*` 2 - r;
```

**Comment by marcoscaceres** [comment]
I'm not sure if we should do anything here. I've documented the workaround here: https://github.com/w3c/respec/wiki/format
