### ISSUE TITLE
No longer possible to override W3C logo in an official document?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1392]
From time to time, W3C working groups develop specs in collaboration with external organizations. In such cases, we need to add another logo next to the W3C one. Specs developed by the Spatial Data on the Web (SDW) Working Group, a joint W3C/OGC effort, provide a concrete example, e.g. the [SSN Ontology](https://w3c.github.io/sdw/ssn/)

To add the OGC logo, the config uses the `logos` setting to [override the standard W3C logo](https://github.com/w3c/respec/wiki/logos), and specifies both the W3C and the OGC logo. This used to work fine, at least until a few months ago, I don't remember what update made behavior change.

However, the [code in headers.html](https://github.com/w3c/respec/blob/ad4a19af0b8b64e9e8af8582a45bc0d806a85f16/js/w3c/templates/headers.html) now adds the W3C logo unless the document is flagged as "unofficial". The SDW WG specs are not "unofficial".

The W3C logo is not overridden and appears duplicated as a result. Duplication is easy to fix: dropping the W3C logo from ReSpec config would do the trick. But then, ideally, I'd like the two logos to appear side by side within the same `<p>`.

**Comment by saschanaz** [comment]
Note that `node ./tools/respec2html.js -e --src https://w3c.github.io/sdw/ssn/ --timeout 30 --out abc.html` also generates wrong logo buttons with empty `href` attributes.
