### ISSUE TITLE
case-insensitive sorting of references

### ISSUE THREAD

**Issue by mattgarrish** [w3c/respec#1396]
I've noticed that spec references that begin with a capital letter sort before those with a lowercase letter.

In general this is not a problem as we've tried to use lowercase references in the [Web Pub spec](https://w3c.github.io/wpub/#references), but if you look at the normative section, RFC2119 appears first because it is auto-inserted.

Ideally it would be nice if sorting was case-insensitive.

**Comment by marcoscaceres** [comment]
So, we probably want:

```JS
refs.sort((a,b) => a.toLowerCase().localeCompare(b.toLowerCase());
```

here:
https://github.com/w3c/respec/blob/develop/src/core/biblio.js#L147

**Comment by marcoscaceres** [comment]
I’ll try to do a release later today or tomorrow.

**Comment by mattgarrish** [comment]
Thanks!
