### ISSUE TITLE
ReSpec not updating on w3c server?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1401]
@dontcallmedom - for some reason, ReSpec is not updating on W3C server (stuck at 17.0.0, should be 17.1.1):

https://www.w3.org/Tools/respec/respec-w3c-common

Could you please take a look on the w3c end? I don't think I've changed anything on the github side to make it stop publishing. I also checked the gh-pages branch, and it's also at 17.1.1.

**Comment by dontcallmedom** [comment]
fixed - paging @tripu on this since the problem was linked to his related script to update webidl2.js.

**Comment by marcoscaceres** [comment]
@tripu, eh? I should have guessed! Looking forward to see you all at TPAC! 🍻😺

**Comment by tripu** [comment]
:sweat:

(I won't be at TPAC this year&hellip; :confused:)
