### ISSUE TITLE
Snapshot generation fails due to <meta charset> outside the first 1024 bytes

### ISSUE THREAD

**Issue by anssiko** [w3c/respec#1417]
HTML snapshots generated from ReSpec source that contains `<meta charset>` as its first element in `<head>` fail validation with the following error:

>A “charset” attribute on a “meta” element found after the first 1024 bytes.

Example ReSpec source:
https://github.com/w3c/manifest/blob/gh-pages/index.html#L4

This means that e.g. automatic WD publications with Echidna fail too.

I think one solution is to inject the chunk of CSS that pushes `<meta charset>` outside the first 1024 bytes as the last thing in `<head>`.

This is a pretty recent regression, since on the 22nd the Manifest publication succeeded: https://lists.w3.org/Archives/Public/public-tr-notifications/2017Sep/0095.html

Alternatively, this is could be a validator bug or feature, since another error was also introduced at the same time without related changes to the source:

>Element “ol” not allowed as child of element “ol” in this context. (Suppressing further errors from this subtree.)

Full error log: https://lists.w3.org/Archives/Public/public-tr-notifications/2017Oct/0046.html

**Comment by anssiko** [comment]
The latter error was fixable in source, PR submitted for that: https://github.com/w3c/manifest/pull/625

For former error remains a blocker for Echidna-based WD publication.

**Comment by marcoscaceres** [comment]
having a look now.

**Comment by anssiko** [comment]
Thanks, that was fast! I can confirm this fix works as expected and the generated snapshot is now valid. Using the latest ReSpec version 18.2.1 released 9 minutes ago.

**Comment by anssiko** [comment]
Probably not related, but reporting here to retain context:

Something wonky going on with Echidna. Merged https://github.com/w3c/manifest/pull/625 after release 18.2.1 was deployed, but no notification was sent to https://lists.w3.org/Archives/Public/public-tr-notifications/2017Oct/ nor was https://www.w3.org/TR/appmanifest/ updated.

(The lone notification https://lists.w3.org/Archives/Public/public-tr-notifications/2017Oct/0046.html is for the earlier merge https://github.com/w3c/manifest/pull/624).

Btw. we're at 666 commits to w3c/manifest now, perhaps that's the reason  `¯\_(ツ)_/¯`

Should I open an issue in https://github.com/w3c/echidna, or should I ask someone to reboot the server or some such magic?

**Comment by anssiko** [comment]
You can ignore the previous comment, magic happened: https://lists.w3.org/Archives/Public/public-tr-notifications/2017Oct/0047.html

**Comment by marcoscaceres** [comment]
Great to hear it’s working.
