### ISSUE TITLE
Shepherd integration

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1424]
Need to talk to @plinss about integration with Shepherd.

**Comment by saschanaz** [comment]
Note: see https://api.csswg.org/shepherd/ for API documentation.

**Comment by xfq** [comment]
Related issue: #1662

FWIW, the source code of Shepherd is here: http://hg.csswg.org/dev/

Specifically, the source of the specification DB/parser is here: http://hg.csswg.org/dev/specification/

**Comment by sidvishnoi** [comment]
Closing in favour of #1662
