### ISSUE TITLE
Link to duplicate definition

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1427]
When there is a duplicate definition, we should just link to it from the warning. 

![screen shot 2017-11-15 at 11 23 21 am](https://user-images.githubusercontent.com/870154/32812149-ad1ac662-c9f7-11e7-9b12-273b7d915782.png)

**Comment by himanish-star** [comment]
@marcoscaceres, Can I also take over this issue?

**Comment by himanish-star** [comment]
I have attempted a solution to this. You can see the GIF below for the changes. Can I file a PR for this ?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30361728/35780632-6acde08a-0a04-11e8-9faf-333f4eaa039e.gif)

**Comment by himanish-star** [comment]
@marcoscaceres, please could I get to know what is the IRC of `W3C/respec`?

**Comment by marcoscaceres** [comment]
@himanish-star, we use the w3c IRC. https://www.w3.org/wiki/IRC

You can find me as "marcosc" in the #specs channel. However, I might be slow to respond today as I'm catching up on a bunch of stuff from last week.

**Comment by himanish-star** [comment]
Thanks a lot! :smiley:

**Comment by himanish-star** [comment]
Actually I do have the things ready, but my laptop's battery was running dry so I have ordered a new battery and I'll surely file a PR after a few hours once I have my laptop back. Sorry for the inconvenience 😞

**Comment by marcoscaceres** [comment]
heh, no problem @himanish-star! Take your time and hope your laptop gets well soon 🔋🚑
