### ISSUE TITLE
Fully qualified method names are not coded

### ISSUE THREAD

**Issue by mgiuca** [w3c/respec#1437]
The draft [Web Share](https://wicg.github.io/web-share/) spec has recently (not sure when?) broken all the links to dictionary members. This previously worked.

I have:

```html
      <section data-dfn-for="ShareData">
        <pre class="idl">
          dictionary ShareData {
            USVString title;
            USVString text;
            USVString url;
          };
        </pre>
        ... snip ...
        <dfn>title</dfn>: The title of the document being shared.
```

And later in the doc:

```html
    <a for="ShareData">title</a>
```

This used to properly link to ... I don't remember. It either linked to the "title" member defined in the IDL, or the `<dfn>title</dfn>` definition element within the ShareData section. I don't remember exactly how it worked but it used to work.

Now all of my `<a for="ShareData">title</a>` and similar refs are just broken refs. Did anything change that may have accidentally broken this?

**Comment by marcoscaceres** [comment]
I dropped support for non-standard “for” a little while ago. Try “data-for” and it should be all good again :)

**Comment by mgiuca** [comment]
Hmm, no that doesn't work either.

I'm trying it on the [data-dfn-for](https://github.com/w3c/respec/wiki/data-dfn-for) example:
```html
<pre class="idl">
interface Foo {
  attribute Bar bar;
  void doTheFoo();
};
</pre>
<p>The <dfn>Foo</dfn> interface is nice. Lets you do stuff.</p>
<p>The <dfn data-dfn-for="Foo">bar</dfn> attribute, returns 🍺.</p>
<p>The <dfn data-dfn-for="Foo">doTheFoo</dfn>() method, returns nothing.</p>
<p>Note that <a data-for="Foo">bar</a> may be carbonated.</p>
```

I added the final paragraph to the example code. The "bar" generates a red error and isn't linked up, even within the same section.

**Comment by marcoscaceres** [comment]
Having a look now. I'll see if I can sprinkle a little magic and get it all working. Will send a PR. 

NB: I'm working on a big rewrite of all the IDL handling and linking that will hopefully make this effortless in the future. I'm hoping to finish it over the xmas break.

**Comment by marcoscaceres** [comment]
Sent PR to the Web Share spec. 

There is bug where `<a>Navigator.share()</a>` is not automatically getting wrapped in `code`. I'll fix that. We can probably merge in the fixes to web share and once I land a fix for this bug that will get automatically fixed.

**Comment by mgiuca** [comment]
Aha, so it just needed to be `data-link-for` (not `data-for`). Thanks for the PR, I'll look over it now.

**Comment by marcoscaceres** [comment]
Yeah, sorry... shouldn't do bug mail on the train.

**Comment by OrionStar25** [comment]
If it hasn't been solved yet, I'd like to try solving this one!

**Comment by marcoscaceres** [comment]
@OrionStar25, sure... but it's a bit of hard one. You need to start here:
https://github.com/w3c/respec/blob/develop/src/core/link-to-dfn.js#L67

**Comment by OrionStar25** [comment]
@marcoscaceres I'm not understanding much on how to do this right now, so should I move on to something easier first?  :$

**Comment by marcoscaceres** [comment]
@OrionStar25, yeah... might be best... searching for something for you.
