### ISSUE TITLE
Upcoming update to WG notes patent policy text

### ISSUE THREAD

**Issue by deniak** [w3c/respec#1443]
@plehegar and @wseltzer agreed to simplify the patent policy text for **WG Notes** (other types of documents remain unchanged).
After https://github.com/w3c/specberus/pull/707 is merged, the markup should simply be:
```html
<p data-deliverer="@@Working Group ID@@">
  This document was produced by a group operating under the  <a href="https://www.w3.org/Consortium/Patent-Policy/"><abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>.
</p>
```

Note: we are adding a requirement on the `data-deliverer` attribute which should list the WG IDs which was already in one of the previous patent policy link.

Once we are certain respec and bikeshed have been updated, we will update pubrules.

**Comment by marcoscaceres** [comment]
Seems straight forward enough.

**Comment by deniak** [comment]
@marcoscaceres it seems respec is generating the old patent policy text again for Notes, e.g. [charmod](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/charmod-norm/%3FspecStatus%3DWG-NOTE).

The following sentences should be there:
```
W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.
```

**Comment by marcoscaceres** [comment]
Will take a look and get that fixed ASAP!

**Comment by marcoscaceres** [comment]
@deniak, I'm confused. I see:

> W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

In that spec? What old text are you seeing?

**Comment by marcoscaceres** [comment]
Screenshot from generated [charmod](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/charmod-norm/%3FspecStatus%3DWG-NOTE) : 

![screenshot 2019-02-05 15 44 14](https://user-images.githubusercontent.com/870154/52253570-ea87a900-295c-11e9-9cb6-b89f122f827c.png)

**Comment by marcoscaceres** [comment]
oh, sorry, that _is_ the old text. Did you mean "The following sentences should **NOT** be there:"?

**Comment by deniak** [comment]
oups, indeed. The sentences should **NOT** be there. The expected paragraph for Notes is
```html
<p data-deliverer="@@Working Group ID@@">
  This document was produced by a group operating under the  <a href="https://www.w3.org/Consortium/Patent-Policy/"><abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>.
</p>
```
