### ISSUE TITLE
Perma Link refers to #undefined for the document

### ISSUE THREAD

**Issue by iherman** [w3c/respec#1445]
Consider, e.g., https://w3c.github.io/pwpub/: the header includes a 

```
includePermalinks: true
```

However, the link to the document itself (ie, the permalink sign appearing right at the W3C logo in this case) refers to `#undefined`. One can see that when hovering over the sign or in the generated HTML.

I ran this on Mac OS El Capitan with FF, Safari, and Vivaldi, the result is the same. It is also not document dependent; I tried it on some other specs, with a similar result.

**Comment by marcoscaceres** [comment]
Assigned to @halindrome, as I think he wrote the module.

**Comment by himanish-star** [comment]
I would like to work on this :smiley:

**Comment by marcoscaceres** [comment]
Setting @himanish-star to investigate the bug. Will let him decide if he wants to proceed with it.

**Comment by himanish-star** [comment]
@iherman, sorry to bother you but I tried to reproduce this issue at https://w3c.github.io/pwpub/?includePermalinks=true but I can't find any permaLink symbol next to the W3C logo. Could you help me in reproducing this issue? :smiley:

**Comment by iherman** [comment]
Hm. You are right, the problem disappeared:-)

There has been several updates of respec since this, so this may have been inadvertently taken care of in one of those iterations.

Closing for now...
