### ISSUE TITLE
Autowrap headings+content in section

### ISSUE THREAD

**Issue by tantek** [w3c/respec#1448]
note that second two "Changes from" headings in https://tantek.github.io/post-type-discovery/index-src.html#change-log have smaller font than the first two.

while it appears that the latter to "Changes from" headings are being artificially made smaller, what's actually happening is that the two headings before that are being artificially inflated from h3 to h2 headings by respec!

the h2 above them is: "A. Change Log"

which is correct.

then after that respect is errantly changing these headings from ```<h3>``` (in the [source](https://github.com/tantek/post-type-discovery/blob/gh-pages/index-src.html#L514)) to ```<h2>``` (in the DOM)
* "Changes from 1 August 2017 WD to this version"
* "Changes from 14 June 2017 WD to 1 August 2017 WD"

Why? It should not be doing that. It should be leaving them alone as ```<h3>``` elements.

Then for some random reason it stops doing that on *third* ```<h3>```:
* "Changes from 1 March 2017 WD to 14 June 2017 WD"

But then errantly adds a superfluous "This section is non-normative." when there is no class name or anything to indicate that that text should be there - also we're already in an explicitly labeled non-normative section "A. Change Log" so there is no reason to say so again.

Expected result:
* leave the ```<h3>``` headings as ```<h3>``` headings in the "A. Change Log" section
* do not add superfluous "This section is non-normative." text there

**Comment by marcoscaceres** [comment]
Sent PR to fix https://github.com/tantek/post-type-discovery/pull/35

However, should probably have ReSpec auto-wrap headings and content in `section` so to avoid these problems.  It's silly to force authors to have explicitly include `section`, when it's basically an ReSpec internal opinion.

**Comment by tantek** [comment]
Still a bug IMO in that perfectly reasonable HTML markup causes respec to screw up heading levels. Keep the "bug" label, and maybe add "workaround available".

**Comment by marcoscaceres** [comment]
Closing, as ReSpec remains opinionated about requiring sections.
