### ISSUE TITLE
viewing fails on Safari Version 10.1.2 (10603.3.8)

### ISSUE THREAD

**Issue by tantek** [w3c/respec#1453]
Tried using Safari due to issue #1450, and ReSpec completely fails there - doesn't do anything at all - you just see the server-served HTML.

E.g.: http://ptd.spec.indieweb.org/index-src.html

**Comment by marcoscaceres** [comment]
Unfortunately, as it’s only me maintaining ReSpec, I’m only able to support the latest stable version of Safari (11) - which is available on the last 3 releases of MacOS X.

I’m guessing you have a machine still using Yosemite?

**Comment by tantek** [comment]
Yes, Yosemite. I don't upgrade OSs that are productively working in general (e.g. "free" High Sierra updates have been bricking functional systems). Certainly not for a browser.

If the ReSpec JS is so fragile/sensitive that it can't be easily maintained (which I take your word for) across even just one major (default system) browser version, then I think you've convinced me to not write any more specs that depend on ReSpec. I realize you're doing your best to keep a W3C tool running that no one else is, and that's a (nearly) thankless job, but it's also not reasonable to make spec authors depend on a fragile toolchain that depends on one person's good will to maintain.

**Comment by marcoscaceres** [comment]
Understood - it’s been a tradeoff, and sad that Apple stopped shipping Safari updates for olde MacOS. If you can step up at least to El Capitan, you can get back on Safari latest.

BikeShed is really good tho and their community of contributors is fairly active.
