### ISSUE TITLE
Forked repositories cannot run karma tests on Travis?

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1462]
https://travis-ci.org/saschanaz/respec/jobs/335975836

The same tests for #1461 succeeds on w3c repo and fails on my own repo.

The result says `Encrypted environment variables have been removed for security reasons.`, so maybe some env vars are needed?

**Comment by marcoscaceres** [comment]
That's really strange as our config doesn't use any encrypted vars.

**Comment by marcoscaceres** [comment]
Could you rebase your fork? Maybe will not magically fix itself? Looking at the log, it seems the fails were Chrome not starting.

**Comment by saschanaz** [comment]
It's still failing 😱

https://github.com/travis-ci/travis-ci/issues/8836

The Travis-CI guys recommend `--no-sandbox` when running Chrome on a Travis container, but our w3c/respec repo is totally okay without it. Not sure what's going on.

**Comment by saschanaz** [comment]
https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348332353:

>We will update again when all of the hosts are back on Trusty and Chrome works on them. (Until then, some may pass, some may not.)

Oh.

**Comment by marcoscaceres** [comment]
They are saying there that they fixed it tho. We can definitely try `--no-sandbox` if you'd like. I don't mind, as it's not running on my computer 😂.

**Comment by saschanaz** [comment]
We can alternatively try `sudo: required`, or may just wait as:

1) I can now use the official repo to test codes :tada:
2) [They are willing to fix it](https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-359018652)
   >We are working to change this, but it is a long-term project that has historically been bumped for weeks or months in order to address interruptive or higher priority work.

**Comment by marcoscaceres** [comment]
Happy for you to test here :) However, there are a few other forks of this project, so if you think it might help them, we could also add `sudo: required` to the config.
