### ISSUE TITLE
19.1.0 doesn't seem to support interface mixins

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1475]
cc: @marcoscaceres

It does not contain support for interface mixins. Probably the scripts were built on a previous commit?

**Comment by marcoscaceres** [comment]
Odd. Will check what happened.

**Comment by marcoscaceres** [comment]
ok, trying to rebuild and figure out what happened.

**Comment by marcoscaceres** [comment]
Seems we regressed somewhere related to the linking with the recent IDL changes. Will walk it back a bit and see if I can figure it out.

**Comment by saschanaz** [comment]
Confirmed that 19.1.1 fixes this :tada:

**Comment by marcoscaceres** [comment]
Excellent! Thanks for checking this one too!
