### ISSUE TITLE
CI fails with a message `{}`

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1476]
Starting from https://github.com/w3c/respec/commit/670b3120207543cd384b616053cf7d4ab3b2af90:

https://travis-ci.org/w3c/respec/jobs/337395491

```
4:08:34 AM  👷‍♀️  node ./tools/respec2html.js -e --timeout 30 --src https://w3c.github.io/payment-request/ --out /dev/null (test 3/9)
{}
Error: Command failed: node ./tools/respec2html.js -e --timeout 30 --src https://w3c.github.io/payment-request/ --out /dev/null
{}
```

**Comment by saschanaz** [comment]
It seems https://w3c.github.io/manifest/ itself has a problem, but that empty error message is still odd.

**Comment by saschanaz** [comment]
#1475 seems related. webidl2.js is up to date there but the ReSpec script is not updated to be compatible.

**Comment by marcoscaceres** [comment]
Yeah, spotted that too. Will have to look in the morning, as it’s 💤 time here.

**Comment by marcoscaceres** [comment]
Ok, this one seems to have been caused by a bug in HyperHTML. Upgrading the dependency seemed to fix things locally for me. I've pushed this as 19.1.1... but just waiting to CI to acknowledge that it worked.

**Comment by marcoscaceres** [comment]
Ok, Travis is happy again 🕺
