### ISSUE TITLE
Missing things in IDL index

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1479]
Given:

```HTML
<pre class="idl">
interface BeforeInstallPromptEvent : Event {
    Promise<PromptResponseObject> prompt();
};

dictionary PromptResponseObject {
    AppBannerPromptOutcome userChoice;
};
</pre>
```

Expected the following to include both `BeforeInstallPromptEvent` AND `PromptResponseObject`:

```HTML
<section id="idl-index"></section> 
```

Actual: `PromptResponseObject` object is missing.

**Comment by shubhshrma** [comment]
Can I work on this @marcoscaceres ? I have setup the project and am ready to try to tackle some issues.

**Comment by shubhshrma** [comment]
@marcoscaceres  @saschanaz It would be great help if you people could possibly locate me to some files to change. I understand the issue after looking [this](https://w3c.github.io/manifest/#beforeinstallpromptevent-interface) page and [this](https://github.com/w3c/manifest/blob/gh-pages/index.html) code. But being new I can't find the appropriate files to work on. Please help. Thanks.

**Comment by marcoscaceres** [comment]
@shubhshrma, thanks for offering to help - some info below.

The IDL index is generated by:
`src/core/webidl-index.js`

And tests for this are in: 
`spec/core/idl-index-spec.js`

If you haven't already, please check out the [developer guide](https://github.com/w3c/respec/wiki/Developers-Guide).

I suggest putting the test case above into the "examples/basic.html" file, and trying to debug it from there.

**Comment by shubhshrma** [comment]
@marcoscaceres The problem is that we are appending only the first child of each ```<pre class="idl">``` and not all children. So, only first block of each is present in ```<section class="idl-index">```. I have made some changes. Please see.

**Comment by marcoscaceres** [comment]
Fixed via https://github.com/w3c/respec/issues/1497
