### ISSUE TITLE
`npm run karma` cannot run Chromium

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1484]
Related with https://github.com/litixsoft/karma-detect-browsers/issues/22.

And it never uses headless mode which is better for CI tests (and required for Windows Subsystem for Linux).

**Comment by saschanaz** [comment]
BTW, Is it intended to run on every browser installed on the system? I have Chrome, Firefox, Opera and MSEdge and karma wants to run tests on all browsers..

**Comment by marcoscaceres** [comment]
That's what I've been doing locally (as I was the lone maintainer). However, we can restrict that now that more people are participating.

**Comment by saschanaz** [comment]
`npm run karma -- --browsers Chromium` should now work per https://github.com/litixsoft/karma-detect-browsers/pull/27
