### ISSUE TITLE
SOTD still points to 1 March 2017 W3C Process Document

### ISSUE THREAD

**Issue by riannella** [w3c/respec#1485]
How can we get our specs to link to the new 1 Feb 2018 W3C process document in the SOTD section?

**Comment by marcoscaceres** [comment]
@riannella, could you please send me a link to the affected document? I'll try to see what is going on. We only rolled out the process changes a few days ago, so there might be a bug.

**Comment by saschanaz** [comment]
I'm seeing 1 Feb 2018:

![image](https://user-images.githubusercontent.com/3396686/36058605-242dd316-0e68-11e8-9022-356146c377e1.png)

**Comment by riannella** [comment]
Hmmm...looks like it could have been a force-reload webpage issue....
