### ISSUE TITLE
What does handle @@@?

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1494]
I found `@@@text@@@` forms in our SOTD template:

https://github.com/w3c/respec/blob/cb910fefe152db689659c6b16b319ffabcc1a239/js/w3c/templates/sotd.html#L37-L53

It seems they are not processed by handlebars or anything, what does handle them?

**Comment by marcoscaceres** [comment]
Heh, I think because we never have member submissions (`isMemberSubmission` being true) in practice, no one has ever seen this bug :)

**Comment by marcoscaceres** [comment]
I think we should just remove support for this from ReSpec. We have better ways to do incubation than relying on member submissions (e.g., regular CGs and the WICG). I've also checked all of Github, and there are zero instances of `isMemberSubmission` set to true.

**Comment by saschanaz** [comment]
@marcoscaceres Does the same applies to `isTeamSubmission`?

**Comment by marcoscaceres** [comment]
Yeah, I believe so. I will check with W3C staff tho.

**Comment by marcoscaceres** [comment]
@dontcallmedom, @plehegar, doing some archeology, it seems like `isTeamSubmission` and `isMemberSubmission` have never been used... how about we remove them from ReSpec?

**Comment by dontcallmedom** [comment]
I know that at least some Member submissions were written with ReSpec, so I think we should keep it; Team submissions may be rare enough that they could be removed

**Comment by marcoscaceres** [comment]
@dontcallmedom is right... there are quite a few ReSpec based member submissions: https://www.w3.org/Submission/

**Comment by saschanaz** [comment]
Hmm, so it seems *something* processes those `@@@`, no idea what it is...

**Comment by marcoscaceres** [comment]
They are probably just changed manually before the submission gets published... we can definitely fix that. It looks like we need a publish date to generate the submission URL.

**Comment by marcoscaceres** [comment]
@OrionStar25, this could be a good one. What needs to be done:

- [ ]  Remove team submission.
- [ ]  Fix the template for isMemberSubmission, so that the `@@@whatever` get replaces with actual configuration options.

See how other things in that file are done... should hopefully be straight forward.

**Comment by OrionStar25** [comment]
sotd.html is present in a different tree and not in develop. Can you please explain why is that? @marcoscaceres

**Comment by marcoscaceres** [comment]
oh, @saschanaz refactored all those :) So it's now here (src/w3c/templates/sotd.js): 
https://github.com/w3c/respec/blob/develop/src/w3c/templates/sotd.js#L40
