### ISSUE TITLE
Typos in the Developer's Guide 

### ISSUE THREAD

**Issue by shikhar-scs** [w3c/respec#1512]
Reading up the developer's guide, I found a couple of typos. 

https://github.com/w3c/respec/wiki/Developers-Guide#warning-users-of-errors
> as they won't be able to fix these, and they minified JS output will make these messages really unhelpful!

`**the** minified JS`

https://github.com/w3c/respec/wiki/Developers-Guide#plugins
> You can also npm run babel:watch.

`You can also **run** npm run babel:watch`

I'll keep on adding more as and when I reach to them :sweat_smile:

**Comment by marcoscaceres** [comment]
Thanks @shikhar-scs. Could you kindly fix any typos you find. Unfortunately, the docs have not had much review.

**Comment by marcoscaceres** [comment]
(please close this issue if the above are fixed)

**Comment by shikhar-scs** [comment]
Done. ThankYou for making me a `collaborator` :sweat_smile:
