### ISSUE TITLE
Better integration with infra spec

### ISSUE THREAD

**Issue by kenchris** [w3c/respec#1520]
Bikeshed has great integration with infra like, if you do for each you can easily refer to which one to use, like

 [=set/For each=] or [=map/For each=] or [=list/For each=]

The infra spec: 
http://infra.spec.whatwg.org

**Comment by marcoscaceres** [comment]
Would be nice to support these inlines... tho the syntax is kinda fugly.

**Comment by marcoscaceres** [comment]
Current solution:

* `<a data-cite="infra#set-iterate">For each</a>`
* `<a data-cite="infra#map-iterate">For each</a>`
* `<a data-cite="infra#list-iterate">For each</a>`

Yes, it's much longer, but it's more clear... I'm open to suggestions on inlining, however... we could just use BS's syntax for compat. 

@kenchris, do you know if you get any other bonus things from BikeShed from the above? Or just the linking?

**Comment by kenchris** [comment]
I am not sure, but the syntax makes the text source very readable

**Comment by marcoscaceres** [comment]
Agree. Might be something we do as part of #1502 if we get time.

**Comment by marcoscaceres** [comment]
For folks following at home, what we need is a generic model for inlining things similar to: https://tabatkins.github.io/bikeshed/#autolinking

We should find a generic way to auto link with some inline syntax that's not super ugly. We don't need to follow BikeShed - the syntax should be intuitive and generalizable.  

@kenchris, I can't find the integration in BikeShed... at least, it's not documented in the autolinking section. Where did you see this?

**Comment by himanish-star** [comment]
So this is no longer a part of #1502

**Comment by marcoscaceres** [comment]
Still part of #1502. It’s quite a significant problem/task.

**Comment by kenchris** [comment]
@marcoscaceres I saw this used in all the Generic Sensor APIs specs

**Comment by marcoscaceres** [comment]
Thanks! Will take a look at how it’s used there. I use an infra list in Payments, so would also benefit.

**Comment by marcoscaceres** [comment]
Fixed via #2261
