### ISSUE TITLE
Respec can't check local source files anymore

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/respec#1522]
respec was able to check a local source file now it seems it is not able to check local files anymore whereas it works fine if the file is retrieved from the web.

With local source file ... **Fails**:
```bash
~/W3C/WebRTC/webrtc-pc$ node support/respec/tools/respec2html.js -e --timeout 30 --src file://`pwd`/webrtc.html --out build/output.html
Error: 📡 HTTP Error 0: file:///home/vivien/W3C/WebRTC/webrtc-pc/webrtc.html
   at fetchAndWrite (/home/vivien/W3C/WebRTC/webrtc-pc/support/respec/tools/respecDocWriter.js:78:13)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
```

With same source file fetched from the web ... **Works**:
```bash
~/W3C/WebRTC/webrtc-pc$ node support/respec/tools/respec2html.js -e --timeout 30 --src https://w3c.github.io/webrtc-pc/ --out build/output.html
```

If possible please add a new test for using local files as the test you have (number 8 and 9) are using a local webserver, eg.

```bash
node ./tools/respec2html.js -e --disable-sandbox --timeout 30 --src http://localhost:3000/examples/basic.built.html --out /dev/null (test 8/9)
```

Issue faced by @suhasHere @alvestrand @dontcallmedom on various webrtc drafts

**Comment by vivienlacourba** [comment]
Hi @marcoscaceres I hope you can help us here.

Side note respec tests are also broken https://travis-ci.org/w3c/respec/jobs/344196977

**Comment by marcoscaceres** [comment]
@saschanaz, this is related to us switching to Puppeteer. File URLs might not work until this get addressed: https://github.com/GoogleChrome/puppeteer/issues/1506

@vivienlacourba, the work around in just to spin up a local server for now.

```Bash
python -m SimpleHTTPServer 8000
```

(or you can npm install `http-server` and use that)

**Comment by marcoscaceres** [comment]
@vivienlacourba, 
> Side note respec tests are also broken https://travis-ci.org/w3c/respec/jobs/344196977

Kindly note the above is a random feature branch, which happens to be failing - but it's not part of the build. 

To check the build status of ReSpec (the "develop" branch), go directly to https://travis-ci.org/w3c/respec

**Comment by vivienlacourba** [comment]
@marcoscaceres, thanks I have a PR ready that uses the python webserver https://github.com/w3c/webrtc-respec-ci/pull/25 I'll merge it tomorrow.

**Comment by marcoscaceres** [comment]
@vivienlacourba, thanks for the update and for switching over to use a local server. Hopefully we can get this working over "file://" again soon. Will let you know once we do.

**Comment by vivienlacourba** [comment]
In the end I used Python 3 http.server module which allows to bind to a specific address. Thanks @alvestrand for the security review.

```bash
python3 -m http.server 8765 --bind 127.0.0.1
```
