### ISSUE TITLE
Highlight variable matching in algorithm

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1529]
Given a spec algorithm like:
https://www.w3.org/TR/payment-request/#dfn-update-a-paymentrequest-s-details-algorithm

If a `<var>` is set, it should be possible to click on it and see all the places where the variable is used. 

If a `<var>` is set but never used, it that's a bug.

**Comment by sidvishnoi** [comment]
Hello sir,
Is this what you're looking for? https://streamable.com/i7kns (something like this, needs update on second part (set, never used))

If yes, I can create a PR for this. Hopefully you can help where this needs to be implemented.
If no, sorry I misunderstood the problem. Can you describe more?

**Comment by marcoscaceres** [comment]
You nailed it @sidvishnoi. That's exactly what I was looking for! 

Let's continue the discussions over in the pull request.
