### ISSUE TITLE
auto normalize references

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1535]
today, if you have:

```
[[html]] and <a data-cite="HTML">
```

Or variance in the above, ReSpec warns:

> "[HTML] is referenced in 2 ways: ('HTML', 'html'). This causes duplicate entries in the References section."

This is annoying for a number of reasons: 
 1. finding the culprit duplicate can be really hard in a large document. Specs can be thousands of lines long, and contain 50-100 citations. 
 1. Clearly, ReSpec knows the two are clashing - so it should just automatically fix the problem (just use the first encountered convention) and avoid adding duplicate entries to the bibliography.

**Comment by shikhar-scs** [comment]
Is this to be solved here or can it be a part of #1502 (module rewrite) ?

**Comment by himanish-star** [comment]
Same question

**Comment by marcoscaceres** [comment]
Can be solved whenever :) It should be fairly simple to fix.

**Comment by OrionStar25** [comment]
WebIDL issue! I'd love to work ont this please :smiley:

**Comment by marcoscaceres** [comment]
Starting point is:
https://github.com/w3c/respec/blob/develop/src/core/inlines.js#L67-L87

And where the warning happens:
https://github.com/w3c/respec/blob/develop/src/core/biblio.js#L182-L189

Somewhere in the above (you whomever works on it), normalization of the reference needs to happen.

**Comment by sidvishnoi** [comment]
Accidentally closed. Reopening
