### ISSUE TITLE
seo and jsonld modules should be merged

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1536]
The [seo](https://github.com/w3c/respec/tree/develop/src/core/seo.js) module and the newly added [jsonld](https://github.com/w3c/respec/tree/develop/src/w3c/jsonld.js) should be merged. They share code and serve a very similar purpose.

**Comment by gkellogg** [comment]
Yes, I was thinking that at the time, but thought to keep them separate, as `doJsonLd` is optional. This makes most sense when the JSON-LD script element is standard, rather than optional (who doesn't want good SEO results?).

**Comment by marcoscaceres** [comment]
@gkellogg agree. It might mean that we can also get rid of the `<meta description>`. 

I'd be interested to see if Bing and DuckDuckGo make use of the JSON-LD (and also the `<meta description>`).

**Comment by marcoscaceres** [comment]
Did a bit of searching, it doesn't seem other search engines are onboard yet with JSON-LD 😞

**Comment by gkellogg** [comment]
No, it's been a bone of contention in the SEO community that JSON-LD is not more widely adopted; it will be eventually, though.

**Comment by goelrohan6** [comment]
Hi @marcoscaceres I would like to work on this issue, how do I get familiar with the codebase, I guess for this all I have to do is merge the modules and search for files where the modules are being used respectively.
what will be the name of the final module?
I couldn't find the files where the module's are being imported

**Comment by marcoscaceres** [comment]
@goelrohan6, please see the [developers guide](https://github.com/w3c/respec/wiki/Developers-Guide) to understand the codebase/plugin-system. 

> what will be the name of the final module?

The idea would be to merge the jsonld.js module into the seo.js module... so, just seo.js :)

> I couldn't find the files where the module's are being imported.
 
The modules are import from the [w3c profile](https://github.com/w3c/respec/blob/develop/js/profile-w3c-common.js).

**Comment by goelrohan6** [comment]
Got it @marcoscaceres, after merging and removing jsonld package from [w3c profile](https://github.com/w3c/respec/blob/develop/js/profile-w3c-common.js).

also the the jsonld-spec.js will be copied to seo-spec.js as with all the test's right?
any other changes before i send a pr?

**Comment by marcoscaceres** [comment]
> Also, the jsonld-spec.js will be copied to seo-spec.js as with all the test's right?

Yeah, good catch. 

> any other changes before I send a pr?

The json-ld module hard codes a W3C copyright into the JSON-LD.... and that's kinda tricky to deal with.  

So, maybe as the first step, we should actually merge jsonld.js into:  https://github.com/w3c/respec/blob/develop/src/w3c/seo.js

Then, if we can generalize the copyright issue... and move everything into core/seo.

**Comment by goelrohan6** [comment]
@marcoscaceres in run function of jsonld there's a condition if(!conf.doJsonLd) // do nothing

should this be followed while moving it to seo too? or the seo run function should run even if it does not satisfy the condition.

and also I should completely delete jsonld file after merging?
I'll send a pr after merging and we can discuss about -spec after that.

**Comment by marcoscaceres** [comment]
> should this be followed while moving it to seo too? 

Not if other parts depend on `conf`. 

> or the seo run function should run even if it does not satisfy the condition.

As above. You will need to check what both modules do. 

> and also I should completely delete jsonld file after merging?

Yes. That would be great.

**Comment by marcoscaceres** [comment]
Thanks @goelrohan6 for the speedy turn-around! Will try to get to it soon! (currently busy with #1502 proposals!)

**Comment by goelrohan6** [comment]
fine @marcoscaceres, actually i'm also a gsoc aspirant, didn't knew about #1502. 
will check out and start preparing a  proposal.
