### ISSUE TITLE
Regression: release.js exits with ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1547]
@saschanaz, sorry, when executing: 

```Bash
./tools/release.js
```

The following is still not producing the correct file URL: 
https://github.com/w3c/respec/blob/develop/tools/release.js#L398
 
It returns:

```Bash
Error: net::ERR_FILE_NOT_FOUND
    at navigate (/Users/marcos/temp/respec/node_modules/puppeteer/lib/Page.js:520:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by saschanaz** [comment]
Sorry, my huge bad 😱 I just pushed a quick fix, does it work?

**Comment by marcoscaceres** [comment]
Np :) Testing.

**Comment by marcoscaceres** [comment]
perfect! 💃  💃  💃 
+ respec@20.0.3
