### ISSUE TITLE
Configure Jasmine to not run in random

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1552]
Jasmine 3 made running test in random order the default. Unfortunately, this breaks our test suite. 

We should initially disable running the tests randomly, then investigate why we can’t run in random order (sounds like buggy tests). 

We need to add: 
```js

jasmine.loadConfig({
    random: false,
});
```

In SpecRunner.html and test-main.js.

**Comment by saschanaz** [comment]
Oh, what tests are breaking? I recently haven't seen any random breakage.

**Comment by marcoscaceres** [comment]
Thought maybe that’s what’s happening here: https://github.com/w3c/respec/pull/1505#issuecomment-370075140

Need to confirm.

**Comment by marcoscaceres** [comment]
Seems tests are still failing there even without random, so maybe this is invalid.

**Comment by saschanaz** [comment]
The errors say `doc` is undefined, but we already have `beforeAll` hook so it shouldn't be the case...

```js
  beforeAll(async () => {
    doc = await makeRSDoc({ config, body });
    specRefOk = (await fetch(bibRefsURL, { method: "HEAD" })).ok;
  });
```

**Comment by marcoscaceres** [comment]
So weird. @saschanaz, will you want to look into this further, or should we just leave it (i.e., just not to randomize). Having the randomized tests does add some potential value, but can live without it.

**Comment by saschanaz** [comment]
Hmm, I will look at it today or tomorrow.

**Comment by OrionStar25** [comment]
There is something about this is this issue: https://github.com/jasmine/jasmine/issues/583

**Comment by marcoscaceres** [comment]
It is, but it’s actually fine. We’ve managed to run tge test suite in random order without issue.
