### ISSUE TITLE
RangeError: Invalid count value exception in idn()

### ISSUE THREAD

**Issue by Orphis** [w3c/respec#1559]
When rendering the [webrtc-pc](https://w3c.github.io/webrtc-pc/) spec, we get this exception:
```
respec-w3c-common.js:1 RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at M (respec-w3c-common.js:414)
    at Object.<anonymous> (respec-w3c-common.js:414)
    at Object.main (respec-w3c-common.js:1)
    at c (respec-w3c-common.js:1)
    at i (respec-w3c-common.js:1)
    at respec-w3c-common.js:414
    at respec-w3c-common.js:414
    at Array.map (<anonymous>)
    at Q (respec-w3c-common.js:414)
```

I tracked it down to `idn()` calls with a negative number. Not quite sure why, but it shouldn't throw any exception. Adding a `Math.max(0, lvl)` to `idn()` seems to fix the issue, but I didn't try to see why it would have a negative padding in the first place.

**Comment by sidvishnoi** [comment]
I've tracked down the bug to 
`src/core/webidl.js#L677 ---  if (meth.static) len += 7;` and 
`src/core/webidl.js#L693 --- var pad = max - len;`.

What is this 7?
What should be done? Should we increase `max` by 7 also? or make `pad = Math.max(pad,0)`

**Comment by saschanaz** [comment]
>What is this 7?

`"static ".length === 7`.

Currently the webidl module is slightly a mess... Anyway, the right fix is to do the same `+= 7` in line 594.

https://github.com/w3c/respec/blob/23001a604799c4c7c0d97b01b970128c8cfd6042/src/core/webidl.js#L588-L595

**Comment by saschanaz** [comment]
@marcoscaceres, do we want to keep this formatter-like feature after we do https://github.com/w3c/webidl2.js/issues/125?

**Comment by marcoscaceres** [comment]
No, I’d like to get rid of the formatter in ReSpec.

**Comment by marcoscaceres** [comment]
@Orphis, should be good now, but you update ReSpec in the Web RTC repo.

**Comment by marcoscaceres** [comment]
fixed typo above.

**Comment by Orphis** [comment]
Thanks!

**Comment by alvestrand** [comment]
@vivienlacourba can you take care of updating webrtc-pc and friends?
