### ISSUE TITLE
Some way to drop "Latest published version" link for specs not published yet

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1562]
ReSpec automatically generates the "Latest Published Version" link, which is obviously great. That said, that link does not exist before a spec gets published as First Public Working Draft, leading to a broken link in first versions of the Editor's Draft. In some cases, groups may work on Editor's Drafts that are initial proposals without concrete plans to publish the spec in the "/TR/" space.

That is not a major issue, for sure, but I haven't seen any way to prevent ReSpec from generating that link (save by using the "unofficial" spec status) and I wonder if something like ```"publishedURI": null``` could be useful. At the same time, if there is a config setting, it's possible that people may forget to remove it after publication...

**Comment by sandhawke** [comment]
This is a major issue for me.   Suggested workaround?

**Comment by marcoscaceres** [comment]
@sandhawke, can you help me understand a little more which of your specs it's affecting? I'm assuming you also have a "ED" before a FPWD?

**Comment by sandhawke** [comment]
Yeah, specifically it's in a CG.   So even after FPWD it'll never have a /TR URL.

Example: https://credweb.org/report/snapshot

So, really there are two orthogonal problems here: ED before FPWD, and CG-ED, neither of which are supported by respec.  I've dealt with ED-before-FPWD enough over the years (dozens of times before respec came along) that I don't want to just ignore that one, but it's true the hack you see me using on that page (shortname = "not-published-as-TR") probably does suffice for that situation.  It's less good for the CG-ED, which might run a year or more before perhaps eventually becoming a WG's FPWD and getting a real shortname.

**Comment by marcoscaceres** [comment]
>  ED before FPWD, 

Ok, we should come up with something clever here.... like "ED" without a `previousStatus` drops the "Latest published version". 

I agree we need a CG-ED status. That makes sense. But we might need to take that TR-Design as it might require additional image assets.  

> It's less good for the CG-ED, which might run a year or more before perhaps eventually becoming a WG's FPWD and getting a real shortname.

Agree.

**Comment by marcoscaceres** [comment]
> I agree we need a CG-ED status.

Actually, we have CG-DRAFT.

**Comment by sandhawke** [comment]
That's different. That's like a WD.  It's a publication approved by the CG as a non-final Report.  For example. the CG-DRAFT form of the CG-ED I linked above is: https://credweb.org/report/20181011

**Comment by marcoscaceres** [comment]
Sorry to drag this out, as changing this could have some significant implications I want to make sure we get It right. My recollection for when we set up community groups was that, they could only be in three states (what's currently supported):

 * unofficial 
 * CG-Draft
 * CG-Final

The rationale being that, as [CG are governed by a simple Draft/Final publication process](https://www.w3.org/community/about/agreements/), they can only be in the states above. The situation you outline is kind of unique in my experience: where a group has to approve the publication of a CG Draft.  

Question is, could "unofficial" serve as "CG-ED"? If no, could you help me understand what's missing?

**Comment by sandhawke** [comment]
I'm kind of lost in the relevant documents.  Do you see something that suggests a CG-Draft could be published without group approval?

**Comment by xfq** [comment]
FWIW, one of my groups need this feature too. We got a few questions about the 404.

**Comment by marcoscaceres** [comment]
Could use some help with this, as I don't currently have time to get to it. I'd be happy to provide guidance if someone wants to have a go at fixing it. Shouldn't be too hard, given the discussion above.
