### ISSUE TITLE
Documentation/Wiki: First-Time User Feedback

### ISSUE THREAD

**Issue by rjksmith** [w3c/respec#1563]
I've just used ReSpec to create my first document and found it very useful, as it simply handles much of the tedious formatting automatically.

However, there were Wiki issues I encountered as a first-time user which I felt slowed my progress more than they should, and I think addressing these might make the learning experience easier and faster for future novices.

1. The HTML example on the [Home page](https://github.com/w3c/respec/wiki) is a great starting point to explain the configuration basics. However, the example in the [Editor's Guide](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide) is identical, and adds no further value. It would have been helpful to me to have a second (more detailed) example in the Editor's Guide, which included more sample content, e.g. a note, a sub-section, an example, an editor’s note, highlighted/unhighlighted code, an appendix, etc.

    Much of this content is already present in the Wiki, but is listed individually on separate pages, e.g. the 'note' CSS class. As a novice, I was unaware of where to find the feature for which I was looking, so including these fragments in an example file would have directed me to it more quickly.

1. The User Guide link in the right-hand navigation panel on the [Home page](https://github.com/w3c/respec/wiki), leads to a blank URL, i.e. https://github.com/w3c/respec/wiki/User's-Guide. Given the choice of 'detailed user guide' and 'user guide' on the Home page, I clicked the link for the less-detailed option and then assumed that the other link also led to a blank page.

    Only much later, having explored the Wiki by guesswork and learned a little more, I was reminded of the 'detailed user guide' link on the Home page and discovered that it actually worked.

1. Being able to see the resulting output alongside the example ReSpec code would allow me to correctly identify features more quickly, i.e. here is the code and here is the rendered display.

I hope this is helpful, but please let me know if you need further clarification.

**Comment by OrionStar25** [comment]
The link to User's Guide has been fixed! :smile:

**Comment by marcoscaceres** [comment]
> The HTML example on the Home page is a great starting point to explain the configuration basics. However, the example in the Editor's Guide is identical, and adds no further value. 

Removed the one from the README.

> It would have been helpful to me to have a second (more detailed) example in the Editor's Guide, which included more sample content, e.g. a note, a sub-section, an example, an editor’s note, highlighted/unhighlighted code, an appendix, etc.

Added, except Editor's note... as they are just a type of "note". 

> The User Guide link in the right-hand navigation panel on the Home page, leads to a blank URL, i.e. https://github.com/w3c/respec/wiki/User's-Guide. Given the choice of 'detailed user guide' and 'user guide' on the Home page, I clicked the link for the less-detailed option and then assumed that the other link also led to a blank page.
> Only much later, having explored the Wiki by guesswork and learned a little more, I was reminded of the 'detailed user guide' link on the Home page and discovered that it actually worked.

Fixed. Also, we are not directing people to https://respec.org/docs. 

> Being able to see the resulting output alongside the example ReSpec code would allow me to correctly identify features more quickly, i.e. here is the code and here is the rendered display.

Agree. We need to add those incrementally as it's quite a bit of work. I'll see about adding some as I go.
