### ISSUE TITLE
Extended attribute on types in union

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#1574]
## Important info

* URL to affected spec: https://w3c.github.io/mediacapture-main/ (but currently only in PR https://github.com/w3c/mediacapture-main/pull/515 )
* ReSpec version: 20.0.4 (but problem persists in 20.0.5)
* [ x ] I did a "hard refresh", but it's still busted. 

## Description of problem
The WebIDL fragment
```typedef ([Clamp] unsigned long or ConstrainULongRange) ConstrainULong;``` is not properly parsed and displayed

Expected:
The HTML representation should still have the [Clamp] extended attribute.

But what actually happened (the bug):
It prints the WebIDL fragment without the extended attribute.

**Comment by marcoscaceres** [comment]
Interesting! Will take a look tomorrow.

**Comment by marcoscaceres** [comment]
I think this is the first time I’ve ever seen such a IDL fragment. I suspect that the template file is missing support for inclusion of extended attributes.
