### ISSUE TITLE
Allow makeStandardOps() to take overrides

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1576]
In the test, we do a lot of this: 
```JS
    const ops = makeStandardOps();
      const newProps = {
        specStatus: "REC",
      };
     Object.assign(ops.config, newProps);
````

We should allow `makeStandardOps(configOverride = {})`: 

And then do the following in `makeStandardOps()`: 

```JS
 return { ...standardOps, ...configOverride }; 
```

**Comment by shikhar-scs** [comment]
> makeStandardOps(configOverride = {})

So, by this you mean that whenever we want a custom config, instead of writing 2 extra steps, we can send the required configurations directly as arguments to the `makeStandardOps` function.

**Comment by marcoscaceres** [comment]
Correct. And with the ability to also override the body.

**Comment by marcoscaceres** [comment]
I'm not sure if we need to do anything with `makeDefaultBody()` at this point. The problem with `makeDefaultBody()` is that sometimes you want stuff at the front of it, other times at the back, and sometimes you want to trash it entirely... so best not bother with it.
