### ISSUE TITLE
npm start doesn't build all components

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1580]
```
TypeError: Cannot read property 'length' of undefined
    at extAttr (webidl.js:250)
    at idlType2Html (webidl.js:158)
    at Object.<anonymous> (webidl.js:80)
    at Object.main (templates.js:35)
    at main (handlebars.js:1145)
    at ret (handlebars.js:1148)
    at writeAttribute (webidl.js:656)
    at webidl.js:602
    at Array.map (<anonymous>)
    at writeInterfaceDefinition (webidl.js:599)
```

I'm using the `examples/basic.html` (local branch in sync with 6b9412b23080d0446fca3aea6d744b19e3cbe097) . I think it's related to updates in webidl: 1aa913521a7158204aa49f55863597335ac9160f (checking out a commit behind this one didn't give error)

Let me know if I'm the only one facing the issue.

**Comment by marcoscaceres** [comment]
Maybe try `npm run build`? Could be that handlebars didn’t build.

**Comment by sidvishnoi** [comment]
Oh! That fixes it!
So we do we need to build it each time there is some update like that?

**Comment by marcoscaceres** [comment]
Yeah, it’s rare to update the templates. But we should update package.json and tge dev guide so it doesn’t catch people out. It’s gotten me too in the past.

**Comment by marcoscaceres** [comment]
Closing this, as we do now build components when we run `npm start`
