### ISSUE TITLE
Improve github labels

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1582]
Github labels are showing up, and they are awesome. Some improvements we could make:

- [x] cache issues (critical - we only get 60 requests / hour on Github)
- [x] concurrent download of issues (critical). The current design awaits each issue. 
- [ ] wrap them in an unordered list (`<ul>`). 
- [x] add an aria label, so this reads: "This issue is labelled on github as: x, y, and z". 
- [x] remove or improve hover effect... currently it's getting inherited, and it's a little bit too much. 

cc @himanish-star

**Comment by himanish-star** [comment]
> remove or improve hover effect... currently it's getting inherited, and it's a little bit too much.

Yep. This kills the design of the labels

**Comment by marcoscaceres** [comment]
We hit a couple of unexpected issues with the last release of this feature (49463aa89b6c8eb45f17d0a08e28b567c3ec5d6e). Mainly to do with the changes we made for fetching and github API limits.

**Comment by himanish-star** [comment]
Hey @marcoscaceres!!!!, sure I would love to work on this. But, as I am pretty much occupied with some other work, I think I'll be only able to work on this in the weekends. Will that work for you?
I could start off with this from the coming weekend :)

**Comment by marcoscaceres** [comment]
oh, whenever you can. No stress! If you don't get time, that's also fine. Just let me know.

**Comment by pradeepgangwar** [comment]
I would like to try this one as my next issue, if no one is currently working on this.

**Comment by sidvishnoi** [comment]
Reopening as there are more items in checklist

**Comment by AdityaSrivast** [comment]
@sidvishnoi I would like to work on it. Can you please brief me on what is to be done?

**Comment by marcoscaceres** [comment]
Talked with @himanish-star... we decided not to wrap the labels in UL. It appears that caching was done at some point.
