### ISSUE TITLE
Editor's Guide is missing content / needs cross-refs

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/respec#1592]
The [ReSpec Editor's Guide](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide) on the wiki has a few references to content that is no longer on that page. E.g., 

> The result of changing these configuration options can be seen in the "Status of this Document" section. Here is an example with different values.

> The following table lists the values currently understood [for `specStatus`]. Each of them has an example link demonstrating what it produces.

I think the "table" might be the one on the [`specStatus` page](https://github.com/w3c/respec/wiki/specStatus), but there is no demonstration of the output boilerplate.

More generally, it would be useful if key terms in the guide linked to the detailed pages, if that is possible within GitHub's wiki format.

**Comment by OrionStar25** [comment]
I agree, there are a lot of missing examples in the wiki. This needs to be updated with small visual mockups.

**Comment by marcoscaceres** [comment]
So, I think we can "hack" the visuals by dragging and dropping images into a Github issue. That will upload the content to github... then we can take the generated URL and paste it into the wiki. I don't know why we can't do that directly in the wiki... it's just not supported.

More generally, the wiki could definitely use a lot of improvements.

**Comment by Swapnilr1** [comment]
A repo's wiki is also a git repository with all the markdown files (though it is not possible to view it as a repository on GitHub, only way to work with it is to clone it), so it is possible to add images there.

**Comment by marcoscaceres** [comment]
@sidvishnoi gave the docs a new coat of paint and updated a whole bunch of stuff, including the guides, etc. Going to close this now, and we can deal with more specific issues as the come up. https://respec.org/docs/
