### ISSUE TITLE
Language markup showing in Editors list

### ISSUE THREAD

**Issue by r12a** [w3c/respec#1594]
## Important info

* https://w3c.github.io/jlreq/
* ReSpec version: 20.3.0
* [ yes ] I did a "hard refresh", but it's still busted. 

## Description of problem

Expected: 

But what actually happened (the bug): Language-related markup showing through in Editors list.

![screen shot 2018-03-28 at 08 07 37](https://user-images.githubusercontent.com/4839211/38014246-f9499e70-325f-11e8-9e75-6b6bd1cfbc1b.png)

**Comment by marcoscaceres** [comment]
Confirmed. Looks like we regressed at some point.

**Comment by r12a** [comment]
Reopening because the fix provided only addressed the names, and not the organisations. Moving the report here from #1786.

## Important info

* URL to affected spec: http://w3c.github.io/clreq/
* ReSpec version: 22.3.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
See the editor lists at top of page, such as:
> 董福興 (Bobby TUNG) (特邀专家 (Invited Expert))

It's possible to surround 董福興 with `<span lang='zh-hant'>`, but not 特邀专家. If you add markup around the latter, it is displayed as source code. Presumably because the respec source code uses textContent, rather than treating the value as HTML for 'company:' (?).

This is a problem, because the wrong glyphs are being displayed. See https://github.com/w3c/clreq/pull/185

**Comment by r12a** [comment]
Thanks for the fix.  How will i be notified when it goes live?  (Because i need to add the language tags at that point.)

**Comment by marcoscaceres** [comment]
Released respec@22.3.4 and confirmed it's 👍

**Comment by r12a** [comment]
Seems to be working. Many thanks!
