### ISSUE TITLE
Confirm that tests exist in WPT

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1596]
Using the [github api for repo contents]( https://developer.github.com/v3/repos/contents/) we should confirm that `data-tests` files exist.

**Comment by sidvishnoi** [comment]
In this repo: https://github.com/w3c/web-platform-tests/, right? 
Or the repo and branch will be available in `conf`?

Can/Should I take this?

**Comment by marcoscaceres** [comment]
we should plan out the details and see what useful things we get back from the API. Main problem we want to solve is the 404 case, where a spec points to a missing test in `data-tests`.

**Comment by sidvishnoi** [comment]
I looked into the Github Trees API. But it gives complete repo tree (not inside some path) which means the response is unnecessarily large.

**Comment by sidvishnoi** [comment]
With https://bit.ly/wpt-transition, I think the Github trees API might be a good solution.
Should we wait for transition before adding this feature or look into the Content API (if we need it earlier)?

**Comment by marcoscaceres** [comment]
I don't see any harm in us investigating a bit. We could document here first how it would be done before we start coding anything.

**Comment by sidvishnoi** [comment]
Got a local version (running on payment-request):
![image](https://user-images.githubusercontent.com/8426945/69664979-6d761d80-10af-11ea-9702-fe4a50b8cab0.png)

Linter API is not flexible enough to provide informative warnings. It cannot tell which test is missing on which `[data-tests]`. Linter API can only tell: "these elements have failed this lint rule" (though nothing stops us `showInlineWarning` withing linter rule). I think it makes sense to add this to `core/data-tests`. What do you think?
