### ISSUE TITLE
The document license cannot be limited to the W3C Document License

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1598]
The document license is either:

(a) the permissive license
(b) a dual license if `isCCBY` is true

and the [W3C Document License](https://www.w3.org/Consortium/Legal/2015/doc-license) cannot be selected alone.

This is AFAIK a change from earlier releases, and has a significant intellectual property impact.

Recommend adding an explicit option to select the [W3C Document License](https://www.w3.org/Consortium/Legal/2015/doc-license) alone.

**Comment by marcoscaceres** [comment]
Do you have a link to a spec affected by this?

**Comment by palemieux** [comment]
https://www.w3.org/TR/2018/PR-ttml-imsc1.0.1-20180227/ and https://www.w3.org/TR/2018/PR-ttml-imsc1.0.1-20180227/ were erroneously published with the permissive license, whereas https://www.w3.org/TR/2017/WD-ttml-imsc1.0.1-20170322/ was not.

In other words, between the WD and the CR, respec.js changed the default copyright statement.

**Comment by marcoscaceres** [comment]
Ah, got it. Thanks! If you set the following:

license: “w3c”,

That should set it back to the restrictive license. 

Out of curiosity, why is the document not using the permissive license?

**Comment by marcoscaceres** [comment]
Just to be clear, all the available options are listed here: https://github.com/w3c/respec/wiki/license

**Comment by palemieux** [comment]
@marcoscaceres Setting `license: “w3c”` yields an error: _You cannot use license "w3c" with W3C Specs. Please set respecConfig.license: "w3c-software-doc" instead._

See https://rawgit.com/w3c/imsc/IMSC1.1/imsc1/spec/ttml-ww-profiles.html?license=w3c

**Comment by palemieux** [comment]
> Out of curiosity, why is the document not using the permissive license?

The specification uses the document license by resolution of the WG.

**Comment by marcoscaceres** [comment]
@palemieux, thanks for confirming and the additional info. That indeed looks like bug! 

I'll see what's going on and get that fixed for you.

**Comment by marcoscaceres** [comment]
Incoming PR. 

Doing a bit of archeology, it seems I made the change here:
https://github.com/w3c/respec/pull/1267

And related:
https://github.com/w3c/respec/commit/6b014b0da4257e000e53ac9815f0f3a41e756f9b

But I can't find the rationale complaining about "w3c" as a license.

@plehegar, apologies as we about this a while back, but is there are reason for groups to still be using the restrictive license still? I guess only for continuity or some other reason?

**Comment by marcoscaceres** [comment]
Ok, PR is https://github.com/w3c/respec/pull/1604 . Waiting on ✅ review for @plehegar or a W3C Team member.
