### ISSUE TITLE
Comment support in WebIDL

### ISSUE THREAD

**Issue by dirkschulze** [w3c/respec#160]
Support for comments in interfaces and dictionaries is missing.

I made some modifications to adapt the old behavior of respec v1 but need to figure out how to build the script :P

**Comment by marcoscaceres** [comment]
This WFM using contiguous webidl. 

<img width="359" alt="screenshot 2015-09-12 19 18 16" src="https://cloud.githubusercontent.com/assets/870154/9834323/188e2c32-5983-11e5-8f5f-c3ea66050be0.png">
