### ISSUE TITLE
Canonical URL not updated with anchor-navigation

### ISSUE THREAD

**Issue by MichielBijl** [w3c/respec#1609]
Not entirely sure if this is a ReSpec bug or an iOS bug.

## Important info

* URL to affected spec: http://w3c.github.io/aria-practices/
* ReSpec version: latest
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Expected:
URL including hash is copied—for example: http://w3c.github.io/aria-practices/#dialog

But what actually happened (the bug):
Canonical URL was copied without hash: http://w3c.github.io/aria-practices/

Optional, steps to reproduce: 
1. Navigate to one of the sections of the APG
1. Copy the URL via iOS’ share sheet
1. Paste somewhere (Notes for example)

**Comment by marcoscaceres** [comment]
ReSpec doesn't manipulate URLs on copy, so I'm guessing this is a bug in iOS. Tried on desktop browsers and was unable to reproduce.

**Comment by MichielBijl** [comment]
Yeah I couldn’t reproduce it on desktop either. I know Apple introduced this around the time AMP was released. iOS grabs the value of `<link rel="canonical" href="…">`. I’ll file a bug with iOS.
