### ISSUE TITLE
caniuse layout and click issues on mobile 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1614]
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version: Click the ReSpec pill (e.g., 20.7.0).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

what actually happened (the bug):

The boxes are shown ontop of the copyright line. 

The boxes are not responding to touch/clicks. 

Expected:
For boxes to be above copyright line and boxes to be clickable. 

Optional, steps to reproduce: 

Load on a phone.

**Comment by marcoscaceres** [comment]
Will provide a screenshot when I get to work.

**Comment by saschanaz** [comment]
Not a phone, any touchable devices are enough to repro this. Tapping should lock the popup state.

**Comment by marcoscaceres** [comment]
hover on small screen currently looks like this:

![screenshot 2018-04-05 12 51 59](https://user-images.githubusercontent.com/870154/38345101-9048a0ca-38d0-11e8-8bf1-79bf595db487.png)

Screenshot from iPhone: 
![screenshot 2018-04-05 12 58 22](https://user-images.githubusercontent.com/870154/38345215-3751400c-38d1-11e8-883a-597e05c8c425.png)

**Comment by marcoscaceres** [comment]
No biggy tho. It should be fairly straight forward to fix. Part of "beta" testing ☺️

**Comment by marcoscaceres** [comment]
I've removed this from Payment Request spec - but will re-enable it once we get this fixed.

**Comment by sidvishnoi** [comment]
This would become a lot easier if we could use nested `ul` for the content that is hidden (submenu like, basically wrapping hidden items in another container). Any chance that we may do that instead?

**Comment by marcoscaceres** [comment]
Nested ul should be ok. I thought that’s what we had already. Can you provide a quick example of what you are thinking here?

**Comment by sidvishnoi** [comment]
Was thinking of something similar. 
`<button>` is something I didn't think of.
Do we also want hover support or just want to toggle on click/touch?
