### ISSUE TITLE
Smarter caching by making use of rate limit info

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1615]
Github's API rate limits requests to HTTP's "X-RateLimit-Limit" per hour. When the rate limit is reset is indicated by the HTTP header, `X-RateLimit-Reset:` which is a unix date. We can basically use this date to work out how long we need to cache resources for (e.g., issues).  

More info: https://developer.github.com/v3/rate_limit/

**Comment by devanshbatra04** [comment]
Interesting. That should be issues, notes, contributors, commenters. We could either
1. have the DOM re render with the new assets. The user should probably have a conf option to set this. I wouldn't want my GH requests to keep running out. 
2. Just set an expire limit on the cached objects. The browser will handle the rest. If the user refreshes after the said time, the cache should have expired.

**Comment by sidvishnoi** [comment]
Closing as no longer an issue due to https://github.com/w3c/respec/pull/2536 and https://github.com/w3c/respec/pull/2538
