### ISSUE TITLE
Cannot pass an array in argument of a constructor

### ISSUE THREAD

**Issue by cdumez** [w3c/respec#162]
I have tried the following with Respec.js:
```
<dl title="[Constructor(DOMString[] type, DOMString value)] interface MyInterface" class="idl">
```

But this fails due to the array type: '[]' in the constructor. Should I somehow escape the square brackets? I haven't been able to find out how to do it.

**Comment by marcoscaceres** [comment]
WFM in using contiguous WebIDL. 

<img width="535" alt="screenshot 2015-08-03 20 26 45" src="https://cloud.githubusercontent.com/assets/870154/9045795/0afbaf06-3a1e-11e5-8191-600e29c084e8.png">
