### ISSUE TITLE
Update templates to point to new web-platform-tests location after move

### ISSUE THREAD

**Issue by foolip** [w3c/respec#1621]
Per https://bit.ly/wpt-transition w3c/web-platform-tests will move to web-platform-tests/wpt. Before it's happened we should prepare the changes in ReSpec, and once it's done those changes should be merged.

Redirects will be in place for specs that use a pinned version of ReSpec, but the new URLs should be rolled out over time.

**Comment by marcoscaceres** [comment]
I guess what ReSpec needs to do is warn if it sees any old URL. Right now, Editors configure their test suite like so:

```JS
testSuiteURI: "https://w3c-test.org/payment-request/",
```

Looking at [the usage data for testSuiteURI])(https://github.com/search?p=2&q=org%3Aw3c+testSuiteURI&type=Code), most people are pointing to "w3c-test.org" or "wpt.fyi", which I assume will continue to work as expected. 

So, it would only be the "w3c/web-platform-tests" ones we would need to change.

**Comment by marcoscaceres** [comment]
@foolip, [sent a PR for this](https://github.com/w3c/respec/pull/1622). It shows a warning: 

![screenshot 2018-04-16 15 36 06](https://user-images.githubusercontent.com/870154/38791700-88e2136a-418c-11e8-88d6-1c64fda9e0a4.png)

Can you confirm that it's ok for Editors to still point to "w3c-test.org"?  

Also, I guess it will take time to move individual projects over (I see 2018-06-01) in the doc.

**Comment by foolip** [comment]
Yeah, changing anything about w3c-test.org isn't part of this move.

I understand now that ReSpec doesn't have "w3c/web-platform-tests" baked into a template, so actually what the task for the move is to send PRs on the specs that have that string somewhere.

@marcoscaceres I think the warning would do the trick eventually, but do you know how many specs would be affected? Might it be less work to send PRs to the specs?

**Comment by marcoscaceres** [comment]
> @marcoscaceres I think the warning would do the trick eventually, but do you know how many specs would be affected? Might it be less work to send PRs to the specs?

Thankfully, looks like [less than 10](https://github.com/search?utf8=✓&q=org%3Aw3c+testSuiteURI+web-platform-tests&type=Code). So, pretty easy to do.

**Comment by foolip** [comment]
Which path would you prefer? I can update https://bit.ly/wpt-transition to use your list instead if you're not already keen to add this warning for other reasons.

**Comment by foolip** [comment]
@marcoscaceres, OK will put that into the doc, thanks!
