### ISSUE TITLE
don't create a new id when an issue is referenced more than once

### ISSUE THREAD

**Issue by siusin** [w3c/respec#1626]
## Important info

* URL to affected spec: [Resource Timing L2](https://github.com/w3c/resource-timing/commit/bcb09cc55ba958616dd9959a6b92581f29269841)
* ReSpec version: 20.7.1.
* [Y ] I did a "hard refresh", but it's still busted. 

## Description of problem

Expected: don't create a new id when an issue is referenced more than once

But what actually happened (the bug): there was a duplicate ID (issue-82) in the generated document

Optional, steps to reproduce: put `data-number="**"` twice in the same document

**Comment by marcoscaceres** [comment]
Thanks @siusin! We will try to get to it soon.
