### ISSUE TITLE
Implementation report not required for REC

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1632]
When `specStatus: "REC"` and `implementationReportURI` is missing, respec emits: _CR, PR, and REC documents need to have an implementationReportURI defined._ 

This is however inaccurate since implementation reports are not a requirement for Recommendations per the [W3 process](https://www.w3.org/2018/Process-20180201/). The implementation report might in fact misleading and/or incomplete once and after the specification reaches REC.

**Comment by marcoscaceres** [comment]
@palemieux thanks for the clarification. I'll change the `implementationReportURI` to only be required for CR. 

The following is for my own record keeping purposes, and in case this comes up again for discussion (not intended to open debate about the W3C Process, as this is not the right place to have that discussion):

> additional implementations may have become available

This probably would not be relevant after REC, as CR is based on two conforming implementations (not all conforming implementations). So, new implementations don't affect status. 

> some of the implementations may no longer be available

This is also not applicable IMO, as REC would have been reached on the basis that two implementation existed at the moment the spec left CR. 

> some implementations that failed some tests may no longer fail these tests

This has two presuppositions: 
  - First, the specification would have never left CR without two implementations passing. 
  - Second, the implementation report being static, which is not necessarily true (e.g., https://wpt.fyi is dynamic).

**Comment by palemieux** [comment]
> This probably would not be relevant after REC, as CR is based on two conforming implementations (not all conforming implementations). So, new implementations don't affect status.
> This is also not applicable IMO, as REC would have been reached on the basis that two implementation existed at the moment the spec left CR.

Exactly. The implementation report, i.e. the document used to demonstrate that every feature is supported by at least two implementations, is relevant only when transitioning from CR to PR.

> Second, the implementation report being static, which is not necessarily true (e.g., https://wpt.fyi is dynamic).

Right. I would not call this kind of deliverable an "implementation report", but rather a "test suite" or an "interoperability matrix". In other words, I would make a difference between (a) the document used to demonstrate implementation experience when transitioning to PR and (b) living artifacts used to help implementers achieve interoperability well after the document transitions to PR.

Makes sense?

**Comment by palemieux** [comment]
> @palemieux thanks for the clarification. I'll change the implementationReportURI to only be required for CR.

Thanks!
