### ISSUE TITLE
Comment filing in SOTD does not match W3M practice

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1636]
It looks like W3M has started pointing to github instead of a mailing list as a means of submitting comments.

See SOTD at https://www.w3.org/TR/2018/REC-ttml-imsc1.0.1-20180424/

It does not look like this is supported by respec.

**Comment by palemieux** [comment]
Suggest adding a link to github in the SOTD if `wgPublicList` is not specified.

**Comment by marcoscaceres** [comment]
Yeah, that would be good. Less and less groups are using mailing lists, and could definitely add this automatically.

**Comment by plehegar** [comment]
For the record, "W3M practice" is actually the rule at https://github.com/w3c/specberus/blob/master/lib/rules/sotd/mailing-list.js

**Comment by palemieux** [comment]
Any chance to fix this soon... if not, I will have to fix manually. Just let me know.

**Comment by AmeliaBR** [comment]
Related: #919

But it looks like this is now fixed for W3C specs?
https://github.com/w3c/respec/blob/7f22f1e283a9fa4be211a5e70510c1e48a29bc5b/src/w3c/templates/sotd.js#L304-L315

It would be nice to use that function for CG/BG reports, though, they still use the old text if a mailing list is specified:
https://github.com/w3c/respec/blob/7f22f1e283a9fa4be211a5e70510c1e48a29bc5b/src/w3c/templates/cgbg-sotd.js#L58-L65
