### ISSUE TITLE
Translation boilerplate does not match W3M practice?

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1637]
W3M uses the following boilerplate: _The English version of this specification is the only normative version. Non-normative translations may also be available_ instead of _See also translations_

See https://www.w3.org/TR/ttml-imsc1.0.1/

**Comment by marcoscaceres** [comment]
Sorry, what’s W3M?

**Comment by palemieux** [comment]
W3M = W3 team/management, e.g. @plehegar

**Comment by marcoscaceres** [comment]
The translation boilerplate above, is that a new text expected by PubRules?

**Comment by palemieux** [comment]
I am not sure. The boilerplate was inserted manually by W3M at publication.

The document passes pubrules: https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-ttml-imsc1.0.1-20180424%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004

**Comment by marcoscaceres** [comment]
@tripu or @deniak, have the requirements changed over at echidna regarding the translation boilerplate? Should I update ReSpec with the text @palemieux  suggests?

**Comment by deniak** [comment]
We are looking at dropping the rule (https://github.com/w3c/specberus/pull/570) but it's still being discussed within W3M. In the meantime, we are still requiring a translation link in the headers of the doc (https://github.com/w3c/specberus/blob/master/lib/rules/headers/translations.js)

**Comment by marcoscaceres** [comment]
Ah, ok. The matching is done just on the link. @palemieux, who provided that text for you? I don’t mind integrating it. Seems nicer than the current boilerplate.

**Comment by palemieux** [comment]
> @palemieux, who provided that text for you? I don’t mind integrating it. Seems nicer than the current boilerplate.

@plehegar provided the text.

**Comment by plehegar** [comment]
I shamelessly stole the text from WOFF 2. The translation database has been retired so we should stop linking to it. I would hold on this front until we know better.

**Comment by marcoscaceres** [comment]
ok, thanks @plehegar. Closing for now.
