### ISSUE TITLE
Missing js/deps/require.js?

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#1639]
## Important info

* ReSpec version: GitHub/develop branch

## Description of problem

missing js/deps/require.js

What happened (e.g., it crashed)?: 

trying to follow instructions in https://github.com/w3c/respec/wiki/Developers-Guide to modify
js\w3c\templates\sotd.html and provide a patch for the w3c-common profile. Did npm install, etc.

When trying to run the following command:
  node ./tools/builder.js --profile=w3c-common
("Working with your new profile", https://github.com/w3c/respec/wiki/Developers-Guide
 )

I get 
{ Error: Error: ENOENT: no such file or directory, open 'C:\Users\Philippe Le Hegaret\Git\publication\respec\js\deps\require.js'
    at Object.fs.openSync (fs.js:646:18)

But what I was expecting?:

Success, ie a new build to test my modification on an example.

**Comment by marcoscaceres** [comment]
The instructions were indeed out of date. It should have said `build:components` instead of just "build", which copies over all the dependencies. 

I've updated the docs to say: 

```Bash
npm install
npm run build:components
npm start
```

Apologies for that! now fixed.
