### ISSUE TITLE
[META] Support ES Modules

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1640]
When Firefox 60 lands in May, we will have ES module support across all target browsers. That means we can start considering using them in ReSpec. 

We should evaluate what that means for our current plugin design and for the dependencies (which are not ES Modules). With dynamic `import()` support, we can basically get rid of RequireJS. 

Ideally, we would then have ReSpec do this:

 1.  load a light stub (or some kind of master stub) for a plugin. These stubs intelligently determine if a plugin is needed: for example, "does this document require syntax highlighting? does this document use WebIDL?" and so on..
 1. For each "yes" stub, it would asynchronously kick off download of each needed module. These modules would have good cache control headers set (we could serve them from either the W3C server, or via respec.org, where we control the HTTP cache settings).
 1. Then we split the modules into group: needs further processing (e.g., anything that needs xrefs), or standalone (e.g., caniuse). 

Just some lose thoughts for now... but it's exciting because potentially this will make ReSpec super tiny, with each spec only loading just what it needs. Right now, we load everything, and that's super wasteful. The modules can be cached, and shared across specs... that may lead to interesting versioning issues, but we can deal with that. 

Thoughts?

**Comment by saschanaz** [comment]
A downside is more round trips for the first visit, which is probably okay.

**Comment by saschanaz** [comment]
Firefox 60 has landed 🎉

**Comment by saschanaz** [comment]
>With dynamic import() support

It seems MSEdge on April 2018 update does not support dynamic import() yet.

**Comment by saschanaz** [comment]
@marcoscaceres You recently said you are planning to use Webpack/Rollup. Do we still ultimately want to do ES modules then?

**Comment by marcoscaceres** [comment]
Closing, as I think we will still want to bundle everything for the foreseeable future. 

We can always look at this again down the road... and, in fact, it kinda already works... we just don't deploy ReSpec this way.
