### ISSUE TITLE
Harmonizing var highlight colors with BikeShed

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1649]
It would be great if we could come to an agreement between Bikeshed's selection of color palette and that of ReSpec, keeping accessibility in mind.

Here are the present colors:
<img width="300" src ="https://user-images.githubusercontent.com/8426945/39535049-927c6df0-4e50-11e8-8270-41f6894330f1.png">

I've also added a [preview gif](https://github.com/w3c/respec/wiki/highlightVars) for ReSpec's highlightVars in action. We used colors inspired by GitHub labels.

ReSpec renders like this:
![screenshot 2018-05-03 14 57 16](https://user-images.githubusercontent.com/870154/39560580-90fa140e-4ee2-11e8-9a48-c34da468b48e.png)

Would people prefer BikeShed's colors? ReSpec's colors? Or something else?

**Comment by marcoscaceres** [comment]
Screenshots would be really helpful above.

**Comment by sidvishnoi** [comment]
Here are the present colors:
![screenshot from 2018-05-02 21-34-00](https://user-images.githubusercontent.com/8426945/39535049-927c6df0-4e50-11e8-8270-41f6894330f1.png)

For those who want to try them out: https://codepen.io/sidvishnoi/pen/YLVMgV

I've also added a preview gif for ReSpec's highlightVars in action: https://github.com/w3c/respec/wiki/highlightVars

**Comment by marcoscaceres** [comment]
@sidvishnoi, could you close this bug and reopen it here:

https://github.com/w3c/tr-design/

That will give us a neutral space in which to discuss harmonization.

**Comment by sidvishnoi** [comment]
Closing in favour of https://github.com/w3c/tr-design/issues/152
