### ISSUE TITLE
"stod" typo in src/w3c/headers.js?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1656]
Sorry, not following the issue template. I just stumbled into what looks like a typo while having a look at the code. I don't even know whether this has any practical impact on existing specs.

At: https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L520
I suspect `stod` should be `sotd`.

You might want to update the variable name in https://github.com/w3c/respec/blob/develop/tests/spec/w3c/headers-spec.js#L1018 as well.

**Comment by marcoscaceres** [comment]
oopsy! PRs sent!
