### ISSUE TITLE
link-to-dfn module may report a TypeError

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1666]
## Important info

* URL to affected spec: https://wicg.github.io/InputDeviceCapabilities/
* ReSpec version: 20.10.4
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
TypeError reported by Respec while generating the spec
```
TypeError​columnNumber: 9296
​fileName: "https://www.w3.org/Tools/respec/respec-w3c-common"​lineNumber: 442​
message: "t[0] is undefined"​
stack: "
e.run/<@https://www.w3.org/Tools/respec/respec-w3c-common:442:9296
each@https://www.w3.org/Tools/respec/respec-w3c-common:1:81330
each@https://www.w3.org/Tools/respec/respec-w3c-common:1:80010
e.run@https://www.w3.org/Tools/respec/respec-w3c-common:442:8391
s/</<@https://www.w3.org/Tools/respec/respec-w3c-common:1:63855
s/<@https://www.w3.org/Tools/respec/respec-w3c-common:1:63654
e.runAll@https://www.w3.org/Tools/respec/respec-w3c-common:1:63264
"​__proto__: Object { stack: "", … } require.js:1
  e.runAll require.js:1
```

But what I was expecting?:
No error... or a more meaningful error if the spec needs to be fixed.

Error is triggered because the code tries to access [`linkTargets[0]`](https://github.com/w3c/respec/blob/79d0497ecb1a82f953d27526f7de429641c1da36/src/core/link-to-dfn.js#L118) whereas the array is empty.

**Comment by marcoscaceres** [comment]
@sidvishnoi's going to look into it! Thanks for the link to the spec, @tidoust.

**Comment by marcoscaceres** [comment]
We found a couple of issues. The CG template should complain in the "wg" is not set. And the linkTargets should not crash when it encounters an empty `<a>`.
