### ISSUE TITLE
Document linter rules

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1669]
We don't have documentation for the linter rules. We should document them: 

- [x] no-headingless-sections
- [x] no-http-props
- [x] privsec-section
- [x] check-punctuation
- [x] local-refs-exist

We should also document how to create them from a developer perspective.

**Comment by pradeepgangwar** [comment]
@marcoscaceres Should I edit these in wiki directly?

**Comment by marcoscaceres** [comment]
I’d suggest we do the first round here, then we can edit them together. Then we can migrate the resulting text to the wiki.

**Comment by pradeepgangwar** [comment]
Sure. I will add the documentation here in few hours. Thanks. :)

**Comment by pradeepgangwar** [comment]
# `check-punctuation` lint rule

Enable this lint rule to check for punctuation. This makes sure that there are no punctuations missing at the end of `<p>` tag.

For example:
```
<p> This has no punctuation at the end <p>
```
You will receive a warning that your `<p>` tag should end with punctuation mark.

## Example of usage

```
var respecConfig = {
  lint: {
    "check-punctuation": true,
  },
}
```

## Example Warning
![screenshot_2019-02-11 replace me with a real title](https://user-images.githubusercontent.com/21259802/52548132-cd862680-2df1-11e9-95d2-f316425f44e5.png)

**Comment by pradeepgangwar** [comment]
@marcoscaceres Please check the documentation i posted in above comment. :)

**Comment by marcoscaceres** [comment]
This is good, but exclude the "Example Warning".

**Comment by pradeepgangwar** [comment]
Done.

**Comment by marcoscaceres** [comment]
> This makes sure that there are no punctuations missing at the end of `<p>` tag.

This might be overly specify. But maybe say:

It checks for:

  * full stops at the end of `<p>` tags.

**Comment by marcoscaceres** [comment]
(we might add more things eventually, like checking for full stops, :, etc. in `li` elements.

**Comment by pradeepgangwar** [comment]
> 
> This might be overly specify. But maybe say:
> 
> It checks for:
> 
>     * full stops at the end of `<p>` tags.

Done. Should I specifically say `full stops` or punctuation mark is ok?

**Comment by marcoscaceres** [comment]
yeah, you are right... it should say "checks that `<p>` tags end with a punctuation mark.".

**Comment by pradeepgangwar** [comment]
# `check-punctuation` lint rule

Enable this lint rule to check for punctuation. It checks for:
- Punctuation mark at the end of `<p>` tag. It should end with any of  ".", ":", "!", "?".

For example:
```
<p> This has no punctuation at the end <p>
```
You will receive a warning that your `<p>` tag should end with punctuation mark.

## Example of usage

```
var respecConfig = {
  lint: {
    "check-punctuation": true,
  },
}
```

**Comment by marcoscaceres** [comment]
Made some changes to the above comment - and enabled syntax highlighting on the example blocks. Looks good to add to the wiki.

**Comment by pradeepgangwar** [comment]
@marcoscaceres Added to wiki. :D

**Comment by marcoscaceres** [comment]
Added privsec linter rule to docs.
