### ISSUE TITLE
Large images appear stretched

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1678]
## Important info

* URL to affected spec: [Extensions to the Semantic Sensor Network Ontology](https://w3c.github.io/sdw/proposals/ssn-extensions/)
* ReSpec version: 20.11.1.
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?:
Figure in [section 3.1](https://w3c.github.io/sdw/proposals/ssn-extensions/#ultimate-feature-of-interest) appears stretched (I will recommend a workaround to the editor, so the problem may already appear to have been fixed when you look at it but see below)

But what I was expecting?:
Image ratio being preserved.

Optional, steps to reproduce:
1. Take a large image (typically larger than 800px) such as the [one in the spec](https://w3c.github.io/sdw/proposals/ssn-extensions/images/observation-foi-patterns.png)
2. Reference it in a spec without specifying its `width` and `height`, e.g. with
```html
<figure>
  <img alt="..." src="observation-foi-patterns.png"/>
  <figcaption>...</figcaption>
</figure>
```
3. If the image is larger than 800px, it will appear stretched, otherwise just reduce the width of the browsing window.

I believe this happens because of #923, where ReSpec adds the natural width and height of the image. Problem is [`base.css`](https://www.w3.org/StyleSheets/TR/2016/base.css) has a `max-width` property for images:
```css
.figure img,    .sidefigure img,    figure img,
.figure object, .sidefigure object, figure object {
	max-width: 100%;
	margin: auto;
}
```
... which shrinks the width as needed, but does not touch the height.

Not sure what is the best way to fix that. Adding a `height: auto` rule to `base.css` would be enough to preserve the image ratio for instance.

**Comment by marcoscaceres** [comment]
ReSpec tries to correct images without width and height, as when those attributes are missing it  causes layout thrashing and it's a symptom that something is probably wrong with the image (in this case, they are way overlarge).  

Two options:
  1. fix the image size to make them something that fits. 
  1. Or, set `width=""` and `height=""`. That tells ReSpec to leave the image alone, and let's it stretch. 

However, that spec should really make the images smaller or use SVG for those diagrams, given that they are full of text and lines.

**Comment by tidoust** [comment]
OK, in the end, the issue is that `base.css` auto-shrinks the width of images without preserving the image ratio.

The problem occurs with reasonably-sized SVG images as well by the way. See for instance
[Figure 1 in Web App Manifest](https://w3c.github.io/manifest/#content-security-policy) if you reduce the width of the browser window (or view the spec on a mobile device in portrait mode): the intrinsic ratio is preserved because SVG brings some magic, but the image container's height remains unchanged as the image width gets reduced, resulting in large top and bottom margins around the image:

![screenshot](https://user-images.githubusercontent.com/1122927/40474066-47292268-5f3e-11e8-8e88-f7fa770ac657.jpg)

Anyway, that's not a ReSpec issue!

**Comment by marcoscaceres** [comment]
> Anyway, that's not a ReSpec issue!

Closing, based on above.
