### ISSUE TITLE
Add CSS for :target

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1683]
For example, on https://w3c.github.io/payment-request/#bib-payment-method-basic-card, one cannot find `[payment-method-basic-card]` easily as it's on bottom of page where it can't be scrolled to based on URL fragment. One has to make eye movement all the way down to bottom to find it.

It would be nice if there is a little CSS on `:target` which lets one focus easily where the hash link lead to.

<img width="400" src="https://user-images.githubusercontent.com/8426945/40579055-4e457a0a-613d-11e8-896c-82fbd776caf7.png">

_It's not easy to find `[payment-method-basic-card]` in this image_

**Comment by marcoscaceres** [comment]
Agree, some kind of emphasis would be nice. I think Wikipedia does something similar, so maybe we can look at their style.
