### ISSUE TITLE
Include MDN Compat data

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1693]
Where there is MDN compat data available, we should show it somehow:

https://github.com/mdn/browser-compat-data

**Comment by CodHeK** [comment]
@marcoscaceres can I work on this ? Also, if possible could you please elaborate on the issue ?

**Comment by CodHeK** [comment]
@marcoscaceres  I went through the links, isin't it similar to the caniuse module respec already has, only more verbose.

**Comment by marcoscaceres** [comment]
Correct, but more accurate as it goes down to the methods and attributes level.

**Comment by CodHeK** [comment]
Okay so are we trying to replace caniuse with this for the long run ?

**Comment by marcoscaceres** [comment]
Maybe... caniuse is great if as a web developer you want to know if you can rely on a whole feature (and it's also "other developers says I can use this safely"). The MDN data is a bit more specific - it's targeted at both web developers and browser developers. Like, I can see specifically which version supports a particular method. 

Maybe in the long run they will converge, but for now it's ok for them to be separate. Hope that makes sense!

**Comment by himanish-star** [comment]
@marcoscaceres, taking a look into this issue :)

**Comment by marcoscaceres** [comment]
Closed via #2110
