### ISSUE TITLE
Refactor all jquery-enhanced utils to vanilla js while keeping backward compatibility

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1699]
Refactor all core/jquery-enhanced.js utils to vanilla js (in core/utils) while keeping backward compatibility and use vanilla js DOM utils in ReSpec.
- Modules:
  - [x] $.makeID -> addId (https://github.com/w3c/respec/pull/1691)
  - [x] $.allTextNodes -> getTextNodes (https://github.com/w3c/respec/pull/1698)
  - [x] $.renameElement -> renameElement (https://github.com/w3c/respec/pull/1806)
  - [x] $.getDfnTitles -> getDfnTitles (https://github.com/w3c/respec/pull/1746)
  - [x] $.linkTargets -> getLinkTargets (https://github.com/w3c/respec/pull/1785)
- [x] Move tests from `jquery-enhanced-spec.js` to `utils-spec.js` (https://github.com/w3c/respec/pull/1838)
- [ ] Add deprecation notice to jquery-enhanced

**Comment by marcoscaceres** [comment]
Closing as done. Looking at making a new W3C profile that excludes jQuery.
