### ISSUE TITLE
Use eslint on Travis

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1711]
Currently Codacy uses eslint but it's not fully customizable and it only shows error for new issues. Maybe we can use eslint directly.

**Comment by marcoscaceres** [comment]
> it only shows error for new issues

This is actually Codacy's best feature.

But I agree that our linting story is sad and needs to be fixed.

**Comment by marcoscaceres** [comment]
@saschanaz, this can be closed now, right?

**Comment by saschanaz** [comment]
Yup, closed by #1777
