### ISSUE TITLE
Add linter rule for internal slots

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1713]
Internal slots need to be preceded by a "."... so:

```HTML
<var>foo</var><a>[[\bar]]</a>.
```

Should make ReSpec upset.

**Comment by marcoscaceres** [comment]
Note to self... something along the lines: 
```JS
[...document.querySelectorAll("var+a")].filter(a => a.textContent.startsWith("[[") && a.previousSibling.textContent !== "." )
```

**Comment by saurabhmittal16** [comment]
Hi, I was interested in working on this, could you explain the issue and where to get started?
Thanks

**Comment by sidvishnoi** [comment]
Hi @saurabhmittal16 👋 
First have a look at our [Developers Guide](https://github.com/w3c/respec/wiki/Developers-Guide). You'll need to create a lint rule in [core/linter-rules](https://github.com/w3c/respec/blob/develop/src/core/linter-rules/). 
For a reference on how to create a linter rule, have a look at [local-refs-exist linter rule](https://github.com/w3c/respec/blob/develop/src/core/linter-rules/local-refs-exist.js). It should provide plenty of insight. If not, we'll be here to help.

In this rule:

``` html
<!-- following should be valid -->
<var>foo</var>.<a>[[\bar]]</a>
<!-- but this should be invalid, hence provide a linter warning -->
<var>foo</var><a>[[\bar]]</a>
```

**Comment by yatri1609** [comment]
@sidvishnoi @marcoscaceres I would like to work on this. Can I go ahead with this?

**Comment by saurabhmittal16** [comment]
Hi @sidvishnoi, thanks for the information
I will update her as soon as possible
