### ISSUE TITLE
W3C logo showing up in unofficial drafts? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1725]
## Important info

* URL to affected spec:
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
@nicky508 wrote: 

> It is not possible to override the W3C logo in an unofficial logo any more and therefore one is not able to use logos in a unofficial draft.

What happened (e.g., it crashed)?: 

But what I was expecting?:

To have no logo. 

Optional, steps to reproduce:
 1. ...

**Comment by nicky508** [comment]
Important info

    URL to affected spec: 
    ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
   Yes - I did a "hard refresh", but it's still busted.

Description of problem
The W3C logo is removed from the unofficial drafts. In the past it was possible to override the W3C logo with your own logo. Now the W3C logo is removed, it is not possible to override it and put your own logo on the draft instead.

What happened (e.g., it crashed)?:
Specifying a logo in the respec, but it is not shown in the draft.

But what I was expecting?:
My own logo (which is specified in the respec) appearing in the right upper corner.

Optional, steps to reproduce:
None.

**Comment by sidvishnoi** [comment]
Why is this being done?
https://github.com/w3c/respec/blob/cf5651238b15060fe4f7c8b141a5ed7908e4f477/src/w3c/headers.js#L231-L233

This was done in https://github.com/w3c/respec/commit/f16890dccf7332a57af1ed9b9d6d5611c6881d52 (fix: double logos in cg spec (closes #1286))

**Comment by marcoscaceres** [comment]
Working on fix.
