### ISSUE TITLE
Unhelpful error details 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1741]
## Important info

* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
the first part is helpful, but the details are not:

<img width="532" alt="screenshot 2018-07-06 10 09 19" src="https://user-images.githubusercontent.com/870154/42383408-2249beec-8105-11e8-8aba-96c4d7465b34.png">

What happened (e.g., it crashed)?: 
It showed me JS errors... I don't care about those. 

But what I was expecting?:
To not see JS errors. 

Optional, steps to reproduce:
 1. Make some IDL attribute, and then define it twice.

**Comment by sidvishnoi** [comment]
Should be caused on any `pub("error")` as:
https://github.com/w3c/respec/blob/b571192c7d7b9f09872e371c6245f740e9546511/src/core/pubsubhub.js#L63-L65

**Comment by saschanaz** [comment]
I agree we can just remove it as AFAIK error stacks are visible via dev tools.

**Comment by marcoscaceres** [comment]
Agree

**Comment by ThobyV** [comment]
Would love to work on this issue @marcoscaceres. I'm pretty new, looking for work to get things started.

**Comment by marcoscaceres** [comment]
Just checked... was actually fixed at some point.
