### ISSUE TITLE
IDL Index looks too condensed

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1745]
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version: 22.1.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

![image](https://user-images.githubusercontent.com/3396686/42450007-bd8d68c6-83bd-11e8-97bf-a500152ac259.png)

But what I was expecting?: Less condensed IDL definitions (spaces between definitions)

**Comment by marcoscaceres** [comment]
The optional issue should be fixed in respec 22.2.0. But yeah, should probably add a new line (or actual padding) between each idl block.

**Comment by marcoscaceres** [comment]
actually, no... the optional issue is still there. Definitely need to fix that, as it's actually dropping the space.

**Comment by saschanaz** [comment]
#1747 does not fix the condensing issue.

**Comment by marcoscaceres** [comment]
Ah, true. Thanks! I was thinking best option is to add a new line, and not padding.

**Comment by marcoscaceres** [comment]
@saschanaz, do you want to take this one?
