### ISSUE TITLE
META(core/xrefs): requirements for API endpoint

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1757]
Requirements for keyword based search endpoint to CSSWG's Shepherd database. As a part of https://github.com/w3c/respec/issues/1662.

We expect to POST a top-level JSON object. The object has the following properties:
 
 * `options` (optional, Object).
 *  `keys` (Array).

Which are described in detail below. 

## Example of POSTed message

``` http
POST /xrefs
Content-Type: application/json
Accept: application/json

{
  "options": {
    "fields": ["type", "normative", "uri"],
    "export": true,
    "spec_type": ["draft"],
    "types": ["dfn", "interface"]
  },
  "keys": [
    {
      "term": "Foo",
      "specs": ["spec1", "spec2"],
      "types": ["interface"]
    },
    {
      "term": "foo bar",
      "specs": ["spec1"],
      "types": ["_CONCEPT_"]
    },
    {
      "term": "bar"
    }
  ]
}
```

## Example JSON Response

``` json
{
  "data": {
    "Foo": [
      {
        "spec": "spec2",
        "type": "interface",
        "uri": "somepage#foo",
      }
    ],
    "foo bar": [
      {
        "spec": "spec1",
        "type": "dfn",
        "uri": "#foo-bar"
      }
    ],
    "bar": []
  }
}
```

## `options` property

The `options` helps limit the amount of data being requested. Also provides an extensibility mechanism. 

It optionally contains the following sub properties:

 * `fields` array
 * `spec_type` array.
 * `export` boolean
 * `types`array.

#### `fields` property (Array)

Default: `["spec", "type", "for", "normative", "uri", "title"]` (i.e., send back everything).

The response would contain only specified fields. Example: `"fields": ["uri", "spec"]`

#### `spec_type` property (Array)

Default: `["draft", "official"]`

If the option is not present, there is no filtering done based on `spec_type`.

If value is an array single element, then only those type of specs are used. For example, `"spec_type": ["draft"]` means we are only looking for "draft" specs.

If value is an array of two elements, then the results of first type are preferred. If there are no matches for first type, only then second type of results are searched. For example, `"spec_type": ["draft", "official"]` means prefer data from "draft" specs, if no data found from draft specs, then look for "official" specs.

#### `export` property (Boolean)

Default: false (return everything)

If we only want the terms that are exported from some document (`export` field in Shepherd data), we can set this option to `true`.

If the option is not present, all terms are searched for (i.e., do not filter based on `export` field in data). This is the default setting.

#### `types` property (Array)

If the `types` for a `key` are not provided, then these (option) `types` are used to filter data. For example, `"types": ["dfn", "interface", "heading"]` means that we only require data of these given types.

If the (option) `types` are not provided but types are specified with the `key`, then only those (key) types are looked for.

If the (option) `types` are not provided, and if no types are specified for a key, then there is no filtering based on `types`. This is the default setting.

## General Requirements

- Each `key` of `keys` in request body contains a mandatory `term` to search for and some optional "context" to reduce ambiguities. The context may contain:
  - `specs` (String[]) - short-names of documents to search in
  - `types` (String[]) - type of term (could be `dfn`, `interface` etc.)
  - `for` (String)  - Example: `{ term: "event", for: "Window" }` means we are looking for the term "event" defined in context of "Window" (i.e. `Window.event`)

- The search for a `term` on back-end should be case insensitive by default. If `types` for a `term` belong to `IDL_TYPES`, then only the search should be case sensitive.

-  All data matching the term should be returned, unless some info to disambiguate is provided.

- The `specs` and `types` are optional but recommended attributes for each term. With ReSpec, `types` will be an array of at least one element. ReSpec will try it's best to identify the exact `type`, but if it cannot do so, it'll send some special keywords (viz. `_CONCEPT_`, `_IDL_`), as follows:
  - `_CONCEPT_`: includes concept types : "dfn", "event", "element"
  - `_IDL_`: includes IDL types:  "attribute", "dict-member", "dictionary", "enum", "enum-value", "interface", "method"

- The `linking_text` attribute in Shepherd data should be treated as same as `title` attribute and be available for search as `term`. For example, with `{ term: "create an event" }` or `{ term: "creating an event" }` (defined in "DOM" spec with type "dfn"), the results returned should be same.

- If no data is found for a `key`, either do not return that key in response, or return it as an empty array. So both of following are valid and are left at discretion of the implementor:

``` json
{ "key": [] }
{ }
```

- The query may contain same `term` multiple times but with different context (i.e. specs/types). The response should return all matching data. Example:

HTTP request's body:
``` json
{
  "keys": [
    { "term": "object", "specs": ["webidl", "dom"] },
    { "term": "object", "specs": ["html"] }
    { "term": "object", "specs": ["a-spec-not-in-shepherd"] }
  ]
}
```

Expected HTTP response's body:

``` json
{
  "data": {
    "object": [
      {
        "spec": "html",
        "type": "element",
        "uri": "iframe-embed-object.html#the-object-element",
      },
      {
        "spec": "webidl",
        "type": "interface",
        "uri": "#idl-object",
      }
    ]
  }
}
```

Comments for above:

- The term `object` doesn't exist in "dom", so no result corresponding to it is returned.
- The spec `"a-spec-not-in-shepherd"` is not tracked by shepherd, so no data is returned for it.
- Data exists for given `term` in both "webidl" and "html". Both are returned with single `term` in response as an array.

**Comment by sidvishnoi** [comment]
A temporary endpoint as a playground for Xrefs API: https://wt-466c7865b463a6c4cbb820b42dde9e58-0.sandbox.auth0-extend.com/xref-proto-2

**Comment by saschanaz** [comment]
Why POST instead of GET?

**Comment by sidvishnoi** [comment]
@saschanaz See https://github.com/sidvishnoi/respec-xref-route/issues/10

**Comment by sidvishnoi** [comment]
Closed via https://github.com/marcoscaceres/respec.org/pull/2, https://github.com/marcoscaceres/respec.org/pull/3
