### ISSUE TITLE
Incorrect extended attribute in IDL causes silent failure

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1760]
## Important info

* URL to affected spec:
* ReSpec version: 22.3.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Try inserting this in examples/basic.html:

```webidl
[CustomExtendedAttribute="wow"]
interface Foo {
  attribute Bar bar;
  void doTheFoo();
};
```

What happened (e.g., it crashed)?: The webidl module fails only with a console message.

But what I was expecting?: No failure

**Comment by saschanaz** [comment]
Turns out that webidl2.js somehow supports the `[ExtAttr="stringliteral"]` syntactically-extended style but ReSpec doesn't know about it. Supporting it is easy, but should we?

**Comment by saschanaz** [comment]
> but warn that it’s a bit non-standard?

We may do it via w3c/webidl2.js#138.

**Comment by saschanaz** [comment]
@marcoscaceres 

So another important point here is that a silent failure happens in ReSpec. I think we may add `pub("fatal", err)` so that a user can be notified that a bug just happened. What do you think?

**Comment by marcoscaceres** [comment]
Fatal could be good, so long as we don’t show the stack. Then we can console.error() for that

**Comment by marcoscaceres** [comment]
We can now define `CustomExtendedAttribute` in the document, otherwise xref tries to link to it. I'm going to go ahead and close this, because the behavior seems good.

**Comment by saschanaz** [comment]
Per https://github.com/w3c/respec/issues/1760#issuecomment-405912359 this is not just a linking problem. Did you try the actual behavior?

**Comment by marcoscaceres** [comment]
I did, but maybe I missed something? It didn't cause any errors and everything looked ok. Please reopen if you think we should do more here.

**Comment by saschanaz** [comment]
I tried this and you're right, it doesn't cause any errors. Probably because ReSpec replaced its own writer with webidl2.js one.
