### ISSUE TITLE
[FEATURE REQUEST

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/respec#1761]
## Important info

* URL to affected spec: https://rawgit.com/w3c/imsc/imsc1.1-cr2/imsc1/spec/ttml-ww-profiles.html#references (hopefully will move to https://www.w3.org/TR/ttml-imsc1.1/ at some point soon)
* ReSpec version: 22.0.1.
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

When specific dated references to external specs are needed, the specref id is often cumbersome, e.g. `ttml2-20180628`, but do not need to stay cumbersome in the generated document.

The feature request is to be able to specify a config option to alias a shorter string to the specref id. For example in this case, a better ref id would be just `ttml2` - the only place that needs to use a specific specref id is in the reference section itself, where the details are extracted.

I'm ambivalent about whether the link in the document body should be either:

1.  `[[!ttml2-20180628]]` whose appearance is changed to `[TTML2]` in the document body, and in the key in the reference section, OR
2. `[[!TTML2]]` with a mapping in the references section to _whatever would have happened if we'd used `[[ttml2-20180628]]`_

Either would work. It would need to be an error state if the same alias was used for more than one specref id.

[Update: apologies for hitting Enter instead of tab when creating this issue and potentially generating a garbage email notification]

**Comment by marcoscaceres** [comment]
@nigelmegitt, you can do the following:

Add the following to your config: 
```JS
        localBiblio: {
          "ttml2": {
            aliasOf: "ttml2-20180628"
          }
        }
```

And then, just cite:

```HTML
<p>Like this [[!ttml2]].</p>
```

And it should show up in the references as "ttml2".

**Comment by nigelmegitt** [comment]
Awesome, thank you! And @palemieux, see https://github.com/w3c/respec/issues/1761#issuecomment-405624624
