### ISSUE TITLE
Support `Assert:` in algorithms

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1762]
Be nice if `Assert:` appears in an algorithm's `<li>`, ReSpec highlights the line.

**Comment by thakurdivyanshu** [comment]
can i work on this??

**Comment by marcoscaceres** [comment]
Sure! Got for it. Is the description clear enough?

**Comment by Swapnilr1** [comment]
Can I work on this issue if it is not already in progress? @marcoscaceres Could you please explain in more detail what is required? I am new here.

**Comment by sidvishnoi** [comment]
Hi @Swapnilr1 👋 
Have a look at https://w3c.github.io/payment-request/#paymentrequest-updated-algorithm (list item 1):

> Assert: request.[[updating]] is false. Only one update can take place at a time.

We need to identify such lines and highlight them.
Feel free to ask if you have any questions. I'll be here to help.

**Comment by Swapnilr1** [comment]
@sidvishnoi Just to confirm, is this effect OK? Changing <li> Assert:... </li> to <li><mark> Assert:... </mark></li> ?

![highlightassert](https://user-images.githubusercontent.com/35957512/50273290-43a88580-0460-11e9-9038-129db9e2b2c1.png)

**Comment by marcoscaceres** [comment]
We probably just want the `<li>` to gain a CSS class "asset". Alternatively, we could wrap the `Assert:` with a `<span class="assert">`.

**Comment by sidvishnoi** [comment]
Although this looks good, it would be better if we add a class to `<li>` like `.assert`.
About the style, I think @marcoscaceres should tell that.

**Comment by marcoscaceres** [comment]
@divyanshu132 take a look at https://heycam.github.io/webidl/ ... it uses "assertion" and has a style definition. We basically want to copy that :)

**Comment by Swapnilr1** [comment]
@marcoscaceres @sidvishnoi Thanks a lot for the explanation. So I should just write JS code to add class "assert" for Assertions in lists, and then the style can be set in the CSS?

**Comment by Swapnilr1** [comment]
Extremely sorry for the delay, but I am not sure where to implement this feature. To the best of my understanding, I should write the JS code somewhere in `src/core` but I am unable to figure out where? The JS files in that folder apply formatting to different tags/content, but I am not able to find a JS file appropriate for algorithm lists. 

Could someone please guide me? Also is there an IRC channel for development help?

**Comment by sidvishnoi** [comment]
You can do this in `core/inlines`.
But better would be creating a `core/algorithms` module. Don't forget to add it to [js/profile-w3c-common.js](https://github.com/w3c/respec/blob/develop/js/profile-w3c-common.js)

**Comment by Swapnilr1** [comment]
I suppose this is closed with pull requests 1987 and 2009.

**Comment by marcoscaceres** [comment]
@Swapnilr1, thanks for the reminder!
