### ISSUE TITLE
Multiple dfn with the same name

### ISSUE THREAD

**Issue by npm1** [w3c/respec#1768]
## Important info

* URL to affected spec: https://w3c.github.io/hr-time
* ReSpec version: 22.3.1

## Description of problem
The spec has a warning:

`Missing <dfn> for Performance interface.`

In the spec, we have:

- A  `<dfn>Performance</dfn>` in a section with `data-dfn-for="Performance"  data-link-for="Performance"`.

- A `<dfn>performance</dfn>` in a section with `data-dfn-for="WindowOrWorkerGlobalScope"  data-link-for="WindowOrWorkerGlobalScope"`.

It seems that the two dfns being the same name is causing the problem. In particular, there are two problems:

1.  "Performance" title in section 5 is not orange (but fortunately links to it do work).
2. The link to "Performance" in section 6 in `readonly    attribute Performance performance;` is to the attribute instead of the interface (even if I try to add a data-link-for for "Performance").

Not sure if this is an issue with ReSpec or if there's a way to fix this?

**Comment by saschanaz** [comment]
It seems #1508 is related.

**Comment by marcoscaceres** [comment]
@saschanaz, Yeah :( Still not figured this out. Trying to find time to dig into it. I've got a bunch of conference talks next week, so right now super busy on those. Will try to look into in August unless anyone else can take it. 

@sidvishnoi, did you see anything useful/helpful while you were investigating?

**Comment by sidvishnoi** [comment]
It is related to #1508 as @saschanaz  mentioned and not a regression.

During some playing, I found keeping IDL case-insensitive resolves this. So,
 - `core/utils@getDfnTitles()` needs to return non-lowercase titles for IDL
 - https://github.com/w3c/respec/blob/01907217105dffa420a23717485c3cf07ae8eb3b/src/core/webidl.js#L656 needs to use `originalName` instead of `name`

By doing the above during investigation, I was able to to fix this issue. Although, I triggered another linking error (probably missed some case-sensitive conversion somewhere)

**Comment by marcoscaceres** [comment]
Fix didn't seem to work on the actual spec, tho it worked in our tests. Need to check what's going on.

**Comment by marcoscaceres** [comment]
Ok, so it's a bit better. At least the IDLType is linking, but the first `dfn` for `Performance` is not being matched. 

@sidvishnoi, would you mind having another look and doing some more experimentation? I think this can be reduced down to a very test case. You just need an  `interface  Performance {};` and a `<dfn>Performance</dnf>`, and another interface `interface Conflict { attribute Performance erformance; }` and:

```HTML
<section>
   <dfn>Performance</dfn> interface.
</section>
<section data-dfn-for="Conflict">
  <dfn>Conflict</dfn> interface.
  <dfn>performance</dfn> attribute.
</section> 
```

**Comment by sidvishnoi** [comment]
Okay. Had a play with this. I think it is time we make `definitionMap` case sensitive for IDL (it worked [_almost_](https://user-images.githubusercontent.com/8426945/43523144-09ce6624-95b9-11e8-813a-31391fb61d6d.png) well as I tried) as I think everything else will be a "workaround". Do we have some reason to not do it yet?

**Comment by marcoscaceres** [comment]
No reason. What means do we to reliably identify IDL?

**Comment by sidvishnoi** [comment]
> What means do we have to reliably identify IDL?

We can check if dfn's term (`textContent`/`data-lt`) exist in some `pre.idl`. We might need to pre-process a `Set` of IDL terms. Not sure here. You and @saschanaz  have more experience with IDL things.

**Comment by marcoscaceres** [comment]
Maybe just `<dfn data-dfn-type=“idl”>Foo</dfn>` for now, then we can make it smarter?

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/respec/pull/1792
