### ISSUE TITLE
WPT tests button looks broken on Edge

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1769]
## Important info

* URL to affected spec: https://w3c.github.io/hr-time/
* ReSpec version: 22.3.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: WPT tests button is broken because [Edge does not supports `<details>` and `<summary>` yet](https://caniuse.com/#feat=details). Even the latest Edge 18 preview does not.

But what I was expecting?:

It should also work on Edge, or at least it shouldn't look this way.

![image](https://user-images.githubusercontent.com/3396686/43245262-9deb5306-90e8-11e8-915b-f4f0c4356123.png)

**Comment by saschanaz** [comment]
Will be great if it's small and lightweight enough.

**Comment by sidvishnoi** [comment]
also, we should handle this overflow causing scrollbars to appear.

![scrolls](https://user-images.githubusercontent.com/8426945/49341832-f4e5a800-f678-11e8-9bc1-eec97afa18f3.gif)

**Comment by marcoscaceres** [comment]
@saschanaz I guess we WONTFIX the Edge aspects anymore.

**Comment by saschanaz** [comment]
@marcoscaceres Edge 18 is just out, and I think we'll also see Edge 19 based still on EdgeHTML (as the latest preview have some changes). So IMO not yet.

**Comment by marcoscaceres** [comment]
Ok, I guess the least we can do is grab the default HTML for those elements?

**Comment by marcoscaceres** [comment]
Oops, I mean the default CSS!

**Comment by ThobyV** [comment]
@marcoscaseres Please can I work on this issue? Would love to.

**Comment by saschanaz** [comment]
@marcoscaceres Still good to have or not? I don't use Edge now, have no push anymore.

**Comment by marcoscaceres** [comment]
Agree. I don’t think we should bother, tbh. 

Sorry @ThobyV, you will need to find a different one.
