### ISSUE TITLE
Language tags exposed in editor list company names

### ISSUE THREAD

**Issue by r12a** [w3c/respec#1786]
## Important info

* URL to affected spec: http://w3c.github.io/clreq/
* ReSpec version: 22.3.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
See the editor lists at top of page, such as:
> 董福興 (Bobby TUNG) (特邀专家 (Invited Expert))

It's possible to surround 董福興 with `<span lang='zh-hant'>`, but not 特邀专家. If you add markup around the latter, it is displayed as source code. Presumably because the respec source code uses textContent, rather than treating the value as HTML for 'company:' (?).

This is a problem, because the wrong glyphs are being displayed. See https://github.com/w3c/clreq/pull/185

**Comment by saschanaz** [comment]
This looks similar with #1594. How about we add `lang` field for editors list, rather than allowing HTML everywhere? @marcoscaceres

**Comment by r12a** [comment]
Indeed, it appears to be part of that issue (sorry for missing it).  A fix was provided for names, but not for organisations.

I believe we should stick with the markup, rather than add a metadata field. Look at the example above, for instance. Both the name and the organisation information are a mix of Chinese and English.  It would be incorrect to apply a zh language tag to the text 'Invited Expert'.

I suggest we close this issue.  I'll raise the problem in #1594.
