### ISSUE TITLE
standard way to mark fingerprinting surface vectors

### ISSUE THREAD

**Issue by npdoty** [w3c/respec#1788]
Potential feature/enhancement for ReSpec: it would be nice if authors could easily note that a particular section/feature was a potential addition to the fingerprinting surface (or sometimes, a "fingerprinting vector") and then ReSpec would add the nice icon next to it, and alt text regarding browser fingerprinting. This is a convention in HTML, and it would be useful to have it for other specs as well.

Bikeshed issue: https://github.com/tabatkins/bikeshed/issues/964

If we can all use a common SVG file for the icon, that'd be great too. I think @zcorpan has provided one here, which might be freely usable (yes?): https://github.com/whatwg/whatwg.org/pull/64

It's been suggested in updating the guidance for mitigating fingerprinting that we add an explanation for spec authors on an easy way to add the fingerprinting icon to their specs: https://github.com/w3c/fingerprinting-guidance/issues/18
I can provide raw HTML as a suggestion, but if there are even easier Bikeshed/ReSpec ways to do this, all the better.

**Comment by saschanaz** [comment]
So it seems the necessary insertion is:

```css
img.fingerprint {
  float: left;
  margin-left: -25px;
}
```

```html
<img src="https://www.w3.org/TR/html5/images/fingerprint.png" 
     class="fingerprint" 
     alt="This feature may contribute to browser fingerprintability.">
```

Should we make it clickable, [as HTML does](https://html.spec.whatwg.org/#fingerprinting-vector)?

**Comment by marcoscaceres** [comment]
Would probably be good to make this a general W3C thing, as part of tr-design.

**Comment by npdoty** [comment]
@saschanaz  It could be clickable, but I'm not exactly sure what the target of the link should be. (It could be the Mitigating Browser Fingerprinting Note, which we'd like to re-publish again soon, or it could be that part of the HTML spec, although that is specific to HTML and not exactly up-to-date regarding fingerprintability.)

Also, including that .png image for now would be great, but also in the not-too-distant future it would be nice to change it to an SVG. That being said, if it's in ReSpec, that rendering change could be updated for all authors much more quickly than if they're doing it manually.

**Comment by saschanaz** [comment]
@marcoscaceres, mind opening an issue for tr-design? I'm not very familiar with that repo.

**Comment by zcorpan** [comment]
The fingerprint image in https://github.com/whatwg/whatwg.org/pull/64 when merged will be CC0 per https://resources.whatwg.org/README.md

When the fingerprint PRs are merged, I think the default will be to link to the definition in the Infra standard.

**Comment by marcoscaceres** [comment]
Closing in favor of https://github.com/w3c/tr-design/issues/162
