### ISSUE TITLE
<dfn> for Gamepad is being ignored

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1789]
## Important info

* URL to affected spec: http://w3c.github.io/gamepad/#gamepad-interface
* ReSpec version: 22.3.3
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

![image](https://user-images.githubusercontent.com/3396686/43497846-2562a22c-957f-11e8-8960-82174212c637.png)

But what I was expecting?: `Gamepad` should get a correct link.

This looks similar with #1768 but not sure whether the same bug is causing this.

**Comment by marcoscaceres** [comment]
Looks like it.
