### ISSUE TITLE
‘File a bug’ link broken despite correct GitHub config

### ISSUE THREAD

**Issue by andreastt** [w3c/respec#1803]
## Important info

* URL to affected spec: https://w3c.github.io/webdriver/
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1). From w3c.org
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The ‘File a bug’ link in the top metadata points to https://github.com/w3c/issues/ (404) instead of https://github.com/w3c/webdriver/issues or https://github.com/w3c/webdriver/issues/new.

I noticed that the GitHub configuration for ReSpec defaults to the gh-pages branch, so I filed https://github.com/w3c/webdriver/pull/1289 to change this to master but it did not resolve the issue.

**Comment by sidvishnoi** [comment]
As a quick-fix, please add a trailing slash in the end of GitHub URL.

**Comment by marcoscaceres** [comment]
@sidvishnoi, did you by chance investigate a bit what was happening there?

**Comment by sidvishnoi** [comment]
Yeah. We have a minor issue. See:
https://github.com/w3c/respec/blob/da275e4a1b4fa54924d3dcbf6ad6c2fd9abc7f5f/src/core/github.js#L87

We just need to ensure that `ghUrl` has a trailing slash. Should be fairly simple to fix. 
We could handle this in code, or we could document in wiki to ask editors to ensure the right URL.

**Comment by marcoscaceres** [comment]
We should probably do it in code, as we shouldn't expect people to read the docs.

**Comment by andreastt** [comment]
Thanks for the quick turnaround!

**Comment by marcoscaceres** [comment]
No problem. We are going to off a couple days before releasing a new build - we are working on a couple of additional fixes.
