### ISSUE TITLE
give `var`s a type 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1804]
Given `var`, like `<var>details</var>`, it would be nice to be able to give the `var` a data type, so then you could do:

```HTML
1. Let |details:IDLContainerType| be whatever... 
2. Set |details.id| to some value.
3. Invoke  |details.doThing()|.
```

As we know `details` is `IDLContainerType`, then it could auto link `id` to `IDLContainerType`'s `id` member or attribute.  Similarly with step 3, we could link the method on IDLContainerType.

**Comment by marcoscaceres** [comment]
We could also come up with a syntax for defining vars.

**Comment by marcoscaceres** [comment]
The same applies with internal slots. We need to be able to say that an internal slot is for a particular interface. 

```Given: 
        <p>
          When getting, the <a>id</a> attribute returns this
          <a>PaymentRequest</a>'s <a>[[\details]]</a>.<a data-lt=
          "PaymentDetailsInit.id">id</a>.
        </p>
```

Should be able write:

```
        <p>
          When getting, the <a>id</a> attribute returns the context object's
          {{{PaymentRequest.[[details]].id}}}.
        </p>
```

Or even:

```
When getting, the <a>id</a> attribute returns this <a>PaymentRequest</a>'s {{{[[details]].id}}}. 
```

We can't link [[\details]] unless we know the type. We will eventually know this from WebIDL itself. 

```
interface Foo {
  slotOrSomething SomeType [[InternalSlot]];
}
```

**Comment by shikhar-scs** [comment]
Hey @marcoscaceres ✋ . Wanted to be back at respec. 😄 Would this be good to start with 😅 ?

**Comment by marcoscaceres** [comment]
@shikhar-scs welcome back! Awesome shirt, btw! 🦊🤘 Be really cool if you wanted to work on this. 

It depends on https://github.com/w3c/respec/issues/1811 getting fixed tho. @sidvishnoi, what's your plan for that one? Do you want to give some pointers to @shikhar-scs? 

As an aside, what would be really cool would be to show the `data-idl-type` when the user hovers over a matching variable. Like Visual Studio does when you hover over things:

![screenshot 2018-09-24 13 36 21](https://user-images.githubusercontent.com/870154/45936905-eaff5300-bffe-11e8-89f9-947448fd1c80.png)

**Comment by shikhar-scs** [comment]
> Awesome shirt, btw! 🦊🤘

Lol, thanks for sending it though 😅 . 

> It depends on #1811 getting fixed tho.

Then, should I go to #1811 first ? 

> Do you want to give some pointers to @shikhar-scs?

Yeah @sidvishnoi this would be great. I'll look into hover too once I get started with this. 😄

**Comment by marcoscaceres** [comment]
> Then, should I go to #1811 first ?

Yeah, might be worth having a look - but coordinate with @sidvishnoi, because he might have a patch in the works already.  

For a bit more background, @sidvishnoi built a very basic parser for that "{{{" "}}}" syntax. But it's not working quite right yet. The code is very small/elegant, so hopefully easy to see what it's doing:
https://github.com/w3c/respec/blob/develop/src/core/inline-idl-parser.js

That then gets used here:
https://github.com/w3c/respec/blob/develop/src/core/inlines.js#L81

Might be good to familiarize yourself with those bits of the code tho. We've also thrown around the idea of having a "real" parser... if you are feeling brave, take a look at:

https://pegjs.org

We could formalize the actual micro language and then use the above to produce the syntax tree.

**Comment by yatri1609** [comment]
@marcoscaceres Can I work on this? I would like to start with some real coding with this one.

**Comment by marcoscaceres** [comment]
@yatri1609 sure! Take a look at using bubble.js for the hover to show the data type. 
https://github.com/krasimir/bubble.js

**Comment by sidvishnoi** [comment]
@marcoscaceres How about using the `title` attribute itself or some regular CSS+JS events if `title` isn't enough? I'm not sure if we should add another library here even though it's tiny.

**Comment by marcoscaceres** [comment]
Agree. I should have said, “something like” bubblejs. Starting with title attribute could work, though something a bit prettier would be nice.

**Comment by marcoscaceres** [comment]
sounds like a plan :)

**Comment by yatri1609** [comment]
@marcoscaceres Sorry I had a accident so wasn't able to work, but now since I am well I will like to get back on this if @sidvishnoi you aren't working on this?

**Comment by sidvishnoi** [comment]
@yatri1609 Oh. We hope you're good now. 

I'm having exams so I won't be working on this till 17th. We have done some work on "giving var a type" part where we essentially re-wrote the inline-idl parser. So feel free to check it out in https://github.com/w3c/respec/pull/1848 

Once that is done, we will fix the xref part and you can take the data type on hover part (See: https://github.com/w3c/respec/issues/1804#issuecomment-432538635)

**Comment by yatri1609** [comment]
@sidvishnoi Yeah I'm good now, Sure I will start looking at how we can have the data type hovering part

**Comment by marcoscaceres** [comment]
(I'm away until next week, unfortunately - will try to respond soon)

**Comment by Swapnilr1** [comment]
Can I work on this one? No one is assigned but it seems people were working on this one. Is this still open?

**Comment by sidvishnoi** [comment]
@Swapnilr1 See https://github.com/w3c/respec/issues/1804#issuecomment-444866639
It's still active (and high priority) but we're not able to make time for it. We can have you on "show data type on hover" part once we're done with #1848

**Comment by marcoscaceres** [comment]
I think we can probably support `<var data-type>` without #1848. Then #1848 can leverage this.

**Comment by pradeepgangwar** [comment]
@marcoscaceres @sidvishnoi zi want to work on this. Let me try this.

**Comment by saschanaz** [comment]
#2175 added variable typing but not the auto-link thing, right?

**Comment by marcoscaceres** [comment]
Correct... need to do the auto linking part. I was unsure if we should just close this bug and start a new one.

**Comment by saschanaz** [comment]
Would be cleaner to start a new thread.
