### ISSUE TITLE
IDL link to local members in same document

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1811]
With the inline IDL syntax, the following doesn't currently work as expected:

```JS
{{{ PaymentAddress.languageCode }}}
```

The base part links `PaymentAddress`, but the `languageCode` member doesn't. 

I think this is incorrect:

https://github.com/w3c/respec/blob/develop/src/core/link-to-dfn.js#L82

There we should try linking locally first (or if data-link-for="" is present), then try external referenced. 

@sidvishnoi, thoughts?

**Comment by sidvishnoi** [comment]
> I think this is incorrect:

Mostly yes. Did things to make things work. 😞 Will be back after a week, hopefully this isn't high priority right now.

> we should try linking locally first

Yes. that is required. I mainly did `{{{ }}}` for external linking right now. Need to make it work local first.
