### ISSUE TITLE
Small-caps is not appropriate for `<code>`

### ISSUE THREAD

**Issue by yoavweiss** [w3c/respec#1812]
## Important info

* https://w3c.github.io/performance-timeline/#getentries-method-0
* ReSpec version: 22.6.0
* [x] I did a "hard refresh", but it's still busted. N/A - it's a style issue

## Description of problem

Going to the link above you can see that code segments are displayed with small-caps, inherited from the `<h6>` style. That doesn't really work.

`<code>` should be excluded from those styles, e.g. by including `font-variant: normal;` in https://www.w3.org/StyleSheets/TR/2016/base.css (line 488 in current version)

I'm not sure if this is a respec issue, or if the styles are maintained elsewhere. Feel free to redirect

**Comment by marcoscaceres** [comment]
base.css is maintained at https://github.com/w3c/tr-design

**Comment by marcoscaceres** [comment]
That seems odd. I’ll check what’s going on there.

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/tr-design/issues/164 and PR https://github.com/w3c/tr-design/issues/165
