### ISSUE TITLE
Autogenerated (section) IDs omit unicode characters

### ISSUE THREAD

**Issue by jakubklimek** [w3c/respec#1813]
## Important info

* ReSpec version: 22.5
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Autogenerated IDs of sections (and other parts of the document as well) based on headings omit unicode characters, creating nonsensical words in URLs.

I would expect the IDs to keep the words intact (i.e. do only lowercase, if that is necessary)

Optional, steps to reproduce:
1. Create a section with heading containing unicode characters, e.g. `Zkracování` and no `id` attribute
2. Observe that the generated id is e.g. `zkracov-n-` instead of `zkracování`

**Comment by marcoscaceres** [comment]
Can probably use: https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript

**Comment by jakubklimek** [comment]
@marcoscaceres To cite the first comment in that post:
> why on earth would you want to remove accents?

The point here is to keep them in. They are valid IRIs and when I define them manually in the ids, they work perfectly.

**Comment by marcoscaceres** [comment]
oh, my bad... I misread. We had problems with these IRIs before when sharing them on twitter, etc. The support for fragments that contain unicode is quite spotty.

**Comment by jakubklimek** [comment]
Well, and was this recently? Tried and https://t.co/S4yYjMNh9i works. Also works ok in Firefox and Chrome... I mean I am not a fan of limiting oneself by a buggy implementation. Instead I would push for fixing the implementation...
