### ISSUE TITLE
data-dfn-for ignored for duplicate IDL enum terms

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#1814]
## Important info

* URL to affected spec: [Presentation API](https://w3c.github.io/presentation-api/)
* ReSpec version: Click the ReSpec pill (e.g., 22.6.0).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The  `PresentationConnectionState` enum, defined in [section 6.5](https://w3c.github.io/presentation-api/#interface-presentationconnection) contains a `closed` term.
The `PresentationConnectionCloseReason` enum, defined in [section 6.5.4](https://w3c.github.io/presentation-api/#interface-presentationconnectioncloseevent) also contains a `closed` term.

Definitions use `data-dfn-for` to distinguish between the two, but ReSpec seems to ignore these attributes for `closed` (but not for the other terms). The result is that:
1. the prose definition of the `closed` term for `PresentationConnectionState`, whose id should be `dom-presentationconnectionstate-closed` ends up with the id `dom-presentationconnectionclosereason-closed`
3. the prose definition of the `closed` term for `PresentationConnectionCloseReason`, whose id should be `dom-presentationconnectionclosereason-closed` ends up with the id `dfn-closed` (and is not identified as an IDL term)

Minimal markup that reproduces the problem:

```html
<pre class="idl">
  enum State { "closed" };
  enum CloseReason { "closed" };
</pre>
<p>For <dfn>State</dfn>, <dfn data-dfn-for="State">closed</dfn> means foo.</p>
<p>For <dfn>CloseReason</dfn>, <dfn data-dfn-for="CloseReason">closed</dfn> means bar.</p>
```

I had not noticed that problem before so this may have been triggered by recent changes to IDL auto-linking code.

**Comment by marcoscaceres** [comment]
Yeah, we don't support this very well right now. It's best to:

```
<section data-link-for="State">
<h2>The State enum</h2>
<pre class=idl>
 enum State { "closed" };
</pre>
</section>
<section data-dfn-for="CloseReason">
<h2>The CloseReason enum</h2>
<pre class=idl>
 enum CloseReason { "closed" };
</pre>
</section>
``` 

As best practice, the enums should be defined as above l. Also, `CloseReason` looks like it should be a `DOMString`, not an enum.

**Comment by tidoust** [comment]
> As best practice, the enums should be defined as above

I suspect the first `data-link-for` in your code should be `data-dfn-for`, but even with that fix, that does not fix the problem. Did I miss something?


> Also, CloseReason looks like it should be a DOMString, not an enum.

Hmm, why? The [actual definition](https://w3c.github.io/presentation-api/#dom-presentationconnectionclosereason) has 3 values (`closed`, `error`, `wentaway`) and implementations are not supposed to create new ones.

**Comment by marcoscaceres** [comment]
> I suspect the first data-link-for in your code should be data-dfn-for, but even with that fix, that does not fix the problem. Did I miss something?

Strange. Can you put up a patch over on the other repo?  

> Hmm, why? The actual definition has 3 values (closed, error, wentaway) and implementations are not supposed to create new ones.

It's more that reasons are usually given, not "enums"... which usually represent states in state machines.

**Comment by tidoust** [comment]
> Strange. Can you put up a patch over on the other repo?

Not sure what patch I should put. What I'm saying is that the following minimal ReSpec doc has the problem:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://www.w3.org/Tools/respec/respec-w3c-common" async class="remove"></script>
    <script class="remove">var respecConfig = {};</script>
  </head>
  <body>
    <section data-dfn-for="State">
      <h2>The State enum</h2>
      <pre class=idl>
       enum State { "closed" };
      </pre>
      <dl>
         <dt><dfn>closed</dfn> state</dt>
          <dd>... bla</dd>
      </dl>
    </section>
    <section data-dfn-for="State">
      <h2>The CloseReason enum</h2>
      <pre class=idl>
       enum CloseReason { "closed" };
      </pre>
      <dl>
         <dt><dfn>closed</dfn> state</dt>
          <dd>... bla</dd>
      </dl>
    </section>
  </body>
</html>
```

**Comment by marcoscaceres** [comment]
Ok, np. Will work off your test case above.

**Comment by marcoscaceres** [comment]
Fix incoming https://github.com/w3c/respec/pull/1816

**Comment by marcoscaceres** [comment]
@tidoust seems good now on v22.7.1. Linking to the right things. Thanks again for the test case!
