### ISSUE TITLE
Add self-links to headings (§ hyperlink anchor)

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#1821]
It would be great if Respec-generated specs had self-links for all headings, the way the HTML spec does and that Bikeshed-generated specs do.

To be clear, I mean the feature where, in the left margin just before the heading, there’s a `§` character that’s a hyperlink to the URL for that heading.

**Comment by marcoscaceres** [comment]
Will release hopefully tomorrow or Monday :)
