### ISSUE TITLE
Duplicate ids are generated for sections with the same title in Markdown docs

### ISSUE THREAD

**Issue by thijsbrentjens** [w3c/respec#1830]
## Important info

* URL to affected spec: (not live in production at the moment)
* ReSpec version: 23.0.2 based build of Geonovum, but generic issue
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
In ReSpec documents using Markdown duplicate ids are generated on the header elements if sections have the same title. In HTML docs this does not occur.

But what I was expecting?
I expected unique ids, similar to an HTML doc where the same titles are used

Optional, steps to reproduce:
1. see the gist at https://gist.github.com/thijsbrentjens/43489b534ef9305881805076bcc35519
1. see the generated source or see snapshot.html
 1. there are 2 elements h3 with id="sectiontitle"

**Comment by thijsbrentjens** [comment]
I tried to figure out what is going on. 

It seems that the code at https://github.com/Geonovum/respec/blob/develop/src/core/markdown.js#L205 is never executed (at least, adding a breakpoint in my browser does not pause executing the code). 

Around https://github.com/w3c/respec/blob/develop/src/core/structure.js#L59 I found that there is an id attribute for the h object in:
```
const id = h.id ? h.id : $sec.makeID(null, title);
```
So somewhere an id is created (and/or never removed in time).
For testing purposes I changed the line (locally) into:
```
const id = $sec.makeID(null, title);
```
to force id generation. Now a counter is added to make the id unique. There probably is/was a good reason to check for an existing id already. So I don't want to change it myself, maybe it will break something. But maybe it helps in the analysis?

**Comment by marcoscaceres** [comment]
Thanks for looking into it! That’s really helpful. I’ll try to find a little time to reproduce what you did tomorrow. It’s indeed strange that the markdown module is not setting the html.

**Comment by gkellogg** [comment]
This happens with examples too:

```html
<pre id="sample-document-context" class="example nohighlight" data-transform="updateExample"
     data-context-for="Expanded sample document"
     title="JSON-LD context">
<!--
{
  "@context": {
    "name": "http://xmlns.com/foaf/0.1/name",
    "homepage": {
      "@id": "http://xmlns.com/foaf/0.1/homepage",
      "@type": "@id"
    }
  }
}
-->
</pre>
```

Produces the following:

```html
<div class="example" id="sample-document-context">
      <div class="marker"><a class="self-link" href="#sample-document-context">Example 7</a><span class="example-title">: JSON-LD context</span></div>
      <pre id="sample-document-context" class="nohighlight" data-context-for="Expanded sample document">{
  "@context": {
    "name": "http://xmlns.com/foaf/0.1/name",
    "homepage": {
      "@id": "http://xmlns.com/foaf/0.1/homepage",
      "@type": "@id"
    }
  }
}</pre>
</div>
```

**Comment by marcoscaceres** [comment]
Trying to reproduce now...

**Comment by marcoscaceres** [comment]
Ok, PRs sent and waiting for review. It was two separate bugs. 

For the markdown case, automatically adding ids is something that was added to Marked.js v4. I've disabled it, and now ReSpec handles the ID generation. 

The examples was a bug on my part - I'd cloned the `pre` before actually removing the id! So thanks @gkellogg for letting me know about this.

**Comment by thijsbrentjens** [comment]
Thanks @marcoscaceres  !

**Comment by marcoscaceres** [comment]
+ respec@23.0.4
