### ISSUE TITLE
Warn when test appears more than once

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1834]
Given, for instance:

```HTML
<p data-tests="
  payment-request-show-method.https.html
  some.other.test.html
  payment-request-show-method.https.html">
          ...
</p>
```

ReSpec should warn about duplicate tests. 

Effectively, somewhere here, we need to check and warn of duplicates:
https://github.com/w3c/respec/blob/develop/src/core/data-tests.js#L86-L98

And also drop the duplicates.

**Comment by sidvishnoi** [comment]
Warn duplicate in entire document or duplicate with respect to a single `[data-tests]` element?

**Comment by marcoscaceres** [comment]
Good question, a single `[data-tests]` element? Sometimes test cover multiple things so it's ok to repeat them.
