### ISSUE TITLE
Export crashes on the editor's draft of JSON-LD

### ISSUE THREAD

**Issue by deniak** [w3c/respec#1842]
## Important info

* URL to affected spec: https://cdn.rawgit.com/w3c/json-ld-syntax/eb61149c86124d4a53ec01f16cd8db132201ad44/index.html
* ReSpec version: 23.1.1

* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: Trying to export that document produces a JS error the first time. It seems to work the 2nd time though. This is problematic for spec-generator.

**Comment by marcoscaceres** [comment]
confirmed. Will take a look first thing tomorrow!

**Comment by marcoscaceres** [comment]
@deniak looks like the crash is happening here:
 https://cdn.rawgit.com/w3c/json-ld-syntax/eb61149c86124d4a53ec01f16cd8db132201ad44/common/common.js

on line 165 - which is outside the control of ReSpec... cc'ing @gkellogg who might know about these scripts?

**Comment by gkellogg** [comment]
Thanks @marcoscaceres this doesn't seem to come up in normal usage. This code block was moved from `postProcess` to use pubsubhub along with other changes, but that shouldn't change it's basic processing. I'll add some guard checks around it, either to ensure `textContent()` is a string, or to use `innerText`, or both.

How can I reproduce the error outside of a web browser, where I don't notice any such error?

**Comment by marcoscaceres** [comment]
Oh, I wonder if it’s triggering outside a browser context at all? Could you check the output and see if the save event fires? I recall for saving that ReSpec provides a different API - which may not be firing the save event.

**Comment by marcoscaceres** [comment]
Ok, just saw your update! Hopefully you can reproduce from there.

**Comment by gkellogg** [comment]
Thanks, previews are back! It would still be useful to know that a failure occurred preventing the preview links from showing up.

**Comment by deniak** [comment]
@marcoscaceres thanks for investigating. Closing this one as it solved @gkellogg's issue.
