### ISSUE TITLE
(refactor): Remove jQuery from ReSpec

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1846]
Remove jQuery from following remaining modules:

- [x] core/requirements https://github.com/w3c/respec/pull/1845
- [x] [core/figures](https://github.com/w3c/respec/blob/develop/src/core/figures.js) https://github.com/w3c/respec/pull/1956
- [x] [core/structure](https://github.com/w3c/respec/blob/develop/src/core/structure.js) https://github.com/w3c/respec/pull/1957
- [x] [core/link-to-dfn](https://github.com/w3c/respec/blob/develop/src/core/link-to-dfn.js) #1897
- [x] [core/dfn](https://github.com/w3c/respec/blob/develop/src/core/dfn.js) #1898
- [x] [core/ui](https://github.com/w3c/respec/blob/develop/src/core/ui.js) #1930
- [x] [core/issue-notes](https://github.com/w3c/respec/blob/develop/src/core/issues-notes.js) #1969
- [x] [w3c/conformance](https://github.com/w3c/respec/blob/develop/src/w3c/conformance.js) #1926
- [x] tests: [~core/dfn-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/dfn-spec.js), [~core/informative-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/informative-spec.js), [~core/issues-notes-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/issues-notes-spec.js), [~core/section-refs-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/section-refs-spec.js), [~core/structure-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/structure-spec.js), [~core/utils-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/core/utils-spec.js), [~w3c/conformance-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/w3c/conformance-spec.js), [~w3c/headers-spec.js~](https://github.com/w3c/respec/blob/develop/tests/spec/w3c/headers-spec.js) (https://github.com/w3c/respec/pull/1977, https://github.com/w3c/respec/pull/1979)

**Comment by sidvishnoi** [comment]
Doing some of the quick ones (figures, structure, conformance) in [remove-jquery branch](https://github.com/w3c/respec/tree/remove-jquery).

**Comment by marcoscaceres** [comment]
Maybe we should leave those of interns? We have a few other high priority things that I'd really like for use to work together on: ✨ https://github.com/w3c/respec/issues/1804 ✨

**Comment by akansha2608** [comment]
Hi @sidvishnoi @marcoscaceres i would like to work on it m can you help me getting started for this repository?

Thanks

**Comment by treyhboy** [comment]
Hi, @marcoscaceres @sidvishnoi can I work on this one?

**Comment by marcoscaceres** [comment]
Sure! Feel free to take any of the above.

**Comment by anoited007** [comment]
@marcoscaceres Sorry I missed ur follow up. I will get to work then.

**Comment by Swapnilr1** [comment]
Can I work on this issue if it is not already in progress?

**Comment by sidvishnoi** [comment]
Hi! Looks like now only [core/issue-notes](https://github.com/w3c/respec/blob/develop/src/core/issues-notes.js) remains. 
@saschanaz are you going to leave this one for the rest of us? 😂

**Comment by Swapnilr1** [comment]
@sidvishnoi Alright, actually when I saw this only 5/8 were marked complete. I will look at some other issue.

**Comment by marcoscaceres** [comment]
@Swapnilr1 easy one https://github.com/w3c/respec/issues/1959 (remove some dead code)

**Comment by marcoscaceres** [comment]
@Swapnilr1 you can also search "src/" for "$(" to see if there are any other jQuery things we missed.

**Comment by devanshbatra04** [comment]
Hi, I am taking up the last one if that's fine.

**Comment by sidvishnoi** [comment]
I've added tests in list above. So, someone can do them also.

**Comment by devanshbatra04** [comment]
Can I also take the tests up as well? I have never written tests before (just debugged), excited to learn! :sweat_smile:

**Comment by yatri1609** [comment]
@sidvishnoi Is there anything left that I can work on in this issue?

**Comment by sidvishnoi** [comment]
@yatri1609 Unfortunately, there isn't anything left in this issue. We can use your help at other issues like https://github.com/w3c/respec/issues/1950, https://github.com/w3c/respec/issues/1713, https://github.com/w3c/respec/issues/1631, https://github.com/w3c/respec/issues/1239

**Comment by marcoscaceres** [comment]
I think with #1979, we are jQuery free 🎉🤞?

**Comment by saschanaz** [comment]
Confirmed we have no more `$()`.

**Comment by sidvishnoi** [comment]
We're jQuery free but we're still shipping jQuery for backward compatibility. 
I believe you two were waiting on me to close this issue? Thanks 😄 ❤️
