### ISSUE TITLE
Single slash "/" resolution in data-cite is both right and wrong. 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1852]
## Important info

* URL to affected spec: https://github.com/w3c/resource-timing/
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
Given:
```HTML
<a data-cite="PERFORMANCE-TIMELINE-2/#performance-timeline">Foo</a>
```

It resolves the URL incorrectly to TR. 

But what I was expecting?:

A link to the performance 2 spec. 

Optional, steps to reproduce:
 1. Use the code above

**Comment by sidvishnoi** [comment]
Looks like we're only taking `href` key into account. If `edDraft` is available, we have to pick that, right? (https://specref.herokuapp.com/bibrefs?refs=performance-timeline-2)

**Comment by marcoscaceres** [comment]
ReSpec is actually doing the right thing, per URL resolution rules:

“/#frag“ + base = base/#

 I’m not sure we should fix this.

**Comment by marcoscaceres** [comment]
I've thought about this a bit... decided it's not worth fixing.
