### ISSUE TITLE
Merge partial WebIDL definition in idl-index?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#1855]
Using partial interface/dictionary definitions in a spec may be helpful to push the IDL portion to where the general definition of the relevant features are. On the other hand, using respect's idl-index is helpful to collect all IDL-s into one place.

However, at the moment, all partial definitions are 'just' collected in the index one after the other. It may be helpful to the reader if all the partials were merged into one (possibly large) definition, instead of having the partials listed one after the other. I tried to see in the code whether there is a hidden switch to do that, and I did not find any...

Would be nice if it was possible...

**Comment by marcoscaceres** [comment]
I agree that would be nice, but it might get confusing as a lot of people copy/paste the IDL into code, documentation, etc. So I’d be personally a bit hesitant for us to support this.

**Comment by marcoscaceres** [comment]
Yeah, was thinking the same... like id=“idl-index” class=“combined” or something. The (not super hard) part is re-parsing the WebIDL, and doing the merge.

**Comment by iherman** [comment]
@marcoscaceres I made some hack for our case (it is much simpler because the idl contains enums and dictionaries only); the only real hack is to take the output of the webidl parser and combine things (and some extra tricks to pretty print WebIDL which, I would think, respec does also somewhere. But I have no idea how to incorporate that into respec; I was looking at the webidl-index file and I do not understand all the details.

(Doing it as part of a preProcess function replacing the idl-index is iffy at best, because respec duplicates the `id` values, which generates also error messages... But this is what I do now, adding a postProcess to remove the extra `id`-s (ouch!))

<details>
<summary>The code I used... it supposes that the partial definition follows the 'real' one, which is probably incorrect, though.</summary>

```javascript
    /**
     * Merging the partial definitions in an array of (parsed) WebIDL structures
     * 
     * @param {Array} webidl - An array of parsed WebIDL structures 
     */
    function merge_partials(webidl) {
        let retval = [];

        webidl.forEach( (definition) => {
            // See if it is partial or not
            if (definition.partial) {
                // We have to find the definition that has already preceded this partial one.
                const def = retval.find((def) => def.name === definition.name);
                if (def === undefined) {
                    console.error(`Partial definition comes before the real one (${definition.name})`);
                } else {
                    def.members = def.members.concat(definition.members);
                }
            } else {
                // This is a bona-fide definition
                retval.push(definition);
            }
        });
        return retval;
    }
```
</details>

**Comment by marcoscaceres** [comment]
I’m still worried this will cause confusion, so I’m closing as “won’t fix”.
