### ISSUE TITLE
data-cite: Reference Subpage Resolution

### ISSUE THREAD

**Issue by rjksmith** [w3c/respec#1856]
## Important info

* URL to affected spec: http://w3c.github.io/sdw/proposals/geotagging/webvmt/#overview
* ReSpec version: 23.3.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

I'm trying to use <code>data-cite</code> to link to a particular section of a subpage using <code>&lt;a&gt;</code>, as [described in the Respec Wiki](https://github.com/w3c/respec/wiki/data--cite#example-of-usage-with-a-element), e.g. <code>&lt;a data-cite="HTML51/subpage.html#section&gt;text&lt;/a&gt;</code>.

Either I've misunderstood how to use this or there's a bug, and I'd be appreciate help in either case.

1. Links without a subpage seem to correctly resolve, e.g. <code>&lt;a data-cite="HTML51&gt;text&lt;/a&gt;</code> correctly resolves to https://www.w3.org/TR/html51/.

1. Links with a subpage seem to incorrectly drop the path, so <code>&lt;a data-cite="HTML51/subpage.html#section"&gt;text&lt;/a&gt;</code> incorrectly resolves to https://www.w3.org/subpage.html#section instead of the expected https://www.w3.org/TR/html51/subpage.html#section.

1. There are examples of both of the above in section 4.1 at http://w3c.github.io/sdw/proposals/geotagging/webvmt/#overview.

Issue #1180 appears to give a nearly identical example, but I'm unsure of its eventual outcome. Please advise.

**Comment by marcoscaceres** [comment]
The behavior is correct, but it’s not meeting user expectations that the path is resolved using the citation as the base. So when starting with “/“, we should add “.” to the front.

**Comment by marcoscaceres** [comment]
Excellent, thanks for confirming.
