### ISSUE TITLE
ReSpec adds width=0 and height=0 for images in a figure

### ISSUE THREAD

**Issue by thijsbrentjens** [w3c/respec#1859]
## Important info

* URL to affected spec: (Geonovum): https://geonovum.github.io/IMVG/
* ReSpec version: Geonovum implementation, based on v 23.0.4
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)? Some images in https://geonovum.github.io/IMVG/ were not shown, because ReSpec added a width=0 and height=0 attribute to the img tag in a figure. The document https://geonovum.github.io/IMVG/ uses the Markdown format. Note: the Geonovum implementation uses a workaround now, with an additional CSS rule. See https://github.com/Geonovum/respec/issues/153

But what I was expecting?: images

Optional, steps to reproduce: 
1. create a ReSpec doc with format markdown
1. include this figure in the markdown: 

```
<figure>
	<a target="_blank" href="https://upload.wikimedia.org/wikipedia/commons/8/8f/Stelsel_van_Basisregistraties.png">
		<img src="https://upload.wikimedia.org/wikipedia/commons/8/8f/Stelsel_van_Basisregistraties.png" alt="Stelselplaat" class="img-responsive">
	</a>
	<figcaption> - Stelsel van Basisregistraties: stelselplaat (klik voor vergroting)</figcaption>
</figure>

```

**Comment by marcoscaceres** [comment]
Fix sounds reasonable to me. If you can prepare a PR, it would be greatly appreciated.
