### ISSUE TITLE
IETF specs don't work with data-cite? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1868]
## Important info

* URL to affected spec: https://w3c.github.io/navigation-timing/
* ReSpec version: Click the ReSpec pill (e.g., 23.4.0).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
Using `data-cite` instead of `href=` for IETF specs doesn't seem to work. 

But what I was expecting?:

That is would work

Optional, steps to reproduce:
 1. convert a `href=` for an IETF spec to a `data-cite`

**Comment by Swapnilr1** [comment]
Can I work on this?

**Comment by Swapnilr1** [comment]
@marcoscaceres I am not able to replicate this issue on my end.
I looked at the spec you linked to (https://w3c.github.io/navigation-timing/) and changing 
`<a href="https://tools.ietf.org/html/rfc7234">HTTP cache</a>` to `<a data-cite="rfc7234">HTTP cache</a>` worked fine for me. 

Could you please just confirm if the issue still exists or not?

**Comment by marcoscaceres** [comment]
Yeah, I also couldn’t replicate it either. Thanks for confirming. Closing as works for us.
