### ISSUE TITLE
pubrules fail due to a spurious `/` in github links

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1870]
respec.js introduces a spurious `/` in github links in the SotD.

Found [while checking `http://sandflow.com/public/imsc/Overview.html`](https://www.w3.org/pubrules/?url=http%3A%2F%2Fsandflow.com%2Fpublic%2Fimsc%2FOverview.html&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

See also https://github.com/w3c/specberus/issues/778

**Comment by marcoscaceres** [comment]
@palemieux sent a PR. Just waiting on review. Will have the fix out later today 🤞.
