### ISSUE TITLE
data-lt generates duplicated definitions

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1878]
## Important info

* URL to affected spec: https://w3c.github.io/gamepad/extensions.html
* ReSpec version: 23.5.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

`<dfn data-lt="pulse()>pulse</dfn>` becomes `data-lt="pulse()|pulse|gamepadhapticactuator.pulse()|gamepadhapticactuator.pulse|pulse()|pulse"` and causes an error saying "Duplicate definitions of 'pulse'".

But what I was expecting?:

`data-lt` shouldn't generate duplicated items.

Removing `data-lt` solves the issue but also removes `gamepadhapticactuator.pulse()|gamepadhapticactuator.pulse`. Is this expected?

**Comment by marcoscaceres** [comment]
Hmm... need to check why the `data-lt`s are not being treated as a set. 

> Removing data-lt solves the issue but also removes `gamepadhapticactuator.pulse()|gamepadhapticactuator.pulse`. Is this expected?

No. We should fix that.

**Comment by saschanaz** [comment]
Looks like the module `dfn` first generates `pulse()|pulse` and then registers them to `definitionMap`, and then `dfn-finder` (or `webidl` when writing the original post) again generates the remaining parts and then again registers them to `definitionMap`, causing the duplication error.
