### ISSUE TITLE
Babel's stage presets are deprecated

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1900]
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets

We will probably want to migrate before upgrading to future releases.

**Comment by saschanaz** [comment]
@marcoscaceres Any thoughts? Maybe we can migrate to https://www.npmjs.com/package/@babel/preset-env or simply remove the dependency.

**Comment by marcoscaceres** [comment]
preset-env is probably the way to go... we just target last stable.
