### ISSUE TITLE
Use @ts-check wherever appropriate

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1905]
It enables strict type check for JavaScripts on any TypeScript-based IDE (e.g. VSCode) so that inappropriate function call can be prohibited before running tests.

**Comment by saschanaz** [comment]
Adding `//@ts-check` at the top of the file is all that needed.

**Comment by saschanaz** [comment]
>we might eventually be able to compile some modules as WASM (🤞).

TIL [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) exists 😮

**Comment by devanshbatra04** [comment]
@saschanaz I am taking this up if that's fine. Oh and Happy New Year!! :smiley:

**Comment by marcoscaceres** [comment]
@saschanaz, this can be closed, right?

**Comment by saschanaz** [comment]
We still have files without `@ts-check`, so no. The ultimate goal is to add `checkJs: true` in `jsconfig.json` which will enable ts-check in every JS file.

**Comment by marcoscaceres** [comment]
Oh, ok. Thanks for confirming.

**Comment by saschanaz** [comment]
https://github.com/w3c/webidl2.js/issues/255 is currently a blocker.

**Comment by marcoscaceres** [comment]
I need to play less computer games and spend some time learning ts. #lifegoals.

**Comment by rahulpurohit29** [comment]
Can I do this?

**Comment by saschanaz** [comment]
@rahulpurohit29 If you have some TypeScript and JSDoc experience, sure.

**Comment by rahulpurohit29** [comment]
If I just add `"checkJs":true` to the src/jsconfig.json it will globally type check for all .js files, right?

**Comment by saschanaz** [comment]
All `src/**/*.js` files, yes. You will then have to solve the type errors TS shows.

**Comment by marcoscaceres** [comment]
That might be a good place to start - but @saschanaz will know more. Try it and see what errors are emitted.  For where the type checks fail, then I assume you would need to go and fix those errors.

**Comment by saschanaz** [comment]
I've found too hard to do fix everything at once, so if you get too much errors then just solve some of them and open a PR. Then we can make things better progressively.

**Comment by marcoscaceres** [comment]
Breaking up the problem is a good suggestion... @rahulpurohit29, try to do one file at a time. Any fixes you can make will be a significant contribution to the project. It will also make it easier for us to review the changes you make (and a good opportunity for you to understand the code).

**Comment by isunitha98selvan** [comment]
If no one is working on this, I would like to take it up.

**Comment by saschanaz** [comment]
@isunitha98selvan Good, feel free to ask questions when need.d

**Comment by isunitha98selvan** [comment]
@saschanaz I added "checkJS":true to jsconfig.json. I then tried to test it by running: tsc -p jsconfig.json. I got a bunch of TS5055 errors i.e JS file would overwrite input file. I am kind of stuck here. How should I proceed?

**Comment by saschanaz** [comment]
@isunitha98selvan That's weird, would you try `npm run lint` instead?

**Comment by isunitha98selvan** [comment]
@saschanaz ended up with almost 795 errors! Not sure where to start debugging

**Comment by saschanaz** [comment]
You can ignore errors from third-party libraries for now.
