### ISSUE TITLE
Anonymous IDL operations cause id collision

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1911]
## Important info

* URL to affected spec:
* ReSpec version: 23.7.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

Operations without names potentially get the same ids.

```webidl
[Exposed=Window]
interface Foo {
  getter DOMString (); // idl-def-foo-
  setter DOMString (); // idl-def-foo-
};
```

But what I was expecting?:

Maybe just no id? Or it may be `idl-def-foo--getter`.

**Comment by marcoscaceres** [comment]
Closed via #3335
