### ISSUE TITLE
Remove support for Error object from core/ui

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1929]
https://github.com/w3c/respec/blob/c1a1f82e2bebd8e75bbcc809e8afebc7c1fee13c/src/core/ui.js#L99-L134

core/ui has a long code block to support `pub("error", new Error("..."))` but looks like we never use it.

@marcoscaceres, I think we decided not to expose raw error messages and stacks to the UI, right? Maybe we can remove it.

**Comment by marcoscaceres** [comment]
Yeah, let's remove it.
