### ISSUE TITLE
Get local references list from definitions

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1952]
Clicking a definition in a bikeshed-generated spec shows a popup that includes local references.

![image](https://user-images.githubusercontent.com/3396686/49991560-d363b500-ffc4-11e8-9f5f-11077330e7e4.png)

It would be great to get the same feature.

**Comment by sidvishnoi** [comment]
@saschanaz We're tracking it in https://github.com/w3c/respec/issues/1103 (and https://github.com/w3c/respec/issues/1869)
Looks like it's the right time to do it as we've 3 separate issues on that 😅

**Comment by saschanaz** [comment]
Oops! 🤣
