### ISSUE TITLE
Remove makeOwnerSwapper()?

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1959]
@marcoscaceres, I found that `makeOwnerSwapper()` is added by https://github.com/w3c/respec/pull/766 but is not being used anywhere. Can it be removed, or do we have any compatibility concerns?

**Comment by marcoscaceres** [comment]
Yep, we can remove it.

**Comment by Swapnilr1** [comment]
@marcoscaceres I have removed `makeOwnerSwapper()` by using grep and removing declarations and definitions where found and then proceeded to verify that it does not break anything. However, security/snyk shows 14 vulnerabilities on my PR. I am not sure what I can do to fix this. Could you please guide me with what I need to fix?

**Comment by marcoscaceres** [comment]
Oh, ignore those. Those are from a dependency and we patch them on release.

**Comment by Swapnilr1** [comment]
@marcoscaceres So that means my PR will be merged?

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/respec/pull/1967
