### ISSUE TITLE
Move CSS out of js folder

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1994]
It would be nice if we could move the css out of the js folder, and ultimately delete the js folder (as we use src/ for JS stuff).

**Comment by saschanaz** [comment]
No more debugging hassle with the compiled sourcemaps? I thought it's the last reason we keep `js/`.

**Comment by marcoscaceres** [comment]
What I was thinking was to use the empty folder to generate stuff, but just keep it empty in the tree. If the transpiration is minimal (and whitespace is kept in development), then sourcemaps are not that much of a problem.... but again, it's something that I need to try out to see if it's any better nowadays.

**Comment by saschanaz** [comment]
Can the directory be `assets`, as we also have `js/core/images`?

**Comment by marcoscaceres** [comment]
yeah, single `assets` directory would be fine too.
