### ISSUE TITLE
Built sourcemap name mismatch 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1995]
when building, the source map file is currently misnamed... it outputs respec-w3c-common.js.map, but should be "respec-w3c-common.build.js.map".

Alternatively, we should trash "respec-w3c-common.build.js.map" and use "respec-w3c-common.js.map", which is a much nicer name 👀

**Comment by marcoscaceres** [comment]
Somewhat high priority this one... as it breaks releasing.

**Comment by saschanaz** [comment]
I also think the new name is better, given that it doesn't cause a breaking change.
