### ISSUE TITLE
Drop shortcut?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#1996]
I think we should drop shortcut.js... it adds little value. The "shortcuts" are quite complicated, and rarely used in practice. I'd be ok with just using the ReSpec pill to get to functionality. We could move core things, like "Save HTML..." up a level in the ReSpec pill to make the pill more useful.   

Opinions?

**Comment by saschanaz** [comment]
Maybe somehow useful for accessibility but not sure. Definitely not useful for me.

**Comment by marcoscaceres** [comment]
Yeah, was thinking the same about the a11y aspects... maybe we can roll our own simplified version of the shortcuts?

**Comment by saschanaz** [comment]
Yes, that should work. I'd like to hear from what a11y experts think though.

**Comment by saschanaz** [comment]
I searched some documents and while all of them require keyboard access support they don't really emphasize the existence of shortcuts.

One example: https://developer.chrome.com/extensions/a11y#shortcuts

**Comment by marcoscaceres** [comment]
I also think it would be best if we fix the ReSpec pill's keyboard accessibility issues instead (https://github.com/w3c/respec/issues/1064). Need to basically treat the popup menu as a `<dialog>`, and then make it possible to tab around. Right now, it's completely broken :(

**Comment by saschanaz** [comment]
`<dialog>` support is currently extremely bad so we would need a polyfill for that.

**Comment by saschanaz** [comment]
I feel we just need a single shortcut to access the pill from anywhere, everything else can be done with the tab key.

(Moved from https://github.com/w3c/respec/issues/2010#issuecomment-452215116 🤣)

**Comment by marcoscaceres** [comment]
> `<dialog>` support is currently extremely bad so we would need a polyfill for that.

Agree. Google ships a really good one (used it before elsewhere): https://github.com/GoogleChrome/dialog-polyfill

**Comment by devanshbatra04** [comment]
Can I take this. I understand you might want to keep it for GSoC. Really looking forward to a challenging issue. :sweat_smile:

**Comment by marcoscaceres** [comment]
This one is higher priority if you’d like a challenge:

https://github.com/w3c/respec/pull/2154

**Comment by marcoscaceres** [comment]
Closing as answered: we keep shortcuts for now.
