### ISSUE TITLE
WebIDL-thing-is-not-defined link is gone

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2003]
https://github.com/w3c/respec/wiki/WebIDL-thing-is-not-defined

This link is currently being used to guide users but it's now gone. What happened? [It definitely was there](https://webcache.googleusercontent.com/search?q=cache:J3ZxBIDdGv8J:https://github.com/w3c/respec/wiki/WebIDL-thing-is-not-defined+&cd=1&hl=en&ct=clnk&gl=us).

**Comment by sidvishnoi** [comment]
yet another spam bot attack
![image](https://user-images.githubusercontent.com/8426945/50735485-ec334500-11d5-11e9-861a-f071f006a1e8.png)

**Comment by sidvishnoi** [comment]
Fixed. [Not our first time](https://github.com/w3c/respec/wiki/WebIDL-thing-is-not-defined/_history).

**Comment by saschanaz** [comment]
TIL I can clone a GH wiki.
