### ISSUE TITLE
Point the IDL block that misses <dfn>

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2004]
## Important info

* URL to affected spec: https://w3c.github.io/touch-events/
* ReSpec version: 24.0.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?:

Currently it's hard to find what elements are causing warnings.

![image](https://user-images.githubusercontent.com/3396686/50735792-ab4c2800-11f7-11e9-97f4-c33631e2bc4e.png)

But what I was expecting?:

Links to the faulty blocks.

**Comment by marcoscaceres** [comment]
Looks like they are trying to define too many things in the same section. The enum, dictionary, and interface should be split into their own `<section>`s.

**Comment by saschanaz** [comment]
This was to ease fixing `<a>idlMember</a>` without `data-link-for` (while the screenshot only shows IDL linking. My bad). Splitting a section doesn't really help here.

**Comment by marcoscaceres** [comment]
@saschanaz, I'm not sure I follow. Wouldn't something like the following fix things? Or are you consider something better?:

```JS
<pre class="idl">
  ...current idl in here...
</pre>
<section data-dfn-for="Touch">
</section>
<section data-dfn-for="TouchInit">
</section>
<section data-dfn-for="TouchEnum">
</section>
```

**Comment by saschanaz** [comment]
That would be clean, but think about this:

```html
<pre class="idl">
</pre>
<section>
  ... <a>myMethod</a> ... 
</section>
<section>
  ... <a>myAnotherMethod</a> ...
</section>
<section>
  ... <a>someOtherThing</a> ...
</section>
```

Definitely the fix is to add proper `data-dfn-for` but at first one has to find where the warnings are from. Currently the only way is to `Control+F`.

**Comment by marcoscaceres** [comment]
Ah, got it. Odd, I thought we were outputting those to the developer console... looking, we definitely don't. I wonder if that's a regression? (maybe not, as I don't see "See developer console.")

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/50747083-7a123d00-1275-11e9-9ba6-6db551184394.png)

We currently correctly get links to the elements but not when linking from `<pre class="idl">`. Fixed the original post to match.
