### ISSUE TITLE
respec-w3c-common.js.map cannot be found

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2006]
https://www.w3.org/Tools/respec/respec-w3c-common.js.map

Currently this throws HTTP 300 and breaks source mapping. Maybe the server should be configured to correctly redirect it.

**Comment by marcoscaceres** [comment]
Ah, I think the w3c server is specifically configured to only work with old file name. We might need to switch back to the crappy name.

**Comment by saschanaz** [comment]
Or we can get a symbolic link to the new name for compatibility 😀

**Comment by marcoscaceres** [comment]
Ok, let's try for that.

@deniak or @tripu, we previously were getting the W3C to serve:
respec/respec-w3c-common.build.js.map

But we renamed that to:
respec/respec-w3c-common.js.map

Would it be possible to get that updated on the w3c side?

**Comment by saschanaz** [comment]
Maybe we can also use third-party `unpkg.com` or `rawgit.com`, etc...

**Comment by tripu** [comment]
[Done](https://www.w3.org/Tools/respec/respec-w3c-common.js.map). The file should be refreshed automatically, like the rest.
