### ISSUE TITLE
replacement for conf.definitionMap?

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2019]
## Important info

* URL to affected spec: https://w3c.github.com/json-ld-syntax
* ReSpec version: 24.1.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

  #1954 removed `definitionMap` from the configuration. This is used in my specs to iterate over definitions and remove those that aren't referenced; it's now broken.

  Is there a replacement mechanism for me to do this using pubsub or something similar?

What happened (e.g., it crashed)?: 

  Developer console complains `TypeError: undefined is not an object (evaluating 'respecConfig.definitionMap[item]')`

But what I was expecting?: A means to iterate over definitions. The code also still depends on jQuery for `makeID`.

Optional, steps to reproduce:
 1. Load, for example, https://w3c.github.com/json-ld-syntax
 2. Note developer console message

**Comment by saschanaz** [comment]
A quick fix is to add `expose("core/dfn-map", { definitionMap });`  in `core/dfn-map.js` which will enable `require("core/dfn-map")`. IMO we should avoid adding such AMD API, though...

**Comment by marcoscaceres** [comment]
Agree about not adding that... what are some alternatives? Should we temporarily again expose  `conf.definitionMap` while we figure this out? That will at least fix the existing spec and let us come up with something cleaner.

**Comment by saschanaz** [comment]
Yes, that will give us some time. #1976 is my suggestion, BTW.

**Comment by marcoscaceres** [comment]
I like where #1976 is going. We should pick that back up.

**Comment by gkellogg** [comment]
There are different things in https://w3c.github.io/json-ld-syntax/common/common.js besides the support for managing definition lists, the important parts is the following:

https://github.com/w3c/json-ld-syntax/blob/6f92b1d634760cd7a393b41bce01e151bfd753f0/common/common.js#L15-L115

This is based on code originally created by @halindrome (IIRC) but used in a number of projects where multiple specs share definitions. It's quite dependent on the use of definition lists (`dl`) to determine if definitions are used outside of the scope of the definition itself. Abstracting this for definitions in general would be difficult using this approach.

A better solution might be to introduce something like a `data-dfn-scope` attribute, to separate the definition from the use. Then, you could determine if uses are inside or outside of the scope, and (optionally) remove all elements having a `data-dfn-scope` matching the unused definition. I think this would be broadly useful, and would simplify editors dependence on ReSpec internals.

For example, the definition found at https://github.com/w3c/json-ld-syntax/blob/6f92b1d634760cd7a393b41bce01e151bfd753f0/common/terms.html#L66-L69 might instead be the following:

```html
<dt data-dfn-scope="absolute IRI"><dfn>absolute IRI</dfn>
<dd data-dfn-scope="absolute IRI">An <a data-cite="RFC3987#section-1.3" class="externalDFN">absolute IRI</a>
    is defined in [[RFC3987]] containing a <em>scheme</em> along with a <em>path</em>
    and optional <em>query</em> and fragment segments.</dd>
```
