### ISSUE TITLE
Add core defaults

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2023]
It would be nice to have a "core/defaults" module, that sets the default core defaults that every specification or document is expected to have. Those can the be amended or overridden by specific profiles. 

For example, all specs should have a specStatus of "unofficial" by default. The license should probably be some CC license, and so on...  

Example of W3C defaults, on which this could be based:
https://github.com/w3c/respec/blob/develop/src/w3c/defaults.js

**Comment by saurabhmittal16** [comment]
Can I try this if no one has started already?

**Comment by marcoscaceres** [comment]
@saurabhmittal16, sure! Is it clear what needs to be done? Let me know if you need more guidance.

**Comment by saurabhmittal16** [comment]
Can you give a brief explanation of how to begin and what should be the default of different config option.
Thanks
