### ISSUE TITLE
Show "Preview of #" in title

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2030]
See the following for details:
https://github.com/tobie/pr-preview/issues/23

Basically, the spec's title should come "Preview of PR xxx: " when the spec `isPreview` is true. 

This would build on @yatri1609's work: 
https://github.com/w3c/respec/pull/1843

**Comment by marcoscaceres** [comment]
@yatri1609, you want to take this one too? It's just a repeat of what you did previously - but this one changes the `<h1>` and `<title>` of the document.

**Comment by yatri1609** [comment]
@marcoscaceres I'll take this one up !! :grinning:

**Comment by marcoscaceres** [comment]
@yatri1609, much appreciated! Let me know if you need any more details or additional guidance.

**Comment by shreya99oak** [comment]
@yatri1609 are you still working on it? @marcoscaceres can I work on it?

**Comment by yatri1609** [comment]
@shreya99oak yes I'm working on it you can have a look at other issues

**Comment by shreya99oak** [comment]
> @shreya99oak there are a few easy tasks in this issue:
> #1582
Ohk I'll have a look at it!

**Comment by marcoscaceres** [comment]
@shreya99oak, this one just came up:
https://github.com/w3c/respec/issues/2051

It's a relatively easy one, but super useful/important. Do you think you could take it on?

**Comment by yatri1609** [comment]
@marcoscaceres The title must be "Preview of PR xxx: " instead of "This is a preview of pull request `PR number`. Am I understanding it correct?

**Comment by yatri1609** [comment]
@marcoscaceres great I'll do that !

**Comment by ThobyV** [comment]
Is there a person working on this issue please?

**Comment by marcoscaceres** [comment]
It’s all yours @ThobyV
