### ISSUE TITLE
Example link fragments are crazy long

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2033]
## Important info

* URL to affected spec:
https://w3c.github.io/screen-orientation/#ex-1-example-1-script-var-show-function-console-log-orientation-type-is-screen-orientation-type-console-log-orientation-angle-is-screen-orientation-angle-screen-orientation-addeventlistener-change-show-window-onload-show-script-button-onclick-screen-orientation-unlock-unlock-button-button-onclick-screen-orientation-lock-portrait-lock-to-portrait-button-button-onclick-screen-orientation-lock-landscape-lock-to-landscape-button

## Description of problem

What happened (e.g., it crashed)?: 
Links on examples without a title are crazy long... see above. Seems to be using the textContent to generate the fragment, instead of just "#ex-2" or "#example-2". 
 
But what I was expecting?:

Something less insane. 

Optional, steps to reproduce:
 
```HTML 
<aside class="example">

</aside>
```

**Comment by nkkumawat** [comment]
@marcoscaceres Can I try this?
