### ISSUE TITLE
aside example `pre` tags don't self indent 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2034]
## Important info

* URL to affected spec:
https://github.com/w3c/payment-request/pull/824/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR1119

## Description of problem
What happened (e.g., it crashed)?: 
For whatever reason, when you have:

```
<aside class="example">
   <pre class="js">
   // stuff...
   </pre>
</aside>
```

The pre highlights, but doesn't correctly remove the whitespace... 

While doing:

```HTML
<div>
  <pre class="example">
  // this works fine.
  <pre>
</div>
```

But what I was expecting?:

For `<pre class=example>` and `<aside> <pre class=js>` to work the same.

**Comment by Swapnilr1** [comment]
I would like to take this up.

**Comment by marcoscaceres** [comment]
sure, a place to start would be:
https://github.com/w3c/respec/blob/develop/src/core/examples.js#L31

Otherwise, here, where the nightlight happens:
https://github.com/w3c/respec/blob/develop/src/core/highlight.js#L61
