### ISSUE TITLE
Unclear if "can I use" when printing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2041]
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version:  24.2.3.
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
When a spec is printed (on paper/PDF), the "can I use" section in the header of doc doesn't actually show if something is supported or not:

![screenshot 2019-01-22 16 25 27](https://user-images.githubusercontent.com/870154/51514139-9233b000-1e62-11e9-882a-4c0f0b9e8d60.png)

But what I was expecting?:

To be able to distinguish them, maybe with ✅ and ❌ and ？ (or similar). 

Optional, steps to reproduce:
 1. Print first page of the spec.

**Comment by marcoscaceres** [comment]
This one just needs to print media rule in: 
https://github.com/w3c/respec/blob/develop/assets/caniuse.css

**Comment by CodHeK** [comment]
@marcoscaceres can I work on this issue ?

**Comment by marcoscaceres** [comment]
@CodHeK, sure! Go for it.

**Comment by marcoscaceres** [comment]
@CodHeK let me know if you need a hand or further details. Please see the Developer Guide linked from the README for instructions to get started.

**Comment by CodHeK** [comment]
@marcoscaceres  Yes, sure! Also, is the issue about adding "ticks" and "crosses" to the ones that are supported ?

**Comment by marcoscaceres** [comment]
Yes, we need to distinguish between them in a meaningful way. If you think there is a better way of doing it, I'm all ears. You might like to take a look at the caniuse.com site for inspiration. 

My feeling is that this can all be done in CSS (in the file linked above) - but I'm open to suggestions.

**Comment by CodHeK** [comment]
Ok, great!

**Comment by marcoscaceres** [comment]
This is how we currently display them on Desktop browsers:

![screenshot 2019-01-22 20 20 34](https://user-images.githubusercontent.com/870154/51524911-42191580-1e83-11e9-8685-be2da512ac38.png)

Note the title attribute there... it's also an option to display that generated content.

**Comment by marcoscaceres** [comment]
This might help too: https://css-tricks.com/css-content/

**Comment by CodHeK** [comment]
@marcoscaceres or if we could only display the ones it supports ?

**Comment by marcoscaceres** [comment]
No, I think it's important to display all of them. The ones that are supported are equally as important as the ones that are not.

**Comment by CodHeK** [comment]
@marcoscaceres any specific version of node required, my `npm install` always get's stuck `extract:rxjs: sill extract @webassemblyjs/helper-fsm@1.7.11`

I am using `node v11.1.0`

**Comment by marcoscaceres** [comment]
Hmm... no. That node version should be is fine? Worst case, quickly try Node LTS to see if you get the same error.

**Comment by CodHeK** [comment]
@marcoscaceres  What I am planning to do is, display all drop downs with the "tick" or the "cross" and the version, that way we can see which ones are supported when its printed on paper/PDF.

Also, when I am making changes in the css, where do I see the changes ? I mean how can I test the changes made by me ?

**Comment by marcoscaceres** [comment]
@CodHeK wrote:

> What I am planning to do is, display all drop downs always (no toggling) with the "tick" or the "cross" and the respective version... that way we can see which ones are supported when its printed on paper/PDF. 

Ok, but to be clear: the Desktop/Mobile versions are fine and  don't need to change. It's only the printed version. 

> Also, when I am making changes in the css, where do I see the changes ? I mean how can I test the changes made by me ?

What I do is I run two terminal windows (Bash or whatever). In one I run:

```bash
npm run babel:watch 
```

Which will track the changes:

And in another: 

```
npm start
```

That will spin up the web server and go to: http://localhost:5000/examples/basic.html. That will load up the bable compiled code and hopefully the CSS changes.  

However, if you find the CSS is not being updated, manually run:

```
npm run babel:build
```

That should force the CSS in ReSpec to be updated.

**Comment by CodHeK** [comment]
@marcoscaceres  This is what I thought ...
![screenshot 2019-01-23 at 10 07 12 am](https://user-images.githubusercontent.com/22097366/51583507-ea1bf680-1ef6-11e9-9548-affa48b04fe3.png)

The print preview 

![screenshot 2019-01-23 at 10 07 27 am](https://user-images.githubusercontent.com/22097366/51583526-0029b700-1ef7-11e9-844d-ee76114074f2.png)

**Comment by marcoscaceres** [comment]
Glad to see you got it going!

For print view, it's probably not necessary to expand the columns. Just showing the current one is fine.

The desktop version, it's fine for it to remain as is (i.e., no ticks or crosses).

**Comment by CodHeK** [comment]
Okay so, how do you want it to be when it’s printed ? The issue was specifically about adding the ticks and crosses for the case when it was printed ...


On Wednesday, January 23, 2019, 11:14 AM, Marcos Cáceres <notifications@github.com> wrote:


Glad to see you got it going!

For print view, it's probably not necessary to expand the columns. Just showing the current one is fine.

The desktop version, it's fine for it to remain as is (i.e., no ticks or crosses).

**Comment by marcoscaceres** [comment]
> Okay so, how do you want it to be when it’s printed ? The issue was specifically about adding the ticks and crosses for the case when it was printed ..

Two options I was thinking about: 

<img width="549" alt="screenshot 2019-01-23 17 37 20" src="https://user-images.githubusercontent.com/870154/51587649-8ebd2900-1f35-11e9-8069-73a03e04b829.png">

Alternatively, using CSS generated content, if you use the `title` attribute's value, you can show, for example:

"Almost supported (aka Partial support) in Chrome 67. Supported in Firefox 66. Not supported or disabled by default in Safari." 

That would also be nice, as it would make it super clear.

**Comment by marcoscaceres** [comment]
If you got the emoji route: the "✓" emoji is better than the one pictured above.

**Comment by marcoscaceres** [comment]
fixed typo above.

**Comment by CodHeK** [comment]
@marcoscaceres  Great, got it! Also, if you could confirm out the cases mentioned below when should I print the tick , cross, question mark.

```
  ["y", "Supported."],
  ["a", "Almost supported (aka Partial support)."],
  ["n", "No support, or disabled by default."],
  ["p", "No support, but has Polyfill."],
  ["u", "Support unknown."],
  ["x", "Requires prefix to work."],
  ["d", "Disabled by default (needs to enabled)."],
```

Because there are cases when there are combination of these in the `title`.

**Comment by CodHeK** [comment]
Sent a PR! 

- Browser :

![screenshot 2019-01-23 at 1 27 30 pm](https://user-images.githubusercontent.com/22097366/51591375-d4b4c580-1f12-11e9-86eb-d9b52858044e.png)

- When Printing : 

![screenshot 2019-01-23 at 1 27 38 pm](https://user-images.githubusercontent.com/22097366/51591403-e9915900-1f12-11e9-88d8-65148817cd02.png)
