### ISSUE TITLE
div that are of class "note" should have a role="note"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2045]
Given:

```HTML
<div class="note">
  <p>I'm a note</p>
</div>
```

It would be great if the `<div>` got a [`role="note"`](https://www.w3.org/TR/wai-aria-1.1/#note) attribute also attached to it.

**Comment by nkkumawat** [comment]
@marcoscaceres can I try this?

**Comment by marcoscaceres** [comment]
Sure. This one should be fairly easy too. See “issues-notes.js”.
