### ISSUE TITLE
Missing section marker when sections are cited 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2046]
Give:

```
<section id="section1">
  <h2>The first section</h2>
</section>
<section id="section2">
  <h2>Another section</h2>
 <p>See <a href="#section1"></a>.<p>
</section>
```

It would be nice if the output of `<a href="#section1"></a>` would be preceded by a section marker sign (§).... so: "See § 1. The first Section".

**Comment by nkkumawat** [comment]
@marcoscaceres assign this to me if no one is working on this.

**Comment by marcoscaceres** [comment]
Sure, go for it. However, I wasn’t able to remember which module controls this, so you might need to do some digging. I’d suggest grep’ing for `querySelectorAll` and seeing which are selecting `a` elements. One of them is expanding them out.
