### ISSUE TITLE
If a spec lacks <section id=conformance>, then it reference should be informative

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2051]
## Important info

* URL to affected spec:
https://w3c.github.io/dxwg/ucr/

## Description of problem
Specs can have either Informative or Normative references. By default, ReSpec treats all documents as if they were Normative. However, some documents, like Use Cases docs, generally are don't use Normative references.  

But what I was expecting?:
The citations in a document that doesn't declare a conformance section (i.e., `<section id="conformance">`) to be treated as Informative. 

To achieve this, all we need to do is add "informative" to the class `attribute` of the `<body>` element  here: 
https://github.com/w3c/respec/blob/develop/src/w3c/conformance.js#L10

cc @andrea-perego

**Comment by marcoscaceres** [comment]
I've asked @shreya99oak if they can work on this. @shreya99oak, if you can, I can provide you with additional guidance. If you haven't already, please get set up by reading the README and follow the link there to the Developer Guide.

**Comment by shreya99oak** [comment]
I'll work on this! Yeah, additional guidance would do:)

**Comment by shreya99oak** [comment]
Thanks!

**Comment by devikasugathan** [comment]
I'm an absolute beginner and would like to take this up as my first contribution.
@shreya99oak are you still working on it? if not @marcoscaceres can I work on it?

**Comment by marcoscaceres** [comment]
@devikasugathan feel free to take it.

**Comment by yatri1609** [comment]
@marcoscaceres Is anyone working on this? If not I can work on this, if you approve.

**Comment by marcoscaceres** [comment]
> @marcoscaceres Is anyone working on this? If not I can work on this, if you approve.

I'm actually working on it at the moment 😬 Turned out to be actually quite a lot of work.
