### ISSUE TITLE
Problem with WSDL "latest version" URLs

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2052]
Just discovered using SpecRef.

Searching for `wsdl` in SpecRef (http://api.specref.org/bibrefs?refs=wsdl) returns what follows:

````json
{"wsdl":{
  "versions":[
    "wsdl-20010315"
  ],
  "href":"https://www.w3.org/TR/wsdl",
  "publisher":"W3C",
  "status":"NOTE",
  "title":"Web Service Definition Language (WSDL)",
  "id":"wsdl",
  "date":"15 March 2001"
}}
````

The issue is that https://www.w3.org/TR/wsdl is not pointing to WSDL 1.1, but to WSDL 2.0 Part 1 (which is not a Note, but a Recommendation).

**Comment by marcoscaceres** [comment]
hmm... does this mean it should be fixed at https://github.com/tobie/specref/ ? ReSpec just renders whatever specref gives back to us.

**Comment by andrea-perego** [comment]
Yes, but the W3C entries in SpecRef are provided by W3C itself.

I think the main question is whether it is correct that

https://www.w3.org/TR/wsdl

redirects to

http://www.w3.org/TR/2007/REC-wsdl20-20070626

instead of

https://www.w3.org/TR/2001/NOTE-wsdl-20010315

**Comment by marcoscaceres** [comment]
I see what you mean... the entry is wrong. It should be the REC. 

@tobie, is the W3C providing us with the wrong data?

**Comment by andrea-perego** [comment]
@marcoscaceres , I'm not sure it's SpecRef. If you check WSLD 1.1

https://www.w3.org/TR/2001/NOTE-wsdl-20010315

the spec indicates as URL of the latest version the following one

https://www.w3.org/TR/wsdl

So, IMO, SpecRef returns the correct information. The issue is that https://www.w3.org/TR/wsdl points to WSDL 2.0, and not to WSDL 1.1, as it should.

**Comment by tobie** [comment]
Well, if this is objectively wrong, we can always override stuff in Specref.

**Comment by tobie** [comment]
See https://github.com/tobie/specref/blob/master/overwrites/w3c.json.

**Comment by marcoscaceres** [comment]
Ah, I didn't know we had that override... IMO it's definitely wrong. Following the link (https://www.w3.org/TR/wsdl) takes you to a W3C Recommendation... that's a pretty big difference to what's there.

**Comment by tobie** [comment]
PR… pretty please?

![image](https://user-images.githubusercontent.com/3392/52045513-f7fbf800-2544-11e9-8d11-9e2f539e302b.png)

**Comment by marcoscaceres** [comment]
heh, dunno, but it was a good one :D

**Comment by marcoscaceres** [comment]
Closing, as this was specref issue.
