### ISSUE TITLE
can't install respec

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/respec#2053]
## Important info

* URL to affected spec: https://travis-ci.org/w3c/webdriver/builds/486466970?utm_source=github_status&utm_medium=notification
* ReSpec version: latest, see travis.yml
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: npm failed to install highlight.js because of missing sha

But what I was expecting?: it to install...

Optional, steps to reproduce:
 1. npm i -g respec

the error log is 48 http fetch GET 200 https://registry.npmjs.org/snyk 1417ms
49 silly pacote range manifest for snyk@^1.122.0 fetched in 1429ms
50 silly resolveWithNewModule snyk@1.123.0 checking installable status
51 silly fetchPackageMetaData error for highlight.js@github:marcoscaceres/highlight.js#7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32 Command failed: /usr/local/bin/git checkout 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
51 silly fetchPackageMetaData fatal: reference is not a tree: 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
52 timing stage:rollbackFailedOptional Completed in 0ms
53 timing stage:runTopLevelLifecycles Completed in 11921ms
54 verbose stack Error: Command failed: /usr/local/bin/git checkout 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
54 verbose stack fatal: reference is not a tree: 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
54 verbose stack
54 verbose stack     at ChildProcess.exithandler (child_process.js:297:12)
54 verbose stack     at ChildProcess.emit (events.js:197:13)
54 verbose stack     at maybeClose (internal/child_process.js:978:16)
54 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
55 verbose cwd /Users/davidburns/development/mozilla-unified
56 verbose Darwin 18.2.0
57 verbose argv "/usr/local/Cellar/node/11.8.0/bin/node" "/usr/local/bin/npm" "install" "-g" "respec"
58 verbose node v11.8.0
59 verbose npm  v6.5.0
60 error code 128
61 error Command failed: /usr/local/bin/git checkout 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
61 error fatal: reference is not a tree: 7b144b3b83ce296d5b29c5e4fc2ea2a65e9d3f32
62 verbose exit [ 1, true ]

**Comment by marcoscaceres** [comment]
Oops! on it!
