### ISSUE TITLE
MDN bar overshawdows text

### ISSUE THREAD

**Issue by CodHeK** [w3c/respec#2056]
![screenshot 2019-01-31 at 2 17 48 pm](https://user-images.githubusercontent.com/22097366/52042455-399b9b80-2563-11e9-9b69-7eb2d93dcfbe.png)
## Important info

* URL to affected spec: [link](https://html.spec.whatwg.org/multipage/interaction.html#gains-focus)
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?:  The MDN support bar overshadows the text in the webpage.

But what I was expecting?: Better if we could have a way make it sticky and minimize it when not required.

**Comment by sidvishnoi** [comment]
Closing as not an issue with ReSpec. HTML spec doesn't use ReSpec.

**Comment by marcoscaceres** [comment]
Thanks @sidvishnoi. 

I'm cc'ing @sideshowbarker so he is aware of the bug (as he authored that MDN box, I believe). Mike, should we transfer this issue somewhere for you?

**Comment by sideshowbarker** [comment]
I am aware of the issue and will be making time soon to rework how the MDN annotations in the HTML spec are presented.

But in the mean time, note that to view the underlying text, you can collapse the entire annotation down to just width of the **MDN** text, all the way over to the right margin.

To make the annotation collapse that way, click inside the upper left-hand corner of the annotation, where angled-ellipses control can be seen.
