### ISSUE TITLE
Emit all errors/warning when with `-e -w`

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2062]
Currently respec2html with `-e -w` halts when it meets the first error or warning message. It should instead emit all messages and then halt, so that the author can fix all things at once.

**Comment by saschanaz** [comment]
@EvsChen Sure! Feel free to ask questions if needed.

**Comment by EvsChen** [comment]
Hi @saschanaz! I have a question. If the script does not halt on error/warning, it seems to me adding `-e` and `-w` will produce no effect to the output. I'm a little confused.

**Comment by saschanaz** [comment]
@EvsChen Try adding this IDL on a document:

```
interface UndefinedInterface {
  void undefinedAttribute();
};
```

and run respec2html against it with `-e -w`. It should emit all warnings and then halt, without an output file.

**Comment by EvsChen** [comment]
I'm not quite sure if we could achieve what you mentioned by "without an output file". When we start writing the output, we cannot decide whether all the errors and warnings have been emitted.

But the first part is definitely OK, i.e. "emit all the warnings/errors".

**Comment by saschanaz** [comment]
>When we start writing the output, we cannot decide whether all the errors and warnings have been emitted.

respec2html already emits an output file only after the processing is completed (as it waits respecIsReady).

All console errors/warnings before that point should be always shown.

**Comment by EvsChen** [comment]
Hi @saschanaz I've submitted a PR (ignore the closed one). Please review!
The handle of the `flags` is kinda weird. I wonder if there is a better way to do this.
