### ISSUE TITLE
ReSpec intercepting button onclick?

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2064]
## Important info

* URL to affected spec: https://w3c.github.io/json-ld-syntax
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1). 24.2.5
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The spec uses an "onclick" in buttons used for tabbing in examples (e.g., [example 3](https://w3c.github.io/json-ld-syntax/#example-3-sample-json-ld-document-using-full-iris-instead-of-terms). The onclick event is not detected for these buttons, although it was recently. Interestingly, if the spec is saved to HTML, the events are triggered, and tabbing works.

The code that does this is inline in the spec [here](https://github.com/w3c/json-ld-syntax/blob/master/index.html#L121-L134). You can see how it should work in the latest published spec [here](https://www.w3.org/TR/json-ld11/#ex-3-sample-json-ld-document-using-full-iris-instead-of-terms), or by saving the editors draft and trying there.

**Comment by gkellogg** [comment]
cc/ @iherman

**Comment by saschanaz** [comment]
I think #2050 is the culprit.

**Comment by gkellogg** [comment]
I'm still seeing the problem in 24.3.0, has the fix been released?  For example, click on tabs in https://w3c.github.io/json-ld-syntax/#example-30-using-vocabularies.

**Comment by marcoscaceres** [comment]
Confirmed. Reopening.

**Comment by marcoscaceres** [comment]
Greg, as a temporary work around, would it be possible for you to make the modifications after ReSpec is done? (I.e., using `postProcess`).

**Comment by marcoscaceres** [comment]
Note for when we try to fix this: using hyperHTML.bind() on the div should retain the event handler.

**Comment by saschanaz** [comment]
@marcoscaceres The issue here is that #2082 has been released yet.

**Comment by marcoscaceres** [comment]
oh, my bad. I thought I'd released it!!!

**Comment by marcoscaceres** [comment]
Doing release right now.

**Comment by marcoscaceres** [comment]
Working, thanks @saschanaz! ☺️
