### ISSUE TITLE
Suggest removal of redundant config options

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2065]
## Important info

* URL to affected spec:
https://w3c.github.io/payment-request/

## Description of problem
ReSpec users generally copy/paste the "respecConfig". What would be nice is that for config values that are already on by default (in core/default or w3c/default), ReSpec should warn that those should be removed from the configuration.

This depends on : 
https://github.com/w3c/respec/pull/2042

**Comment by saschanaz** [comment]
Is that behavior generally preferred? I think explicit values ensures that the local settings would never be affected by upstream changes.

**Comment by zerefwayne** [comment]
@marcoscaceres Can I work on this issue? I'm new to pdf.js

**Comment by marcoscaceres** [comment]
Heh, good recovery (pdf.js 👀😁). Sure, please get set up by reading the developer guide - link is in the README.

**Comment by isunitha98selvan** [comment]
Hey. Can I work on this ?

**Comment by gaurav3210** [comment]
Is there any issues which not yet get assigned. Please tell about that I want to get assigned.

**Comment by marcoscaceres** [comment]
@gaurav3210, you are free to grab any claimed issue that hasn't been completed after a week.

**Comment by gaurav3210** [comment]
Thank you sir.

**Comment by gaurav3210** [comment]
Will you please assigned this issue to me. I will PR by tomorrow

**Comment by marcoscaceres** [comment]
@gaurav3210 please see the good first issues list. If you are interested in GSoC, having self initiative is a prerequisite.

**Comment by lolimay** [comment]
> ReSpec should warn that those should be removed from the configuration.

I am so confused about this feature. In my opinion, instead of warning user that those duplicated configurations should be removed, we can introduce the concept of configuration priority. In this way, `core/defaults` with higher priority can overwrite `w3c/defaults` with a lower priority so that ReSpec can automatically these handle configuration conflicts instead of bothering users.

@marcoscaceres ，please let me know whether I should work on this idea. Thanks!

**Comment by lolimay** [comment]
Sorry for possibly misunderstanding what you mean:
> ReSpec users generally copy/paste the "respecConfig". **What would be nice is that for config values that are already on by default (in core/default or w3c/default)**, ReSpec should warn that those should be removed from the configuration.

Are you mean that we should warn users that which configrations were turned on by default?

**Comment by marcoscaceres** [comment]
> Are you mean that we should warn users that which configrations were turned on by default?

Yes... but I'm having second thoughts. Reflecting on the previous discussions, I think it's fine to just leave them.
