### ISSUE TITLE
New field under the participate header called `Contribute`

### ISSUE THREAD

**Issue by CodHeK** [w3c/respec#2071]
## Description of problem

![screenshot 2019-02-05 at 2 17 39 pm](https://user-images.githubusercontent.com/22097366/52261968-1309a600-2951-11e9-8191-c18f92859f81.png)

We could add a new field `Contribute` that could redirect the user directly to the APIs contribution guide / developer's guide.

**Comment by marcoscaceres** [comment]
Unfortunately, I don’t know of any specs that have such a guide. Do you have an example you are thinking of?

**Comment by CodHeK** [comment]
I figured if there is an option to `file a bug` there must be some way to contribute as well

**Comment by marcoscaceres** [comment]
Generally, we rely on the first link as the way people get to a repo’s readme. The problem with contributing to standards is that it’s a bit nontrivial: people have to sign things, others have to pay a bunch of money, etc.... so the easiest way is for people to “file a bug” as per the link above .

**Comment by marcoscaceres** [comment]
Closing this as it's a bit outside the scope of what ReSpec can do (and the current links more or less serve this purpose). Appreciate the suggestion nonetheless.
