### ISSUE TITLE
Explore why eslint on Travis is too permissive

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2074]
From https://github.com/w3c/respec/pull/2073#issuecomment-460691098.

**Comment by saschanaz** [comment]
I tried some back and forth on my own branch and found that eslint on Travis works correctly for src/core but not for src/core/linter-rules. Maybe some directory glob problem, but not sure why as we use same glob pattern on both Travis and local.

**Comment by marcoscaceres** [comment]
Maybe OS level thing?

**Comment by saschanaz** [comment]
@marcoscaceres Yes, it seems so... turns out that quoting helps. 🤦‍♀️

https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784
