### ISSUE TITLE
Linter rule to check for non-en-US english in IDL

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2078]
See this Twitter thread: 
https://twitter.com/marcosc/status/1093151940769341440?s=20

In W3C docs/specs, we should check WebIDL attributes and operation identfiers are in US English. 

I wonder if there is some way of doing it? Need to research.

**Comment by marcoscaceres** [comment]
Maybe https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage

**Comment by CodHeK** [comment]
@marcoscaceres can I try this ?

**Comment by saschanaz** [comment]
@marcoscaceres That's a WebExtensions API but ReSpec is not an extension 😅

**Comment by marcoscaceres** [comment]
Oh whoops... totally missed that. I was wondering how I'd missed that API... would have been a "too good to be true" addition to the web :)

**Comment by CodHeK** [comment]
@marcoscaceres can we use this: [https://www.npmjs.com/package/languagedetect](https://www.npmjs.com/package/languagedetect ) ?

**Comment by saschanaz** [comment]
@CodHeK I don't think we want to add a 200+ KiB dependency.

**Comment by CodHeK** [comment]
@saschanaz could you please help me find where the `WebIDL attributes and operation identfiers` are ?

**Comment by saschanaz** [comment]
https://github.com/w3c/respec/blob/d451e5efb187ba3b62205998fa0e12606a5a21f1/src/core/webidl.js#L114-L130

@CodHeK Here, but what are you going to do?

**Comment by CodHeK** [comment]
@saschanaz I am just trying to understand what the issue is about and see if we could do anything ...

**Comment by CodHeK** [comment]
@saschanaz what are the attributes/identifier here which need to be checked for the language ?

**Comment by saschanaz** [comment]
@CodHeK `data.name` should be checked there as that presents IDL identifiers. I think `data.name` is enough.

**Comment by CodHeK** [comment]
You mean the variable name at [L119](https://github.com/w3c/respec/issues/2078#L119)

**Comment by marcoscaceres** [comment]
I think this might be impossible to do reliably... @CodHeK, before looking at code, check if it's even possible at all without an actual *real* dictionary. I just don't think it is, because, for example:

```
attribute Laser laser;
```

So we would need some kind of dictionary lookup.... unless there is some actual Dictionary API on the web we would use, but that seems a bit extreme.

**Comment by CodHeK** [comment]
I got two packages, `typo-js` (83kb)  and `check-word` (3kb) they both seem pretty lightweight, we could use them I guess

**Comment by marcoscaceres** [comment]
ok, 83kb is way too massive... and looks like check-word doesn't give us the precision :(

https://github.com/S0c5/node-check-word/blob/master/index.js#L8

**Comment by saschanaz** [comment]
`check-word` is not 3 KiB as its dictionaries are already 37 MiB.

**Comment by marcoscaceres** [comment]
heh, yeah: https://raw.githubusercontent.com/S0c5/node-check-word/master/word-regexes/en-regex.js

**Comment by marcoscaceres** [comment]
it has the whole dictionary. That's awesome :) lol.. 

I think I'm going to close this.
