### ISSUE TITLE
Modules should contain their own localization information

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2084]
We currently have localization strings in core/l10n.js that are used throughout ReSpec. However, it's rare that a localized string is used in more than one place at a time. What would be better is for where localization happens, the strings be included in the appropriate module itself. 

Then core/l10n should only export the `lang` of the document, which should be configurable. Then each module that requires localization should just key off that value.  

This model is already used by the linter modules:
https://github.com/w3c/respec/blob/develop/src/core/linter-rules/check-charset.js#L6-L18

So, we just need to copy that. 

The following remain:

- [x] src/core/figures.js
- [x] src/core/github.js
- [x] src/core/issues-notes.js
- [x] src/core/structure.js
- [x] src/w3c/headers.js
- [x] src/w3c/templates/cgbg-headers.js
- [x] src/w3c/templates/cgbg-sotd.js
- [x] src/w3c/templates/headers.js
- [x] src/w3c/templates/sotd.js

**Comment by ThobyV** [comment]
Can I take on this issue please?

**Comment by marcoscaceres** [comment]
Sure @ThobyV. Go for it. Are you clear on what you need to do?

**Comment by ThobyV** [comment]
I would need a bit more explanation if you could, but can you please point me to an example module that uses the *core/i10n*  localization strings but not the newly proposed, required model used in https://github.com/w3c/respec/blob/develop/src/core/linter-rules/check-charset.js#L6-L18

I think I would be able to find out more from there.

**Comment by marcoscaceres** [comment]
You should be able to find lots of instances by searching the code for "conf.l10n". 

Try:
```BASH
 git grep -C5 "conf.l10n" src
```

to see where they are used, and in what context.

**Comment by ThobyV** [comment]
Thanks @marcoscaceres for your time. I am about to Implement your instructions and hopefully send a PR for review. However There are some things I wish to be clear about. 

Firstly, Is it ok to remove  the `run` function from *core/I10n* and where it's called since I think we wouldn't need or export it anymore as we are no longer setting the `config.I10n` object to localization strings  (If I am correct). 

Secondly would this mean what I would need to Include the localization strings in the appropriate  modules  with the available language options as used here:
https://github.com/w3c/respec/blob/c115b0438832b4f555933297793356a8add0260d/src/w3c/l10n.js#L4-L27

**Comment by ThobyV** [comment]
Thanks @marcoscaceres for your time. I am about to Implement your instructions and hopefully send a PR for review. However There are some things I wish to be clear about. 

Firstly, Is it ok to remove  the `run` function from *core/I10n* and where it's called since I think we wouldn't need or export it anymore as we are no longer setting the `config.I10n` object to localization strings  (If I am correct). 

Secondly would this mean what I would need to Include the localization strings in the appropriate  modules  with the available language options as used here:
https://github.com/w3c/respec/blob/c115b0438832b4f555933297793356a8add0260d/src/w3c/l10n.js#L4-L27

**Comment by ThobyV** [comment]
@marcoscaceres I do hope I am doing the right things.

**Comment by marcoscaceres** [comment]
> Firstly, Is it ok to remove the `run` function from _core/I10n_ and where it's called since I think we wouldn't need or export it anymore as we are no longer setting the `config.I10n` object to localization strings (If I am correct).

I would leave it for now, for backwards compatibility. There might be people using in in eternal modules that we don't know about. 

> Secondly would this mean what I would need to Include the localization strings in the appropriate modules with the available language options as used here:

Yes, that is correct. 

I'd suggest just starting with one module and just sending a PR for that (so we can check you are on the right path). Don't do them all at once.

**Comment by Irelokeh** [comment]
Oh Thanks @Marcoscaceres, I also thought it would be good to do gradual changes. I will send a P.R For review.

**Comment by ThobyV** [comment]
Oh thanks @marcoscaceres,  I also thought so to work on one module firstly. I will send a PR. I'm grateful for your time.

**Comment by marcoscaceres** [comment]
@ThobyV, looking forward to seeing what you come up with!

**Comment by marcoscaceres** [comment]
Related issue that we should fix as part of this: https://github.com/Geonovum/respec/issues/164

**Comment by ThobyV** [comment]
@marcoscaceres Sure I will be sending a P.R in some hours. Thanks! I want to make sure as possible I try to fix every issue assigned to me. I am very lucky and glad I could use your help. I will contact you more frequently through the issues. 

Also I have checked the *Geonovum* Branch of Respec issue which you referenced. I will try to run some test and then check for fix,

**Comment by marcoscaceres** [comment]
Remember code does not need to be perfect before you send a PR. It’s perfectly fine to send up code just to get initial feedback. If you spend too much time, and you’ve done the wrong thing, you will only find out too late. It’s better to send code up early and get review/guidance as you go (i.e., “perfect is the enemy of the good”).

**Comment by ThobyV** [comment]
Truly I will do Exactly as you say. I have been trying to do things to be perfect. Thanks for the advice. I am encouraged by you @marcoscaceres .

**Comment by marcoscaceres** [comment]
@isunitha98selvan, do you want to collaborate with @ThobyV? See his pull requests and details above to get an idea of what needs to be done. There are lots of these little modules, so it’s a great way to get started.

**Comment by isunitha98selvan** [comment]
Sure I will do that.

**Comment by ThobyV** [comment]
@isunitha98selvan you're welcome to ask me anything if you will.

**Comment by marcoscaceres** [comment]
@ThobyV do you have a rough approximation of which are left. The W3C ones can mostly be ignored.

**Comment by ThobyV** [comment]
@marcoscaceres  I am currently working on the module `figures.js` and I think this module uses the `conf` object for localization only. I checked that the `run` fucntion collects `conf` object and passes to `collectFigures()` and `decorateFigure` which then uses it for localization of captions. 

The linter will not tolerate removing it from the functions that pass it around except it is removed totally from the module. Is this a good thing to do?

**Comment by ThobyV** [comment]
> @ThobyV do you have a rough approximation of which are left. The W3C ones can mostly be ignored.

I think there are 4 modules which I have not worked on in the /W3C and 2 left in /Core.  the w3c has most localization work.

**Comment by marcoscaceres** [comment]
Sorry, I meant finding places where we have hard-coded user facing English strings and replacing then with localized versions. There are plenty that don’t use the l10n object.

**Comment by ThobyV** [comment]
Oh... No wonders. Thanks for explanations. I also thought about non-hard codeds 😙

**Comment by marcoscaceres** [comment]
Accidentally closed this

**Comment by ThobyV** [comment]
Oh I've been away for a while but I have all things in check now! Is there someone re-assigned to this already? Would love to work on it @marcoscaceres

**Comment by marcoscaceres** [comment]
@ThobyV, feel free to continue.

**Comment by ridhishjain** [comment]
@marcoscaceres, @sidvishnoi, are the 4 modules src/w3c (the above ones which are not checked) still needed to be refactored??
If yes, I would like to take this issue.

**Comment by sidvishnoi** [comment]
@ridhishjain that's correct. Assigning it to you!
Feel free to split it into multiple PRs if change set is large.

**Comment by ridhishjain** [comment]
all `src/w3c/templates` files are refactored in these PRs. 
Not sure what to do in `src/w3c/headers.js` as it does not have any `l10n` object in it.

**Comment by marcoscaceres** [comment]
@ridhishjain would be cool just to go through src/w3c/headers.js and see if there is some possibility to localize anything there. There might not be (and that's totally fine), but would be great to just have quick look.

**Comment by ridhishjain** [comment]
There's one thing, we are importing `hyperHTML` from core/import-maps, which itself is importing the same from node_modules directory. Will it be ok to import `hyperHTML` directly in headers.js??

In fact, why do we even need import-maps.js?. Can't we just directly import the stuff wherever it is needed?

**Comment by marcoscaceres** [comment]
Import map is needed, unfortunately, to handle the import for us... it's a long story, but we can't get rid of it right now :(

**Comment by ridhishjain** [comment]
I guess the issue can be closed then

**Comment by sidvishnoi** [comment]
I'll do the remaining ones.
