### ISSUE TITLE
Update my name

### ISSUE THREAD

**Issue by gsnedders** [w3c/respec#2089]
There's a few files in `tests/` that refer to me as Geoffrey; these should be updated to Sam.

Given they're in tests, I don't know if there's any expectations anywhere I need to update, and I don't have the time to figure out how to run them.

The cases are:

```
./tests/specifications/index.html
219:        Many thanks to Marcos Cáceres for moral support, and to Bert Bos and Geoffrey Sneddon for their

./tests/specifications/ED-respec-test-20100224.html
611:        Many thanks to Marcos Cáceres for moral support, and to Bert Bos and Geoffrey Sneddon for their

./tests/specifications/snapshot-as-html_source.html
122:        Many thanks to Marcos Cáceres for moral support, and to Bert Bos and Geoffrey Sneddon for their
```

**Comment by marcoscaceres** [comment]
No problem. Will get then fixed for ya. I don’t think anything touches those files and pretty sure nothing checks the names.

**Comment by marcoscaceres** [comment]
pull request sent... will be merged soon.
