### ISSUE TITLE
core/utils joinAnd function should use ListFormat

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2096]
It would be great if core/utils's [`joinAnd()`](https://github.com/w3c/respec/blob/develop/src/core/utils.js#L382) would make use of the new [ListFormat API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat). 

What needs to change:

 1. core/utils should import `lang as docLang` from core/i18n. 
 1. `joinAnd()` should gain a third argument lang that defaults to `docLang`. 
 1. If `intl.ListFormat` is available, use it. 
 1. Otherwise, fallback to existing code. 
 1. Bonus: add support for some localization of `joinAnd()` - we should at least support Dutch, but would be nice to support some other languages.

**Comment by marcoscaceres** [comment]
@devanshbatra04, would you like to work on this one?

**Comment by saschanaz** [comment]
Looks like even Firefox Nightly does not support the API.

**Comment by marcoscaceres** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1433306 is tracking bug for Firefox. There is some code already there so we should hopefully ship it in a year or so.

**Comment by devanshbatra04** [comment]
Yes, on it.
