### ISSUE TITLE
Build command hardcodes w3c-profile

### ISSUE THREAD

**Issue by thijsbrentjens** [w3c/respec#2103]
## Important info

* URL to affected spec: n/a
* ReSpec version: Click the ReSpec pill (e.g., 24.3.x).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
Building the profile of Geonovum with the new builder tool does not use the profile of Geonovum. A document that uses this build shows a W3C document.

But what I was expecting?:
That the Geonovum profile was used. 

Optional, steps to reproduce:
 1. get Geonovum's code
 1. run : ``` npm run build:geo ```
 1. open a (local) doc with this respec build. It shows a W3C document, instead of a Geonovum doc

For Geonovum I created a fix, see https://github.com/Geonovum/respec/commit/c634f9f04980baba4501dc0dd16e232390a862f1. Could you use that (it is just one line) or do you need a separate PR?

**Comment by marcoscaceres** [comment]
A pull request would be great!

**Comment by isunitha98selvan** [comment]
I would like to send a PR for this.

**Comment by rishabh3112** [comment]
Sorry @isunitha98selvan, I didn't noticed your PR before sending mine. Have closed one I send :+1:.

**Comment by isunitha98selvan** [comment]
Cool thanks
