### ISSUE TITLE
(Minor) non-breaking space should be used for §

### ISSUE THREAD

**Issue by iherman** [w3c/respec#2109]
## Description of problem

Recently respec changed the cross-references to sections by preceding the section title with the '§' character. However, currently that character is followed by a space and the section number; instead, it should be followed by a _non breaking space_ and the section number. Otherwise, we get effects like this:

![opera snapshot_2019-02-19_172353_w3c github io](https://user-images.githubusercontent.com/520723/53030728-b4255000-346b-11e9-801a-a3baade0e207.png)

**Comment by marcoscaceres** [comment]
Indeed! Let me see if I can find some to fix this quickly.

**Comment by marcoscaceres** [comment]
It's now in the tree, so will ship it with next release (probably a couple of days).

**Comment by iherman** [comment]
thanks @marcoscaceres 

Cc: @gkellogg

**Comment by marcoscaceres** [comment]
If it's affecting publication or anything, happy to release it. Let me know.
