### ISSUE TITLE
Difficulty Installing respec dependencies.

### ISSUE THREAD

**Issue by ThobyV** [w3c/respec#2112]
* ReSpec version: 24.3.3
* Linux Fedora OS

Difficulty Installing respec dependencies.

Steps to reproduce: `npm install`

I have npm errors while trying to install respec dependencies for the first time so I can run some  tests.  Later I discovered it was due to a dependency *highlight.js*  from _package.json_ `(    "highlight.js": "github:highlightjs/highlight.js#cli" )` which breaks the installation as it is being stuck for a reason I suspect is related to the given error: 

`Command failed: /usr/bin/git checkout cli`
`error: pathspec 'cli' did not match any file(s) known to git.`

Removing this line from _package.json_ and running `npm install` installs all dependencies. But highlight is needed and i do not know how to install this dependency, Installing it independently from npm it has a  file structure which is different from what respec uses for builds/commands so I had to remove it.

Any help would be appreciated as I am so humbled to be able contributes here and I have been stuck trying different things so far.

**Comment by sidvishnoi** [comment]
Does removing just the `#cli` part help? 
If it does, just remove the `#cli` and please send us a PR for same.
`package.json` can have a dependency in the form of `"github:user/repository#branch"`. It looks like `cli` branch doesn't exist there anymore.

@marcoscaceres As we'll be installing from master branch directly, we better use a tag instead.

**Comment by marcoscaceres** [comment]
Ah yes, sorry! I landed the highlight CLI yesterday and forgot to update this.

**Comment by ThobyV** [comment]
@sidvishnoi .. Removing the `#cli` fixed the problem! I will send a fix.

**Comment by ThobyV** [comment]
@marcoscaceres yikes. 😂

**Comment by ThobyV** [comment]
Some people may also have errors with `npm install` being stuck on `loadIdealTree`.

Deleting `package-lock.json` and then running `npm install` works just fine.
