### ISSUE TITLE
Linking to sections & figures

### ISSUE THREAD

**Issue by r12a** [w3c/respec#2131]
This has become so annoying that i'm finally making time to raise an issue. Currently automatic completion of link text for links pointing to sections and figures is prompted by creating a `a` element without link text, eg. `<a href="#myfragid"></a>`. This produces no visible rendered text if the link fails, and also in Dreamweaver's design view (which i use all the time). You get something such as:

> See .

This is annoying because i can't see at a glance where it's pointing to. If the rendering fails, it's often not very noticeable, and you have to jump through some hoops to locate the appropriate bit of source text in order to know which fragid is failing.

Could we create an alternative (to allow backwards compatibility) where the souce code would look like this:

```
<a class="secref">myfragid</a>
```

This would then show the following in design view, or in failed renderings:

> See myfragid

For figure references we could use `<a class="figref">myfragid</a>`.

I use this approach for my own document templates, and it works well.  The essential logic shouldn't change much, just get the cue from the class name and the target location from the link text.

**Comment by r12a** [comment]
Also, section references have recently begun including § at the start. Is that intentional?  I wish they wouldn't.

And i'm inclined to think that the figure references have only recently begun adding a colon at the end (though maybe i'm mistaken, and they did this before).  Anyway, it doesn't look good, and may be problematic for the non-english localisations of respec.

**Comment by r12a** [comment]
I hope the above doesn't come across as too abrupt or critical.  I'm a great fan of Respec!  If we could improve this small feature that would make it even better :-)

**Comment by marcoscaceres** [comment]
> Also, section references have recently begun including § at the start. Is that intentional? I wish they wouldn't.

@r12a, a quick fix for the section markers is adding `addSectionLinks: false` to your ReSpec config.
  
We did enable them by default, as they provide a convenient way to link to sections without needed to go  to the ToC. 

> And i'm inclined to think that the figure references have only recently begun adding a colon at the end 

Not sure I follow. Could you please point me to an affected spec so I can take a look?

**Comment by r12a** [comment]
hi @marcoscaceres I like to have the section links on, that's a useful addition.  I'd just prefer not to have the § character show up in the link to a section. For an example, see https://w3c.github.io/iip/devanagari/#h_line_breaking

On closer inspection, the problem with figure references seems to be caused by a local stylesheet, so no problem there after all. Sorry for the noise. (The rule was adding a colon after .figno, and wasn't limited to doing so within the figcaption element.)

**Comment by marcoscaceres** [comment]
@r12a, I know you are not a huge fan of Lisp-like syntax, but as we were already using "[[[thing]]]" to expand citations, we've decided to just stick with that. 

Once #2309 lands, you will be able to do [[[#fragment-id]]], and that will expand out: 

 * examples
 * sections
 * figures 

If ReSpec can't find what you are trying to reference, it will show a (hopefully helpful) error.

**Comment by r12a** [comment]
Thanks Marcos!  In principle, i would have preferred markup yes, but (if i understand correctly how it works) this should still meet the basic need, and may actually be easier to type for authors.  It will also be handy to have the error message. I'll try it out once it's landed.

**Comment by r12a** [comment]
@marcoscaceres i'm not familiar with the process steps between merging the fix and landing it. Do you have an idea about how soon i'll be able to use this in a live document?  I ask because i'm make a large format-related edit to JLREQ at the moment, and it would be convenient to make this change at the same time.

**Comment by marcoscaceres** [comment]
Generally, we release within an hour or two. So this is out :)

**Comment by r12a** [comment]
Ah! I'll try it again. Thanks.

**Comment by marcoscaceres** [comment]
Make sure you are on the latest version (24.21.0):
 
![Screenshot 2019-04-30 20 06 29](https://user-images.githubusercontent.com/870154/56954962-79cee200-6b83-11e9-87fc-9aab0788b28f.png)

**Comment by r12a** [comment]
I seem to be on 24.21.0, but i can't figure out how to get the latest version. Any tips? (I tried shift-refresh).

**Comment by marcoscaceres** [comment]
@r12a, could you put up the spec somewhere? Happy to have a look.

**Comment by r12a** [comment]
Thanks @marcoscaceres.  I uploaded a version of the file with a couple of [[[#...]]] items in it.  One is under (b) at https://w3c.github.io/jlreq/temporary_bilingual_devt/#basic-principles-for-development-of-this-document

**Comment by marcoscaceres** [comment]
Thanks! having a look at what's going on...

**Comment by marcoscaceres** [comment]
Um, embarrassing... missed "_" in the relevant regex 🙀 @r12a, will fix when I get home unless someone else beats me to it!

**Comment by r12a** [comment]
Phew! Thank goodness it's not just me being stupid then :-).  Thanks for your help.  I'll stand by for news.

**Comment by marcoscaceres** [comment]
@r12a we will have to see how it plays with the its-locale-filter-list. I think it should be ok... but will need to check if we are cloning those nodes so it retains the its-locale-filter-list information.

**Comment by marcoscaceres** [comment]
Reduced test case:
```
        <h3 id="about_character_classes">
            <span its-locale-filter-list="en">About Character Classes</span>
            <span its-locale-filter-list="ja">文字クラスについて</span>
        </h3>
        <p>[[[#about_character_classes]]]</p>
```

**Comment by r12a** [comment]
Note, btw, that it doesn't work on [[[#kanji-hiragana-and-katakana]]] either. Also, fwiw, i tried to get it working on a different document, a few days ago, with the same result.

**Comment by marcoscaceres** [comment]
@r12a with the `its-locale-filter-list`, is the expectation that those `span`s be available inside the generated text? I'm guessing yes.

**Comment by r12a** [comment]
Yes, indeed.

**Comment by marcoscaceres** [comment]
Ok, right now, we are pulling the titles as plain text out of a look-up table... I'll need to do a little refactoring to make sure we clone the the nodes instead.

**Comment by r12a** [comment]
And other markup, too, such as bidi- or language-related markup, should also be preserved. (And that may include other tags than just span, such as bdi, etc.)

**Comment by marcoscaceres** [comment]
@r12a, make the changes as needed and I'll use your document to make sure it works. I'll keep you posted on progress.

**Comment by r12a** [comment]
Ok, i uploaded a few more changes for your testing.  I'm finding that if there's no _, i get `<a href="#introduction"></a>` as output (ie. no link text).  There are a few section references and a few figure references included in the conversions, near the start of the doc. (I didn't convert all yet, since there's well over 1,000 in total.)

**Comment by r12a** [comment]
hi @marcoscaceres I'm now seeing no difference between behaviour for ids with underscore than for other ids  However, respec isn't producing anything visible for these links. See for example, https://w3c.github.io/jlreq/temporary_bilingual_devt/#the-structure-of-this-document  Just wanted to make sure that you're aware.  Ignore this if you are.

**Comment by marcoscaceres** [comment]
Hi @r12a, was just about to message you to give you a brief update. So, yes, we fixed and shipped the "_" handling (what you are currently seeing), and I'm currently working on cloning the nodes in the expansions. I have it working locally, but it has caused a few regressions, so I'm currently working on fixing those. 

<img width="553" alt="Screen Shot 2019-05-02 at 11 02 34 PM" src="https://user-images.githubusercontent.com/870154/57077048-62802800-6d2e-11e9-93ed-f8d18db5b418.png">

**Comment by r12a** [comment]
Cool.  

Btw, i think it would be useful, if you agree, to add standard class names to the resulting markup when a link replaces [[[...]]].  For example, class="secref" or class="figref", etc.  The reason for that is that we may want to style the resulting links differently (esp. in certain languages).  Just a suggestion.

**Comment by marcoscaceres** [comment]
Good suggestion. We currently add 'sec-ref' for section references, so will make sure to do the same for the other types.

**Comment by r12a** [comment]
There were a couple of other things i was thinking about related to language and directionality of the source of the reference text.

These things are not really relevant to the jlreq doc we are using for testing, because the structure used to support the multilingual nature of the content creates language-specific spans inside a heading which declare language (and could declare direction) as needed.  So it applies to a more general case. It's also probably only an issue where a document contains headings, etc. in more than one language, so not likely to be an issue for most W3C specs.

I've been drafting some text, and it's still very, very drafty, but i'll send it to you in case you think we should take these things into account for respec.

**Comment by marcoscaceres** [comment]
Thanks for the additional info. 

It should be trivial to derive the `dir` and lang from tree order (based on the matched element), so will definitely add that.

**Comment by marcoscaceres** [comment]
@r12a, sent a PR that supports that does that clones the nodes and also applies dir/lang, based the document you sent me. 

It's likely that I might have overlooked something (as I'm not accustomed to looking at multilingual documents), but we can iterate on it if I've missed anything.

**Comment by r12a** [comment]
@marcoscaceres is there a way i can test this before you make it live?  (I'm not sure i'll grok everything just looking at the source code.)

**Comment by marcoscaceres** [comment]
@r12a, I'll put a build somewhere... brb.

**Comment by marcoscaceres** [comment]
Try: 
https://raw.githubusercontent.com/marcoscaceres/playground/gh-pages/respec-w3c.js

**Comment by marcoscaceres** [comment]
A few things from the document:

 * id "kanji-hiragana-and-katakana" is missing. 
 * you have:

```
      <tr id="term.illustrations">
        <td>illustrations</td>
        <td>図版</td>
        <td>zuhan</td>
        <td>A general term referring to a diagram, chart, cut, figure, picture and the like, to be used for printed materials.</td>
      </tr>
```

Which I'm unsure how to expand.

**Comment by r12a** [comment]
kanji-hiragana-and-katakana is a strange thing. https://w3c.github.io/jlreq/#kanji-hiragana-and-katakana takes you to a section, even though respec doesn't like the link. Haven't figured out why, but i also left that in to check the error msg worked.

For term.illustrations, i think i need to make that an ordinary link. (It probably should use dfn, but this is old code.)

Looking at the results myself, i'm noticing a couple of things, so far:
1. a lot more is working! :)
1. the list of links in section 1.4 is not appearing if i switch the language to Japanese (still investigating)
2. i'm not seeing lang or dir attributes, or bidi isolation of section numbers from the heading text

Still investigating....

**Comment by marcoscaceres** [comment]
Ah, with "kanji-hiragana-and-katakana", I think it's because the id is not set explicitly in the document? I think adding the id explicitly should fix that. 

> For term.illustrations, i think i need to make that an ordinary link.

I think that would be best... expanding the table row into something meaningful might be somewhat arbitrary. 

> i'm not seeing lang or dir attributes, or bidi isolation of section numbers from the heading text

About 3, I need some guidance there. Those are indeed getting all screwed up, so we probably need to localize those properly when they are actually generated.

**Comment by r12a** [comment]
> About 3, I need some guidance there. Those are indeed getting all screwed up, so we probably need to localize those properly when they are actually generated.

I'll add the content of my article draft to the test file i'm using, and see if i can glean anything useful.  It will probably take me a while, although i suspect it might be very late for you by now (and quite early for me).  So you may not hear much from me for a while, but i'll be working on it as time allows.

**Comment by r12a** [comment]
Btw, if it's easier, we can chat on IRC using the #i18n channel.

**Comment by r12a** [comment]
[discussion continued on IRC]

Here is a draft set of recommendations for modelling the markup for links to headings and figures: http://w3c.github.io/i18n-drafts/questions/qa-reference-links.html
