### ISSUE TITLE
Best practices should use .advicement class

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2133]
Best practice boxes should use the W3C’s advicement css class. We currently use out own custom style.

**Comment by isunitha98selvan** [comment]
I would like to work on this. So I would have to replace bp.css with advancement css class in best-practise.js, right? How do I go about testing it?

**Comment by isunitha98selvan** [comment]
As far as I understand this, practisedesc styling needs to be changed such that it uses advisement class. We can set this class along with the <p> tag. Can we remove bp.css and change the documentation such that we use <p class="advisement"> instead of <p class="practicedesc"> ?

**Comment by isunitha98selvan** [comment]
@marcoscaceres any other way to go about this?

**Comment by marcoscaceres** [comment]
You will need to track down where the best practice boxes are generated. It's probably here:
https://github.com/w3c/respec/blob/develop/src/core/best-practices.js

I think you want to change `ul.classList.add("practicebox");` to add "advicement" instead. And then we can delete bp.css entirely.

**Comment by marcoscaceres** [comment]
(you will need to see how the best practices get rendered, however... to make sure they look right)

**Comment by marcoscaceres** [comment]
Visually, they should look like this after you make the change:
https://w3c.github.io/tr-design/src/readme.html#advisement

**Comment by isunitha98selvan** [comment]
We want the advisement box in place of practisedesc. There is no element which refers to this in https://github.com/w3c/respec/blob/develop/src/core/best-practices.js.
<p class="practisedesc"> refers to https://github.com/w3c/respec/blob/develop/assets/bp.css directly.

**Comment by isunitha98selvan** [comment]
`ul.classList.add("advisement")` will not work practisebox is not what needs to be modified. As far as I see it, we will have to edit the wiki to change it to `<p class="advisement">` and remove the practisedesc function from bp.css

**Comment by marcoscaceres** [comment]
@isunitha98selvan, please see https://github.com/w3c/respec/pull/2153#issuecomment-473121835

It's basically what needs to be done.

**Comment by SuyashSalampuria** [comment]
@marcoscaceres @saschanaz Shall I take up the issue.
Please correct me if I have not understood the task rightly
I have to replace practicelab with advisement 
Also, giving strong to those spans so that advisement can be used

**Comment by saschanaz** [comment]
Oops, this one is fixed by #2340. Sorry for confusion!
