### ISSUE TITLE
respec-highlight style sheet should appear before the W3C TR stylesheet

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#2140]
## Important info

* URL to affected spec: https://w3c.github.io/performance-timeline/
* ReSpec version: 24.4.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

The W3C TR style sheet is no longer the last one to appear in html/head. The respec-highlight inline style sheet "github.com style" appears (race condition?) after the TR style sheet.

[[
  👎 Error code “last”.
      ⮡ cf https://www.w3.org/pubrules/doc/rules/?profile=WD#lastStylesheet
]]
https://lists.w3.org/Archives/Public/public-tr-notifications/2019Mar/0014.html

But what I was expecting?:

The W3C TR style sheet appears as the last style in html/head.

Optional, steps to reproduce:
 1. Open https://w3c.github.io/performance-timeline/
2. Go in the DOM inspector and note that there is a style element after the <link rel=stylesheet href='...W3C-ED'

Or use the spec-generator
  https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/performance-timeline/?specStatus=WD&shortName=performance-timeline

**Comment by marcoscaceres** [comment]
Will fix first thing tomorrow.

**Comment by marcoscaceres** [comment]
Closed via #2141

**Comment by marcoscaceres** [comment]
@plehegar fixed in latest published release. Hopefully all good now.
