### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by isunitha98selvan** [w3c/respec#2145]
## Description of problem
package-lock.json locks the version of the dependencies involved. It should preferably be in .gitignore

**Comment by marcoscaceres** [comment]
So, we actually want the dependency locking, as it assures everyone is on the same version of the dependencies. That makes finding bugs more manageable.

**Comment by marcoscaceres** [comment]
Closing this as wont fix. However, it was a good question, but not right for this project.
