### ISSUE TITLE
Work with w3c to serve new highlight bundle 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2163]
The W3C is currently serving the hljs bundle from gh-pages branch. However, we've now externalized that the highlighter into its own module. Ideally, the bundled should be getting served by the W3C from new repository. 

https://github.com/marcoscaceres/respec-hljs

cc @deniak

**Comment by marcoscaceres** [comment]
@deniak I think what we need to do is transfer https://github.com/marcoscaceres/respec-hljs to the w3c GitHub org. And then redo whatever magic you are doing on the W3C side to currently mirror the ReSpec builds.

**Comment by deniak** [comment]
@marcoscaceres I'm missing something here. Can you point me where W3C is serving that bundle so I can evaluate what needs to be change?
Also, since it's used in respec, I don't think it's an issue to transfer the ownership of the repo to W3C

**Comment by marcoscaceres** [comment]
Apologies I want not very clear: 

Right now, the W3C hosts for us:

https://www.w3.org/Tools/respec/respec-highlight.js

And that was originally a mirror of:
https://github.com/w3c/respec/blob/develop/js/deps/respec-highlight.js

**Comment by marcoscaceres** [comment]
Now, we would like it to mirror:

https://github.com/marcoscaceres/respec-hljs/blob/hljs/dist/respec-highlight.js

(but I'd like to transfer the "marcoscaceres/respec-hljs" repo to the W3C space in the process)

**Comment by deniak** [comment]
The repository has been transferred to w3c: https://github.com/w3c/respec-hljs
and we should now serve the latest version of the file on w3.org

**Comment by marcoscaceres** [comment]
Amazing! Thanks so much @deniak! 

Just reopening as I need to do a little cleanup now on the ReSpec side.
