### ISSUE TITLE
Autofilling an anchor not working in deeply nested algorithm? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2170]
## Important info

* URL to affected spec: https://github.com/w3c/performance-timeline/pull/115
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: In https://github.com/w3c/performance-timeline/pull/115 something is preventing the section's title from getting filled. 

But what I was expecting?:

for the section's title to appear in the `<a>`. 

Optional, steps to reproduce:
 1. See https://github.com/w3c/performance-timeline/pull/115

**Comment by Swapnilr1** [comment]
@marcoscaceres Fixed in #2172.
