### ISSUE TITLE
Definitions that abbreviate 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2174]
Given, for instance, 

```HTML
<dfn>primary account number</dfn>
```

It would be nice to able to add `data-abbr`:

```HTML
<dfn data-abbr="PAN">primary account number</dfn>
```

which would then render as:

"primary account number (PAN)"

And PAN would be added to the inline.js abbreviations map. So, then, one could just write:

```HTML
Check the PAN.
``` 

And ReSpec would automatically wrap that in `<abbr title="primary account number">PAN</abbr>`. 

What would be nice also, is for ReSpec to automatically derive the abbreviation if just given:

```HTML
<dfn data-abbr>primary account number</dfn>
``` 

(i.e., the first letter of each word is combined and upper-cased... so "PAN")

Would be equivalent to:

```HTML
<dfn data-abbr="PAN">primary account number</dfn>
```

**Comment by devanshbatra04** [comment]
On it. :-)
