### ISSUE TITLE
xref should handle singular and plural cases

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2179]
Given:

```HTML
<a data-cite="infra">code points</a>
```

xref should be checking for "code points" and "code point", where "code point" is the match in the infra spec. 

cc @sidvishnoi

**Comment by Swapnilr1** [comment]
Working on it.

**Comment by sidvishnoi** [comment]
I'm thinking if we should handle pluralization on server side. That way:
+ we won't have complicated logic at client
+ stronger search API, which can also be used in search interface
- extra data returned from server in some cases

**Comment by Swapnilr1** [comment]
@sidvishnoi That's a good idea. I don't think there would be many cases where both the singular and plural forms are present in the specifications, so extra data being returned should be a rare issue.

**Comment by sidvishnoi** [comment]
Server side implementation: https://github.com/sidvishnoi/respec-xref-route/pull/26/

**Comment by sidvishnoi** [comment]
Closed via sidvishnoi/respec-xref-route#26
