### ISSUE TITLE
variable inlines should support generic types

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2184]
For example:

```
Let |networks:sequence&lt;DOMString>| be an empty DOMString sequence.
```

**Comment by saschanaz** [comment]
Should also support spaced types e.g. `unsigned long long`.

**Comment by marcoscaceres** [comment]
Yeah, ran into that today 😁

**Comment by marcoscaceres** [comment]
I think we can basically just split on ":"... left side is variable, right side is type. Done.

**Comment by sidvishnoi** [comment]
Right side is type already. We need to update the regex. Maybe add like this?
``` diff
- \\B\\|\\w[\\s\\w]*\\w(?:\\s*\\:\\s*\\w+)?\\|\\B
+ \\B\\|\\w[\\s\\w]*\\w(?:\\s*\\:.+)?\\|\\B
```

**Comment by marcoscaceres** [comment]
But if we know everything on the right of : is type, what would we do with the regex?

**Comment by sidvishnoi** [comment]
Regex is for splitting the text in `subtxt`. We can have a simpler regex like `\B\|.+(?:\:.+)\|\B`. I'm not sure of the cases it may go "bad" - like over matching text.

**Comment by marcoscaceres** [comment]
I was thinking if we could send the type into webidl2.js, we can get back a simple AST. Then we could have some fun :)

**Comment by marcoscaceres** [comment]
@saschanaz, wdyt of the comment above? Doable?

**Comment by saschanaz** [comment]
webidl2.js is not exposing classes yet, and even if it did the classes doesn't support parsing string snippets yet. Supporting that would be absolutely great, though.

**Comment by marcoscaceres** [comment]
Ok, we should come up with a simple replica of https://github.com/w3c/webidl2.js/#idl-type

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/respec/pull/2221

**Comment by Swapnilr1** [comment]
@sidvishnoi Well I don't think #2221 fully solves this, at least as per the discussion related to getting AST from WebIDL2 module.

**Comment by saschanaz** [comment]
We can open a new issue 😀
