### ISSUE TITLE
Regression: noRecTrack text not showing 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2196]
## Important info

* URL to affected spec: https://w3c.github.io/payment-method-basic-card/
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
The noRecTrack related text is not being added. 

But what I was expecting?:
For the associated text to be there. 

Optional, steps to reproduce:
 1. Add noRecTrack: true to config

**Comment by pradeepgangwar** [comment]
I guess the issue was fixed by #2199. Is there anything left @marcoscaceres ?

**Comment by marcoscaceres** [comment]
Thanks for the reminder. No, nothing left here.
