### ISSUE TITLE
New Copydeps tool which uses GulpJS

### ISSUE THREAD

**Issue by devanshbatra04** [w3c/respec#2198]
Currently, the copydeps tools simply copies the dist versions of npm packages. This could have several disadvantages. It doesn't minify them, or remove comments. 

I propose we set up [gulp](https://gulpjs.com/) tasks instead. 

More importantly, gulp tasks would allow us to convert CommonJS and ES dependency packages to AMD (until we keep using requireJS). And avoid issues like #2191. 

It could also allow us to use packages which don't have a packaged build/dist directory and handle dependencies.

**Comment by marcoscaceres** [comment]
> It doesn't minify them, or remove comments.

We do that when we run uglify in ./tools/builder.js

> I propose we set up gulp tasks instead.

Plan is to overcome this eventually by moving to Webpack (#1975).
