### ISSUE TITLE
abbr title's whitespace needs normalization 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2210]
As we are taking the taxtContent, we need to normalize the whitespace... otherwise, this happens:  

![Screen Shot 2019-03-28 at 4 31 19 PM](https://user-images.githubusercontent.com/870154/55132599-0f3b1880-5177-11e9-88a4-599349591850.png)

**Comment by marcoscaceres** [comment]
@devanshbatra04, you want to work on this? Should be quick.

**Comment by devanshbatra04** [comment]
Yup. Sure.

**Comment by devanshbatra04** [comment]
This isn't Respec's fault. 
Here's the markdown written in the spec's source.
![Screenshot from 2019-03-28 13-18-10](https://user-images.githubusercontent.com/33961252/55139563-10128100-515c-11e9-98de-fd5bffc83015.png)

It works well if they change it to 
```html
<dfn data-abbr="PMI" data-cite=
    "payment-method-id#standardized-payment-method-identifiers">standardized payment method identifier</dfn>

(not entering a new line between the words "standardized" and "payment")

**Comment by marcoscaceres** [comment]
Like with JS, authors don't have control over line length. We run HTML tidy over the document, and tidy decides where to break things up. So, it's still ReSpec's fault as ReSpec is the one setting the title attribute :)

**Comment by devanshbatra04** [comment]
Oh Okay. Didn't know that. :sweat_smile: 
I will see to it now.

**Comment by marcoscaceres** [comment]
No problem :) All part of learning the magic of spec writing.
