### ISSUE TITLE
Auto-expanding inline references

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2211]
In ReSpec, we currently support the ability to, for example, write:

```HTML
<a data-cite="payment-request"></a>
```

That gets expanded to:

```HTML
<a href="https://...">Payment Request API</a>
```

However, `<a data-cite="payment-request"></a>` is kinda ugly... What would be nicer would be to write inline (3 square brackets):

```
[[[payment-request]]]
```

And that then gets transformed to:

```HTML
<a data-cite="payment-request"></a>
```

And ReSpec then handles the rest.

**Comment by Swapnilr1** [comment]
I would like to work on this. Need some time though.
