### ISSUE TITLE
Explore about replacing `normalizePadding()` with `reindent()`

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2212]
Turns out that a simple replacement doesn't work, so explore about why.

**Comment by saschanaz** [comment]
Looks like indentation processing is weird on `normalizePadding()`. For example:

```markdown
<section id='sotd'><p>foo</p></section><section id='toc'></section>

    # Title
    Some text
```

Per the markdown spec, the text should be interpreted as `<pre>` because of its indentation. Instead, the function tends to interpret it as normal unindented markdown by trimming the text and all its indentations.

**Comment by marcoscaceres** [comment]
Correct... so, this is for legacy reasons. People were writing markdown inside the body indented like that:(

**Comment by saschanaz** [comment]
Is there a live example? I saw this on our tests that appends indented template string.

**Comment by marcoscaceres** [comment]
I’ll dig some up.

**Comment by marcoscaceres** [comment]
https://github.com/coremob/coremob-2012/blob/gh-pages/index.html

**Comment by marcoscaceres** [comment]
Hello from 2012!

**Comment by saschanaz** [comment]
🤦‍♀️

**Comment by marcoscaceres** [comment]
Heh, yep. Kinda stuck. But we could make a case to break things for sanity’s sake.

**Comment by marcoscaceres** [comment]
@saschanaz do you think we can do anything here? Or “abandon all hope”?

**Comment by saschanaz** [comment]
@marcoscaceres I think we should learn exactly what behavior differences exist, add some tests for it, and then we can revisit this. For now it's rather a black box...

**Comment by marcoscaceres** [comment]
Closing. Markdown should be written as markdown and ReSpec shouldn’t try to correct authoring mistakes for it.
