### ISSUE TITLE
Tests: karma doesn't run tests on Firefox 66.0.0 (Linux)

### ISSUE THREAD

**Issue by thijsbrentjens** [w3c/respec#2254]
## Important info
* URL to affected spec: n/a
* ReSpec version: current develop ()
* [x] I did a "hard refresh", but it's still busted. 
* browser: Firefox 66.0.0 (Ubuntu)

## Description of problem
Running tests using:
```
npm run tests
```
Does open a browser window, but does not start to run tests. 
The console gives an exception for test-main.js:
```
SyntaxError: dynamic module import is not implemented
```

Note that tests do run with Chromium:
```
npm run karma -- --browsers Chromium
```

**Comment by Swapnilr1** [comment]
This is because Firefox 66 does not support dynamic imports by default. They can be enabled by toggling `javascript.options.dynamicImport` in `about:config`. Though right now I have to toggle this option each time I run karma tests.
Firefox 67 will probably enable it by default (as far as I know it's enabled in the Beta builds), fixing the issue.

**Comment by marcoscaceres** [comment]
@thijsbrentjens, we just added something that should help. You can now do:

```Bash
export BROWSERS=FirefoxPref
./tools/builder.js --profile=geonovum --debug
karma start
```

That will automatically enable dynamic imports, and makes sure the profile gets generated in a debuggable way.  

You can also add `export BROWSERS=FirefoxPref` to your .bashrc or .szshrc (depending on what you use).

**Comment by marcoscaceres** [comment]
Just noting, having to build the profile before testing is a temporary thing... once we have Webpack in place, that bit of pain will go away.

**Comment by saschanaz** [comment]
>Just noting, having to build the profile before testing is a temporary thing... once we have Webpack in place, that bit of pain will go away.

I don't understand, we should still run webpack before the test?

**Comment by marcoscaceres** [comment]
> I don't understand, we should still run webpack before the test?

**Comment by marcoscaceres** [comment]
> I don't understand, we should still run webpack before the test?

Sure, but with Webpack dev server running, it's constantly building in the background... so it just works TM. Right now, we have to remember to rebuild every time... which I often forget so end up spinning up Karma, having to shut it down, etc..

**Comment by marcoscaceres** [comment]
closing as answered.
