### ISSUE TITLE
Let definitions in specs be "for" particular things

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2271]
For WebIDL, we have the ability to say that the definition of `attribute X` is for `SomeInterface`. It would be nice to be able to expand this concept globally so that:

 * A definition can be for a particular thing (e.g., "sort" is for "list").
 * A internal slot is for an interface. (e.g., we can then have: [[request]] is for PaymentRequest, [[request]] is for PaymentResponse and a way to define both, but without them conflicting)

**Comment by sidvishnoi** [comment]
Closed by #2873, #2868 and some part already existed.
