### ISSUE TITLE
Definitions should include a self link

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2272]
Likke in the WebIDL spec:

https://heycam.github.io/webidl/#aborterror

It is shown on hover. 

![Screen Shot 2019-04-15 at 9 29 28 AM](https://user-images.githubusercontent.com/870154/56100852-22b0f680-5f61-11e9-8edd-7073cea5a9e4.png)

**Comment by sidvishnoi** [comment]
Closing in favor of https://github.com/w3c/respec/issues/1103
