### ISSUE TITLE
"Can I use this API" doesn't apply everywhere

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2274]
Can I use shows "Can I Use this API?" in the header. However, not all specs are APIs... So maybe we should say: 

 * Can I use this feature?

or 

 * Browser support:

Other suggestions?

**Comment by sidvishnoi** [comment]
+1 for "Browser support"

**Comment by marcoscaceres** [comment]
>  "Browser support:"
Yeah, I agree... it would fit most nicely with the other things listed.
