### ISSUE TITLE
kjhtml disables karma grep option

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2289]
`npm run karma -- --browsers ChromeHeadless --grep WebIDL` is expected to only run WebIDL tests but `kjhtml` somehow disables this. Removing `kjhtml` from `karma.conf.js` fixes the issue.

Relevant issue: https://github.com/dfederm/karma-jasmine-html-reporter/issues/23

**Comment by marcoscaceres** [comment]
I’m still unsure if this is really a ReSpec bug?

**Comment by saschanaz** [comment]
Not strictly, but I needed to note this somewhere.
