### ISSUE TITLE
var highlight overmatches

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2297]
Given: 

```HTML 
    <section>
        <p>|varA|.</p>
        <section>
          <p>|varA|</p>
        </section>
     </section>
```

The second |varA| shouldn't be highlighted, because it's in a new sub section.

**Comment by saschanaz** [comment]
Meaning they are different variables? I suspect that would be confusing for readers...

**Comment by marcoscaceres** [comment]
Yes, they are different. Indeed, it’s confusing. I’ll try to send a fix tomorrow.

**Comment by saschanaz** [comment]
To be clear, I think readers may falsely consider they are same because of the name, even after the fix. What would be the use case here?

**Comment by marcoscaceres** [comment]
Ah, no. It’s pretty clear they are not. You can take a look at Payment Request API to see that clearly. There are visual cues in each section to indicate they are self-contained: for example, heading, algorithms contain lines and indenting, etc. When the overmatching on vars happens, it’s pretty clear there is some kind of bug.

**Comment by marcoscaceres** [comment]
(Sorry for lack of images and links to clearly show the problem - on my phone. Will post some tomorrow)

**Comment by marcoscaceres** [comment]
Example: 

<img width="948" alt="Screenshot 2019-04-22 18 04 05" src="https://user-images.githubusercontent.com/870154/56490592-10b6f100-6529-11e9-8e33-4be1078aac46.png">

**Comment by saschanaz** [comment]
Ah, okay, explicit redeclaration.
