### ISSUE TITLE
clearer message for when data-cite stomps on a reference

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2310]
Given:

```
<body data-cite="WebIDL">
<ol data-cite="infra"><li>{{DOMString}}
```

The second data-cite stomps on the first data-cite... so it would be nice if the error message made it more clear why DOMString is not found (in infra). 

Alternative might be to walk up the tree, so first try infra, and then try WebIDL.

**Comment by sidvishnoi** [comment]
I think this is fixed with https://github.com/w3c/respec/pull/2434

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/respec/pull/2455 and #2434
