### ISSUE TITLE
MDN pill hard to use on mobile

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2313]
The MDN boxes are a little difficult to use on mobile. We should increase hit area to the whole box, and we should open the whole thing up by default (i.e., let's get rid of details). 

We should also improve the markup. When we shipped, we copied what the HTML Spec was doing... but the markup is less than ideal.

**Comment by Swapnilr1** [comment]
Working on it. Also found a minor rendering issue with Firefox.

![firefox](https://user-images.githubusercontent.com/35957512/57016636-c32d3900-6c38-11e9-9599-481e4a9ac6f4.png)

> We should increase hit area to the whole box
Yup - even when working on a desktop, it took me some time to figure out I am supposed to click on the 3 dots on the top left to open the MDN pill.
