### ISSUE TITLE
Allow IDL types to be self-defined

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2316]
From https://github.com/w3c/respec/issues/685#issuecomment-487366561

>... like allowing IDL things to be “self defining” (in the IDL itself) instead of requiring things to be defined separately.

**Comment by saschanaz** [comment]
@marcoscaceres What would self-defining exactly mean? To allow IDL definitions lack `<dfn>` and transform anchors to dfn if then?

**Comment by marcoscaceres** [comment]
Correct, so, for instance:

```HTML
<section data-dfn-for="Foo" data-link-for="Foo"> 
<pre class="idl">
interface Foo {
  attribute DOMString state;
  void someMethod(); 
}
</pre>
<p><dfn>someMethod()</dfn> ... bla bla <a>state<a> attribute.</p> 
</section>
```

If `state` attribute has no matching `dfn` in the document, it gets wrapped in a `<dfn>`.
