### ISSUE TITLE
Should inheritance take same path as name

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2317]
Given:

```
 interface Foo : EventTarget {};
```

Right now, the WebIDL module has `inheritance()` handler path, but EventTarget really just another interface (name). @saschanaz, should that just take the "name()" template path instead? Right now, the code doesn't complain when the super class is not linked.

**Comment by marcoscaceres** [comment]
I've been playing around with changing inheritance to:

```JS
    inheritance(contents) {
      contents.removeAttribute("data-link-for");
      contents.dataset.xrefType = "_IDL_";
      return hyperHTML`<span class="idlSuperclass">${contents}</span>`;
    },
```

**Comment by saschanaz** [comment]
`inheritance()` is just a wrapper to add `.idlSuperclass`, the real linking thing happens on `reference()`.

**Comment by saschanaz** [comment]
Maybe we want to introduce strict-linking that warns whenever unknown reference happens? Right now [any unknown references are just ignored](https://w3c.github.io/performance-timeline/#the-performanceentry-interface). (Look at `DOMHighResTimeStamp`.)

**Comment by marcoscaceres** [comment]
Yeah, agree. We want strict linking on everything... `xref: true` can then deal with the broken links, because it knows how to easily find IDL. Another bonus is that the linking table in the IDL module goes away :)

**Comment by marcoscaceres** [comment]
@saschanaz I can try to work from `reference()` and see how I go. I'll draft something up, but would appreciate your guidance.

**Comment by marcoscaceres** [comment]
Making a note that https://github.com/w3c/respec/issues/1917 is related... in as far as it adds a bunch of needless spans that could be on the elements themselves in most cases.

**Comment by marcoscaceres** [comment]
Ok, scary bit... to achieve this, we need to enable xref on all W3C specs. Are we ready? Should we just deal with the fallout? 

I have something working locally, and it’s pretty awesome: all webIDL types now link.

**Comment by saschanaz** [comment]
Maybe we can just enable the strictness for who opts-in xref thing?

**Comment by marcoscaceres** [comment]
We could, but would mean many code paths. I’d rather just move people. ReSpec’s current citation model is actually harmful to the web 😢 I’ve realized this as I’ve been increasingly using xref and migrating specs. 

Having said that, xref is backwards compatible, so I don’t think too many specs will be affected. Those affected will be ones that have bugs already (e.g., the one you linked to above).

**Comment by marcoscaceres** [comment]
(Harmful in that one can cite definitions  that are not exported from other specs... which is bad)
