### ISSUE TITLE
should maplike be passed to `reference()`?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2321]
@saschanaz, not sure this is right, but I think `maplike` should be passed to the `reference()` template handler (same way that sequence, record, and Promise are passed). I can then link "maplike" to the WebIDL spec via the template.

**Comment by marcoscaceres** [comment]
For reference, this is what I'm working on:

```JS
    reference(wrapped) {
      switch (wrapped) {
        case "maplike":
        case "sequence":
        case "record":
          return hyperHTML`<a data-xref-type="dfn">${wrapped}</a>`;
        case "Promise":
          return hyperHTML`<a data-xref-type="dfn" data-lt="Promise type">${wrapped}</a>`;
        default:
          return hyperHTML`<a data-xref-type="_IDL_">${wrapped}</a>`;
      }
    },
```

It works nicely for everything except `maplike` :) ... is there others?

**Comment by saschanaz** [comment]
Thing is that they are syntactic keywords rather than general IDL identifiers. `maplike`/`setlike`/`iterable` are not even type names. I'd like to add a new hook for those syntactic things (mainly to link anonymous getters from the keyword `getter`), but not sure what would be the best name.

`keyword()` would work but then why some keywords but not others? 🤔

**Comment by marcoscaceres** [comment]
heh, see also "Promise object" 😂😭

**Comment by marcoscaceres** [comment]
`keyword()` would be fine... it's really up to us to classify them.

**Comment by saschanaz** [comment]
Yeah... we can pass `Promise` but we cannot pass `maplike` as an argument 😁

I think `generic()` (as a syntactic form) and `modifier` might work.

**Comment by marcoscaceres** [comment]
I'm happy with whatever you think is best.

**Comment by saschanaz** [comment]
Okay, I'll go `generic()` first and `modifier()` later.

**Comment by marcoscaceres** [comment]
Ok, does this look right then?:

```JS
    generic(type){
      switch (type) {
        case "Promise":
          return hyperHTML`<a data-xref-type="dfn" data-lt="Promise type">${wrapped}</a>`;
        default:
          // sequence, record... 
          return hyperHTML`<a data-xref-type="dfn">${wrapped}</a>`;
      }
    },
    modifier(keyword) {
      // maplike, setlike, and iterable
      return hyperHTML`<a data-xref-type="dfn">${wrapped}</a>`
    },
    reference(wrapped) {
      switch (wrapped) {
        case "Promise":
          return hyperHTML`<a data-xref-type="dfn" data-lt="Promise type">${wrapped}</a>`;
        default:
          return hyperHTML`<a data-xref-type="_IDL_">${wrapped}</a>`;
      }
    },
```
```

**Comment by marcoscaceres** [comment]
oops, let me fix the above.

**Comment by saschanaz** [comment]
I'll go `generic()` for generic-like syntactic forms include `maplike`, and `modifier()` for `getter`, `stringifier` etc.
