### ISSUE TITLE
Internal References broken by last update (24.21.2)

### ISSUE THREAD

**Issue by mkovatsc** [w3c/respec#2328]
## Important info

* URL to affected spec: any Editor's Draft on github.io (e.g., https://w3c.github.io/wot-architecture/ or https://w3c.github.io/json-ld-syntax/)
* ReSpec version: 24.21.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

* Only the first internal reference with `<a href="#..."></a>` is rendered as "§ X. ..."
* All following are not rendered (no link text)

But what I was expecting?:

* All internal references rendered correctly with the section heading as link text

Optional, steps to reproduce:
1. Go to any Editor's Draft on github.io, e.g., https://w3c.github.io/wot-thing-description/#sec-td-serialization
2. Check the text for missing link texts on internal references 

Firefox says:
```
TypeError: "r is null"   --   base-runner.js:70
    s anchor-expander.js:145
    o anchor-expander.js:120
    run anchor-expander.js:41
    l base-runner.js:36
    l base-runner.js:23
    runAll base-runner.js:68
    runAll base-runner.js:70
```
Chrome says:
```
TypeError: Cannot read property 'getAttribute' of null
    at s (anchor-expander.js:147)
    at o (anchor-expander.js:120)
    at Object.e.run (anchor-expander.js:41)
    at base-runner.js:36
    at new Promise (<anonymous>)
    at base-runner.js:23
    at Object.e.runAll (base-runner.js:68)
    at async https:/www.w3.org/Tools/respec/respec-w3c-common:16
```

**Comment by marcoscaceres** [comment]
Thanks @mkovatsc... sent a fix!

**Comment by mkovatsc** [comment]
Great, thanks for the quick fix!
