### ISSUE TITLE
Default licence for unofficial drafts

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2352]
## Important info

* URL to affected spec: N/A
* ReSpec version: 24.21.7
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Currently, the default licence for unofficial drafts is CC-BY 3.0.

Shouldn't it be switched to the latest version - namey, 4.0 ?

**Comment by marcoscaceres** [comment]
Good suggestion. We should also decouple status and license.

**Comment by andrea-perego** [comment]
And maybe also the copyright holder(s).

**Comment by prondubuisi** [comment]
Hello @marcoscaceres  What is required to solve this issue, Am looking to get started contributing to this project

**Comment by pradeepgangwar** [comment]
@marcoscaceres I guess this issue has been fixed.

**Comment by marcoscaceres** [comment]
Nope, still links to 3.0 in
src/w3c/templates/headers.js:

This needs to be updated: 
const ccLicense = "https://creativecommons.org/licenses/by/3.0/";
