### ISSUE TITLE
Subtitles in SpecRef entries

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2353]
## Important info

* URL to affected spec: https://w3c.github.io/dxwg/dcat/
* ReSpec version: 24.21.7
* ~[x] I did a "hard refresh", but it's still busted.~

## Description of problem

Not sure this is the right place to ask, so my apologies in advance.

The question is whether the `subtitle` string is appended to the title in the entries pushed to SpecRef.

In the specific case above, the issue is that, if the `subtitle` string is not added to the entries pushed to SpecRef, the new version of DCAT will have the same title of the original one, which may lead to confusion. The same problem may apply to other specs.

**Comment by marcoscaceres** [comment]
@dontcallmedom and @tobie... see above... I know this came up before, but I can't recall what happens exactly with regards to subtitle?

**Comment by tobie** [comment]
Specref just pulls in the data from W3C’s RDF API. I don’t think there a subtitle concept there.

**Comment by dontcallmedom** [comment]
indeed, I don't think we capture subtitles in the TR model - adding @deniak 

if the qualification in the subtitle is important, it's probably worth considering putting it in the title itself.

**Comment by deniak** [comment]
Yes, we expect the title to be the [first `h1` only](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/title.js). If more and more specs make use of that subtitle, we should probably update the rule to take that into account.

**Comment by marcoscaceres** [comment]
Thanks everyone! Closing as answered as not specifically a ReSpec issue... feel free to continue discussing here tho if anything needs to change.

**Comment by andrea-perego** [comment]
@marcoscaceres , where should I post this issue, then? I.e., which is the relevant repo with the scripts in charge of generating the W3C entries for SpecRef?

It's a bit urgent, as we are going to publish the final PWD for DCAT, for CR transition. So, we would like to know if we need to add in the title what is now in the subtitle.

/cc @plehegar , @draggett , @dr-shorthair , @davebrowning

**Comment by tobie** [comment]
This would be with W3C webmaster, so I assume @deniak. You can always add a local bibliography for the problematic titles as a workaround.
