### ISSUE TITLE
Merge reqRef feature into core/anchor-expander?

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2361]
Currently `core/requirements` allows `<a class="reqRef" href="#id"></a>` to reference requirements, but maybe we can do this in `core/anchor-expander` without requiring `class="reqRef"`. @marcoscaceres Thoughts?

**Comment by saschanaz** [comment]
Are we using this feature BTW?

**Comment by marcoscaceres** [comment]
I've not seen that used anywhere, tbh. Didn't know it was a thing.

**Comment by SuyashSalampuria** [comment]
@marcoscaceres  @saschanaz 
It can be done surely and it will be making the code a bit lighter too. 
But without referencing the class reqRef, do we need to do the same for all the matching anchor tags(even without reqRef class)?
If I have understood the issue correctly, shall I try working on it

**Comment by SuyashSalampuria** [comment]
It will be surely a nice idea to do this in core/anchor-expander . 
Shall I try upon this issue @saschanaz

**Comment by saschanaz** [comment]
We should first make sure that specs do use this feature, or we would be working on a feature that nobody uses.

**Comment by saschanaz** [comment]
Seems the only use is in an inactive spec named CoreMob: https://github.com/coremob/coremob-2012/blob/gh-pages/index.html

**Comment by marcoscaceres** [comment]
That spec is long dead. We can remove this.

**Comment by SuyashSalampuria** [comment]
Ohkay!! I am gonna remove this spec then!!

**Comment by saschanaz** [comment]
Now I wonder anyone uses `.req` 👀

**Comment by marcoscaceres** [comment]
It's not part of base, at least:
https://github.com/w3c/tr-design/blob/gh-pages/src/base.css

**Comment by marcoscaceres** [comment]
I'm not seeing any `<p class="req">:
https://github.com/search?l=HTML&q=org%3Aw3c+%3Cp+class%3D%22req%22%3E&type=Code

**Comment by saschanaz** [comment]
I couldn't find one either. Maybe we can remove core/requirements altogether.

**Comment by marcoscaceres** [comment]
Let’s do it.

**Comment by SuyashSalampuria** [comment]
Ohkay ! I will do that small task for you commander @saschanaz

**Comment by saschanaz** [comment]
Will you modify #2653 or you prefer merging it first? Whichever is okay.

**Comment by SuyashSalampuria** [comment]
MOdifying #2653  is always better . Similar commits made at one place !!
