### ISSUE TITLE
Incorrect error report for Note-track WD

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#2362]
## Important info

* URL to affected spec: https://raw.githack.com/w3c/apa/May_2019_WD/captcha/index.html
* ReSpec version: 24.21.7

## Description of problem

Respec reports an error: "Document configured as noRecTrack, but its status ("WD") puts it on the W3C Rec Track. Status cannot be any of: FPWD, WD, FPLC, LC, CR, PR, PER, REC. More info."

But what I was expecting?: Working Draft is a [valid status for a Note-track document](https://www.w3.org/2019/Process-20190301/#Reports) still in development, so respec should not report it as an error. If there is a desire to differentiate Note WDs from Rec WDs then a new status option should be available, but I can find [none documented](https://github.com/w3c/respec/wiki/specStatus). Though I don't see the need for a separate specStatus, the WD plus noRecTrack should be sufficient information if there are any special handlings of the document type.

**Comment by marcoscaceres** [comment]
Sent a PR to allow FPWD and WD through #2366
