### ISSUE TITLE
DOMHighResTimeStamp fails to link

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2377]
## Important info

* URL to affected spec: https://w3c.github.io/performance-timeline/
* ReSpec version: 24.22.3
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 

![image](https://user-images.githubusercontent.com/3396686/58742908-45409580-8463-11e9-8776-4ff78172d7dd.png)

The type is from: https://www.w3.org/TR/hr-time-2/#dom-domhighrestimestamp

**Comment by saschanaz** [comment]
https://respec.org/xref/ gives no result for DOMHighResTimeStamp, any idea? @sidvishnoi

**Comment by marcoscaceres** [comment]
It’s not part of the dataset yet. We need to implement #685 first.

**Comment by sidvishnoi** [comment]
The terms that are available to xref can be seen here: https://respec.org/xref/meta?fields=terms (Will add them to the UI as auto-predict today)

**Comment by sidvishnoi** [comment]
https://github.com/tabatkins/bikeshed-data/blob/046a5d7638be7e629265c7a7e6720747b8810c76/data/anchors/anchors-do.data#L2110 shows it's not exported (see L2127), so it's not part of dataset.

**Comment by saschanaz** [comment]
@sidvishnoi I'm not familiar with the file, what do we expect at L2127?

**Comment by sidvishnoi** [comment]
@saschanaz L2127 denotes "export" (1 means true, empty means false) 
https://github.com/tabatkins/bikeshed/blob/0da7328/bikeshed/update/updateCrossRefs.py#L313-L328

**Comment by saschanaz** [comment]
This has been fixed. xref is great 🎉 🎉 🎉
