### ISSUE TITLE
data-cite: No matching dfn found

### ISSUE THREAD

**Issue by rjksmith** [w3c/respec#2386]
## Important info

* URL to affected spec: https://w3c.github.io/sdw/proposals/geotagging/webvmt/
* ReSpec version: 24.23.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: A page that previously gave no errors, now gives 11 Respec errors related to `data-cite` references.

But what I was expecting?: No errors

Optional, steps to reproduce:
 1. Load page in Safari or Firefox and error flag is shown

Analysis: Firefox console shows the following Javascript errors.
```
Plugin core/biblio took too long. 
Object { updateFromNetwork: l(), resolveRef: e(), run: run()
, wireReference: Getter, stringifyReference: Getter, biblio: {…}, name: "core/biblio", … }
base-runner.js:26
    i base-runner.js:26
Error: "Plugin core/biblio took too long."
    i base-runner.js:27
base-runner.js:70
Couldn't match "**svg**" to anything in the document or to any other spec. Please provide a [`data-cite`](https://github.com/w3c/respec/wiki/data--cite) attribute for it. at: [1](#respec-offender-error-no-matching-dfn-found). undefined pubsubhub.js:106
Couldn't match "**svg**" to anything in the document or to any other spec. Please provide a [`data-cite`](https://github.com/w3c/respec/wiki/data--cite) attribute for it. 
Array [ a#respec-offender-error-no-matching-dfn-found.respec-offending-element
 ]
utils.js:180
```
which correspond to `<a data-cite='SVG11'>SVG</a>`. The SVG hyperlink works and the [SVG11] entry is added to the references list, but an error is flagged by Respec. Similar errors occur for references to HTML51, ECMA-404, etc.

This may be related to #2358.

**Comment by sidvishnoi** [comment]
@marcoscaceres

Maybe we can use `/xref/meta?fields=specs` to filter on `data-cite` to show error when spec is in dataset but term isn't.
If we were to simply not show this error when the element has a `data-cite` on itself, we would be potentially missing actual bad links like:
``` html
<a data-cite="html">something not in html</a>
<!-- above will just link to [html], with no error/warning shown, which is bad -->
```

I'm not sure of cases like `<a data-cite='HTML51'>HTML</a>`.

Another way could be to disable xref on certain links (say, `data-no-xref`), but it adds load on editor.

**Comment by marcoscaceres** [comment]
@rjksmith, so... we accidentally didn't think about this case (aliasing specs) when we designed the `xref` feature 😿 To cut a long story short, we've added a `data-no-xref` attribute to overcome this problem. 

To fix  the problem, you need to  do:

```
<a data-cite='SVG11' data-no-xref="">SVG</a>
```

Alternatively, you can do (as you  already mentioned):

```
[[SVG11]]
```

Or, maybe better :

```
[[[SVG11]]]
```

Which will print "Scalable Vector Graphics (SVG) 1.1 (Second Edition)".

**Comment by rjksmith** [comment]
I've updated my offending `data-cite` references with `data-no-xref=''` as suggested and can confirm that the 11 errors have now gone, which is excellent.

Many thanks for your support.

**Comment by marcoscaceres** [comment]
Thanks @rjksmith - sorry to make you do the extra work. Glad it fixed things for you.
