### ISSUE TITLE
New data-cite errors

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2394]
## Important info

* URL to affected spec: https://w3c.github.io/json-ld-syntax/
* ReSpec version: 24.23.2
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Lately, our specs are generating errors about missing data-cite on elements which include data-cite. I described this in [this comment](https://github.com/w3c/respec/issues/2363#issuecomment-501445170) on a #2363 .

For example, the UI says 'Couldn't match "json-ld 1.1" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.', where the referenced element is `<a data-cite="JSON-LD11">JSON-LD 1.1</a>`, and JSON-LD11 is in Specref and, in fact, shows up in References.

**Comment by marcoscaceres** [comment]
Oh, argh. Can you use `[[[JSON-LD]]]` for now? That will expand the reference for you in the meantime.

**Comment by marcoscaceres** [comment]
Fixed typo above.

**Comment by gkellogg** [comment]
I'd rather not change these, as it's often the case that a `[[]]` accompanies the reference. If it's going to be fixed in the near term, I'll just wait for the dust to settle.

**Comment by marcoscaceres** [comment]
Will try to fix it soon. I’m currently away at a work thing.

**Comment by marcoscaceres** [comment]
Closed via #2409 

The solution is to use `data-no-xref=""`.
