### ISSUE TITLE
GitHub rate limits & authentication

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/respec#2397]
I'm trying to set up automated builds with the [respec2html tool](https://github.com/w3c/respec/blob/develop/tools/respec2html.js).  However, my spec has lots of issue cross-references to GitHub that need to be fetched.  I get blocked by the Github API if I run the build twice without a wait in between:

> ReSpec error: Error fetching issue #81 from GitHub. API rate limit exceeded for [IP address] (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (HTTP Status 403)

I think the "check the docs" suggestion is from GitHub, not ReSpec.  But I'm wondering if there is a way that ReSpec can upgrade to authenticated requests. They don't need to have any special permissions: the issues are publicly readable.

Now, digging around in the ReSpec code & closed issues, it looks like there are undocumented `githubuser` and `githubtoken` config options.  But I'm not sure what kind of token that is.

If that's a [Github personal access token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line), including it in my repo code would be very dangerous, equivalent to including a password with all the permissions of my account! I would need to create a new [machine user Github account](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) that only has read-only, public permissions.

Some suggestions:

- Could the ReSpec team create a default "ReSpec Builder" user (That is, a basic GitHub account with read-only, public-only permissions) that is used for authentication if the spec doesn't have a token?

- Or, could ReSpec be registered as a proper [GitHub App](https://developer.github.com/v3/guides/basics-of-authentication/) that users could add to their repo? (Falling back to the public API if the app doesn't have permission.)  I'm not sure if this is possible, though, since there would need a way for the script to access it's own secret key from the client side.

## Important info

* URL to affected spec: https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/
* ReSpec version: 24.23.2 (from npm)
* [x] I did a "hard refresh", but it's still busted. (NA)

**Comment by marcoscaceres** [comment]
Hi @AmeliaBR! So yes, it's indeed a person GitHub token. You have a few options depending on the environment where you want to generate your spec. 

On TravisCI, you can securely store the token as an environment variable, then you can do, for example:

```Bash
./respec2html.js --src http://example.com/spec.html?ghToken=$GH_TOKEN --out spec.html
```

Where "example.com" can be replaced with a localhost server if need be. Basically, you can do the same locally... just store your token as an environment variable and do the same as above using localhost... or I think just doing the following will work:

```Bash
./respec2html.js index.html?ghToken=<your token here> --out spec.html
```
 

If you need a hand getting it set up, ping me on the w3c IRC (marcosc) or we can find some time to chat.

**Comment by AmeliaBR** [comment]
Thanks @marcoscaceres. Yes, that would work.

I'm already using a GitHub token as a Travis configuration variable for the deploy step, so I can definitely use it for the build step as well.  I didn't realize that you could apply the config option on the command line instead of in the source code.

**Comment by AmeliaBR** [comment]
Ooops, no, this isn't a solution (not for my use case, anyway).  ReSpec writes config variables set in the command line to the *built* spec. Which my Travis build then committed to Github Pages, and Github's Oath token scanning (thankfully) caught it & revoked the token.

https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/3f2922fccc324b29ecd394e2753f47eb77f3d452/index.html#L546

So, so much for that plan. Any other strategies?

**Comment by marcoscaceres** [comment]
> So, so much for that plan. Any other strategies? 

Ok, let's blacklist ghToken and ghUser from being written into the document. Thanks for catching that.

**Comment by marcoscaceres** [comment]
@AmeliaBR, ok... sent a PR (#2401) to make sure the security sensitive properties get removed... note that the token property is called `"ghToken"` and not `"githubtoken"`. 

I'll release that in a little bit.

**Comment by marcoscaceres** [comment]
@AmeliaBR, PR is merged and released as v24.23.4. Want to try again?

**Comment by AmeliaBR** [comment]
> note that the token property is called "ghToken" and not "githubtoken"

You sure about that? There's nothing in the repo that references `ghToken` and `ghUser` other than the commits you just added.

Compare:
https://github.com/w3c/respec/search?q=ghToken&unscoped_q=ghToken
with:
https://github.com/w3c/respec/search?q=githubtoken&unscoped_q=githubtoken

**Comment by sidvishnoi** [comment]
> There's nothing in the repo that references ghToken and ghUser other than the commits you just added.

You're right Amelia. Missed it in review. Sent a fix (#2403). Will release by tomorrow morning.

**Comment by marcoscaceres** [comment]
Oops 🙊 sorry Amelia. Confused myself doing this in a hurry. Note that the property is case sensitive, so need an uppercase T for token.

**Comment by marcoscaceres** [comment]
Closing as I think this is now fixed. @AmeliaBR, let me know if  that's not the case for you.
