### ISSUE TITLE
recursive data-include not implemented

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/respec#2402]
## Important info

* URL to affected spec:
This  affects all specs @marcoscaceres confirmed in specprod this is a documented but missing feature

Currently the issue can be seen at
https://davidcarlisle.github.io/mathml/#full-mathml
 
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).

24.23.2

* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

data-include attributes are not processed in html that has been included via data-include (despite this being a documented feature)

See the discussion on the mailing list 
https://lists.w3.org/Archives/Public/spec-prod/2019AprJun/0009.html

What happened (e.g., it crashed)?: 
the attribute is simply copied to the output

But what I was expecting?:
recursive processing

(adding the feature would be nice, just documenting that it doesn't work would be another acceptable outcome)

**Comment by marcoscaceres** [comment]
Discussed this with @davidcarlisle and we decided to keep the current behavior (i.e., no recursive includes). I've updated the Editor's Guide so it no longer says we support recursive imports.

**Comment by OR13** [comment]
:(
