### ISSUE TITLE
Better GitHub issues support

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#241]
It would be nice if Respec integrated better with GitHub for Editor's drafts. This includes, the ability to pull in open issues, and the ability to show normative changes to the spec (via bugs that are tagged as being such changes). Such a feature could automagically generate a "Changes" section for a spec, which could then be published in snapshots on /TR/.

**Comment by tobie** [comment]
@marcoscaceres: thoughts on [respec-gh-issues](https://github.com/tobie/respec-gh-issues) and [respec-issues](https://github.com/tobie/respec-issues).

**Comment by gkellogg** [comment]
+1 on respec-gh-issues!

It does seem dependent on using <div> (tried it with <p>, and no number was generated). Also, if the element has a body, perhaps it shouldn't be overridden?

Another thought would be to create an appendix referencing all open issues.
