### ISSUE TITLE
xref: search externally first, then look for local dfn

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2429]

**Comment by saschanaz** [comment]
Why should the xref data preferred? Is current setup causing some problems?

**Comment by marcoscaceres** [comment]
I think the issue is not correctly articulated. The actual problem is that data-cite must not prevent matching local definitions.

**Comment by saschanaz** [comment]
>data-cite must not prevent matching local definitions.

You mean must prevent?

**Comment by marcoscaceres** [comment]
These must all work: 
```
      <section>
      <p><dfn>hi there</dfn></p></section>
      <section data-cite="dom html" id="test">
        <p><a id="link1">event handler</a> try either [dom] or [html]</p>
        <section data-cite="dom">
          <p data-cite="svg">
            <a id="link2">event handler</a>
            - not in [svg] -> fallback to [dom] -> fallback to [dom], [html]
              <a>hi there</a>
          </p>
          <p>
            <a id="link3" data-cite="fetch">event handler</a>
            - try and stop at [fetch] as data-cite is on self
          </p>
        </section>
      </section>
```

**Comment by marcoscaceres** [comment]
> You mean must prevent?

Nope. Must not.

**Comment by marcoscaceres** [comment]
This still means match in current document first, the fall back to data-cite.

**Comment by saschanaz** [comment]
Ah okay, understood. 

> > You mean must prevent?
> 
> Nope. Must not.

Do `<a id="link3" data-cite="fetch">event handler</a>` possibly fallback to local definitions? The issue title seems it should but I think it should not...

**Comment by marcoscaceres** [comment]
Yes, but we may warn. Specs shouldn’t stomp on each other’s definitions - that’s really bad if they do.

**Comment by sidvishnoi** [comment]
This issue was created out of confusion, so closing.
