### ISSUE TITLE
xref: Links in code should be treated as IDL

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2436]
## Important info

* URL to affected spec: https://w3c.github.io/mediacapture-output/#methods (See 5.2 in `setSinkId` method)
* ReSpec version: 24.26.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: Couldn't match "domexception" to anything in the document or to any other spec. 

But what I was expecting?:  `DOMException` is present in markup as `<a><code>DOMException</code></a>`. I think it should be treated as `_IDL_` in xref.

The request was sent as:
``` 
specs: ["webidl"] // fine
term: "domexception" // should've been DOMException
types: ["_CONCEPT_"] // should've been _IDL_
```

**Comment by marcoscaceres** [comment]
I don’t think we should support that, tbh. The correct syntax for IDL things is {{DOMException}}.
