### ISSUE TITLE
tests/xref: refactor xref tests

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2438]
There are too many xref tests, a lot of them being duplicates or redundant. A refactor would be nice.

**Comment by SuyashSalampuria** [comment]
@sidvishnoi  Shall I try on this

**Comment by ridhishjain** [comment]
@SuyashSalampuria are u working on some other issue??
if so, @sidvishnoi can I take this?

**Comment by marcoscaceres** [comment]
@ridhishjain, yes, feel free to take it.

**Comment by sidvishnoi** [comment]
Closing as discussed in https://github.com/w3c/respec/pull/2681#issuecomment-570612971
