### ISSUE TITLE
add "untilDate" to formerEditor

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2451]
There are quite a few instances of people adding "until" to indicate when an editor retired from a spec. This is currently done using the `"note:"` config option of the person object. 

We should add support for this "natively" via `untilDate` or `retiredDate`.

**Comment by fycdev** [comment]
I will like to work on this 👍

**Comment by marcoscaceres** [comment]
Awesome! Thanks @fycdev!

**Comment by fycdev** [comment]
#2468 
Work in progress PR ☝️

**Comment by sidvishnoi** [comment]
Done in https://github.com/w3c/respec/pull/2468
