### ISSUE TITLE
Support {{ Parent / "child" }} relationships for enums

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2466]
Something occurred to me when working on this regarding enums... the following could totally work too:

```
{{ EnumContainer / "some enum value" }} 
```

Which is the same as: 

```
{{EnumContainer["some enum value"]}}
```

We should support both forms. That's less Editors need to learn.

**Comment by sidvishnoi** [comment]
The regex is clashing with exception. Interesting. Can fix it, but it'll be hacky.
