### ISSUE TITLE
Built-in IDL datatypes are not linked when specStatus is "unofficial"

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#2469]
## Important info

See attached [sample.zip](https://github.com/w3c/respec/files/3488345/sample.zip)

## Description of problem

Built-in IDL datatypes are not linked when `specStatus: "unofficial"`

In the attached sample, change `specStatus: "unofficial"` to `specStatus: "ED"` and `double` becomes linked to the corresponding IDL definition.

**Comment by marcoscaceres** [comment]
@palemieux, so this is actually by design. The unofficial specs profile default all their preferences to "false", including "xref". So to enable it for unofficial documents/specs, you need to explicitly do:

```
  "xref": true,
```

However, for specs fall into the W3C profile, "xref" is automatically set to true.

**Comment by palemieux** [comment]
Great. Is this in the manual? If so, sorry I missed it. If not, perhaps add
your explanation below?

**Comment by sidvishnoi** [comment]
[Updated the docs](https://github.com/w3c/respec/wiki/specStatus) to include `xref: true` for auto-linking with `specStatus: "unofficial"`.

[`xref`](https://github.com/w3c/respec/wiki/xref) is a new feature (presently in beta phase) in ReSpec which allows us to auto-link external references (that includes built-in IDL types).  You can read more about [Auto linking external references](https://github.com/w3c/respec/wiki/Auto-linking-external-references) in wiki.

**Comment by palemieux** [comment]
Looks like the bug label can be removed. Should I close the issue?

**Comment by marcoscaceres** [comment]
Thanks for letting us know and reminding us to update the docs!
