### ISSUE TITLE
Don't default to w3.org/TR/ as canonical URL!

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/respec#2470]
## Important info

* URL to affected spec: [static snapshot](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/) or [source code](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/index.html)
* ReSpec version: 24.30.3
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened?: 

Ran my report through a link checker & discovered that ReSpec is adding a canonical URL `<link>` that points to a non-existant URL on w3.org/TR/

But what I was expecting?:

Nothing. More specifically, that you wouldn't guess a canonical URL if I don't specify it.

Optional, steps to reproduce:

 1. Not sure. But looking at [the source code](https://github.com/w3c/respec/blob/6ea387c38a4881b7cc9eae8ce1c9a7fc58126d45/src/w3c/seo.js), it seems to happen anytime you don't add a `canonicalURI` config value.
2. From that seo.js source code, it looks like it should only happen if `shortName` is in the config (which it isn't in my case), but I guess some other code is extracting the github repo name to auto-generate a short name. But even if I had proactively included a short name, that doesn't mean this is a TR report!

Recommended solution: 

Maybe, check the `specStatus` and if this _is_ a TR report (WD, CR, REC, etc.), then auto-generate a canonical URL to w3.org.

But don't do it for other types of documents!

And maybe don't even do it for TR reports, since the canonical URLs in those cases should probably be the time-stamped versions? Might want to check with the W3 webmaster.

**Comment by marcoscaceres** [comment]
Thanks @AmeliaBR, but indeed. Your suggestion for how to fix this sounds good. 

It would be great to have a W3C utility method to determine if a document is on the W3C Rec track.

**Comment by fycdev** [comment]
Hi @AmeliaBR!
This should hopefully be fixed in v24.32.2 👍
