### ISSUE TITLE
[Feature request] upgrade-insecure-requests

### ISSUE THREAD

**Issue by Malvoz** [w3c/respec#2485]
Hi ReSpec!

I'd like to propose a new configuration member allowing editors to enforce [`upgrade-insecure-requests`](https://w3c.github.io/webappsec-upgrade-insecure-requests/) using CSP's [`<meta>` element delivery method](https://w3c.github.io/webappsec-csp/#meta-element) to prevent [mixed content](https://w3c.github.io/webappsec-mixed-content/) blocking, e.g.:

```JAVASCRIPT
var respecConfig = {
  secureRequests: true // Or rather "upgradeInsecureRequests"?
};
```
would output:

```HTML
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```

where `secureRequests` could otherwise default to `false`.

Consideration:
> Authors are strongly encouraged to place `<meta>` elements as early in the document as possible, because policies in `<meta>` elements are not applied to content which precedes them. In particular, note that resources fetched or prefetched using the `Link` HTTP response header field, and resources fetched or prefetched using `<link>` and `<script>` elements which precede a meta-delivered policy will not be blocked.

Alternatively, the policy could instead be directly included as a `<meta>` element in HTML templates?

**Comment by marcoscaceres** [comment]
Should be trivial to add. Just wondering, what prompted the request?

**Comment by Malvoz** [comment]
> what prompted the request?

https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/126

**Comment by marcoscaceres** [comment]
Awesome, thanks!

A challenge might be that ReSpec runs after the DOMContentLoaded fires, which means it might be too late to for the policy to have an effect (things would have already started to load in parallel and like already got blocked). Having ReSpec include the meta tag would only have an effect after the document is exported to raw HTML. However, in such a case, there might be limited value in adding it via ReSpec, as the meta element could just be manually included at the top of the document.

**Comment by marcoscaceres** [comment]
Closing this in light of https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/129/files

It was a good suggestion.
