### ISSUE TITLE
Biblio links should have a `data-link-type="biblio"`

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2492]

**Comment by sidvishnoi** [comment]
Relevant code: https://github.com/w3c/respec/blob/d78ccf01fadee0303d7676aef3c9dad902a12db4/src/core/render-biblio.js#L158-L162

**Comment by yash-agarwal17** [comment]
Can I work on this?

**Comment by sidvishnoi** [comment]
Yep! Go for it!

**Comment by ridhishjain** [comment]
as @yash-agarwal17 removed his assignment, I'll be working on this.
