### ISSUE TITLE
Overloaded operations showing as errors

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#2495]
## Important info

* URL to affected spec: https://w3c.github.io/webrtc-pc/webrtc.html
* ReSpec version: 24.30.5
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
When trying to upgrade the WebRTC spec above (whose online version is currently tied to a static version of ReSpec 24.3.0), it triggers 5 new errors for overloaded operations defined in the spec.
> WebIDL validation error: The operation "createOffer" has already been defined for the base interface "RTCPeerConnection" either in itself or in a mixin 

But what I was expecting?:
No errors for overloaded operations.

**Comment by marcoscaceres** [comment]
@dontcallmedom, the above WebIDL error might be correct. The validator follows the WebIDL spec quite closely.

**Comment by dontcallmedom** [comment]
huh, you're absolutely right:
> Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

Not sure when that landed in WebIDL, but I guess that moves the bug back in our court - sorry for the noise then.
