### ISSUE TITLE
Duplicate ids in markup for overloaded constructors

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#2513]
## Important info

* URL to affected spec: https://w3c.github.io/mediacapture-main/getusermedia.html in https://github.com/w3c/mediacapture-main/pull/622
* ReSpec version: 24.32.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
The `MediaStream` has 3 overloaded constructors; each of these constructors get assigned the id `idl-def-mediastream-constructor` in its IDL wrapping markup, which makes the document no longer pubrules compliant.

But what I was expecting?:
A different id for each constructor.

**Comment by saschanaz** [comment]
I'm seeing `idl-def-mediastream-constructor-0`, `idl-def-mediastream-constructor-1`, and `idl-def-mediastream-constructor-2` but not `idl-def-mediastream-constructor`. Could you elaborate a bit more?

**Comment by saschanaz** [comment]
I do see something wrong, other constructors must not link to the first overload but they do.

**Comment by dontcallmedom** [comment]
I [put a `postProcess` in place to override the default behavior](https://github.com/w3c/mediacapture-main/commit/f6fb26b4a166fa3ed9b0033e4e24042a06d6dbbe)

**Comment by saschanaz** [comment]
Found that general operation overload is also broken with the same issue.
