### ISSUE TITLE
Don't link TreatNullAs= types

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2517]
For example:

```
interface mixin InnerHTML {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString innerHTML;
};
```

EmptyString is not exported from WebIDL.

**Comment by saschanaz** [comment]
I saw that `PutForwards` also links in wrong way. Maybe we should make a whitelist for linking?

**Comment by marcoscaceres** [comment]
yeah, makes sense to whitelist...
