### ISSUE TITLE
links in the registry table headers lack contrast

### ISSUE THREAD

**Issue by rdeltour** [w3c/respec#2522]
The use of links in the [registry's table header](https://www.w3.org/TR/timing-entrytypes-registry/#registry) make them very hard to read (low contrats). 

<img width="724" alt="screenshot of the header, with low contrast in a couple columns" src="https://user-images.githubusercontent.com/520889/65132888-a2754c80-da3c-11e9-9544-5c0ef739f3c7.png">

It’s probably worth fixing in the spec’s stylesheet?

**Comment by marcoscaceres** [comment]
This is now fixed, @rdeltour - but you will need to republish the document on TR.

**Comment by rdeltour** [comment]
> This is now fixed, @rdeltour - but you will need to republish the document on TR.

Thanks @marcoscaceres! 🎉
Ping @plehegar who’s that spec editor (I just happened to notice the issue at TPAC).
