### ISSUE TITLE
List of specs that are generated using Respec?

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#2523]
Is there a list somewhere of specs that are published using Respec?

**Comment by dontcallmedom** [comment]
I don't know if you're interested in W3C/Web specs, or specs in general (since respec is also used outside of the w3c ecosystem).

For W3C, I know collecting a subset of that information via [reffy](https://github.com/tidoust/reffy) would be relatively easy since we need to identify respec-based editors draft when we extract data from specs (cc @tidoust).

(I say subset because reffy doesn't crawl all W3C specs, "only" the ones with CSS and IDL)

**Comment by tidoust** [comment]
A quick glance suggests that Reffy knows about **51 specs** generated with Respec. As pointed out by @dontcallmedom, this only covers W3C specs that define some WebIDL (or CSS in theory, but all CSS specs seem to be using Bikeshed). Here is the list:

- [Accessible Rich Internet Applications (WAI-ARIA) 1.2](https://rawgit.com/w3c/aria/master/)
- [Audio Output Devices API](https://w3c.github.io/mediacapture-output/)
- [Battery Status API](https://w3c.github.io/battery/)
- [Beacon](https://w3c.github.io/beacon/)
- [ContentEditable](https://w3c.github.io/editing/contentEditable.html)
- [Cooperative Scheduling of Background Tasks](https://w3c.github.io/requestidlecallback/)
- [DOM Parsing and Serialization](https://w3c.github.io/DOM-Parsing/)
- [Encrypted Media Extensions](https://w3c.github.io/encrypted-media/)
- [Gamepad](https://w3c.github.io/gamepad/)
- [Geolocation API Specification](https://w3c.github.io/geolocation-api/)
- [HTML Media Capture](https://w3c.github.io/html-media-capture/)
- [High Resolution Time Level 2](https://w3c.github.io/hr-time/)
- [Identifiers for WebRTC's Statistics API](https://w3c.github.io/webrtc-stats/)
- [Identity for WebRTC 1.0](https://w3c.github.io/webrtc-identity/identity.html)
- [Input Device Capabilities](https://wicg.github.io/InputDeviceCapabilities/)
- [Input Events Level 2](https://w3c.github.io/input-events/)
- [Media Capture Depth Stream Extensions](https://w3c.github.io/mediacapture-depth/)
- [Media Capture and Streams](https://w3c.github.io/mediacapture-main/)
- [Media Capture from DOM Elements](https://w3c.github.io/mediacapture-fromelement/)
- [Media Playback Quality](https://w3c.github.io/media-playback-quality/)
- [Media Source Extensions™](https://w3c.github.io/media-source/)
- [MediaStreamTrack Content Hints](https://w3c.github.io/mst-content-hint/)
- [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/)
- [Network Information API](https://wicg.github.io/netinfo/)
- [Page Visibility Level 2](https://w3c.github.io/page-visibility/)
- [Payment Handler API](https://w3c.github.io/payment-handler/)
- [Payment Method: Basic Card](https://w3c.github.io/payment-method-basic-card/)
- [Payment Request API](https://w3c.github.io/payment-request/)
- [Performance Timeline Level 2](https://w3c.github.io/performance-timeline/)
- [Pointer Events](https://w3c.github.io/pointerevents/)
- [Pointer Lock 2.0](https://w3c.github.io/pointerlock/)
- [PointerEvents - Level 2 - Extensions](https://w3c.github.io/pointerevents/extension.html)
- [Preload](https://w3c.github.io/preload/)
- [Presentation API](https://w3c.github.io/presentation-api/)
- [Push API](https://w3c.github.io/push-api/)
- [Remote Playback API](https://w3c.github.io/remote-playback/)
- [Resource Timing Level 2](https://w3c.github.io/resource-timing/)
- [Screen Capture](https://w3c.github.io/mediacapture-screen-share/)
- [Selection API](https://w3c.github.io/selection-api/)
- [Server Timing](https://w3c.github.io/server-timing/)
- [The Screen Orientation API](https://w3c.github.io/screen-orientation/)
- [Touch Events - Level 2](https://w3c.github.io/touch-events/)
- [User Timing Level 3](https://w3c.github.io/user-timing/)
- [Vibration API (Second Edition)](https://w3c.github.io/vibration/)
- [Wake Lock API](https://w3c.github.io/wake-lock/)
- [Web App Manifest](https://w3c.github.io/manifest/)
- [Web MIDI API](http://webaudio.github.io/web-midi-api/)
- [Web NFC API](https://w3c.github.io/web-nfc/)
- [Web Share API - Level 1](https://w3c.github.io/web-share/)
- [WebDriver](https://w3c.github.io/webdriver/)
- [WebRTC 1.0: Real-time Communication Between Browsers](https://w3c.github.io/webrtc-pc/)

**Comment by saschanaz** [comment]
@sidvishnoi You said you previously got a list (that probably does not depend on existence of Web IDL), could you publicize it?

**Comment by sidvishnoi** [comment]
I can create a list from the respec.org server logs, but it'll only contain the specs that use either caniuse or xref (via webidl or explicit queries). It does have some non-w3c specs though.

**Comment by sidvishnoi** [comment]
I was able to grab a list of 118 documents using ReSpec. The data comes from server logs of https://respec.org (HTTP `referrer`). The list is likely to be incomplete as it only contains the specs that use WebIDL, xref (auto-linking) or caniuse and I only checked some recent logs. 
I hope I did the filtering correctly. If a more complete list is required, I can search into older logs or implement a ping service that can help us track specs.

<details>
<summary>List of documents using ReSpec</summary>
<pre>
https://adrianhopebailie.github.io/web-monetization/ 
https://darobin.github.io/breakup/specs/browser-dom/ 
https://darobin.github.io/breakup/specs/core-algorithms/ 
https://darobin.github.io/breakup/specs/html-tables/ 
https://dev.w3.org/2009/dap/file-system/file-dir-sys.html 
https://dev.w3.org/2009/dap/file-system/file-writer.html 
https://dev.w3.org/html5/html-polyglot/ 
https://dev.w3.org/html5/html-polyglot/html-polyglot.html 
https://dvcs.w3.org/hg/dap/raw-file/tip/light/CR.src.html 
https://dvcs.w3.org/hg/dap/raw-file/tip/proximity/CR.src.html 
https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-concepts/index.html 
https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-mt/index.html 
https://dvcs.w3.org/hg/webcrypto-highlevel/raw-file/tip/Overview.html 
https://dvcs.w3.org/hg/webevents/raw-file/tip/touchevents.html 
https://ericprud.github.io/XMItoRDF/doc/ddi.shex.html 
https://json-ld.org/spec/latest/json-ld-api/ 
https://json-ld.org/spec/latest/json-ld-framing/ 
https://json-ld.org/spec/latest/json-ld/ 
https://kuddai.github.io/webrtc-timing/ 
https://manifest.sysapps.org/ 
https://mathml-refresh.github.io/mathml-core/ 
https://opencreds.org/specs/source/use-cases/ 
https://opencreds.org/specs/source/webdht/ 
https://rdf.js.org/data-model-spec/ 
https://rdf.js.org/stream-spec/ 
https://usecases.responsiveimages.org/ 
https://w3c-ccg.github.io/credential-handler-api/ 
https://w3c-ccg.github.io/did-resolution/ 
https://w3c-ccg.github.io/did-spec/ 
https://w3c-dvcg.github.io/ld-proofs/ 
https://w3c.github.io/automotive/vehicle_data/vehicle_information_service.html 
https://w3c.github.io/automotive/vehicle_information_api/vehicle_information_api_specification.html 
https://w3c.github.io/battery/ 
https://w3c.github.io/beacon/ 
https://w3c.github.io/DOM-Parsing/ 
https://w3c.github.io/dxwg/ucr/ 
https://w3c.github.io/editing/execCommand.html 
https://w3c.github.io/filesystem-api/ 
https://w3c.github.io/gamepad/ 
https://w3c.github.io/gamepad/extensions.html 
https://w3c.github.io/geolocation-api/ 
https://w3c.github.io/hr-time/ 
https://w3c.github.io/html-aam/ 
https://w3c.github.io/html-aria/ 
https://w3c.github.io/html-media-capture/ 
https://w3c.github.io/input-events/ 
https://w3c.github.io/json-ld-api/ 
https://w3c.github.io/json-ld-framing/ 
https://w3c.github.io/json-ld-syntax/ 
https://w3c.github.io/manifest/ 
https://w3c.github.io/mediacapture-depth/ 
https://w3c.github.io/mediacapture-fromelement/ 
https://w3c.github.io/mediacapture-main/ 
https://w3c.github.io/mediacapture-main/getusermedia.html 
https://w3c.github.io/mediacapture-output/ 
https://w3c.github.io/mediacapture-screen-share/ 
https://w3c.github.io/mediacapture-worker/ 
https://w3c.github.io/navigation-timing/ 
https://w3c.github.io/network-error-logging/ 
https://w3c.github.io/nfc/proposals/common/nfc.html 
https://w3c.github.io/page-visibility/ 
https://w3c.github.io/payment-handler/ 
https://w3c.github.io/payment-method-basic-card/ 
https://w3c.github.io/payment-method-credit-transfer/ 
https://w3c.github.io/payment-method-pisp-credit/ 
https://w3c.github.io/payment-request/ 
https://w3c.github.io/perf-timing-primer/ 
https://w3c.github.io/performance-timeline/ 
https://w3c.github.io/pointerevents/ 
https://w3c.github.io/pointerevents/extension.html 
https://w3c.github.io/pointerlock/ 
https://w3c.github.io/preload/ 
https://w3c.github.io/presentation-api/ 
https://w3c.github.io/pub-manifest/ 
https://w3c.github.io/publ-cg/education/epub-education.html 
https://w3c.github.io/publ-cg/guides/epub-a11y-faq.html 
https://w3c.github.io/push-api/ 
https://w3c.github.io/remote-playback/ 
https://w3c.github.io/resource-timing/ 
https://w3c.github.io/screen-orientation/ 
https://w3c.github.io/selection-api/ 
https://w3c.github.io/server-timing/ 
https://w3c.github.io/touch-events/ 
https://w3c.github.io/trace-context/ 
https://w3c.github.io/user-timing/ 
https://w3c.github.io/vc-data-model/ 
https://w3c.github.io/vibration/ 
https://w3c.github.io/wake-lock/ 
https://w3c.github.io/web-nfc/ 
https://w3c.github.io/web-share/ 
https://w3c.github.io/web-share/level-2/ 
https://w3c.github.io/webcomponents/spec/custom/ 
https://w3c.github.io/webcomponents/spec/imports/ 
https://w3c.github.io/webcomponents/spec/shadow/ 
https://w3c.github.io/webdriver/ 
https://w3c.github.io/webrtc-pc/ 
https://w3c.github.io/webrtc-stats/ 
https://w3c.github.io/webrtc-svc/ 
https://w3c.github.io/wot-binding-templates/ 
https://w3c.github.io/wot-scripting-api/ 
https://w3c.github.io/wot-thing-description/ontology/jsonschema.html 
https://webaudio.github.io/web-midi-api/ 
https://wicg.github.io/badging/ 
https://wicg.github.io/directory-upload/proposal.html 
https://wicg.github.io/frame-timing/ 
https://wicg.github.io/InputDeviceCapabilities/ 
https://wicg.github.io/netinfo/ 
https://wicg.github.io/savedata/ 
https://wicg.github.io/serial/ 
https://wicg.github.io/visual-viewport/ 
https://wicg.github.io/web-share-target/ 
https://wicg.github.io/web-share-target/level-2/ 
https://www.w3.org/2012/nfc/web-api/ 
https://www.w3.org/2012/sysapps/telephony/ 
https://www.w3.org/2019/06/mediacapture-diff.html 
https://www.w3.org/2019/wot/json-schema 
https://www.w3.org/2019/wot/td 
https://www.w3.org/TR/2005/WD-swbp-skos-core-guide-20051102 
</pre>
</details>

**Comment by marcoscaceres** [comment]
@dontcallmedom oohhh... do you think we can do something about these ones:

https://dev.w3.org/2009/dap/file-system/file-dir-sys.html 
https://dev.w3.org/2009/dap/file-system/file-writer.html 
https://dev.w3.org/html5/html-polyglot/ 
https://dev.w3.org/html5/html-polyglot/html-polyglot.html 
https://dvcs.w3.org/hg/dap/raw-file/tip/light/CR.src.html 
https://dvcs.w3.org/hg/dap/raw-file/tip/proximity/CR.src.html 
https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-concepts/index.html 
https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-mt/index.html 
https://dvcs.w3.org/hg/webcrypto-highlevel/raw-file/tip/Overview.html 
https://dvcs.w3.org/hg/webevents/raw-file/tip/touchevents.html

They are probably all stale! It's not great if people are stumbling onto those from random searches.

**Comment by marcoscaceres** [comment]
Similarly with:

https://www.w3.org/2012/nfc/web-api/ 
https://www.w3.org/2012/sysapps/

We should probably make sure that things in the SysApps repo are no longer using gh-pages:
https://github.com/sysapps/

@anssiko, seems you might still have access to those repos? I can help disable them too if you add me as admin there.

**Comment by anssiko** [comment]
@dontcallmedom, we'd like to disable gh-pages for all the specs at https://github.com/sysapps/ You seem to have touched these repos most recently.

Maybe replace the ReSpec generated EDs with static HTML snapshots to not break URLs? Or is it better to gut the specs with a clear SoTD? I leave it to your judgement.

**Comment by dontcallmedom** [comment]
+1 to creating static snapshots - I'm neutral on gutting the specs. But I'm not volunteering to do the actual work (I only touched the repos because the abandonned sysapps.org domain was breaking links)

**Comment by saschanaz** [comment]
Should errors fixed before making snapshot or can we use older ReSpec there?

**Comment by marcoscaceres** [comment]
> Should errors be fixed before making snapshot or can we use older ReSpec there?

So SysApps, we want to "gut" them... which means removing the body text and saying we are no longer working on these specs.

**Comment by marcoscaceres** [comment]
@dontcallmedom I can gut them, but I'll need admin rights on the SysApps org... be quicker that way.

**Comment by marcoscaceres** [comment]
Will push up static snapshots like this: 

![Screenshot 2019-10-01 17 19 38](https://user-images.githubusercontent.com/870154/65942008-b8890100-e46f-11e9-89eb-59d1c61a3bad.png)

@dontcallmedom, is that ok?

**Comment by dontcallmedom** [comment]
@marcoscaceres can you link to the github repo somewhere visible if people want to find out more about the history of the documents?

My preference would be to leave the abstract intact, and use the SoTD to say "work has been discontinued, see github repo for historical information".

**Comment by marcoscaceres** [comment]
ok, sounds good.

**Comment by marcoscaceres** [comment]
Exhibit A https://sysapps.github.io/app-uri/

**Comment by marcoscaceres** [comment]
Ok, all the SysApps ones are done... I've also archived the repos.

**Comment by marcoscaceres** [comment]
Closing as @sideshowbarker's question was answered. We should probably spin up a spec hygiene project.
