### ISSUE TITLE
Fix alert icon styling

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/respec#2531]
https://github.com/w3c/respec/blob/092e9788b58c342da35378ec29ef26fbb002b4c7/assets/issues-notes.css#L25

Looks a bit funky, APG members will submit PR

**Comment by marcoscaceres** [comment]
@ZoeBijl yeah, totally needs some love. Appreciate any help making it look better!

**Comment by marcoscaceres** [comment]
(as an aside, we might eventually want to push this up to the W3C's base.css so we get consistent styling for warning boxes across all specs)

**Comment by saschanaz** [comment]
Seems to be fixed by #2539. Please reopen if not.
