### ISSUE TITLE
Remove w3c/linter module

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2535]
See also https://github.com/w3c/respec/pull/2534#discussion_r332840247

**Comment by ridhishjain** [comment]
@saschanaz I would like to work on this issue, can you please guide me through this?

**Comment by saschanaz** [comment]
I couldn't find any clue that we ever used w3c/linter, especially when it essentially is just a partial duplicate of w3c/defaults. I think we should just remove it, what do you think @sidvishnoi?

**Comment by sidvishnoi** [comment]
Yes. We should remove it as the linter rules are already registered in `w3c/default`
