### ISSUE TITLE
Top level IDL things should have data-dfn-for=""

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2546]
If no data-dfn-for and top level WebIDL thing (e.g, dictionary, interface, etc), we should add data-dfn-for="" to be clear it's not for anything.

**Comment by sidvishnoi** [comment]
Is this the only thing that needs to be done? :thinking: 
https://github.com/w3c/respec/blob/c4ffceaf59a78279df5538ccf6788acfd3bebe49/src/core/dfn-finder.js#L144

**Comment by marcoscaceres** [comment]
But it depends on parent... it's makes me sad that the "finder" has side effects, but whatever.

**Comment by sidvishnoi** [comment]
cc: @saschanaz

**Comment by saschanaz** [comment]
>we should add data-dfn-for="" to be clear it's not for anything.

Reasonable. I wonder whether it caused some trouble?

>it's makes me sad that the "finder" has side effects

`decorateDfn()` is in dfn-finder but has been split from "finder" functions (in other words, nothing in dfn-finder calls `decorateDfn()` anymore).

**Comment by sidvishnoi** [comment]
>  I wonder whether it caused some trouble?

Somehow, Shepherd (hence bikeshed-data, hence xref) is treating top level things like: https://respec.org/xref/?term=Performance&specs=hr-time&types=interface
Saying `Performance` is defined "for Performance" and is not top level by itself.

**Comment by saschanaz** [comment]
Oops, that's problematic indeed!

**Comment by sidvishnoi** [comment]
@saschanaz I'm not sure whether https://github.com/w3c/respec/issues/2546#issuecomment-543021791 would be enough or it'll break stuff.
