### ISSUE TITLE
Remove karma-requirejs

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2552]
karma-requirejs shouldn't be needed as no tests currently depend on it, but removing it still breaks karma and causes tests to be not loaded anymore. This needs some investigation.

**Comment by marcoscaceres** [comment]
Heh! Zombie 🧟‍♂️ RequireJS!!  🥰

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/respec/pull/2598
