### ISSUE TITLE
Migrate to rollup from webpack

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2554]
#2553 needs compiling some dependencies (specifically `marked` and `pluralize`) to es modules instead of previous copydeps so that es module system can load them. Webpack does not support emitting es modules yet (https://github.com/webpack/webpack/issues/2933), maybe we should migrate to rollup to do this.

(Currently #2553 uses forked ES module versions of those dependencies, but maintaining forks is a burden.)

**Comment by marcoscaceres** [comment]
I don't mind, so long as we get a development server and don't need to (re)compile the code test it.

**Comment by saschanaz** [comment]
Compiling dependencies would happen after `npm install` as current copydeps do, so it shouldn't make additional burden when testing 👍

**Comment by saschanaz** [comment]
Closed by #2553
