### ISSUE TITLE
Remove unused utils functions

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2557]
Currently the list is:

* calculateLeftPad
* ~~xmlEscape~~ (#2578 added a use)
* lead0
* parseSimpleDate
* parseLastModified
* isoDate - This seems simpler alternative over `ISODate.format`?

**Comment by ridhishjain** [comment]
@saschanaz by removing, u mean commenting out or deleting the code?

"src\core\utils.js"....Is this the right path to where they are to be deleted?
If it is, I am taking this issue

**Comment by SuyashSalampuria** [comment]
`function* walkTree(walker) {
  while (walker.nextNode()) {
    yield /** @type {T} */ (walker.currentNode);
  }
}
`
is also unused. 
Should this too be removed @saschanaz @marcoscaceres

**Comment by saschanaz** [comment]
Seems that #2662 fixed it.
