### ISSUE TITLE
Guidance on how to specify changing affiliations

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2561]
## Important info

* URL to affected spec: https://www.w3.org/TR/vocab-dcat-2/
* ReSpec version: Click the ReSpec pill (e.g., 24.34.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Some editors of DXWG deliverables have changed affiliation since they joined the WG.

As far as we know, this should be specified in the specs following the guidelines at https://w3c.github.io/manual-of-style/#affs . However, we were not able to find any guidance in ReSpec on how to do this, and which fields should be used.

Could you please advise?

**Comment by marcoscaceres** [comment]
@andrea-perego, you can just update the company, or, you can make use of the "note:" if you want to say that they used to work for a different company... like `"note": "Previously at BigCorp". However, it's a bit 🤷🏽‍♂️ how you do it or if you do it at all.

**Comment by marcoscaceres** [comment]
@andrea-perego here are all the possible fields for a person object:

https://github.com/w3c/respec/wiki/person

**Comment by marcoscaceres** [comment]
Closing as I think this is answered
