### ISSUE TITLE
Add support for `data-local-lt`

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2566]
Right now, we have a situation where we are exporting, for example:
```
<dfn data-lt=
        "installing|installed|installation" data-export="">install</dfn>
```

We should provide a means to exclude some terms from being exported. BikeShed uses `data-local-lt`, I believe, to achieve the same thing. Would be good if we supported the same thing.

**Comment by saschanaz** [comment]
Relevant Bikeshed doc: https://tabatkins.github.io/bikeshed/#local-lt

**Comment by marcoscaceres** [comment]
Added documentation:
https://github.com/w3c/respec/wiki/data-local-lt

@sidvishnoi, want to check it?

**Comment by sidvishnoi** [comment]
Nice. Thanks!
