### ISSUE TITLE
Support for COinS standard

### ISSUE THREAD

**Issue by wetneb** [w3c/respec#2570]
[COinS](https://en.wikipedia.org/wiki/COinS) is a standard to embed machine-readable citation data in web pages. The idea is to embed markup that is not normally rendered but which robots can easily scrape, making it easier to extract citations from a web page.

For instance, if you inspect [the Wikipedia article about COinS](https://en.wikipedia.org/wiki/COinS) (or any other article which uses citation templates), and in particular the references, you will find this markup:
```html
<cite>
... DOM for the human-readable citation …
<span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.jtitle=D-Lib&amp;rft.atitle=Generalizing+the+OpenURL+Framework+beyond+References+to+Scholarly+Works+-+The+Bison-Fut%C3%A9+Model&amp;rft.volume=7&amp;rft.issue=7%2F8&amp;rft.date=2001-07%2F2001-08&amp;rft_id=info%3Adoi%2F10.1045%2Fjuly2001-vandesompel&amp;rft.issn=1082-9873&amp;rft.aulast=Van+de+Sompel&amp;rft.aufirst=Herbert&amp;rft.au=Beit-Arie%2C+Oren&amp;rft_id=http%3A%2F%2Fwww.dlib.org%2Fdlib%2Fjuly01%2Fvandesompel%2F07vandesompel.html&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ACOinS"></span>
</cite>
```
The `title` argument encodes the bibliographic reference using a controlled vocabulary. The `class="Z3988"` is the magic keyword to announce COinS data.

It should be relatively straightforward to adapt the current rendering code to produce COinS markup. That would enable interoperability with the clients / harvesters which rely on this format.

**Comment by marcoscaceres** [comment]
> COinS is a standard to embed machine-readable citation data in web pages. The idea is to embed markup that is not normally rendered but which robots can easily scrape, making it easier to extract citations from a web page.

As with other metadata enhancements, that challenge here is trying to balance metadata/markup bloat with utility for spec authors and readers. So, generally what we'd require is to see this supported in software or search engines used by the standards community. 

So: 

>  robots can easily scrape, making it easier to extract citations from a web page.... clients / harvesters..

Which bots / clients / harvesters exactly? And how are these used by the W3C community and to what benefit? If none are currently used, who is planning to add support and how will the data widely benefit the standards community?

**Comment by wetneb** [comment]
The Wikipedia article linked above has a few examples of COinS integrations. Personally, I use Zotero's browser extension. Having COinS support in respec would enable the following workflow:
* read a spec and click on an inline reference, leading you to the reference section;
* fire up the Zotero extension which detects the COinS markup;
* it lets you import the reference in your own bibliography;
* you can then cite this reference in other contexts (LaTeX documents, LibreOffice, Wikipedia pages, …)

So the added value for individual users is to avoid having to type in the reference in your own bibliographic metadata store.

I am not sure how other integrations work. The Wikipedia article mentions ResearchGate: I suspect they are using COinS to extract citations from documents, to populate a citation graph. So as a spec author, this would allow me to make sure my specs are better integrated in that citation graph.

I think this integration would be especially useful for references to specs, which lack well-established unique identifiers that are understood throughout the scholarly communications pipelines. For references to papers with DOIs, this is probably less important, since the DOI itself is sufficient to represent a reference (as it is well integrated in most citation extraction tools).

There are other proposals to embed machine-readable citation metadata in HTML pages (again, see the Wikipedia article for that) but it seems to me that all the alternatives are not as well established as COinS.

**Comment by marcoscaceres** [comment]
I’m still worried that we are dealing with a very limited user base for this (i.e., folks who have Zotero installed). There is a non-trivial development, maintenance, and distribution cost. 

Instead of using the COins spans, I’m wondering if Zotero can be taught about our current bibliographic structure? I see that it supports data extraction already. We can then sprinkle a few more bits of data into what we currently have without needing to duplicate everything in a span using COins?

**Comment by wetneb** [comment]
I totally understand your concerns: as a ReSpec maintainer, I can imagine you are exposed to all sorts of requests from spec writers who tend to get overly excited by all sorts of standards that nobody actually uses!

I would not say that the user base is limited to Zotero users: COinS is a standard that existed long before Zotero came into existence (this is just one example I am personally using).
ResearchGate itself is used by millions of people, including academics who work on standards: most of them have probably not heard of COinS but they still rely on this infrastructure.

The original use case, as far as I am aware, is in browser extensions which let users look up references in some physical library. If you use one of these extensions and you see a book being cited in a spec, the extension lets you look up that book in your local library in one click. See for instance this LibX extension: https://libraryguides.missouri.edu/c.php?g=27944&p=172336

Concerning the maintenance costs, I would say they are pretty low: if you decide to add fields to Specref's format for instance, that is not going to break any COinS integration - your new field would just not be exposed in COinS unless you take the time to add it. It would not break existing workflows.

Concerning the overhead in DOM, it only adds one `<span />` for each citation: the metadata is then stored in its `title` element in a pretty compact way, I would say.

> Instead of using the COins spans, I’m wondering if Zotero can be taught about our current bibliographic structure?

Do you mean writing a scraper for ReSpec's citation style? This would have the following downsides:
* Scrapers are brittle and expensive to maintain - a change in ReSpec's rendering choices could break the scraper;
* Such a scraper would only provide integration in Zotero, not in all the other COinS integrations;
* Since specs can be hosted on any domain, adding a scraper in Zotero would imply running that scraper on any webpage by default, which would come at a cost to users: the scraper would run even on pages not rendered by ReSpec.

**Comment by marcoscaceres** [comment]
> I totally understand your concerns: as a ReSpec maintainer, I can imagine you are exposed to all sorts of requests from spec writers who tend to get overly excited by all sorts of standards that nobody actually uses!

It's rare - but it does happen:) That's why we like to see wide impact/benefit before we add anything. For example, for JSON-LD, there was visual evidence that Google's search results would be improved. That has demonstrable proof of the utility for editors and other users who are searching for specs. 

This still feels like we'd be serving an extremely limited audience. For specs themselves, we already include JSON-LD to describe a spec - that should at least solve for the use case for anyone wanting to ingest a spec into something like research gate.  

For citations, I'd be willing to entertain something that doesn't duplicate the data that's already in the citation itself (i.e., the COins `<span title=""></span>` is a not so amazing hack that merely duplicates the surrounding data - structuring the citation would be more palatable). 

Is there some other alternative that Zotero supports where we can avoid the `<span>` and just use proper HTML? Does it support some microformat structure or something more reasonable?

**Comment by wetneb** [comment]
> Is there some other alternative that Zotero supports where we can avoid the <span> and just use proper HTML? Does it support some microformat structure or something more reasonable?

It would be great to find such a format - I would be keen to implement it (regardless of whether it is actually supported by Zotero or not, in fact). I am not aware of any but I will ask around and report back if I find something.

I suspect asking for no duplication between the human-readable and the machine-readable formats is a relatively big ask, but who knows, maybe that exists. It would basically be a generalization of the `<cite>` element that is already be used to highlight the title of cited works: we would need equivalents for other metadata fields.

**Comment by marcoscaceres** [comment]
Appreciate you having a look. 

> I suspect asking for no duplication between the human-readable and the machine-readable formats is a relatively big ask, but who knows, maybe that exists. 

🤞 Seems like it would be a solved problem. Maybe something useful here http://microformats.org/wiki/citation ?

**Comment by wetneb** [comment]
Actually, I did not realize that the citations can already be exposed in JSON-LD (because of #2575 which prevented it from being generated). That's great! Then I guess this already exposes the citations in machine-readable form, so the need for COinS or other inline alternatives seems weaker.

**Comment by wetneb** [comment]
Closing since we can use JSON-LD's citations instead.
