### ISSUE TITLE
Is the "w3c" license supported?

### ISSUE THREAD

**Issue by wetneb** [w3c/respec#2575]
## Important info

* URL to affected spec: [w3c-license-bug.html.gz](https://github.com/w3c/respec/files/3864459/w3c-license-bug.html.gz)
* ReSpec version: 24.34.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: when setting the `license` to `"w3c"` and enabling JSON-LD generation via `doJsonLd: true`, no JSON-LD is generated.

But what I was expecting?:

JSON-LD to be generated.

## Source of the problem

Although the wiki claims that a `"w3c"` license is supported, there does not seem to be a corresponding object in `src/w3c/header.js`, so the JSON-LD code is unable to extract the corresponding license info.

Discrepancy between
https://github.com/w3c/respec/blob/25ef75e9b0c87646a871c64c700207f58e877d68/src/w3c/headers.js#L84-L92
and
https://github.com/w3c/respec/blob/25ef75e9b0c87646a871c64c700207f58e877d68/src/w3c/headers.js#L185-L207

The "w3c" license identifier is supposed to be valid according to #1604.

**Comment by marcoscaceres** [comment]
No, you are correct... it's either w3c-software or "w3c-software" or "w3c-software-doc"

**Comment by marcoscaceres** [comment]
The default license is set here:
https://github.com/w3c/respec/blob/develop/src/w3c/defaults.js#L19
