### ISSUE TITLE
Link to GitHub commits wrong

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2582]
## Important info

* URL to affected spec: https://w3c.github.io/json-ld-api/
* ReSpec version: 24.34.7.
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The auto-generated link to "Commit History" in the header ends with "/gh-pages"

**Comment by gkellogg** [comment]
There's a note in Aliasing Keywords: "Aliased keywords MUST NOT be used within a context, itself.", but it's not normative, and shouldn't use normative language.

There are a number of places in keyword definitions where we say --term-- MUST NOT be aliased, and we probably shouldn't make this statement. It's not that there's something special about a keyword (other than `@context`) that prevents it from being aliased, it's that nothing in a context definition can be aliased. The grammar and term definition sections should make this clear normatively. We should remove statements we've added about not aliasing keywords other than `@context` and clarify that keywords may be aliased in the body of a JSON-LD document exclusive of a context or term definition.

**Comment by marcoscaceres** [comment]
Confirmed... weird bug.

**Comment by sidvishnoi** [comment]
The default branch is `gh-pages`. One has to set branch to master as described in [wiki](https://github.com/w3c/respec/wiki/github).
Alternatively, if we want to link to default GitHub branch, the branch is suffix is unnecessary - so this part can be on ReSpec side also.

**Comment by marcoscaceres** [comment]
Interesting... is being able to work out what the default branch is a new ability that we have with the GH API?

**Comment by sidvishnoi** [comment]
Not sure how the API relates to this.

**Comment by sidvishnoi** [comment]
Closing as can be fixed by configuring `github.branch` option.
