### ISSUE TITLE
Treat webIDL language tag as case insensitive in Markdown

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2596]
## Important info
* URL to affected spec: https://github.com/WICG/serial/pull/75

## Description of problem

What happened (e.g., it crashed)?: 

When using three backticks, I was expecting `WebIDL` to work.. 

But what I was expecting?:

To be able to use `WebIDL` or `webIDL` or just `IDL`... or even WEBIDL. 

Optional, steps to reproduce:
 1. Set `format: "markdown"` in the config. 
 1. Make a code block:

```WebIDL
interface Foo {};
```

Tag it with `WebIDL`.

**Comment by sidvishnoi** [comment]
Relevant code: https://github.com/w3c/respec/blob/2e7e0e19035304f9816107ad45acf4f41e5fb487/src/core/markdown.js#L90-L95

**Comment by janiceshiu** [comment]
Fixed in #2611
