### ISSUE TITLE
Add support for importing a markdown file

### ISSUE THREAD

**Issue by mimoo** [w3c/respec#2600]
## Important info

Hello,

First, let me say that this project is pretty awesome!

One minor minor issue I'm running into is that my IDE is automatically formatting the html page which messes up the markdown I have in there. I think a feature to inject a markdown file into the page would be pretty cool in order to fix this!

**Comment by marcoscaceres** [comment]
Thanks for your words of support! 

It may be possible to do:

```html
<section 
  data-include="some.md"
  data-include-format="text"
  data-format="markdown">
</section> 
```

Though we could add better support via data-include-format.

**Comment by mimoo** [comment]
doesn't seem to work : o

**Comment by mimoo** [comment]
I take it back, it doesn't work if I simply open the file in the browser but works if I serve it with python!

**Comment by marcoscaceres** [comment]
Ah yes, sorry. I forgot about that!
