### ISSUE TITLE
markdown expects tabs instead of spaces for nested lists

### ISSUE THREAD

**Issue by mimoo** [w3c/respec#2603]
Using respec with markdown, it seems like nested lists don't work if they aren't using tabs.

```markdown
* this
  - is
    + a nested list :)
```

* this
  - is
    + a nested list :)

**Comment by marcoscaceres** [comment]
Yeah, that's odd... we might need to look into that.

**Comment by marcoscaceres** [comment]
@mimoo, can you provide us with the exact markdown you are using?

**Comment by mimoo** [comment]
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <title>nopeBFT Specification</title>
  <script src='https://www.w3.org/Tools/respec/respec-w3c-common' class='remove'></script>
  <script class='remove'>
    var respecConfig = {
      specStatus: "base",
      editors: [{
        name: "nope",
        url: "https://www.nope.com",
      }],
      github: "https://github.com/nope/nope",
      shortName: "nope",
      format: "markdown",
    };
  </script>
</head>

<body>
  <section id="abstract">
      Things
  </section>

* Things
  * thing2
    * thing3

another:

* Things
  - Things
    + things

</body>

</html>
```

**Comment by mimoo** [comment]
maybe the problem comes from this function removing the padding: https://github.com/w3c/respec/blob/develop/src/core/markdown.js#L148

**Comment by mimoo** [comment]
indeed, converting all spaces with tabs fix the issue. In the mean time this script might be useful to people encountering the same issue:

```py
import sys
f = open(sys.argv[1])
toWrite = ""
for line in f.readlines():
    # two spaces -> four spaces
    number_space = len(line) - len(line.lstrip(" "))
    line = "\t" * (number_space//2) + line[number_space:]
print(toWrite)
```

**Comment by saschanaz** [comment]
>Here's an example:

The indentation is wrong there. It starts with 2-space indented section and then zero-indented markdown. Adding indentation fixes the issue.

**Comment by mimoo** [comment]
this is what the [doc](https://github.com/w3c/respec/wiki/format) says:

> ReSpec will do its best to correctly format the markdown. Please remember that markdown is supposed to be placed flush against the left margin - but we do support padded sections.

**Comment by saschanaz** [comment]
Yes... so this is where it starts to be confusing:

> ReSpec will do its best to correctly format the markdown.

This part is a total mess and no one understands what it really does. We should ultimately remove this, please don't depend on it. Sorry 🙇‍♀️

> Please remember that markdown is supposed to be placed flush against the left margin - but we do support padded sections.

The "support for padded markdown" infers the base indentation from the very first line of markdown - which is `<section>` in your example (as markdown includes some HTML support). It then tries its best to remove the base indentation everywhere, which is why the list goes wrong.

So the answer is: If you indent something, please indent everything.

**Comment by marcoscaceres** [comment]
Agree... if you use markdown, please treat the whole document as markdown. Mixing and matching is on per section will confuse the markdown parser... most of the time, we literally just take the `body` element's content and give it to marked.js, and just print whatever comes out. We can't really do any special handling apart from that.

**Comment by marcoscaceres** [comment]
closing as "won't fix" given the above discussion.
