### ISSUE TITLE
GitHub issue label is breaks into lines

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2606]
* URL to affected spec: https://w3c.github.io/json-ld-api/#h-issue-4
* ReSpec version: 24.35.2

![image](https://user-images.githubusercontent.com/8426945/70144925-f222f600-16c4-11ea-8948-2fcb8c24ddb8.png)
^^ The issue label "defer-future-version" is broken into multiple lines.

Relevant file: [assets/issues-notes.css](https://github.com/w3c/respec/blob/d78ccf01fadee0303d7676aef3c9dad902a12db4/assets/issues-notes.css)

**Comment by ridhishjain** [comment]
@sidvishnoi Can I work on this task?

**Comment by marcoscaceres** [comment]
Go for it @ridhishjain.

**Comment by sidvishnoi** [comment]
@ridhishjain This issue occurs at a specific combination of issue title length and its label's length. 
Have a look at the [Developers Guide](https://github.com/w3c/respec/wiki/Developers-Guide) to get things set up locally. 

To reproduce this issue locally, you can change `examples/basic.html` to add:
``` html
    <section>
      <h2>test</h2>
      <p class="issue" data-number="94">Expansion concept "key's term definition" is unclear with compact IRI keys.</p>
    </section>
```

and change `respecConfig.github` to `"w3c/json-ld-api"`

Or you can play with the CSS using browser's developer tools at https://w3c.github.io/json-ld-api/#h-issue-4

**Comment by yash-agarwal17** [comment]
@sidvishnoi I have worked on this issue and want to contribute. If I am allowed to make a PR, i wanted to ask if we only have to reproduce this issue in basic.html and solve the error?

**Comment by sidvishnoi** [comment]
@yash-agarwal17 I think @ridhishjain has already started working on this. 
You can look into other issues marked as [good first issues](https://github.com/w3c/respec/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
https://github.com/w3c/respec/issues/2084 and https://github.com/w3c/respec/issues/2492 are good to get you started.

**Comment by sidvishnoi** [comment]
Fixed in https://github.com/w3c/respec/pull/2617
