### ISSUE TITLE
Indentation is messed up in markdown code blocks

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2609]
ReSpec version: 24.35.2

![image](https://user-images.githubusercontent.com/8426945/70219006-1a186500-176a-11ea-8bea-d4b72ebd32d3.png)
![image](https://user-images.githubusercontent.com/8426945/70219057-2bfa0800-176a-11ea-8422-43df01e4590f.png)

`normalizePadding` is causing troubles here.

**Comment by saschanaz** [comment]
... and `normalizePadding` is completely a mess... 🤦‍♀️

I once suggested replacing it with core/reindent and it turns out there are legacy specs that depend on the current weird untested indentation behavior 😣

**Comment by marcoscaceres** [comment]
Yeah, normalizePadding() is just awful 🤢. We could easily fix the specs, I think. There are probably maybe 10-20 or so markdown specs and use the newer function.

**Comment by mimoo** [comment]
related to https://github.com/w3c/respec/issues/2603 it seems : )

**Comment by SuyashSalampuria** [comment]
@marcoscaceres  @saschanaz 
Shall I go on with this.
Shall I write a new function similar to normalizePadding or modify it

**Comment by saschanaz** [comment]
Ah, I already have a local branch to fix this, sorry 😅

**Comment by SuyashSalampuria** [comment]
NP!!

**Comment by marcoscaceres** [comment]
Reopening... we will need to fix the specs depending on the bad behavior first.

**Comment by marcoscaceres** [comment]
Closing, as we never got any complaints… so assuming those specs fixed themselves.
