### ISSUE TITLE
Allow overriding copyright

### ISSUE THREAD

**Issue by darobin** [w3c/respec#263]
We currently have additionalCopyrightHolders for that, but 1) it's a horrible name (due to the fact that we're reusing an option designed for something else), and 2) if people switch the specStatus they might forget to remove it, in which case it will have bad side-effects.

We need a "copyright" setting that only applies to unofficial drafts.

**Comment by marcoscaceres** [comment]
A better option would be to just allow people to directly write one:

```
<p class="copyright">
   ... © Whatever markup...
</p>
```

And make sure that gets relocated into the head.
