### ISSUE TITLE
Remove conf.bugTracker support

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2632]
It seems there is no test that uses `conf.bugTracker`.

@marcoscaceres Do we use this feature? AFAIK all modern specs should use GitHub issue tracker, should we drop this?

**Comment by marcoscaceres** [comment]
You are right. I think that’s obsolete with github member. Let’s remove it. I don’t even think it’s documented.

**Comment by saschanaz** [comment]
@SuyashSalampuria Hey, wanna try working on this too? 😎

**Comment by SuyashSalampuria** [comment]
Yes sure, @saschanaz  I was researching on how to tests for rconf.bugTracker support.
The task has become much simpler now
I think I will make the PR within a day for this
