### ISSUE TITLE
require('os').tmpdir() has been depriciated and should be replaced by another package

### ISSUE THREAD

**Issue by SuyashSalampuria** [w3c/respec#2673]
* URL to affected spec: https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js

The use of this npm package has been depreciated . It should be replaced by another package

**Comment by marcoscaceres** [comment]
I'm not sure this is correct? The "os" package is part of node and I don't think it's been deprecated:  
https://nodejs.org/api/os.html#os_os_tmpdir

Where did you see this message?

**Comment by marcoscaceres** [comment]
Closing as invalid, but can reopen once we hear back from @SuyashSalampuria.

**Comment by SuyashSalampuria** [comment]
I was just having a read of this page 
https://www.npmjs.com/package/os-tmpdir
And it asks us require('os-tmpdir')() gives a more consistent behaviour
If it is not affecting our specs, no issues @marcoscaceres
