### ISSUE TITLE
Exported definitions should be marked

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2686]
In `ui/dfn-list` (Definitions), exported definitions should be marked differently than non-exported definitions. The UI for marking is for discussion.

**Comment by ridhishjain** [comment]
@sidvishnoi, as this is UI related, can u tell me how to reproduce the behavior...or where to look for different UIs of exported and non-exported definitions?

**Comment by sidvishnoi** [comment]
src/`ui/dfn-list`.js, as mentioned in description. This shows up as ReSpec menu button -> Definitions.

**Comment by ridhishjain** [comment]
What I understood is that we need to change the UI of the definitions (links) appearing in the popup box. And corresponding to that, we may need to change assets/ui.css


![Screenshot (65)](https://user-images.githubusercontent.com/45514905/71771702-bdc18480-2f65-11ea-8fbc-b8bdb14781f7.png)

**Comment by sidvishnoi** [comment]
That's correct @ridhishjain But changes would go in `respec.css` (`.respec-dfn-list`).
More importantly, we need to decide first how we want exported/non-exported dfn to look like
