### ISSUE TITLE
indentation in codeblocks still doesn't work with markdown

### ISSUE THREAD

**Issue by mimoo** [w3c/respec#2700]
I've had many issues trying to make markdown work. 

* using triple backticks for codeblocks with markdown, indentation is broken (everything is flushed to the left)
* after converting codeblocks to `<pre class="rust"></pre>`, codeblock does not work anymore because I use `data-include` to include my code within the html file:

```
<section 
data-include="consensus_fixed.md"
data-include-format="text"
data-format="markdown">
</section> 
```

* inlining my markdown within the file, and with `<pre class="rust">`,  indentation only works for the first tab, not for others.

**Comment by saschanaz** [comment]
We had fixed it but found that there are some breakage in existing specs. We'll revisit it soon.

**Comment by mimoo** [comment]
any proposed approach that would work for the moment? Should I just give up on indentation until this is fixed? Or should I just switch my specification to full HTML instead of markdown?

**Comment by saschanaz** [comment]
You can try v25.0.0 which includes my proposed fix that got reverted later.
