### ISSUE TITLE
Improve styling of anchor tags on focussing upon them

### ISSUE THREAD

**Issue by SuyashSalampuria** [w3c/respec#2713]
* URL to affected spec: https://github.com/w3c/respec/blob/develop/src/ui/save-html.js

When the anchor tags namely-HTML, XML, EPUB3 are in focus, they are not clear.
We need better styling . 
(They open on clicking export after respec pill)

**Comment by ridhishjain** [comment]
I'll be working on this

**Comment by SuyashSalampuria** [comment]
Sure @ridhishjain 
![Screenshot from 2020-01-15 17-57-17](https://user-images.githubusercontent.com/44131389/72433962-83a37e80-37c0-11ea-8edd-5e475417d6f3.png)

First click Respec button and then then export, focus on buttons using TAB spaces. You will see that close button is in focus initially!!
