### ISSUE TITLE
Respec thinks that PR numbers are definitions

### ISSUE THREAD

**Issue by janiceshiu** [w3c/respec#2731]
## Important info

* URL to affected spec: [Example spec](https://w3c.github.io/navigation-timing/?isPreview=true&prNumber=23)
* ReSpec version: 25.1.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
**What happened?:** Unexpected error in respec pill.
**But what I was expecting?:** No errors.

### Steps to reproduce:
 1. Add `?isPreview=true&prNumber=23` to a spec. For example, `https://w3c.github.io/navigation-timing/` becomes https://w3c.github.io/navigation-timing/?isPreview=true&prNumber=23. Alternatively, add `{isPreview=true, prNumber: 23}` to a spec's config in local
2. Visit the link
3. The title should say something like `Preview of PR #23: Navigation Timing Level 2`
4. There is one red error in the respec pill.
```Couldn't match "#23" to anything in the document or in any other document cited in this specification: dom, fetch, hr-time-2, html, infra, performance-timeline-2, resource-timing-2, service-workers, url, webidl. See how to cite to resolve the error at: 1.```
5. This is because Respec seems to think that `#23` is a reference to some definition and tries to resolve it.
6. Ideally #23 should link to the PR itself. Regardless, even if it doesn't link to anything, `#23` it shouldn't be flagged as a citation error.

Thanks for confirming that this is a bug and not expected behaviour, @sidvishnoi!

**Comment by sidvishnoi** [comment]
@janiceshiu `prUrl` is required along with `?isPreview=true&prNumber=23`. How did you reach the above config without getting `prUrl`?

**Comment by janiceshiu** [comment]
https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L269-L271

**Comment by sidvishnoi** [comment]
This part to be precise:
https://github.com/w3c/respec/blob/b3922e7c1ee774dd0de61430c61d609fa2dc543d/src/w3c/templates/headers.js#L101-L104
