### ISSUE TITLE
WebIDL breaks with attribute named "object"

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2767]
## Important info

* URL to affected spec: https://w3c.github.io/json-ld-api/
* ReSpec version: 25.3.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The WebIDL block for [RdfTriple](https://w3c.github.io/json-ld-api/#dfn-rdftriple) does not render properly. Changing "object" to "obj" (as is done in w3c/json-ld-api#384) makes it work, but clearly ReSpec shouldn't have such a sensitivity

What happened (e.g., it crashed)?: It shows a Syntax error in the bug "Syntax error at line 6 in 6, since `interface RdfTriple`". This goes away when the name is changed to "obj", or anything else.

(There are other errors related to `JsonLdInput input`, which are because `JsonLdInput` includes a dictionary in its definition, that the parser doesn't like; annoying, but not a show-stopper.)

(There is also an unexplained "Error when calling function", which I can't figure out from the developer console, but doesn't seem to be related.)

But what I was expecting?:

Properly formatted WebIDL.

Optional, steps to reproduce:
 1. ...

**Comment by sidvishnoi** [comment]
> Changing "object" to "obj" makes it work

If I understand correctly, we can't have an identifier as one of [DistinguishableType](https://heycam.github.io/webidl/#prod-DistinguishableType), so identifiers like `object`, `boolean` would be invalid. Though we can escape them (`_object` will work). @saschanaz can tell more on WebIDL.

> There is also an unexplained "Error when calling function"

It is coming from [common.js#L131](https://github.com/w3c/json-ld-api/blob/8099234347af489b1ca7a82ec87014877fff47d2/common/common.js#L131), as `respecConfig.definitionList` doesn't exist. It was an undocumented internal thing, which was removed more than a year ago (#1968). If you can explain what `common.js` does and why, I may be able to help you fix/migrate it to use ReSpec's API.

**Comment by saschanaz** [comment]
>so identifiers like object, boolean would be invalid.

Updated Web IDL spec explicitly allows them, so this is a bug on webidl2.js side.

**Comment by saschanaz** [comment]
Oops, actually no. `object` is a special keyword and [the allowed argument keyword list](https://heycam.github.io/webidl/#prod-ArgumentNameKeyword) does not include `object`. You can open a bug there side if this sounds like a problem.

**Comment by gkellogg** [comment]
> the allowed attribute keyword list

I've got to say, the seemingly arbitrary restrictions that get added make managing specs pretty challenging. In this case, we use _subject_, _predicate_, and _object_ rather pervasively, as they are core RDF concepts. To all of a sudden have one of these core principles become unavailable is frustrating. It would be useful if you could establish some form of configuration parameter that allowed such things to be overcome. It's quite late in the game for us to rename such important concepts.

**Comment by gkellogg** [comment]
> It is coming from [common.js#L131](https://github.com/w3c/json-ld-api/blob/8099234347af489b1ca7a82ec87014877fff47d2/common/common.js#L131), as `respecConfig.definitionList` doesn't exist. It was an undocumented internal thing, which was removed more than a year ago (#1968).

Does this mean I can make the errors go away by defining `definitionList`? What would go in there?

> If you can explain what `common.js` does and why, I may be able to help you fix/migrate it to use ReSpec's API.

`common.js` does a number of things, but the one that binds it to jQuery is the use in managing shared definitions. When last I checked, the issue was having an effective replacement for `makeID`, which was defined on an element. At some point, it would be good to remove jQuery stuff, as managing common definitions across companion specs is something that we'll probably need to do in the future.

**Comment by saschanaz** [comment]
@gkellogg I can file an issue to the IDL spec to explicitly allow `object` (so far the spec authors appreciate such suggestion), do you want me to do so?

**Comment by gkellogg** [comment]
Thanks, that would be great. But, please consider a respecConfig field that can override these restrictions.

**Comment by marcoscaceres** [comment]
I'm not sure we want to deviate from standard WebIDL, as restrictions in WebIDL are usually in place for very good reasons (e.g., deviating might be web incompatible, or conflict with the underlying ECMAScript concepts on which WebIDL depends on). Also, please remember what I said previously about using WebIDL for an untended purpose: it's not well-suited for data models - only for web exposed APIs - so your milage may vary when using it for modeling RDF-related things.

**Comment by gkellogg** [comment]
This strikes me as something to TAG may need to take up sometime, as JSON-LD _is_ used in the browser, and is an emerging best practice for data within web pages as well as with Web Workers, and [the TAG has considered its use before](https://github.com/w3ctag/design-reviews/issues/312#issuecomment-434689623). Aside from carving out namespaces for things like "object", the restriction for dictionary-like arguments seems arbitrarily limiting, although may have some good reasoning behind it.

**Comment by saschanaz** [comment]
Will open an issue to ping IDL people later today to allow this 👍

**Comment by bzbarsky** [comment]
> It's quite late in the game for us to rename such important concepts.

Why do you need to rename anything?  If the IDL has `_object` as the name of the attribute, that serves as an escape to indicate "I mean the identifier with the string `object`, not the keyword `object`".  That is, if you use `_object` the actual JS reflection will have a property named `"object"`, which is what you want.

**Comment by sidvishnoi** [comment]
If https://github.com/heycam/webidl/issues/845 is supported, it will eventually be fixed in w3c/webidl2.js. Until then, `_object` remains the way to declare identifier.
