### ISSUE TITLE
Conformance section with customized title and content?

### ISSUE THREAD

**Issue by xfq** [w3c/respec#2768]
## Important info

* URL to affected spec: https://w3c.github.io/miniapp/specs/uri/#conformance
* ReSpec version: 25.3.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Is it possible to add a section with `id="conformance"` but change the section title and the boilerplate?

**Comment by sidvishnoi** [comment]
Yes. You can use the [`override`](https://github.com/w3c/respec/wiki/override) class

``` html
<section id="conformance" class="override">
  <h2>custom title</h2>
  <p>body</p>
</section>
```

**Comment by xfq** [comment]
I see. Thank you!
