### ISSUE TITLE
Replace Greenkeeper with Snyk

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#2784]
From #2781:

> ☝️ **Important announcement:** Greenkeeper will be saying goodbye 👋 and passing the torch to Snyk on June 3rd, 2020! [Find out how to migrate to Snyk and more at greenkeeper.io](https://greenkeeper.io)

**Comment by sidvishnoi** [comment]
Hi @siusin!
Can you disable the Greenkeeper integration in ReSpec?

**Comment by siusin** [comment]
done! @sidvishnoi

**Comment by sidvishnoi** [comment]
Thanks @siusin!
Thank you for your contribution on open collective also!

**Comment by siusin** [comment]
You're welcome. Thanks for all you have done for the projects!

**Comment by marcoscaceres** [comment]
Now using dependabot.
