### ISSUE TITLE
otherLinks without href don't render

### ISSUE THREAD

**Issue by tguild** [w3c/respec#2789]
It seems the behavior of otherLinks has changed, at least between when Time-OWL was last published and now

https://www.w3.org/TR/2017/REC-owl-time-20171019/

The editors chose to use otherLinks as advertised

https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#extra-links-at-top-of-the-document

[[There are times when you might need extra links or other important information to appear together with other links at the top of the document.]]

If a href is not provided, key but not value is generated, see for example Contributors.

https://w3c.github.io/sdw/time/

The more detailed otherLinks documentation does not list href as optional nor elaborate on how 'other important information' (without a link) is handled.

https://github.com/w3c/respec/wiki/otherLinks

If other specs consistently have a href for otherLinks then the main page of the Editors guide could be updated and remove the phrase 'or other important information' to change expectations. 

For now I'll manually edit the Time-OWL spec before publishing, and going forward could move contributors to acknowledgement section and find a better way to handle the OGC document number reference (or get a link for it).

**Comment by sidvishnoi** [comment]
Regression from https://github.com/w3c/respec/pull/1514.

**Comment by sidvishnoi** [comment]
Thanks for reporting @tguild!
Updated the wiki to reflect that `href` is optional.

**Comment by tguild** [comment]
Thanks @sidvishnoi
