### ISSUE TITLE
Conceptual for should be treated as case insensitive

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2792]
For example:

[=list/For each=]

And
[=List/For each=]

should both link.

Right now, [=List/For each=] is not found.

**Comment by sidvishnoi** [comment]
Found a case where we can't simply just lowercase the forContext: [`[= AbortSignal/add =]`](https://respec.org/xref/?term=add&types=_CONCEPT_&for=AbortSignal) - add is a concept here, not a method. 
But on xref server, we can try the lowercase forContext if the original one is not found.
