### ISSUE TITLE
Add Web Monatization to ReSpec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2806]
It would be nice if ReSpec could be monetized in a number of ways:
 
 1. add Web Monetization support. 
 1. add a direct link to our open collective in the ReSpec pill.
 1. add "buy us a coffee" https://www.buymeacoffee.com support, as a little button. 

For 1, we should default to out own Wallet - but allow others to configure their own wallet if they want - so individual specs can be monetized if people want.

**Comment by marcoscaceres** [comment]
Fixed via #2966

**Comment by sidvishnoi** [comment]
We're still missing (2) and (3) above though..

**Comment by marcoscaceres** [comment]
That’s ok. Those are not particularly effective ways to get funding.
