### ISSUE TITLE
(feature request) a configuration to add updated date to title page publication date

### ISSUE THREAD

**Issue by himorin** [w3c/respec#2828]
## Important info

* URL to affected spec: https://www.w3.org/TR/2018/REC-ttml-imsc1.1-20181108/
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Timed-Text WG is planning to update IMSC recommendations in-place following [republishing procedure](https://www.w3.org/2003/01/republishing/).
This requires to modify date as: 

> W3C Recommendation 5 February 2004 (updated 1 August 2017) 

or pubrules recommends:

> <h2>W3C Recommendation 7 April 2004, edited in place 19 August2004</h2>

In current HEAD, [code for headers](https://github.com/w3c/respec/blob/develop/src/w3c/templates/headers.js#L115) just put formatted date as 'W3C spec-status formatted-date', and no room to add something like above.
If respec can have a new configuration to enable this, it helps us a lot.

**Comment by sidvishnoi** [comment]
@himorin Released #2834 and now available in ReSpec 25.6.0.
Preview: https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html?modificationDate=2020-04-13
Wiki: https://github.com/w3c/respec/wiki/modificationDate

**Comment by nigelmegitt** [comment]
Thanks for the quick turnaround on this @sidvishnoi
