### ISSUE TITLE
FPWD-NOTE vs FPWG-NOTE

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#2852]
## Important info

* URL to affected spec: https://github.com/w3c/json-ld-streaming
* ReSpec version: 25.6.3
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
ReSpec documents various [`specStatus`](https://github.com/w3c/respec/wiki/specStatus) configuration values, including `FPWD-NOTE`. However, the [PubRules](https://www.w3.org/pubrules/doc) document defines `FPWG-NOTE` (note "G" not "D" in "FPWG").

What happened (e.g., it crashed)?: 

This becomes an issue when creating a snapshot such as [this](https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/json-ld-streaming/pubrules/index.html?specStatus=FPWD-NOTE&shortName=json-ld11-streaming) to run against the PubRules checker. It may be why I'm seeing an issue about "Required patent policy paragraph not found.", even though ReSpec does create a patent policy paragraph.

But what I was expecting?:

Optional, steps to reproduce:
 1. ...

**Comment by marcoscaceres** [comment]
Argh, we might need to dig through the w3c templates and set the right conditions for this. It’s weird that PubRules is getting confused though.

**Comment by marcoscaceres** [comment]
I think process 2021 solved this. There is now only 1 type of note.
