### ISSUE TITLE
Browser Support table generated by caniuse feature should factor in mobile versions of Chrome, Firefox, and Safari

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#2859]
With the `caniuse` feature enabled, Respec apparently doesn’t take mobile versions of Chrome, Firefox, and Safari into consideration when generating the Browser Support table.

An example where that can lead to misleading information is the Network Information API:

https://wicg.github.io/netinfo/

That shows misleadingly shows only Chrome and (Blink-based) Edge have support. But in fact Firefox for Android also has support, as shown by https://caniuse.com/#feat=netinfo and https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API#Browser_compatibility

There are other cases where we have features that aren’t enabled in desktop versions of Chrome, Firefox, and Safari but that are enabled in the mobile versions.

So, for specs to be showing accurate indicators of browser support, Respec should consider the mobile versions of Chrome, Firefox, and Safari when generating Browser Support tables.

**Comment by marcoscaceres** [comment]
Hi @sideshowbarker, please see https://github.com/w3c/respec/wiki/caniuse ... it can be configured specifically to show mobile versions.

**Comment by sideshowbarker** [comment]
aha — I should have taken time to read the docs… Will close this and file an issue against the Netinfo spec. Thanks!

**Comment by marcoscaceres** [comment]
Sounds good. See you over in the other repo :) Should be quick to fix.
