### ISSUE TITLE
Better support indicators for MDN boxes

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2861]
Elsewhere, @sideshowbarker wrote:

@marcoscaceres This reminds me that I’ve been meaning to suggest an enhancement to the MDN annotations generated by Respec: We can add an implementation-status indicator to the collapsed MDN buttons. Take a look at https://wicg.github.io/webusb/#device-usage

The (Bikeshed-generated) MDN annotations there shout pretty loudly (maybe too loudly…) that `USBDevice` is only implemented in one engine.

Then for comparison, go to https://drafts.csswg.org/css-logical-1/#caption-side and scroll down. The implementation-status indicators in the MDN annotations there are pretty useful. The CSS Logical Properties and Values spec is a mix of features at varying levels of implementation maturity: some implemented in all engines, some in two engines, and some only in one engine. A reader can get a pretty quick sense of which are which just with quick scroll through the spec.

Due to the baroque complexity of BCD status data for some features, programatically identifying whether a particular browser currently supports a particular feature requires some work. But I’ve already done that work — three times: Once in Free Pascal (for the HTML spec) and once in Python (for Bikeshed) and once also in JavaScript (for https://github.com/w3c/mdn-spec-links).

We could re-use the same algorithm for Bikeshed — and probably also copy over the JavaScript code for it that I already have. I’ve been meaning to write a Bikeshed patch for it, but haven’t managed to get around to it quite yet.

**Comment by marcoscaceres** [comment]
Sample of not supported: 

![Screenshot 2020-05-11 18 30 45](https://user-images.githubusercontent.com/870154/81540832-949e7e00-93b5-11ea-89c5-aa243feab73e.png)

Sample of supported: 

![Screenshot 2020-05-11 18 30 59](https://user-images.githubusercontent.com/870154/81540838-9700d800-93b5-11ea-8922-2b1163108a6d.png)

**Comment by sideshowbarker** [comment]
I realize now I misspoke a bit in what’s in the issue description here. It’s not actually necessary to re-write an algorithm for generating the implementation-status indicatators.

That’s because all the https://w3c.github.io/mdn-spec-links/ JSON data already now includes an `engines` array that lists the shortname of each engine that supports a particular feature; like this:

```json
    "dom-mediadeviceinfo-deviceid": [
        {
            "engines": [
                "blink",
                "gecko"
            ], 
```
So you can just check the length of that `engines` array.
