### ISSUE TITLE
xref linking bug

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2902]
Given `xref: "web-platform"` in the config, the following works fine:

```HTML
      <li>
            <a data-cite="fetch">body</a>.
      </li>
```

While the following does not (complains it's ambiguous, because HTML also defines `body`): 

```HTML
      <li data-cite="fetch">
            <a>body</a>.
      </li>
      <li data-cite="fetch">
            [=body=].
      </li>
```

For whatever reason, xref is not getting the citation context from its closest parent.

**Comment by sidvishnoi** [comment]
xref is indeed getting context from closest parent, but the problem is, it doesn't stop when it has found a term. It's a major logical bug in respec-xref-route's search function.

**Comment by marcoscaceres** [comment]
Oops
