### ISSUE TITLE
W3C logo showing up in unofficial drafts

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2904]
## Important info

* URL to affected spec: https://ec-jrc.github.io/dcat-ap-jrc/
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1): 25.6.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

The W3C logo is showing up in unofficial drafts, even if the `logos` field is missing in `config.js`. This was not happening until recently.

It seems to be the same problem reported in https://github.com/w3c/respec/issues/1725 and fixed that time.

But what I was expecting?: 

No logo

Optional, steps to reproduce:
 1. ...

**Comment by sidvishnoi** [comment]
`src/w3c/defaults.js` which runs before `src/w3c/headers.js`, adds this logo without checking for `specStatus`. Need to filter out default logo while checking for specStatus in `src/w3c/headers.js`
