### ISSUE TITLE
Weirdness of "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2913]
In [xref search](https://respec.org/xref/?term=application%2Fx-www-form-urlencoded),   "application/x-www-form-urlencoded" is categorized as a HTML attribute... might be a bug in HTML that it's being exported incorrectly? 

We are suggesting it be cited as "[^application/x-www-form-urlencoded^]", which doesn't actually match anything.

**Comment by sidvishnoi** [comment]
This seems to be an issue with HTML spec. Bikeshed is treating it as:
https://github.com/tabatkins/bikeshed-data/blob/260ae9181b3940eb7301a1446c64e3eddc09b206/data/anchors/anchors-ap.data#L888-L896

**Comment by sidvishnoi** [comment]
`[^application/x-www-form-urlencoded^]` is buggy for sure. It'll look for "x-www-form-urlencoded" attribute for "application" element. Need to allow escaping `/` when it's part of the term.

**Comment by sidvishnoi** [comment]
@marcoscaceres What do you prefer for escaping? `[^foo//bar^]` or `[^foo\/bar^]` or something else? There are more terms like `"text/html"` that need escaping.

I couldn't figure out what Bikeshed uses - maybe it's not supported there.

**Comment by marcoscaceres** [comment]
I think [^foo\/bar^] as we use \ to escape citations already.

**Comment by sidvishnoi** [comment]
Looks like your comment got escaped and rendered wrong?
![image](https://user-images.githubusercontent.com/8426945/83029106-e7cc2e00-a04f-11ea-8a41-0647d9d7851e.png)

**Comment by marcoscaceres** [comment]
Indeed, rendered wrong... had to escape it 😅

**Comment by sidvishnoi** [comment]
This issue can be closed now I think.. until we find a valid case where we need element attr that contains `/` (or when we support attr-value).

**Comment by marcoscaceres** [comment]
Ok, but does the HTML spec still need to be fixed so it exports the right thing?

**Comment by sidvishnoi** [comment]
Depends on what you want to export from there. I think you were looking for some serializer, which is exported
