### ISSUE TITLE
data-sort is broken for PWETF

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#2920]
## Important info

* URL to affected spec: https://w3c.github.io/PWETF/#dfn-bully
* ReSpec version: 25.8.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: "Workplace Bullying" is sorted between "Sexism" and "Sexual harassment"

But what I was expecting?: It should be last in the list.

**Comment by sidvishnoi** [comment]
There are a few markup errors there that cause the list to end prematurely.
https://github.com/w3c/PWETF/blob/09f74e778895e89ccf06113cd77ff3f812524287/index.html#L766
https://github.com/w3c/PWETF/blob/09f74e778895e89ccf06113cd77ff3f812524287/index.html#L776-L778

**Comment by jyasskin** [comment]
Thanks for finding those. From https://github.com/w3c/PWETF/pull/139/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL753, the choice of whether to use `<dt> <dfn>stuff...` or `<dt><dfn>stuff...` also appears to change the sort key, which shouldn't be happening.

Since Respec runs after the HTML parser fixes things up, it seems like it'll be hard to detect every error, but it could probably warn for https://github.com/w3c/PWETF/blob/09f74e778895e89ccf06113cd77ff3f812524287/index.html#L776-L778 which causes a plain `<dfn>` tag to appear in the final DOM where there ought to only be a `<dt>` or `<dd>`.

**Comment by sidvishnoi** [comment]
> the choice of whether to use <dt> <dfn>stuff... or <dt><dfn>stuff... also appears to change the sort key, which shouldn't be happening.

Yes, that's a bug. Will fix ASAP.

Regarding the invalid markup issues, I'm afraid such checks might bloat ReSpec. I think they should be checked by IDE and other tooling. A quick one could be to use tidy as a validator:
```
$ tidy -config tidyconfig.txt -o /dev/null -q index.html
line 469 column 5 - Warning: missing </section> before <dt>
line 768 column 9 - Warning: inserting implicit <dl>
line 777 column 11 - Warning: missing <dd>
line 778 column 9 - Warning: discarding unexpected </dt>
line 797 column 9 - Warning: trimming empty <dt>
```
