### ISSUE TITLE
No section numbering when content is in a file imported via data-include

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#2925]
## Important info

* URL to affected spec: https://andrea-perego.github.io/respec/examples/starter.html (not a spec, just made it to reproduce the issue)
* ReSpec version: 25.6.0, 25.8.1
* [x] I did a "hard refresh", but it's still busted. 

### What happened (e.g., it crashed)?: 

If part of the content of a document, including `SECTION` elements, is in an external file, imported in the main document via `data-include`, ReSpec does not number those `SECTION`'s.

You can see this at

https://andrea-perego.github.io/respec/examples/starter.html

and compare it with

https://w3c.github.io/respec/examples/starter.html

As you can see, Section 1.2 is not numbered in the former, where this section has been moved to an external file imported via `data-include`.

### But what I was expecting?:

To have sections numbered also when the content is in an imported file.

### Optional, steps to reproduce:
 1. ...

**Comment by sidvishnoi** [comment]
@andrea-perego Please consider using [`data-include-replace`](https://github.com/w3c/respec/wiki/data-include-replace)

**Comment by andrea-perego** [comment]
Thanks for the hint. @sidvishnoi .
