### ISSUE TITLE
Double commas appear in WebIDL interface attributes with nullables

### ISSUE THREAD

**Issue by scheib** [w3c/respec#295]
e.g. ```<dt>attribute unsigned long? viciousness</dt>```
Produces: "viciousness of type unsigned long, , nullable"
Expected: "viciousness of type unsigned long, nullable"

From: http://www.w3.org/respec/examples/webidl.html#attributes-3

**Comment by marcoscaceres** [comment]
We are deprecating using `dl` defined IDL, so closing as won't fix.
