### ISSUE TITLE
respec.org certificate has expired

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#2979]
This breaks XRef access

**Comment by sidvishnoi** [comment]
:fire: This breaks everything :fire: 
Let me see if I can figure something out on the server, otherwise @marcoscaceres will have to do it in morning.

**Comment by marcoscaceres** [comment]
Waiting on Dreamhost still... le sigh...

**Comment by sidvishnoi** [comment]
Phew. Looks alright now.
Thanks for reporting @dontcallmedom!

**Comment by marcoscaceres** [comment]
Dreamhost said:

>I'm very sorry about the trouble with renewing your SSL.
>
>I've confirmed all DNS records point to DreamHost so the SSL should have
been renewed automatically via DNS validation.

Hopefully doesn't happen again 🤞
