### ISSUE TITLE
Proposal: add a `prepare()` pass before `run()` pass

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2981]
ReSpec has "prepare" code like [this](https://github.com/w3c/respec/blob/b9dab188f0eb460980fcabac718e85cb421fed47/src/core/worker.js#L10-L21) or [this](https://github.com/w3c/respec/blob/7faae154e57d4af864a83b50adf744029fbd7496/src/core/style.js#L15-L16) in many modules. My idea is to add a `async prepare(conf)` in such modules, and do a pass where all modules run their `prepare()`, followed by our existing `run()` pass.

Why?
- I was trying to reorder some plugins to make overall ReSpec appear to load faster (mainly create ToC before content below the fold). But some plugins add headings dynamically (not available until they `run()`), but ToC requires those headings (so we've a dependency chain making ToC render late). If we can generate those headings in a prepare, then we can easily generate ToC earlier (See this demo of impact: https://respec-run-toc-early.netlify.app).
- This would also help with https://github.com/w3c/respec/pull/2187 where we can keep mutations in prepare, and not make them top-level.

Thoughts? @saschanaz @marcoscaceres

**Comment by saschanaz** [comment]
This sounds good! I see no immediate negative point.

**Comment by marcoscaceres** [comment]
Like it! /me presses 👍 button.
