### ISSUE TITLE
MDN shortName gets overridden 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2982]
given config:
```
      shortName: "geolocation-API", // upper case
      mdn: {
        shortName: "geolocation-api", // lower case
        mdn: true,
      },
```

The MDN shortName gets overridden by the top level `shortName`, so results in a 404 when fetching from MDN.

**Comment by sidvishnoi** [comment]
The `mdn` configuration as object is internal. To specify a different key, use `mdn` as a string. 
Wiki: https://github.com/w3c/respec/wiki/mdn
``` js
{
      shortName: "geolocation-API", // ignored for mdn
      mdn: "geolocation-api", // used by mdn
}
```

**Comment by marcoscaceres** [comment]
oh, lol, missed that...
