### ISSUE TITLE
bogus reference replacement when shortname is a prefix of another spec

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#2984]
## Important info

* URL to affected spec: https://w3c.github.io/webrtc-pc/ when upgraded to latest respec as in https://github.com/w3c/webrtc-pc/pull/2549
* ReSpec version: 25.11.0
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

ReSpec replaces `WEBRTC` in all references of the WebRTC spec by `__SPEC__`, but in the process, it replaces references to `WEBRTC-STATS` by `__SPEC__-STATS` which thus fails.

see also https://github.com/w3c/webrtc-pc/runs/817547755?check_suite_focus=true

**Comment by sidvishnoi** [comment]
This will be fixed on next ReSpec release, in the `respec-w3c` profile. The issue doesn't exist in `respec-w3c-common`.

Note that, the respec-w3c profile is not fully compatible with respec-w3c-common, so there might be errors. Mainly `require(["core/pubsubhub"]` etc. will be removed in near future.
