### ISSUE TITLE
Warning on respec-w3c-common

### ISSUE THREAD

**Issue by deniak** [w3c/respec#2986]
## Description of problem

I recently noticed that https://www.w3.org/Tools/respec/respec-w3c-common was no longer updated and found a related issue https://github.com/w3c/respec/pull/2838.

If https://www.w3.org/Tools/respec/respec-w3c-common is deprecated, is it possible to add a warning so people are aware they should switch to https://www.w3.org/Tools/respec/respec-w3c? Also, should we keep the common version around or do you expect a redirection to the new version instead?

**Comment by sidvishnoi** [comment]
> is it possible to add a warning so people are aware they should switch

Yes. Got that planned in https://github.com/w3c/respec/issues/2889. 

> should we keep the common version around

Yes. We'll keep it as long as it has users. Redirecting to other one will cause a lot of breakage, which is why we froze it in first place. Though, we still backport severe bug fixes to w3c-common.

**Comment by marcoscaceres** [comment]
> If https://www.w3.org/Tools/respec/respec-w3c-common is deprecated, is it possible to add a warning so people are aware they should switch to https://www.w3.org/Tools/respec/respec-w3c? 

I think we need to basically go through all W3C specs that are using it and evaluate each on case-by-case basis... there are some folks (e.g., A11y WG) that have added some jQuery extensions, so they can't move to the new stuff. 

> Also, should we keep the common version around or do you expect a redirection to the new version instead?

As above... no. It's more a matter of systematically moving everyone over to the new ReSpec. I'm hoping we will be able to do that over the next year, and hopefully we can kill off -common in a year or two entirely.

**Comment by deniak** [comment]
Thanks for the details. I'll close the issue since you have already the warning planned.
