### ISSUE TITLE
HTML in markdown code snippets doesn't work

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#3005]
<details>
<summary>Unescaped Input</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Replace me with a real title</title>
    <script src='../profiles/w3c.js' async class='remove'></script>
    <script class='remove'>
      var respecConfig = {
        specStatus: "ED",
        shortName: "shortname-api",
        editors: [{ name: "Your Name" }],
        github: "https://github.com/w3c/some-API/",
        format: "markdown",
      };
    </script>
  </head>
  <body>

    ## test

    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
    </head>
    <body>
      <div class="issue" data-number="280"></div>
      <script>
        alert("whoa");
      </script>
    </body>
    </html>
    ```

    <section id='abstract'>
      <p>This is required.</p>
    </section>
    <section id='sotd'>
      <p>This is required.</p>
    </section>
  </body>
</html>
```

</details>

<details>
<summary>Output (HTML in snippet evaluated, including the script!)</summary>

![image](https://user-images.githubusercontent.com/8426945/87032305-08b4a100-c202-11ea-8d9d-f6c0ab1425a9.png)

</details>

And if I try to escape:

<details>
<summary>Escaped Input</summary>

```html
    ## test

    ```html
    &lt;!DOCTYPE html&gt;
    &lt;html lang="en"&gt;
    &lt;head&gt;
      &lt;meta charset="UTF-8"&gt;
      &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
      &lt;title&gt;Document&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
      &lt;div class="issue" data-number="280"&gt;&lt;/div&gt;
      &lt;script&gt;
        alert("whoa");
      &lt;/script&gt;
    &lt;/body&gt;
    &lt;/html&gt;
    ```
```

</details>

<details>
<summary>Output</summary>

![image](https://user-images.githubusercontent.com/8426945/87032378-28e46000-c202-11ea-8081-1ebcbd28eb79.png)

</details>

Also, unindenting everything to left evaluates some part of input:
<details>

![image](https://user-images.githubusercontent.com/8426945/87033321-a65ca000-c203-11ea-9b71-c6cfef3384f4.png)

</details>

So, it's not possible to add HTML code snippets in markdown.

I can see it doesn't mean to work this way, but I would like if we could make it work for includes.

**Comment by sidvishnoi** [comment]
@saschanaz thoughts?

**Comment by saschanaz** [comment]
It seems markdown thinks HTML tags as plain texts inside code blocks, as the same happens on the [marked demo page](https://marked.js.org/demo/?text=%23%23%20test%0A%0A%60%60%60html%0A%3C!DOCTYPE%20html%3E%0A%3Chtml%20lang%3D%22en%22%3E%0A%3Chead%3E%0A%20%20%3Cmeta%20charset%3D%22UTF-8%22%3E%0A%20%20%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1.0%22%3E%0A%20%20%3Ctitle%3EDocument%3C%2Ftitle%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%0A%20%20%3Cdiv%20class%3D%22issue%22%20data-number%3D%22280%22%3E%3C%2Fdiv%3E%0A%20%20%3Cscript%3E%0A%20%20%20%20alert(%22whoa%22)%3B%0A%20%20%3C%2Fscript%3E%0A%3C%2Fbody%3E%0A%3C%2Fhtml%3E%0A%60%60%60%0A%0A%23%23%20test%0A%0A%60%60%60html%0A%26lt%3B!DOCTYPE%20html%26gt%3B%0A%26lt%3Bhtml%20lang%3D%22en%22%26gt%3B%0A%26lt%3Bhead%26gt%3B%0A%20%20%26lt%3Bmeta%20charset%3D%22UTF-8%22%26gt%3B%0A%20%20%26lt%3Bmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1.0%22%26gt%3B%0A%20%20%26lt%3Btitle%26gt%3BDocument%26lt%3B%2Ftitle%26gt%3B%0A%26lt%3B%2Fhead%26gt%3B%0A%26lt%3Bbody%26gt%3B%0A%20%20%26lt%3Bdiv%20class%3D%22issue%22%20data-number%3D%22280%22%26gt%3B%26lt%3B%2Fdiv%26gt%3B%0A%20%20%26lt%3Bscript%26gt%3B%0A%20%20%20%20alert(%22whoa%22)%3B%0A%20%20%26lt%3B%2Fscript%26gt%3B%0A%26lt%3B%2Fbody%26gt%3B%0A%26lt%3B%2Fhtml%26gt%3B%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master).

**Comment by sidvishnoi** [comment]
Maybe we can run `markdownToHTML` for `data-include` earlier - before adding the content to DOM - to prevent evaluating HTML?

**Comment by saschanaz** [comment]
Not quite sure what's the concern here, I think the unescaped input is okay as it is, as those HTML tags will not be parsed as HTML by marked.

**Comment by sidvishnoi** [comment]
Have a look at https://respec.org/docs/src.html#basic-layout
"Example 1" gets parsed as HTML (there are no `<html>`, `<head>` tags in example, but they're in source) .

**Comment by saschanaz** [comment]
Ah got it, we inject it first to the tree as `innerHTML` and this is the problem... Yes, your suggestion seems viable, maybe with `data-include-format=markdown`.
