### ISSUE TITLE
CG/BG drafts should use CG-DRAFT, not ED

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3017]
When the group is W3C's WICG, ReSpec error if the status is not CG-DRAFT or CG-FINAL(i.e., "ED" is not allowed).

**Comment by hober** [comment]
This should be the case for any CG.

Note that the Bikeshed change validates the status for all W3C groups. For instance, it would warn if a WG tried to use CG-DRAFT as well.
