### ISSUE TITLE
WG-NOTE does not generate Previous version header

### ISSUE THREAD

**Issue by fhirsch** [w3c/respec#303]
Generating a WG-NOTE does not include a previous version header.  It should, for example when previousPublishDate and previousMaturity are set.

This works fine for specStatus WD but fails for specStatus WG-NOTE

**Comment by marcoscaceres** [comment]
This WFM. Tested using:

```
      var respecConfig = {
        specStatus: "WG-Note",
        editors: [{
          name: "Your Name",
          url: "http://your-site.com",
        }],
        processVersion: 2015,
        edDraftURI: "http://some.github.repo",
        shortName: "dahut",
        previousMaturity: "WD",
        previousPublishDate: "2014-12-12", 
      };
```

And seen output: 
![screenshot 2016-04-19 18 50 45](https://cloud.githubusercontent.com/assets/870154/14633171/c2e9b898-065f-11e6-8d03-6662046b0d17.png)
