### ISSUE TITLE
`group` configuration option doesn't work

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3032]
## Important info

- URL to affected spec: https://raw.githack.com/w3c/bp-i18n-specdev/xfq/respec-group/index.html (source is currently in a PR: https://github.com/w3c/bp-i18n-specdev/pull/46 )
- ReSpec version: 25.12.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

The sentence "This document was published by the Internationalization Working Group as an Editor's Draft." disappeared, and the link in "W3C maintains a public list of any patent disclosures" is broken. I tried it in a local http server and the result is the same.

**Expected behavior (e.g., it shouldn't crash):**

The sotd text/links shouldn't be changed.

**Comment by sidvishnoi** [comment]
@xfq It seems to be working fine to me:
![image](https://user-images.githubusercontent.com/8426945/88146980-380fd880-cc1a-11ea-82e2-6b81e4eb5e21.png)

**Comment by xfq** [comment]
I have tried Chrome 84.0.4147.89, Firefox 78.0.2, and Safari 13.1.1 on macOS 10.15.5 after clearing the cache and disabling the extensions, but only Safari works. See the screenshots below:

-----

Chrome:

<img width="1680" alt="chrome" src="https://user-images.githubusercontent.com/2863444/88163525-61922980-cc45-11ea-957a-8e8b133514bf.png">

-----

Firefox:

<img width="1680" alt="firefox" src="https://user-images.githubusercontent.com/2863444/88163566-6e168200-cc45-11ea-9ed6-7406b6fd2a90.png">

-----

Safari:

<img width="1680" alt="safari" src="https://user-images.githubusercontent.com/2863444/88163754-ba61c200-cc45-11ea-9338-28e0634d41f3.png">

**Comment by sidvishnoi** [comment]
Weird. It's working for me in Firefox (78, 80) and Chrome (84). Can you check if there are any errors in developers console?

**Comment by sidvishnoi** [comment]
@marcoscaceres @saschanaz - Can you reproduce this?

**Comment by xfq** [comment]
> Can you check if there are any errors in developers console?

Please see the screenshots below.

-----

Chrome:

<img width="1680" alt="chrome" src="https://user-images.githubusercontent.com/2863444/88185472-8d71d700-cc66-11ea-9b0f-ef20f16eec86.png">

-----

Firefox:

<img width="1680" alt="firefox" src="https://user-images.githubusercontent.com/2863444/88185502-95ca1200-cc66-11ea-9310-892b385bf975.png">

-----

See also Safari, in case it provides some useful info as well:

<img width="1680" alt="safari" src="https://user-images.githubusercontent.com/2863444/88185580-ada19600-cc66-11ea-8d86-36378813be05.png">

**Comment by saschanaz** [comment]
Line 499 in `fetchAndCache` should probably call `.valueOf()` instead of `toString()`. BTW, still weird that it's getting ByteString conversion error. What's the value of `expiryDate` when you add a breakpoint at `utils.js:499`?

**Comment by sidvishnoi** [comment]
Ah. toString produces locale dependent string. We can use toISOString here, if valueOf is not supported.

**Comment by sidvishnoi** [comment]
Will send a fix in an hour or so..

**Comment by saschanaz** [comment]
ISOString sounds good as it's more readable 👍

**Comment by sidvishnoi** [comment]
@xfq, thanks for those error messages. It should be fixed with #3033, though would be nice if you can confirm it by replacing the respec script with https://deploy-preview-3033--respec-pr.netlify.app/respec-w3c.js.

It should be released by next week. We can do an early release with this patch if you need to earlier.

**Comment by xfq** [comment]
I confirm that All Goes Well now. Thanks!
