### ISSUE TITLE
Proposal: improving error reporting

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#3035]
Create a custom error class:
``` js
// extending error gives us stack trace
class ReSpecError extends Error {
  // which module had error. can help in filtering errors.
  module: string;
  message: string;
  details?: string;

  // how to solve the error, link to docs etc.
  hint?: string;

  // offending elements
  elements?: Element[],
  // ... or offending respecConfig property
  config?: string,
  // and maybe more or less members if needed
}
```

Instead of `pub("error", message)`, do `pub("error", new ReSpecError(...))` to get a more structured and consistent error message. Then we can selectively show parts of error in UI and console.

Also, by `document.dispatchEvent(new CustomEvent('respecerror' | 'respecwarning', { detail: respecError }))` in `sub("error" | "warn")`, we can attach event listeners in respecDocWriter instead of watching for console messages. This way, we can better display errors/warnings with CI or spec-generator service.

Thoughts @saschanaz @marcoscaceres?

I played a bit with this earlier in [better-error-doc-writer](https://github.com/w3c/respec/compare/better-error-doc-writer) branch (also includes some nice-ish API changes to respecDocWriter).

**Comment by marcoscaceres** [comment]
Looks like a good change.

**Comment by sidvishnoi** [comment]
Moving `dispatchEvent` part to https://github.com/w3c/respec/issues/1084
