### ISSUE TITLE
Internal slots should support linking as instance variables 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3037]
Currently we support {{Foo.[[slot]]}}, but we don't support `{{Foo/[[slot]]}}`. The latter form is generally more useful, as normally we do:

> Set the |thing:Foo|.{{Foo/[[slot]]}} to "some value".

**Comment by sidvishnoi** [comment]
Discussed over Slack. The internal slot definition was missing `data-dfn-type="idl"`. Automating this in https://github.com/w3c/respec/pull/3038
