### ISSUE TITLE
ARIA landmarks are not quite correct

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#304]
In a PFWG Editor's meeting today, we reviewed the aria landmarks that ReSpec is inserting into documents.  There are some additional landmarks that could be automatically generated (e.g., a role of navigation on the table of contents), and some that are not quite right (e.g. a role of heading on an h\* element is not strictly necessary).

Definition lists can have role of definition on the defining text, linked to the things they define - in conjunction with dfn elements anyway.  Also, inline dfn elements can have their enclosing element be used as a definition.

**Comment by marcoscaceres** [comment]
@halindrome, is this bug still valid?

**Comment by halindrome** [comment]
Yes.  And I have a PR somewhere that does quite a bit to address it.  I will put it on my list.

**Comment by marcoscaceres** [comment]
@halindrome sounds good. Looking forward to seeing it.

**Comment by marcoscaceres** [comment]
bumping to milestone 3.3

**Comment by marcoscaceres** [comment]
I'll add these based on feedback from Patrick.
