### ISSUE TITLE
Colons in the specification metadata block

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3041]
ReSpec can automatically generate spec metadata like "This version:", "Latest published version:", or "Participate:".

In https://github.com/w3c/respec/blob/f564b3aa141a02f267866f36e51e238bf1ed94c4/src/core/github.js#L23-L56 , there is no colon after the strings in `en`. Some languages use `U+FF1A` instead of `U+003A` for colon, so I think a better way to deal with the colon in a spec metadata entry is to either add colons to the strings (`participate: "Participate:"` instead of `participate: "Participate"`), or let ReSpec automatically add a colon based on the language tag.

(Not sure this is a feature request or a bug, so tagging "feature request" for now.)

**Comment by xfq** [comment]
The colon seems to be generated here: https://github.com/w3c/respec/blob/33532d9f29b5188614ca16d75098eaa9df86875a/src/w3c/templates/show-link.js#L14

**Comment by marcoscaceres** [comment]
Great point.

**Comment by saschanaz** [comment]
Which language prefers U+FF1A BTW?

**Comment by xfq** [comment]
> Which language prefers U+FF1A BTW?

It's very commonly used in Chinese and Japanese.

I have also seen it in Korean, but I don’t know whether it is commonly used (preferred).

**Comment by saschanaz** [comment]
>I have also seen it in Korean, but I don’t know whether it is commonly used (preferred).

I can confirm it's not.

**Comment by xfq** [comment]
For Chinese, see also https://w3c.github.io/clreq/#id78
