### ISSUE TITLE
Linter for well-known noninclusive words

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#3059]
**Is your feature request related to a problem? Please describe.**

Some specifications still have noninclusive words including blacklists: https://w3c.github.io/webcrypto/KeyDiscovery.html

A linter will be helpful to detect and remove them.

**Describe the solution you'd like**

Warn wherever such words exist with a way to suppress it

**Comment by marcoscaceres** [comment]
@Alice linked to this on twitter:
https://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

I think it would be awesome to have this as a linter, along with recommendations for alternatives. 

@saschanaz, something you'd wanna build?

**Comment by sidvishnoi** [comment]
Specberus has this already: https://github.com/w3c/specberus/blob/main/lib/rules/structure/neutral.js

Might be better to delegate that to spec-prod instead of ReSpec? https://github.com/w3c/spec-prod/issues/3

**Comment by saschanaz** [comment]
Good idea 😃

**Comment by marcoscaceres** [comment]
I guess it depends if we can get echidna checks running earlier... it's nice getting those kinds of warnings early in the spec development process (i.e., as someone is editing locally, instead of pre-publication).

**Comment by marcoscaceres** [comment]
Closing as we now support pub rules on spec-prod.
