### ISSUE TITLE
Unofficial specs using CC-BY

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3064]
In a spec with `specStatus: "unofficial", license: "cc-by"`, ReSpec emits an error:

> You cannot use license "`cc-by`" with W3C Specs. Please set `respecConfig.license: "w3c-software-doc"` instead.

In the documentation for [specStatus](https://github.com/w3c/respec/wiki/specStatus), `unofficial` is:

> An unofficial draft. Use this if you're producing a document outside of W3C but want to use styles that match those of W3C specifications, for instance to propose a new document while hosting it on your own server. Note that this automatically licenses the content under CC-BY v3.0. If you want a different copyright, you will need to set the various copyright configuration options.	

(BTW, CC-BY v3.0 should probably be CC-BY v4.0 here. See [the code here](https://github.com/w3c/respec/blob/b623ed094e11b251c9b6c03bf347afb3359ffd23/src/w3c/templates/headers.js#L288).)

Since "unofficial" is considered a document *outside* of W3C and the default license is CC-BY, maybe ReSpec shouldn't emit this [error](https://github.com/w3c/respec/blob/2bcffb680c784b0fe65c606bc08c5e22fc797872/src/w3c/headers.js#L238-L241)?

**Comment by xfq** [comment]
I just took a look and the problem seems to have not been fixed. Is it because there is no new version of ReSpec released yet?

**Comment by sidvishnoi** [comment]
@xfq release coming up in a few hours.
