### ISSUE TITLE
"npm start" devserver doesn't work with Firefox

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#3070]
See https://github.com/w3c/respec/pull/3068#discussion_r471137177

**Comment by marcoscaceres** [comment]
WFM (`npm start -- --browser Firefox`) with FF 88.  

<img width="704" alt="Screen Shot 2021-04-26 at 6 13 16 pm" src="https://user-images.githubusercontent.com/870154/116050660-149f2000-a6bb-11eb-9d82-74288f467eb5.png">
