### ISSUE TITLE
Adapt W3C profile to new process / patent policy

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3086]
**Is your feature request related to a problem? Please describe.**
By September 15, W3C specifications will be developed under a new Process (which introduces new sub-stages to the CR process and new states for the post-REC life); progressively, groups will transition to a new patent policy. See https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0024.html

See also https://github.com/w3c/modern-tooling/issues/86

**Describe the solution you'd like**
ReSpec should be ready to handle:
* changes in the SOTD
* new CR classes
* Rec with embedded changes or additions

**Describe alternatives you've considered**
N/A

**Can you or your organization fund the work or help with development?**
I'll take care of starting a draft pull request for at least the first 2 items above (since they're the ones that will be needed most rapidly)

**Additional context**
N/A

**Comment by sidvishnoi** [comment]
Support added in https://github.com/w3c/respec/pull/3096
