### ISSUE TITLE
Respec GitHub Pages Template

### ISSUE THREAD

**Issue by OR13** [w3c/respec#3122]
**Is your feature request related to a problem? Please describe.**

Often need to create a new specification that is hosted on GitHub pages. 

Wish I could use markdown as well as html.

Spend a lot of time explaining how GitHub works to people trying to use ReSpec.

**Describe the solution you'd like**

I'd like a "ReSpec starter github pages" template, that is community maintained, well documented / clean...

and which can be used to create new specifications, that will just work, after the repo has been created.

**Describe alternatives you've considered**

Always copying from the same repos i am familar with, lots of find replace...

**Can you or your organization fund the work or help with development?**

We can help with development.

**Additional context**

Made this GitHub template https://github.com/transmute-industries/respec-github-pages

Would be happy to donate it / work with anyone else who likes this idea to improve it.

**Comment by marcoscaceres** [comment]
Hi @OR13! Good suggestion. It's certainly possible to write a spec using markdown... however, markdown can be a bit limited, but if a spec is simple enough, it can be done. All one needs is to set `format: "markdown"` or use `data-include=` and set the format (details can be found at https://respec.org/docs/#markdown). 

Here are two examples that use markdown in their specs:

 * https://github.com/WICG/serial/blob/gh-pages/index.html
 * https://github.com/WICG/netinfo/blob/gh-pages/index.html

About the template, sounds like a great idea. I think @plehegar was working on something similar at:
https://github.com/w3c/note-respec-repo-template

So might be worth combining forces there. 

I'm also reminded that our own ReSpec docs are generated from markdown pulled directly from this project's wiki:
https://github.com/marcoscaceres/respec.org/blob/gh-pages/static/docs/src.html

It does require some additional JS, but @sidvishnoi can provide more details if needed.

**Comment by OR13** [comment]
@marcoscaceres yes, in fact, I generally advise against using markdown for specs... but since so many people want to use it, I prefer not to take a bunch of dev dependencies to use it with github... here is the linked to the w3c ccg mailing list where I announced it: https://lists.w3.org/Archives/Public/public-credentials/2020Sep/0058.html

I will see about merging / aligning with the repos you linked.

Thanks!

**Comment by marcoscaceres** [comment]
Ok, cool. Let me know how you'd like to proceed.

**Comment by OR13** [comment]
I opened an issue on the other repo template, I will close this issue.
