### ISSUE TITLE
Add W3C Interest and Business Groups to `groups`  option

### ISSUE THREAD

**Issue by chrisn** [w3c/respec#3130]
## Important info

- URL to affected spec: https://w3c.github.io/me-media-timed-events/
- ReSpec version: 25.16.4
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

The list of W3C groups at https://respec.org/w3c/groups/ doesn't include Interest or Business Groups, so I don't know what `group`  value to set to update my document.

**Comment by sidvishnoi** [comment]
Updated list at https://respec.org/w3c/groups/

**Comment by chrisn** [comment]
LGTM. Thank you for responding so quickly!
