### ISSUE TITLE
Issue titles in issue summary section are split between columns

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#3135]
## Important info

- URL to affected spec: https://raw.githack.com/w3c/dxwg/dcat-versioning/dcat/
- ReSpec version: 25.16.5
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened?:**

In the spec above, part of the issue title in the issue summary section has been moved to the 2nd column, with a resulting effect which is quite confusing for readers, and looks like a rendering error.

To see it, open the link below and scroll up to the "Issue summary" section:

https://raw.githack.com/w3c/dxwg/dcat-versioning/dcat/#introduction

**Expected behavior (e.g., it shouldn't crash):**

Issue titles are not split between columns.

**Optional, steps to reproduce:**

1.  ...

**Comment by sidvishnoi** [comment]
The problem seems to be gone for now.
IIRC, the problem was caused when there is a single issue in `issue-summary` (in a way, it's a rendering error: CSS multi-column is buggy).

**Comment by sidvishnoi** [comment]
Okay. I see it. Adding `display: inline-block` to `#issue-summary li` should fix that. Will send a PR soon.
