### ISSUE TITLE
Pubrules rejects future update link in PR documents

### ISSUE THREAD

**Issue by mattgarrish** [w3c/respec#3137]
## Important info

- URL to affected spec: https://w3c.github.io/pub-manifest/snapshot/ https://w3c.github.io/audiobooks/snapshot/
- ReSpec version: 25.16.5
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

The Proposed Recommendations for pub-manifest and audiobooks both anticipate future updates after recommendation. Respec currently outputs this paragraph in response:

```
<p>This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. Future updates to this specification may incorporate <a href="https://www.w3.org/2020/Process-20200915/#revised-rec-features">new features</a>.</p>
```

The pubrules checker has two complaints about this, however. First, it expects PR documents to link to the fragment #allow-new-features (which is more specific to PRs from what I see). Second, it won't recognize the link is there unless it is in its own paragraph (could be a bug with pubrules but noting here).

To get the documents error-free for publishing, I had to manually tweak the markup to:

```
<p>This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.</p>
<p>Future updates to this specification may incorporate <a href="https://www.w3.org/2020/Process-20200915/#allow-new-features">new features</a>.</p>
```

**Comment by marcoscaceres** [comment]
Sorry for the delay. CC @dontcallmedom, as it may be a W3C template issue. Will try to take a look soon.

**Comment by dontcallmedom** [comment]
@marcoscaceres I can take care of submitting a PR for this, thanks for pinging me

@deniak is it expected that pubrules enforce having a separate paragraph for the "allow new features" link?

**Comment by marcoscaceres** [comment]
Thanks @dontcallmedom! Really appreciate the help.

**Comment by deniak** [comment]
> @deniak is it expected that pubrules enforce having a separate paragraph for the "allow new features" link?

Nope, pubrules simply checks that the text appears in the SotD. I'll check why it reports an error when there's a single paragraph

**Comment by deniak** [comment]
@dontcallmedom your PR should fix the problem. It doesn't matter if it's in one or two separate paragraphs

**Comment by mattgarrish** [comment]
> Nope, pubrules simply checks that the text appears in the SotD.

If you don't find anything, I wonder if it picked up a cached version of the file from github. Didn't think of it at the time, as I made the changes in quick succession so I assumed the para change fixed it.

Is there any way to see the source of what pubrules is checking? I've run into caching problems happen in the past but they were more obvious in terms of the error no longer matching the source.

**Comment by deniak** [comment]
@mattgarrish unfortunately, pubrules doesn't have that option. Only Echidna will keep a record of each submitted document.
