### ISSUE TITLE
How do I get specref references when using respec2html.js

### ISSUE THREAD

**Issue by silviapfeiffer** [w3c/respec#314]
When I create my spec using phantomjs, it's missing the references:

  $ phantomjs respec/tools/respec2html.js index.html Overview.html

When I just load the page, the respec references are included.

I wasn't able to find documentation of how to get them when using respec2html.js .

**Comment by dontcallmedom** [comment]
not yet; I'm trying to get an instance of specrefs hosted on https://x.w3.org, but this is still in progress

**Comment by dontcallmedom** [comment]
hmm... this was fixed long ago, closing
