### ISSUE TITLE
Provide shortcut to IDL fragment

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3156]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm on the definition of an interface (attribute, methods, etc) (e.g. having followed a link from another spec) and I can't easily move to the IDL fragment where the said item is defined.

**Describe the solution you'd like**
An easily identifiable link from the said item back to where it is defined as an IDL fragment.

**Describe alternatives you've considered**
N/A

**Can you or your organization fund the work or help with development?**
I'd be happy to help implementing or reviewing if there is interest

**Additional context**
cc @tidoust since he expressed a similar interest in such a feature

**Comment by sidvishnoi** [comment]
To confirm, are you looking for a shorter way of doing this:
![image](https://user-images.githubusercontent.com/8426945/95437749-008c0f00-0973-11eb-8d2a-c8d6f9e344e2.gif)

**Comment by dontcallmedom** [comment]
not necessarily shorter (in terms of clicks), but much clearer. See e.g. https://w3c.github.io/webrtc-pc/webrtc.html#rtcrtpsender-interface - finding where to click to get to the IDL fragment takes way to long.

**Comment by sidvishnoi** [comment]
Something like this might be good:
![image](https://user-images.githubusercontent.com/8426945/95441070-4f3ba800-0977-11eb-90a2-dd56b1505795.png)
