### ISSUE TITLE
Make default template more mobile friendly 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#316]
If it doesn't already, the default template should include: 

```
<meta content="width=device-width,initial-scale=1" name="viewport">
```

**Comment by darobin** [comment]
Ok, fair point (though you should get a life ;). Go ahead!

**Comment by marcoscaceres** [comment]
I have a life... I often go out with my friends to the fanciest of social places, and we load up w3c specs on our mobile telephony devices and we laugh and laugh about people who write specs. Then we read random conformance requirements to each other while imitating the voices of various editors (including you!)* 


<small>* events depicted here may have only taken place in my head. Maybe I just read specs on the toilet. </small>

**Comment by darobin** [comment]
You know what, we should make a short movie that's *exactly* that.

**Comment by marcoscaceres** [comment]
I'm in! I'll start practicing my lines. I have a few favorites.

**Comment by darobin** [comment]
At this point anyone else getting notifications for this bug should *probably* hit the "Unsubscribe" button in the right column.

Here's mine:

```
[Definition:]  Throughout this specification, the term absent is used as a distinguished
property value denoting absence.
```
--http://www.w3.org/TR/xmlschema-1/#d0e1531

**Comment by marcoscaceres** [comment]
I've added this as part of https://github.com/w3c/respec/pull/571

**Comment by marcoscaceres** [comment]
The next w3c styesheet handles this now.
