### ISSUE TITLE
Multipage reference shorthand syntax doesn't work

### ISSUE THREAD

**Issue by marisademeglio** [w3c/respec#3176]
## Important info

- URL to affected spec: in progress, no URL at the moment
- ReSpec version: 25.18.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

This shorthand:
`[[HTML/media.html#dom-media-playbackrate]]`

uses the syntax found in the [shorthand documentation](https://github.com/w3c/respec/wiki/Shorthands-Guide#reference-shorthands) but results only in "Reference not found".

Respec is generally working ok for me -- just using `[[HTML]]` results in a reference to https://html.spec.whatwg.org/multipage/ .  

**Expected behavior (e.g., it shouldn't crash):**

I expect `[[HTML/media.html#dom-media-playbackrate]]` to create a reference to https://html.spec.whatwg.org/multipage/media.html#dom-media-playbackrate

**Comment by marcoscaceres** [comment]
Right, that syntax is deprecated for the HTML spec. For that, you should use:

```
{{HTMLMediaElement/playbackRate}}
```

Plus make sure you have `xref: "web-platform"` in your Respec config.    

When unsure how to cite (or the syntax), we've created a helpful tool to help (showing playbackRate):
https://respec.org/xref/?term=playbackRate

**Comment by marisademeglio** [comment]
Thanks! That worked. The github wiki isn't clear about the deprecated syntax.

**Comment by sidvishnoi** [comment]
We never supported the `[[SPEC/page.html#id]]` syntax. See https://github.com/w3c/respec/issues/2708
