### ISSUE TITLE
Bad reference error for valid specref ID

### ISSUE THREAD

**Issue by marisademeglio** [w3c/respec#3177]
## Important info

- URL to affected spec: in progress, no URL yet
- ReSpec version: 25.18.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

Reference `[[SMIL3]]` gives "bad reference" error.

**Expected behavior (e.g., it shouldn't crash):**

Expected that it would resolve correctly. It has an entry in specref: https://api.specref.org/bibrefs?refs=SMIL3

**Comment by marcoscaceres** [comment]
@marisademeglio, I wasn't able to reproduce locally. Do you have a link to the affected spec?

**Comment by marisademeglio** [comment]
No link yet, it's a work in progress. I'm waiting to fix these issues as well as finish some editorial tasks before the next draft is posted.

What I found is that fixing [this issue](https://github.com/w3c/respec/issues/3176) made this problem go away. So now I can reference `[[SMIL3]]` just fine.

I still can't do something like `[[SMIL3/smil-extended-media-object.html#edef-param]]` though (to point directly at [param](https://www.w3.org/TR/SMIL3/smil-extended-media-object.html#edef-param)) -- is that supposed to work?

**Comment by sidvishnoi** [comment]
Instead of `[[SMIL3/smil-extended-media-object.html#edef-param]]`, try:
```html
<a data-cite="SMIL3/smil-extended-media-object.html#edef-param">some text</a>
```

`data-cite` syntax is used when terms can't be found using https://respec.org/xref/ (need to make this clearer in docs)

**Comment by marisademeglio** [comment]
Great, thanks for the help!
