### ISSUE TITLE
Change all http links to https in ReSpec Documentation

### ISSUE THREAD

**Issue by Aman-Codes** [w3c/respec#3179]
**Is your feature request related to a problem? Please describe.**
Currently there are many http links  in [ReSpec Documentation website](https://respec.org/docs/) which on clicking redirects to the https links. It would be great if we change all links to https

**Describe the solution you'd like**
Change all http links to https in ReSpec Documentation

I would like to work on it and fix them.

**Comment by sidvishnoi** [comment]
Hi! This would need to be edited in the [wiki](https://github.com/w3c/respec/wiki). I would recommend going to the website, and hover over the heading of sections that contain `http://` links, and click the edit link to jump to correct page in wiki.

**Comment by Aman-Codes** [comment]
I believe we can safely close this issue as all the links are now updated expect some which are not https

**Comment by sidvishnoi** [comment]
Thanks @Aman-Codes, @somyadwivedi-mriirs!
