### ISSUE TITLE
Drop promisify() from tests

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#3188]
[fs.promises](https://nodejs.org/api/fs.html#fs_fs_promises_api) API has been there for a while. We should be able to use it without breaking changes.

**Comment by uditmishra128** [comment]
Hi ,I would like to work on this issue , can you suggest me way to get started.

**Comment by sidvishnoi** [comment]
@uditmishra128 We want to replace `promisify` calls from [tests/test-build.js](https://github.com/w3c/respec/blob/b4d3f7cc02a46cd208e8e155813b740d2f62ea91/tests/test-build.js) (and other files if any) with the `fs.promises` API. The tests are run via `npm run test:build`.
