### ISSUE TITLE
Wrap IDL code with <pre><code>

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#3189]
Currently ReSpec inserts `.idlHeader` into `<pre>`, which forces crawlers to use ReSpec-specific code to remove it.

Doing `<pre><span class="idlHeader">...</span><code>...</code></pre>` could be better, as crawlers can query `pre code` as a standard way. It's also semantically better, as `<pre>` does not automatically say the content is a code. [HTML](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element) says:

>To represent a block of computer code, the pre element can be used with a code element

It also can replace a hacky code inside ReSpec by querying `pre code`:

https://github.com/w3c/respec/blob/7faae154e57d4af864a83b50adf744029fbd7496/src/core/webidl-index.js#L67-L70

See also https://github.com/whatwg/html/pull/3768.

**Comment by marcoscaceres** [comment]
If I'm remembering correctly, we tried to do this once and it broke reffy - so we need to be cautious. Or, at least, we will need to check we don't break any dependent downstream services.

**Comment by saschanaz** [comment]
The pattern is already supported by reffy (because HTML uses it): https://github.com/tidoust/reffy/blob/master/src/browserlib/extract-webidl.js#L109
