### ISSUE TITLE
Support `event` as a `dfn-type`

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3197]
**Is your feature request related to a problem? Please describe.**
Although not fully documented, [Bikeshed recognizes `event`](https://tabatkins.github.io/bikeshed/#dfn-for) as an automatically exported definition type. This helps among other things auto-link to the said events via xref.

ReSpec should allow to do the same.

**Describe the solution you'd like**
`<dfn data-dfn-type=event>statechange</dfn>` should create a definition marked with a type of "event", exported by default, and linkable (in particular, allowing to discriminate between an event associated with an interface, and a method of the same name in the said interface).

**Describe alternatives you've considered**
N/A

**Can you or your organization fund the work or help with development?**
Always happy to review related pull requests

**Comment by saschanaz** [comment]
I think #3245 has nothing to do with dfn-type=event?

**Comment by dontcallmedom** [comment]
I think it was all that was needed for events to at least be exported (and thus referenceable from other specs); but I don't disagree that there may be more features wanted with that specific definition type

**Comment by saschanaz** [comment]
Ah okay, my misunderstanding 😬. Thanks for clarification 👍
