### ISSUE TITLE
Weird data-lt attribute for IDL methods with one optional param?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#3200]
## Important info

- URL to affected spec: All specs that define IDL methods that only take one optional parameter, e.g. [`PaymentResponse.complete`](https://w3c.github.io/payment-request/#dom-paymentresponse-complete) in [Payment Request API](https://w3c.github.io/payment-request/)
- ReSpec version: 25.18.1

## Description of problem

The generated `data-lt` attribute contains a leading comma that looks weird. For instance, the attribute's value is `complete()|complete(, result)` for the `PaymentResponse.complete` method. I would rather expect `complete(, result)` to be `complete(result)`.

That seems to only happen when there is only one argument that is `optional`.

**Comment by tidoust** [comment]
Digging into the code, I suspect that this happens due to:
https://github.com/w3c/respec/blob/develop/src/core/dfn-finder.js#L100

```js
const result = `${operationName}(${requiredArgs}${
  optionalArgs ? `, ${optionalArgs}` : ""
})`;
```

... could perhaps be replaced by:

```js
const result = `${operationName}(${
  requiredArgs && optionalArgs ? `${requiredArgs}, ${optionalArgs}` :
  requiredArgs ? requiredArgs :
  optionalArgs ? optionalArgs : ""
})`;
```

**Comment by marcoscaceres** [comment]
Option 1 would be my preference.

**Comment by tidoust** [comment]
Yes, I love option 1 too, all the more since I did not suggest any option 2 ;)
I prepared PR #3208 accordingly.

**Comment by sidvishnoi** [comment]
Fixed in https://github.com/w3c/respec/pull/3208
