### ISSUE TITLE
Add front matter publication history link

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/respec#3212]
W3C now maintains a history page for every /TR document's short name, at a url like `https://www.w3.org/standards/history/[spec short name]` for example https://www.w3.org/standards/history/ttml-profile-registry . I would like to be able to add that link to the front matter of W3C specs using Respec in place of the "previous link", for example as per the TTWG resolution at https://github.com/w3c/ttwg/issues/145#issuecomment-724863585.

Currently the only mechanism I can see to do it is as I did at w3c/tt-profile-registry#81, i.e. to add to "other links" e.g.:

```json
otherLinks: [{
            key: "Publication history",
            data: [{
              value: "https://www.w3.org/standards/history/ttml-profile-registry",
              href: "https://www.w3.org/standards/history/ttml-profile-registry"
            }]
          }]
```

That works, but puts the link below the Editors where the "previous version" link traditionally lived above the Editors.

I'd like a simple way to add the history to the front matter and have it go around the same place where Previous Version goes now.

**Comment by sidvishnoi** [comment]
I think it's a nice addition to ReSpec, and I think we should do this automatically as we already have the shortname.
It might better if we show it under the "latest published version"? Something like this maybe:
![image](https://user-images.githubusercontent.com/8426945/99248454-7915a380-282e-11eb-821e-03c843fd46f4.png)

**Comment by nigelmegitt** [comment]
Happy to have it automatically added, if that's what other groups would like. I'd prefer to have a separate History line myself, because at a quick glance that (history) link looks like part of the main URL, but such a URL doesn't work, right now anyway.

**Comment by marcoscaceres** [comment]
We could probably just add a bit more padding to "(history)" so it's easier to distinguish from latest published version URL. We'd also need to make sure PubRules doesn't get tripped up... it shouldn't, but just something to confirm.

**Comment by sidvishnoi** [comment]
Added in https://github.com/w3c/respec/pull/3795
