### ISSUE TITLE
The browser support feature shows incorrect data

### ISSUE THREAD

**Issue by jpmedley** [w3c/respec#3213]
I don't know how widespread this is. The Browser Support feature shows incorrect data on at least one spec. The Browser Support heading in the [manifest spec](https://w3c.github.io/manifest/)) shows support in Chrome as 89. If I hover over the label it expands to show Chrome support in 86 through 89. (I'm not sure why I thought to hover. There's no affordance suggesting that I should do that.) The underlying caniuse data appearts correct.

Chrome has actually supported [web app manifest since 39](https://www.chromestatus.com/feature/6488656873259008). There is a similar problem with the Chrome Android label.

![image](https://user-images.githubusercontent.com/8204171/99417318-a4d86e00-28ae-11eb-9b0e-dbf976d78256.png)

**Comment by saschanaz** [comment]
I guess the table currently focuses on latest versions rather than the history.

**Comment by sidvishnoi** [comment]
More context: https://github.com/w3c/manifest/issues/939

**Comment by sidvishnoi** [comment]
Fixed in https://github.com/marcoscaceres/respec.org/pull/159
