### ISSUE TITLE
Drop bits that talk about jQuery in documentation

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#3228]
The descriptions of [postProcess](https://respec.org/docs/#postProcess) and of [preProcess](https://respec.org/docs/#preProcess) in the doc still mention jQuery, which is no longer available in the w3c profile.

(via @wolenetz)

**Comment by tidoust** [comment]
I updated the corresponding Wiki pages: [`preProcess`](https://github.com/w3c/respec/wiki/preProcess) and [`postProcess`](https://github.com/w3c/respec/wiki/postProcess). The update on `preProcess` hasn't made it to the HTML documentation yet, but I suppose that's just a matter of propagation.

**Comment by sidvishnoi** [comment]
@tidoust Thanks for editing the docs! I've manually updated the HTML documentation.
