### ISSUE TITLE
.advisement box is inconsistent with other boxes

### ISSUE THREAD

**Issue by carmacleod** [w3c/respec#3233]
The ".advisement" box is the only "best practices" style box that has a border on the right.
This looks inconsistent when an advisement box is right beside another type of box.

See also: https://github.com/w3c/respec/pull/2340

The following screen snapshot from the ARIA Practices Guide shows a green "note" box immediately followed by an orange "advisement" box. See the extra border line on the right. None of the other "best practices" style boxes have that line.

![image](https://user-images.githubusercontent.com/3331913/100806969-75257c00-33ff-11eb-9b31-0898d424d2ca.png)

**Comment by sidvishnoi** [comment]
I think it should be discussed in tr-design, as it comes from https://w3c.github.io/tr-design/src/readme.html#advisement

**Comment by carmacleod** [comment]
Thank-you. I've opened https://github.com/w3c/tr-design/issues/231.
Closing this issue.
