### ISSUE TITLE
stop FOUC

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/respec#326]
when respec loads doc often there is a flash of unstyled content, would be nice if it did not occur

**Comment by marcoscaceres** [comment]
Note to future @marcoscaceres: if you combine all the styles into a single element, and insert it into the document on end-all, that will reduce the number of style recalculations significantly. Also, you should not insert styles that are not needed (e.g., if there is not WebIDL in the spec, then don't include the WebIDL styles... dummy). If we can move more stuff to base.css, then that is also a huge win.

**Comment by halindrome** [comment]
FWIW if there are easy ways to just rely on what is ALREADY in base.css that would be a huge win too.  In that we would have more consistency within and among specs.  Right @fantasai ?

**Comment by marcoscaceres** [comment]
> On 27 Jun 2016, at 10:10 PM, Shane McCarron <notifications@github.com> wrote:
> 
> FWIW if there are easy ways to just rely on what is ALREADY in base.css that would be a huge win too. In that we would have more consistency within and among specs. Right @fantasai ?
> 
We need to actually dig into ReSpec's style sheet and see what duplication there is. Base.css is unlikely to ever give us good syntax highlighting tho because we (ReSpec and BS) depend on different tools... But who knows. 

Maybe we can get consistent notes, warnings, tables, etc.  Those are the low hanging fruits.

**Comment by fantasai** [comment]
base.css intentionally doesn't include syntax highlighting rules. Definitely should be relying on it for styling tables, etc. -- anything documented in http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample really.

**Comment by marcoscaceres** [comment]
@fantasai, unrelated... but tables are still super broken :(

![screenshot 2017-02-14 16 00 57](https://cloud.githubusercontent.com/assets/870154/22915914/d37bc4e2-f2ce-11e6-8a78-c8f59755e66f.png)
