### ISSUE TITLE
Enum with no <dd> uses next <dt> instead.

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#329]
```html
<dl title="enum DeviceType" class="idl">
  <dt>computer</dt>
  <dt>phone</dt>
  <dt>mouse</dt>
</dl>
```
produces:

Enumeration|description
--------------|---------
computer|phone
phone|mouse 
mouse|

This is probably not high priority since specs shouldn't leave enums undocumented, but it came up while starting to draft the spec.

**Comment by marcoscaceres** [comment]
Won't fix, as we are no longer maintaining Ol' school WebIDL
