### ISSUE TITLE
Links to IDL entities should land on <section> describing the entity

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#330]
In the IndexedDB spec, `IDBRequest` links to https://dvcs.w3.org/hg/IndexedDB/raw-file/default/Overview.html#idl-def-IDBRequest. However, https://dvcs.w3.org/hg/IndexedDB/raw-file/default/Overview.html#h4_request-api contains introductory text that's useful in understanding the raw interface definition. It should be possible to cause `<a>IDBRequest</a>` to link to the section containing the IDL definition instead of the IDL definition itself.

**Comment by marcoscaceres** [comment]
The DFN should be set on the heading instead. As in:

```HTML
<section>
   <h2><dfn>Whatever</dfn> interface</h2>
    <pre class="idl">
    [Contructor]
    interface Whatever {};
    </pre>
</section>
```
And should happen automatically, where possible: #1050
