### ISSUE TITLE
Support linking to external xrefs

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#332]
It's important for specs to be able to deep-link into each other, but currently ReSpec doesn't look into the [`xrefs.json`](https://github.com/tobie/specref/blob/master/xrefs.json) database when resolving `<a>` links.
#223 mentions that this was discussed in http://lists.w3.org/Archives/Public/spec-prod/2012JulSep/thread.html#msg15.

**Comment by innovimax** [comment]
+1

**Comment by marcoscaceres** [comment]
Closed in favor of #1424
