### ISSUE TITLE
wgPatentURI deprecated but required

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#3344]
## Important info

- URL to affected spec: see description
- ReSpec version: 26.0.2
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

Respec documents that the "wgPatentURI" parameter is deprecation in favour of "group", and warns upon its use. But without that parameter present, it does not output a URI for the patent disclosures link.

* [Example without wgPatentURI](https://raw.githack.com/w3c/aria/d2ef211da85a48dd38d4f38ad87496efd49d8f76/index.html) - disclosures link is empty.
* [Example with wgPatentURI](https://raw.githack.com/w3c/aria/bd201631048d44e3a356b0e62ab130e7f06888ec/index.html) - disclosures link is correct, but Respec complains.

Expected behaviour: Respec behaves [as documented](https://github.com/w3c/respec/wiki/wgPatentURI) and puts in correct patent link based on the "group" parameter.

For purposes of this issue, ignore other Respec errors and warnings in those examples, they are related to the switch from respec-w3c-common to respec-w3c.

**Comment by sidvishnoi** [comment]
Hi. Looks like a configuration error in spec. `respecConfig.group` expects a group name ("aria") instead of a number (83726).

**Comment by marcoscaceres** [comment]
Hmm... @sidvishnoi, what if we also supported the numbers? Maybe could be a thing? It's not as nice as supporting the group aliases, but could be useful.

**Comment by sidvishnoi** [comment]
Can do, but not sure if we should support multiple ways to specify the same thing (leads to maintanence burden as well as confusion if not documented explicitly). Look at how many ways we support GitHub config.

**Comment by marcoscaceres** [comment]
I'm happy to stick with a string then. Closing this as answered.
