### ISSUE TITLE
<pre><code> pattern deviates from HTML

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#3349]
Followup after https://github.com/w3c/respec/issues/3189

## Important info

- URL to affected spec: examples/basic.html
- ReSpec version: Click the ReSpec pill in top-right corner (e.g., 25.12.0). develop branch
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:** It becomes `<pre class="def idl"><code>`

**Expected behavior (e.g., it shouldn't crash):** `<pre><code class="idl">` (Not sure about `def`)

But maybe okay? Not sure. cc @marcoscaceres and @foolip for Reffy.

**Comment by marcoscaceres** [comment]
@saschanaz, any chance of a PR for this one? Should be fairly quick. We probably don't need the "def"... I don't think we use that anywhere.

**Comment by saschanaz** [comment]
I tried it before opening this but it seems it's kinda needed for `position: relative` on `<pre>`. @sidvishnoi

**Comment by marcoscaceres** [comment]
If it proves annoying to change, I'd be inclined to leave this as is. It doesn't have any practical application in the browser or ReSpec itself, as far as I can tell.

**Comment by saschanaz** [comment]
Agreed, closing as there is no report that reffy is broken.
