### ISSUE TITLE
Missing link to respec-w3c-common

### ISSUE THREAD

**Issue by SteveALee** [w3c/respec#3360]
In coga/content-usable we use "respec-w3c-common.js" and I see many other documents do. 

However, I cannot find the source code anywhere. I can use the published version but it's not easy to read as it's been minimised.

I suggest a link is added to the 'respec ecosystem' section of the docs at a minimum.

**Comment by SteveALee** [comment]
Ah I now found a [depreciation note in the wiki](https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide)!

Such profiles need more of a mention in [the docs](https://respec.org/docs/)? Is see a mention under `xfref` but that is not how they are included in the examples I see.

**Comment by SteveALee** [comment]
OK so now I found it in `/develop/profiles`. GitHub search can be a pain. But profiles still need to be better documented IMHO.

**Comment by sidvishnoi** [comment]
Hi, profiles are documented in the [Developers Guide](https://github.com/w3c/respec/wiki/Developers-Guide). If you're looking for source code of `respec-w3c-common` and its plugins, they're in the now-defunct [w3c-common branch](https://github.com/w3c/respec/tree/w3c-common).
I would suggest to migrate to `respec-w3c` profile instead. It is the only "officially supported" profile. Let us know if you face any difficulties.

**Comment by SteveALee** [comment]
@sidvishnoi thank you. Could I suggest that profiles are also relevant to users in the user guide? At least knowing they exist and set a lot of behaviour? Plus a pointer to those provided?

I would provide a small PR but it seems to be in the wiki which AFAIK don't support PRs.

Now I am looking at the respec generated content is see the run-time depreciation warning too. Hah. The new one seem fine for now. thanks

**Comment by marcoscaceres** [comment]
Hi @SteveALee! Sorry about the confusion. For W3C stuff, there is only one profile (w3c). The other profiles are for other  consortia, so they wouldn't be of any use outside those institutions.  

I'll see if I can clarify that a bit in the docs.

**Comment by marcoscaceres** [comment]
Ok, added some details about profiles to the developer docs.
