### ISSUE TITLE
Minor errors in docs

### ISSUE THREAD

**Issue by SteveALee** [w3c/respec#3361]
- https://respec.org/docs/#structure "that were not covered as part of the very basics." what very basics? There's nothing earlier in the doc.
- https://respec.org/docs/#title-and-subtitle "As noted in the previous chapter" can;t find that either.

**Comment by marcoscaceres** [comment]
Thanks @SteveALee! I've rewritten the structure section and removed the confusing "As noted in the previous chapter,".
