### ISSUE TITLE
Trailing colon in "File a bug:" and "Commit history:"

### ISSUE THREAD

**Issue by andrea-perego** [w3c/respec#3362]
## Important info

- URL to affected spec: https://w3c.github.io/dxwg/dcat/
- ReSpec version: 26.1.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

Some of the links under "Participate:" (namely, "File a bug" and "Commit history") include a trailing colon that should not be present.

**Expected behavior (e.g., it shouldn't crash):**

They shouldn't have that colon.

**Optional, steps to reproduce:**

1.  ...

**Comment by marcoscaceres** [comment]
Ooooops! Sent a PR. Should be fixed later today. Thanks for letting us know, @andrea-perego!
