### ISSUE TITLE
"group" option still complains about patent policy

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#3399]
## Important info

- URL to affected spec: https://raw.githack.com/w3c/coga/42f963e1f8e0217ed26ae04ea8d5e816be4d8e75/content-usable/index.html
- ReSpec version: 26.4.0
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

Respec notes the use of deprecated configuration options and advises to replace with the "group" configuration. Doing so, however, triggers a new error "(w3c/headers): Invalid wgPatentPolicy value. Please use "PP2017" or "PP2020".". Following the link in the error message to https://respec.org/docs/#wgPatentPolicy, the documentation explicitly says "Note: If you're using the group configuration option, this is set automatically for you.".

**Expected behavior (e.g., it shouldn't crash):**

When using the "group" configuration, Respec should behave as documented and not require configuration options that are documented as unrequired.

**Optional, steps to reproduce:**

1.  ...

**Comment by sidvishnoi** [comment]
@marcoscaceres (If you see this before I wake up tomorrow): `conf.wgPatentPolicy` can be an array (of potentially different values). Need to support this at:
https://github.com/w3c/respec/blob/2ff1b146cca4cd8373c01868fb4353e8dd29a978/src/w3c/headers.js#L529-L534
https://github.com/w3c/respec/blob/387ab82d27049175ab7296770f3a3f7353b8bb45/src/w3c/templates/sotd.js#L247-L250

**Comment by dontcallmedom** [comment]
I would not bother with supporting multiple patent policies for joint work - there aren't so many joint deliverables in the first place, and I'm not sure it's well defined what would happen in that situation - certainly pubrules doesn't cover that case.

(I've checked that APA and AG are both under PP2017)

**Comment by marcoscaceres** [comment]
Yeah, multiple patent policies would be a bit of a nightmare scenario.

**Comment by marcoscaceres** [comment]
@sidvishnoi, let me know if you want to take this one, otherwise I'll get on to it tomorrow.
