### ISSUE TITLE
Documentation: export is no longer using shepherd

### ISSUE THREAD

**Issue by jnurthen** [w3c/respec#3430]
## Description of problem

https://github.com/w3c/respec/wiki/data-export is incorrect - according to https://github.com/w3c/aria-common/issues/48#issuecomment-789432527 the info on this page is out of date. Please update.

**Comment by marcoscaceres** [comment]
Fixed. Now talks about [Webref](http://github.com/w3c/webref/).

**Comment by marcoscaceres** [comment]
@dontcallmedom, do you want to have quick look at https://github.com/w3c/respec/wiki/data-export and see if there anything else we should say there?

**Comment by marcoscaceres** [comment]
Reopening... @dontcallmedom, please close this if you think it looks ok.

**Comment by dontcallmedom** [comment]
LGTM
