### ISSUE TITLE
Supporting definition aliases

### ISSUE THREAD

**Issue by beverloo** [w3c/respec#344]
As of now, defining a concept of "webapp" can be done using:
`<dfn>webapp</dfn>`

This enables us to use `<a>webapp</a>` when referring to it. However, when having to use the plural form, an explicit title attribute is needed on the anchor: `<a title="webapp">webapps</a>`.

An alternative would be to accept aliases for a definition, or, if we want to keep it limited, only an explicit plural. For example:

`<dfn data-aliases="webapps appz">webapp</dfn>`
`<dfn data-plural="webapps">webapp</dfn>`

It would remove some of the useless <a title> churn.

+@mvano

**Comment by halindrome** [comment]
I am planning to do a pull request that supports the basics of this soon - aliases and 'namespaces'.  We can look at the broader support for more of the bikeshed - like features in time.

**Comment by marcoscaceres** [comment]
closed via  #455
