### ISSUE TITLE
Add a link to specref with last-updated time

### ISSUE THREAD

**Issue by noamr** [w3c/respec#3440]
**Is your feature request related to a problem? Please describe.**
When working on several specs at the same time, it's hard to know when ReSpec catches the changes.

**Describe the solution you'd like**
In https://respec.org/xref/, have a link to the hourly updates of specref, or to wherever refs are coming from, with a "last updated" date (kind of like here https://www.specref.org)

**Describe alternatives you've considered**
State that the refs are coming from specref in the documentation... it takes a while to figure that out :)

**Can you or your organization fund the work or help with development?**
Sure, I can try to do that if the direction is agreed upon.

**Additional context**
Currently working on 7 specs at the same time with cross references (FETCH, Resource Timing, Navigation Timing, XHR, HTML, HR-TIME, Service workers). See https://github.com/whatwg/html/pull/6536#pullrequestreview-630117806

**Comment by marcoscaceres** [comment]
Good suggestion. @sidvishnoi, should we move this to the respec.org repo instead?

**Comment by tobie** [comment]
I want to point out here that the service handling cross-referencing (Shepherd) isn't the same as the service handling bibliographic references (Specref).

**Comment by noamr** [comment]
> I want to point out here that the service handling cross-referencing (Shepherd) isn't the same as the service handling bibliographic references (Specref).

So linking to both, and to any other source of data for ReSpec, would help :)

**Comment by marcoscaceres** [comment]
Note that we now use Reffy for our data (not Shepherd)... I know, the interdependencies are getting a bit crazy https://github.com/w3c/reffy
