### ISSUE TITLE
dfn.role=link containing a link

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3482]
## Important info

- URL to affected spec: https://w3c.github.io/webrtc-pc/ (if it were updated to ReSpec 26.6.0)
- ReSpec version: 26.6.0
- [x] I did a "hard refresh", but it's still busted.

## Description of problem
`<dfn data-cite=url>` generates markup à la `<dfn role=link><a href=url></a></dfn>` - I presume the `role=link` is for the definition panel, but it is not valid to have an element with `role=link` encompassing a link element.

**Comment by marcoscaceres** [comment]
Correct, yes...  was also looking into this. Presumedly, there shouldn't be any `<a>` inside a `<dfn>`, so need to check where those are happening.

**Comment by dontcallmedom** [comment]
it's the `<dfn data-cite>` which gets turned into `<dfn><a>` (which makes sense to me)

**Comment by marcoscaceres** [comment]
ah, yes... and those shouldn't have a panel! Got it. That's our friend #3254.

**Comment by dontcallmedom** [comment]
There is another case where this might happen (and where it's unclear how to fix it): `<dfn>Update the {{Bar}}</dfn>` (or in general, any definition that itself links to something else). Maybe this should create a span to wrap the non-link part of the definition content?

**Comment by marcoscaceres** [comment]
Yeah, that's not great usage. The correct thing to do there would be:

```
<dfn>Update the `Bar`</dfn>
```

But after chatting to @sidvishnoi, I think we will allow it as it provides clarity in what the spec editor is trying to express semantically there.

**Comment by sideshowbarker** [comment]
I ran into another case:

```html
<p>The <dfn>corresponding <a>input source state</a> type</dfn>
 for a label <var>action type</var> is given by the following table:
```
https://github.com/w3c/webdriver/blob/master/index.html#L7372-L7373

There are numerous instances of that in the source of the WebDriver spec.

There are also instances in the DOMParsing spec.

**Comment by marcoscaceres** [comment]
Ok, so now it's a matter of opinion (or validation, really). Given the new accessible `dfn`s are `role=link`s, we should probably disallow anchors inside `dfn`.

**Comment by marcoscaceres** [comment]
Been looking at various edge cases, and I think it might be easier to drop `role=link` for now. That will unblock various specs and we came come up with something more sane in the mean time.
