### ISSUE TITLE
Automatic link to sub-sections duplicate definition markup

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3486]
## Important info

- URL to affected spec: https://w3c.github.io/webrtc-pc/webrtc.html
- ReSpec version: 26.6.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem
The WebRTC spec uses automatic links to one of its subsection with `<a href="#rtcicetransport"></a>`.
This gets expanded with the full markup of the title of that section, including the `<dfn>` of the `RTCIceTransport` name (although as a `span dfn-type=interface` rather than a `dfn` element). That definition then gets wrapped into the dfn panel popup trigger - the panel never actually gets shown because the link takes precedence, but it doesn't make sense for the definition to be copied over, and with the latest accessibility improvements, it creates a situation where an element with `tabindex` gets embedded in a link, which the markup validator flags as an error.

**Comment by marcoscaceres** [comment]
Weird, the `dfn` shouldn't get copied over... as you state, it becomes a `span`. I'm trying to figure out the the rest and see if I can reproduce. This is markup that is generated:

<img width="1032" alt="Screen Shot 2021-04-28 at 3 54 24 pm" src="https://user-images.githubusercontent.com/870154/116353390-062b4280-a83a-11eb-870a-b73f1a39fa4a.png">


The span definitely shouldn't have the old attributes, so I'll fix that. 

However, I'm not seeing anything corresponding to the dfn panel. @dontcallmedom, can you help me understand a bit more what's going on? Or maybe the fix I sent in 26.6.2 fixed it?

**Comment by dontcallmedom** [comment]
This is the code that I see generated (even with 26.6.2):
```html
<a href="#rtcicetransport" class="sec-ref">§&nbsp;<bdi class="secno">5.6 </bdi>
          <span data-export="" data-dfn-type="interface" data-idl="interface" data-title="RTCIceTransport" data-dfn-for="" tabindex="0" role="link" aria-haspopup="dialog" title="Show what links to this definition"><code>RTCIceTransport</code></span> Interface</a>
```
I'm not sure why we're getting different results.

**Comment by marcoscaceres** [comment]
Oh, no matter. I see the bug clearly now! The span definitely shouldn't get any attributes anyway, so quick to fix. Thanks for helping clarify that @dontcallmedom!

**Comment by dontcallmedom** [comment]
While 26.6.4 copies fewer attributes, it still has some including `tabindex`:
```html
<a href="#rtcicetransport" class="sec-ref">§&nbsp;<bdi class="secno">5.6 </bdi>
          <span data-dfn-type="interface" data-title="RTCIceTransport" tabindex="0" aria-haspopup="dialog"><code>RTCIceTransport</code></span> Interface</a>
```

see also https://github.com/w3c/webrtc-pc/pull/2648/checks?check_run_id=2488488175

**Comment by marcoscaceres** [comment]
So, it's doing the right thing, but the markup of the WebRTC spec is now incorrect: the definitions shouldn't include links. I'll send a PR.

**Comment by dontcallmedom** [comment]
? No definition with links is involved here afaict

**Comment by marcoscaceres** [comment]
See https://github.com/w3c/webrtc-pc/pull/2649 ... I'm kinda torn between ReSpec auto-fixing this or if that is authoring error.

**Comment by dontcallmedom** [comment]
I think ReSpec already auto-fixes this ReSpec doing the right thing (per https://github.com/w3c/respec/issues/3482#issuecomment-827373233) - although it could do better by keeping the appropriate `<code>` formatting, possibly counting the reference, etc.

In any case, it is orthogonal to the problem I'm reporting which is not coming from a definition with a link in it :)

**Comment by marcoscaceres** [comment]
Ah, sorry, yes. I was sure this was fixed too, which is why I got confused.

**Comment by marcoscaceres** [comment]
Ok, https://github.com/w3c/respec/pull/3507 should hopefully fix this.

**Comment by marcoscaceres** [comment]
Sorry for the delay on this on @dontcallmedom. A few unrelated things changed which are causing CI to fail (so haven't been able to merge). I hope to have it sorted by tomorrow.
