### ISSUE TITLE
Respec generates wrong patent policy text for joint publication.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/respec#3494]
## Important info

- URL to affected spec: https://raw.githack.com/w3c/coga/Working-Group-Note-usable-2021-0429/snapshot/coga-usable/Overview.html#sotd

## Description of problem
When publishing a joint publication, pubrules is looking for the following paragraph in Status of This Document:
> ^This document was produced by groups operating under the( 15 September 2020| 1 August 2017)? W3C Patent Policy. ?(The groups do not expect this document to become a W3C Recommendation. ?)?$

**What happened (e.g., it crashed)?:**
respec only generates text 'The group does not...'
https://github.com/w3c/respec/blob/77ab0c7507d9960c50745dde954a87e199e2be81/src/w3c/templates/sotd.js#L262-L264

**Expected behavior (e.g., it shouldn't crash):**
If there're multiple groups (joint publication), generate 'The groups do not ...' instead.

cc @ruoxiran and @deniak .

**Comment by marcoscaceres** [comment]
Patch sent... will hopefully be fixed later today.
