### ISSUE TITLE
How to turn off the abbreviations feature?

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3514]
**Is your feature request related to a problem? Please describe.**

I don't know how to turn off the abbreviations feature.

**Describe the solution you'd like**

It would be useful if there's a configuration option or something to tell ReSpec not to wrap abbreviations with `<abbr>` automatically.

**Additional context**

For some documents, I only want to mark some (but not all) abbreviations, and their expansions are not the same (even though the abbreviations are the same). However, as far as I understand ReSpec can’t handle this because it will automatically wrap all matching abbreviations with `<abbr>` (and I don't know which expansion ReSpec will choose).

This feature request is currently mainly for the word "GB" in [clreq](https://w3c.github.io/clreq/). I just want to add `abbr` for the "main text" (like "GB-style" in [3.1.4](https://w3c.github.io/clreq/#prohibition_rules_for_line_start_end)), but not for the standard code (like "GB/T 15834-2011"). Even if we (the editors of the document) decide to add `abbr` to all instances of this abbreviation, since the expansions in each language are different, it is troublesome to edit when adding it. And if there is one place that we forget to add, the (automatically added) expansion may be wrong.

**Comment by marcoscaceres** [comment]
@xfq, sent https://github.com/w3c/respec/pull/3515 ... would excluding some abbr's be sufficient? 

Alternative would be to be more strict with matching.... like, excluding if there is a "/", but that gets tricky :(

**Comment by xfq** [comment]
> @xfq, sent #3515 ... would excluding some abbr's be sufficient?

Looks good to me. Thank you!

> Alternative would be to be more strict with matching.... like, excluding if there is a "/", but that gets tricky :(

I agree.
