### ISSUE TITLE
Missing 'p-org' hcard classes

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#3530]
## Important info

- URL to affected spec: https://w3c.github.io/media-playback-quality/
- ReSpec version: 26.6.6
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

The [source](https://github.com/w3c/media-playback-quality/blob/gh-pages/index.html) of this spec includes

```javascript
        editors: [
          {
            w3cid: 45389,
            name: 'Mounir Lamouri',
            company: 'Google',
          },
```

But the generated output has 
```html
<dd class="p-author h-card vcard" data-editor-id="45389"><span class="p-name fn">Mounir Lamouri</span> (Google) </dd>
```

Where the "Google" bit isn't marked up. [Another (Bikeshed) spec](https://www.w3.org/TR/media-capabilities/) has:

```html
<dd class="editor p-author h-card vcard" data-editor-id="45389"><span class="p-name fn">Mounir Lamouri</span> (<a class="p-org org" href="https://www.google.com/">Google Inc.</a>)
```

**Comment by jyasskin** [comment]
It's working correctly in https://w3c.github.io/media-source/, so it might be only when there's no `companyURL` field that would generate an element around the company name?

**Comment by marcoscaceres** [comment]
correct. Although, we could put a span around company name. Would that help?

**Comment by jyasskin** [comment]
Yep, and that's what Bikeshed does: https://w3c.github.io/webtransport/

```html
<dd class="editor p-author h-card vcard" data-editor-id="65611"><span class="p-name fn">Bernard Aboba</span> (<span class="p-org org">Microsoft Corporation</span>)
```
