### ISSUE TITLE
Tests `toBe(null)`, should use `toBeNull()`

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3538]
We have a lot of tests that use `toBe(null)`... but should use `toBeNull()`.

```
git grep "toBe(null)" tests
```

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue, Please assign me this issue.

**Comment by marcoscaceres** [comment]
Hi @himanshu007-creator, sure. Please feel free to take it.
