### ISSUE TITLE
Generation of 'ePub' format

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#355]
@iherman mentioned that it would be helpful to be able to transform a respec document into an "ePub" format document.  Seems difficult to do in a browser context.

**Comment by marcoscaceres** [comment]
We support this via a web service. We should only do it locally if there is more demand for it. We should talk to @iherman to see how many request per month his service is currently getting and for which specs etc. That will give us a better indication if we should move to supporting this locally.
