### ISSUE TITLE
Provide a flag to disable unitTestServer or integrationTestServer 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3566]
**Is your feature request related to a problem? Please describe.**
When testing, the dev server spins up multiple Karma instances. This is frustrating because they stack ontop of each other, making it difficult to debug tests.  

**Describe the solution you'd like**

It would be great to disable integration test or the unitTest server.

**Comment by sidvishnoi** [comment]
I wonder if we can modify karmaConfig to run both at once in devServer.

**Comment by marcoscaceres** [comment]
possibly, tough I don't mind them split up.
