### ISSUE TITLE
Support expansion of headings across specs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3589]
**Is your feature request related to a problem? Please describe.**
It's sometimes nice to reference particular sections of other specs. However, ReSpec doesn't support that unless one uses data-cite, which is fragile. 

**Describe the solution you'd like**
The ability to expand to headings across other specs, via `[[[spec#section-header]]]`. And have the section number and other details of the spec appear. 

E.g., [[css-flexbox-1#auto-margins]] could expand to:

```HTML
<a href="https://drafts.csswg.org/css-flexbox-1/#auto-margins">§8.1 Aligning with auto margins</a> of [[css-flexbox-1]]
```

Or 
```HTML
<a href="https://drafts.csswg.org/css-flexbox-1/#auto-margins">§8.1 Aligning with auto margins</a> of <cite>CSS Flexible Box Layout Module Level 1</cite>
```

**Comment by sidvishnoi** [comment]
Duplicate: https://github.com/w3c/respec/issues/2708

**Comment by marcoscaceres** [comment]
Thanks for finding the duplicate!
