### ISSUE TITLE
Referencing IDL Constants fails

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3590]
## Important info

- URL to affected spec: https://w3c.github.io/mediacapture-main/getusermedia.html (although the bug isn't visible there at the moment - see also https://github.com/w3c/mediacapture-main/issues/792#issuecomment-853124982)
- ReSpec version: 26.8.4
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**
{{HTMLMediaElement/HAVE_METADATA}} triggers a ReSpec error

**Expected behavior (e.g., it shouldn't crash):**
it should link to https://html.spec.whatwg.org/multipage/media.html#dom-media-have_metadata as [now recognized by xref](https://respec.org/xref/?term=HAVE_METADATA&for=HTMLMediaElement)

(I think, but haven't verified, that ReSpec only queries xref for attributes and dict-member, and so doesn't get constants)

**Comment by sidvishnoi** [comment]
Will update here when fix is released.

**Comment by sidvishnoi** [comment]
Released v26.8.8 🎉
