### ISSUE TITLE
`title` attr added to panel'd dfns is breaking Bikeshed

### ISSUE THREAD

**Issue by tabatkins** [w3c/respec#3592]
In <https://github.com/w3c/respec/commit/af110561953238cc7a0c33a42b3b7ddb32407b61> "fix(core/dfn-panel): make dfn panel keyboard accessible", you started adding a `title="Show what links to this definition"` to dfns with a panel.

This, unfortunately, interacts badly with Shepherd, the tool Bikeshed uses to scrape specs for definitions. Legacy specs often put linking text into the `title` attribute (for.... reasons, I guess), so when Shepherd is looking for a dfn's linking text, it first looks for the `data-lt` attribute, then falls back to the `title` attribute, then falls back to the text content.

This change, then, meant that suddenly every recently-updated ReSpec-generated spec is just, as far as Bikeshed is concerned, defining the phrase "Show what links to this definition" dozens of times. :( (You can see one example of a spec triggering this in <https://github.com/tabatkins/bikeshed-data/commit/70917352fecc809918ef8cc71492ea57df080293>.)

@plinss is on vacation this week, and so will be able to fix the heuristics to avoid this situation next week when he gets back, so it's possible this is simply a no-op on y'all's parts. 

However, this does raise the question of why this attribute is being added at all? To the best of my knowledge, current a11y expert advice is pretty consistently just "don't use the `title` attribute" - see <https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/> for example. In particular, this addition didn't seem related to keyboard accessibility at all, since you don't get a title popup when keyboard-focusing an element in any browser. Would it be reasonable to just revert that line?

**Comment by sidvishnoi** [comment]
Sent https://github.com/w3c/respec/pull/3593 as quick fix. 
Thanks for the "don't use `title`" advice. This was probably meant as a temporary _solution_.

**Comment by marcoscaceres** [comment]
Thanks for letting us know @tabatkins. It would be good to coordinate on a generic solution for the `dfn` panel. The ReSpec one makes a bunch of improvements over the original HTML one. Would be great to have some shared code for consistency there (and all-round better accessibility for dfns).

**Comment by marcoscaceres** [comment]
@tabatkins, @plinss, any chance you could tell me which specs are still polluting BikeShed/Shepherd's data with "Show what links to this" definitions? 

I can then go and republish them on TR so we get clean data again. We've republished Web Manifest and Media Capture already, but happy to do any others.

**Comment by plinss** [comment]
I don't see that in the spec DB at all anymore, so it looks like you got them all.
