### ISSUE TITLE
Support maplike declarations

### ISSUE THREAD

**Issue by ddorwin** [w3c/respec#361]
ReSpec fails with many errors and warnings when using the new maplike declaration (http://heycam.github.io/webidl/#idl-maplike) in an interface. The same is true for setlike.

For example:
  `<dt>readonly maplike &ltlong, DOMString&gt</dt>`
  `<dt>maplike &ltlong, DOMString&gt</dt>`

At a minimum, the above syntax should add the declaration in the interface's IDL. A bonus would be to provide information about the additional methods.

**Comment by yutakahirano** [comment]
http://webaudio.github.io/web-midi-api/ plans to use maplike, so I'm trying add the functionality.

**Comment by ddorwin** [comment]
@yutakahirano, Thank you for adding this!

While trying to use it, I noticed that a subsection named "Maplike" with the text from the `<dd>` element is added. The tests at https://github.com/w3c/respec/blob/develop/tests/spec/core/webidl.html demonstrate this. That text should probably be ignored or inserted into the main section.

I would also be nice to add something like the following from the EME spec:
>The readonly maplike declaration adds `entries`, `forEach`, `get`, `has`, `keys`, `values`, `@@iterator` methods and a size getter.

A nit: In the tests mentioned above, the referenced "hoge" and "fuga" are not used in the actual example.

**Comment by yutakahirano** [comment]
Thank you for the feedback.

> That text should probably be ignored or...

I need it, because I want to describe the key value of a maplike<DOMString, V>, as in the example. Just DOMString is not enough.

> ...inserted into the main section.

I created a [branch] (https://github.com/yutakahirano/respec/tree/maplike-update) to update the description. What do you think about it?

> I would also be nice to add something like the following from the EME spec:

>> The readonly maplike declaration adds entries, forEach, get, has, keys, values, @@iterator methods and a size getter.

I added the description in the branch but I'm not sure if it should be inserted automatically or by hand (by each spec author).

**Comment by ddorwin** [comment]
Thanks. The branch looks good, though I'd have to see the output to be sure.

I think it makes sense to automatically add the text since it will always be accurate and doing so ensures specs are consistent and correct. Are there cases where you think the author might want to modify it?

**Comment by yutakahirano** [comment]
> I think it makes sense to automatically add the text since it will always be accurate and doing so ensures specs are consistent and correct. Are there cases where you think the author might want to modify it?

OK, then let's generate the description.
By the way, I think using links could be helpful and [made another change](https://github.com/yutakahirano/respec/commit/0ad764403f99b1a509abd996209bf2e5726f2461) for the branch. Do you think it is a good change? A readers can easily check what "maplike" is, but each spec author should provide &lt;dfn id="maplike"&gt;...&lt;/def&gt; as I did in webidl.html.

**Comment by ddorwin** [comment]
>By the way, I think using links could be helpful and made another change for the branch. Do you think it is a good change? A readers can easily check what "maplike" is, but each spec author should provide &lt;dfn id="maplike"&gt;...&lt;/dfn&gt; as I did in webidl.html.

My thoughts as a user of ReSpec are below. I would defer to the maintainers, though.

Although maplike is a bit complex and a link would be nice, I think we should be consistent with other Web IDL types and markup. For example, we don't link to BufferSource, which is not obvious, or Promise. Also, Terminology/Definitions sections usually contain terms specifically relevant to the spec.

I would actually be fine with linkifying all such types in the IDL, but that would be a separate task.

Another option would be to linkify the text about the additional methods and point directly to the Web IDL spec. (There may be some issues with pointing at an ED that specs would have to address.)

Also, if any links are automatically added, they may need to be followed by [[!WebIDL]].

**Comment by yutakahirano** [comment]
OK, I reverted the last commit.

**Comment by ddorwin** [comment]
The changes for maplike pushed to ReSpec in the last day have a couple bugs, one of which causes a warning on http://validator.w3.org/.

Bug 1 - Validator warning:
>`Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.
From line 1719, column 16; to line 1719, column 82
pan></pre><section typeof="bibo:Chapter" resource="" property="bibo:hasPart"><p>Thi`

It appears that the `This interface has "entries"...` text is in a section without a header. I think it's probably fine as a paragraph.

Bug 2 - `“get”` is missing from the list of methods.

For discussion: I wonder whether it makes sense to use `<code>has</code>` rather than `"has"`.

**Comment by yutakahirano** [comment]
Thanks for reporting this.

> Bug 1 - Validator warning:
> 
>> Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections. From line 1719, column 16; to line 1719, column 82 pan&gt;&lt;/pre&gt;&lt;section typeof="bibo:Chapter" resource="" property="bibo:hasPart"&gt;&lt;p&gt;Thi

> It appears that the This interface has "entries"... text is in a section without a header. I think it's probably fine as a paragraph.

Can you tell me how to get the message, please?

> Bug 2 - “get” is missing from the list of methods.
>

Ah, sorry, I will fix it.

> For discussion: I wonder whether it makes sense to use <code>has</code> rather than "has".

What do you think about @@iterator, then?

**Comment by ddorwin** [comment]
> Can you tell me how to get the message, please?

If you generate a file that uses maplike and upload it to a server, you can check it at http://validator.w3.org/. If you pushed a Web MIDI update, you can check it at this URL: http://validator.w3.org/nu/?doc=http%3A%2F%2Fwebaudio.github.io%2Fweb-midi-api%2F

>>For discussion: I wonder whether it makes sense to use `<code>has</code>` rather than "has".

>What do you think about @@iterator, then?

If I understand correctly, that's a binding detail and does not effect the methods. I suggested using `<code>` because it would match other methods in specs. I don't know whether that is the correct way to document this, though. That's why this comment is for discussion. :)

**Comment by yutakahirano** [comment]
>> Can you tell me how to get the message, please?

> If you generate a file that uses maplike and upload it to a server, you can check it at http://validator.w3.org/. If you pushed a Web MIDI update, you can check it at this URL: http://validator.w3.org/nu/?doc=http%3A%2F%2Fwebaudio.github.io%2Fweb-midi-api%2F

Thanks.

>> For discussion: I wonder whether it makes sense to use <code>has</code> rather than "has".

>> What do you think about @@iterator, then?

> If I understand correctly, that's a binding detail and does not effect the methods. I suggested using &lt;code&gt; because it would match other methods in specs. I don't know whether that is the correct way to document this, though. That's why this comment is for discussion. :)

It does. You can get the iterator function by `maplike[Symbol.iterator]`.

**Comment by marcoscaceres** [comment]
Looks like there is nothing else left to be done here.
