### ISSUE TITLE
Not super helpful error messages

### ISSUE THREAD

**Issue by anssiko** [w3c/respec#3635]
pr-push.yml fails with:

```
 Document on track but no previous version.
        Plugin: w3c/headers
          Hint: Add [previousMaturity](https://respec.org/docs/#previousMaturity) and [previousPublishDate](https://respec.org/docs/#previousPublishDate) to ReSpec’s config.
```
via https://github.com/w3c/device-posture/runs/2727557242?check_suite_focus=true

@xfq

**Comment by anssiko** [comment]
I was actually reacting to "publishing to TR more than once per day fails" case. I was wondering if spec-prod could detect that and warn the operation might fail, if that's the case. Optimally, it wouldn't fail.

**Comment by marcoscaceres** [comment]
> "publishing to TR more than once per day fails" case.

Ah, it does report a fail, but the errors are also quite cryptic:
https://github.com/w3c/spec-prod/issues/82

**Comment by sidvishnoi** [comment]
> publishing to TR more than once per day fails

That shouldn't be happening. It's probably some other bug where spec-prod didn't set right right respecConfig. Will investigate.

**Comment by marcoscaceres** [comment]
We did a bunch of work on this in #3637. Closing for now and we can fix up any specifically unhelpful ones.
