### ISSUE TITLE
My respec suddenly looked different: the themeing did not work any more

### ISSUE THREAD

**Issue by sabinem** [w3c/respec#3645]
## Important info

- URL to affected spec: https://www.dcat-ap.ch/releases/2.0/dcat-ap-ch.html
- ReSpec version: Click the ReSpec pill in top-right corner (e.g., 25.12.0). I don't see that pill any more
- [x] I did a "hard refresh", but it's still busted.It happend to me in all environment: on my PROD, TEST and LOCAL environments

## Description of problem

**What happened (e.g., it crashed)?:** All of a sudden the respec formatting was gone

**Expected behavior (e.g., it shouldn't crash):** Before all my respec looked like a normal respec specification

**Optional, steps to reproduce:**

1. just look at the url given above: what is wrong there? I did not redeploy and yesterday it looked normal. Today it looks like the bare text, with the respec formatting mostly gone. Please help me understand what happend. Other respecs that I normally use for reference also look different today: https://www.w3.org/TR/vocab-dcat-2/ gets a 503, https://ec-jrc.github.io/dcat-ap-jrc/ also doe not look normal.

**Comment by sidvishnoi** [comment]
Hi. ReSpec scripts/styles are hosted on W3C and W3C servers are down at the moment. I'll update here when server is up again.

**Comment by sabinem** [comment]
Thank you very much for your reply. It is good to know that it is a server problem and will wait for an update then.

**Comment by sidvishnoi** [comment]
Servers are back up and all is good again 🎉

**Comment by sabinem** [comment]
@sidvishnoi Sorry for contacting you again, but do you have any experience on how often and long the W3C server is usually down. This weekend it has been down for hours on Saturday and again for hours on Sunday. Now it is down again. Is it usually so unreliable? Or has this just been an exceptional weekend? What are you experience with this? And do you have any suggestions on how to deal with this? Caching?

**Comment by sidvishnoi** [comment]
It's unusual for W3C servers being down (and for that long). I'm a volunteer here, so I am not aware of what's happening on server.

> And do you have any suggestions on how to deal with this? Caching?

Nothing in the short term unfortunately. For ReSpec, we'll try to make all Respec scripts self-hosting/CDN friendly (i.e., independent of W3C hosting). Currently, you can access the respec-w3c profile at https://w3c.github.io/respec/builds/respec-w3c.js, but as some W3C hosted scripts/styles are hard-linked in it (like [base.csss](https://www.w3.org/StyleSheets/TR/2016/base.css), [fixup.js](https://www.w3.org/scripts/TR/2016/fixup.js), [respec-highlight.js](https://www.w3.org/Tools/respec/respec-highlight)), so it's not much use.

The best solution here would be for organizations to create/maintain their own profiles, so each organization can include scripts/styles/logos hosted at their own servers. In fact, I would encourage opendata-swiss to create a custom ReSpec profile. We currently help maintain [4 profiles](https://github.com/w3c/respec/tree/develop/profiles) within this repo. Let us know if you'd like to create a new profile, and we'll help you in the PR (see https://github.com/w3c/respec/pull/3543 for example).

**Comment by marcoscaceres** [comment]
@sabinem, sorry for the issues. There were some infrastructure problems over the weekend outside our control. As @sidvishnoi mentioned, it's indeed quite rare that the whole w3c would go down.

**Comment by sabinem** [comment]
@marcoscaceres @sidvishnoi Thank you very much for getting back to me. That is good to know, that this weekend was exceptional. Also thanks for the suggestions. We might consider this at some point in the future.

**Comment by marcoscaceres** [comment]
Great! And yes, the fallback option should be fairly easy to set up. 

If working on it locally, other option is to `npm install` ReSpec into your project... however, to be honest, I've help maintain ~100 ReSpec specs for about 10 years and never found the need to do that.

**Comment by marcoscaceres** [comment]
Details about what happened https://www.w3.org/2003/08/system-status.html
