### ISSUE TITLE
Allow using `class=` for data-* attribute things 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3653]
**Is your feature request related to a problem? Please describe.**
Having to write `data-*` for many things is no fun. 

**Describe the solution you'd like**
It would be good use `class=` where possible:

Like:
```HTML
   <dfn class="exported event">change</dfn>
```
Would become
```HTML
   <dfn data-exported="" data-dfn-type="event">change</dfn>
```

**Comment by sidvishnoi** [comment]
Closed via #3704
