### ISSUE TITLE
Missing W3C Logo for notes

### ISSUE THREAD

**Issue by iherman** [w3c/respec#3715]
## Important info

- URL to affected spec: https://w3c.github.io/epub-specs/epub33/tts/?specStatus=FPWD-NOTE&publishDate=2021-08-03
- ReSpec version: 26.9.4.
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened ?**

The W3C logo is not generated to the upper right hand corner of the page for WG Notes (FPWD or not). Consider

https://w3c.github.io/epub-specs/epub33/tts/?specStatus=FPWD-NOTE&publishDate=2021-08-03

as opposed to, e.g.,

https://w3c.github.io/epub-specs/epub33/tts/?specStatus=WD&publishDate=2021-08-03

**Expected behavior (e.g., it shouldn't crash):**

Add the logo :-)

**Comment by marcoscaceres** [comment]
Oops. Will fix that tomorrow (if not earlier)!
