### ISSUE TITLE
Make respec include RDFa attributes only as an opt-in

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#374]
Respec should be changed so its output doesn't contain RDFa attributes by default but instead only as an opt-in for those authors who want RDFa included and who actually use it for something themselves.

Especially, RDFa shouldn't be hardcoded into respec output without even giving authors a choice to opt out of it, and without regard to whether particular authors actually want RDFa in their documents or not.

### Rationale
The absence of RDFa in any respec document isn't going to break anything. There is no system that depends on all W3C specification markup consistently including RDFa, and there is no W3C policy requirement that specification markup must include RDFa. In fact, other preprocessors like Bikeshed and Anolis don't generate RDFa at all, but their output still works fine with W3C pubrules and other tools.

Further, RDFa is not needed by browsers for rendering purposes or for any other processing purposes, and also not needed by AT and in fact its presence in respec-generated documents has caused some problems in practice for AT users of those documents, as described in https://github.com/w3c/respec/issues/370

In addition to those problems, the RDFa attributes cause a large number of "unknown attribute" errors to be reported by HTML checking tools; in particular by https://validator.nu/ and https://html5.validator.nu/ and by all non-W3C instances of checking tools based on the `validator.nu` code.

The root element of every single document generated by respec looks something like this:

`<html lang="en" dir="ltr" typeof="bibo:Document w3p:PR" about="" property="dcterms:language" content="en">`

In https://validator.nu/ and other checkers, that immediately generates two errors: one for the `about` attribute and one for the `content` attribute. And that's just for the very first element in the document.

One big problem with that is, authors can't fix those problems themselves by editing the (pre-processed) source of their own documents. First, most authors probably won't even initially realize what those attributes are or how they got there. But once they figure out that respec added them, they still have no practical option for dealing with the problem except to manually editing the generated output.

And while they're doing that, those authors are likely to notice that `property="dcterms:language" content="en"` is simply repeating semantic information that's already provided by the native HTML `lang="en"`. And next they're likely to wonder what information purpose the seemingly pointless empty `about=""` attribute is actually meant to serve (and they're likely to keep wondering that as they later find and remove multiple instances of `about=""` in other elements), or, just a little further into the beginning of the document, the empty `datatype=""` they'll find in the `section` element for the Abstract. 

So, authors who use respec should have a reasonable expectation that their documents won't cause errors to be reported by https://validator.nu/ which they're not themselves responsible for, which they don't themselves understand, and which they can't themselves readily fix.

But we can completely avoid that scenario by changing the respec behavior so that RDFa only gets added to documents when authors intentionally opt-in to it, based on them actually having some understanding of what RDFa is for and valuing it enough to actually choose to have it in their documents rather than being forced into having it in their documents.

Their only choice otherwise is to quit using respec altogether, which I'd think is something the people who are putting time into developing respec and who'd like it to be useful would rather didn't have to happen.

**Comment by marcoscaceres** [comment]
This was fixed, right @halindrome? I see code that checks for the RDFa config option  in various places? 

Please reopen if not fixed.
