### ISSUE TITLE
Protect against injected code?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#3743]
I have no idea whether this is doable or not.

By a pure coincidence, I ran into a similar problem with two different browsers. Both on my local Safari and Brave browsers, when I generated an HTML, it resulted in invalid HTML. In both cases it turned out that an extension injected some code into the generated HTML which made it invalid. 

In the case of Brave, the presence of the  ["WOT Website Security & Browsing Protection"](https://chrome.google.com/webstore/detail/wot-website-security-brow/bhmmomiinigofkjcapegjjndpbikblnp) resulted in the following:

```
<link rel="stylesheet" href="https://www.w3.org/StyleSheets/TR/2016/W3C-WG-NOTE.css"></head>
<span id="warning-container"><i data-reactroot=""></i></span>

<body class="h-entry">
```

In the case of Safari it was a different extension (["Grammarly for Safari"](https://apps.apple.com/us/app/grammarly-for-safari/id1462114288?mt=12)) that injected a small snippet with some custom elements (that HTML was valid, but pubrules checker, understandably, objected).

Of course, it is possible to solve these two particular cases (I disabled/removed both extensions) but it took a long time to get there from what were pubrules checker errors. Hence the question: is it possible for the respec HTML generator to counteract such injection attempts? To be honest I have no idea when and how these types of injections happen in a browser and whether respec can catch this, to it may be lost cause... 

cc @OR13

**Comment by marcoscaceres** [comment]
Unfortunately, extension that can manipulate the DOM can basically inject anything. ReSpec can’t really detect those kinds of changes. 

When generating a document, it’s safest to do it from the command line.

**Comment by iherman** [comment]
> Unfortunately, extension that can manipulate the DOM can basically inject anything. ReSpec can’t really detect those kinds of changes.

I was afraid of this :-(

> 
> When generating a document, it’s safest to do it from the command line.

Ah. To be honest, I did not even realize you can use respec from command line. But now I know! (Found the [reference in the manual](https://respec.org/docs/#using-command-line).)
