### ISSUE TITLE
Remove "gh-pages" from Commit history in Participate

### ISSUE THREAD

**Issue by siusin** [w3c/respec#3748]
## Important info

- URL to affected spec: https://w3c.github.io/virtual-keyboard/
- ReSpec version: 26.13
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?: 
https://github.com/w3c/virtual-keyboard/commits/gh-pages will return 404 because we are using main as the released branch.

**Expected behavior (e.g., it shouldn't crash):
https://github.com/w3c/virtual-keyboard/commits/ should be good enough.

**Optional, steps to reproduce:

1.  add `github: "w3c/virtual-keyboard"` to `respecConfig`.

**Comment by marcoscaceres** [comment]
Hi @siusin! 

I think you might want to change:

```JS
gitHub: "w3c/virtual-keyboard"
```

To:

```Js
 github: {
    repoURL: "w3c/virtual-keyboard",
    branch: "main",
  },
```

And hopefully that should fix it! 🙏 More details: 
https://respec.org/docs/#github

Let me know if that works!

**Comment by sidvishnoi** [comment]
The branch name in commits list in GitHub is not required: by default, /commits lists commits in default branch.
We've historically used gh-pages as we hosted ReSpec docs directly on GitHub pages, but I think it should no longer be needed.
I think we should remove the branch name from the URL if user doesn't provide it explicitly.

**Comment by siusin** [comment]
Good to know, thanks @marcoscaceres !

Agree with @sidvishnoi , it'd be nice to remove gh-pages since most of our repos no longer use it as the released branch.
