### ISSUE TITLE
Typo in appendix docs

### ISSUE THREAD

**Issue by kaelig** [w3c/respec#3777]
👋🏻 In https://github.com/w3c/respec/wiki/appendix, there's a missing `/` in the closing `h2`:

```diff
<section class="appendix">
-   <h2>Acknowledgements<h2>
+   <h2>Acknowledgements</h2>
  <p>This spec would not be possible without...</p>
</section>
```

**Comment by sidvishnoi** [comment]
Thanks! Fixed in https://github.com/w3c/respec/wiki/appendix/58204a52a5d6e40da474b19e696817ad498025d4
