### ISSUE TITLE
core/inlines could use Ranges

### ISSUE THREAD

**Issue by darobin** [w3c/respec#378]
It wasn't an option when the original code was written because Range support was too flimsy, but it is much better now. I think that instead of doing what it is doing now which involves creating a DocumentFragment for all matching Text nodes, building the content inside, and replacing the Text node in its parent (which I'm guessing isn't fast) we could likely use `surroundContents()` instead. Low priority but worth investigating.

**Comment by marcoscaceres** [comment]
I looked into this a bit... I'm not convinced. Using DocumentFragment is fine.
