### ISSUE TITLE
Example id's should not include the example number

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#3784]
e.g. example-2-foooo, this is because if a new example is added, the IDs all change.

**Comment by xfq** [comment]
FWIW, when the spec editor does not specify an ID for an example, Bikeshed uses the hash of the example to [generate an ID](https://github.com/tabatkins/bikeshed/blob/8bb502091c0fa6a322c3b402ca297bf382715ecd/bikeshed/unsortedJunk.py#L1107). This is also a way to prevent ID changes.
