### ISSUE TITLE
The title of the generated document is inconsistent with the original title

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3798]
## Important info

- URL to affected spec: https://w3c.github.io/clreq/
- ReSpec version: 26.13.4
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

The `title` of the static HTML document generated by ReSpec is not the same as the original `title` of the document.

The [title](https://github.com/w3c/clreq/blob/3384e9a8747baa2b5b0703a0041465c528f1cdd8/index.html#L5) of https://w3c.github.io/clreq/ is "Requirements for Chinese Text Layout - 中文排版需求", but in the generated HTML it is "Requirements for Chinese Text Layout中文排版需求", and Pubrules reports an error:

> Content of title and h1 do not match. Text of title is 'Requirements for Chinese Text Layout中文排版需求' while h1 is (transformed into) 'Requirements for Chinese Text Layout - 中文排版需求'.

**Expected behavior (e.g., it shouldn't crash):**

ReSpec should probably not modify the `title` of the document.

**Optional, steps to reproduce:**

1. Open https://w3c.github.io/clreq/
2. Generate a static HTML document
3. Open the document and view the `title` of the document

**Comment by xfq** [comment]
I took a look at the cause of the problem, and it seems to be because ReSpec and Specberus have handled the h1/title of the document inconsistently:

* https://github.com/w3c/respec/blob/77ab0c7507d9960c50745dde954a87e199e2be81/src/core/title.js#L64
* https://github.com/w3c/specberus/blob/7873269809561965744b8e6ec6298815080e2399/lib/rules/headers/h1-title.js#L17-L21

**Comment by marcoscaceres** [comment]
Hmm... I see, but the `<br>` handling seems very arbitrary in Specberus. We could do the same thing in ReSpec, but seems  very fragile. If that's convention and we can't fix it some other way, we can do it.

**Comment by xfq** [comment]
> Hmm... I see, but the `<br>` handling seems very arbitrary in Specberus. We could do the same thing in ReSpec, but seems very fragile. If that's convention and we can't fix it some other way, we can do it.

I'm not sure if there is a convention or a better way to fix it. Maybe @deniak knows more.

**Comment by deniak** [comment]
From https://www.w3.org/pubrules/doc/rules/?profile=WD#title, pubrules transforms:
* `:<br>` with `: `
* `<br>` with ` - `

So for that specific document, pubrules expects the title to be "Requirements for Chinese Text Layout - 中文排版需求"

**Comment by marcoscaceres** [comment]
I sent a PR that mirrors pubrules. 

Just thinking out loud: an alternative way might have been to use CSS to hide ”:” and add a line break.
