### ISSUE TITLE
Broken style for FPWD

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3861]
## Important info

- URL to affected spec: https://xfq.github.io/testing/miniapp-packaging-WD/index.html
- ReSpec version: 27.0.5
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

After exporting [this document](https://xfq.github.io/testing/miniapp-packaging-WD/index.html) into HTML, it contains a link to https://www.w3.org/StyleSheets/TR/2021/W3C-FPWD , which is 404.

**Expected behavior (e.g., it shouldn't crash):**

The link shouldn't be broken. Maybe it should be https://www.w3.org/StyleSheets/TR/2021/base.css ? I'm not sure.

**Comment by xfq** [comment]
cc @plehegar @deniak

**Comment by marcoscaceres** [comment]
having a look...

**Comment by marcoscaceres** [comment]
I think it should be:
https://www.w3.org/StyleSheets/TR/2021/W3C-WD

**Comment by marcoscaceres** [comment]
I think there is some copy/pasta in the "W3C-WD" stylesheet:

```
/* Style for a "Working Group Note" */
```

**Comment by deniak** [comment]
> I think there is some copy/pasta in the "W3C-WD" stylesheet:
> 
> ```
> /* Style for a "Working Group Note" */
> ```

I made a PR to fix those: https://github.com/w3c/tr-design/pull/265.

And yes, the stylesheet expected for FPWD is https://www.w3.org/StyleSheets/TR/2021/W3C-WD
