### ISSUE TITLE
respecConfig.github documentation does not match output

### ISSUE THREAD

**Issue by rakuco** [w3c/respec#3863]
https://respec.org/docs/#github says

> It also adds an object to otherLinks for under "Participate", with the appropriate links to your GitHub repository.

While that does seem to be true when I look at src/core/github.js, just setting `respecConfig.github` does not seem to render the "Participate" section. On the other hand, a section called "Feedback" with the appropriate links to the GitHub repository is rendered by src/w3c/templates/headers.js, but this is not documented.

**Comment by sidvishnoi** [comment]
This was recently changed to incorporate W3C 2021 Process.

**Comment by marcoscaceres** [comment]
Fixed. Added "Feedback" and screenshot.
