### ISSUE TITLE
Pubrules errors with notes

### ISSUE THREAD

**Issue by mattgarrish** [w3c/respec#3868]
In addition to the problem about the `open` attribute reported in #3867, when trying to re-publish notes I'm also getting new errors about missing style sheets, status sections, patent policy, etc.

```
Specberus Errors:
    Failed to include logo in link with absolute URLs.
      { name: 'headers.logo', section: 'front-matter', rule: 'logo' }
    The &lt;details&gt; element in the header should have attribute "open".
      {
        name: 'headers.details-summary',
        section: 'front-matter',
        rule: 'docIDFormat'
      }
    Missing W3C TR style sheet "https://www.w3.org/StyleSheets/TR/2021/W3C-NOTE".
      { name: 'style.sheet', section: 'metadata', rule: 'goodStylesheet' }
    No stability warning paragraph.
      {
        name: 'sotd.stability',
        section: 'document-status',
        rule: 'stability'
      }
    Required patent policy paragraph not found. Expected text related to patent policy requirements: <blockquote>The 1 August 2017 W3C Patent Policy does not carry any licensing requirements or commitments on this document.</blockquote>
      { name: 'sotd.pp' }
    This resource or link found in document (https://www.w3.org/StyleSheets/TR/2021/W3C-WG-NOTE) is not responding ok (404 ). Please install it correctly.
      {
        name: 'links.linkchecker',
        section: 'compound',
        rule: 'compoundFilesLocation'
      }
```

Some examples of failed runs with these errors:

- https://github.com/w3c/epub-specs/runs/4139739098?check_suite_focus=true
- https://github.com/w3c/epub-specs/runs/4139881057?check_suite_focus=true
- https://github.com/w3c/epub-specs/runs/4139880922?check_suite_focus=true

I was getting a warning about switching the status from "WG-NOTE" to "NOTE", but doing that didn't help.

**Comment by marcoscaceres** [comment]
Thanks @mattgarrish. Having a look now...

**Comment by marcoscaceres** [comment]
After #3869, I think it works now... I re-ran the last action and it published. 

I see you fixed the "WG-NOTE" issue already.

**Comment by mattgarrish** [comment]
Sorry, the last action was a test of a specification to see if the issue was limited to notes. The specifications are working now that the open attribute is fixed, but for notes I'm still getting these errors about a missing stability warning paragraph and a required patent policy (see https://github.com/w3c/epub-specs/actions/runs/1439248365):

```
  Specberus Errors:
    No stability warning paragraph.
      {
        name: 'sotd.stability',
        section: 'document-status',
        rule: 'stability'
      }
    Required patent policy paragraph not found. Expected text related to patent policy requirements: <blockquote>The 1 August 2017 W3C Patent Policy does not carry any licensing requirements or commitments on this document.</blockquote>
      { name: 'sotd.pp' }
  
  Details: https://labs.w3.org/echidna/api/status?id=c537322b-3f5c-4ee9-a2e4-60ac9fc26eb6
  💥 Echidna publish has failed.
```

I don't know what the stability warning paragraph is, but I thought the patent policy was included automatically from the `group` setting. Does something need to be fixed in the group's metadata for that one?

**Comment by marcoscaceres** [comment]
@mattgarrish do you have a link to the editor's draft by chance? That helps me with debugging.

**Comment by marcoscaceres** [comment]
@deniak, question for you: the W3C API is telling ReSpec that this group ("epub") is operating under the 2020 policy. However, Specberus seems to think they are on "pp2017"? 

Could it be that the "sotd.pp" rule is outdated in expecting the text "1 August 2017"? Or is something else wrong?

**Comment by deniak** [comment]
I can confirm the EPUB 3 WG is operating under PP 2020 so there must be a bug in pubrules.
Do you have the link to the specification you are testing so I can investigate?

**Comment by deniak** [comment]
Never mind, I'll look at the GH action logs

**Comment by marcoscaceres** [comment]
Just in case http://localhost:8000/docs/a11y-faq/?specStatus=NOTE

**Comment by deniak** [comment]
So digging more into it, I no longer get the patent policy error while checking the snapshot sent to Echidna. We did release a new version of pubrules yesterday containing a few fixes @jennyliang220 made.
The only error left is the stability paragraph:
```
No stability warning paragraph. Expected text:
    Group Notes are not endorsed by W3C nor its Members.
```

The sentence generated by respec is slightly different:
```
Publication as a Group Note does not imply endorsement by W3C and its Members. 
```

**Comment by marcoscaceres** [comment]
Ok, easy. Will fix! Thanks @deniak.
