### ISSUE TITLE
ReSpec Template for Pandoc ?

### ISSUE THREAD

**Issue by akuckartz** [w3c/respec#387]
Has anyone created a template for Pandoc (http://johnmacfarlane.net/pandoc/) or is otherwise using Pandoc to create ReSpec documents? Anybody interested in that?

**Comment by darobin** [comment]
I don't believe anyone has done that, but it certainly would be a nice thing to have!

**Comment by marcoscaceres** [comment]
closing.

**Comment by akuckartz** [comment]
Why was this closed?

**Comment by marcoscaceres** [comment]
I'm not sure we need it, tbh. I think the community is happy with the current tool chain. However, if you want to have a go a making it and sending a PR, it could be good.
