### ISSUE TITLE
typo: To you can use...

### ISSUE THREAD

**Issue by jonassmedegaard** [w3c/respec#3880]
https://respec.org/docs/#sections contains a note box:
> To you can use ...

The initial "To" seems a leftover from some rephrasing.

**Comment by sidvishnoi** [comment]
Fixed in [wiki](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide/_compare/f7b0b124cba1360ee7355d06d6a9efa4c5c8081e...68fb85dbce0233186eec3761175e57b67c4e5fee). Thanks for reporting!
