### ISSUE TITLE
typo: Subsetion

### ISSUE THREAD

**Issue by jonassmedegaard** [w3c/respec#3881]
https://respec.org/docs/#sections contains in its example code and rendered output this string:
> Subsetion text

A "c" is missing - should instead be "Subsection text".

**Comment by sidvishnoi** [comment]
Thanks! Fixed in [wiki](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide/_compare/eb24cd350a7d970889e6c91efe6c73a956746765...f7b0b124cba1360ee7355d06d6a9efa4c5c8081e)
