### ISSUE TITLE
Permalinks get messed up "content" attribute if heading text has special characters

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#389]
Example: https://rawgit.com/w3c/coga/master/user-research/index.html

There are headings in this document that have apostrophes in them, e.g., "Description of Alzheimer's". Heading text is used to populate various attributes including id and title. In most cases, the apostrophe is converted to a hyphen, so for instance, you get id="h-description-of-alzheimer-s". However, for the permalink there is a that has messed up output for this attribute which messes up parsers:

content="3.4.2.2 Description of Less Common (Non-Alzheimer" s)'=""

which is invalid markup. What should happen is:

content="3.4.2.2 Description of Less Common (Non-Alzheimer's)"

(preferred), or

content="3.4.2.2 Description of Less Common (Non-Alzheimer-s)"

if using the same "any character I don't know becomes a hyphen" algorithm.

I think this might be in the RDFa part of Respec, but not sure, I'm not that wise about output.

**Comment by michael-n-cooper** [comment]
Sorry for submitting empty description on first attempt, I pressed "enter" after entering the title and it submitted rather than move to the description field as I expected.

Example: https://rawgit.com/w3c/coga/master/user-research/index.html

There are headings in this document that have apostrophes in them, e.g., "Description of Alzheimer's". Heading text is used to populate various attributes including id and title. In most cases, the apostrophe is converted to a hyphen, so for instance, you get id="h-description-of-alzheimer-s". However, for the permalink there is a <span> that has messed up output for this attribute which messes up parsers:

content="3.4.2.2 Description of Less Common (Non-Alzheimer" s)'=""

which is invalid markup. What should happen is:

content="3.4.2.2 Description of Less Common (Non-Alzheimer's)"

(preferred), or

content="3.4.2.2 Description of Less Common (Non-Alzheimer-s)"

if using the same "any character I don't know becomes a hyphen" algorithm.

I think this might be in the RDFa part of Respec, but not sure, I'm not that wise about output.

**Comment by halindrome** [comment]
I will look at this shortly.

**Comment by darobin** [comment]
This was fixed by #391.
