### ISSUE TITLE
Reuse abstract section if present when in markdown mode

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3897]
## Important info

- ReSpec version: 28.0.5
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

Because editing HTML is troublesome, and not all editors are good at HTML, I am trying to convert some ReSpec documents into Markdown by adding `format: "markdown"` to the config, but encountered some problems.

The first issue is that the Abstract and sotd sections do not seem to support Markdown. See the [code](https://github.com/xfq/testing/blob/9ab55220464ebfa86d98a564a95f32dcdb46225b/simple-ruby-markdown-rs-v1/index.html#L14-L24) and [rendered version](https://xfq.github.io/testing/simple-ruby-markdown-rs-v1/) of a document for an example. The style of the rendered document seems broken.

So I tried to turn the Abstract and sotd parts into HTML, but the Markdown parts in the body text were not rendered at all. See the [code](https://github.com/xfq/testing/blob/main/simple-ruby-markdown-rs-v2/index.html) and [rendered version](https://xfq.github.io/testing/simple-ruby-markdown-rs-v2/) of a document for details. Because I can't use Markdown for some of the main text (for example, I'm not able to add an `id` to an `li` in Markdown), I used HTML for those parts.

Maybe I'm using it wrong, but I'm not sure how to debug this. Can I get a pointer to information on writing specs in Markdown?

**Comment by sidvishnoi** [comment]
If it helps, can you try using `data-include` with `data-include-format="markdown"` instead of `respecConfig.format = "markdown"`. Markdown includes are much more stable. This has additional benefit that you don't need to escape `<>` in code blocks (WebIDL or HTML).

**Comment by marcoscaceres** [comment]
Nah, that would mean creating an external file. 

@xfq, you are right that it's a bug... I would do:

```
<section id="abstract">
...markdown here, exclude section title...
</section>
```

**Comment by marcoscaceres** [comment]
Also, please remember that markdown doesn't like whitespace... this works fine:

```
<section id="abstract">
A simple set of rules for placement of Ruby text in Japanese typography.
</section>

<section id="sotd">
This document was initially written in Japanese
and translated to English
by the <a href="https://www.aplab.jp/jwt">Japanese Writing Technology</a> Working Group
of the <a href="https://www.kri.sfc.keio.ac.jp/en/lab/aplab/">Advanced Publishing Laboratory</a> of Keio University.

It represents the subjective view of its authors and contributors
as to one possible approach to address the problem,
and does not claim to be the only possible solution.
It is submitted to present a non-Japanese speaking audience
with this particular approach,
and to encourage discussion of this topic.

The original Japanese version is <a href="ruby-rules-ja.pdf">available in PDF format</a>.
</section>
```

**Comment by marcoscaceres** [comment]
Rendered: 

<img width="612" alt="Screen Shot 2021-11-30 at 2 36 57 pm" src="https://user-images.githubusercontent.com/870154/144139354-dec28ec1-992a-4568-ad70-67e0b55a698c.png">

**Comment by marcoscaceres** [comment]
@xfq, how did you go? Working ok or still broken for you?

**Comment by xfq** [comment]
Your method indeed works fine, but it would be great if we can just write:

```markdown
## Abstract {#abstract}

A simple set of rules for placement of Ruby text in Japanese typography.

## Status of This Document {#sotd}

This document was initially written in Japanese and translated to English by the [Japanese Writing Technology](https://www.aplab.jp/jwt) Working Group of the [Advanced Publishing Laboratory](https://www.kri.sfc.keio.ac.jp/en/lab/aplab/) of Keio University [...]
```

In addition, if ReSpec supports adding `id`s to `li` and `figure` elements, it is even better, but I understand this is complex, and it is not easy to design a concise and readable syntax.

(There's an open issue against Bikeshed for markdown lists too: https://github.com/tabatkins/bikeshed/issues/1405 )

**Comment by xfq** [comment]
I just tested this and it still doesn't work. Is it my way of using it wrong? See the [code](https://github.com/xfq/testing/blob/e9fabec31f9ac89a5069402c3d3c4a83335221cf/simple-ruby-markdown-rs-v1/index-a-s.html#L14-L24) and [rendered document](https://xfq.github.io/testing/simple-ruby-markdown-rs-v1/index-a-s.html).
