### ISSUE TITLE
Nullable promise parameter not parsed correctly

### ISSUE THREAD

**Issue by mvano** [w3c/respec#390]
When IDL indicates a nullable promise parameter, respec does not link the param type at all. In the example below, I would expect it to link Foo to its definition, excluding the question mark.

``` idl
Promise<Foo?>    getFoo ();
```

I ran into this with the Push API spec for getSubscription: https://w3c.github.io/push-api/#pushmanager-interface

**Comment by marcoscaceres** [comment]
wfm.. might have been an old school idl problem
