### ISSUE TITLE
Check for Separate Security and Privacy sections

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3907]
**Describe the solution you'd like**

The [W3C horizontal review guidelines](https://w3c.github.io/documentreview/#how_to_get_horizontal_review) mentions separate **Security Considerations** and **Privacy Considerations** sections:

> Before requesting privacy and security reviews from the Privacy Interest Group (PING) and security reviewers, respectively, authors must write both "Security Considerations" and "Privacy Considerations" sections for their documents,
> https://w3ctag.github.io/security-questionnaire/#reviews

Maybe it's useful to check it in ReSpec and emit a warning for REC-track documents using the w3c profile.

**Additional context**

There's a similar issue in Bikeshed: https://github.com/tabatkins/bikeshed/issues/2120

**Comment by marcoscaceres** [comment]
Hmm... agreeing with what Tab said over in BS... but yeah, we can modify the checker. That should be pretty easy.

**Comment by marcoscaceres** [comment]
@xfq, initial PR for this:
https://github.com/w3c/respec/pull/3922/files

If you'd like to take a look... I might make it complain also for "ED" status and might be more explicit on exactly which "rec track" documents need this.
