### ISSUE TITLE
Syntax of automatic linking to figures

### ISSUE THREAD

**Issue by xfq** [w3c/respec#3916]
## Important info

- ReSpec version: 28.0.7
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

https://respec.org/docs/#figures-table-of-figure says:

> Automatic linking to figures works just as it does for sections, with `[[[!#some-figure]]]`.

But it doesn't seem to work for me. See the [test code](https://github.com/xfq/testing/blob/d0312bc0021a5612ae9920133079f19ec04f735b/respec-syntax-1/index.html#L98) and [rendered document](https://xfq.github.io/testing/respec-syntax-1/#id15). ReSpec emitted:

> Couldn't find a match for "!#fig-loose-setting" Occurred at: 1. (Plugin: "core/data-cite").

`[[[#some-figure]]]` works though. I'm not sure if this is a docs bug or an impl bug, so I will write an issue here first.

**Comment by marcoscaceres** [comment]
Oops, yes. The docs are wrong: the ! should not be there.

**Comment by sidvishnoi** [comment]
Updated docs.

**Comment by xfq** [comment]
Maybe https://respec.org/docs/#sections also needs fixing?

**Comment by sidvishnoi** [comment]
Good catch!
