### ISSUE TITLE
Enable editing of the documentation by the community

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/respec#3924]
https://respec.org/docs/#code-blocks has a popup-link "Edit" that leads to https://github.com/w3c/respec/wiki/markdown/_edit.
I think it's an excellent idea to let the community contribute to the documentation because that takes off pressure from the developers.
Eg PlantUML does that (eg see page https://plantuml.com/class-diagram) and even allows anonymous editing in 3 syntaxes (docuwiki, asciidoc, markdown).

However, that takes me merely to https://github.com/w3c/respec/wiki/markdown with a blue warning "You do not have permission to update this wiki".
I cloned `respec`, but on github the wiki is not part of the source, unlike eg Azure Git.

Is it possible to come up with some way to enable community editing of the documentation?

----
The specific doc change I want to make is in https://github.com/w3c/respec/wiki/markdown#code-blocks:

**from**
Syntax highlighting for various languages, including an advanced syntax highlighter for WebIDL is available out of the box.

**to**
Respec uses [highlight.js](https://github.com/highlightjs/highlight.js) for syntax highlighting of various languages.
"abnf", "css", "http", "javascript", "json", and "xml" are supported by default, and you could add more by modifying [respec-highlight.js](https://github.com/w3c/respec/blob/develop/worker/respec-highlight.js).
An advanced syntax highlighter for WebIDL is also available out of the box.

**Comment by sidvishnoi** [comment]
> Is it possible to come up with some way to enable community editing of the documentation?

Hello! Yes, it's possible and I've enabled it. We had to limit the access earlier due to spam edits from bots [^1].  Feel free to edit now :)

>  I cloned respec, but on github the wiki is not part of the source, unlike eg Azure Git.

GitHub wikis aren't part of the repo source code, but you can clone it by adding `.wiki` suffix to repo like:
```
git clone git@github.com:w3c/respec.wiki.git
```

[^1]: https://github.com/w3c/respec/issues/2003,

**Comment by sidvishnoi** [comment]
Though, it might be helpful to link to https://respec.org/docs/#examples as that already contains list of supported languages.

**Comment by xfq** [comment]
It seems that there is a new spam edit: https://github.com/w3c/respec/wiki/BANANA

Maybe we can transfer the documents in the wiki to Markdown files in the repo itself in the future (it can be this repo or a separate repo), so that those who want to contribute can use pull requests to contribute.

**Comment by marcoscaceres** [comment]
We should figure out how to just enable access for W3C members. 

@VladimirAlexiev, in the meantime, I'll give you write access.

**Comment by VladimirAlexiev** [comment]
Thanks! 
Btw, I have a w3c account. But I guess you mean the w3c group on github

**Comment by VladimirAlexiev** [comment]
Edited the following sections:
- https://respec.org/docs/#pre-and-code-elements
- https://respec.org/docs/#examples
- https://respec.org/docs/#code-blocks
