### ISSUE TITLE
Link constructors in WebIDL

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#394]
Forked from https://github.com/w3c/respec/pull/373#discussion_r22060777. Link the `[Constructor]` extended attribute to `<dfn title="InterfaceName" for="InterfaceName">`, and give that the id `InterfaceName-InterfaceName`. I'd guess that `[NamedConstructor=Name]` should go to `<dfn title="Name">` and have the id `dom-Name`, but @tabatkins may point out that [Bikeshed](https://github.com/tabatkins/bikeshed/blob/master/docs/idl.md) does something different.

**Comment by shubhshrma** [comment]
@marcoscaceres what are starting steps with this in ```webidl.js```? I'm trying to include this in my gsoc tasks list.

**Comment by marcoscaceres** [comment]
@shubhshrma, basically, when we see a "constructor", it needs to create an entry in `conf.definitionMap` that can be linked to as: "InterfaceName.IntefaceFunction()", as described in https://github.com/w3c/respec/issues/394#issuecomment-71237207  

You probably don't need to go into this level of detail in you proposal, just describe generally what needs to be fixed overall for WebIDL.

**Comment by marcoscaceres** [comment]
Blocked on https://github.com/heycam/webidl/issues/636 

We might be getting new syntax for this.
