### ISSUE TITLE
Warn that webidl-oldschool is deprecated

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#395]
Forked from https://github.com/w3c/respec/pull/373#discussion_r22034180. This should probably wait until webidl-contiguous has seen a bit of use and is stable.

**Comment by marcoscaceres** [comment]
As I've already had to clean up one spec using old IDL, I think it's time to start showing a real warning.

**Comment by marcoscaceres** [comment]
ReSpec now warns.
