### ISSUE TITLE
Installed `respec` package depends on a compromised version of `colors`

### ISSUE THREAD

**Issue by kaelig** [w3c/respec#3951]
As shown in these logs: https://github.com/design-tokens/community-group/runs/4757732944?check_suite_focus=true#step:3:670

<img width="963" alt="Screen Shot 2022-01-09 at 10 32 03 PM" src="https://user-images.githubusercontent.com/85783/148726144-9a225ea0-db2b-4710-b99e-1fc03891532e.png">

I tried to overcome this issue by adding [these lines](https://github.com/design-tokens/community-group/blob/main/package.json#L27-L32) to `package.json`:

```json5
  // For npm
  "overrides": {
    "colors": "1.4.0"
  },
  // For yarn
  "resolutions": {
    "colors": "1.4.0"
  }
```

But this didn't only solved the issue locally, and not with the `w3c/spec-prod@v2` action.

Is there a workaround someone can provide?

**Comment by sidvishnoi** [comment]
Released new ReSpec version (28.2.0) with `colors` locked at a safe version. Re-running spec-prod action should work as expected now.
