### ISSUE TITLE
New requirement to use section rather than div for SOTD & abstract

### ISSUE THREAD

**Issue by r12a** [w3c/respec#3955]
For some reason (i don't remember seeing any announcement, and can't find one), Respec now complains if you have used a div rather than a section tag for the abstract and SOTD text, and it seems that this needs to be changed to allow publication of the document. Why was this changed?

The i18n WG/IG is actively maintaining over 40 editor's drafts, so this is a pain, especially given that around 20 of those ED are typically republished without having to open the HTML and edit it (because the changed text is automatically sucked in from elsewhere).  Presumably this is also going to trip up a lot of other folks publishing documents at W3C, and make them re-edit their docs when they are trying to publish.

Why can't respec simply rewrite the div to a section automatically?

**Comment by marcoscaceres** [comment]
> Why can't respec simply rewrite the div to a section automatically?

It can. Let me send a pull request to do that ☺️

**Comment by r12a** [comment]
Thanks Marcos !

**Comment by marcoscaceres** [comment]
@r12a could please let us know if the SOTD are ok? I didn't see/make any relevant code changes to the SOTD code, but I might have missed something!

**Comment by r12a** [comment]
@marcoscaceres i updated https://www.w3.org/International/afrlreq/gap-analysis/nkoo-gap, which has divs for both abstract and SOTD and it published it ok.
