### ISSUE TITLE
Section permalinks recent visual regressions

### ISSUE THREAD

**Issue by kaelig** [w3c/respec#3974]
## Important info

- URL to affected spec: https://design-tokens.github.io/community-group/format/
- ReSpec version: 28.2.6
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

https://github.com/w3c/respec/pull/3899 and/or https://github.com/w3c/respec/pull/3966 introduced two regressions when fixing https://github.com/w3c/respec/issues/3898:

1. all headings now have too much space after them (this is because the `a` is now in the flow between the preceding heading and the element that follows it)
2. Some anchors are now vertically misaligned with their respective headings
<img width="590" alt="Screen Shot 2022-01-26 at 3 04 39 PM" src="https://user-images.githubusercontent.com/85783/151262010-28336362-0323-42e8-acef-532acfa552f5.png">

**Comment by marcoscaceres** [comment]
Ha! thanks @kaelig. Looks like I spent so long on the other issue that I stopped seeing the gap! Sending a fix now.

**Comment by marcoscaceres** [comment]
Leaving this open as the alignment is still a bit off. I think in order to fix it, I'll need to wrap the headings and the anchors in a div and lay them out with CSS Grid or Flex (unless you or someone else has a better suggestion). I might do that as a follow up.

**Comment by marcoscaceres** [comment]
h4-h6 are still having issues...
