### ISSUE TITLE
Misleading links on Exposed extended attribute values

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#3976]
## Important info

- URL to affected spec: any that uses `[Exposed]`
- ReSpec version: 28.2.2
- [x] I did a "hard refresh", but it's still busted.

## Description of problem
Respec [adds links to the values of the `Exposed` extended attribute](https://github.com/w3c/respec/blob/1314564705e987e05e4d3d31a376c4bbb370b9e7/src/core/webidl.js#L51) that link to interfaces; but in practice, the names are distinct from interfaces, and only indirectly linked to them: e.g. a `Exposed=Worker` doesn't imply your global object is an instance of `WorkerGlobalScope` - it instead indicates that you're exposed in any object surfaced with the `Global=Worker` extended attribute.

I think it would be cleaner to have no link at all.

**Comment by marcoscaceres** [comment]
Cc’ing @saschanaz for any additional input on this. I’m ok to remove the links.

**Comment by marcoscaceres** [comment]
@dontcallmedom, so, "Global" is just an identifier? 

Does that mean I could do:

```
[exposed=Somewhere]
interface Foo{};

[Exposed=Somewhere, Global=Somewhere]
interface Bar {};
```

And `Foo` and `Bar` would show up "Somewhere"? I guess my question is, wouldn't "Somewhere" be formally defined? Or is it just a name?

**Comment by saschanaz** [comment]
Yeah, it's confusing as WorkerGlobalScope has no `[Global]`. Could be great if it could be linked to all interfaces that have `[Global=Worker]` but that complicates things.

**Comment by dontcallmedom** [comment]
> @dontcallmedom, so, "Global" is just an identifier?

The value assigned to the Global extended attribute is indeed just an identifier, one that lives in a different namespace than WebIDL names.

> Does that mean I could do:
> 
> ```
> [exposed=Somewhere]
> interface Foo{};
> 
> [Exposed=Somewhere, Global=Somewhere]
> interface Bar {};
> ```
> 
> And `Foo` and `Bar` would show up "Somewhere"? 

Correct; more specifically, this would make `Bar` a definition of the global object for realms that match the "Somewhere" name, and these realms would expose both the `Foo` and `Bar` interfaces.

> I guess my question is, wouldn't "Somewhere" be formally defined? Or is it just a name?

I would have expected these names to be formally defined, but I guess the fact that they haven't been so far means that may not be necessary; I built the [Globals view in WebIDLpedia](https://dontcallmedom.github.io/webidlpedia/globals/) to try and get a sense of what such a definition would be though.

**Comment by saschanaz** [comment]
Does it mean we should link to WebIDLpedia instead? 😄
