### ISSUE TITLE
Human Readable Date Inconsistant And Not Localized

### ISSUE THREAD

**Issue by init-dcat-ap-de** [w3c/respec#3981]
## Important info

- ReSpec version: 28.2.8

## Description of problem

![grafik](https://user-images.githubusercontent.com/14979304/151711913-3c3bb7ae-77c7-483f-bf4e-eddff4aab2a9.png)

The dates in the top part of the document are 
1. inconsistant
The first date uses the English name of the month (March) while the second date uses the German name (Januar = January).
Both should use the German name, since the language is set to German.

2. not localized
The correct localization in German would be
`1. März 2022`  and `27. Januar 2022`

The leading `0` is not used in texts and the `.` after the day is mandatory.

**Comment by init-dcat-ap-de** [comment]
Thank you for the fast fix. 
I guess it's better to add this comment here (or should I open a new issue?):

The first date is now perfect, but the second one is still inconsistant:
![grafik](https://user-images.githubusercontent.com/14979304/151929223-9a4c6351-1087-46ed-a863-ca326a504d93.png)

**Comment by sidvishnoi** [comment]
@init-dcat-ap-de Where's this date exactly? Can you share more context?

**Comment by init-dcat-ap-de** [comment]
@sidvishnoi of course!

The date is the [`modificationDate`](https://respec.org/docs/#modificationDate) and is used in the sub-title.

**Comment by sidvishnoi** [comment]
@marcoscaceres Can we use `W3CDate` there without breaking pubrules?
https://github.com/w3c/respec/blob/a2d2a17513c8cd4d575a0f3d2f3e10aec2662309/src/w3c/templates/headers.js#L402
https://github.com/w3c/respec/blob/a2d2a17513c8cd4d575a0f3d2f3e10aec2662309/src/w3c/templates/headers.js#L406-L415

**Comment by init-dcat-ap-de** [comment]
@sidvishnoi do the pubrules apply to translations?

**Comment by marcoscaceres** [comment]
Nope. But the issue is a quick fix. Will try to get to it soon!
