### ISSUE TITLE
Generated appendices absorbed into previous markdown section

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#3994]
## Important info

- URL to affected spec: https://respec-preview.netlify.app/?spec=https%3A%2F%2Fraw.githubusercontent.com%2Fw3ctag%2Fprivacy-principles%2Fmain%2Findex.html&version=https://unpkg.com/respec@29.0.1/builds/respec-w3c.js (after https://github.com/sidvishnoi/respec-preview/pull/5 is merged)
- ReSpec version: 29.0.1
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

`#bp-summary` is shown as section 2.12 instead of as appendix C, and similarly for `#issue-summary` and `#references`. The appendices that we wrote as markdown are correctly shown as appendices. ReSpec 28 didn't have this issue.

**Comment by marcoscaceres** [comment]
Confirmed. Having a look.

**Comment by marcoscaceres** [comment]
Ha! funny issue 😅 

basically, the mix of `h1`'s in the markdown above + ReSpec assuming everything is `h2` confused the restructuring code. Sending a hot fix that creates h1 titles for included sections, which get converted to `h2`s when the doc is restructured.

**Comment by marcoscaceres** [comment]
@jyasskin, should be good in 29.0.3... just checked. But let me know if there are any other issues 🙏

**Comment by marcoscaceres** [comment]
Found a couple more...
