### ISSUE TITLE
Auto-numbering tables like examples

### ISSUE THREAD

**Issue by egekorkan** [w3c/respec#4004]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I want to link to or mention a table, like in a GitHub issue, saying that "Table 3 has an issue at ...". Tables are not automatically numbered and are not linkable like examples are. Tables can have an `id` attribute and it can be used for linking but this needs one to look at the HTML source and also does not solve the fact that the tables are not numbered.

**Describe the solution you'd like**
I would like to use a CSS class for the table that auto generates the table number and by using the `title` attribute, hyperlinks the table URL to the "[Table 3](http://exampe.com/myspec#my-amazing-table): My Amazing Table" . A concrete example would be https://respec.org/docs/#example-a-basic-respec-document but for tables. A hacky solution is shown in Additional Context, item 2.

**Describe alternatives you've considered**
One can manually add a caption for the tables, manually insert a number (and maintain that number) and add a link. This can be scripted rather easily. In the case of the [W3C WoT Thing Description](https://w3c.github.io/wot-thing-description/) which has already some custom rendering scripts in place, it would not be a lot of work and would be invisible for the contributors of the spec (since they have to use those rendering scripts anyway).

**Can you or your organization fund the work or help with development?**
My organization is a member of W3C and W3C seems to be funding the development. For a separate contribution, I would need to trigger some people with no guarantees of a favorable answer. A one-time contribution would be most likely due to how my organization does payments _most of the time_. I do not plan to make a personal financial contribution but I can support the development with my skills. My organization can also support someone in my team to make a PR with this feature but no guarantees on the maintenance of this feature.

**Additional context**

1. Currently a table looks like this:
![image](https://user-images.githubusercontent.com/20195407/152600897-adc3fe36-a7d7-4f45-a680-6d633bcb2c07.png)
for the following HTML
```html
    <table class="def" id="tab-namespaces">
    <thead>
        <tr>
            <th>Vocabulary</th>
            <th>Namespace IRI</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Core</td>
            <td><code>https://www.w3.org/2019/wot/td#</code></td>
        </tr>
        <tr>
            <td>Data Schema</td>
            <td><code> 	https://www.w3.org/2019/wot/json-schema#</code></td>
        </tr>
        <tr>
            <td>Security</td>
            <td><code>https://www.w3.org/2019/wot/security#</code></td>
        </tr>
        <tr>
            <td>Hypermedia Controls</td>
            <td><code>https://www.w3.org/2019/wot/hypermedia#</code></td>
        </tr>
    </tbody>
    </table>
```

2. Ideally something like this would be nice

```html
<table class="def" id="tab-namespaces" title="Namespaces used in a Thing Description">
<!-- line below is ideally auto-generated -->
      <caption style="text-align:left;margin-bottom: 0;" class="def"><a href="#tab-namespaces">Table 1</a>: Namespaces used in a Thing Description</caption>
    <thead>
        <tr>
            <th>Vocabulary</th>
            <th>Namespace IRI</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Core</td>
            <td><code>https://www.w3.org/2019/wot/td#</code></td>
        </tr>
        <tr>
            <td>Data Schema</td>
            <td><code> 	https://www.w3.org/2019/wot/json-schema#</code></td>
        </tr>
        <tr>
            <td>Security</td>
            <td><code>https://www.w3.org/2019/wot/security#</code></td>
        </tr>
        <tr>
            <td>Hypermedia Controls</td>
            <td><code>https://www.w3.org/2019/wot/hypermedia#</code></td>
        </tr>
    </tbody>
    </table>
```

![image](https://user-images.githubusercontent.com/20195407/152602764-2403c2d9-5bed-4999-b1b9-0f3cd7c54cf1.png)

3. A related issue: https://github.com/w3c/wot-thing-description/issues/1256

**Comment by marcoscaceres** [comment]
Hmm... I wonder if such tables shouldn't actually be `<figures>`?... maybe not. 

Having said that, alternative I've used is giving `<caption>` a `<dfn>`... like "`<dfn>The table of things</dfn>`"... and then "as shown in [=the table of things=]".

**Comment by egekorkan** [comment]
So I have tried your ideas. Using `<dfn>` actually is not too bad, it automatically generates clickable links but it has some issues:
- We use <dfn> for definitions in the terminology and some other places so it would be a bit weird to use it for captions.
- We get respec errors for unused definitions, so these would also show errors if unused. I personally think that each table, figure and example that exists must be used in the text as well. So this may not be an issue.
- There are still no numbers generated. I like being able to refer to something by saying "Example 5" instead of saying "Example of an amazing thing".

Regarding using figures: I have tried to wrap the table in a figure class (so not putting a PNG) and I get the following:
![image](https://user-images.githubusercontent.com/20195407/152770798-0e015a51-d92c-4fa5-aa80-9e0d676e1a4c.png)

Which is almost exactly what I want! The only issue is that a table is marked as a Figure for the reader and that might be confusing.

Regarding putting actual PNGs: that would not be possible since the text inside them cannot be selected with a mouse and we use the tables as assertions for testing our specs.

**Comment by danielpeintner** [comment]
I looked at the ReSpec documentation hoping to find a way to create a *own* category.

What do I mean by that. I try to replace the automatically added "Figure" text with my own group and numbering. I did not find any possibility. Did I miss anything? If so, please let us know.

**Comment by marcoscaceres** [comment]
No, but it may be worth looking at how figures are done. 
https://github.com/w3c/respec/blob/develop/src/core/figures.js

**Comment by marcoscaceres** [comment]
We would need to work out some opt in mechanism for this (as numbering tables is not commonly), as well as a way of referencing a table without using its number. 

I still think `<table id=“mytable” class=“numbered”><summary>Table of goodies` might be the right answer here tho. So:

“As shown in [[[#mytable]]],”

would render as:

“As shown in Table 1. Table of Goodies,”

with the right linking.

**Comment by egekorkan** [comment]
It would be ok to support both types of tables. I think that we need to agree on the following points:
- What is used for the link that appears in the URL. I am guessing the `id` field but it can be also `title` like it is with examples
- What is used for referencing the table inside the document. I am guessing the `id` field as well.
- If one document uses numbered and unnumbered tables, i.e. numbered table, unnumbered table, numbered table, what number does the third table get. In other words, is che class `numbered` only for rendering the actual value or is it used for counting internally or not as well.

**Comment by marcoscaceres** [comment]
> What is used for the link that appears in the URL. I am guessing the id field but it can be also title like it is with examples

It would be the `id` (ReSpec sometimes automatically generates those, like for the examples). 

> What is used for referencing the table inside the document. I am guessing the id field as well.

Correct. Using the id also how we reference figures and headings/sections - so that would be consistent.

> If one document uses numbered and unnumbered tables, i.e. numbered table, unnumbered table, numbered table, what number does the third table get. In other words, is the class numbered only for rendering the actual value or is it used for counting internally or not as well.

Right. Some tables might not be numbered for whatever reason (i.e., they are not "data" tables) or tables that need to be referenced.

**Comment by marcoscaceres** [comment]
I probably won't have time to get to this in the next month, but so I'd suggest if anyone has cycles to take this up to look at:
https://github.com/w3c/respec/blob/develop/src/core/figures.js (and related tests)

I think we have a pretty good model to work off defined above.
