### ISSUE TITLE
Including a common glossary across multiple documents

### ISSUE THREAD

**Issue by msporny** [w3c/respec#404]
We have a slowly forming requirement in the Web Payments IG that we keep our terminology straight across all documents. We can do this in two ways - 1) create a glossary document and link externally to it, or 2) copy-paste only the glossary terms that matter into the spec in question.

1 makes for a very annoying to edit and annoying to read spec. Annoying to edit because all your <dfn>s are external links, and annoying to read because you need two documents open to understand what's being said.

2 is annoying because you have to keep the terms used in each spec in sync w/ the master glossary.

Ideally we'd we able to do something like the bibliographic references (localBiblio) but for glossary terms. In the magical future world, only the glossary terms that were used in the specification would be pulled in from the master glossary.

I tried to hack something together tonight and was thwarted.

I can use data-include and data-include-sync to include the glossary no problem, but then I have some respec.preProcess steps that need to run over the entire document /before/ ReSpec starts doing its thing. So, the order of operations I need are:
1. Put all data-include statements into the document.
2. Run respec.preProcess functions (that inject dfn statements into the document).

How can I do this with a recent version of ReSpec? The problem, of course, is that respec.preProcess is run /before/ the data-include attributes are processed.

**Comment by msporny** [comment]
@halindrome the preProcess stuff I run is your tref/tdef hack from a very long time ago (because I find it very useful). Is there another way to do that these days?

**Comment by marcoscaceres** [comment]
duplicating content (definitions) across specifications is going to end in tears (specially where we don't have living standards where these definitions cannot be pulled in in real time). I would strongly urge you to just have a single document, and just hyperlink to where the definition of a concept is (as is done with WHATWG specs, for instance).  

So yes, we need cross-ref support in ReSpec.

**Comment by halindrome** [comment]
I have a design and early implementation of cross reference support.  However, for this problem, the simple solution is to put your glossary in a separate file that is included by each document that needs it.  It just works (tm).  See any of the ARIA specs for examples.  Or contact me privately and I can walk you through it.

**Comment by msporny** [comment]
@marcoscaceres I'm fine w/ cross-ref support - is someone working on it? If not, should one of the folks on our engineering team do it? If so, where should they put it. Pointers to a module to model the feature after and/or file to put it in would be helpful.

@halindrome I'm going to have to contact you privately; we have some other stuff to chat about. I don't think data-include happens early enough to create the <dfn>s necessary, but data-oninclude sounds interesting... got any links to the ARIA spec you're referring to?

**Comment by darobin** [comment]
If you really want to do this, the trick is probably to have preProcess fetch and insert the glossary itself somehow. But I tend to agree that this feels better as a document you can link to.

Cross-ref support certainly is on the list but it isn't actively being developed on the client side. @tobie might have some things to say about data availability for the backend part. It certainly is something that's very much in demand.

**Comment by tobie** [comment]
I'm working on the back-end for this, but I'm currently sick leave so can't really give you a precise ETA.

Precise use cases for what you expect from such a back-end would be useful, however.

**Comment by halindrome** [comment]
We have good support for this as an extension now.  It is pretty straightforward.

**Comment by tobie** [comment]
@halindrome link?

**Comment by halindrome** [comment]
It is in use in PFWG and in the WPIG now.  The WPIG one is simplest... 
https://github.com/w3c/webpayments-ig/tree/master/latest/common

In scripts there is a JS file that implements removing unused definitions.  The central terms are in whatever file you like, and are brought in using data-include.  For example in the WPIG capabiltiies document it uses:

    <div data-include="../common/terms.html" data-oninclude="restrictReferences"></div>

**Comment by marcoscaceres** [comment]
using data-include seems like a good solution for this, so closing.
