### ISSUE TITLE
Consider displaying the first version a feature started to work at in CanIUse widget

### ISSUE THREAD

**Issue by tomayac** [w3c/respec#4042]
The current widget shows the _latest_ version an API can be used at:

<img width="490" alt="Screen Shot 2022-02-17 at 11 17 01" src="https://user-images.githubusercontent.com/145676/154455212-c4ee4898-f432-44d8-8938-7191acd0c2b9.png">

([Source](https://www.w3.org/TR/geolocation/))

It might be more useful to show the _first_ version an API started to work in. This is a widget based on the same data our team has built for [web.dev](https://web.dev/):

<img width="490" alt="Screen Shot 2022-02-17 at 11 16 27" src="https://user-images.githubusercontent.com/145676/154455114-3e8c9438-8efb-4f01-852c-020f1832c649.png">

([Source](https://web.dev/file-system-access/#browser-support))

CC: @marcoscaceres

**Comment by marcoscaceres** [comment]
Alternative might be we hide the version number entirely... Then if a user hovers over the browser they can see the since info. For example:
 
<img width="735" alt="Screen Shot 2022-02-18 at 2 32 58 am" src="https://user-images.githubusercontent.com/870154/154515037-57eff267-2ca2-4ff8-aceb-e31c6c019824.png">

**Comment by marcoscaceres** [comment]
It might be nice to also figure out how to make it more obvious that these are drop-downs...

**Comment by marcoscaceres** [comment]
Ok, @sideshowbarker and I had a little play... how about: 

![Screen Shot 2022-02-22 at 5 06 53 pm](https://user-images.githubusercontent.com/870154/155072801-5d16801a-cd85-4950-bb73-0ab9cc1d65a2.png)

It shows:

 * minimal support version. 
 * Gets rid of the hover functionality (readers can see that info on caniuse itself)
 * Retains the some of the fine-grained "it's kinda supported" level information.

**Comment by marcoscaceres** [comment]
We need to change this on the server, as we are sending back "server-side rendered HTML"™️ at the moment (or we fix the rendering on the server side to stop giving us the hover drop-downs).

**Comment by tomayac** [comment]
I quite like this. Two additional ideas to try could be to add `≥` to the version numbers to convey support started at the displayed version and to use `❌` instead of `⛔️`.

**Comment by marcoscaceres** [comment]
> Two additional ideas to try could be to add ≥ to the version numbers to convey support started

Yeah, something like that might work.. maybe we should do a somewhat unscientific twitter poll to see if people understand what it means with/without it. 

> at the displayed version and to use ❌ instead of ⛔️.

We found the ❌ didn't work because of the red background (not enough contrast... but we can try to fade the red background or use "⤫" or one of the other "x"s)....

**Comment by tomayac** [comment]
> We found the ❌ didn't work because of the red background (not enough contrast... but we can try to fade the red background or use "⤫" or one of the other "x"s)....

Or simply `N/A`.

**Comment by marcoscaceres** [comment]
`N/A` is good.. as it's literally what we mean.

**Comment by tomayac** [comment]
Thanks so much for the work on this! I think it's a lot better now!

**Comment by marcoscaceres** [comment]
No problem. Thank you for the great suggestion of showing the first supporting version. That solved a bunch of problems for us. 

We are going to continue to improve this over next few months (mobile view needs some work still).
