### ISSUE TITLE
Error or warning for a missing w3cid in respecConfig

### ISSUE THREAD

**Issue by iherman** [w3c/respec#4055]
Recent versions of pubrules checker consider it as an error if the `data-editor-id` attribute is missing for an editor. (I am not sure it complains for every specification type, though; it did it for me for a Rec.) 

This HTML attribute is generated from respec's [`w3cid` field in `respecConfig`](https://respec.org/docs/#person). However, that field is not marked as required in the respec documentation, nor does respec warn if it is missing. For editors making the connection between the pubrules error and a specific respec field may not be obvious…

A simple solution would be if respec reported either an error or at least a warning if that field is missing.

cc @msporny

**Comment by marcoscaceres** [comment]
Yeah, this would be great and easy to check for. 

What I'd ultimately like an API to pull (limited) user info from a W3C ID (there are privacy concerns, obviously! However, we can do this already through the W3C API, so "cat is out of the bag" already).

**Comment by msporny** [comment]
> What I'd ultimately like an API to pull (limited) user info from a W3C ID (there are privacy concerns, obviously! However, we can do this already through the W3C API, so "cat is out of the bag" already).

Privacy violations happen when unexpected actions are taken wrt. what folks expect to be private information. I, for one, would be surprised if my profile information was available to non-W3C Members (as an example) under certain conditions. Just because the W3C API might contain a privacy violation today, doesn't mean it should continue to in the future.

Pulling certain W3C Member Profile fields that the individual has consented to, for the purposes they consented, is fine. For example, a checkbox to this effect might be the solution here: "Allow W3C to publish my name, affiliation, my website, and my company's website on a specification for which I'm the Editor or Author." <-- totally fine. Doing that w/o consent, is what's not ok. I realize this is a pain for the folks building the W3C API and ReSpec, so I appreciate the thoughtful work that will go into making sure we're following best practices from a privacy regulation perspective (GDPR, CCPA, PEPIDA, etc.) /cc @wseltzer @rigow

This is a separate topic, where should I raise an issue about it?

**Comment by msporny** [comment]
> A simple solution would be if respec reported either an error or at least a warning if that field is missing.

+1 to that.

A few things to note. I have never found an easy way to get a w3cid value w/o having to either 1) ask the individual, or 2) rely on W3C staff to get the value for me. @iherman noted that I should be able to go to the WG member page and find the value, however, the link he mentioned that I should be able to click on, doesn't exist for me (possibly a link that shows up only for W3C staff)?

In any case, finding the `w3cid` value has always been a challenge for me for the past decade or so.

**Comment by marcoscaceres** [comment]
> Doing that w/o consent, is what's not ok. I realize this is a pain for the folks building the W3C API and ReSpec, so I appreciate the thoughtful work that will go into making sure we're following best practices from a privacy regulation perspective (GDPR, CCPA, PEPIDA, etc.) 

It would be opt in... exactly the same way that editors today put their own information into a document, they would instead just put their W3C ID into a document. 

> This is a separate topic, where should I raise an issue about it?

No need. I already filed on on the W3C API a while ago.

**Comment by msporny** [comment]
> It would be opt in... exactly the same way that editors today put their own information into a document, they would instead just put their W3C ID into a document (which they also do today).

Except that it's not opt-in... noting @iherman's original issue text:

> Recent versions of pubrules checker consider it as an error if the data-editor-id attribute is missing for an editor.

So, when @iherman told me of this error, and that it would lead to our REC meeting publication issues, he gave me all the w3ids and I added them into the document without a second thought that doing so might pull in PII. In other words, I was involved in a potential privacy violation, did not get consent from the other Editors/Authors, and blindly added their w3ids.

Just trying to make the privacy nuance clear here... Unless I'm missing something, we've got a system here that sets Editors up for unknowingly perpetrating privacy violations.

> No need. I already filed on on the W3C API a while ago.

Thank you!

**Comment by marcoscaceres** [comment]
> Just trying to make the privacy nuance clear here... Unless I'm missing something, we've got a system here that sets Editors up for unknowingly perpetrating privacy violations.

I don’t think so. People can’t be editors of a spec if they are not in a working group, and they can’t have a w3cid if they are not w3c members. Plus a bunch of other checks and balances: the Process requires that editors be affirmed by Chairs and publicly announced etc. etc. Plus we have a fairly standard set of information that shows up at the top of a document. Seems pretty unlikely anyone would be surprised if they explicitly signed up to edit a spec and then were shocked to find their name and company affiliation at the top of the document.

**Comment by msporny** [comment]
> Seems pretty unlikely anyone would be surprised if they explicitly signed up to edit a spec and then were shocked to find their name and company affiliation at the top of the document.

Yes, agreed. My concern was the "other information" that would be pulled from a w3cid. The set that would be pulled was vague, and the general concern was "things that people didn't expect to be public would be pulled". 

Here's a non-exhaustive list of things that I would consider personal information in a w3cid: personal email addresses, mobile phone numbers, and home mailing addresses. I expect that we wouldn't just pull those into display code, but never underestimate what a junior developer would do with that information w/o some strict guidance.

In any case, if you have a handle on it @marcoscaceres, then I'm fine w/ you making the appropriate decisions (I trust you to do that). Just trying to highlight that w3c user accounts do contain PII that is expected to remain as such.
