### ISSUE TITLE
Style: Use a sans-serif font for WebIDL label

### ISSUE THREAD

**Issue by inexorabletash** [w3c/respec#406]
I think this comes out of `respec/js/core/css/webidl-oldschool.css` but I'm not hip to the build system...

The definition of:
```css
pre.idl::before {
  content: "WebIDL";
  font-family: initial;
}
```
... leaves the generated "WebIDL" label in a glorious serif typeface ("Times New Roman" or your local platform equivalent). The rest gets styled via W3C-WD spec's `body { font-family: sans-serif; }` rule, but the `initial` bypasses that. It looks somewhat glaringly out of place. `inherit` doesn't help, since then it ends up in a monospace font.

How about `font:family: sans-serif;` instead? (Yes, it's a risk if W3C-WD is ever revised...)

**Comment by darobin** [comment]
You're right; I've fixed this, it'll ship with the next release.
