### ISSUE TITLE
Wrong syntax for This Version link

### ISSUE THREAD

**Issue by xfq** [w3c/respec#4064]
## Important info

- URL to affected spec: https://w3c.github.io/clreq/?specStatus=DNOTE
- ReSpec version: 31.0.9
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**

Wrong syntax for This Version link.

**Expected behavior (e.g., it shouldn't crash):**

The syntax of a “this version” URI should be `https://www.w3.org/TR/YYYY/DNOTE-shortname-YYYYMMDD/` instead of `https://www.w3.org/TR/DNOTE-clreq-20220301/` (there is no year between `TR/` and `/DNOTE`).

**Steps to reproduce:**

1.  Open https://w3c.github.io/clreq/?specStatus=DNOTE
2. Observe the This Version link

**Comment by marcoscaceres** [comment]
Oops! Will fix this hopefully tomorrow
