### ISSUE TITLE
Provide a way to refer to [[internal slots]] of JS objects

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#407]
The [ECMAScript standard](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-internal-methods-and-internal-slots) uses names in [[]]s to refer to "internal" properties of objects. ReSpec formats anything in [[]]s as a bibliography reference. It's possible to defeat this by writing `[<span></span>[InternalSlot]]`, but that's awkward.

Sorry if I just missed the way to do this.

**Comment by marcoscaceres** [comment]
You can use [[\WhatEver]] to escape such things. I use it in the manifest spec :)
