### ISSUE TITLE
clarify documentation for exporting definitions for external use

### ISSUE THREAD

**Issue by npdoty** [w3c/respec#4074]
**URL to affected spec or repo:**

https://respec.org/docs

**What happened (e.g., it crashed)?:**

Documentation suggests we should use a CSS classname to mark a definition for export: https://respec.org/docs/#data-export

However, in passing in the documentation, it seems expected that a `data-export` attribute (perhaps with a value of `""`) is the way to export definitions for use via xref or webref.

**Expected behavior (e.g., it shouldn't crash):**

Document how to use `<dfn data-export`, and/or deprecate using a CSS class name, and/or specify which is preferred.

**Comment by marcoscaceres** [comment]
Updated the docs to no longer talk about `data-export`. Made it clear that `class="export"` is the preferred way. 

Waiting on https://github.com/w3c/respec-web-services/pull/277 ... once that lands, the docs will get regenerated and we can close this.

**Comment by npdoty** [comment]
Overloading a CSS class name to have semantic meaning is the _preferred_ approach? I'm surprised, but appreciate the clarity in any case!
