### ISSUE TITLE
Markdown code block not properly rendered

### ISSUE THREAD

**Issue by sroertgen** [w3c/respec#4077]
Hello there 👋,

## Description of problem

Using angle brackets in markdown code blocks leads to not properly rendered html. E.g.

```
HTTP/1.1 200 OK
Content-Type: application/ld+json
Link: <https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
```

https://github.com/dini-ag-kim/amb/blob/7fc3b7832281384598e37d3b9235aff127345113/draft/index.html#L204-L207

...looks like this:

![](https://user-images.githubusercontent.com/160292/111476618-9d2ab800-872e-11eb-92f0-5ee827204097.png)

We need it to display HTTP-Link header information like this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link#syntax

If I understand correctly respec uses marked under the hood. A [minimal marked example](https://marked.js.org/demo/?text=%60%60%60%0AHTTP%2F1.1%20200%20OK%0AContent-Type%3A%20application%2Fld%2Bjson%0ALink%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fkim%2Flrmi-profile%2F2021mmdd%2F%3E%3B%20rel%3D%22profile%22%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) looks fine.

**Optional, steps to reproduce:**

Here is a minimal respec html to reproduce:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Replace me with a real title</title>
    <script src="../builds/respec-w3c.js" type="module" class="remove"></script>
    <script class="remove">
      // All config options at https://respec.org/docs/
      var respecConfig = {
        specStatus: "ED",
        editors: [
          {
            name: "Your Name",
            url: "https://your-site.com",
          },
        ],
        format: "markdown",
        github: "w3c/respec",
        shortName: "respec",
        xref: "web-platform",
        group: "webapps",
        noRecTrack: true,
      };
    </script>
  </head>
  <body>

<section id="abstract">

## Foo

```

````
```
HTTP/1.1 200 OK
Content-Type: application/ld+json
Link: <https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
```
````

```
</section>

<section id="conformance">
<p>
This is required for specifications that contain normative material.
</p>
</section>
<section id="index"></section>
<section id="sotd"></section>
</body>
</html>
```

(this is of course one document, just didn't know how to escape the embedded code block properly...)

**Comment by sidvishnoi** [comment]
As a ReSpec doc is HTML, `<`, `>` need to be escaped, even when the format is markdown. This is because browser's HTML processing triggers before our Markdown processing.

In your particular case:
~~~diff
<section id="abstract">

## Foo

```
HTTP/1.1 200 OK
Content-Type: application/ld+json
- Link: <https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
+ Link: &lt;https://w3id.org/kim/lrmi-profile/2021mmdd/&gt;; rel="profile"
```

</section>
~~~

---

If escaping HTML isn't feasible, consider using [`data-include`](https://respec.org/docs/#data-include) with [`data-include-format="markdown"`](https://respec.org/docs/#data-include-format)

~~~html
<!-- in index.html -->
<section data-include="./section.md" data-include-format="markdown"></section>
~~~

~~~md
<!-- in section.md -->
## Foo

```
HTTP/1.1 200 OK
Content-Type: application/ld+json
Link: <https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
```
~~~

**Comment by marcoscaceres** [comment]
@sroertgen, can you try adding "HTTP" at the front of the code block? Ie.,: 

![Screen Shot 2022-03-15 at 2 08 50 pm](https://user-images.githubusercontent.com/870154/158298281-ebb41bdc-cf00-4812-a056-bb8d90359726.png)

This is working for me:
![Screen Shot 2022-03-15 at 2 09 33 pm](https://user-images.githubusercontent.com/870154/158298340-3ecc7508-d9ea-44c5-96cd-0be8179a264c.png)

**Comment by marcoscaceres** [comment]
Oh wait... it's removing the "//"... hmm...

**Comment by marcoscaceres** [comment]
@sroertgen, you can do the following:

```HTML
<pre class="nolinks HTTP">
HTTP/1.1 200 OK
Content-Type: application/ld+json
Link: &lt;https://w3id.org/kim/lrmi-profile/2021mmdd/>; rel="profile"
</pre>
```

Not the best, but should work 🙏

**Comment by sroertgen** [comment]
I can confirm that it's working this way! Thank you!

**Comment by marcoscaceres** [comment]
No problem. I've updated the docs:
https://github.com/w3c/respec/wiki/markdown#links-in-code-blocks

**Comment by renyuneyun** [comment]
As of now (actually for over half a year), this seems to not work again. Escaping won't help. In particular, escaping `<` as `&lt;` will not be recognised. See example below:

``````
- Link `<http://example.com/SomePath>` doesn't work.
- Left-escaped link `&lt;http://example.com/SomePath>` doesn't work.
- Left-right-escaped link `&lt;http://example.com/SomePath&gt;` partially works.

```turtle
:sub :link <http://example.com/BadBoss>;
  :left-escape &lt;http://example.com/SomePath>;
  :left-right-escape &lt;http://example.com/SomePath&gt; .
```
``````

![图片](https://github.com/speced/respec/assets/3293723/78643bee-2fc3-4f96-83a6-fdba497d064a)


Side note: escaping `>` alone will result in some syntactical issues. It's not demonstrated in the example above.
