### ISSUE TITLE
Javascript interference from respec.js

### ISSUE THREAD

**Issue by r12a** [w3c/respec#4089]
[**URL to affected spec or repo**](https://w3c.github.io/bp-i18n-specdev/#ghChecklist)

The button at that location allows people to generate a dump of the do's and don'ts in the document in checklist form, which they can then use for spec reviews.

Clicking on the button fails because of some code in respec.js (!?):

> TypeError: h3s[j].querySelector(...) is null
>     createIssueText https://w3c.github.io/bp-i18n-specdev/make_checklist.js:20
>     onclick https://w3c.github.io/bp-i18n-specdev/#ghChecklist:1
>  TypeError: h3s[j].querySelector(...) is null 
> error { target: Window, isTrusted: true, message: "TypeError: h3s[j].querySelector(...) is null", filename: "https://w3c.github.io/bp-i18n-specdev/make_checklist.js", lineno: 20, colno: 20, error: TypeError, srcElement: Window, eventPhase: 0, bubbles: true, … }
> respec.js:6:10

This is very wierd.  That button in only clicked on long after the page has loaded.  There are no calls to respec.js involved in executing that command.  On the surface it looks rather suspicious – why is some unknown function being called?

I don't know for sure when this started happening.  It used to work fine before.

Please provide a fix, since this feature is important for horizontal review work.

**Comment by sidvishnoi** [comment]
> why is some unknown function being called?

Which function in particular? From the stack-trace, I don't see anything other than `createIssueText` being called, which is coming from `<script src="make_checklist.js"></script>` (line 7, index.html).

From stack-trace, it looks like some some `h3` is missing.

**Comment by sidvishnoi** [comment]
Heh. The section before https://github.com/w3c/bp-i18n-specdev/blob/23a55cc80a0c9dc32d2b9516b0d3410a2b36bde3/index.html#L2745 isn't closed. So, ReSpec converts it into a sub-section. As it's a sub-section, the heading there's not h3, it's h4.
