### ISSUE TITLE
Do not enable ReSpec bubble and/or Save Snapshot until "RESPEC DONE!"

### ISSUE THREAD

**Issue by ddorwin** [w3c/respec#410]
During a bibrefs outage, I found that I could Save Snapshot even though processing was incomplete. I only discovered this when diffing the saved file. When I investigated, I found that the first two RESPEC log messages were present but "RESPEC DONE!" was not. It appeared that processing was hung waiting for the bibrefs server, but everything appeared fine (unless you opened the console and knew to look for "RESPEC DONE!"

To help authors avoid incomplete versions, I propose not enabling the Save Snapshot option until processing is actually complete.

Note: If I recall correctly, the server request eventually timed out. However, I didn't take note of the resulting behavior. If it doesn't already, ReSpec should ensure that such processing step failures are always result in the red error count displayed with the ReSpec bubble.

**Comment by halindrome** [comment]
I feel like there are a few different situations that could effect this.
We can easily use the event mechanism to populate the bubble once the last
done message is displayed.  I will look into it tomorrow.

On Thu, Mar 5, 2015 at 3:50 PM, ddorwin <notifications@github.com> wrote:

> During a bibrefs outage, I found that I could Save Snapshot even though
> processing was incomplete. I only discovered this when diffing the saved
> file. When I investigated, I found that the first two RESPEC log messages
> were present but "RESPEC DONE!" was not. It appeared that processing was
> hung waiting for the bibrefs server, but everything appeared fine (unless
> you opened the console and knew to look for "RESPEC DONE!"
>
> To help authors avoid incomplete versions, I propose not enabling the Save
> Snapshot option until processing is actually complete.
>
> Note: If I recall correctly, the server request eventually timed out.
> However, I didn't take note of the resulting behavior. If it doesn't
> already, ReSpec should ensure that such processing step failures are always
> result in the red error count displayed with the ReSpec bubble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/410>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Seems like our first candidate to use .respecIsReady
