### ISSUE TITLE
Browser support table is rendered wrong without icons

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#4111]
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/pointerevents/

**What happened (e.g., it crashed)?:**

![image](https://user-images.githubusercontent.com/3396686/161067927-d76d3179-fd70-4540-b6dc-d1cb52082fd5.png)

**Expected behavior (e.g., it shouldn't crash):**

Well, with icons...

https://www.w3.org/browser-logos/chrome/chrome.svg doesn't exist, for example.

**Comment by saschanaz** [comment]
It seems #4093 fixed this but 32.1.1 is not being provided by W3C.

**Comment by sidvishnoi** [comment]
@dontcallmedom Can you check why https://www.w3.org/Tools/respec/respec-w3c is not serving the latest ReSpec release? It didn't update on last 2 releases.

**Comment by dontcallmedom** [comment]
Paging @deniak

**Comment by deniak** [comment]
This should now be fixed. The script was still using the old default branch `gh-pages`.

**Comment by sidvishnoi** [comment]
Thanks Denis and Dominique!

Tracking the issue when images fail to load at: https://github.com/w3c/respec/issues/4090
