### ISSUE TITLE
Wrong GitHub label color for some background colors

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#4139]
Via point 5 in https://github.com/w3c/media-source/issues/307

## Description of problem

See [Issue in Media Source](https://w3c.github.io/media-source/#h-issue-0) spec, rendered as image below as spec will likely be updated soon.

![image](https://user-images.githubusercontent.com/1122927/165483416-93445003-2637-42db-9d1b-1ab87b475b16.png)

**What happened (e.g., it crashed)?:**

Contrast for the "agenda" label is wrong. The background color of the agenda label is `#b60205` (i.e. `rgb(182, 2, 5)`) and, on GitHub, the color of the label is white to provide a good enough contrast. Problem is that ReSpec chooses to render the label in black. An obvious workaround is to select another color for the label (which I just did for MSE) but since label colors are randomly attributed when labels are created, that bug probably affects other specs.

I do not know what algorithm GitHub uses to choose the color of the label from its background color but the algorithm that ReSpec uses to determine whether it should use black or white for the label's color seems wrong in that it takes for granted that anything with a red component higher than `128` needs a black color:
https://github.com/w3c/respec/blob/dac6a364151926340b21b760ddd3eb24dc9cd5d9/src/core/issues-notes.js#L301-L304

WCAG techniques include formulas for computing a proper contrast ratio:
https://www.w3.org/WAI/WCAG21/Techniques/general/G18.html#tests

**Comment by sidvishnoi** [comment]
https://stackoverflow.com/a/41491220 seems like a good snippet for reference. (Verified with bg=`#b60205`, fg=`#fff`).
Should update with WCAG21 constants and verify though.
