### ISSUE TITLE
Support Oct 2015 process

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#415]
The current `processVersion` only supports 2014 and I think an older one. But the new pub rules asks for Oct 2015.

**Comment by halindrome** [comment]
Oct 2015?  I feel that is in the future?

On Tue, Mar 17, 2015 at 11:46 AM, Marcos Caceres <notifications@github.com>
wrote:

> The current processVersion only supports 2014 and I think an older one.
> But the new pub rules asks for Oct 2015.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/415>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Argh, I'm high on crack. Never mind.
