### ISSUE TITLE
Discontinued drafts link to a page that doesn't mention that status

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#4152]
## Description of problem

**URL to affected spec or repo:** 

https://www.w3.org/TR/preload/
Generated with ReSpec 24.23.4.

**What happened (e.g., it crashed)?:**

The "W3C Discontinued Draft" text on the second line links to https://www.w3.org/standards/types#DISC, but that page doesn't mention discontinued drafts.

**Comment by marcoscaceres** [comment]
@plehegar, should I add an exception for "W3C Discontinued Draft" or will you include it as part of https://www.w3.org/standards/types?
