### ISSUE TITLE
Support github and updated boilerplate

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#416]
People that don't use mailing lists (that's me!) should be able to list a GH repo as the primary way to provide feedback about a spec. 

As @AFBarstow proposes: 

> The boiler plate asking for feedback via GH and the Status section 
> asking for feedback via p-webapps is certainly suboptimal. AFAIK, 
> PubRules mandates the comment list. If we can't get that restriction 
> lifted, I recommend the relevant text in the SotD clearly state using GH 
> for comments/bugs/issues is _strongly preferred_ and the list should 
> only be used as a `last resort`.

**Comment by plehegar** [comment]
For reference: https://github.com/w3c/specberus/blob/master/lib/rules/sotd/mailing-list.js

**Comment by marcoscaceres** [comment]
Mailing lists are no longer required by the w3c + we now have `github` option.
