### ISSUE TITLE
Inconsistent styling of code links

### ISSUE THREAD

**Issue by mattgarrish** [w3c/respec#4163]
By default, text in `code` elements get styled a reddish color (#c63501).

When using the markdown shorthands to reference elements in the HTML spec, the generated markup is `<code><a>element</a></code>`. These links are blue (#034575). All good.

But when you have text in `code` inside of a link with other text, you get a mix of both colours (i.e., the `code` text is the red colour and the rest of the link text the blue colour). Similarly if you use the pattern `<a...><code>...</code></a>` you get links that are red instead of blue.

If you get a few of these in close proximity, it starts to look very strange. Here's a screenshot from the EPUB 3.3 spec showing how the colours keep changing:

<img width="540" alt="links" src="https://user-images.githubusercontent.com/1565164/169274503-b97bba4f-e05c-4ba0-a27f-6ca551d245a6.PNG">

What I've done for now is add this additional rule to our local CSS to make all `code` in links blue:

```
a code
{
    color: rgb(3,69,117) !important;
}
```

But it would be better if this could be handled by the respec output.

My preference is to have all `code` be blue when it's part of a link, but @iherman may have a different opinion on this and prefer that all `code` be the red colour whether in a link or not.

**Comment by iherman** [comment]
> My preference is to have all `code` be blue when it's part of a link, but @iherman may have a different opinion on this and prefer that all `code` be the red colour whether in a link or not.

That may indeed be my own personal choice; links are underlined in general, so it is enough of a visual clues as far as I am concerned; I prefer to have all code elements be the same colour, regardless of their positions.

That being said, it is my personal opinion, I would not lie down the road on this. What is really of importance in my view is consistency, which is missing now.
