### ISSUE TITLE
gh-contributors list needs escaping

### ISSUE THREAD

**Issue by jnurthen** [w3c/respec#4169]
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/html-aam/

**What happened (e.g., it crashed)?:**

Outputs the following code
`<li><a href="https://github.com/github-actions[bot]">github-actions[bot]</a></li>`

**Expected behavior (e.g., it shouldn't crash):**
It should escape [bot] in the href so it passes the validator

**Optional, steps to reproduce:**

1.  ...

**Comment by jnurthen** [comment]
even better would be to filter out the bots

**Comment by marcoscaceres** [comment]
yeah, good suggestion. Having a generalized filter would be good too (similar to `<rs-changelog>`).

**Comment by jnurthen** [comment]
added postProcess to remove any bots in the contributors list to unblock us until this is resolved.
