### ISSUE TITLE
document.respec.isReady doesn't work

### ISSUE THREAD

**Issue by xfq** [w3c/respec#4170]
## Description of problem

**URL to affected spec or repo:**

Test spec: https://xfq.github.io/testing/document-respec/

Code: https://github.com/xfq/testing/blob/71fac32e78e5c905178f49126f775eceff645b15/document-respec/index.html#L22-L27

**What happened (e.g., it crashed)?:**

I tried to use [document.respec.isReady](https://github.com/w3c/respec/wiki/document.respec), but it doesn't work. Can anyone point me in the right direction?

**Expected behavior (e.g., it shouldn't crash):**

It should output a message to the console.

**Comment by marcoscaceres** [comment]
It's probably better to use https://respec.org/docs/#postProcess

**Comment by marcoscaceres** [comment]
Yeah, I think we deprecated isReady a while ago:

* chore: deprecate respecIsReady in favor of respec.ready (#3090) 

Looks like we forgot to update the docs.

**Comment by xfq** [comment]
I see. Thank you!

BTW, https://respec.org/docs/#core-base-runner-core-base-runner-js also needs updating.

**Comment by marcoscaceres** [comment]
Updated...
