### ISSUE TITLE
Using the command line to build a spec

### ISSUE THREAD

**Issue by xfq** [w3c/respec#4183]
ReSpec seems to support using the command line to build a spec. It would be useful to have an installation instruction as well as an explanation of the options (like [this one](https://tabatkins.github.io/bikeshed/#cli-options) for Bikeshed).

Sorry if it already exists somewhere. I searched https://respec.org/docs/ but didn't get anything that looked promising.

**Comment by sidvishnoi** [comment]
This? https://respec.org/docs/#using-command-line

**Comment by sidvishnoi** [comment]
Above can use some more explanation of course. Like examples, how to override config etc.

**Comment by xfq** [comment]
Sorry, somehow I didn't see this section. Feel free to close this issue. Thank you!
