### ISSUE TITLE
Table and figure anchor link generation

### ISSUE THREAD

**Issue by ProgramMax** [w3c/respec#4222]
Currently, figures and tables can be linked by id. For example, `<a href="#mytable"></a>`. This will replace the link text with the table number, such as "Table 3".

Linking to sections can be done in the other direction, however. If we have `<section><h2>My section</h2></section>` we can link to it by `<a>My section</a>`. Rather than link to the id, we can link to the name. Tables and figures could use the caption & figcaption for this.

Should ReSpec allow linking to tables & figures the same way it can link to sections?

**Comment by danielpeintner** [comment]
I think this feature would be very welcome. Currently, we can link sections, examples etc but not figures/tables.
see some discussions here: https://github.com/w3c/wot-thing-description/pull/1772#issuecomment-1423818693

**Comment by marcoscaceres** [comment]
Unfortunately, we currently don't have anyone doing feature development on ReSpec... so, please feel free to dive in.

**Comment by egekorkan** [comment]
@marcoscaceres , @relu91 from the WoT WG will work on a PR on this.

**Comment by ProgramMax** [comment]
I tried implementing this (over a year later, whoops). I'm not sure this was actually added.

If I'm reading the linked pull request correctly, it adds a self-link. So "Figure 1 *Figure caption here*" becomes "<a href=*self*>Figure 1</a> *Figure caption here*".

But the intention is elsewhere in the document for me to be able to "<a>*Figure caption here*</a>" like we can do with section titles.

Am I reading the pull request correctly? Is this done and I'm doing something wrong when trying to use it?
Thanks!

**Comment by danielpeintner** [comment]
What https://github.com/w3c/respec/pull/4392 does is that it creates a *new* ordered list for figures & tables.

see for example https://github.com/w3c/wot-thing-description/blob/main/index.html#L923-L926

which renders as follows, see https://w3c.github.io/wot-thing-description/#td-core-model

credits go to @relu91

**Comment by sidvishnoi** [comment]
@ProgramMax you can use `[[[#figure-id]]]` syntax to mention a figure. It'll render as 
```html
<a href="#figure-id" title="Figure caption">Figure 1</a>
```

AFAIR, we didn't add caption in linking text (and only `Figure N`) to reduce verbosity as figure caption can be long sometimes.

**Comment by ProgramMax** [comment]
I see. Thank you :)
