### ISSUE TITLE
Subtitles should not use h2

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#423]
According to the HTML5 Recommendation, an hN element must only be used to introduce a section.  In particular, it must NOT be used to markup a subtitle.  ReSpec should not violate this conformance requirement.

http://www.w3.org/TR/html5/common-idioms.html#sub-head

**Comment by darobin** [comment]
The problem isn't on ReSpec's side, it's a pubrules issue. This can be addressed only after https://github.com/w3c/specberus/issues/155 is.
