### ISSUE TITLE
Can't reference HTTP headers exported from other specs

### ISSUE THREAD

**Issue by clelland** [w3c/respec#4233]
## Can't reference HTTP headers exported from other specs

I've been unable to find a way to get ReSpec to reference an HTTP header definition exported from, say, fetch. The refs are picked up by webref [see JSON here](https://github.com/w3c/webref/blob/main/ed/dfns/fetch.json), and are linkable from Bikeshed, so I presume that they're being exported correctly. However, https://respec.org/xref doesn't surface them, and I can't get ReSpec to generate a link.

This is about the shortest conforming document that can demonstrate the issue:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Demonstration of #4233</title>
    <script src="https://www.w3.org/Tools/respec/respec-w3c" class="remove" defer></script>
    <script class="remove">
      var respecConfig = {
        specStatus: "ED",
        edDraftURI: "https://localhost/",
        editors: [{ name: "Your Name", url: "https://your-site.com" }],
        shortName: "demo",
        group: "webperf",
        xref: ["fetch"],
      };
    </script>
  </head>
  <body>
    <section id="abstract"></section>
    <section id="sotd"></section>
    <section id="conformance"></section>
    <section>
      <h2>Demo</h2>
      <p>I'd like to reference <a http-header>Access-Control-Allow-Origin</a>.</p>
      <p>Perhaps as <a>http-access-control-allow-origin</a>.</p>
      <p>Or maybe as [=http-access-control-allow-origin=].</p>
      <p>The best I can do is <a data-cite="!fetch#http-access-control-allow-origin">Access-Control-Allow-Origin</a>.</p>
    </section>
  </body>
</html>
```

A similar Bikeshed document links correctly to the definition in Fetch:

```
<pre class='metadata'>
Title: Demonstration of #4233
Status: ED
ED: https://localhost/
Shortname: demo
Level: none
Editor: Your Name, https://your-site.com
Group: webperf
Repository: https://localhost/ repo
Abstract:
</pre>
<section>
  <h2 id="demo">Demo</h2>
  <p>In bikeshed, I can reference <a http-header>Access-Control-Allow-Origin</a>.</p>
</section>
```

**Comment by marcoscaceres** [comment]
Indeed... @sidvishnoi, are the headers in the database? If so, we should definitely expose them. 

Then reference them with:

```
<a data-xref-type="http-header">Access-Control-Allow-Origin</a>
```

**Comment by sidvishnoi** [comment]
They aren't in our processed database as of now. Will include them. 
Though, not sure which [type-type](https://github.com/w3c/respec-web-services/blob/main/routes/xref/lib/constants.ts) of data they'll be. Probably `CONCEPT_TYPE`. That will impact what shorthand we assign them, if any (maybe `[# Access-Control-Allow-Origin #]`?).

**Comment by sidvishnoi** [comment]
Following now works:
```html
<a data-xref-type="http-header">Access-Control-Allow-Origin</a>
```
