### ISSUE TITLE
Ignore SVG styles and classes

### ISSUE THREAD

**Issue by ahankinson** [w3c/respec#4238]
**Is your feature request related to a problem? Please describe.**

I am trying to embed SVG renderings of music notation into a ReSpec Document. The SVG contains `class` attributes on the elements that intersect with known ReSpec classes (e.g., `.note`), which then processes the SVG and inserts HTML. 

e.g., it will take: 

`<g data-id="n1ck10te" data-class="note" class="note">`

and change this to:

```
<div class="note" role="note" id="issue-container-generatedID-3">
    <div role="heading" class="note-title marker" id="h-note-3" aria-level="5">
        <span>Note</span><!---0.688706%-->
    </div>
    <g data-id="nve1u6i" data-class="note" class=""></g>
</div>
```

This obviously breaks the SVG rendering. I cannot control the output of the SVG and, indeed, `note` seems like a perfectly valid class for music notation renderings.

**Describe the solution you'd like**

The solution might be one, or both of:

 - Ignore all `class` attributes on elements with `<svg>` as an ancestor;
 - Add a CSS class on elements that tells ReSpec to completely skip processing all descendants 

**Additional context**

I can personally see no good reason for ReSpec to be processing anything within an `<svg>` block, so at a minimum it should probably ignore SVG entirely.

**Describe any alternatives you've considered**

I have no work-around. I have tried various combinations of `exclude` or `ignore` classes, but nothing seems to work. I also can't see any obvious way to fix this with a different profile, or plugins, since the processing of these classes runs pretty deep into the core as far as I can tell. 

**Can you or your organization fund the work or help with development?**

Yes, I probably have the skills and can try to implement this, but with two caveats:

1. I am not familiar with the ReSpec codebase, so would need pointers on where to look; and 
2. I would need a design decision from the community on which solution is preferable (or indeed, if another solution is desired)

NB: I apologize if this is a duplicate of a message I sent to the mailing list. That seems to not work very well.

**Comment by sidvishnoi** [comment]
ReSpec can ignore `.note` in SVG here (we can perhaps add a filter using `elem instanceof HTMLElement`): https://github.com/w3c/respec/blob/210492a385948480b71471edd4f0a06338a17a63/src/core/issues-notes.js#L369-L374

But the `.note` CSS class (which comes from [W3C/tr-design base.css](https://github.com/w3c/tr-design/blob/f6a29f49ffc79a2c16d3c3210436583c4e06120b/src/base.css#L872-L880)), will continue to apply styles unless we increase its specificity. Alternatively, you can override the W3C styles in your document.

Also consider if you can rename the `.note` classes in SVG to something else in a [`preProcess`](https://respec.org/docs/#preProcess) or `postProcess` step. This, of course, won't work if `.note` in SVG is to be styled differently and you can't update the CSS there.

**Comment by ahankinson** [comment]
I'm reticent to post-process the `.note` class in the SVG, since it's used by the notation renderer (https://www.verovio.org/index.xhtml) to reference shapes and glyphs. So that would probably break lots of things.

I have no problem overriding the `.note` CSS class locally to make it work; I will experiment with that.

If I am successful in making the `issues-notes.js` change more specific, should I open a PR with the change against core?

Thank you for your help!

**Comment by sidvishnoi** [comment]
> If I am successful in making the issues-notes.js change more specific, should I open a PR with the change against core?

Sure!
