### ISSUE TITLE
Specs missing from XRef

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#4243]
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/json-ld-framing/

**What happened:** Cross references which resolved when published as a recommendation no longer resolve.

**Expected behavior:** Citations of the form `{{RemoteDocument/`documentUrl`}}` should result in a appropriate link to the defining spec.

Looking at [Xref](https://respec.org/xref/), the short-names referenced in the ReSpec config no longer appear. `xref: ["json-ld11", "json-ld11-api", "json-ld11-framing"]`. This cause all specifications accessing terms/WebIDL in any of these specs to not be treated properly. Other parts of the spec work around this using `<a data-cite="JSON-LD11-API#dom-remotedocument-documenturl">documentUrl</a>`, for example, but this doesn't result in appropriate styling and shouldn't be necessary. For some reason, these specs were dropped from SpecRef.

**Optional, steps to reproduce:**

1.  See ReSpec bug

Please forward to an appropriate repository, if this is not the right location

**Comment by gkellogg** [comment]
The xrefs are resolving now, thanks. Perhaps due to @tidoust's updates to browser-specs. Feel free to close the issue, if this completes the resolution of the issue.

**Comment by sidvishnoi** [comment]
Thanks @tidoust!
