### ISSUE TITLE
ReSpec is down?

### ISSUE THREAD

**Issue by ashimura** [w3c/respec#4258]
## Description of problem

It seems ReSpec is not working now (20:00 JST, 7 Sep 2022).

Please see, e.g.:
  https://w3c.github.io/wot-architecture/

**What happened (e.g., it crashed)?:**

ReSpec Error on the missing "group" parameter, which is actually specified.

Also no CSS label for the document status, e.g., "Editor's Draft", is shown on the left top.

In addition, the saved file name using the "ReSpec" menu is "base-wot-arhcitecture11-20220901.html".

**Comment by dontcallmedom** [comment]
respec.org (which provides the API end point for a number of respec features) is down (503)

**Comment by sidvishnoi** [comment]
Dreamhost (respec.org's host) was down today: https://www.dreamhoststatus.com/pages/history/575f0f606826303142000510

And it didn't restart server automatically when things became ok. I'll manually restart the server and close the issue when status is ok.

**Comment by sidvishnoi** [comment]
All is good now 🕊️
