### ISSUE TITLE
Wrong instructions on warnings and errors in developmentguide

### ISSUE THREAD

**Issue by CHAOSdonut** [w3c/respec#4266]
in the development guide under "Warning users of errors"  it is stated that you should use:
`pub("warn", "Markdown that represents a warning");`
to give users a warning. 

This does increment the warning counter but makes it unclickable. Clicking the button gives the following error in the browserconsole:
`TypeError: Cannot read properties of null (reading 'childNodes')
    at HTMLButtonElement.<anonymous> (ui.js:159:49)`

Giving the `pub("warn")` a `new RespecError` instead of a string fixes this issue but this is not documenten in the development guide.

**Comment by sidvishnoi** [comment]
Thanks @CHAOSdonut! I've [updated](https://github.com/w3c/respec/wiki/Developers-Guide/_compare/947bc7460dada2e8bf192e784b20dcaf5d4f27e1...e359ef2a318939e51008adf11c58929df76c6edd) the docs.
