### ISSUE TITLE
revisedRecEnd should only be needed for proposed amendments, not candidate ones

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#4291]
## Description of problem

[The Rec rendition of the WebRTC editors draft](https://w3c.github.io/webrtc-pc/webrtc.html?specStatus=REC) flags an error because the spec as candidate corrections but no `revisedRecEnd` date configured.

**Expected behavior (e.g., it shouldn't crash):**
Since the document only has *candidate* corrections, not *proposed* corrections, that configuration should not be needed, since only the latter goes through AC review.

**Comment by siusin** [comment]
Same issue here:
https://github.com/w3c/html-aria/actions/runs/3417604916/jobs/5688930947#step:3:515
