### ISSUE TITLE
Respec insertion of `<abbr>` in SVG hides the text in the abbr

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/respec#4334]
## Description of problem

When Respec wraps abbreviation text in an SVG inside an `<abbr>` element that text disappears.

**URL to affected spec or repo:**

https://github.com/w3c/dapt/pull/86 - unfortunately the PR Preview is broken, so you need to check out the branch to see this happening locally, and remove the worksaround `class="exclude"` on the DAPT abbreviation in `index.html`.

**What happened (e.g., it crashed)?:**

When the abbreviation "DAPT" is defined in the Respec document, and a `<text>` element containing "DAPT Script" is included in an SVG figure, the SVG only renders the text "Script", because the text "DAPT" was wrapped in an `<abbr>`.

**Expected behavior (e.g., it shouldn't crash):**

The text "DAPT Script" should appear, and there should be no `<abbr>` elements inserted into the SVG.

_Possibly_ some alternative to `<abbr>` in SVG is possible, like a hover-over tooltip.

**Optional, steps to reproduce:**

1.  Create a Respec document that defines an abbreviation using an `<abbr>` element, e.g. for the text "DAPT".
2.  Create an SVG with a `<text>` element that includes the abbreviated text (e.g. "DAPT Script").
3.  Include the SVG in the Respec document as a `<figure>` containing a `<div data-include="path/to/figure.svg"></div>` to bring the SVG document in.
4.  View the document: the abbreviated text inside the SVG is wrapped inside an `<abbr>` element, which is not rendered.

**Things I tried:**

I tried to add `class="exclude"` on the `<div>` that includes the SVG, and I tried wrapping that `<div>` in another `<div class="exclude">` but neither thing stopped the Respec script from finding and wrapping the abbreviated text.

I successfully stopped Respec from replacing the abbreviated text throughout the whole document, including the SVG, by adding `class="exclude"` to the originating abbreviation, but that is a non-ideal solution.

**Comment by marcoscaceres** [comment]
I guess it would be prudent to check namespace (and not touch things not in the HTML namespace)... which namespace is the abbr in?

**Comment by sidvishnoi** [comment]
Our inlines parser is a bit to aggressive here.

**Comment by nigelmegitt** [comment]
> I guess it would be prudent to check namespace (and not touch things not in the HTML namespace)... which namespace is the abbr in?

The inserted `<abbr>` is not qualified with a namespace prefix, so it'll be in the SVG default namespace, in this case `http://www.w3.org/2000/svg` - are you suggesting that if in an SVG, it should be inserted in the [HTML namespace](https://infra.spec.whatwg.org/#html-namespace)? I did not try testing that, I guess it _might_ work, but I would not expect any difference in rendering behaviour, since as far as I know UAs don't expect an HTML element in the middle of SVG content.

**Comment by sidvishnoi** [comment]
Might be enough to add an exclusion here: https://github.com/w3c/respec/blob/5d1999c46e58c34d32f26c84b362df394f318325/src/core/inlines.js#L276-L280

Will have to test. I might have some time this weekend.
