### ISSUE TITLE
Figure out why netlify build is breaking 

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#4339]

**Comment by marcoscaceres** [comment]
I got an email a few weeks ago that saying that it had been disabled? (by you 🙈)

**Comment by sidvishnoi** [comment]
It was broken and I didn't like the red cross in CI, so I disabled it temporarily 🐼

**Comment by sidvishnoi** [comment]
Had to update Node.js in Netlify. Added [`NODE_VERSION`](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) env var to do that.
