### ISSUE TITLE
REC with changes failed Pubrules' check.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/respec#4340]
https://github.com/w3c/respec/blob/4cf00601ab33e355b8caf22b33588b9676beb455/src/w3c/templates/sotd.js#L463-L465

The document generated by former code looks like:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/8498677/207564219-69c07473-922e-4a23-bca1-d7c7290f5a64.png">

There's a trailing space at the end of `</a>`.

Found when debugging  https://labs.w3.org/echidna/api/status?id=2597b610-fff6-4088-997a-9413e2809730

**Comment by sidvishnoi** [comment]
Released in [`v32.5.1`](https://github.com/w3c/respec/releases/tag/v32.5.1)
