### ISSUE TITLE
Self bibliography reference results in ReSpec error "ReSpec doesn't support expanding this kind of reference."

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#4362]
## Description of problem

When using a common file to reference documents in a series, one of the document references is inevitably to itself.
This results in a ReSpec error relating to a "ReSpec doesn't support expanding this kind of reference" exception from anchor-expander.js.

**URL to affected spec or repo:** https://github.com/gkellogg/rdf11-wg/rdf-concepts/ (eventually, https://github.com/w3c/rdf-concepts/).

**What happened (e.g., it crashed)?:** It gives the error "ReSpec doesn't support expanding this kind of reference" which is misleading.

**Expected behavior (e.g., it shouldn't crash):** It should recognize the entry and perform appropriate expansion.

**Optional, steps to reproduce:**

Pretty obvious, when you load.

Note that the ultimate home for this is https://github.com/w3c/rdf-concepts/spec. I created an included file [related.html](https://github.com/gkellogg/rdf11-wg/blob/main/related.html) which lists the related specs, and bibliography entries in [local-biblio.js](https://github.com/gkellogg/rdf11-wg/blob/main/local-biblio.js). When I replaced the content of one (say, RDF12-CONCEPTS) with `{aliasOf: "RDF11-CONCEPTS'}` there was no error.

If there's a best practice for displaying all documents in a series, including the current document, I couldn't find it in the Wiki.

**Comment by gkellogg** [comment]
No in https://github.com/w3c/rdf-concepts, and failing Echidna build gives an error to https://github.com/w3c/rdf-concepts/pull/1.

**Comment by gkellogg** [comment]
Okay, figured out the root of the problem, which requires some different solution for referencing all the documents in a series. The root of the problem is that the document includes its own citation (`[[RDF12-CONCEPTS]]` in this case). There is some pubsubhub "end-all" logic to remove the actual references, but the bibliographic entry gets created. In [anchor-expander](https://github.com/w3c/respec/blob/main/src/core/anchor-expander.js), this ends up trying to expand find references to that entry, which includes the **This Version** link in the document header, which is an anchor element (`a`), the logic fails because the `matchingElement.localName` goes into the default case, which generates the error.

I'm in search of prior examples for document series that try to do something similar and skip the entry where the citation is for `respecConfig.shortName`. But, even though documents probably shouldn't cite themselves, it probably shouldn't result in such an opaque error.

**Comment by gkellogg** [comment]
Perhaps if references such as `[[RDF12-CONCEPTS]]` used within the defining document did not create a bibliographic entry, and instead linked to the current document, it could avoid such problems. This could be a linter warning that could be specifically ignored, if desired.

**Comment by gkellogg** [comment]
For future reference, I solved this by using a `data-transform` on each entry to a function that checks to see if it contains `respecConfig.shortName` and do some replacement in that function, which happens before the bibliography is created. Note that [`data-transform`](https://github.com/w3c/respec/wiki/data-transform) is marked as deprecated, but I couldn't have done this with [`data-oninclude`](https://github.com/w3c/respec/wiki/data-oninclude), as it's not related to `data-include`.

**Comment by sidvishnoi** [comment]
Thanks for investigating @gkellogg! Sent a PR to fix.
