### ISSUE TITLE
Microsyntax for "abstract-op" links?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#4376]
Right now, when using the `[= =]` microsyntax for links, it only works if the target is a `dfn` definition; I think this makes sense when there exists a dedicated microsyntax for other types of definitions (e.g. `{{ }}`), especially when these other types are of a different nature (i.e. more code than prose).

But the type [`abstract-op`](https://speced.github.io/bikeshed/#dfn-types) is more on the prose side and doesn't have a microsyntax, so I think it should be possible to use  `[= =]` links for them; the alternative would be to use the [microsyntax that bikeshed uses for them `[$ $]`](https://speced.github.io/bikeshed/#autolink-wrappers).

**Comment by sidvishnoi** [comment]
With https://github.com/w3c/respec-web-services/pull/207, we made `abstract-op` to be same as `dfn`, so it should be possible to use `[= =]` (i.e., there's no "abstract-op" in ReSpec xref database.
Is there something that's not linking right?

**Comment by dontcallmedom** [comment]
That only works for links to outside of the spec, but not for links inside the spec itself I believe.

The following micro-spec illustrates it as it triggers a linking error.
```html
<!doctype html>
<html>
  <title>Element definition</title>
    <script class="remove">
      var respecConfig = {
        specStatus: "base",
        shortName: "foo",
        editors: [{name: "foo"}],
      };
    </script>
    <script src="https://www.w3.org/Tools/respec/respec-w3c.js"></script>
  </head>
  <body>
    <section>
      <dfn class="abstract-op">define an algorithm locally</dfn>
      [= define an algorithm locally =]
    </section>
  </body>
</html>
```

**Comment by sidvishnoi** [comment]
Ah, that makes sense.
