### ISSUE TITLE
Document `lint-ignore`, `no-unused-dfns`, and `informative-dfn`

### ISSUE THREAD

**Issue by xfq** [w3c/respec#4396]
## Description of problem

**What happened (e.g., it crashed)?:**

`lint-ignore`, `no-unused-dfns`, and `informative-dfn` are not mentioned in https://respec.org/docs/

They are used in some specs, but currently the only way to understand what they do is to remove them, and then read the ReSpec warning. If they are documented, there is no need for this.

**Expected behavior (e.g., it shouldn't crash):**

They should be documented in https://respec.org/docs/

/cc @r12a

**Comment by caribouW3** [comment]
Hi. I have added the doc in https://github.com/w3c/respec/wiki/
