### ISSUE TITLE
Converting MA to RFC2119 tag interferes with Unicode names

### ISSUE THREAD

**Issue by r12a** [w3c/respec#4426]
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/afrlreq/nko/#fig_joining_forms  - middle of the table, the line with U+07E1 NKO LETTER MA

**What happened (e.g., it crashed)?:**

Respec added `<em class="rfc2119">MA<!---0.084743%--></em>` around the word MA, causing it to look italicised.

This is set by the following line of code:
https://github.com/w3c/respec/blob/6f6032fa1cb0207c0d14a62c5f9810b9cd6115c3/src/core/inlines.js#L34

**Expected behavior (e.g., it shouldn't crash):**

It's not clear why the Y in MAY should be optional.  In this case it causes a problem by being overly clever.

Can we remove the question mark from the regex?

(Note to self: error reported by Charles Riley.)

**Comment by sidvishnoi** [comment]
Looks like a regression from #3716, the `?` is certainly a typo.
PR welcome, otherwise I'll find some time tomorrow to send fix and release.

**Comment by r12a** [comment]
Thanks @sidvishnoi . I'm still seeing the problem. Is that because the full release is still pending?  If so, approximately how long until the problem is fully fixed?

**Comment by r12a** [comment]
Fixed confirmed. Thanks.
