### ISSUE TITLE
the "Terms defined by reference" index should index `dfn[data-cite]`

### ISSUE THREAD

**Issue by pchampin** [w3c/respec#4438]
## Description of problem

**URL to affected spec or repo:** 

https://w3c.github.io/rdf-semantics/spec/#index-defined-elsewhere

**What happened (e.g., it crashed)?:**

The "Terms defined by reference" section contains all the texts of `<a data-cite="...">` elements, an none of the texts of `<dfn data-cite="...">` elements.

**Expected behavior (e.g., it shouldn't crash):**

It seems to me that its should be the opposite (including the `dfn`s, and not the `a`s). After all, the section is about "Terms **defined** by reference".

**Optional, steps to reproduce:**

1.  The following text in  a new respec document
```html
<a data-cite="RDF11-CONCEPTS#dfn-subject">subject</a> <dfn data-cite="RDF11-CONCEPTS#dfn-predicate">predicate</a>
```
2. insert `<section id="index"></section>` in that document
3. open that document and jump to the index section
4. it will contain the following entry:
    * RDF 1.1 Concepts and Abstract Syntax
        * subject

(but not "predicate")

NB: this bug could be the root cause of #4437

**Comment by sidvishnoi** [comment]
I think the heading "Terms defined by reference" is a bit misleading. "Externally defined terms referenced" would be more correct here.

Though, I agree `<dfn data-cite>` entries should be added to the index (while retaining `<a data-cite>` ones as is.

**Comment by pchampin** [comment]
Thanks for this quick fix!

> while retaining `<a data-cite>` ones as is.

I'm still not convinced. In our docs we have examples that look like this:
```html
... as described in <a data-cite="SOMESPEC#sec3">Section 3</a> of [[SOMESPEC]].
```
which results in "Section 3" appearing in the "Terms defined by reference" section...

On the other hand, for actual definitions, we use `<dfn data-cite="...">defterm</dfn>` in one place of our document, then `<a>defterm</a>` anywere else.

To sum it up, I consider that
* there are use-cases for `<a data-cite>` that does not justify inclusion in the "Terms defined by reference" sections, and
* the cases that justify inclusion in the "Terms defined by reference" sections can be covered by `<dfn data-cite>`.

**Comment by tabatkins** [comment]
For reference, Bikeshed has the same behavior as ReSpec here - external links add entries to the "Terms Defined By Reference" section.

(But I'm not sure what ReSpec's behavior is wrt `data-cite` - Bikeshed doesn't have the same syntax. It sounds like it might be closer to a biblio reference? Biblio links (and section links, which are a subset of biblio links) don't add entries to this index in Bikeshed; they just trigger entries in the biblio section instead.)

**Comment by sidvishnoi** [comment]
`<a data-cite>` ones are listed in "Terms Defined By Reference" as ReSpec doesn't know whether the term linked is a dfn or section. It treats everything as a "dfn". Although we now have xref, `<a data-cite>` is still the way to link to things that are not in xref database.

We can recommend `<dfn data-cite>` for definition references and `<a data-cite>` for other references, but removing `<a data-cite>` links from references could be a annoyance for spec-authors, specially for old specs that haven't migrated to xref. I don't have any strong opinions here.

We could however support `<a data-cite="..." data-link-type="heading">` to explicitly declare the link as a heading/section/not-dfn, and exclude them from Index. (Related: https://github.com/w3c/respec/issues/3680), or use a micro-syntax to create such references.

**Comment by gkellogg** [comment]
It would be nice to have something like `<a data-cite="..." data-noindex>` which could be more granular than `data-link-type="heading"`, but both would solve this specific issue. For specs that really don't want to consider referenced terms as being "defined by reference", they could either use this pattern universally, or do something like <dfn data-cite="..." data-noexport>`, if that would also keep it out of the index.

I view the definition indexes as being largely useful for spec development rather than eventual publication as a Rec, but it would be nice if they could be use to express the editor's intent.
