### ISSUE TITLE
Link button in IDL definitions

### ISSUE THREAD

**Issue by g-ortuno** [w3c/respec#444]
Is there anyway we can add link buttons to IDL definitions to get the url to the IDL faster? Every time I want to reference the IDL I'm looking at, I have to open the inspector copy the id and paste it into the address bar.

**Comment by marcoscaceres** [comment]
@g-ortuno sounds like a good idea.

**Comment by darobin** [comment]
+1
Now of course someone has to code it :) Did you have a specific UI in mind? I ask because there can be a fair number of anchors in an IDL block, we don't want to crowd it.

(Side rant: this really should be a browser feature...)

**Comment by marcoscaceres** [comment]
> (Side rant: this really should be a browser feature...) 

Oh?

**Comment by marcoscaceres** [comment]
Browser-feature-wise, copy/paste on the IDL blocks would be nice. We can expose these as links, then you should be able to copy/paste them.

**Comment by darobin** [comment]
On 04/06/2015 22:20 , Marcos Caceres wrote:
>     (Side rant: this really should be a browser feature...)
>
> Oh?

Yeah: you have an ID, you should be able to link to it. Right-click -> 
Copy Link to Element (or whatever) ought to do the trick. But that's 
unrelated :)

-- 
Robin Berjon - http://berjon.com/ - @robinberjon

**Comment by devanshbatra04** [comment]
@marcoscaceres can I work on this?

**Comment by marcoscaceres** [comment]
Sure, but only after the other PRs have been merged.
