### ISSUE TITLE
Preview and Diff functions fail with data-include

### ISSUE THREAD

**Issue by jandrieu** [w3c/respec#4480]
## Description of problem

When using data-include, it fails to render in Github previews and diffs.

**URL to affected spec or repo:**

https://github.com/w3c/vc-use-cases/pull/145

**What happened (e.g., it crashed)?:**

The rendered html shows errors because the relative URL of the include points to files that don't exist.

**Expected behavior (e.g., it shouldn't crash):**

The included files should render

**Optional, steps to reproduce:**

1. Add a data-include attribute that includes a local file, merge it in.
2. Verify that the merge is in the current rendering (github.io)
3. Make a new branch, somewhere. 
4. Change a file. Commit that to the new branch
5. Make a PR to merge new branch
6. Click on the preview or diff link in the PR review

You'll note that the data-includes do not get rendered in the preview.

The underlying cause is that the relative URL takes on the base of the preview, which isn't the branch.

I don't know how the preview and diff functions are configured, but it seems that code could set the base using a URL that points to the branch that is being merged in.

Are those preview and diff functions under the ReSpec umbrella or something else?

**Comment by sidvishnoi** [comment]
@jandrieu This belongs to [tobie/pr-preview](https://github.com/tobie/pr-preview).

**Comment by jandrieu** [comment]
For my own sanity, here's the issue over there. https://github.com/tobie/pr-preview/issues/144
