### ISSUE TITLE
Wrong example in https://github.com/w3c/respec/wiki/index

### ISSUE THREAD

**Issue by rakuco** [w3c/respec#4487]
The [`<index>` documentation](https://respec.org/docs/#id-index) in https://github.com/w3c/respec/wiki/index has two examples, and the second one seems to have been copy-pasted from https://github.com/w3c/respec/wiki/idl-index -- it is using `<section id="idl-index" class="appendix">` rather than `<section id="index" class="appendix">`

**Comment by sidvishnoi** [comment]
Fixed. Thanks for reporting!
