### ISSUE TITLE
scroll-to can happen BEFORE respec is really done

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#452]
Currently one of the last things ReSpec does is look at the request URI for a fragment identified.  If there is one, then it attempts to position the view of the user agent at that location.

The problem arises of a spec subscribes to the end-all event.  Since the scroll handing happens BEFORE end-all, any modifications to the document during end-all processing will be missed!

In a separate branch I have added an event that happens even AFTER end-all.  This is just to handle aria-busy.  My proposal is that we change the scroll handling to be an event handler that subscribes to the new event and it does the scrolling when that happens.  Should solve the problem.

**Comment by halindrome** [comment]
ALSO, the scrolling can happen before data-include loads are complete if data-include-sync is not specified.  We should track async data-includes and only attempt the scrolling once all of those have actually finished.

**Comment by patrickhlauke** [comment]
The most aggravating part seems to be that for some reason, using Chrome, if the scrolling happened before everything was finished (meaning that the final scroll position does not match the fragment identifier), hitting ENTER in the url bar again does not then jump to the right place, but seems to actually reload the page (which then does the wrong scrolling again). tl;dr: in Chrome, any url with a fragment identifier is borked completely.

**Comment by simevidas** [comment]
I have actually proposed an intervention in Chrome ([see here](https://groups.google.com/a/chromium.org/d/msg/intervention-dev/pcddUMxqbXg/V6-zPebFAgAJ)) to fix this issue, unaware that it’s an issue with ReSpec.

Being able to link to specific sections in W3C specs is an *essential* functionality — reading specs is “hard enough” without having them load at a random position completely unrelated to the URLs fragment  — so it’s worth prioritizing (and hotfixing) this issue, I think.

**Comment by marcoscaceres** [comment]
I agree. I'm sick of the FOUC and this issue. I'm going to bump them up the priority list. Also, we need help people stop publishing ReSpec source docs and set up auto publish.

**Comment by halindrome** [comment]
Yes - auto-publish.  ReSpec source should not be viewed by real people.
It's for development.

On Mon, Apr 25, 2016 at 9:04 PM, Marcos Cáceres <notifications@github.com>
wrote:

> I agree. I'm sick of the FOUC and this issue. I'm going to bump them up
> the priority list. Also, we need help people stop publishing ReSpec source
> docs and set up auto publish.
>
> Sent from my iPhone
>
> > On 26 Apr 2016, at 11:37 AM, Šime Vidas <notifications@github.com>
> wrote:
> >
> > I have actually proposed an intervention in Chrome (see here) to fix
> this issue, unaware that it’s an issue with ReSpec.
> >
> > Being able to link to specific sections in W3C specs is an essential
> functionality — reading specs is “hard enough” without having them load at
> a random position completely unrelated to the URLs fragment — so it’s worth
> prioritizing (and hotfixing) this issue, I think.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
>
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/452#issuecomment-214585169>
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> Yes - auto-publish. ReSpec source should not be viewed by real people. It's for development.

So, computers are not going to help here. We will need to go out to individual specs and help them move off github pages.

**Comment by halindrome** [comment]
By providing an out-of-the-box solution that helps generate static versions
to the gh-pages branch whenever the master is updated or something, using
travis?  'cause that would be super handy.

On Mon, Apr 25, 2016 at 9:53 PM, Marcos Cáceres <notifications@github.com>
wrote:

> Yes - auto-publish. ReSpec source should not be viewed by real people.
> It's for development.
>
> So, computers are not going to help here. We will need to go out to
> individual specs and help them move off github pages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/452#issuecomment-214592201>
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> By providing an out-of-the-box solution that helps generate static versions to the gh-pages branch whenever the master is updated or something, using travis? 'cause that would be super handy.

Better would be Echidna integration. There is no need to have a gh-pages branch at all for anything apart from "unofficial" drafts.

**Comment by halindrome** [comment]
That's only true for w3c specs. Others use this tool.

**Comment by halindrome** [comment]
Actually - I have derailed this issue.  Sorry!  Now that we have a promise wrapper available in ReSpec, can't we actually just fix this by doing the final positioning after ReSpec (and anything ReSpec ends up calling) is done?
