### ISSUE TITLE
xref for "xr-standard" gamepad mapping not working

### ISSUE THREAD

**Issue by nondebug** [w3c/respec#4535]
## Description of problem

This PR is blocked on this issue:
https://github.com/w3c/gamepad/pull/168

**What happened (e.g., it crashed)?:**

  Error: ROR] Couldn’t find “&quot;xr-standard&quot; gamepad mapping“ in this document or other cited documents: [dom], [hr-time], [html], [infra], [permissions-policy], [webidl], and [webxr-gamepads-module].

**Expected behavior (e.g., it shouldn't crash):**

Working xref

**Optional, steps to reproduce:**

1.  ...

**Comment by sidvishnoi** [comment]
With some bisecting, I was able to find this regress in https://github.com/w3c/respec/pull/4439. Now onto debugging...
