### ISSUE TITLE
W3C PER status was deprecated in 2017

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#4549]
## Description of problem

W3C PER status option is confusing for spec editors since it's no longer a valid W3C document status.

**URL to affected spec or repo:**

https://github.com/w3c/epub-specs/pull/2575#issuecomment-1735422916

**What happened (e.g., it crashed)?:**

[Proposed Edited Recommendations ](https://www.w3.org/2015/Process-20150901/#revised-rec) were removed from the [W3C Process in 2017](https://www.w3.org/2017/Process-20170301/#revised-rec).

This is not a bug per say nor a feature request. But having invalid W3C document status in respec leads to additional confusion on how to maintain W3C Recommendations.

**Expected behavior (e.g., it shouldn't crash):**

https://github.com/w3c/respec/blob/bf44a988cbdc545bb2479918790dc4725752cb74/src/w3c/headers.js#L134 must not list PER as an option.

**Optional, steps to reproduce:**

1.  Use specStatus: "PER"
2. Don't get an error

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/respec/pull/4584
