### ISSUE TITLE
respec.org SSL certificate has expired

### ISSUE THREAD

**Issue by anatoly-scherbakov** [w3c/respec#4568]
## Description of problem

**URL to affected spec or repo:**

https://respec.org

**What happened (e.g., it crashed)?:**

The site is expected to load.

Instead, it shows:

![image](https://github.com/w3c/respec/assets/2282888/6c882ef9-a2c7-4932-a873-9fde7f1f2d06)

Reason is expired certificate:

![image](https://github.com/w3c/respec/assets/2282888/95dcd2a7-e43a-4bcb-b4bb-1361255a69a7)

**Comment by sidvishnoi** [comment]
cc: @marcoscaceres

**Comment by sidvishnoi** [comment]
Fixed now, thanks to Marcos.

**Comment by marcoscaceres** [comment]
I complained (again) to Dreamhost... this should never happen as SSL certs from Let's Encrypt.
