### ISSUE TITLE
Problem with sequence parametrized types with multiple types

### ISSUE THREAD

**Issue by arunranga** [w3c/respec#457]
I'm obliged to specify something that looks like this:

Promise &lt;sequence&lt;(File or Directory)&gt;> getFilesAndDirectories()

but the above doesn't quite work in respec.

(This will go away when have AsyncIterator or Observable, which are being discussed in ES6/ES7 -- see w3c/filesystem-api#4 for more context for why constructs such as the above is needed.)

Thanks for any help in advance :)

**Comment by arunranga** [comment]
This might be a dup of w3c/respec#331 but a fix would be cool still.

**Comment by marcoscaceres** [comment]
closing as dup of w3c/respec#331
