### ISSUE TITLE
Member-SUBM specStatus for Member Submissions somewhat borked

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#458]
The documentation mentions a "Member-SUBM" specStatus but that status does not really do the job:

1. Member Submissions usually have completely different copyrights. ReSpec uses the default W3C copyright for the spec, as explained in the documentation. However, setting `additionalCopyrightHolders` will not replace the whole copyright, and `overrideCopyright` is not documented (on purpose?)
2. The right "Member Submission" logo is not automatically added. This can of course easily be achieved thanks to the `logos` setting.
3. ReSpec complains about the document being "on track but no previous version" and adds an empty "Previous Version" in the links section.
3. The SoTD boilerplate is not the right one although note it is not really possible to generate the "right" boilerplate since the links it contains include a link to the Team Comment that cannot be known a priori.

For info, the Member Submission template with the SoTD boilerplate is at:
http://www.w3.org/2005/07/pubrules?uimode=filter&docstatus=mem-subm#sample-template

I am not sure whether this issue should be treated as a request to change the code of ReSpec or as a request to document the limitations. A Member Submission does not really need to be iterated over once submitted, so it's not such a big deal if some manual editing needs to take place right before the submission happens.

**Comment by darobin** [comment]
Does #459 fix all the issues you had? If so, please close this. Thanks!

**Comment by tidoust** [comment]
All issues fixed for me, thanks!
