### ISSUE TITLE
problems generating h1 from title

### ISSUE THREAD

**Issue by r12a** [w3c/respec#460]
http://w3c.github.io/clreq/ (and its TR equivalen) needs to add markup to the `h1` to apply language information, (a) so that chinese fonts are used for the ideographs, and (b) to enable the language in the title to be filtered by language.

since the `title` element takes only plain text, generating the `h1` from it, as respec does, is problematic.

i can think of other scenarios where you might possibly want to style the `h1` text, for just one example. see the `h1` for http://www.w3.org/International/questions/qa-navigation-select

can someone please de-couple this arrangement if there is an `h1` defined in the document already.

**Comment by marcoscaceres** [comment]
I agree that if there is already a H1 we should just use that.

**Comment by marcoscaceres** [comment]
@sidvishnoi has tests for this in #1567. @shikhar-scs, can you work together on this with @sidvishnoi? I guess we also need a test for the sub-heading.

**Comment by shikhar-scs** [comment]
> can you work together on this with @sidvishnoi?

collaboration is always good to have. :smiley:  However, if it were not for my exams, I would have completed this work by myself. :sweat_smile: .

So yeah, @sidvishnoi please have a look at my PR #1516 . It has been reviewed by @marcoscaceres and thus, you can push your work related to the tests at https://github.com/shikhar-scs/respec/tree/h1-and-title, refactoring it according to my code [here](https://github.com/w3c/respec/pull/1516/files). 

Meanwhile, I'll write the tests for the sub-heading :+1: Thanks for the help :)
