### ISSUE TITLE
markup obliterated in .sec-title

### ISSUE THREAD

**Issue by r12a** [w3c/respec#461]
inline markup in heading text that is reflected in a `span.sec-title` link is removed.

there several reasons why it is appropriate to keep the inline markup: these include semantic issues such as bidi support, use of the translate flag on keywords, language markup, as well as any other stylistic markup. Furthermore, this messes up language selection in the chinese and korean layout requirements docs on TR. If you go to [http://localhost/git/clreq/#writing_modes_in_chinese_composition](http://localhost/git/clreq/#writing_modes_in_chinese_composition), click on the zh button in the top right, and look at the 2nd note, you will see

中文所使用的汉字与标点符号，原则上都是正方形的文字，自活字排版时代起，无论直、横排，都能使用相同的活字排列。但部分标点符号需配合文字书写方向调整字面分布及方向，见**3.1.2 Sizes and positions of Punctuation Marks 標點符號的字形、尺寸與字面分布 標點符號的字形、尺寸與字面分布**标点符号与 其排版节的详述。

instead of

中文所使用的汉字与标点符号，原则上都是正方形的文字，自活字排版时代起，无论直、横排，都能使用相同的活字排列。但部分标点符号需配合文字书写方向调整字面分布及方向，见3.1.2 **標點符號的字形、尺寸與字面分布**标点符号与 其排版节的详述。

can someone please fix this asap, so that it doesn't just extract the textContent.

**Comment by r12a** [comment]
note, btw, that figure references do retain the inline markup.

**Comment by marcoscaceres** [comment]
As the document is gone, and this code was refactored, I'm going to assume this is fixed now.

**Comment by r12a** [comment]
Fwiw, i fixed the link. This was asking for respec to figure out what language the text was in, then choose the section title on that basis, but i think the new approach is ok (all 3, in this case, languages are presented in the link text by default).
