### ISSUE TITLE
Prepare code for new publication process (2015)

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#462]
respec needs to get ready for:
[[
Any group who was publishing under the 2014 Process should start publishing under the 2015 Process as of 1 September 2015.
]]

**Comment by plehegar** [comment]
See also https://github.com/w3c/echidna/issues/213

**Comment by plehegar** [comment]
See also https://github.com/w3c/specberus/issues/218

**Comment by marcoscaceres** [comment]
closed via #463
