### ISSUE TITLE
Revert the change that added warnings for use of the "title" attribute with dfn elements

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#466]
I strongly disagree with the change made in PR #456 that causes Respec to emit warnings for use of the `title` element with `dfn` elements, and I request that the change be reverted.

That change conflicts with document-conformance requirements in the HTML spec in that it tries to make a particular markup case a conformance error despite the fact that the HTML spec does not in any way define that case as an error.

Along with that, it causes Respec authors to get spurious errors when processing their documents.

Related comments also at https://github.com/w3c/respec/commit/85e2f950d69028a7300033fa05aee3281a64c0db#commitcomment-12459055

**Comment by halindrome** [comment]
We will discuss your request.  However, note that reverting this change
would not effect the warnings that the HTML validator might throw.  The
change that implemented the use of lt was in separate pull request.  This
warning was added in this pull request at the behest of @darobin.

On Thu, Jul 30, 2015 at 10:06 PM, Michael[tm] Smith <
notifications@github.com> wrote:

> I strongly disagree with the change made in PR #456
> <https://github.com/w3c/respec/pull/456> that causes Respec to emit
> warnings for use of the title element with dfn elements, and I request
> that the change be reverted.
>
> That change conflicts with document-conformance requirements in the HTML
> spec in that it tries to make a particular markup case a conformance error
> despite the fact that the HTML spec does not in any way define that case as
> an error.
>
> Along with that, it causes Respec authors to get spurious errors when
> processing their documents.
>
> Related comments also at 85e2f95#commitcomment-12459055
> <https://github.com/w3c/respec/commit/85e2f950d69028a7300033fa05aee3281a64c0db#commitcomment-12459055>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/466>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Closed with #468
