### ISSUE TITLE
Drop support/requirement for the non-HTML "lt" attribute, use a data-linkterm (or whatever) attribute instead.

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/respec#467]
As noted in https://github.com/w3c/respec/commit/85e2f950d69028a7300033fa05aee3281a64c0db#commitcomment-12459055 there is significant value in being able to take the HTML source of a document that will be fed to a browser for Respec processing, and run an HTML checker on it to have the checker find and report any problems with the document.

As noted in https://github.com/w3c/respec/pull/456#commitcomment-12445781
> Whether by design or not, ReSpec’s input prior to the deprecation of `<a title=foo>` and mandatory migration to `<dfn lt=…>`, _was_ validate-able with the HTML validator.  These changes regresses that (non)feature.

It seems part of the motivation for using an `lt` attribute is because Bikeshed uses one. But Bikeshed source is not intended to be conforming HTML, and Bikeshed and Respec do not have interoperability with one another, and interoperability is not a goal for either tool. So in practice, there's very little need or value in Respec using an attribute for this that has the same name as the one Bikeshed uses.

Regardless, whatever value there may be in having an attribute named `lt`, it needs to be considered whether it’s worth losing HTML checkability.

I assert it’s not worth losing HTML checkability—especially since instead, Respec could use a `data-linkterm` or whatever attribute to get the same effect, without losing/regressing HTML checkability.

See also #466.

**Comment by stevefaulkner** [comment]
Can we not add abitrary non html attributes to respec output, when we have conforming mechanisms to do the same.

**Comment by halindrome** [comment]
Fixed in #468
