### ISSUE TITLE
Generic nullable type not rendered in inline var syntax

### ISSUE THREAD

**Issue by nondebug** [w3c/respec#4708]
## Description of problem

**URL to affected spec or repo:**

https://github.com/w3c/gamepad/pull/205#pullrequestreview-2050627610

**What happened (e.g., it crashed)?:**

It wasn't recognized as a variable name:
![image](https://github.com/w3c/respec/assets/14099571/b5241704-5d06-429b-a271-357ab79a2013)

If I remove the ? then it renders correctly.

**Expected behavior (e.g., it shouldn't crash):**

|gamepads| should be styled like a variable and should show the type sequence<Gamepad?> on hover.

**Comment by sidvishnoi** [comment]
Can you send a PR with a test similar to https://github.com/w3c/respec/pull/4685?
