### ISSUE TITLE
Reference to external definition used within details does not open when selected from appendix

### ISSUE THREAD

**Issue by gkellogg** [w3c/respec#4715]
## Description of problem

**URL to affected spec or repo:**  

https://www.w3.org/TR/rdf-canon

**What happened (e.g., it crashed)?:**

Selecting link in Terms defined by reference does not show usage.

**Expected behavior (e.g., it shouldn't crash):**

It should open details and position viewer at the reference

**Optional, steps to reproduce:**

1.  From [Terms defined by reference](https://www.w3.org/TR/rdf-canon/#index-defined-elsewhere), select (e.g.) "lexical form > [§ 4.4.3 Algorithm](https://www.w3.org/TR/rdf-canon/#ref-for-index-term-lexical-form-1)".
2. This references an anchor contained within a `details` element, but does not result in opening the details and repositioning the viewer to that usage.
3. It should show the reference, even if contained in such a hidden element.

See https://github.com/w3c/rdf-canon/issues/214#issuecomment-2128054553 for the related issue.

**Comment by sidvishnoi** [comment]
While ReSpec can address this, it's a more general issue with browsers. Chrome opens the details, while Firefox doesn't. See https://bugzilla.mozilla.org/show_bug.cgi?id=1820528

I'll file an issue in tr-design so fixup.js can handle this, including for Bikeshed specs.
