### ISSUE TITLE
Deprecate rfc2119.js?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#472]
I see in the w3c directory a file called "rfc2119.js", which seems to rely on a `conf.respecRFC2119`. However, it's not documented and seems kinda useless. We should deprecate that.

**Comment by darobin** [comment]
Nope!

The `conf` object is used for configuration but also for communication between modules. This isn't bad: in fact it allows modules to signal useful information that the users can override as well.

In this case, the `w3c/rfc2119` module uses information created by `core/inlines`. The latter lists the RFC2119 keywords that it sees in that configuration item, the former uses that list to generate the list given in the conformance section. That way if you never use "SHALL NOT" in your document, you don't confuse people by telling them about it.

**Comment by marcoscaceres** [comment]
Ok, thanks for the clarification - sorry I missed that.
