### ISSUE TITLE
Depracate callback usage for plugins

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#473]
The plugin use of `cb()` seems kinda useless, particularly as generally results in a no op. If we have actual async plugins, they should returns promises. I've been playing around with using my own async prollyfill, and end up with the following, which is much cleaner thanks to `Promise.all`: 

``` JS
define(["async"], function(async) {
  return {
    runAll: async(function*(plugs) {
      // publish messages for beginning of all and end of all
      var pluginStack = 0;
      respecEvents.pub("start-all");
      respecEvents.sub("start", () => pluginStack++);
      respecEvents.sub("end", () => {
        pluginStack--;
        if (!pluginStack) {
          respecEvents.pub("end-all");
          document.respecDone = true;
        }
      });
      respecEvents.pub("start", "core/base-runner");
      // the first in the plugs is going to be us
      plugs.shift();
      yield Promise.all(plugs.map(async(function*(plug) {
        if (!("run" in plug)) {
          return;
        }
        try {
          const noop = () => { };
          yield plug.run(respecConfig, document, noop, respecEvents);
        } catch (err) {
          respecEvents.pub("error", err);
          respecEvents.pub("end", "unknown/with-error");
        }
      })));
      respecEvents.pub("end", "core/base-runner");
    }),
  };
});
```

**Comment by halindrome** [comment]
I dont hate this idea.  However, do we REALLY know that promises are supported where we need them?  Or is there some shim that will emulate them.  We have a lot of documents now that expose ReSpec to their constituents rather than generating a static snapshot.

**Comment by marcoscaceres** [comment]
> However, do we REALLY know that promises are supported where we need them? 

The current code actually already depends on them and is using a shim/polyfill (see base-runner.js).  Basically, for ReSpec 4, if we were to go ES6/Bable, we should get the polyfills as part of the transpiling.

**Comment by darobin** [comment]
We used to have a few async modules (most notably biblio) but I think they've all since been made relatively sync (in the sense that they may be internally async but they only callback when done anyway).

**Comment by marcoscaceres** [comment]
I have a slick new base-runner in the works. Excited about sharing it :dancer:

**Comment by marcoscaceres** [comment]
The new base-runner support async functions as plugins, so the following is a valid plugin:

```JS
import whatever;

export async function run ( conf ) {
   await thing();
}
```
