### ISSUE TITLE
Webspecs mode has dependencies on specs.webplatform.org

### ISSUE THREAD

**Issue by darobin** [w3c/respec#476]
If you use the webspecs `specStatus` it will include CSS and an icon that are loaded from specs.webplatform.org. Since the future of that site is at best uncertain, it would be best to serve those resources from elsewhere (GitHub, W3C, wicg.io, or inlining them are all options).

**Comment by tripu** [comment]
[`w3c.github.io/modern-tooling`](https://w3c.github.io/modern-tooling/) uses `specStatus` `webspec` (singular). It's looking for the corresponding CSS file on `w3.org` (not on `webplatform.org`), but it can't find it, and the document doesn't render as it should.

Did we forget to copy that CSS to our server? Should the spec use a different `specStatus` now?

**Comment by halindrome** [comment]
Sorry I did not see this.  Let me raise it on IRC.  But yes, that file is NOT included in the 2016 tr-design changes as far as I know.  I didn't even remember it being supported.

**Comment by halindrome** [comment]
Hmm - I think the strategy is going to be to deprecate this functionality - throw a warning if it is used, but link back to webplatform.org for the files for the nonce.  I will put together a PR.

**Comment by marcoscaceres** [comment]
As we removed support for Webspecs, this is no longer an issue.
