### ISSUE TITLE
Webspecs CSS needs work

### ISSUE THREAD

**Issue by darobin** [w3c/respec#477]
This is a broad bug, applying to https://specs.webplatform.org/assets/css/kraken.css which I think should henceforth either be treated as part of ReSpec, or get its own repo that isn't under the webspecs org.

It has a few usability issues and a few problems listed in comments.

**Comment by marcoscaceres** [comment]
I don't think this project took off, so closing

**Comment by marcoscaceres** [comment]
specs.webplatform I mean
