### ISSUE TITLE
Adding a <script> element with the config information to the generated output

### ISSUE THREAD

**Issue by iherman** [w3c/respec#478]
If a post-processor wants to do something with the generated HTML file, it would become very useful if the original config would be available in the file in a machine readable way. After all, many information (document status, short name, list of editors, etc) are available; currently the only way to get to those information is to extract them essentially scraping the content. An easy way would be to generate a `<script>` element to the file containing a JSON serialization of the config data. 

(My use case is a Python script I am finalizing for the generation of an EPUB3 version of a TR document.)

**Comment by marcoscaceres** [comment]
@iherman, a cheap option would be to simply externalize your own Respec config into a JS file. That way, you can treat the generation of the document and any post processing independently. 

Simply:
 
```JS
<script src="EPUB_Spec_Config.js"></script>  
```
Then you can grab the config file independently. 

WDYT?

**Comment by iherman** [comment]
@marcoscaceres I am not sure exactly what you mean. Do you mean that

* respec would dump the config file into a JSON file and add a link to it when generating HTML; or
* the author of the respec file would be required to link to an external JSON file instead of using the current approach.

The former approach would of course work. But I have the feeling you are referring to the latter. In which case...  if *all* respec authors were adopting that externalizing approach, that would work. But I believe the boat has sailed on that one.

Indeed, the goal of the script I am working on is to convert *any* respec file, to generate an EPUB version of the document through the 'save' snapshot of the file, just like one can generate (X)HTML formats today (or generate a diff file). Essentially, to provide an friendlier alternative version of the document to PDF that many specs do these days. It is not a tool restricted to some, specific specs. 

And this is not an EPUB issue only. I can imagine other types of 'postprocessing' tools on documents produced through respec. A good example may be an automatic generation of a simple index file of all the TR documents with the minimal bibliographic information: all the necessary data are in the config part, but are diluted into various places once respec has done its work. Keeping the structured data in an easy-to-consume place seems to be valuable to me.

I know there is an RDFa encoding of many of the data in the output. And, of course, if a postprocessor did a full RDF extraction and handled the RDF data, that would also be solution. However, I am just afraid of a sledgehammer effect; an RDFa processor is a relatively heavy tool, so is handling the resulting RDF data.  This is justified for more complex Linked Data applications, whereas consuming JSON data is an easy step for just about any environment. (B.t.w., if the config data is transformed into JSON-LD and stored as such in the output, that is also perfectly fine!)

**Comment by darobin** [comment]
@marcoscaceres The purpose of this bug is for ReSpec to save its configuration at the end so that other tools can reuse it down the line. ReSpec has a fair bit of good quality data that gets lost after the generation has happened.

**Comment by marcoscaceres** [comment]
Got it. I thought Ivan just wanted this for the ePub specs exclusively. We can easily add the JSON to the appendix and just display:none that section. One would still need a HTML parser to get at it tho. Is that ok?

**Comment by iherman** [comment]
Of course it is all right to rely on an HTML parser; that is difficult to avoid.

That being said, I have the impression (but this is only an impression) that it is cleaner to add the JSON content into a <script> tag in the header, rather than as part of the content. Per the HTML5 specification:

> The script element allows authors to include dynamic script and data blocks in their documents.

i.e., it is defined for such usage as well. The only point is that the `@type` attribute should be set to `application/json`.

**Comment by marcoscaceres** [comment]
> i.e., it is defined for such usage as well. The only point is that the @type attribute should be set to application/json.

Yeah, that could work.

**Comment by marcoscaceres** [comment]
@iherman https://github.com/w3c/respec/pull/484

BTW, why don't we just add "Save as EPUB" as a save option? In theory, we could generated EPUB packages directly in respec.

**Comment by halindrome** [comment]
That's what he is doing.

On Mon, Aug 31, 2015 at 10:46 AM, Marcos Caceres <notifications@github.com>
wrote:

> @iherman <https://github.com/iherman> #484
> <https://github.com/w3c/respec/pull/484>
>
> BTW, why don't we just add "Save as EPUB" as a save option? In theory, we
> could generated EPUB packages directly in respec.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/478#issuecomment-136411788>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
@halindrome but @iherman is doing it in Python? Why not just do it in JS?

**Comment by halindrome** [comment]
He can explain it, but the python bit is a web service that does some of
the heavy lifting.  At least that was my understanding.  You don't want to
try to produce zip archives in JS.  Or at least I don't.

On Mon, Aug 31, 2015 at 10:53 AM, Marcos Caceres <notifications@github.com>
wrote:

> @halindrome <https://github.com/halindrome> but @iherman
> <https://github.com/iherman> is doing it in Python? Why not just do it in
> JS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/478#issuecomment-136413515>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Why not? It's trivial with https://stuk.github.io/jszip/

**Comment by iherman** [comment]
> On 31 Aug 2015, at 17:56 , Shane McCarron <notifications@github.com> wrote:
> 
> He can explain it, but the python bit is a web service that does some of
> the heavy lifting. At least that was my understanding.

Indeed. Except for s/is/will be/:-) The code runs on my machine locally but still has to be deployed as a W3C service.

The python vs. JS issue is also a matter of pragmatism. I did have many of the code around in Python already, so gathering it into a coherent service was relatively straightforward. Finally: I am an old-skool person who has been using Python on and off for about 20 years, but I am an absolute novice in JS, and I am lazy:-)



>  You don't want to
> try to produce zip archives in JS. Or at least I don't.
> 
> On Mon, Aug 31, 2015 at 10:53 AM, Marcos Caceres <notifications@github.com>
> wrote:
> 
> > @halindrome <https://github.com/halindrome> but @iherman
> > <https://github.com/iherman> is doing it in Python? Why not just do it in
> > JS?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/w3c/respec/issues/478#issuecomment-136413515>.
> >
> 
> 
> 
> --
> Shane McCarron
> halindrome@gmail.com
> —
> Reply to this email directly or view it on GitHub.
> 


----
Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by marcoscaceres** [comment]
@iherman, ok, let us know if it gets popular tho. We could add support if enough people are interested.

**Comment by iherman** [comment]
Once all services are set up, I will send in a PR for the save-html.js file (the only code that is affected by this).

**Comment by iherman** [comment]
(Reopening the issue)

@marcoscaceres Unfortunately, the solution does not seem to be o.k. I have just tested by generating HTML from a [respec document on github](http://w3c.github.io/csvw/csv2json/) and what I get is something like:

```
<script id="respecFinalConfig" type="application/json">{<br>  "localBiblio": {<br>    "tabular-data-model": {<br>      "authors": [<br>  ...
```

I.e., the text includes the `<br>` elements, and makes the content invalid JSON...

**Comment by marcoscaceres** [comment]
@iherman you are right, it's busted. I'm not getting any output at all. Will try to fix soon.

**Comment by iherman** [comment]
@marcoscaceres I wonder what is happening. I have pulled the latests development branch, yielding version 3.2.71. I run a document referring locally to that file and

* on chrome and safari (both latest versions) the result is identical (``<br>`` in the code)
* on firefox the content of the script element is empty:-(

(I also tried the version on W3C, the result is the same.)
