### ISSUE TITLE
Encapsulating the content into a <main> element?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#479]
I generate an EPUB3 version of the TR document produced by respec. Unfortunately, there are discrepancies among epub readers; one is that they artificially set zero padding on the body element. (This is the case with Kobo or with the iBook readers of Apple.) This means the logo on the header area is overwritten by the content.

One way of getting around that, which I believe would be useful for other post-processing facilities, is to encapsulate the whole content of the document in a `<main>` element (which would also make sense logically, so to say). That means the styling of the post-processed content could become easy.

**Comment by marcoscaceres** [comment]
@iherman, I wonder if you can just add something like the following into your document:
 
```CSS
body{
   padding: 1em !important;
}
```

**Comment by iherman** [comment]
> On 26 Aug 2015, at 17:49 , Marcos Caceres <notifications@github.com> wrote:
> 
> @iherman, I wonder if you can just add something like the following into your document:
> 
> body
> {
> 
> padding: 1em !important
> ;
> }
> 

Nop, we tried this. More exactly, that seems to work with Kobo (somebody from Kobo tried it), but did not work for iBooks. It seems that the iBook implementation manipulates (conceptually) the CSS cascade and overwrite that padding no matter what the user does. :-(




> —
> Reply to this email directly or view it on GitHub.
> 


----
Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by marcoscaceres** [comment]
On August 26, 2015 at 11:53:43 AM, Ivan Herman (notifications@github.com) wrote:

> Nop, we tried this. More exactly, that seems to work with Kobo (somebody from Kobo tried  
> it), but did not work for iBooks. It seems that the iBook implementation manipulates  
> (conceptually) the CSS cascade and overwrite that padding no matter what the user does.  
> :-(

Apple knows best ;) wrapping things in a `<main>` could work, but we are working around non-conforming user agents and that's not great.

**Comment by darobin** [comment]
we are working around non-conforming user agents and that's not great

There's a name for that; it's called "Web Development".

**Comment by iherman** [comment]
> On 26 Aug 2015, at 18:24, Marcos Caceres <notifications@github.com> wrote:
> 
> 
> On August 26, 2015 at 11:53:43 AM, Ivan Herman (notifications@github.com) wrote:
> 
> > Nop, we tried this. More exactly, that seems to work with Kobo (somebody from Kobo tried 
> > it), but did not work for iBooks. It seems that the iBook implementation manipulates 
> > (conceptually) the CSS cascade and overwrite that padding no matter what the user does. 
> > :-(
> 
> Apple knows best ;)

:-)

> wrapping things in a `<main>` could work, but we are working around non-conforming user agents and that's not great. 

I understand. And, to be clear, my tool has solved the problem by doing this change before generating the EPUB file, so I can personally live without it. The question is whether such feature would be useful in general. If, for example, the header and the content part of the overall content was clearly separated using the <header> and <main> elements, that could help other post-processing tools. Worth considering.

**Comment by iherman** [comment]
> On 26 Aug 2015, at 18:32, Robin Berjon <notifications@github.com> wrote:
> 
> we are working around non-conforming user agents and that's not great
> There's a name for that; it's called "Web Development".
> 
:-)

**Comment by halindrome** [comment]
FYI when the PFWG discussed this they felt that appendices should be
encapsulated separately from the main content.  There is a pull request
that implements this, but I don't think it ever got merged.  Basically it
pulled all of the normative content into a div with a role of main, and the
appendices into a div with a role of complementary IIRC.

On Wed, Aug 26, 2015 at 12:13 PM, Ivan Herman <notifications@github.com>
wrote:

>
>
> > On 26 Aug 2015, at 18:32, Robin Berjon <notifications@github.com> wrote:
> >
> > we are working around non-conforming user agents and that's not great
> > There's a name for that; it's called "Web Development".
> >
> :-)
>
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/479#issuecomment-135111399>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
@iherman, how about I include the `main` element at save time for ePub files? That should at least cover your use case. Also, can you give me the CSS rule (padding? margin?) you for `<main>` that will work best for you?

**Comment by marcoscaceres** [comment]
Actually, never mind! As I'm just GETing a URL, it would be best if you added the main element when you generate the ePub file on the server.

**Comment by iherman** [comment]
@marcoscaceres , as I wrote in my [previous comment](https://github.com/w3c/respec/issues/479#issuecomment-135111258), my tool already does that. I only raised the issue because it may be of a more general usage.

P.S. note, b.t.w., that in the latest version I do not use ``<main>`` but a ``div`` with a special ID. The reason is that I modified the tool a bit so that it could also handle HTML files that come from bikeshed, and those files already use the ``<main>`` element, albeit not encapsulating the whole content. Because there can be only one ``<main>``, I had to make the modification.

**Comment by marcoscaceres** [comment]
Ohhh... I do hate the competition. I'll take a look at what bikeshed does + @halindrome's suggestion of excluding the appendixes.

**Comment by marcoscaceres** [comment]
So, a simple solution is to do the following somewhere. 

```JS
// possible to add, e.g., :not(#abstract):not(#toc):not(#sotd)
$("body>section:not(.appendix)").wrapAll("<main></main>");

// or 
$("body>section:not(.appendix)").wrapAll("<div role=main></div>");
```

**Comment by iherman** [comment]
> On 12 Sep 2015, at 07:28 , Marcos Caceres <notifications@github.com> wrote:
> 
> So, a simple solution is to do the following somewhere.
> 
> // possible to add, e.g., :not(#abstract):not(#toc):not(#sotd)
> $("body>section:not(.appendix)").wrapAll("<main></main>");
> 
> // or
> $("body>section:not(.appendix)").wrapAll("<div role=main></div>");
Right. I would not want to go into the philosophical debate, though, whether the appendices should be part of  ``<main>`` or not; my feeling is that actually it should (in many respect, appendices are bona fide part of a TR document, albeit not necessarily normative).


----
Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by marcoscaceres** [comment]
> Right. I would not want to go into the philosophical debate, though, whether the appendices should be part of ``<main>`` or not; my feeling is that actually it should (in many respect, appendices are bona fide part of a TR document, albeit not necessarily normative).

Agree. I put a lot of important information into appendices too.

**Comment by marcoscaceres** [comment]
closing as won't fix.

**Comment by marcoscaceres** [comment]
actually, might still do this... but we put everything between top and the references inside main.

**Comment by marcoscaceres** [comment]
Decided again we won't fix this... 5 years of putting this off is probably enough.
