### ISSUE TITLE
"for" attributes used for WebIDL references remain in generated snapshot

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#483]
The "for" attributes that one needs to use to reference a particular interface in WebIDL prose remain in the generated snapshot. This means that the resulting spec does not pass markup validation, which in turns prevents publication to /TR/ space for W3C specs.

The "for" attributes should rather be dropped from the generated spec. The same thing should happen to "link-for" and "dfn-for" attributes.

I noticed the problem while trying to publish the Presentation API spec [1], which makes use of such references. Using spec-generator to produce the snapshot [2] (manual generation yields the same result) produces a spec that does not pass markup validation [3].

Note that I'm very likely going to update the Presentation API spec to add some post-processing code that drops the problematic attributes so the links below may not show errors for long. The bug still exists.

[1] http://w3c.github.io/presentation-api/
[2] https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/presentation-api/index.html?specStatus=WD;shortName=presentation-api
[3] https://validator.w3.org/nu/?doc=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpresentation-api%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dpresentation-api

**Comment by tidoust** [comment]
As noted, I added a post-processing rule to the Presentation API spec to remove the "for" attributes, so that spec now passes markup validation, while this bug gets fixed.

FWIW, post-processing code:
https://github.com/w3c/presentation-api/blob/gh-pages/index.html#L82

**Comment by marcoscaceres** [comment]
cc @jyasskin

**Comment by jyasskin** [comment]
FWIW, my spec is now using Bikeshed, so I'm unlikely to get around to fixing this in ReSpec.

**Comment by marcoscaceres** [comment]
@jyasskin ok, np. Will take a look.

**Comment by halindrome** [comment]
When you are looking at this, keep in mind the contract with Shepherd.  I am not certain what it wants to look for to ensure that components of IDL are corrected connected to one another and expose their interfaces in the external spec database.  @tobie?

**Comment by tobie** [comment]
@plinss is who you want to talk for Shepherd.

**Comment by plinss** [comment]
Shepherd expects all non-standard attributes to begin with data-, e.g. data-dfn-type, data-dfn-for, etc. Attributes like 'for" or "link-for" should only be input to tools like Respec and Bikeshed and should be removed from the output (most likely replaced with the data- equivalent). Bikeshed takes care of this.

**Comment by plinss** [comment]
More details on the Shepherd contract can be found in the Bikeshed docs at: https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md

**Comment by marcoscaceres** [comment]
This WFM? When I save http://w3c.github.io/presentation-api/ I get the right data-dfn-for?

**Comment by marcoscaceres** [comment]
(Please reopen if I'm wrong)

**Comment by tidoust** [comment]
@marcoscaceres Well, yes, it works... because I added an `afterEnd` post-processing rule in the Presentation API spec to work around the bug, as noted in a previous comment:
 https://github.com/w3c/respec/issues/483#issuecomment-136329170

(Also note that the bug is not about missing `data-` attributes, but rather about `for` attributes that remain in the generated spec)

To see the the bug in action, drop the post-processing:
 http://w3c.github.io/presentation-api/?afterEnd=null

If you browse the generated source of that document, you will notice that there are `for` and `link-for` attributes that remain in the spec. These attributes are not valid in HTML5, and thus make the validator issue errors.

An example of offending markup generated by ReSpec:
```
<a for="PresentationRequest" href="#dom-presentationrequest-start" class="internalDFN" data-link-type="dfn">
```

FWIW, the initial source that gives birth to that markup contains the `for` attribute, of course, but it's needed for ReSpec to create the appropriate reference:
```
<a for="PresentationRequest">start</a>
```

**Comment by marcoscaceres** [comment]
@tidoust, d'oh. I had also tested it on another file, in which the offending attributes didn't show up. Have a fix coming up.
