### ISSUE TITLE
Run respec2html.js was part of the test suite.

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#501]
@marcoscaceres keeps breaking respec2html.js because it's not tested as part of the our test suite. We should either ban Marcos or fix the test suite.

**Comment by marcoscaceres** [comment]
@dontcallmedom thoughts on how we do this... I don't have any direct experience with respec2html.js.

**Comment by dontcallmedom** [comment]
my suggestion (and sorry I can't afford to provide a patch for this at the moment):
* prepare a set of respec-valid documents that loads respec from within the repo; ideally, they would exercise as much of respec as possible (e.g. a bunch of webidl)
* add to the "test" script in package.json a rule to run "./tools/respec2html.js -e -w " on these documents
* a bonus point might to be to run an HTML5 validator on the output of that command — that way, we would detect when respec starts generating invalid HTML5; this might be better done in Travis CI though (see [how I do it e.g. for the WebRTC spec](https://github.com/w3c/webrtc-pc/blob/master/.travis.yml))

(I don't know if the stuff in tests/specifications was supposed to be used for this kind of test? maybe that wouldn't be a bad place to put these new "respec-valid" documents)
