### ISSUE TITLE
Additional author information

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#507]
Authors would like to be able to add additional links to, for example, an ORCID, or even their twitter profile, linkedIn profile etc. As such, the author field should provide a means of adding additional links. 

As part of the additional links, it would be good to allow authors to add a custom CSS class - that is, so they can style the link they way that they want. 

In the document, it might appear like:

 * Marcos Caceres (twitter, linkedIn), Mozilla. 

Or:

 * Ivan Herman (0000-0003-0782-2704, @ivan_herman), W3C. 

Or some such...

**Comment by iherman** [comment]
Created a pull request for this, see #508. The approach is: for each name, the config file may include something of the form:

```
              ,   extras:     [{
                    name:  "0000-0003-0782-2704",
                    href:  "http://orcid.org/0000-0003-0782-2704",
                    label: "orcid"
                  }, {
                    name:  "@ivan_herman",
                    href:  "http://twitter.com/ivan_herman",
                    label: "twitter"
                  }]
```

where ``label`` and ``href`` are optional. The result is to add a comma separated list of ``span`` elements at the end of the name as follows:

```
<span class="LABEL VALUE"><a href="HREF VALUE">NAME VALUE</a></span>
```

In practice, the user can adapt the output with some CSS. For example, for the code above, the following CSS makes sense:

```
      span.twitter:before {
        content: url(figures/twitter_logo.png);
      }
      span.orcid:before {
        content: url(figures/orcid_logo.png);
        margin-right: 2px;
      }
```

(Unfortunately, neither twitter nor ORCID "servers" their logos from their site, at least not yet.)

**Comment by marcoscaceres** [comment]
Few things:

 * `label` should really be `class`.  Otherwise, people will ask why the `label` doesn't show up.
 *  `class` should take an array. People might want multiple classes for whatever reason.

**Comment by marcoscaceres** [comment]
Actually, let's just make class a string, like you have it now... people can just add "," :)

**Comment by iherman** [comment]
> On 30 Sep 2015, at 24:27 , Marcos Caceres <notifications@github.com> wrote:
> 
> Few things:
> 
> label should really be class. Otherwise, people will ask why the label doesn't show up.
> class should take an array. People might want multiple classes for whatever reason.


Changed label to class. Per your other comment, left the content unchanged
