### ISSUE TITLE
gh-pages branch gone? breaks respec2html

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#513]
It looks like the `gh-pages` branch was removed, removing the content of https://w3c.github.io/respec/ from the Web; but at least respec2html.js has a dependency on this existing for loading the UI module (see js/profile-w3c-common.js) so it doesn't work any more.

**Comment by dontcallmedom** [comment]
I've re-pushed a new version of gh-pages for now; will keep this issue open for discussing the overall issue.

**Comment by halindrome** [comment]
how in the world could the gh-pages branch have been removed?  It is how we
deploy new versions!

On Tue, Oct 13, 2015 at 1:54 AM, Dominique Hazael-Massieux <
notifications@github.com> wrote:

> I've re-pushed a new version of gh-pages for now; will keep this issue
> open for discussing the overall issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/513#issuecomment-147623984>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
I probably trashed it:) I'll enable branch protection.

**Comment by marcoscaceres** [comment]
@dontcallmedom, I don't have enough privileges to enable branch protection. Can you please do it? It takes two seconds: just go to "settings" for the repo, click on "branches", and you will see an option there.

**Comment by marcoscaceres** [comment]
@dontcallmedom, just please add develop and gh-pages. I think that's all we need?

**Comment by dontcallmedom** [comment]
done, develop and gh-pages are now protected.
