### ISSUE TITLE
Allow easy specification and extraction of assertions

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#514]
For the purposes of testing, it would be nice to have an easy way to annotate assertions, and also some sort of command or workflow that would export those in a format that is readily machine consumable.  No real suggestions on what that format should be.... maybe simple JSON-LD with some well defined terms?

**Comment by marcoscaceres** [comment]
One could just look for RFC2119 keywords I guess. I did something like this in the past. http://www.w3.org/TR/test-methodology/

**Comment by halindrome** [comment]
Resurrecting this.  I really want to be able to annotate with class values.

**Comment by dontcallmedom** [comment]
FWIW, I've recently used `[...document.querySelectorAll(".rfc2119")].map(x=>x.parentNode).filter((x,i,a)
=> i==0 || x!==a[i-1]);` in the console to extract all the paragraphs that contains rfc 2119 keywords in a respec-based spec

**Comment by halindrome** [comment]
Sure.   I was thinking of a collection of those, categorized as unclassified or by some grouping.  Then tables of them that could be emitted ala best practices.  Links to the real text, of course.  And an ability to easily extract them and push them into test case skeletons or something would be sexy too (separate script of course).

**Comment by halindrome** [comment]
Just to be a little clearer..... "some grouping" could be a data-tc (test class) attribute that you set if there are multiple classes of assertions in your document.  Arbitrary strings.  Add an element to the UI that would show all of the classes and be able to display an index of each (ala definitions now). Maybe I should socialize this with the Bikeshed folks so we take a similar approach should they want to do something too?  @tabatkins ?

**Comment by tabatkins** [comment]
Bikeshed has a convenience thing built in to handle a little bit of this - you can use an `<assert>` tag in your markup, and Bikeshed will turn it into a `<span>` with an auto-generated ID created from a hash of the contents, so tests can point to it and be sure the link will work as long as the assertion doesn't change.

I'm happy to allow/generate more metadata around this, too.

**Comment by marcoscaceres** [comment]
Reminded of the classic:
https://www.w3.org/TR/test-methodology/

**Comment by marcoscaceres** [comment]
Reflecting on this, the presentation of conformance requirements is somewhat specific to each specification and needs of each WG (or even each implementer and how they choose to implement things!). 

As a community, we haven't come up with an established way of concisely gathering and presenting conformance requirements (apart from the specifications themselves). What we have established is a strong testing culture, where conformance requirements are translated to testable assertions, which are then represented as tables in, for instance, [wtp.fyi](https://wtp.fyi).  

When it comes down to it, for APIs at least, the conformance requirements are mostly keyed off WebIDL attributes and operations. For those, ReSpec does allow for a couple of useful things:

 1. [`data-tests=`](https://github.com/w3c/respec/wiki/data-tests) allows linking to tests. 
 1. And we have the `wpt-tests-exist` a linter rule that checks if a WTP test exists on the WPT repo. 

As such, I'm included to close this for now.
