### ISSUE TITLE
References section is formatted incorrectly

### ISSUE THREAD

**Issue by vijaybh** [w3c/respec#518]
W3C style manual on formatting references: http://www.w3.org/2001/06/manual/#ref-section

Respec docs say localBiblio should be formatted like this: http://www.w3.org/respec/ref.html#localbiblio

I see two issues:
1. Respec lists authors before the title, style manual says title should come first.
2. Respec ignores the publisher field.

**Comment by marcoscaceres** [comment]
The W3C style manual is a little out of date. We've evolved our style based on usage experience over the last 15 years.

**Comment by vijaybh** [comment]
OK, I can understand listing authors before title, but are you saying that ignoring the publisher field is also by design? Specref.org has at least a few references with publisher and no author, and these come out looking rather weird. If Respec is going to ignore publishers, then should it not warn when a reference (at least in localBiblio) uses this field?

**Comment by marcoscaceres** [comment]
@vijaybh, I'll try to take a look. If the publisher is there, then we should be displaying it. If you have a sample case I can use, then that would be greatly appreciated.

**Comment by vijaybh** [comment]
Thanks.

I emailed a test HTML file to Dominique - unfortunately GitHub says I can't upload anything other than picture files because I don't have write access to the repo.

The test file was quite simple - I just made a basic HTML file that has a title and pulls in the W3C Respec, added the below piece of script, and made a reference to TestRef in my abstract.

    (function () {

    respecConfig.localBiblio = {
        "TestRef": {
            title: "If this reference starts with a title followed by an author and a publisher, Respec works",
            href: "http://www.w3.org/2001/06/manual/#ref-section",
            authors: ["William Shakespeare"],
            publisher: "Publishers Inc."
        }
    };

    })();
