### ISSUE TITLE
Use the experimental 2016 stylesheets for EDs

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#520]
Similar to some of the bikeshed documents (see https://lists.w3.org/Archives/Public/spec-prod/2015OctDec/0033.html), we should start testing the new stylesheets asap.

**Comment by halindrome** [comment]
Can we do this as an option?  respec configuration option I mean.

**Comment by plehegar** [comment]
my only reluctance to keep it as an option is that most will now see it before the end of December and it will be useless after.

**Comment by halindrome** [comment]
I understand.  But if it is automatic 1) people will scream because some of the stuff is awful, and 2) all of our documents will be hitting a non-w3c server for their stylesheets.

**Comment by halindrome** [comment]
I misunderstood your request @plehegar - sure, we could make this the default for EDs.  There are some problems with the WebIDL styles right now that I need to fix.  I will work on this today and do a new PR that changes the default on EDs unless there are objections.

**Comment by plehegar** [comment]
One thing I didn't catch earlier with #522. It can't be used on https://w3c.github.io/ specs because:
1. it's using http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED instead of https://
2. https://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED is not trusted.

**Comment by halindrome** [comment]
What would you like to do to address this?

On Wed, Nov 25, 2015 at 2:10 PM, Philippe Le Hegaret <
notifications@github.com> wrote:

> One thing I didn't catch earlier with #522
> <https://github.com/w3c/respec/pull/522>. It can't be used on
> https://w3c.github.io/ specs because:
> 1. it's using
> http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED
> instead of https://
> 2. https://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-ED
> is not trusted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/520#issuecomment-159719078>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> What would you like to do to address this? 

@fantasai, can you please fix your cert?

**Comment by plehegar** [comment]
talked to @fantasai last night. We need to use https://w3c.github.io/tr-design/src/W3C-ED.css.

**Comment by halindrome** [comment]
That is what is referenced in PR #528, right @marcoscaceres ?

**Comment by tripu** [comment]
@fantasai said:
> Github.io is not able to serve up with content negotiation the way the W3C server does, no.

So we're looking into alternatives, eg hosting on `https://www.w3.org` or having `fantasai.inkedblade.net ` serve via HTTPS.

**Comment by r12a** [comment]
what's the outlook for resolving this?  December is a really short month, for me, and i suppose others, and i'd like to get testing with my docs.

**Comment by plehegar** [comment]
I copied the styles in http://www.w3.org/2016/01/. @fantasai, the unfortunate way to update them at the moment is to ping me on irc or by email (or irc #pub if I'm not around). Note that this may not where we'll have them in their definitive place.

**Comment by tripu** [comment]
(Fixed, now that #529 has been merged?)

**Comment by tripu** [comment]
We may still set up a quick hook to update the files GH &rarr; w3.org&hellip;

**Comment by plehegar** [comment]
btw, here is an example of a MANIFEST file to take advantage of the change without breaking automatic publication:
https://github.com/w3c/performance-timeline/blob/gh-pages/W3CTRMANIFEST
