### ISSUE TITLE
Nudging/warnings/prompts for Privacy and Security Considerations sections

### ISSUE THREAD

**Issue by npdoty** [w3c/respec#539]
(Per prior conversation with @darobin and @wseltzer, I meant to log this in Github months ago.)

It would be great if the Respec tooling could help prompt or nudge those using it for Web spec development to include a Privacy and Security Considerations section if they haven't already. This could be done either by introducing a warning (that can be turned off), or by creating a section with an issue block or bold text noting the lack of text.

Some issues that have been noted:
- Respec can be used for other documents besides W3C specs, and so this prompt wouldn't make sense in those contexts (so we'd want to limit its applicability somehow)
- False positives (where a spec does have a good priv/sec considerations section but still gets the warning/prompt) would be frustrating: can we write a good heuristic to guess at the presence of existing sections? I bet this would be feasible.

**Comment by npdoty** [comment]
Bikeshed has something similar, to introduce a warning if the sections appear to be missing, and specifically and explicitly limits it to W3C groups:
https://github.com/tabatkins/bikeshed/commit/89f5bdc7f12294f5c59890ee19d9ee5619c57a66
https://github.com/tabatkins/bikeshed/issues/513
Thanks @mikewes

**Comment by marcoscaceres** [comment]
Great idea. We could warn if missing a section labelled "privacy" or some such.

**Comment by marcoscaceres** [comment]
Pilfer: https://github.com/tabatkins/bikeshed/pull/514/files#diff-3029e86a898fb9c94d4c0b4238b4a709R316

**Comment by npdoty** [comment]
I'm thinking we should check for having _either_: both a section with "security" and "considerations" and a section with "privacy" and "considerations" _or_: a section with "security" "privacy and "considerations". Maybe I should do a quick check and see if that would have any false positives for a sample of recently published documents that do have relevant sections.

**Comment by mikewest** [comment]
The check I added to Bikeshed is fairly brain dead, and will cause false
positives. My take on it is that it's reasonable to require explicit
"security considerations" and "privacy considerations", as that will make
it clear for reviewers and readers at a fairly small cost to authors and
editors.

I guess combining them into a single section would be alright as well.
*shrug* If that's a cowpath you find in your spot checking, I wouldn't mind
paving it with you.

-mike

On Friday, 11 December 2015, Nick Doty <notifications@github.com> wrote:

> I'm thinking we should check for having *either*: both a section with
> "security" and "considerations" and a section with "privacy" and
> "considerations" *or*: a section with "security" "privacy and
> "considerations". Maybe I should do a quick check and see if that would
> have any false positives for a sample of recently published documents that
> do have relevant sections.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/539#issuecomment-163823170>.
>


-- 
-mike

**Comment by marcoscaceres** [comment]
Added this a while ago
