### ISSUE TITLE
TR CSS versioning into the document?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#552]
With the upcoming change of the /TR CSS files and resulting changes in respec (e.g., using `nav` for the TOC) I wonder whether adding a 'css-version' flag to the config part automatically would make sense. Post-processing HTML files generated via respec (eg, generating an epub) will have to rely on that version for some details; at the moment, the only way to do that seems to be by analysing the css reference's URI to see if there is, eg, a year in it. Can be done by inelegant. (And there may be a need to convert files that were published, say, in 2015, ie, whose CSS version is different than what will come in a few weeks...)

**Comment by marcoscaceres** [comment]
We support this via experimental styles, but it's not something we really want to expose.

**Comment by iherman** [comment]
@marcoscaceres , I am not sure I understand the answer. What does experimental style mean in practice?

**Comment by marcoscaceres** [comment]
Sorry, I was not very clear. We support an internal property that one can set on ReSpec's configuration - for example:

``` JS
conf.useExperimentalStyles = "2016"; //or true, which just uses the current year
```

That then simply changes `{version}` in the following URL:
"https://www.w3.org/StyleSheets/TR/{version}"

Which then becomes the default style URL that is used. Right now, it defaults to 2016.

**Comment by iherman** [comment]
If I understand you well, this means that the version of the CSS will be reflected in the URI it uses, insofar as in /TR/{version} the {version} string actually stands for a year. If that is a principle we can use for later years as well, then that also works (actually, this is exactly what I implement right now:-). So I am fine...
