### ISSUE TITLE
Update to Phantomjs 2.1

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#557]
@dontcallmedom, any chance you could check if updating to the recently released Phantom 2.1 might be of value? IIUC, it has an updated WebKit... might help overcome some of our legacy JS issues.

**Comment by dontcallmedom** [comment]
I've tested and our test suite works with phantom2.1

In terms of adopting phantom2.1, this might mean several things:
* require phantom2.1 to running respec2html.js (I assume we could add a version test to the script)
* only commit to support phantom2.1 (in particular, we would use [phantom2.1 in our Travis setup](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-174568331))
* try and revert some of the "make-phantomjs-happy" commits to simplify and clean up our code base and see if they work with phantom2.1
