### ISSUE TITLE
Type error in old(?) Safari

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#562]
Gregg Kellogg wrote: 

I’ve just started seen errors pop up when running on Safari: 

• [TypeError] undefined is not an object (evaluating 't[0].for_') ⊟ 
https://www.w3.org/Tools/respec/respec-w3c-common:14:24272 
each@https://www.w3.org/Tools/respec/respec-w3c-common:5:27677 
each@https://www.w3.org/Tools/respec/respec-w3c-common:5:25651 
run@https://www.w3.org/Tools/respec/respec-w3c-common:14:23658 
https://www.w3.org/Tools/respec/respec-w3c-common:8:7646 
initializePromise@[native code] 
Promise@[native code] 
https://www.w3.org/Tools/respec/respec-w3c-common:8:7617 
promiseReactionJob@[native code] 

This happens, for example, on http://w3c.github.io/csvw/primer/. 

No errors on Firefox or Chrome. 

Gregg Kellogg 
gregg@greggkellogg.net

**Comment by marcoscaceres** [comment]
I'm not able to reproduce in latest Safari (9.0.3). Closing as WFM. Please reopen if it happens again.

**Comment by gkellogg** [comment]
Yes, it's working properly now with now software change on my side.

**Comment by marcoscaceres** [comment]
@gkellogg excellent to hear. Thanks for double checking.
