### ISSUE TITLE
useExperimentalStyles should be a string, not a boolean

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#569]
using "useExperimentalStyles" as a boolean is not maintainable, because it means we need to keep updating URLs to match particular experimental behavior and URLs that change. I suggest we initially change it to a string (URL). The current code wouldn't need to change; as checks are done as truthy.

**Comment by marcoscaceres** [comment]
actually... no... argh. Will give this more thought...

**Comment by marcoscaceres** [comment]
I'm going to support both a boolean and a string here - so we can maintain the dated experimental style selection: 

```JS
          // Select between classic styles and experimental
          switch (conf.useExperimentalStyles){
            case "2016":
            case true:
              version = "2016/";
              break;
            default:
              version = "";
          }

```

**Comment by tripu** [comment]
That looks good, @marcoscaceres.

Anyway, I'm thinking that keeping the boolean is OK if we can reasonably expect support for yearly TR redesigns to *not* overlap in time. I mean, starting some time around mid-2016, `useExperimentalStyles=true` will mean &ldquo;use 2017 style&rdquo;, and anything else will mean &ldquo;2016 style&rdquo;; nobody will be using anything but TR 2016 by then&hellip; no?

**Comment by halindrome** [comment]
I honestly don't understand pub scheme migration at the W3C.  Every time
there is an effort like this, it seems to get thrwarted before it gets
launched.

Your changes make sense to me, but I would like to see the boolean continue
to work too.

On Wed, Feb 17, 2016 at 1:33 AM, tripu <notifications@github.com> wrote:

> That looks good, @marcoscaceres <https://github.com/marcoscaceres>.
>
> Anyway, I'm thinking that keeping the boolean is OK if we can reasonably
> expect support for yearly TR redesigns to *not* overlap in time. I mean,
> starting some time around mid-2016, useExperimentalStyles=true will mean
> “use 2017 style”, and anything else will mean “2016 style”; nobody will be
> using anything but TR 2016 by then… no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/569#issuecomment-185076305>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by tripu** [comment]
> I honestly don't understand pub scheme migration at the W3C.  Every time there is an effort like this, it seems to get thrwarted before it gets launched.

:(
I hope it's not the case this time, @halindrome!
Anything in particular that is bothering you about this *tr-design* project&hellip;?

**Comment by halindrome** [comment]
Sure.  But I generally keep my mouth shut about them.   Line spacing is
weird in some cases (nested sections with no content in the parent have a
wide gap; successive dd elements after a dt have a lot of space between
them).  I don't like the ToC on the left side on wide monitors.  Or at
least it should be resizeable.  I could go on.

On Wed, Feb 17, 2016 at 7:14 AM, tripu <notifications@github.com> wrote:

> I honestly don't understand pub scheme migration at the W3C. Every time
> there is an effort like this, it seems to get thrwarted before it gets
> launched.
>
> :(
> I hope it's not the case this time, @halindrome
> <https://github.com/halindrome>!
> Anything in particular that is bothering you about this *tr-design*
> project…?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/569#issuecomment-185198999>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> On 17 Feb 2016, at 11:55 PM, Shane McCarron <notifications@github.com> wrote:
> 
> I honestly don't understand pub scheme migration at the W3C. Every time
> there is an effort like this, it seems to get thrwarted before it gets
> launched.
> 
> Your changes make sense to me, but I would like to see the boolean continue
> to work too.

Boolean will continue to work. It will just default to /2016/.

But we need to work with folks at the W3C to avoid using dates - it's a terrible way of doing version control. There should only be "/experimental/" and stable designs. Experiments eventually become stable. The history could be tracked in git instead. 

>

**Comment by marcoscaceres** [comment]
> On 18 Feb 2016, at 1:30 AM, Shane McCarron <notifications@github.com> wrote:
> 
> Sure. But I generally keep my mouth shut about them. Line spacing is
> weird in some cases (nested sections with no content in the parent have a
> wide gap; successive dd elements after a dt have a lot of space between
> them). I don't like the ToC on the left side on wide monitors. Or at
> least it should be resizeable. I could go on.

I would not fret too much about the above. The new design is far from perfect, but we can improve it over time (and it's an improvement on current in many ways). Once it goes live, bugs will flood in; adding to the pressure to fix the above things you mentioned. I think you've already filed bugs for the above, right? 

>

**Comment by halindrome** [comment]
I think so, yes.  And I don't disagree.  I am not change-averse.  You just
think I am

On Wed, Feb 17, 2016 at 5:38 PM, Marcos Caceres <notifications@github.com>
wrote:

>
>
> > On 18 Feb 2016, at 1:30 AM, Shane McCarron <notifications@github.com>
> wrote:
> >
> > Sure. But I generally keep my mouth shut about them. Line spacing is
> > weird in some cases (nested sections with no content in the parent have a
> > wide gap; successive dd elements after a dt have a lot of space between
> > them). I don't like the ToC on the left side on wide monitors. Or at
> > least it should be resizeable. I could go on.
>
> I would not fret too much about the above. The new design is far from
> perfect, but we can improve it over time (and it's an improvement on
> current in many ways). Once it goes live, bugs will flood in; adding to the
> pressure to fix the above things you mentioned. I think you've already
> filed bugs for the above, right?
>
> >
> > On Wed, Feb 17, 2016 at 7:14 AM, tripu <notifications@github.com> wrote:
> >
> > > I honestly don't understand pub scheme migration at the W3C. Every time
> > > there is an effort like this, it seems to get thrwarted before it gets
> > > launched.
> > >
> > > :(
> > > I hope it's not the case this time, @halindrome
> > > <https://github.com/halindrome>!
> > > Anything in particular that is bothering you about this *tr-design*
> > > project…?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/w3c/respec/issues/569#issuecomment-185198999>.
>
> > >
> >
> >
> >
> > --
> > Shane McCarron
> > halindrome@gmail.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/569#issuecomment-185460493>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by plehegar** [comment]
Note that, independently to what respec can generate, pubrules will only accept one specific /TR style for a given period of time. At the moment, that time period was meant to be 12 months, from January 1 to December 31.
https://github.com/w3c/tr-design/blob/gh-pages/README.md

**Comment by tripu** [comment]
> Sure.  But I generally keep my mouth shut about them.   Line spacing is weird in some cases (nested sections with no content in the parent have a wide gap; successive dd elements after a dt have a lot of space between them).  I don't like the ToC on the left side on wide monitors.  Or at least it should be resizeable.  I could go on.

Ah, OK then, @halindrome; you meant *specific technical issues*. Those are being addressed in project `tr-design`, so we're good. (I thought you meant you had philosophical doubts about the project, or something like that :)

**Comment by tripu** [comment]
> Note that, independently to what respec can generate, pubrules will only accept one specific /TR style for a given period of time. At the moment, that time period was meant to be 12 months, from January 1 to December 31. https://github.com/w3c/tr-design/blob/gh-pages/README.md

(Again, with the caveat that we *may* not do the switches on January 1 every year, like experience has demonstrated.)
