### ISSUE TITLE
When the new styles go live, what should we do?

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#570]
Sounds like the new styles will be live soon.  Right now there is a "useExperimentalStyles" flag that takes a value or a boolean.  How should we handle this when the actual changeover occurs?

1. Remove support for the old styles altogether - making the new "experimental" the default case.
2. Change the default value of useExperimentalStyles to "/2016/" so that everything just starts using it, but a spec could override by changing the value to false or "".
3. Do the above and also add a warning if you disable the new styles.

Personally, I prefer 1.  But there may be riots in the streets.

**Comment by plehegar** [comment]
The plan was always to only allow one style for a given year so documents using the old styles will be rejected by pubrules once we do the switch. See
 https://github.com/w3c/tr-design/blob/gh-pages/README.md
We'd keep experimental for the next release of style sheets.

**Comment by marcoscaceres** [comment]
@halindrome, @plehegar, sounds like 1 is the way to go. 

However, 2 will still apply but we need a location for evolving experimental styles. Once the new code goes in (PR #571), option 2 will automatically just take the current year and use that for experimental styles (when the `useExperimentalStyles: true`). However, a user may set the particular version by using `useExperimentalStyles: "2016"` or whatever. 

I'm not entirely happy with the above, so we need to discuss a more robust solution for opting into the experimental styles. Right now, the fixup.js script is still buggy, and we should expect regular fixes as this rolls out.

**Comment by marcoscaceres** [comment]
Nothing left to be done here. We shall see if issues arise at the end of the year, but people shouldn't be opting into experimental style for "production" drafts, only for testing. We should get @fantasi to maybe show a banner via css that says "this is an experimental style sheet".
