### ISSUE TITLE
Use Karma instead of Phantomjs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#572]
It seems pointless to use Phantomjs for anything other than the spec generator. Phantomjs is constantly out of date, doesn't support any new shinny, and it is generally a piece of crap to work with and debug. 

Karma uses actual browsers and works with Travis. Thus, we should retire our use of Phantom and move to using Karma and never look back.

**Comment by tripu** [comment]
(I take note of the idea, for other projects we have using PhantomJS!)
