### ISSUE TITLE
Console warning: The key "shrink-to-fit" is not recognized and ignored.

### ISSUE THREAD

**Issue by ddorwin** [w3c/respec#574]
1. Load a ReSpec source doc.
1. Look at the developer console output.
1.  See the following warning:

> The key "shrink-to-fit" is not recognized and ignored.

**Comment by halindrome** [comment]
This is a browser-dependent warning.  It is used in some browsers.

On Fri, Feb 26, 2016 at 4:12 PM, ddorwin <notifications@github.com> wrote:

>
>    1. Load a ReSpec source doc.
>    2. Look at the developer console output.
>    3. See the following warning:
>
> The key "shrink-to-fit" is not recognized and ignored.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/574>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by ddorwin** [comment]
Thanks. I thought it might be an unused item like I sometimes seen in my ReSpec. Chrome does not report this in newer versions: https://bugs.chromium.org/p/chromium/issues/detail?id=569649.
