### ISSUE TITLE
ReSpec output causes W3C validator warning: "Element body does not need a role attribute."

### ISSUE THREAD

**Issue by ddorwin** [w3c/respec#575]
1. Use https://validator.w3.org to check a spec created with ReSpec
2. Observe the following:

> `Warning: Element body does not need a role attribute.`
> `From line 725, column 3; to line 725, column 71`
> `</head>↩  <body class="h-entry toc-inline" role="document" id="respecDocument"><p id=`

**Comment by halindrome** [comment]
THank you for this information.  I will talk to the validator people.  This
is a silly warning IMHO.

On Fri, Feb 26, 2016 at 5:52 PM, ddorwin <notifications@github.com> wrote:

>
>    1. Use https://validator.w3.org to check a spec created with ReSpec
>    2. Observe the following:
>
> Warning: Element body does not need a role attribute.
> From line 725, column 3; to line 725, column 71
> </head>↩ <body class="h-entry toc-inline" role="document"
> id="respecDocument"><p id=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/575>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Isn't role implied?

**Comment by halindrome** [comment]
Sure - this was (again) for RDFa.  I think I can work around it. But it is
silly to flag that up.

On Sat, Feb 27, 2016 at 8:22 AM, Marcos Caceres <notifications@github.com>
wrote:

> Isn't role implied?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/575#issuecomment-189650263>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> On 28 Feb 2016, at 3:32 AM, Shane McCarron <notifications@github.com> wrote:
> 
> Sure - this was (again) for RDFa. I think I can work around it. But it is
> silly to flag that up.

Unrelated, but I wonder if we should get HTML to have a "Element.getComputedARIARole()" API. Wouldn't that solve all these problems? as RDFa could just rely on that to see if it needs to add a role - or can generate the triple from that?

**Comment by halindrome** [comment]
Well - in theory.  And there is such an API being proposed in ARIA 1.1 I
think.  But RDFa doesn't require a DOM nor a browser so that interface
wouldn't really be around.  RDFa and the Role Attribute are very explicit
about what attributes MUST be present on each element in order to be
processed.  Same with microdata.  There are no implicit "roles" for RDFa.
That would lead to bizarre garbage triples in the output.

On Sat, Feb 27, 2016 at 7:27 PM, Marcos Caceres <notifications@github.com>
wrote:

>
>
> > On 28 Feb 2016, at 3:32 AM, Shane McCarron <notifications@github.com>
> wrote:
> >
> > Sure - this was (again) for RDFa. I think I can work around it. But it is
> > silly to flag that up.
>
> Unrelated, but I wonder if we should get HTML to have a
> "Element.getComputedARIARole()" API. Wouldn't that solve all these
> problems? as RDFa could just rely on that to see if it needs to add a role
> - or can generate the triple from that?
>
> >
> > On Sat, Feb 27, 2016 at 8:22 AM, Marcos Caceres <
> notifications@github.com>
> > wrote:
> >
> > > Isn't role implied?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/w3c/respec/issues/575#issuecomment-189650263>.
> > >
> >
> >
> >
> > --
> > Shane McCarron
> > halindrome@gmail.com
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/575#issuecomment-189758843>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> On 29 Feb 2016, at 9:17 AM, Shane McCarron <notifications@github.com> wrote:
> 
> Well - in theory. And there is such an API being proposed in ARIA 1.1 I
> think. But RDFa doesn't require a DOM nor a browser so that interface
> wouldn't really be around.

I guess it would be "Web RDFa" then :)

> RDFa and the Role Attribute are very explicit
> about what attributes MUST be present on each element in order to be
> processed.

This seems redundant, as markup is not the DOM. And where there is a... Hey! Whoa! I nearly went down the rabbit hole! 

> Same with microdata.

Microdata died, didn't it? 

> There are no implicit "roles" for RDFa.
> That would lead to bizarre garbage triples in the output.

I guess it depends on if the graph is built from markup or from the DOM. Anyway, not in scope for ReSpec. 

Close?

**Comment by stevefaulkner** [comment]
The reason `<body role="document">` throws a warning is that the rules for use of [ARIA in HTML](https://www.w3.org/TR/html-aria/#docconformance) define the use of default roles, for all HTML elements that have implied ARIA roles, as SHOULD NOT, if an author has a good reason to ignore the warning, that is their choice. The reasoning for this rule is that adding default roles are in general cruft.

**Comment by halindrome** [comment]
Excellent point steve,  I will point out to the pubrules people that those
warnings are not critical.  But I will also attempt to update RDFa to do it
a different way.  So no, let's leave this open.  I will fix it.  I was just
waiting until after Tuesday.

On Mon, Feb 29, 2016 at 4:51 AM, stevefaulkner <notifications@github.com>
wrote:

> The reason <body role="document"> throws a warning is that the rules for
> use of ARIA in HTML <https://www.w3.org/TR/html-aria/#docconformance>
> define the use of default roles, for all HTML elements that have implied
> ARIA roles, as SHOULD NOT, if an author has a good reason to ignore the
> warning, that is their choice. The reasoning for this rule is that adding
> default roles are in general cruft.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/575#issuecomment-190152217>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
What are the next steps here, @halindrome?

**Comment by marcoscaceres** [comment]
Ping @halindrome.
