### ISSUE TITLE
<dfn id="x" dfn-for="y">constructor</dfn> causes JS error

### ISSUE THREAD

**Issue by domenic** [w3c/respec#582]
Presumably someone should be using a `Map` or `Object.create(null)` instead of an object, as otherwise `o.constructor === Object`.

Haven't created a tiny repro case but ran into this working on the custom elements spec.

**Comment by marcoscaceres** [comment]
@domenic will take a look.

**Comment by halindrome** [comment]
This also seems to effect http://w3c.github.io/selection-api/

**Comment by marcoscaceres** [comment]
@domenic, we are still working to fix it. Hoping to have a fix by monday.
