### ISSUE TITLE
Warning left border bigger than right border

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#584]
Like this is not pretty: 

![screenshot 2016-03-02 13 14 42](https://cloud.githubusercontent.com/assets/870154/13448665/ee583e8a-e078-11e5-9a5e-e8c7de42e31e.png)

**Comment by halindrome** [comment]
What spec was this in?  And do you think it is a respec issue or a tr-design issue?

**Comment by marcoscaceres** [comment]
This is in Web manifest.... might be my fault... haven't checked
