### ISSUE TITLE
Errors in the lab version...

### ISSUE THREAD

**Issue by iherman** [w3c/respec#589]
I do not know whether this is related to #585; if so, sorry for the noise!

See:

![screen shot 2016-03-02 at 10 57 47](https://cloud.githubusercontent.com/assets/520723/13456923/ad9abb56-e065-11e5-9b66-f3da2dcc7dcb.png)

**Comment by marcoscaceres** [comment]
@iherman, can you post the URL for that ... I will take a look.

**Comment by marcoscaceres** [comment]
actually, never mind! must be the same thing as  #590

**Comment by marcoscaceres** [comment]
Confirmed... I think once 590 lands it should also fix itself.

**Comment by marcoscaceres** [comment]
@iherman, it's working now (tested it with the ARIA spec that Steve pointed to). Please reopen if it's not working for you.

**Comment by iherman** [comment]
Just for the records, it indeed works now.
