### ISSUE TITLE
can't save snapshot 

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/respec#590]
when attempting to save a snapshot via the respec button nothing happens
for example on this http://rawgit.com/w3c/aria/master/practices/aria-practices.html (i have checked othe specs as well same deal)
when activating the save snapshot menu button expect list of options html/xhtml etc to be displayed, but they are not.
Don't know if this has anything to do with use of new style, but was working OK prior to their introduction.

**Comment by marcoscaceres** [comment]
Will investigate...

**Comment by marcoscaceres** [comment]
Confirmed... it doesn't happen with the unbuilt version, but happens once ReSpec is packaged up

**Comment by marcoscaceres** [comment]
@stevefaulkner, need a day to fix (it's just on midnight here now). Thanks for your patience.

**Comment by marcoscaceres** [comment]
Ok, found the bug... sent a PR #593.
