### ISSUE TITLE
jquery prototype is not extended with functions in utils

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#597]
Many extension functions, both embedded in script elements and in external files, rely upon the '$' Object being extended by the $.fn methods in the utils.js module.  This does not appear to be happening now.  So, for example, the following code in a method that was called using data-oninclude used to work and now fails:

<pre>
   $.each(base.querySelectorAll("dfn"), function(i, item) {
        var $t = $(item) ;
        var titles = $t.getDfnTitles();
        var n = $t.makeID("dfn", titles[0]);
        if (n) {
            termNames[n] = $t.parent() ;
        }
    });
</pre>

$t.getDfnTitles and $t.makeID both fail to resolve now.  I am attempting to run this down, but I suspect @marcoscaceres will know immediately where to look!

**Comment by marcoscaceres** [comment]
Ah! I broke that, indeed :) adding things to the prototype of jquery is a terrible idea regardless, so will make a new helper object.

**Comment by marcoscaceres** [comment]
This was fixed by release 106
