### ISSUE TITLE
"save snapshot" not working on Firefox 44.0.2?

### ISSUE THREAD

**Issue by iherman** [w3c/respec#600]
I run https://w3c.github.io/csvw/syntax/ in FF 44.0.2 on Mac OS X 10.11.3 (El Capitan); pushing the 'Respec' button gives the pop-up menu, but none of the actions work:-(

The same file works on Chrome on the same machine.

**Comment by tripu** [comment]
I can't reproduce it on Linux.
@iherman, can you clear your browser's cache and retry? Also, see if there are JS errors on the console (I think it's &#8984;+shift+K) or if any of the assets failed loading (perhaps &#8984;+shift+Q)?

**Comment by iherman** [comment]
Oops, a cache clear did it. But how come? Were there such drastic changes?

Anyway… sorry for the noise

**Comment by tripu** [comment]
No idea. It's difficult to predict the behaviour of pages when some of their assets are stuck in a cache somewhere between the source and the user&hellip;

**Comment by halindrome** [comment]
Yes - respec was effectively rewritten in the last two weeks.  Well, more
or less.

On Thu, Mar 3, 2016 at 9:22 AM, tripu <notifications@github.com> wrote:

> No idea. It's difficult to predict the behaviour of pages when some of
> their assets are stuck in a cache somewhere between the source and the user…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/600#issuecomment-191812901>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Browsers cache very aggressively. I need to check what headers the w3c servers are using. I'm also thinking that using service workers to perform updates might help here.
