### ISSUE TITLE
Should still test against phantomjs

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#604]
Echidna / whatever else is in that tool chain uses phantomjs as the environment for ReSpec - so we should ALSO test using phantomjs if that is at all possible.  Is it @marcoscaceres ?

**Comment by marcoscaceres** [comment]
We still do spec generation tests against Phantomjs (see/run `./tests/headless.js`). These are run both on Travis and any time one does `npm test`. This tests that ReSpec is built correctly, and that those documents load properly. 

However, it's pointless to run the specs on Phantomjs, as Phantomjs is not a web browser (and it's always grossly out of date in terms of feature support). Hence, any failures on PhantomJS are not representative of anything remotely resembling a web browser. 

Karma, otoh, runs the tests in real web browsers - specially important if maintainers `npm test` locally before committing. This allows us to test our code a across a wide range of platforms and browsers (not as good as using [SauceLabs](https://saucelabs.com/), will set that up eventually, but pretty good for now). 

Make sense?

**Comment by tripu** [comment]
> *&ldquo;Echidna / whatever else is in that tool chain uses phantomjs as the environment for ReSpec.&rdquo;*

Yes, [spec-generator](https://github.com/w3c/spec-generator) uses `phantomjs`. I'm looking at moving to `phantomjs-prebuilt`, at least.

**Comment by marcoscaceres** [comment]
@tripu, I've been using latest Phantomjs-prebuilt here and it works great.
