### ISSUE TITLE
Can we provide a Promise that will resolve when everything is really done?

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#607]
One of the problems people have with extending ReSpec / providing other instrumentation is that we don't fire any sort of event that means "we are really really really done".  Is there a way to accomplish this with a Promise?  Or with a DOM event?

**Comment by marcoscaceres** [comment]
Yes, indeed we can :) A promise is better than an event, because, with an event you are always racing against time. It should be trivial to implement (famous last words).
