### ISSUE TITLE
Need better list of specs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#612]
The list of specs using respec in the examples folder is unrepresentative of real specs (I.e., using it in testing is close to useless). We need to gather a list of real specs to test our generation-code against.

**Comment by halindrome** [comment]
I have all sorts of specs that rely upon ReSpec.  But what does it mean to test against them?  What would constitute a pass?  A fail?

**Comment by marcoscaceres** [comment]
Good questions. I guess it would mean no syntax or js errors from ReSpec or its dependencies. Authors errors would be ok.

**Comment by halindrome** [comment]
Understood.  Let me see if I can stick a few into the test bucket from my collection.

**Comment by marcoscaceres** [comment]
We should just start by collecting a new set of examples (and maybe have a script that auto d/l new versions and changes the script tag). I know you have a few good ones from web payments. I got a few personal ones too. The more the better.

**Comment by marcoscaceres** [comment]
The following are now outdated, so we need to remove/update/replace them: 

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

Error: Command failed: phantomjs --ssl-protocol=any ./tools/respec2html.js --delay 1 -w -e http://localhost:3000/examples/basic.html /dev/null 10

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

1:19:00 AM  🚄  Running test 3 of 9.

1:19:02 AM  🚄  Running test 4 of 9.

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

Error: Command failed: phantomjs --ssl-protocol=any ./tools/respec2html.js --delay 1 -w -e http://localhost:3000/examples/experimental.html /dev/null 10

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

1:19:04 AM  🚄  Running test 5 of 9.

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

Error: Command failed: phantomjs --ssl-protocol=any ./tools/respec2html.js --delay 1 -w -e http://localhost:3000/examples/getusermedia.html /dev/null 10

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

1:19:05 AM  🚄  Running test 6 of 9.

1:19:07 AM  🚄  Running test 7 of 9.

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

Error: Command failed: phantomjs --ssl-protocol=any ./tools/respec2html.js --delay 1 -w -e http://localhost:3000/examples/previousVersions.html /dev/null 10

WARN:  Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl
