### ISSUE TITLE
Better support for illegal-example

### ISSUE THREAD

**Issue by darobin** [w3c/respec#62]
These are not handled completely well — they should cause an additional "illegal" class to be added to the container, and styled accordingly.

**Comment by marcoscaceres** [comment]
Do you have an example spec that makes use of this? Maybe a few more details about the kind of styling you would expect to see?

**Comment by darobin** [comment]
Illegal examples should be styled differently from legal ones. I think this is mostly a CSS improvement.

**Comment by marcoscaceres** [comment]
Moved to TR style project instead.
