### ISSUE TITLE
Write a pre-commit hook that checks that `fdescribe` and `fit` are not present in tests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#622]
A `fdescribe()` slipped through, which focuses the test suite :( My bad. Will add a test for this, initially as a pre-commit hook.

**Comment by halindrome** [comment]
Is there any way (not now - someday) to add a command line hook that would run a subset of the tests without having to edit the driver file?  I thought it used to do this.

**Comment by marcoscaceres** [comment]
There probably is through Jasmine + that little test file generator tool. You could generate just the list of tests you want, and then feed them to Jasmine via localhost. Like:
```bash
# Would just dump the tests you give it... 
./tools/make-testfiles.js -f files, to, test
# Would just open the given tests... 
open http://localhost:8000/test/SpecRunner.html 
```

**Comment by marcoscaceres** [comment]
NB: I haven't implemented support for giving the test file generator the ability to pick only certain files, but it would be really trivial to do.

**Comment by marcoscaceres** [comment]
Maybe file a separate file for the above?

**Comment by marcoscaceres** [comment]
...err, separate bug I mean

**Comment by marcoscaceres** [comment]
handled by ESLint now
