### ISSUE TITLE
Add code coverage support 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#631]
We should add a code quality tool like code climate to get an idea of gaps in our tests.

**Comment by CodHeK** [comment]
@marcoscaceres [this](https://codeclimate.com/quality/) is the one right ?

**Comment by marcoscaceres** [comment]
yep, but it's one of many.

**Comment by CodHeK** [comment]
`Codacy` is already being used as a code quality tool right ?

**Comment by marcoscaceres** [comment]
yes, but Codacy doesn't tell us what is being tested by our test suite... can it? 

just talking to a friend of mine, she is telling me https://jestjs.io might be compatible with our setup - as our test suite is based on Jasmine.

**Comment by CodHeK** [comment]
hm..oh, yes! This looks nice, maybe we can try this!

**Comment by marcoscaceres** [comment]
yeah, I think it's a good option... they should have a "migrating from Jasmine" guide... but please see if there are some blog posts with criticisms from other projects.

**Comment by CodHeK** [comment]
Uh, yeah using jestjs would make us shift entirely from jasmine to jest right, the tests need to be re-written ?

**Comment by marcoscaceres** [comment]
@saschanaz, from other projects you work on, any experience or suggestions in this area? I can also ask folks on twitter... though it might depress. 

We could check what big open source projects are using... like Babel, or some others.

**Comment by CodHeK** [comment]
@marcoscaceres got this blog, [https://fuhton.com/Migrating-from-Jasmine-to-Jest/](https://fuhton.com/Migrating-from-Jasmine-to-Jest/) I believe we must shift our testing suite to jest, it's got an inbuilt code-coverage tool and syntax looks pretty similar to jasmine.

**Comment by marcoscaceres** [comment]
Looks like the APIs are very close... so looks like minimal rewrite. That's a huge bonus.

**Comment by CodHeK** [comment]
Yes, exactly!

**Comment by marcoscaceres** [comment]
Some reading material 
https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2018-f68950900bc3

**Comment by CodHeK** [comment]
@marcoscaceres so, how should I proceed towards implementing this ? I skimmed through the jest docs, doesn't look any different than jasmine, should I begin with it's integration then ?

**Comment by marcoscaceres** [comment]
Not yet. An important part of decision if to weight the pros/cons. It’s why I asked if you could find some blogs criticizing it so we can evaluate its merits. 

The other things we would do is maybe prototype one module to see if it works and the report we get.

**Comment by CodHeK** [comment]
Right! I'll do a bit more research on this first and get back to you!

**Comment by CodHeK** [comment]
@marcoscaceres we could probably use this [https://github.com/skovhus/jest-codemods](https://github.com/skovhus/jest-codemods) , might make the jasmine to jest migration really easy!

**Comment by marcoscaceres** [comment]
@CodHeK, could you try a couple of our tests, see what comes out? Intrigued to see this working.

**Comment by CodHeK** [comment]
Using the `codemods` right ?

**Comment by marcoscaceres** [comment]
Yep, using codemods.

**Comment by CodHeK** [comment]
@marcoscaceres I am a little confused here, I see there is `karma` , `mocha` `jasmine` all three of them present in the `package.json` file, how exactly are we testing here ?

**Comment by CodHeK** [comment]
I am having problems ( permission errors ) with install jest, is there any sort of restriction in the repo that doesn't let others install new packages ?

**Comment by marcoscaceres** [comment]
No, there should be no restriction. Can you paste in the error?

**Comment by CodHeK** [comment]
![screenshot 2019-02-09 at 3 00 44 pm](https://user-images.githubusercontent.com/22097366/52519045-89711580-2c7b-11e9-9aca-43994bed4f97.png)

@marcoscaceres I don't know it says `permission denied`, I even tried adding `sudo` didn't work
I tried it on one of my other projects it got installed without any errors! 😕

**Comment by CodHeK** [comment]
Also, I tried the `codemods` on the `/tests/spec/core/linter-rules` folder worked really well! 😄 now I just need to install `jest` to check if those tests pass.

**Comment by marcoscaceres** [comment]
I would try removing the entire node_modules directory and doing `npm install` again. It’s definitely looking like the jest directory has bad permissions for whatever reason.

**Comment by CodHeK** [comment]
@marcoscaceres it's starting to work! :D 

I used `codemods` on the `/tests/spec/core/linter-rules` folder, ran `npm test` got this...

![screenshot 2019-02-10 at 1 01 46 pm](https://user-images.githubusercontent.com/22097366/52531148-06ad9080-2d37-11e9-8934-33974d517f8a.png)

Iit seems `jest` doesn't work with `RequireJS` need to find a workaround for this!

**Comment by marcoscaceres** [comment]
Ok, this is good to know. Additional motivation to get rid of RequireJS as a dependency. Appreciate you digging into this.

**Comment by CodHeK** [comment]
`require([`core/linter-rules/${ruleName}`], ({ rule }) => resolve(rule));` is this the part where `RequireJS` is being used ?

**Comment by marcoscaceres** [comment]
Yeah, it could be... what happens if you treat that as an ES6 import instead? The RequestJS is irrelevant. 

```
import { rule } from  "/src/core/linter-rules/check-charset";
```

**Comment by CodHeK** [comment]
`import { rule } from  '../../../src/core/linter-rules/check-charset';` this would be correct with the right path right ?

 I don't know why I get this error saying `Cannot find module '../../../src/core/linter-rules/check-charset' from 'check-charset-spec.js`

**Comment by CodHeK** [comment]
@marcoscaceres  `import { rule } from  '../../../../src/core/linter-rules/check-charset.js';` this worked "
😛

**Comment by CodHeK** [comment]
@marcoscaceres jest worked! 🎉 
![screenshot 2019-02-11 at 4 28 08 pm](https://user-images.githubusercontent.com/22097366/52559113-5fa22500-2e1a-11e9-8774-6485d4ca1d47.png)

**Comment by marcoscaceres** [comment]
Ok, awesome! How do we now pull coverage information from it?

**Comment by CodHeK** [comment]
We can just run `npm coverage` for that!

**Comment by marcoscaceres** [comment]
I've never do it, so what does it produce?

**Comment by CodHeK** [comment]
I'll just implement it on the `linter-rules` folder and post a screenshot here!

**Comment by marcoscaceres** [comment]
Appreciate that. Excited to see where this is going!

**Comment by CodHeK** [comment]
@marcoscaceres The coverage is of this sort...

![screenshot 2019-02-11 at 4 39 35 pm](https://user-images.githubusercontent.com/22097366/52559614-b9571f00-2e1b-11e9-8fb9-edb3424c1c5b.png)

![screenshot 2019-02-11 at 4 39 26 pm](https://user-images.githubusercontent.com/22097366/52559609-b3f9d480-2e1b-11e9-9477-eeb0c183c0ad.png)

**Comment by marcoscaceres** [comment]
Very nice! 

We probably don’t need to save to a file, but we might still want this to somehow be part of our continuous intergration process. We would generally want 100% coverage for any new code.

**Comment by marcoscaceres** [comment]
Ok, something like this might work 🤔 

https://github.com/nickmerwin/node-coveralls/blob/master/README.md#jest

**Comment by CodHeK** [comment]
@marcoscaceres yeah!! 

```
    - stage: Run eslint
      script:
        - npm run lint
    - stage: Run headless
      script:
        - npm run test:headless
    - stage: Run Karma unit tests
      script:
        - travis_retry karma start --single-run --reporters mocha karma.conf.js
```

I'll have to replace the karma units tests with these right or we run both ? 😕

**Comment by marcoscaceres** [comment]
Yeah, there seems to be good instructions here:
https://medium.com/@ollelauribostr/start-measuring-coverage-with-jest-travis-ci-and-coveralls-1867928aca42

I’d try bundling everything up into a pull request. I’ve enabled coveralls for ReSpec over on coveralls.io... so should see something work hopefully 🤞

**Comment by marcoscaceres** [comment]
Note we use “develop” instead of “master”.

**Comment by CodHeK** [comment]
@marcoscaceres I'll make all the tests ready and passing with jest until then! Should I also do the travis integration ?

**Comment by marcoscaceres** [comment]
> karma units tests with these right or we run both ?

Not sure yet. Karma will probably break I think, so I think it will be jest only.

**Comment by CodHeK** [comment]
@marcoscaceres there's a small problem with the other tests, the line `afterAll(flushIframes)` (eg: `algorithms-spec.js`) , I don't see where the function `flushIframes` is being imported here... 😕

**Comment by marcoscaceres** [comment]
About the work items. I’d suggest sending a pull request now. We won’t merge it, but it’s to make sure we can check it’s on the right track. This might turn out to be a lot of work... so go slow. Do the easy ones first and get feedback.

**Comment by CodHeK** [comment]
Yes! Sending one now!

**Comment by marcoscaceres** [comment]
It’s imported via https://github.com/w3c/respec/blob/develop/tests/spec/SpecHelper.js

Which may be part of Jasmine. Jest must have an equivalent.

**Comment by CodHeK** [comment]
Yes, but how is it imported in the file test files, I don't see any `require` or `imports` ?

**Comment by CodHeK** [comment]
Oh, okay these are `Globals` ! 😅

**Comment by marcoscaceres** [comment]
Heh, yep... sort of. So:
https://github.com/w3c/respec/blob/develop/tests/SpecRunner.html

And there is one more...

**Comment by marcoscaceres** [comment]
karma injects it too:

https://github.com/w3c/respec/blob/develop/karma.conf.js

**Comment by marcoscaceres** [comment]
Jest must have some kind of global loader too.

**Comment by CodHeK** [comment]
I shall send a PR now, `linter-rules` folder is set! There's a lot work left on the other test file which I shall complete gradually ... 

And yes, jest has something called as `mockers` I guess for such Globals.

**Comment by CodHeK** [comment]
@marcoscaceres sent a PR - https://github.com/w3c/respec/pull/2085

**Comment by marcoscaceres** [comment]
What we could do is incrementally transition from Karma/Jasmine to jest being explicit about which runner runs what. That will allow us to do one at a time, and hopefully prevent bit-rot. We could start with the linters and then some of the easy ones.

**Comment by CodHeK** [comment]
Should I add travis too ? like only for the linter-rules folder ?

**Comment by marcoscaceres** [comment]
Yes, adding TravisCI support would be great.

**Comment by elharony** [comment]
Hi @marcoscaceres ,

I would like to contribute and help fixing this issue, as it's marked as <kbd>[Good First Issue](https://github.com/w3c/respec/labels/good%20first%20issue)</kbd> but it doesn't seem to be so. Am I right? Please provide some guidelines here! 🙏

**Comment by saschanaz** [comment]
I intend to fix this in #2187, so removing the tag.

Current state there:

```
tests/test-node.js
  Core — data-abbr
    √ processes definition abbreviations (4500.396ms)
    √ allows different abbreviation combinations to link to dfn (76.59ms)
    √ correctly parses and abbreviates different Abbreviation syntax (80.698ms)
    √ warns when used with unsupported elements (68.492ms)
    √ normalizes title of added abbr for unwanted spaces (65.78ms)


  5 passing (10s)
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |    29.92 |     23.2 |    27.75 |    30.43 |                   |
 js                    |    71.43 |    62.16 |    82.35 |    73.26 |                   |
  html-parser.js       |    72.73 |    58.33 |    66.67 |       80 |              5,17 |
  html-template.js     |       70 |       64 |    83.33 |    70.15 |... 09,110,111,113 |
  respec-version.js    |       80 |    58.33 |      100 |    88.89 |                 5 |
 src                   |       90 |    44.44 |      100 |       90 |                   |
  index.js             |      100 |      100 |      100 |      100 |                   |
  respec-document.js   |    83.33 |    44.44 |      100 |    83.33 |             14,30 |
 src/core              |    21.47 |    15.15 |    20.49 |    21.82 |                   |
  asset-loader.js      |      100 |      100 |      100 |      100 |                   |
  cgbg-headers.js      |        0 |        0 |        0 |        0 |                 7 |
  cgbg-sotd.js         |        0 |        0 |        0 |        0 |                 5 |
  headers.js           |    66.67 |    44.05 |      100 |    66.67 |... 59,277,286,292 |
  show-link.js         |        0 |        0 |        0 |        0 | 6,8,9,10,11,13,20 |
  show-logo.js         |        0 |        0 |        0 |        0 |... 11,14,24,25,26 |
  show-people.js       |    45.45 |    30.43 |       50 |    46.88 |... 99,102,104,105 |
  sotd.js              |    45.83 |    36.14 |    41.67 |    45.83 |... 80,283,310,337 |
 tests                 |       75 |      100 |       50 |       75 |                   |
  test-node.js         |       75 |      100 |       50 |       75 |             27,28 |
 tests/spec            |    12.79 |       10 |       15 |    12.79 |                   |
  SpecHelper.js        |    12.79 |       10 |       15 |    12.79 |... 85,199,210,217 |
 tests/spec/core       |      100 |      100 |      100 |      100 |                   |
  data-abbr-spec.js    |      100 |      100 |      100 |      100 |                   |
-----------------------|----------|----------|----------|----------|-------------------|
```

**Comment by marcoscaceres** [comment]
@saschanaz, looks like you had coverage kinda working in #2187... is it possible to extract just that from #2187?

**Comment by saschanaz** [comment]
@marcoscaceres 

1. It works on Node.js, which we don't prioritize now 😱
2. I used another test framework to do that, migration was not very straightforward.

**Comment by marcoscaceres** [comment]
No problem. I’ll see if there is some other alternative.

**Comment by marcoscaceres** [comment]
Giving up on this for now...
