### ISSUE TITLE
Use CDN for jquery

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#636]
It might be smarter to load jQuery from a CDN. Given the high cache hit rate for jquery served from google, we should save significant time just using Google's CDN version. 

The trade off is that we lose control over the version, but could be worth it - specially as we look at reducing our reliance on jQuery.

**Comment by halindrome** [comment]
Instead of bundling it?  I would prefer not.  Right now people can drop a copy of respec on their laptop and to work in a park.  I do it all the time.  Others have mentioned they put copies into their github repo so it is stand alone and they can work off line.  I wouldn't want to lose that feature.

**Comment by marcoscaceres** [comment]
But one still relies on external resources, like all the W3C CSS files, fixup.js, etc.

**Comment by halindrome** [comment]
Huh - I wonder why that just works?  I mean, the fixup.js crap is new, but
the CSS.  Must be cached locally for those of use who do this.   Good
points.

On Thu, Mar 10, 2016 at 8:14 AM, Marcos Caceres <notifications@github.com>
wrote:

> But one still relies on external resources, like all the W3C CSS files,
> fixup.js, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/636#issuecomment-194864366>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
HTTP caching :)

**Comment by marcoscaceres** [comment]
That's exactly my point. The cache times are long lived, and with Service Workers + Foreign Fetch, we can have true offline support.

**Comment by marcoscaceres** [comment]
Should also add SRI: 

```
<script
  src="https://code.jquery.com/jquery-2.2.1.js"
  integrity="sha256-eNcUzO3jsv0XlJLveFEkbB8bA7/CroNpNVk3XpmnwHc="
  crossorigin="anonymous"></script>
```

**Comment by marcoscaceres** [comment]
Note to self: this can be done with the "onBeforeNodeInserted" prop on requirejs' config. Need to check the URL matches jQuery, and then add in the integrity and cross origin attributes. Otherwise, it can be done with a custom module, that creates and inserts jQuery as a script tag instead of as part of "define".

**Comment by marcoscaceres** [comment]
Closing as won't fix. Going to see if we can get a minimal version of jQuery instead.
