### ISSUE TITLE
Tests should test spec generation against pubrules

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#639]
Since a major customer for respec is w3c publications, we should ensure that generated specs (continue to) pass pubrules.

**Comment by xfq** [comment]
Related: https://github.com/w3c/respec/issues/792

**Comment by sidvishnoi** [comment]
We should do this in [respec-validator](https://github.com/marcoscaceres/respec-validator) probably.

**Comment by sidvishnoi** [comment]
Closing in favor of https://github.com/w3c/respec/issues/792
