### ISSUE TITLE
Deprecate webspecs status support 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#643]
Webspecs never happened, unfortunately. So we should deprecate that code.

**Comment by tripu** [comment]
Does this refer to `specStatus` `webspec` (in singular)?

Is this why [`w3c.github.io/modern-tooling`](https://w3c.github.io/modern-tooling/) can't find the CSS file it's looking for?

**Comment by marcoscaceres** [comment]
> On 22 Mar 2016, at 9:22 PM, tripu <notifications@github.com> wrote:
> 
> Does this refer to specStatus webspec (in singular)?
> 

Yes.

> Is this why w3c.github.io/modern-tooling can't find the CSS file it's looking for?
> 

I don't know, tbh. But probably.

**Comment by tripu** [comment]
@marcoscaceres, which would be the valid `specStatus` that is &ldquo;closest&rdquo; to the late `webspec`?
I need a replacement for [modern-tooling](https://w3c.github.io/modern-tooling/).
Thanks!

**Comment by halindrome** [comment]
I think this got dropped by accident TBH.  @marcoscaceres we never concluded that we should no longer support thus spec status... and all the support remains in the code.  The only problem is that js/w3c/style.js doesn't have the case for it in the switch statement. 

I don't like that we are breaking compatibility by removing features.  Especially when there is nothing to replace them.  There is no equivalent right now.  

@tripu - two options right now:

1. use specStatus "unofficial" - that will be ugly but it will work.
2. Add some stuff into your document header to emulate the support for webspec until we can get full support back in.  I will create a PR for that now.

What would you need to add?

The style sheet https://specs.webplatform.org/assets/css/kraken.css

The "icon" <link rel="icon" href="https://specs.webplatform.org/assets/img/icon.png">

And the script:  "https://specs.webplatform.org/assets/js/kraken.js"

If you embed those in your header it should just work.

**Comment by halindrome** [comment]
@tripu is there any value in attempting to support the new ToC styles in conjunction with the webspec styles?  I can probably do it.  Just not sure you want it - and I am afraid of collateral damage to other specs that we are unaware of.

**Comment by marcoscaceres** [comment]
We need numbers. Who is using webspec? I was under the impression that whole effort died?

**Comment by halindrome** [comment]
Oh - I certainly believe the effort died.  I just didn't want to break faith with existing documents that might reference it.  dont break the web.

**Comment by marcoscaceres** [comment]
I'm sorry, I'm still really confused. If this is dead, and we can't point to any documents that are is using it, then why are we supporting it?

**Comment by halindrome** [comment]
Well, we can point to at least *one*, since @tripu reported that the modern-tooling document no longer works.  We have no way of knowing who is using / dependent upon respec.  So we should always be careful to not break compatibility.  At least, that's my philosophy.
