### ISSUE TITLE
Save snapshot leaves fixup.js generated content in the saved document

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#644]
This results in two TOC toggles being inserted.  Arguably a bug in fixup.js, but we can address it here too by removing the node with ID toc-nav

**Comment by deniak** [comment]
The bug is not entirely fixed. Generated snapshots still end up with a class 'toc-sidebar' in the `<body>` which is a bug according to @fantasai https://github.com/w3c/tr-design/pull/91#issuecomment-208467559
