### ISSUE TITLE
W3C not serving source maps

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#647]
Source maps don't seem to be getting pushed to the w3c server - so don't get served. Will need W3C help here.

**Comment by dontcallmedom** [comment]
can you say more about which additional files need to be pushed?

**Comment by marcoscaceres** [comment]
@dontcallmedom builds/profile-w3c-common.build.js.map

**Comment by dontcallmedom** [comment]
https://www.w3.org/Tools/respec/profile-w3c-common.build.js.map now proxies to http://w3c.github.io/respec/builds/profile-w3c-common.build.js.map — let me know if that matches what you needed or not.

**Comment by marcoscaceres** [comment]
@dontcallmedom, sorry, I made a mistake :( The filename I was after was actually "respec-w3c-common.build.js.map"

**Comment by dontcallmedom** [comment]
https://www.w3.org/Tools/respec/respec-w3c-common.build.js.map is up and running

**Comment by marcoscaceres** [comment]
Yay! Thank you!
