### ISSUE TITLE
Permalinks that are right justified are on the wrong line (too high up)

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#652]
The new styles must have changed something.

**Comment by marcoscaceres** [comment]
Could you please drop in a screenshot?

**Comment by halindrome** [comment]
I *could*.  I would rather just fix it ;-)  I need to find the example I saw when I created this...  found it!  I do note that this does not happen all the time.  It might just be something they are doing wrong in the example spec at https://rawgit.com/w3c/aria/Mar_2016_Heartbeats/practices/aria-practices.html#dialog_nonmodal

![screenshot 2016-03-15 at 08 44 57](https://cloud.githubusercontent.com/assets/520688/13779686/45b8631a-ea8a-11e5-8193-e5423023d1eb.png)

**Comment by halindrome** [comment]
Nevermind - this is a bug in *their* style sheet.
