### ISSUE TITLE
Pubrules doesn't like viewport

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#654]
The latest respec inserts the following viewport meta tag:

<meta content="initial-scale=1.0, shrink-to-fit=no, width=device-width" name="viewport">

Pubrules expects:

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

The primary difference seems to be initial-scale=1 vs initial-scale=1.0; I don't know if pubrules also cares about the order of things in the content attribute, nor do I know if there is a processing difference between 1 and 1.0. I just know that the webmaster won't let me publish unless there is a clean pubrules report. Again I can't point to a sample URI because I'm manually fixing this in order to pass pubrules and be allowed to publish.

**Comment by halindrome** [comment]
Oh for crying out loud.  PLH says respec output passes pubrules.  @plehegar ?

**Comment by marcoscaceres** [comment]
verified. I wants 1.

**Comment by michael-n-cooper** [comment]
I confirm the fix is now passing pubrules.
