### ISSUE TITLE
Release.js: be more assertive about branch being out of date

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#656]
The release spec needs to be more assertive with checking if the develop branch is up to date, and do a git pull on it.

**Comment by halindrome** [comment]
Also the gh-pages branch.  And it should switch back to whatever branch it was on once the release.js completes.

**Comment by marcoscaceres** [comment]
> Also the gh-pages branch

Everything from develop gets merged onto gh-pages branch. This branch should never be out of date because: 

 1. we never touch it directly. 
 1. we do "git update remote" (which pulls down the remote gh-pages)

> And it should switch back to whatever branch it was on once the release.js completes.

Will add.
