### ISSUE TITLE
Investigate using preload for css, scripts, etc

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#663]
We include various things that would benefit from using [preload](https://w3c.github.io/preload/). 

It would be cool to see how much faster we can make the Preload Spec load by adding preload to ReSpec :dancer: 

cc @yoavweiss

**Comment by marcoscaceres** [comment]
Ok, I've been thinking about how to do this. Today, ReSpec does less than ideal things with regards to style sheets:

 1. it packages them up as text in the build script. 
 1. it treats them as text (via requirejs). 
 1. it includes them into the document after DomContentLoaded (hence #326). 
 1. it includes them directly in the spec, but our styles rarely change (like maybe like once every 6 months or less) - so they are prime candidates for long expires. 

This is not ideal. What we actually want is to externalize the css so it can be preloaded. We also need to make the plugin loader an independent module, allowing it to load css related things early (before DOMContentLoaded) and `.then()` do the document processing after we have the CSS.

So, this would mean: 

 * [ ] Make plugin loader its own JS module (which base-runner.js can use). 
 * [ ] Group modules into "before load", "after load" sets - allowing us to better control when things are injected. Make the style module add the style as link relationships, not at style elements. 
 * [ ] Talk to W3C about the possibility of externalizing our style sheets (cc @dontcallmedom) (or, worst case, we load them as text and inject them into the document at save time)

**Comment by dontcallmedom** [comment]
externalizing the respec style sheet on w3.org wouldn't be an issue at all; I can have the same system that mirrors the respec JS bundle mirror a similarly maintained stylesheet.

**Comment by yoavweiss** [comment]
Is it possible to add `Link:` headers to respec's JS response? That would probably be the easiest way to get the browser to load all required resources before parsing all the JS.

Otherwise, you'd need each spec to add `<link>`s, which may be cumbersome.

**Comment by dontcallmedom** [comment]
I'm reasonably sure I can get a Link header added to the w3.org respec; but this will increase the need of coordination when new links needs to be added or old ones removed; assuming this is not mission critical, that's probably OK though.

**Comment by marcoscaceres** [comment]
I'm a little hesitant to go the HTTP Link: route because I'm paranoid that Gecko won't add support for it (we don't have a good track record with things like that) - and the w3c would need to keep a list of specs that were generated with ReSpec so to add the Link: to the request (as our style won't make sense for BikeShed docs). 

Won't the Link header also need to be served from GH Pages (in the case of Editors' Drafts)?

**Comment by yoavweiss** [comment]
I'm talking about adding a Link header to the response for respec.js, not to the specs themselves. We should try it out and see how fast/slow it actually is.

Regarding Gecko support, I believe Gecko supports `Link` headers for everything that has `<link>` support. So the main concern there is to get `preload` support up and running.

**Comment by marcoscaceres** [comment]
@yoavweiss, sorry, still trying to understand how it all works... so more dumb questions: are you saying that:
 
```HTML
<head>
<script src="respec.js"></script>  
```

Would be served with a Link header like (psudo-code)  `Link: rel=preload; as=script`? If yes, what benefits are there, given that the script would block? 

> I believe Gecko supports Link headers

Interesting, I thought we only supported linking to CSS. If the machinery is there already, that's great!

**Comment by yoavweiss** [comment]
What I propose is:

* Spec HTML includes `<script src="respec.js">`
* Response to respec includes Link headers that trigger the download of all resources that respec depends on
* When the browser needs these resources, it can just the ones that were already fetched (or are in-flight).

I'm not 100% sure what would be the benefits, as I'm not sure how many resources does respec depend on and what is the dependency tree depth.

This would be less performant than including `<link>`s to these resources right in the spec's HTML, btu would require significantly less maintenance, and specs that would be interested in that extra perf boost would be able to add the links as well.

**Comment by marcoscaceres** [comment]
Added a bunch of pre-load. The next most significant thing we can do is replace jquery with cash (another js lib, had same API surface - sans the AJAX baggage - only like 5kb). The only performance bottle neck is that.
