### ISSUE TITLE
Parameter description columns are very narrow

### ISSUE THREAD

**Issue by rtoy** [w3c/respec#666]
In the latest release, the parameter description column is very narrow which makes it difficult to read.  See, for example, http://webaudio.github.io/web-audio-api/#methods-6.  The description of the `when` parameter is smashed into a narrow column that makes for hard reading.

Is there a way to make the columns a bit wider?

**Comment by halindrome** [comment]
Thank you for your comment.  This is actually an issue with tr-design, not respec.  I am going to close this issue and open one on your behalf over there.
