### ISSUE TITLE
Unnecessary complexity of plugins

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#669]
The plugin protocol is a function scope that requests dependencies, which returns an object that has a run() methods that takes 4 args. Those args are the document, the configuration, a callback, and an event emitter. 

This protocol can be greatly reduced to just having each scope return a function that:
- takes a copy of the configuration - but cannot mutate the configuration (I.e., conf should be frozen). 
- takes the document (or virtual doc). 
- returns a promise: the promise resolves with the set of changes to be made to the document (diff), and warnings to the user. It should reject with errors that prevent manipulation of the document or exceptional errors. 

This would allow for concurrent execution of plugins in a composable manner, allowing changes to be made in batches at each turn of the event loop. The same applies to warnings: they can be gathered and shown in one go, instead of depending on a complex pubsubhub system. It would also keep things asynchronous, while greatly reducing complexity and interdependence between plugins. Where plugins do depend on eachother, some kind of queues will be needed (but those should be limited or folded together, as modules should be independent).

**Comment by halindrome** [comment]
Hmm.   I am not sure this is actually *worth* doing.  Respec does not need to be awesomely performant.  Most specs are relatively small, processors are getting faster.  Moreover, the order of processing is actually _important_ in many cases in ReSpec.  

I like fixing things even when they aren't broken, but... we must have some lower hanging fruit than this.

**Comment by marcoscaceres** [comment]
> On 26 Mar 2016, at 6:25 AM, Shane McCarron <notifications@github.com> wrote:
> 
> Hmm. I am not sure this is actually worth doing. Respec does not need to be awesomely performant. Most specs are relatively small, processors are getting faster. Moreover, the order of processing is actually important in many cases in ReSpec.
> 
That's a bug tho.
> I like fixing things even when they aren't broken, but... we must have some lower hanging fruit than this.
> 
Sure. This is v4 basically. 

This is more about maintainability of ReSpec, rather than performance - better performance would be a side effect. Although ReSpec's plugin architecture is mostly ok (just needs a few tweaks), the imperative coding style makes it extremely hard to fix bugs and add features (see any of the more complex modules, like headers or webidl... They are unapproachable spiderwebs, and need to be rewritten).

**Comment by marcoscaceres** [comment]
This is now supported, while retaining backwards compat with the old plugin format. However, new plugins added to the project much adhere to the new format.
