### ISSUE TITLE
Issues that are closed shouldn't show up in the spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#670]
With the GH module, when issues are closed, they still show up in the spec but as empty... they should be removed from the document and from the summary:

![screenshot 2016-03-24 13 45 18](https://cloud.githubusercontent.com/assets/870154/14007004/c41a4000-f1c6-11e5-9286-71733d7bed92.png)

A warning should be generated instead.

**Comment by himanish-star** [comment]
I can fix this maybe.

**Comment by marcoscaceres** [comment]
+ respec@20.0.5
