### ISSUE TITLE
Support JSON-LD as document linked data container

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#671]
Annotating with RDFa is one way to capture semantic data in a document.  Another is to rely upon JSON-LD.  Both are aggressively indexed by the various search and knowledge engines.  Building a JSON-LD context for W3C specs that relies upon some W3C vocabulary terms and then Schema.org for the rest would result in greater uptake.

**Comment by marcoscaceres** [comment]
This seems outside the scope of the project. ReSpec already annotates stuff with json-ld and search engines already find specs easily.
