### ISSUE TITLE
issues-notes.js imports css 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#672]
Issues-notes.js imports CSS as text. This should just be moved into the main style sheet and externalized.

**Comment by marcoscaceres** [comment]
Actually, issues-and-notes' CSS should be retired into the main w3c stylesheet.

**Comment by CodHeK** [comment]
@marcoscaceres can I still work on this, is it just moving the css file ?

**Comment by CodHeK** [comment]
This [https://github.com/w3c/respec/blob/develop/assets/issues-notes.css#L31](https://github.com/w3c/respec/blob/develop/assets/issues-notes.css#L31) looks redundant same as this -> [https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L637](https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L637)

**Comment by marcoscaceres** [comment]
Not, there is also redundancy in the .notes and possibly other things. Any little bit you can remove would really help.

**Comment by CodHeK** [comment]
@marcoscaceres I couldn't find any other redundancy in `issues-notes.css` and `base.css` except the one I mentioned above .

**Comment by CodHeK** [comment]
@marcoscaceres https://github.com/w3c/respec/pull/2070 sent a PR!

**Comment by marcoscaceres** [comment]
closed via #2070
