### ISSUE TITLE
Features at risk that are on github are not linked

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#673]
If a feature is at risk, and it's linked to github, it should not require an `atRiskBase`.

**Comment by saschanaz** [comment]
What should the at-risk issue look like? Currently it's "FEATURE AT RISK 1540" if the GitHub issue number is 1540, but this makes me think there are at least 1540 features at risk 😮

**Comment by marcoscaceres** [comment]
Probably, "FEATURE AT RISK: ISSUE 1540".

**Comment by saschanaz** [comment]
We have the issue titles following, so something like `FEATURE AT RISK (ISSUE 1540): ISSUETITLE` would have more consistent colon position.

**Comment by marcoscaceres** [comment]
Agree. That looks good.
