### ISSUE TITLE
Show labels from github

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#674]
For issues included from github, it might be nice to also include the labels.

**Comment by tripu** [comment]
What do you mean by this, @marcoscaceres?

**Comment by marcoscaceres** [comment]
This is for when people include issues from github into specs:

```
<div class="issue" data-number="123">
</div>
```

The above gets filled with content from github. My idea as to also show any labels associated with the issue.

**Comment by himanish-star** [comment]
I mean to cause no inconvenience to anyone by commenting in a number of issues. But I also have a working solution for this issue too! I will also reference my commit here in a while. But I will wait until I'm done with PRs #1477 and #1473 before filing a PR for this issue :smiley:

**Comment by marcoscaceres** [comment]
@himanish-star, no need for apologies. Please feel free to comment or ask anything. Your help is greatly appreciated. 

Looking really great, @himanish-star!

**Comment by himanish-star** [comment]
Thanks marcos :smiley:

**Comment by tripu** [comment]
@himanish-star, good job!

If I may, :+1: to your suggestion, but :-1: to capitalising all labels automatically (I see that labels in the issues you're using for testing are not all in caps themselves: #1369; #1370). Sometimes labels include CamelCase words, acronyms, etc, and that would be lost when capitalising all. ALSO, CAPS REDUCE READABILITY, imho.

**Comment by marcoscaceres** [comment]
Yeah, might be best to leave the capitalization as is. Well spotted @tripu!

**Comment by himanish-star** [comment]
Sure I'll see to this

**Comment by himanish-star** [comment]
![image](https://user-images.githubusercontent.com/30361728/36306263-06a8aa4e-133d-11e8-8c83-31c69f71a1f2.png)

I have made changes but I have some tests failing so I'm looking into that. @tripu are you happy with the changes

**Comment by tripu** [comment]
@himanish-star, yes, thank you!

(I would suggest perhaps more space between the title of the issue and the set of labels, but we can fine-tune those things once you have a PR ready for review.)

**Comment by himanish-star** [comment]
Yeah I have still one more test failing which I'm trying to correct
