### ISSUE TITLE
There should be a way to limit ToC depth by section

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#675]
Aria APG has a situation where they are ending up with a very cluttered ToC (as reported by @MichielBijl).  They would like to be able to say that, for a given section, the ToC depth should be limited.  I can think of 3 ways to do this:
1. allow maxTocLevel to be an array (this has the disadvantage that adding a new section in the middle would have unintended consequences).
2. allow maxTocLevel to remain as is, and add a maxTocBySection object where there are section IDs mapped to section level max but default to the maxTocLevel (requires that section elements have IDs, but I think that is not a terrible idea anyway)
3. add some special class on section elements that means "children of this section should not be in the ToC".  Maximally flexible, but means more work for authors if what you really wanted was a simple case.

P.S. At the core of this is the silly restriction that headings are expected to be in section elements.  If we were not insisting on that, people could just not use section elements when they didn't want a "section", but instead just wanted a heading within a section.

**Comment by marcoscaceres** [comment]
Why not just use class=no-toc? It should be rare that one nests too deep (or something is probably wrong).

**Comment by halindrome** [comment]
and they are.  it just seems like a lot of work to work around what is arguably a bug in ReSpec.

**Comment by MichielBijl** [comment]
So, in the APG we have this piece of code (simplified):

```HTML
<section id="design-pattern-name">
    <h2>Design pattern title</h2>
    <p>…</p>
    <section>
        <h3>Keyboard interaction</h3>
        <p>…</p>
    </section>
    <section>
        <h3>ARIA states, roles, and properties</h3>
        <p>…</p>
    </section>
    <section>
        <h3>Examples</h3>
        <ul>
            <li>…</li>
        </ul>
    </section>
</section>
```

This repeats itself 37 times because we have 37 design patterns. We don't want the section subheadings in the ToC; that would make the ToC unnecessarily long. Currently, all these subheadings have the `no-toc` class, but it would be much easier (to maintain) if you could set something like `data-max-toc=level-2` on the parent section: `<section id="design-pattern-name" data-max-toc="level-2">`.

**Comment by marcoscaceres** [comment]
@MichielBijl, ah, I see - thanks!

**Comment by marcoscaceres** [comment]
It might be easier to make `data-max-toc-level="2"`, just for parsing. And we could limit it to only top most sections. Then it would be easy to construct at CSS query that automatically adds "no-toc" to the offending headings.
