### ISSUE TITLE
In the current trunk and in the use_nightmarejs branch I get a maximum call stack exceeded error

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#680]
Nothing special in any of the code.  It should just work, but (at least in chrome) it is throwing an error:

[RangeError] Maximum call stack size exceeded

Here is an example URI that I will not touch until you can look at it:  http://dev.spec-ops.io/webpayments-ig/VCTF/use-cases/

**Comment by marcoscaceres** [comment]
That's the fetch bug. I've reverted the fetch stuff from the develop branch. Will send the fetch stuff again in a new PR.
