### ISSUE TITLE
Implement bikeshed's dfn contract

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#685]
The contract is as follows: 

- [X] The defining element MUST be a dfn or h2...h6. No other element is recognized as defining a term.
- [X] The element MUST have an id attribute.
- [x] The linking text defaults to the text content of the dfn/heading. If the desired text content isn’t suitable for linking text, or you wish to provide multiple linking texts, a `lt` attribute` containing one or more pipe-separated linking texts will override the text content. See also §6.3 Defining Extra-Short "Local" Linking Texts

Note: we don't support `local-lt`. We also "dirty" the `data-lt` with various things, like plurals... we might need to deal with that.  

- [x] `data-dfn-type` MUST be provided, and set one of the [accepted values](https://tabatkins.github.io/bikeshed/#dfn-types). (The dfn element, specifically, actually allows this to be omitted, and defaults to the "dfn" type. But headings require a type, and dfns are clearer with it specified.)

Note: it's still unclear what the heading types should be. We need to. look that up. 

- [x] Either `data-export` or `data-noexport` MAY be provided (both boolean attributes). If neither is provided, "dfn" type definitions default to noexport, while all others default to export. Unexported definitions aren’t linkable by default.

- [x] Several types of definitions are namespaced to another construct; for example, attribute names are namespaced to an interface. These definitions MUST contain a data-dfn-for attribute, containing a comma-separated list of one or more definitions they’re namespaced to.

Note:  we. can support for on IDL definitions easily enough. We need to support them for internal slots too, and possibly other other things. However, we generally don't want to export internal slots, because they are private.

**Comment by halindrome** [comment]
FWIW I have this implemented for ReSpec.  The namespacing etc. works well.
But it would be nice to be able to share the definitions among documents /
document segments and have the links resolve into companion documents as
well.

On Wed, Apr 6, 2016 at 12:48 AM, Marcos Caceres <notifications@github.com>
wrote:

> https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/685>
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
That's awesome to hear. Can you put up a branch? Would like to take a looksy.

**Comment by halindrome** [comment]
Yeah.... I actually think it IS in a branch. I can't find it but I will keep looking.

**Comment by saschanaz** [comment]
@marcoscaceres The link is broken, do you recall what this is?

**Comment by sidvishnoi** [comment]
@saschanaz This maybe?
https://github.com/tabatkins/bikeshed/blob/10ff3eb4050069e20bb9b943c8b76fe5bfe3a48f/docs/index.bs#L2229

**Comment by marcoscaceres** [comment]
Yep, that one.

**Comment by saschanaz** [comment]
That again maps to: https://tabatkins.github.io/bikeshed/#dfn-contract

Thanks!

**Comment by saschanaz** [comment]
>If the desired text content isn’t suitable for linking text, or you wish to provide multiple linking texts, a lt attribute containing one or more pipe-separated linking texts will override the text content.

We use `data-lt` and this item requires we use `lt` instead. Fixing Shepherd instead to support `data-lt` looks more reasonable here... (Or does Shepherd already support it?)

**Comment by sidvishnoi** [comment]
@saschanaz Shepherd uses `data-lt` only. `lt` is probably Bikeshed's shorthand.
http://hg.csswg.org/dev/specification/file/821238a37a22/python/specification/specificationparser.py#l516

**Comment by saschanaz** [comment]
That's good. What are the missing features here?

**Comment by marcoscaceres** [comment]
We need to decide if we should automatically add “no-export” to non-IDL definitions, and export IDL things (along with data-* things that might be needed). 

There are other subtle things we should do, like allowing IDL things to be “self defining” (in the IDL itself) instead of requiring things to be defined separately.

**Comment by marcoscaceres** [comment]
To be clear, Editors should explicitly have to either export things or explicitly not export things. I think BikeShed defaults to exporting by default.

**Comment by saschanaz** [comment]
Adding `data-export` for IDL things sounds easy enough.

**Comment by marcoscaceres** [comment]
Ok, I've updated OP with the actual contract that we need to conform to. The IDL ones are definitely the easiest ones.

**Comment by marcoscaceres** [comment]
Ok, I think we are good with implementing the contract with respect to IDL. I've documented that we support the same values as bikeshed for data-dfn-type. The next release of ReSpec supports  better exports of IDL operations too.
