### ISSUE TITLE
Error: Cannot read property 'for_' of undefined

### ISSUE THREAD

**Issue by riannella** [w3c/respec#689]
I get the following error:
======
[TypeError] Cannot read property 'for_' of undefined ⊟
TypeError: Cannot read property 'for_' of undefined
    at HTMLAnchorElement.<anonymous> (https://www.w3.org/Tools/respec/respec-w3c-common:18:6493)
    at Function.ae.extend.each (https://www.w3.org/Tools/respec/respec-w3c-common:8:482)
    at ae.fn.ae.each (https://www.w3.org/Tools/respec/respec-w3c-common:7:30459)
    at Object.run (https://www.w3.org/Tools/respec/respec-w3c-common:18:5875)
    at https://www.w3.org/Tools/respec/respec-w3c-common:10:17586
    at https://www.w3.org/Tools/respec/respec-w3c-common:10:17548
======

**Comment by marcoscaceres** [comment]
Do you have a link to your spec itself? Unfortunately, the error below comes from the minified code so it's not possible for me to debug.

**Comment by riannella** [comment]
Yes, here:
https://github.com/w3c/poe/blob/model/model/WD-index-respec.html

**Comment by marcoscaceres** [comment]
@riannella thanks! (and hi! long time :smile:!)

Confirmed error... 
```JS
TypeError: undefined is not an object (evaluating 'linkTargets[0].for_') — link-to-dfn.js:75
```

Trying to find what is causing it in the doc itself.

**Comment by marcoscaceres** [comment]
@riannella, you have some markup in your document that is causing the issue:
```HTML
<h4><a name="section-231"></a>2.3.1 Role</h4> 
```

That should be:
```
<section>
<h4>Role</h4>
 ...
</section>
```

That will allow ReSpec to auto id that section and number it for you. 

ReSpec should warn about `<a name></a>` being a deprecated way of linking in a document as part of #20 .

**Comment by marcoscaceres** [comment]
@riannella, there is also one more. Search for: 
```HTML
<h3><a name="section-22"></a>2.2 Asset</h3>
```

**Comment by marcoscaceres** [comment]
@riannella, I would also recommend running [HTML5 Tidy](https://github.com/htacg/tidy-html5) over your document. It will take care of the nesting for you wrt to `<section>`s, making it easier to spot issues. Plus it's also good for when people send you PRs on github. Keeps code clean, etc.

**Comment by riannella** [comment]
> On 13 Apr 2016, at 13:36, Marcos Caceres <notifications@github.com> wrote:
> 
> @riannella <https://github.com/riannella>, I would also recommend running HTML5 Tidy <https://github.com/htacg/tidy-html5> over your document. It will take care of the nesting for you wrt to <section>s, making it easier to spot issues. Plus it's also good for when people send you PRs on github. Keeps code clean, etc. 
> 

Thanks Marcos !!

Renato
