### ISSUE TITLE
decouple specStatus from license

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#696]
It should be possible to override the license.

**Comment by wetneb** [comment]
At the moment it seems that for an unofficial draft, whatever license I add in the config, respec will always display "This document is licensed under a Creative Commons Attribution 4.0 License."

Another license can be added for unofficial drafts using `additionalCopyrightHolders` but that is pretty counter-intuitive: as a user, I expect the `license` field to be used to generate this text, regardless of the status of the document. For instance, the license is currently exported in JSON-LD using the `license` field directly: this should also be done for this text.

If some licenses are incompatible with some document status, then a warning can be generated.

**Comment by marcoscaceres** [comment]
We should use the same as NPM's package.json... and the same identifiers. We can get the same list from OSI or whomever it is that publishes it.

**Comment by marcoscaceres** [comment]
I did a little investigating, and unfortunately it's not possible to use SPDX because it's missing too much critical information. 

However, it's now possible to simply override the copyright by including a `<p class="copyright">` at the top of the document. ReSpec then moves the paragraph to the right place.
