### ISSUE TITLE
Link [CEReactions], and maybe other IDL extended attributes, to their definition

### ISSUE THREAD

**Issue by domenic** [w3c/respec#702]
In https://github.com/w3c/webcomponents/issues/186#issuecomment-211631287 I am adding the [CEReactions] extended attribute (defined at https://html.spec.whatwg.org/multipage/scripting.html#cereactions) to many different specs, many of which use ReSpec. It would be great if it linked to its definition. Optionally, other extended attributes should also link to their definitions in Web IDL.

Counterpart Bikeshed issue: https://github.com/tabatkins/bikeshed/issues/677

**Comment by marcoscaceres** [comment]
Will take a look and try to match whatever bikeshed ends up using.

**Comment by marcoscaceres** [comment]
Closed via #1098

**Comment by marcoscaceres** [comment]
I'm now linking to both extended attributes and known/standard IDL types. 

@domenic, if new extended attributes are added to HTML, could you kindly please let me know? Sadly lacking the bandwidth to track changes in HTML.
