### ISSUE TITLE
respec2html should error if not a ReSpec document

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#704]
@tripu suggested we make respec2html stop if ReSpec is not found.... which... makes complete sense. Right now, it just times out leaving the end user feeling empty.

**Comment by dontcallmedom** [comment]
ideally, this happens at the level of respecDocWriter (so that we can also error in the spec-generator)

**Comment by marcoscaceres** [comment]
Yep. It's hard to test tho... because ReSpec rips itself out after it runs leaving few reliable traces. Let's see what I can find that we can use.

**Comment by marcoscaceres** [comment]
So, this might work:
js/w3c/aria.js:                $('body', doc).attr('id', 'respecDocument') ;

Aria.js adds respecDocument to body.
