### ISSUE TITLE
Improvements to respecDocWriter

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#706]
While updating the spec generator to use respecDocWriter, I noted the following issues:
* it doesn't seem to fail gracefully (i.e. with a promise rejection) when it fails to download the url (I got on a 404 URL: "Unhandled error in async function. [Error: .wait() timed out after 30000msec]")
* when out is null, it prints out the generated HTML on stdout; at least in my case, I only need it as a returned value, not on stdout

**Comment by marcoscaceres** [comment]
Will fix the first one

> when out is null, it prints out the generated HTML on stdout; at least in my case, I only need it as a returned value, not on stdout

Just "/dev/null" the out.

**Comment by dontcallmedom** [comment]
re /dev/null/ that's what I do, but it's a waste of resource to ask node to open a file for nothing

**Comment by marcoscaceres** [comment]
> re /dev/null/ that's what I do, but it's a waste of resource to ask node to open a file for nothing

Yeah, agree. It's not the best. I'll special case the empty string as an alternative.
