### ISSUE TITLE
Markdown formatter breaks <pre> blocks by stripping whitespace

### ISSUE THREAD

**Issue by igrigorik** [w3c/respec#724]
Steps to reproduce...

```html
<script class='remove'>
  var respecConfig = {
   ...
    format: "markdown",
   ...
}
</script>

<section>
<pre class='example highlight'>
     Thing
         Where space 
     Matters
</pre>
</section>
```

This behavior breaks code samples in specs. Looking at the code, seems like culprit is [this function](https://github.com/w3c/respec/blob/fa28f640a33bb7de223e5350c49113f17c1e8b50/js/core/markdown.js#L141), which is being applied indiscriminately. 

Real world (broken) example: https://w3c.github.io/requestidlecallback/ - see the code examples in readme.

/cc @marcoscaceres

**Comment by marcoscaceres** [comment]
Getting close to fishing this... at least @igrigorik spec is ok. However, it caused a few other issues in some other specs. Hope to fix tomorrow.  

![screenshot 2016-05-02 18 55 12](https://cloud.githubusercontent.com/assets/870154/14950744/7bf03f10-1097-11e6-8dab-0de346dd2b94.png)

**Comment by marcoscaceres** [comment]
*finishing

**Comment by igrigorik** [comment]
\o/ ... thanks Marcos!

**Comment by marcoscaceres** [comment]
pr sent for review...

**Comment by marcoscaceres** [comment]
@igrigorik just waiting for the W3C to pick up the release.

**Comment by igrigorik** [comment]
Awesome, thanks Marcos!
