### ISSUE TITLE
Error in ontolex spec 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#726]
@fsasaki reported an issue occurring in:  
http://www.w3.org/2016/04/ontolex/

Will investigate.

**Comment by marcoscaceres** [comment]
@fsasaki, it seems you are adding JQuery 1.4, which will trash or conflict with JQuery that is included with ReSpec (2.x). That may be causing the problem.

**Comment by fsasaki** [comment]
That was the issue, thanks!

**Comment by marcoscaceres** [comment]
@fsasaki there are a bunch of other issues in that spec (e.g., loading http resources over TLS, etc). Is there a repo for your spec? 

You can try to update your copy with this:
https://gist.github.com/marcoscaceres/e6fcaedcd0e1981d09a00879083dbd40

I updated the fancybox script files.

**Comment by fsasaki** [comment]
Thanks, Marocs. I have forked the original repro, see my fork here
https://github.com/fsasaki/ontolex/blob/master/specification.html
I have updated my fork with your copy. If you see other issues can you let
me know in my fork?

Thanks,

Felix

2016-04-29 7:21 GMT+02:00 Marcos Cáceres <notifications@github.com>:

**Comment by marcoscaceres** [comment]
@fsasaki, will do.

**Comment by fsasaki** [comment]
With 
http://www.w3.org/2016/04/ontolex/
in Safari (Version 8.0.6 (10600.6.3))  I get the following error and the respec style does not display - any idea what the reason may be?

> [Error]
 TypeError: undefined is not a function (evaluating 'Array.from(arguments)')
	(anonyme Funktion) (respec-w3c-common, line 19)
	execCb (respec-w3c-common, line 7)
	check (respec-w3c-common, line 7)
	enable (respec-w3c-common, line 7)
	enable (respec-w3c-common, line 7)
	(anonyme Funktion) (respec-w3c-common, line 7)
	(anonyme Funktion) (respec-w3c-common, line 7)
	each (respec-w3c-common, line 7)
	enable (respec-w3c-common, line 7)
	init (respec-w3c-common, line 7)
	(anonyme Funktion) (respec-w3c-common, line 7)

**Comment by marcoscaceres** [comment]
For generation of documents, we only have resources to support current generation browsers. Can I kindly ask that you update to 9.1. It's been almost exactly a year since 8.0.6 was released.

**Comment by fsasaki** [comment]
Thanks for the info - sure, will do.

- Felix

2016-04-29 16:58 GMT+02:00 Marcos Cáceres <notifications@github.com>:
