### ISSUE TITLE
Add highlight.js support for markdown

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#745]
When using markdown, it'd be nice to not have to wrap things in a `<pre>` tag to get highlight support. So you can just use back-ticks and specify the language.

**Comment by halindrome** [comment]
I am confused.  I thought ReSpec used google-code-prettify.js.  That's what is in the js directory in the tree.

**Comment by marcoscaceres** [comment]
Yes, you are correct - sorry about the confusion: the one was not on npm and was not as supported as hljs, so I swapped it. This one works the same, but allows for updates, etc.

**Comment by halindrome** [comment]
Sorry - what is "this one" in this context?

**Comment by marcoscaceres** [comment]
Highlight.js === this one.
