### ISSUE TITLE
Support for https in /TR

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#749]
From the [proposal](https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html):

- [x] link to TR stylesheets
- [x] links to W3C logo and W3C main homepage
- [x] ALL document identifiers ("This Version", "Latest Version", "Previous
Version", etc.)
- [x] links to W3C IPR notice, liability, trademark, and document use
- [x] link to the W3C technical reports index
- [x] links to W3C Patent Policy, patent disclosures, and W3C Process
- [x] link to fixup.js and other supported scripts
- [x] links to errata page and translation
- [x] links to ReSpec guide

**Comment by marcoscaceres** [comment]
I'll double check, but I think we completely default to TLS throughout.

**Comment by marcoscaceres** [comment]
Sent a PR with fixes for HTTP URLs.
