### ISSUE TITLE
Ugly output 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#750]
The output from ReSpec is pretty gross. 

It would be nice if it was beautiful. 

![screenshot 2016-05-11 22 15 56](https://cloud.githubusercontent.com/assets/870154/15180640/317454a4-17c6-11e6-9f41-ed8b0d1b6578.png)

**Comment by halindrome** [comment]
This feels a little subjective.  What did you have in mind?

**Comment by marcoscaceres** [comment]
> On 12 May 2016, at 12:30 AM, Shane McCarron <notifications@github.com> wrote:
> 
> This feels a little subjective. What did you have in mind?
> 

Running the code through a beautifier on save. I'm currently testing this: https://github.com/beautify-web/js-beautify

As I need to use it for the markdown code. It basically just fixes white space without changing the markup. You can try it here:

http://jsbeautifier.org
