### ISSUE TITLE
WebIDL needs to support FrozenArray

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#752]
I could really use support for this in several specs...

http://heycam.github.io/webidl/#idl-frozen-array

webidl2.js does not grok it yet, but if it did...  @darobin ?

**Comment by halindrome** [comment]
I am an idiot.   It works just fine.  Never mind....

**Comment by marcoscaceres** [comment]
Oh, if you have a test we could quickly add, that would be great. 

I should check if there are other fancy things in webidl that are not supported by webidl2.js.
