### ISSUE TITLE
Limit number of tests run in parallel

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#754]
It would be nice if it were possible to limit this.  When the tests start up a bunch of browsers at the same time it can run smaller machines out of memory pretty quickly!

**Comment by halindrome** [comment]
Or maybe what is happening is that the tests are not properly cleaning up when they are done and leaving old user agent processes around?

**Comment by halindrome** [comment]
A little more data on this....  running the test collection against Chrome took just under 2 minutes on this server.  Firefox took just under 20 minutes.

**Comment by marcoscaceres** [comment]
Yeah, Firefox's JIT is 💩. I filed a bug about Firefox being orders of magnitude slower than other browsers a few weeks ago. Unfortunately, it's not our code/tests that is the problem. For example, Safari runs the tests in under 20 seconds.

**Comment by marcoscaceres** [comment]
Here is the Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1265980
