### ISSUE TITLE
"Back to Top" target link

### ISSUE THREAD

**Issue by newtoncalegari** [w3c/respec#771]
The "Back to Top" link located at the end of the document is very useful, but it doesn't work properly when the ToC is fixed on the sidebar.
When the sidebar is hidden and the ToC is on the top of the document, the "Back to Top" link works fine, because it links to the "#toc" and consequently jumps to the top of the document.

So, I suggest to change the target to the title of the document, this way it will always send to the top, even when sidebar is active.

cheers,

**Comment by marcoscaceres** [comment]
@newtoncalegari, I think that's a bug in the TR-Design project, so I've filed it there for you:
https://github.com/w3c/tr-design/issues/99

**Comment by newtoncalegari** [comment]
Thanks @marcoscaceres ;-)
