### ISSUE TITLE
Replace jQuery for slim

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#773]
As part of #385, it was proposed we look at using a minimal version of jquery. An good alternative is:

https://github.com/kenwheeler/cash/

In theory, it should work fine as a drop in replacement.

**Comment by marcoscaceres** [comment]
So looks like we need to get rid of a few .fade() calls and replace them with CSS transitions

**Comment by halindrome** [comment]
I am concerned that we are unaware of how jquery is relied upon by other people who extend respec.  I know that a lot of specs make extensions...  is there some pressing reason to not just include all of jquery?

**Comment by marcoscaceres** [comment]
Yeah, good point: but it seems unlikely that they use the animation features (cash has everything else). The motivation is mostly the amount of bloat and jquery black magic which makes it frustrating to work with and debug. There is not much reason for jquery to be used in ReSpec: the browser can do everything the jQuery does nowadays and often better.

**Comment by halindrome** [comment]
Okay - good to know.  The most interesting extensions that I have seen are the epub generation stuff (which is built in now of course) and the UI extension we did in ARIA to allow for saving of some state information as JSON.  And yes, none of those are doing animation.

**Comment by marcoscaceres** [comment]
This has shipped.
