### ISSUE TITLE
no more html highlighting?

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#776]
Trying to follow
 https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0052.html

Compare
  https://www.w3.org/TR/resource-hints/#preconnect
with
  https://w3c.github.io/resource-hints/#preconnect

we lost syntax highlighting on html. Tried with or without highlight class and it didn't make a difference.

**Comment by marcoscaceres** [comment]
Will be fixed by: https://github.com/w3c/respec/pull/767

**Comment by marcoscaceres** [comment]
I've double checked. It's indeed fixed by the update. Soon to be released.
