### ISSUE TITLE
Deactivating hyperlinking in examples

### ISSUE THREAD

**Issue by plehegar** [w3c/respec#777]
Compare
 https://www.w3.org/TR/resource-hints/#fetching-the-resource-hint-link
with
 https://w3c.github.io/resource-hints/#fetching-the-resource-hint-link

It seems that the new highlighter is attempted to be too smart for its own good.

The hyperlink is https://example.com/next-page.html%3E
and really, we should link to example.com in the first place. Is there a way to disable this?

**Comment by marcoscaceres** [comment]
I'll see how we can turn it off. I think it's the markdown parser (might be doing the right thing, but we should be able to disable it).

**Comment by plehegar** [comment]
fyi, this blocked the TR update of resource hints yesterday. this would be worth adding into the testbed.

**Comment by marcoscaceres** [comment]
@plehegar, this is a "feature" of markdown it seems (https://gist.github.com/alexpeattie/4729247). It can be disabled with a few hacks (e.g., the `http:<span></span>//some.url` one).

**Comment by marcoscaceres** [comment]
A solution might be to add a nolink class. I can then convert HTMLAnchors to text nodes.

**Comment by marcoscaceres** [comment]
PR sent.

**Comment by plehegar** [comment]
LGTM.

**Comment by marcoscaceres** [comment]
Thanks! Something is tripping up one of the tests. Looking into it.
