### ISSUE TITLE
dfn + code chops off space

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#783]
This code:
```HTML
For clarity, a <dfn>megabit</dfn> is 1,000,000 bits, and 
<dfn data-lt="Mbit/s">megabits per second</dfn> is equivalent to transferring:
```
Turns into: 
![screenshot 2016-05-24 17 30 52](https://cloud.githubusercontent.com/assets/870154/15495774/67216830-21d5-11e6-8232-01f076ea754b.png)

Which is missing the space between "megabits" and "is".

**Comment by marcoscaceres** [comment]
Also happening with following markdown:

```md
  1. <a>Fire a simple event</a> named `change` at the `NetworkInformation` object.
```

**Comment by halindrome** [comment]
Interesting - is this happening ONLY in markdown?

**Comment by marcoscaceres** [comment]
I think so. See http://wicg.github.io/netinfo/

**Comment by igrigorik** [comment]
This may belong in a separate bug, but I'm seeing extra spaces too.. 

e.g. from: http://igrigorik.github.io/feature-policy/
![image](https://cloud.githubusercontent.com/assets/10652/15522852/2354c1ca-21ca-11e6-8079-33bef968e18b.png)

Note the extra space after the first quote.

**Comment by marcoscaceres** [comment]
@igrigorik, fixed the other issues locally... PR incoming. Looking into the extra space issues now.

**Comment by marcoscaceres** [comment]
@igrigorik, it appears to be a bug in the beautifier we are using, I [filed a bug on them](https://github.com/beautify-web/js-beautify/issues/943). Will try to see if I can work around it.

**Comment by marcoscaceres** [comment]
@halindrome I sent a PR, could you kindly review? (or @igrigorik, if you are feeling up to it, ptal)

If it's ok, I'll get this out ASAP.

**Comment by marcoscaceres** [comment]
@dontcallmedom jumped in and did the review! He is a hero 🏆 .

**Comment by igrigorik** [comment]
\o/
