### ISSUE TITLE
Space appearing when quote is followed by element.

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#786]
A [bug in jsbeautifier](https://github.com/beautify-web/js-beautify/issues/943) is affecting ReSpec.

Given HTML:

```HTML 
<p>If the document&#39;s origin is an opaque origin, throw a
&quot;<code>SecurityError</code>&quot; <code>DOMException</code>.</p>
```

jsbeautifier produces:

```HTML
<p>If the document&#39;s origin is an opaque origin, throw a &quot;
    <code>SecurityError</code>&quot; <code>DOMException</code>.</p>
```

Which results in a space between the quote and SecurityError, like: <samp> " <code>SecurityError</code>"
 
Expected: "<code>SecurityError</code>" with no spaces.

**Comment by marcoscaceres** [comment]
Seems it is still happening :( @igrigorik, looking into it some more.

**Comment by marcoscaceres** [comment]
@igrigorik, should be all good now. Please let me know if anything else comes up.

**Comment by dontcallmedom** [comment]
Unfortunately, it seems to problem occurs with other punctuation signs; in particular, it adds an extra space after the opening parenthesis of the copyright holders list, making document not-pubrules compliant.

See https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/webrtc-stats/webrtc-stats.html%3FspecStatus=WD;shortName=webrtc-stats for instance.

**Comment by igrigorik** [comment]
@marcoscaceres thank you! Will report if I come across anything else.
