### ISSUE TITLE
Inserted stylesheets move charset declaration too far down

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#791]
With the stylesheets being inserted at the start of the head element (including the new highlighter stylesheet), the `<meta charset>` declaration gets pushed beyond the first 1024 bytes of the document, which makes the HTML5 validator complains.

Ideally, the stylesheet would be inserted after the meta charset.

**Comment by marcoscaceres** [comment]
Yeah, spotted that today. So it needs to be moved up after processing is done (so exported docs have it in the right place). Same with meta viewport.

**Comment by dontcallmedom** [comment]
hmm… still doesn't seem to work

**Comment by marcoscaceres** [comment]
odd... let me try...

**Comment by marcoscaceres** [comment]
@dontcallmedom, what spec? I just tried a few and it's fine? 

![screenshot 2016-05-27 17 37 38](https://cloud.githubusercontent.com/assets/870154/15601305/f097ed56-2431-11e6-95ee-287b7a7b3e8d.png)

**Comment by marcoscaceres** [comment]
@dontcallmedom, note: the fix only happens when you save. Not to source documents: there it doesn't matter, because the HTML parser will have seen the meta element by the time ReSpec runs.

**Comment by marcoscaceres** [comment]
Fixed grammar above... I might be having Friday 🍻 while bug fixing 👍

**Comment by dontcallmedom** [comment]
I had tried saving webrtc-stats to no avail https://w3c.github.io/webrtc-stats/webrtc-stats.html (see also https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/webrtc-stats/webrtc-stats.html%3FspecStatus=WD;shortName=webrtc-stats )

**Comment by dontcallmedom** [comment]
doh, it is there now... Probably some funky caching :(

**Comment by marcoscaceres** [comment]
Funky 💃

**Comment by dontcallmedom** [comment]
The problem has re-appeared apparently

**Comment by marcoscaceres** [comment]
Odd. Should bisect what's happened here.
