### ISSUE TITLE
Change to publish / subscribe has broken ARIA and related specs

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#793]
The ARIA specs use messages to decide when to do certain operations.  Whatever changed recently with this has broken their integration and now the specs are not working at all.  ReSpec puts the following into the console: 

```window.respecEvents() is deprecated. Use 'require("core\pubsubhub", aFunction)' instead.```

Sadly, I am sure no one except @marcoscaceres will know what that means.  I want to help them out but I am not sure what direction to point.

I will look at the documentation, but I expect that has not been updated to reflect this change yet.

**Comment by marcoscaceres** [comment]
Should be easy to fix, whatever it is. But the above message is indeed incorrect. Note that it's a deprecation warning, which means it should still be working. Can you put a link to the affected specs here?

**Comment by halindrome** [comment]
there are lots.  Try https://github.com/w3c/aria

The basic problem is twofold.  async lazy loading means respecEvents is not available early and the extension scripts assume that it is.  See common/script/resolveReferences.js or aria/scripts/aria.js

**Comment by halindrome** [comment]
FYI I have added require calls to resolveReferences.js to try to sort this out, and it appears that only one subscribed message is getting delivered.  It subscribes to 'end' and then teases out which 'end' it wants.  but it only gets called once.

**Comment by halindrome** [comment]
Oh lord.  @marcoscaceres did you take out all of the start and end messages?  How are extensions supposed to hook in when modules complete if we don't have start and end messages?

**Comment by marcoscaceres** [comment]
@halindrome can't you use end-all for resolveReferences.js?

**Comment by marcoscaceres** [comment]
same with aria.js. Interjecting in the middle of core processing does not strike me as great idea.

**Comment by halindrome** [comment]
Sometimes it is necessary.  resolveReferences might be able to use end-all.  aria.js cannot.  I will try resolveReferences out.

**Comment by halindrome** [comment]
To be clear, aria.js (and ariaClient.js) cannot because they create content that refers to definitions and other specs and that content will be further marked up by the subsequent parts of ReSpec.
