### ISSUE TITLE
Syntax highlighting issue for interfaces with a "Constructor"

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#806]
See: https://w3c.github.io/presentation-api/#idl-def-presentationrequest
(tested in Edge, Firefox and Chrome)

Source is:

```
<pre class="idl">
  [Constructor(DOMString url)]
  interface PresentationRequest : EventTarget {
    Promise&lt;PresentationConnection&gt; start();
    Promise&lt;PresentationConnection&gt; reconnect(DOMString presentationId);
    Promise&lt;PresentationAvailability&gt; getAvailability();

    attribute EventHandler onconnectionavailable;
  };
</pre>
```

The methods render in grey. Looking at the markup, it seems everything gets wrapped in `<span class="hljs-comment">...</span>` tags.

Dropping the constructor as below solves the highlighting issue:
```
<pre class="idl">
  interface PresentationRequest : EventTarget {
    Promise&lt;PresentationConnection&gt; start();
    Promise&lt;PresentationConnection&gt; reconnect(DOMString presentationId);
    Promise&lt;PresentationAvailability&gt; getAvailability();

    attribute EventHandler onconnectionavailable;
  };
</pre>
```

**Comment by tidoust** [comment]
Additional note that the presence of a Constructor does not seem to be enough to trigger the problem. The "length" of the interface definition also seems to play a role.

For instance, the following interface definition is correctly highlighted:

```
<pre class="idl">
  [Constructor]
  interface Dahut : Mammal {
    const unsigned short LEVROGYROUS = 0;
    const unsigned short DEXTROGYROUS = 1;
    Dahut turnAround(float angle, boolean fall);
    unsigned long trip();
  };
</pre>
```

However, dropping any of the four property lines from the above definition makes the whole interface turn grey, e.g.:

```
<pre class="idl">
  [Constructor]
  interface Dahut : Mammal {
    const unsigned short DEXTROGYROUS = 1;
    Dahut turnAround(float angle, boolean fall);
    unsigned long trip();
  };
</pre>
```

I suspect the problem occurs in highlight.js

**Comment by marcoscaceres** [comment]
Yeah, I think I forgot to filter out idl files when applying the highlighting.

**Comment by marcoscaceres** [comment]
I mean: filter out pre elements that have an idl class value. PR on its way!
