### ISSUE TITLE
Deprecate diffTool

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#808]
We should consider deprecating `diffTool`, as the default one doesn't support HTTPS + I can't see anyone using anything but the default one: 
https://github.com/search?p=1&q=org%3Aw3c+diffTool&type=Code

It's also not very helpful when compared to just looking at git's history or commits on github.

**Comment by halindrome** [comment]
It is used for producing diff-marked versions of specs for publication.  I will add a certificate to the default server right now.  Note: it is also available at the W3C - presumably on a secured server already.
