### ISSUE TITLE
Deprecate ED status and edDraftURI

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#809]
We should start encouraging editors to stop publishing Editor's drafts and move to autopublishing with Echidna. There is no valid reason to publish editors drafts anymore, so we should help people transition.

**Comment by halindrome** [comment]
Actually, most of the groups I am in find the constant publication via
echidna annoying.  Editors drafts should (and are) the status of documents
in their raw, churning form.  Periodically those drafts are declared stable
and pushed for review.  I appreciate there are groups that do not work that
way, but many many do.   Working that way in combination with the diff tool
makes it easier for people to review the drafts from time to time, looking
at what has changed.

I would oppose making ED status deprecated.  On the other hand, I would be
happy to help make it easier to use Echidna for the groups that do.  Are
there changes needed to do that?

On Tue, Jun 7, 2016 at 12:59 AM, Marcos Cáceres <notifications@github.com>
wrote:

> We should start encouraging editors to stop publishing Editor's drafts and
> move to autopublishing with Echidna. There is no valid reason to publish
> editors drafts anymore, so we should help people transition.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/respec/issues/809>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAfx8KhbWkPWegb6erUfM3p_tYlau_T1ks5qJQjLgaJpZM4Ivle2>
> .
>



-- 
Shane McCarron
halindrome@gmail.com
