### ISSUE TITLE
Process a clone document instead of the real DOM

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#818]
Elsewhere, Matt King proposed: 

> I am wondering if there is a better way for respect to work. Is there a way to make all the 
> respec changes without doing it on the live DOM and then replace the entire DOM or something 
> like that. Content hidden with display none is left out of the AX tree, so maybe the whole 
> DOM could be hidden while the processing is occurring ... maybe not great for everyone, 
> but at least you would all have an experience that is more like mine .

**Comment by marcoscaceres** [comment]
WIP patch: 
https://github.com/w3c/respec/commit/323aa76b106f9c49cbafee3570bf73eb6f6adee4

 * tells the AT that we aria-busy.
 * does ReSpec processing on cloned document.
 * replaces the old doc element with the new doc element
 * tells the AT that we are no longer busy... but it's a different node... so I don't know if the AT smart enough to know what is going on.  

@stevefaulkner and @patrickhlauke, would ❤️ to work with you on this.

**Comment by marcoscaceres** [comment]
A bit more context:
https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0101.html

**Comment by patrickhlauke** [comment]
Will review, but quickfire question: will this (swapping the DOM) completely break links to fragment identifiers (which is already borked currently in Chrome)?

**Comment by marcoscaceres** [comment]
@patrickhlauke, not if we do it right. I need to get people off the stupid asycn event crap that is currently used by respec, which is causing that problem.

**Comment by marcoscaceres** [comment]
To be clear, the trick to getting the fragment navigation to work is to do all the processing before first paint. Right now, there is a Promise.resolve() call that is spinning the event loop and causing a paint to happen (the FOUC you currently see). That then confuses the browser, because it has time to try to navigate while ReSpec is changing the DOM.

**Comment by halindrome** [comment]
Huh... I always wondered why that happened.  The event loop isn't really async though... it is synchronous...  

The ARIA group came up with an extension that solves the fragment ID issue, btw.  Might be a gross hack, but they do:

<pre>
// Fix the scroll-to-fragID problem:
require(["core/pubsubhub"], function (respecEvents) {
    "use strict";
    respecEvents.sub("end-all", function () {
        if(window.location.hash) {
            window.location = window.location.hash;
        }
    });
});
</pre>

**Comment by marcoscaceres** [comment]
> On 9 Jun 2016, at 11:18 PM, Shane McCarron <notifications@github.com> wrote:
> 
> Huh... I always wondered why that happened. The event loop isn't really async though... it is synchronous...
> 

Promise.resolve().then() causes the event loop to spin. It was added to allow other scripts to hook into the message queue. 

> The ARIA group came up with an extension that solves the fragment ID issue, btw. Might be a gross hack, but they do:
> 
> // Fix the scroll-to-fragID problem:
> require(["core/pubsubhub"], function (respecEvents) {
>     "use strict";
>     respecEvents.sub("end-all", function () {
>         if(window.location.hash) {
>             window.location = window.location.hash;
>         }
>     });
> });

That seems ok. There is probably a few options and checks we can do there.

**Comment by halindrome** [comment]
@marcoscaceres what if we didn't use Promises in the processing loop?  I mean - leave the surrounding promise that you created, but within the loop just do synchronous processing.  Module 1, then module 2, then module 3.   It presumes that any message consumers are also synchronous... or that they are going to spawn something off that can be done asynchronously.  Or is that anathema these days?

**Comment by marcoscaceres** [comment]
>  or that they are going to spawn something off that can be done asynchronously. Or is that anathema these days?

Right now, only Biblio does async work... as it talks to specref.

**Comment by marcoscaceres** [comment]
> @marcoscaceres what if we didn't use Promises in the processing loop? I mean - leave the surrounding promise that you created, but within the loop just do synchronous processing. Module 1, then module 2, then module 3. It presumes that any message consumers are also synchronous... or that they are going to spawn something off that can be done asynchronously. Or is that anathema these days?

To be clear, the above is more or less how it works today with a few exceptions. Basically, anything that is sync, runs sync... anything that is not, doesn't. This is why I proposed elsewhere to basically remove the `{run: function(){}}` stuff, and just return a function.... which can return a promise. Anyway, I don't want to get bogged down in all that now. We will be able to clean a lot of this up when Safari 10 ships, as we will then have universal ES6 support in all browsers, making all this stuff much easier to reason about.   

The heart of the problem is gathering all the changes into some data structure that prevents all the DOM thrashing. Right now, we mutate the Document itself without any cares... which is not great. Ideally, we want to only change document fragments, then gather those fragments and insert them when we are done (or when actually required... see my recent changes to w3c/styles, for example).... it's a hard problem that I think needs to be solved incrementally.

**Comment by marcoscaceres** [comment]
(cheap solution is still to just do what  Matt King suggested... display: none until end-all)

**Comment by patrickhlauke** [comment]
Still happy to help review/test whatever you have so far, if you can point me to a live working example (since I didn't have much luck building it from scratch on my Windows environment)

**Comment by jsoref** [comment]
@marcoscaceres : have things improved?

**Comment by marcoscaceres** [comment]
No, but things are not that bad either. I'm waiting for Edge 14 to be released, which will then give us more sane API surface to deal with all these issues.

**Comment by jsoref** [comment]
I'm using Edge 38 w/ EdgeHTML 14 today...

**Comment by marcoscaceres** [comment]
@jsoref,  I didn't know 14 was released? Are you using the Windows Insider thing?

**Comment by jsoref** [comment]
My insider computer is running Edge 39 w/ EdgeHTML 14 ...

**Comment by marcoscaceres** [comment]
We will continue to do this incrementally (batched changes), but I don’t think we can do this in one go.
