### ISSUE TITLE
Releasing to another branch

### ISSUE THREAD

**Issue by nickevansuk** [w3c/respec#820]
Hi Marcos,

Since our last correspondence I haven't had much time to do pull requests (though I see you've implemented some of the same features, which is great!). There's one thing that would really help me out and make contribution easier (I suspect for others too)...

Could we change the release process so that it publishes the /build/ stuff to a different branch instead of develop?

At the moment I release to our openactive/respec repo (a fork which our own specs use), and then currently need to reconcile the two. A separate build branch would make it much easier to keep develop in sync.

Let me know what you think.

Thanks,

Nick

**Comment by marcoscaceres** [comment]
I agree: we should only have builds in the gh-pages branch and not in the "develop" branch.

**Comment by nickevansuk** [comment]
👍

**Comment by marcoscaceres** [comment]
Sorry @nickevansuk, this never happened :( It's still hard for us to do this, because we have scripts and other external dependencies expecting things on gh-pages.
