### ISSUE TITLE
Allow people to deploy ReSpec as a dependency

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#824]
As raised by @halindrome, the problem with having W3C auto-deploy our builds is that end-users of ReSpec loose control of which version of ReSpec they are using. This has a number of issues: 
- Using semver is meaningless, because everyone just gets the latest. 
- Editors are not given the choice to upgrade, to test if their specs work ok, etc. Editors should make an informed choice when to upgrade, based on both semver and a changelog. This burden cannot be on the maintainers of ReSpec, because it simply does not scale. 
- End-users on the web suffer because they might occasionally see broken specs. 
- Maintainers need to occasionally fight fires, which wouldn't be the case if we could semver (as we could backport fixes, etc - but also develop new features without fear of breaking people's things). 

I would like to suggest we continue to allow the W3C to automatically deploy ReSpec "Nightly" ("use it at  your own risk"), and we start encouraging Editors to treat ReSpec as an npm dependency. That is, if you want to use ReSpec, you should:

``` Bash
npm install respec
respec2html -s spec.src.html -o spec.html   
```

//cc @dontcallmedom, @plehegar, your thoughts?

**Comment by dontcallmedom** [comment]
I'm not sure that we can rely on everything single W3C spec editor installing and adopting a node/npm environment.

If we switch ReSpec to semver, I'm happy to adjust the W3C mirroring setup so that we publish and keep the latest major releases available. That doesn't deal with the goal of keeping raw respec documents off the Web, but that feels like a separate topic in any case.

**Comment by halindrome** [comment]
I have to agree with Dom.  Most editors are just people who want to type.
Not people who are node / js experts.

I don't have a goal of keeping raw respec documents off the Web in any
case. I think that is a fine way for people to work in most instances.
Very low barrier to entry.  That's why ReSpec was attractive in the first
place.

On Fri, Jun 10, 2016 at 3:13 AM, Dominique Hazael-Massieux <
notifications@github.com> wrote:

> I'm not sure that we can rely on everything single W3C spec editor
> installing and adopting a node/npm environment.
>
> If we switch ReSpec to semver, I'm happy to adjust the W3C mirroring setup
> so that we publish and keep the latest major releases available. That
> doesn't deal with the goal of keeping raw respec documents off the Web, but
> that feels like a separate topic in any case.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/respec/issues/824#issuecomment-225119994>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAfx8Bw71r-Agn_ED6Ej0iQ8ICitMo6Pks5qKRyYgaJpZM4IyoSz>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by plehegar** [comment]
is the intent to deploy Respec source code as a dependency or to deploy a Respec build as a dependency? If the former, then I concur with Dom. I don't imagine editors being interested in deploying node/npm for the purpose of using respec. Those might as well use bikeshed. But if you give them the possibility to have the build as a dependency, then it allows them to use a specific version of respec.

**Comment by marcoscaceres** [comment]
> is the intent to deploy Respec source code as a dependency or to deploy a Respec build as a dependency?

One would have many options:

 * could link to ReSpec on w3c server
 * could link to local ReSpec 
 * could entirely exclude ReSpec, and dynamically include either local or w3c version to produce output


> I don't imagine editors being interested in deploying node/npm for the purpose of using respec. 

This may be true. It is highly convenient to just use a script tag. However, this is not the reality of modern web application development. I'll also note that the rapid uptake of BikeShed serves as a good counter example that a lot of editors are ok with this. 

I'm also worried about this kind of thing: can one disassociate knowing JS or web development practices and still meaningfully contribute to the standardization of JS APIs and web development practices? 

> Those might as well use bikeshed.

Perhaps, but they provide different features (BS wins here) and syntax (we use HTML, while BS uses some  proprietary markup language). A Bikeshed document could work exactly the same as ReSpec by calling the web service that Tab already set up (just doing `documentElement.outerHTML = responseText`).  

> But if you give them the possibility to have the build as a dependency, then it allows them to use a specific version of respec. 

Yes, that would be the idea. 

Again, the point is not to stop people from using ReSpec in a script tag - but to realize that there is much more flexibility in using it as a NPM dependency.

**Comment by marcoscaceres** [comment]
Oh, and this.... So much this:https://twitter.com/tabatkins/status/742856463748472834

**Comment by marcoscaceres** [comment]
Good enough for now.
