### ISSUE TITLE
Fetching GH issues can sometimes fail

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#825]
It's possible that when working on stuff, one hits the limit of 60 requests per hour when fetching Github issues. This causes a 403 and thus causes ReSpec to die (which is not great, obviously). Need some error recovery there.

**Comment by sidvishnoi** [comment]
How about we cache the responses from GitHub in the localStorage (for like 5min)? That can help in reducing the requests to GitHub.

**Comment by marcoscaceres** [comment]
Need to double-check if GitHub still has the 60/hour limit (I’ve not hit this problem in a long time). But yes, caching them would be good, and using the cached ones first and only invalidating stale ones. We do the same with bibliographical entries.

**Comment by saschanaz** [comment]
Has this been fixed, given that we have implemented caching?

**Comment by marcoscaceres** [comment]
I guess it's probably as good as it can be, given the limitations that we have.
