### ISSUE TITLE
Add ability to include date/time into ednotes

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#829]
In the ARIA Editors call today, people discussed having ednotes include the date they were added.  The suggestion was that they use a datetime attribute on the enclosing element.  We could then put this into the emitted content in a consistent manner.  

The use case was to give guidance about when an editors note was introduced to help reviewers understand relevance.

**Comment by marcoscaceres** [comment]
That be nice 👍

**Comment by marcoscaceres** [comment]
It's best to add the date/time via 'title='.
