### ISSUE TITLE
specberus issuing a warning on respec output

### ISSUE THREAD

**Issue by iherman** [w3c/respec#831]
(To be honest, I was not sure whether this is an issue for specberus or for respec, ie, I did not know where to submit the issue. The dice fell on the respec side:-)

When there is highlighting in a respec source, respec adds a bunch of css statements; in particular, it adds:

```
    .hljs {
      display: block;
      overflow-x: auto;
      padding: 0.5em;
      color: #333;
      background: #f8f8f8;
      -webkit-text-size-adjust: none;
    }
```

This leads to a warning in specberus, claiming that the `-webkit-...` property is not acceptable. 

I have not found the code in the respec repo for this css, so I cannot offer a PR if it is indeed a respec issue. Sorry about that; just reporting the issue.

Cc: @deniak

**Comment by marcoscaceres** [comment]
I'll look into it tomorrow. The CSS is coming from an upstream source - but I can rip out or change the CSS at save time. However, -webkit stuff is now, sadly, standard and might even be in specs. Need to check.

**Comment by marcoscaceres** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

So, it's non standard but we do want this on mobile😖 I guess I'll just rip it out for now.

**Comment by marcoscaceres** [comment]
@iherman, can one still publish if the warning is there?

**Comment by iherman** [comment]
Well, I guess for every warning it is a matter of discussing it with the webmaster, who is the ultimate authority...

I think this is something that should be discussed with @deniak, our current webmaster. I would only add as a go-between, which is hardly an efficient way of handling this:-)

**Comment by marcoscaceres** [comment]
/me hands @iherman a can with a string 😆 

@deniak - I can see why -webkit-text-size-adjust: none; was added by github.css - as it would presumably mess code examples up on mobile devices. As an iOS user, I'm a little bit scared about removing it.

**Comment by marcoscaceres** [comment]
Seems that "webkit-text-size-adjust" vanished from the style sheet upstream.
