### ISSUE TITLE
webidl-contiguous incorrectly links to non-idl definition

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#836]
We have a spec under development [1] that declares a block of IDL.  That IDL has a constructor in it that happens to have the same name as a 'dfn' for a term elsewhere in the document.  The constructor gets incorrectly linked to the term.   Basically, we need some way for webidl to know better than to link to a dfn that is not "for" the interface in question (data-dfn-for).  dfns that are in the document that are not "for" idl have a data-dfn-for attribute of 'dfn' I think.

Note: debugging this using the reference below is somewhat more complicated because the source for this brings in another external file with some terms in it.

[1] http://www.opencreds.org/specs/source/claims-data-model/

**Comment by marcoscaceres** [comment]
I think this was fixed.
