### ISSUE TITLE
Need WebIDL docs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#847]
The WebIDL documentation is lacking. The best we have is the `example/contiggeee...argh...hard...to..spell.html` file. We can take things from that tho.

**Comment by marcoscaceres** [comment]
I've created: 
https://github.com/w3c/respec/wiki/WebIDL-Guide

But it could use a once over. @halindrome, can you please review it and see if it's ok? Feel free to make changes, etc. Close if happy.

**Comment by halindrome** [comment]
Good start.  Closing.
