### ISSUE TITLE
Support different bibliographical styles

### ISSUE THREAD

**Issue by riannella** [w3c/respec#857]
The publisher is listed after the Authors, which is not a common bibliographic style.
Can the publisher item be moved to the end (before the URL ref)?

**Comment by marcoscaceres** [comment]
I tend to agree that the current bibliographical style is pretty awful. 

Can I suggest we change it to:

Linked-Document-Title (refNote). Publisher/Consortium. Date. Author/Editor. URL.

So: 
A. Phillips; M. Davis. IETF. Tags for Identifying Languages. September 2009. IETF Best Current Practice. URL: https://tools.ietf.org/html/bcp47

Becomes:
Tags for Identifying Languages (IETF Best Current Practice). IETF. September 2009. A. Phillips; M. Davis. URL: https://tools.ietf.org/html/bcp47

URL is also redundant, as it's already in the link... it should only be added when document is printed.

**Comment by marcoscaceres** [comment]
So to avoid debates, we should have a `biblioStyle` option... so we can just have some of the standard ones: MLA, APA, or whatever and people can just pick.

**Comment by riannella** [comment]
Agree - the biblioStyle option is the best solution (with a default setting).

**Comment by marcoscaceres** [comment]
@riannella, sorry, only now coming back to this... if I point you to the code for the current bibliographical style, could you make a derivative version that produces a "standard" bilbiographical style? It would be trivial to enable.

**Comment by riannella** [comment]
What biblio properties are currently supported? I can then indicate which ones are used (and the order) for APA and MLA citation styles.

**Comment by marcoscaceres** [comment]
@riannella we use this data/API: https://github.com/tobie/specref/blob/master/README.md#api

So, basically, we take a reference and covert it here: 
https://github.com/w3c/respec/blob/develop/src/core/biblio.js#L49

What we would do instead is add an optional "style" argument: 
```
function stringifyReference(ref, style) {
  switch(style):
    case "APA":
      output =  // do conversion here....
       break;
    case "MLA":
       output = // do conversion here....
       break;
   default:
     output = // what ReSpec currently does... 
  }
  return output;
}
```

**Comment by marcoscaceres** [comment]
Expanded example above... but that's basically what needs to happen.

**Comment by riannella** [comment]
APA and MLA have different rules depending if it is a Book, Journal, Website etc...but I think this is a good compromise (given the set of biblio properties we have):

MLA: authors, title, status, publisher, date, href

APA: authors, date, title, status, publisher, href

**Comment by marcoscaceres** [comment]
@riannella that sounds good. We don't have publication type information in the SpecRef database anyway, so even if we wanted to, we couldn't get too fancy. So compromise sounds good. 

You want to give the functions a shot? You can use ES6 templates strings, which should make it pretty easy: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

If not, I'll try to find some time.

**Comment by riannella** [comment]
Sorry @marcoscaceres but only a brave person should as me to code again ;-)

**Comment by marcoscaceres** [comment]
heh, np. I'll take me a little while, but I'll try to add the alternative citation methods.

**Comment by marcoscaceres** [comment]
Leaving this open, as I still like the idea of having the ability to choose styles

**Comment by marcoscaceres** [comment]
@riannella, ok, title first. Should be live in a few minutes.

**Comment by riannella** [comment]
yes, it works..looks much better 👍

**Comment by marcoscaceres** [comment]
@OrionStar25, this is a good one, I think. Details of what needs to be done are above. however, you need to modify this instead: 
https://github.com/w3c/respec/blob/develop/src/core/biblio.js#L66

It needs to take a citation style (e.g., `wireReference(rawRef, target, style)`). The default is whatever is there at the moment. 

But we also want to add the APA citation style:
http://www.bibme.org/citation-guide/apa/website/

And MLA is:
http://www.easybib.com/guides/citation-guides/mla-8/cite-website-mla-8/

**Comment by OrionStar25** [comment]
On it!

**Comment by marcoscaceres** [comment]
@riannella, we spent a fair bit of time on this (https://github.com/w3c/respec/pull/1561) but we concluded that neither APA and MLA were really suitable for referencing in specs. Also, the current structure (or lack of it) in specref made this harder/more error prone than we anticipated.   

So, unfortunately, we won't be able to support this. Closing as won't fix.
