### ISSUE TITLE
support `data-for` attribute for WebIDL

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#863]
Right now, defining something from to a contiguous WebIDL requires the use to an invalid `for` attribute. This causes a warning when trying to tidy HTML, like:

```BASH
line 268 column 11 - Warning: <dfn> proprietary attribute "for"
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!
```
Which is not great.

**Comment by halindrome** [comment]
I thought we also supported data-for?  We do in the dfn module.... I was
using it to track the definitions for different buckets for exporting etc.
in my changes to support bikeshed-like definitions and references..

On Sun, Jul 10, 2016 at 8:51 AM, Marcos Cáceres <notifications@github.com>
wrote:

> Right now, defining something from to a contiguous WebIDL requires the use
> to an invalid for attribute. This causes a warning when trying to tidy
> HTML, like:
>
> line 268 column 11 - Warning: <dfn> proprietary attribute "for"
> Info: Document content looks like HTML5
> Tidy found 1 warning and 0 errors!
>
> Which is not great.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/respec/issues/863>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAfx8HgLgP8VAxzg86TwAKKVeRHd4z2pks5qUPjFgaJpZM4JI1rn>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Dunno. I tried it yesterday and it didn't work:( will take a closer look today.

**Comment by marcoscaceres** [comment]
So, turns out it is "data-dfn-for".
