### ISSUE TITLE
Tool to convert old school webidl to new school webidl

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#864]
Text from the methods, and attribute descriptions seem to have disappeared from the ReSpec spec TV Control API:
http://w3c.github.io/tvcontrol-api/

All that remains is the "MUST", or attribute types, see e.g.:
http://w3c.github.io/tvcontrol-api/#attributes-1

I tried different releases of ReSpec. [Version 3.3.1](https://github.com/w3c/respec/commit/db24dee49156ae850277eb6a76d87445b0bf7d2c) still renders the text correctly, while version 3.3.2 does not. Could the update to jQuery 3.0.0 have triggered this?

Note this spec will likely move to WebIDL contiguous mode at some point, that's just not done yet.

**Comment by marcoscaceres** [comment]
Hi François,
Old school web idl is obsolete. I'm happy to help with transitioning the spec to new school webidl. 

And yes, I think the move to jquery 3 had a negative effect on old school webidl. Ive transitioned quite a few specs already: it's quite straight forward.

**Comment by tidoust** [comment]
Understood, Marcos. I know how to transition the spec, just need to find the time. I forced the use of a previous version of ReSpec in the meantime.

**Comment by halindrome** [comment]
I know we have deprecated old style IDL.  I will take a quick look and see
if there is anyway to do a patch.

On Mon, Jul 11, 2016 at 9:08 AM, François Daoust <notifications@github.com>
wrote:

> Understood, Marcos. I know how to transition the spec, just need to find
> the time. I forced the use of a previous version of ReSpec in the meantime.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/respec/issues/864#issuecomment-231744955>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAfx8NIx-T6nr9JrepYNfjiK4BFzk6Jxks5qUk5OgaJpZM4JJNXX>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
@tidoust, I suggest you take a look at the Web Audio repo. Someone there came up with a tool that automagically converts old school to new school IDL. 

If you can find the source, it might be a nice addition to our /tools/ folder that more people could use. I'd be happy to help with that.

**Comment by tidoust** [comment]
@marcoscaceres, I do not know for Web Audio, but I note @dontcallmedom worked on a tool to semi-automate the conversion for the WebRTC spec: 
https://github.com/dontcallmedom/respec/tree/oldschool2contiguous
https://github.com/dontcallmedom/respec/blob/oldschool2contiguous/js/core/webidl-oldschool-converter.js

I haven't had a look at it yet. I'll let @dontcallmedom comment on whether that can be easily turned into a tool for the /tools/ folder.

**Comment by marcoscaceres** [comment]
So, I think we successfully did all the conversions... so, don't need this anymore 🎉
