### ISSUE TITLE
Lint for charset not being UTF-8

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#873]
We should add a rule to the linter that checks if a document's charset is UTF-8.

**Comment by marcoscaceres** [comment]
We can probably do better, and always convert to UTF-8 on save via Encoding API.

**Comment by marcoscaceres** [comment]
So it’s not exactly checked: it just blindly adds a meta charset saying it’s UTF-8. But the document might be in a different encoding.

**Comment by shubhshrma** [comment]
```TextEncoder``` of the API is what we need here?

**Comment by marcoscaceres** [comment]
> TextEncoder of the API is what we need here?

I think so, then decode it out to UTF-8.

**Comment by saschanaz** [comment]
@marcoscaceres Is this still relevant? I think the new `core/exporter` always generates UTF-8.

**Comment by marcoscaceres** [comment]
I think the idea was to check if the input is not UTF-8 or if it contains a contradictory `<meta charset>` prior to exporting.

**Comment by saschanaz** [comment]
> if the input is not UTF-8

I think the only way to check it is to check whether meta[charset] is absent or points a different encoding.

> if it contains a contradictory <meta charset> prior to exporting

👍


________________________________

**Comment by CodHeK** [comment]
@saschanaz any work that needs to be done here, maybe I can try doing this issue ?

**Comment by saschanaz** [comment]
Hello @CodHeK!

We want to add a file in `src/core/linter-rules` that checks the document has `<meta charset="utf-8" />` properly. A linter warning message should be shown if it's absent or there is non-UTF-8 charset declaration instead.

Checking out existing linters e.g. [local-refs-exist](https://github.com/w3c/respec/blob/develop/src/core/linter-rules/local-refs-exist.js) may help you understanding how the linters work.

**Comment by CodHeK** [comment]
@saschanaz okay, great! I'll do a bit of checking and get back if I have any doubts!

**Comment by CodHeK** [comment]
@saschanaz looking at the existing linters gives me a fair idea of how to proceed, but how do I test them as an when I write the code for the linter ?

**Comment by saschanaz** [comment]
@CodHeK You can test it somehow like this: https://github.com/w3c/respec/blob/bd65955f036e1912f932ac4188cdff5c4a65780a/tests/spec/core/linter-rules/local-refs-exist-spec.js

Note that you have to register your new linter in src/w3c/defaults.js first before any test.

**Comment by CodHeK** [comment]
@saschanaz should the link add the meta tag by it's own to the doc if not present ? or change it to utf-8 if it's something else ?

**Comment by CodHeK** [comment]
@saschanaz please review the PR for the linter https://github.com/w3c/respec/pull/2075
