### ISSUE TITLE
More granular styles for "table.simple th code" with better legibility/contrast

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/respec#877]
See for instance the simple tables at https://w3c.github.io/pointerevents/#dom-pointerevent-pointertype and https://w3c.github.io/pointerevents/#the-buttons-property - with current styles, using `<code>` in a `<th>` results in an unreadable color combination with a very low color contrast.

![74437974-4d70-11e6-926a-30a2203cb298](https://cloud.githubusercontent.com/assets/895831/16954397/a660bd92-4dc8-11e6-8a8a-e472f4176ab7.png)

Is this something that can/should be fixed here in respec? Not sure if this is a common use pattern.

x-ref https://github.com/w3c/pointerevents/issues/112

**Comment by marcoscaceres** [comment]
Argh, yuck - look at that. 

We could fix easily fix it in ReSpec (in [respec2.css](https://github.com/w3c/respec/blob/develop/js/core/css/respec2.css)), but need to double check if it's not coming from the w3c's style sheet. 

We are trying to kill ReSpec from having any style information at all.

**Comment by marcoscaceres** [comment]
Confirmed, it's coming from ReSpec. Will send a PR.
