### ISSUE TITLE
Allow for figure references not to include the whole caption

### ISSUE THREAD

**Issue by r12a** [w3c/respec#879]
It's extremely useful to be able to automatically fill in the link text for pointers to figures. (Jlreq has over 300 figures, most of which are referred to from the text.)  However, it's a bit problematic when the link text becomes something like

`see Fig. 10: Example of face tsumegumi in horizontal writing mode. (The 1st line is the same text with solid setting, for comparison.).`

Note also that this tends to produce a double full stop at the end.

I'd like to be able to produce just the following instead

`see Fig. 10`

I think this should be the default actually.

(Note that i'm happy to continue filling section links with the section title – that gives a useful result.)

**Comment by r12a** [comment]
In case it helps, i looked at the code. I'm not familiar with this style of js, but i guess the basic idea is as follows.

go to https://github.com/w3c/respec/blob/develop/js/core/figures.js

change
```
if (figMap[id]) {
        $a.addClass("fig-ref");
        if ($a.html() === "") $a.append(figMap[id].clone());
}
```

to append the following information created as part of a figure
```
.prepend($("<span class='figno'>" + num + "</span>"))
.prepend(doc.createTextNode(conf.l10n.fig))
```

rather than just cloning the whole figcaption.

**Comment by r12a** [comment]
Still waiting for this to be done.  How can we move it forward?

**Comment by halindrome** [comment]
I am uncomfortable just implementing this as it would significantly change the way the tool works for existing users.  I wouldn't mind this with an option I guess...   conf.figRefNumOnly = true or something.  @marcoscaceres what do you think?

**Comment by r12a** [comment]
I'd prefer it to be a default, but i hear what you say, and a switch would be ok.

**Comment by r12a** [comment]
Can we raise the priority of this?  I'm trying to prepare a doc for publication and hitting validation errors because the caption of the figure contains a tags linking to definitions.

```
<a href="#figure-letter_reh_shapes" class="fig-ref">Figure <span class="figno">6</span> 
<span class="fig-title">
<a href="#dfn-right-joining" class="internalDFN" data-link-type="dfn">Right-joining 
letters</a> only have two forms of <a href="#dfn-final" class="internalDFN" data-link-type="dfn">final</a> 
and <a href="#dfn-isolated" class="internalDFN" data-link-type="dfn">isolated</a>.
</span></a>
```

Which means that every time i generate the doc from respec, i need to track down and manually change the markup here (by removing the figure caption from the reference).  That's definitely broken!

**Comment by marcoscaceres** [comment]
Sorry, trying to get to this :( I agree that it should just be “see Figure 10”.  That’s pretty standard.

**Comment by himanish-star** [comment]
I would like to take over this
