### ISSUE TITLE
Build scripts hardcode location of node

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#899]
The scripts assume node is at /usr/local/bin/node.  This isn't always practical.  I think they should be changed to just assume it is in the path.

For example, right now I do builds on a few different platforms and rely upon nvm to allow me to choose the version of node that is in use.

**Comment by marcoscaceres** [comment]
>  I think they should be changed to just assume it is in the path.

That sounds fine, but I have no idea how to that... what do I put at the top of files to indicate that they are require node to run?

**Comment by dontcallmedom** [comment]
```sh
#!/usr/bin/env node
```
?

(I was hit by the same issue FWIW)

**Comment by marcoscaceres** [comment]
@dontcallmedom, thanks! Will update the scripts now.
