### ISSUE TITLE
Add Linking to constructors in WebIDL 

### ISSUE THREAD

**Issue by mwatson2** [w3c/respec#900]
```
[Constructor]
interface Foo
{
...
};
```

If I document the `Foo` constructor with `<dfn>Foo</dfn>`, then all links to `Foo` in the document point to the definition of the constructor (`#dom-foo`) and not to the IDL (`#idl-def-foo'). No amount of additional attributes on the`dfn` element seems to fix this.

**Comment by marcoscaceres** [comment]
@mwatson2, sorry, can you provide just a tiny bit more text so I can make sure we fix this properly? Like, what would you like to describe about the Foo constructor. Some sample text/markup would be really helpful to see how to wire everything up.

**Comment by marcoscaceres** [comment]
Ok, looked into this a bit more... Yeah, we sadly don't support this yet.

**Comment by marcoscaceres** [comment]
changed to feature request.

**Comment by marcoscaceres** [comment]
Duplicate of https://github.com/w3c/respec/issues/394
