### ISSUE TITLE
Lint for definitions that are defined but never used

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#904]
It should flag things that are defined but never used as potential errors.

**Comment by halindrome** [comment]
I have code for this.  That code ALSO knows how to find definitions that only refer to other definitions.  And this is another example of a warning that could go into a separate "lint warnings" box so it doesn't scare people.

**Comment by marcoscaceres** [comment]
Awesome if you already have code. I'm trying to think of a nice UI for the linter messages.

**Comment by halindrome** [comment]
Note that the code that decides if a reference to a definition and whether that reference is just from another definition or not depends upon definitions being in a section with a well known class.  We do this so we can remove the terms that are unused from the document automatically (when including terms from a central glossary file shared among many specs).  Anyway, how about if I do a PR that maintains and exposes the list of unused terms, and then we can independently decide what to do with said list?
