### ISSUE TITLE
define where vocabulary in webidl should link

### ISSUE THREAD

**Issue by johanneswilm** [w3c/respec#910]
For the @w3c/editing inputevent spec, we would like to do:

```
readonly attribute DataTransfer? dataTransfer;
```

But it seems this is currently not possible, as respec will automatically link both instances of "datatransfer" to the same definition. For now it says:

```
readonly attribute DataTransfer? transferData;
```

But just changing the attribute name to make dealing with respec seems not the right way of dealing with this. This may be a documentation issue.

**Comment by marcoscaceres** [comment]
Related spec:
https://w3c.github.io/clipboard-apis/#dfn-datatransfer

**Comment by marcoscaceres** [comment]
Argh, I mean: 
http://w3c.github.io/editing/input-events.html

**Comment by johanneswilm** [comment]
They also use it, yes, but that's not the spec that has the issues. The spec that has the issues is http://w3c.github.io/editing/input-events.html

**Comment by johanneswilm** [comment]
ah, you found it. will remove comments.

**Comment by marcoscaceres** [comment]
Ok, we should start by converting the spec to contiguous WebIDL... old
school web IDL is deprecated.

**Comment by johanneswilm** [comment]
Ok, will do. Is there some place one can see updates on what aspects become deprecated and how to convert it to the new format?

**Comment by marcoscaceres** [comment]
On August 8, 2016 at 1:52:08 PM, Johannes Wilm (notifications@github.com) wrote:
> Ok, will do. Is there some place one can see updates on what aspects become deprecated
> and how to convert it to the new format?

Usage of deprecated features show up as warning next to ReSpec pill.

Sadly, the documentation for conversion is still really lacking.
However, this is a good opportunity to improve it.

I'm going to do a once over on your spec... brb

**Comment by johanneswilm** [comment]
> Usage of deprecated features show up as warning next to ReSpec pill.

I don't currently see any warnings.

> I'm going to do a once over on your spec... brb

ok, great. I believe it should also be
```
partial interface InputEvent : UIEvent
```
but it seems the old format couldn't handle partial and subclassing simultaneously.

**Comment by marcoscaceres** [comment]
> I don't currently see any warnings.

That was me looking at the wrong spec.. Sorry about that.

**Comment by marcoscaceres** [comment]
@johanneswilm Take a look at:
http://w3c.github.io/respec-docs/examples/webidl-contiguous.html

That basically shows all the functionality we currently support with regards to linking WebIDL to prose. It may help.

**Comment by johanneswilm** [comment]
@marcoscaceres I have looked at that document before, but couldn't see any example that would fit. I then quickly skimmed over the respec source code and didn't get any wiser. So I concluded that what we need is either undocumented or not supported, which is why I created this bug report. I now looked at the document again. Is there something in their I have overlooked that applies in this case?

What is the suggestion to do if this is not supported? Simply write the webidl part directly in HTML with inline CSS?

**Comment by marcoscaceres** [comment]
>  Is there something in their I have overlooked that applies in this case?

No, I think you are correct and it's currently not supported. Your document's markup seems to be ok - so it's clearly a limitation with ReSpec :(  

> What is the suggestion to do if this is not supported? Simply write the webidl part directly in HTML with inline CSS?

For now yes - certainly something you can try. Will try to fix this bug soon in ReSpec itself.

**Comment by marcoscaceres** [comment]
@johanneswilm, I think I found the problem. You should use a `data-dfn-for` attribute.  The following works for me locally:

```HTML
    <section>
      <pre class="idl">
interface Test{
  readonly attribute DataTransfer? dataTransfer;
};
      </pre>

      <p><dfn data-dfn-for=Test>dataTransfer</dfn> holds information about richtext and
        plaintext data that is to be taken from or added to the document
      in a <code><dfn>DataTransfer</dfn></code> object if there is relevant data.
    </section>
```
