### ISSUE TITLE
https not used for patent links

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/respec#914]
According to https://lists.w3.org/Archives/Public/spec-prod/2016JulSep/0022.html, https is now required for certain w3c links, and respec has been updated to output them. But in http://rawgit.com/w3c/aria/MC_graphics_pub_Aug2016/svg-aam/svg-aam.html (or https://labs.w3.org/spec-generator/?type=respec&specStatus=WD&url=http://rawgit.com/w3c/aria/MC_graphics_pub_Aug2016/svg-aam/svg-aam.html), the links for "public list of any patent disclosures..." are coming out as http, and this is causing it to fail pubrules.

**Comment by halindrome** [comment]
Check your respec configuration in the source.  It is likely that you have the URI hardcoded as starting with http: instead of https:  

Respec does not override your choice in this.

**Comment by michael-n-cooper** [comment]
Oh, sorry. I thought respec was just generating that stuff from the WGID, e.g., 83726, didn't notice it was hard-coded as a full URI in the config. That would be easier I think, but that means I can fix this for now.

**Comment by marcoscaceres** [comment]
Filed a feature request: https://github.com/w3c/respec/issues/915
