### ISSUE TITLE
Preload back-cg-draft.png

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#921]
Opportunistically preload back-cg-draft.png when status is CG-Draft ... same with CG-Final:
- https://www.w3.org/StyleSheets/TR/2016/logos/back-cg-draft.png
- https://www.w3.org/StyleSheets/TR/2016/logos/back-cg-final.png

**Comment by shivendrarox** [comment]
Hi!! @marcoscaceres,
I am interested on working in this one!

**Comment by shivendrarox** [comment]
Hi!! @marcoscaceres,
I am interested on working in this one!

**Comment by shivendrarox** [comment]
are you meaning something like this ?
https://codepen.io/shivendrarox/pen/bvpzmB

**Comment by marcoscaceres** [comment]
Not quite :) more like this:
https://github.com/w3c/respec/blob/develop/src/w3c/style.js#L82

Browsers already know how to preload things.

**Comment by marcoscaceres** [comment]
Basically, we need to use this function when the spec is a CG-Draft
https://github.com/w3c/respec/blob/develop/src/core/utils.js#L148

And you would need to figure out where the CG-Draft template is loaded from. On my phone, so can’t check :(

**Comment by lolimay** [comment]
Hi, @marcoscaceres . Is this issue still valid? I think I could work on this.

**Comment by marcoscaceres** [comment]
heh, sorry @lolimay... you keep finding all the bogus ones. We probably don't want to preload this, as it's a low priority resources. On the bright side, you've helped closed two issues, so ... 🏆

**Comment by lolimay** [comment]
That's really a pity😂, I believe that I can fix some valuable issues later.
