### ISSUE TITLE
respec-w3c-common  has a bug

### ISSUE THREAD

**Issue by michael-oneill** [w3c/respec#928]
Since this morning I am getting the following bug:

respec-w3c-common:12 Uncaught ReferenceError: PARAMS_CONTAINS is not defined

e.g. in https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html

**Comment by zcorpan** [comment]
Maybe a bug in the minifier? https://github.com/w3c/respec/blob/e384535ab86bd0511c96e88b24902889e8a1eb07/js/deps/highlight.js#L990 doesn't have "return" there...

**Comment by opoto** [comment]
Breaks http://globalplatform.github.io/WebApis-for-SE/doc/

**Comment by marcoscaceres** [comment]
Thanks for reporting. I've reverted to 5.0. Will bisect in the morning!

**Comment by marcoscaceres** [comment]
Odd that our CI reported no issue with 5.0.1.
https://travis-ci.org/w3c/respec/builds/156733035

**Comment by marcoscaceres** [comment]
So, turns out this is a bug in hightlight.js. I sent an PR upstream: 
https://github.com/isagalaev/highlight.js/pull/1306

**Comment by marcoscaceres** [comment]
I also patched hightlight.js locally, waiting for a fix.
