### ISSUE TITLE
Stylesheets should be harmonized with bikeshed

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#936]
(this came up at lunch at TPAC)

Bikeshed and ReSpec should use the same styles for things that are NOT already covered by the W3C house styles.   In particular, IDL, references, etc.

**Comment by marcoscaceres** [comment]
I can only agree. But it would mean aligning CSS class names of generated things. We could do this incrementally tho.

**Comment by halindrome** [comment]
FWIW unless there is an actual class name collision, aligning could be as simple as *adding* their class names to the ones we put in, right?

**Comment by marcoscaceres** [comment]
Correct, but we need to do that investigation.

**Comment by marcoscaceres** [comment]
We've aligned as much as we can and now rely more heavily on tr-design. Closing as nothing really actionable here.
