### ISSUE TITLE
Safari no longer rendering ReSpec and gives an error

### ISSUE THREAD

**Issue by clapierre** [w3c/respec#949]
I am using Safari Version 9.1.3 (11601.7.8) under OS X Version 10.11.6

When I go to
http://w3c.github.io/dpub-pwp-ucr/index.html 
or any previously reSpec file locally (which use to work)
reSpec does not reformat the page and in debug logs:

I get the following error.
`     <script src="https://www.w3.org/Tools/respec/respec-w3c-common" async="" class="remove”>
`
line 3329 of respect-w3c-common
Unexpected keyword ‘const’
Const declarations are not supported in strict…
o=s;

**Comment by marcoscaceres** [comment]
Thanks for the bug report. Unfortunately, we only support Safari 10:( We don't have enough resources to support legacy browsers for spec generation - only for output. Any reason you can't upgrade to 10?

**Comment by clapierre** [comment]
Our IT told us not to upgrade to the latest version of MacOS which I assume also ties to Safari.
Here was their email.

MacOS Sierra (10.12) was released yesterday.  Please do not do the upgrade at this time as its not compatible with our VPN and Symantec Endpoint Protection.  There may be other applications not compatible that we are not aware of at this time.

**Comment by marcoscaceres** [comment]
> On 15 Oct. 2016, at 12:10 am, Charles LaPierre <notifications@github.com> wrote:
> 
> Our IT told us not to upgrade to the latest version of MacOS which I assume also ties to Safari.
> 

 I have Safari 10 installed and I'm not on Sierra. Works great! It should be a standard update from the AppStore.

**Comment by marcoscaceres** [comment]
Closing, as the solution is just to update the browser.
