### ISSUE TITLE
Deprecate lc related things

### ISSUE THREAD

**Issue by aaronpk** [w3c/respec#953]
Respec throws a warning when the JSON data is missing an `lcEnd` property, but this is no longer required under the new process.

**Comment by marcoscaceres** [comment]
Given that LC is no longer part of the W3C process at all, I'm just going to remove all the LC stuff from ReSpec.

**Comment by marcoscaceres** [comment]
@aaronpk, let me know if it's all good for you.

**Comment by aaronpk** [comment]
Thanks!
