### ISSUE TITLE
Example style gets broken

### ISSUE THREAD

**Issue by yoavweiss** [w3c/respec#958]
I've edited the [preload spec](https://w3c.github.io/preload/) and did [some changes](https://github.com/yoavweiss/preload/tree/add_as_for_header). They seem to have broken the styling of the example that followed them ("directives to preload").

Looking at the inspector, I see that the example continaer was turned from `<div class=example>` to `<pre class="hljs xml">`. I'm not sure why. Truncating the length of above change (e.g. from 3 paragraphs to 2) seems to make the issue go away

**Comment by halindrome** [comment]
First.... respec doesn't look at div when playing with examples... You cannot actually put raw html in a example and have it presented as an html example.... you would need to escape the &lt;, &gt;, and &amp; symbols if that is what you are trying to do.

As to what is happening with the class.  I think it has to do with the IDL processing.  I will try to run that down.

**Comment by yoavweiss** [comment]
In that particular case, a new line between the `</p>` and the `</div>` was the cause for style breakage.

**Comment by marcoscaceres** [comment]
@yoavweiss, is this still an issue? I'm trying to see if it's still broken...

**Comment by marcoscaceres** [comment]
@yoavweiss, please reopen if not fixed.
