### ISSUE TITLE
"Unable to test GitHub repository" on Snyk site

### ISSUE THREAD

**Issue by nickmccurdy** [w3c/respec#960]
I noticed in a PR that the Snyk build status indicator was passing, but oddly enough if you click on the `Details` link the Snyk site gives you this error. I'm not sure if this is intentional, I haven't used it before.

[Home page of this repo on Snyk](https://snyk.io/test/github/w3c/respec)

**Comment by marcoscaceres** [comment]
@nickevansuk, I'll look into it.

**Comment by marcoscaceres** [comment]
Seems to be working correctly again.
