### ISSUE TITLE
Support linking to stringifier

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#982]
Given:

```JS
interface Foo {
   stringifier DOMString();
};
```

One should be able to link to the stringifier somehow.

**Comment by marcoscaceres** [comment]
The rendering of stringifier is also kinda bad... it puts spaces between the return type and `()`

**Comment by marcoscaceres** [comment]
This should link to "stringification behavior" when `stringifier;` appears on its own. When it appears on an attribute, the attribute defines the serialization steps.

**Comment by marcoscaceres** [comment]
@saschanaz is `stringifier DOMString();` even a thing anymore?

**Comment by saschanaz** [comment]
It's a thing, but equivalent of `stringifier;`. Yes, stringifier operations always return DOMString [per the spec](https://heycam.github.io/webidl/#idl-stringifiers).

>Stringifiers declared with operations must be declared to take zero arguments and return a DOMString.

**Comment by marcoscaceres** [comment]
Ah, ok... so such anonymous translate to toString()? or should we just use "stringification behavior"?

**Comment by marcoscaceres** [comment]
I'm wondering mostly how we would link to these in a spec... stringifiers are quite rare, judging by Gecko's support of them:
```
dom/webidl/DOMException.webidl:  stringifier;
dom/webidl/DOMMatrix.webidl:    [Exposed=Window, Throws]   stringifier;
dom/webidl/DOMTokenList.webidl:  stringifier DOMString ();
dom/webidl/HTMLHyperlinkElementUtils.webidl:  // Bug 824857: no support for stringifier attributes yet.
dom/webidl/HTMLHyperlinkElementUtils.webidl:  //  stringifier attribute USVString href;
dom/webidl/HTMLHyperlinkElementUtils.webidl:  stringifier;
dom/webidl/Location.webidl:  // Bug 824857: no support for stringifier attributes yet.
dom/webidl/Location.webidl:  //  stringifier attribute USVString href;
dom/webidl/Location.webidl:  stringifier;
dom/webidl/MediaList.webidl:  // Bug 824857: no support for stringifier attributes yet.
dom/webidl/MediaList.webidl:  // stringifier attribute DOMString        mediaText;
dom/webidl/MediaList.webidl:  stringifier;
dom/webidl/Range.webidl:  stringifier;
dom/webidl/Selection.webidl:  stringifier DOMString ();
dom/webidl/URL.webidl:  // Bug 824857: no support for stringifier attributes yet.
dom/webidl/URL.webidl:  //  stringifier attribute USVString href;
dom/webidl/URL.webidl:  stringifier;
dom/webidl/URLSearchParams.webidl:  stringifier;
dom/webidl/WorkerLocation.webidl:  // Bug 824857: no support for stringifier attributes yet.
dom/webidl/WorkerLocation.webidl:  //  stringifier attribute USVString href;
dom/webidl/WorkerLocation.webidl:  stringifier;
```

**Comment by saschanaz** [comment]
> Ah, ok... so such anonymous translate to toString()? or should we just use "stringification behavior"?

Do you have a preference? `toString` is a reserved identifier so we can freely use it for linking.

Stringifiers are indeed rare, and I failed to find a real example of the longer form of stringifier. There are some `stringifier attribute` but not `stringifier DOMString ()`; Should it be removed? 🤔

The DOMTokenList thing there is just a workaround because gecko doesn't support stringifier attributes. ([I have a patch](https://phabricator.services.mozilla.com/D48355).)

**Comment by marcoscaceres** [comment]
On reflection, `toString` will be confusing because people will wonder where that method came from.  So I think for `stringifier;` tried to link to "stringification behavior" for `Interface`. 

> stringifier DOMString ();

Be nice if that died.

**Comment by marcoscaceres** [comment]
> I have a patch

🤯

**Comment by saschanaz** [comment]
>Be nice if that died.

Found one example in [Selection API](https://w3c.github.io/selection-api/#selection-interface), but AFAICT it's the only spec that uses this form.

**Comment by saschanaz** [comment]
Filed https://github.com/heycam/webidl/issues/816
