### ISSUE TITLE
Delete boilerplate with link to translations page?

### ISSUE THREAD

**Issue by tripu** [w3c/respec#983]
[`js/w3c/templates/headers.html#L124-L127`](https://github.com/w3c/respec/blob/cd363b9ccee3251e6e32895b702f3f5b34855238/js/w3c/templates/headers.html#L124-L127)

cf w3c/specberus#552

**Comment by marcoscaceres** [comment]
Sorry, just saw this. Will fix soon

**Comment by tripu** [comment]
@marcoscaceres, I'm sorry for dragging you into this perhaps too early, but discussion about the exact wording and the expected links for translations isn't settled yet: https://github.com/w3c/specberus/issues/552#issuecomment-278046638

**Comment by marcoscaceres** [comment]
np, I've got no idea what's going on anyway so it's all good 👍
