### ISSUE TITLE
Autolink IDL extended attributes

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#989]
Well-known IDL definitions should be automatically linked to the WebIDL spec (e.g., SecureContext, etc.).

**Comment by marcoscaceres** [comment]
duplicate of #702

**Comment by anssiko** [comment]
It seems [SecureContext] links to https://www.w3.org/TR/WebIDL-1/#SecureContext that does not exist, should link to https://heycam.github.io/webidl/#SecureContext instead.

A possible solution would be to link to https://heycam.github.io/webidl/ by default, but that might have process implications. Perhaps in such cases specs could opt-out from extended attribute auto-linking via a config flag, or too messy?

**Comment by tidoust** [comment]
@anssiko FYI, we exchanged about the WebIDL version to use for that feature in #1105 (also about an opt-in mechanism). There are process implications for PR/REC specs.

I guess the process response here would be "all keywords that exist in WebIDL Level 1 should auto-link to WebIDL Level 1", "all keywords that only exist in WebIDL Level 2 should auto-link to WebIDL Level 2", creating two references in the end.

Now, in WD, ED, and even CR, people would probably rather expect to simply link to the latest version of WebIDL without having to worry about what is defined where and what can be considered stable.

**Comment by marcoscaceres** [comment]
Ah, doh! I knew I missed one. Will check the others too. 

So, ReSpec will only add WebIDL-LS iff the Editor uses one of the LS features. But never on its own. By using SecureContext, for instance, an editor is opting to cite LS. Not much we can justifiably do about it.

**Comment by marcoscaceres** [comment]
> I guess the process response here would be "all keywords that exist in WebIDL Level 1 should auto-link to WebIDL Level 1", "all keywords that only exist in WebIDL Level 2 should auto-link to WebIDL Level 2", creating two references in the end.

So the problem is that things in L2 might supersede things in L1 with bug fixes, etc. 

> Now, in WD, ED, and even CR, people would probably rather expect to simply link to the latest version of WebIDL without having to worry about what is defined where and what can be considered stable.

We might need to make some hard choices here - and then ask people to complain "upstream". For things that are in L2, we should link to L2. For things that are fixed in L2 - we should tell people to complain to WebIDL editors to push those things down to L1 (or to publish a "stable" L2 as REC, and produce an L3, and so on).

**Comment by marcoscaceres** [comment]
Option 3 is that the W3C just make an exception for WebIDL - which would more closely match reality.
