### ISSUE TITLE
Error trying to install a local copy of Respec

### ISSUE THREAD

**Issue by riannella** [w3c/respec#992]
Hi, I am trying to install a local copy of Respec (to make some specific changes) and after the "npm install" I get the following error:
=====
> respec@7.0.0 copydeps /Users/renato/users/monegraph/GitHub/architecture/respec-develop
> node ./tools/copydeps.js

/Users/renato/users/monegraph/GitHub/architecture/respec-develop/tools/copydeps.js:30
const rm = async(function*(...files) {
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "copydeps"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! respec@7.0.0 copydeps: `node ./tools/copydeps.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the respec@7.0.0 copydeps script 'node ./tools/copydeps.js'.
npm ERR! This is most likely a problem with the respec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/copydeps.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs respec
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls respec
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/renato/users/monegraph/GitHub/architecture/respec-develop/npm-debug.log

=========

This is macOS 10.12.2

**Comment by marcoscaceres** [comment]
Your version of Node is out of date 😊 please use anything above version 6 (current LTS release).

**Comment by riannella** [comment]
Thanks @marcoscaceres - that worked....
I do wish computers were smarter ;-)

**Comment by marcoscaceres** [comment]
@riannella, I'm hoping to be able to warn in the future about this.
