### ISSUE TITLE
Support markdown includes

### ISSUE THREAD

**Issue by tpluscode** [w3c/respec#993]
It would seem that the `data-include` always imports HTML or text when the `data-include-format` attribute is used.

I think that when the global setting mandates the use of markdown (`var respecConfig={ format: "markdown" }`) includes should also be treated as such.

Alternatively (or in addition), `data-include-format="markdown"` could also be supported.

**Comment by marcoscaceres** [comment]
I agree. It seems like a bug that it currently isn't.

**Comment by marcoscaceres** [comment]
ok, yeah... the markdown processing is happening before the includes. It might be a one line fix to get it to work. 

For reference:
js/profile-w3c-common.js

We should can try just moving markdown processing down (or, alternatively, moving the includes code up).

**Comment by marcoscaceres** [comment]
Experimented and sent a PR to fix this... need to write a test for it before merging, but seems all good.

**Comment by tpluscode** [comment]
Great. Thanks for acting so quickly

**Comment by tpluscode** [comment]
Is this already included in 7.1.0?

**Comment by marcoscaceres** [comment]
No, but I'll release soon (in a couple of hours).

**Comment by marcoscaceres** [comment]
@tpluscode, shipped it! Let me know if you have any problems.

**Comment by tpluscode** [comment]
Unfortunately there is a problem. You can see the errors appearing in console [here](http://t-code.pl/Hydra/spec/latest/core/)

**Comment by marcoscaceres** [comment]
@tpluscode, ah! I see... Try this:

1. Remove `##conformance` from the include file - ReSpec treats the conformance section as special. 
2. change you include to section to just:

```HTML
<section id="conformance" data-include="sections/conformance.html"></section>
```

**Comment by tpluscode** [comment]
I did that ant it still breaks most of the time. And when it doesn't the conformance section doesn't appear in the ToC and has no header

**Comment by tpluscode** [comment]
> most of the time

possible race condition?

**Comment by marcoscaceres** [comment]
Odd, was working for me locally. I'll take a closer look tomorrow. Should be fixable tho. 

Thanks for your patience.

**Comment by tpluscode** [comment]
Hey, no problem! Take your time

**Comment by marcoscaceres** [comment]
@tpluscode, I refactored the include code. Hopefully it is working ok now.

**Comment by tpluscode** [comment]
No luck :(. Here are the errors I'm getting

> TypeError: Cannot read property 'classList' of undefined
    at Object.show (ui.js:38)
    at profile-w3c-common.js:79
    at y.check (require.js:887)
    at y.enable (require.js:1177)
    at Object.enable (require.js:1565)
    at y.<anonymous> (require.js:1164)
    at each (require.js:70)
    at y.enable (require.js:1111)
    at y.init (require.js:792)
    at require.js:1400

>TypeError: $.getJSON(...).error is not a function
    at Object.apply (respec-w3c-extensions.js:115)
    at Object.runAll (base-runner.js:41)
    at Array.<anonymous> (profile-w3c-common.js:81)
    at e (domReady.js:12)
    at t (domReady.js:22)
    at HTMLDocument.n (domReady.js:32)

> TypeError: Cannot read property 'remove' of null
    at Object.run (markdown.js:254)
    at base-runner.js:54
    at base-runner.js:53 "TypeError: Cannot read property 'remove' of null
    at Object.run (https://cdn.rawgit.com/w3c/respec/develop/builds/respec-w3c-common.js:8:6386)
    at https://cdn.rawgit.com/w3c/respec/develop/builds/respec-w3c-common.js:4:18386
    at https://cdn.rawgit.com/w3c/respec/develop/builds/respec-w3c-common.js:4:18350"

> TypeError: Cannot read property 'remove' of null
    at Object.run (markdown.js:254)
    at base-runner.js:54
    at base-runner.js:53

> Uncaught (in promise) TypeError: Cannot read property 'removeAttribute' of undefined
    at Object.enable (ui.js:106)
    at profile-w3c-common.js:88

**Comment by marcoscaceres** [comment]
Reopening to take a look

**Comment by marcoscaceres** [comment]
@tpluscode, where is the actual repo for this spec on github? I'd like to clone it to investigate with a debug build of ReSpec.

**Comment by tpluscode** [comment]
Here's my fork: https://github.com/tpluscode/hydra

See `spec/latest/core/index.html`. I'm pulling respec from github cdn

**Comment by marcoscaceres** [comment]
@tpluscode, ok... so, the "source_text" error is due to: 
https://github.com/beautify-web/js-beautify/pull/1093

Hopefully they merge that soon - so thanks for letting me know... 

About the $getJSON(), can you use [fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) or XHR instead? jQuery might no be available when that function is being called. 

Also, that should be a function, to which .apply() is called... so, having an object with an .apply() method is not really what you want there. To be clear:

```js
function preProc(c) {/*... stuff...*/ }
```

**Comment by tpluscode** [comment]
You lost me with jQuery. It's not my code in general, but I don't see $getJSON() being used

**Comment by tpluscode** [comment]
Please disregard that other comment ;)

**Comment by marcoscaceres** [comment]
beautify-web/js-beautify#1093 got merged, so hopefully now works ok... @tpluscode, let me know.

**Comment by tpluscode** [comment]
It works great locally but strangely still throws some errors on GitHub pages. Probably a different problem though. The section imported from markdown renders fine

**Comment by tpluscode** [comment]
I don't know. It's something with my Chrome. Works great in Incognito and Firefox.

Thank you very much!
