### ISSUE TITLE
Drop warnings about missing <dfn> for "definition" names (interface, enum, etc.)?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec#997]
New warnings reported by ReSpec about IDL members that lack dfn in prose are very useful. However, the report includes warnings for interface/enum/dictionary/... names as well. Is this intended?

For instance, consider the following IDL block:

```webidl
interface PresentationRequest : EventTarget {
    Promise<PresentationConnection>   start();
    [...]
};

interface PresentationConnection : EventTarget {
    [...]
};
```

If I click on `start`, I would expect to be taken to the description of the start method, which indeed requires a dfn in prose (and a warning if it does not exist).

Now, if I click on the `PresentationConnection` returned by `start`, I would expect to be taken to the IDL definition of `PresentationConnection`, not to prose that describes that concept. Letting the IDL **be** the definition for `PresentationConnection` typically allows for that.

This seems a common pattern in our specs. Is this saying that it is an anti-pattern?

**Comment by marcoscaceres** [comment]
> However, the report includes warnings for interface/enum/dictionary/... names as well. Is this intended?

Absolutely! Those should be linked too. 

> This seems a common pattern in our specs. Is this saying that it is an anti-pattern?

A little bit. 

The pattern to use for the above is:

```HTML
<section data-dfn-for="PresentationRequest">
  <h2><dfn>PresentationRequest</dfn> interface</h2>
  <pre class="idl">
  interface PresentationRequest : EventTarget {
    Promise&lt;PresentationConnection> start();
  };
  </pre>
  <section link-for="PresentationRequest">
    <h3><dfn>start</dfn> method</h3>
    <p>The <a>PresentationRequest.start</a> method.
    <p>Or <a>start<a> method...</p>
  </section>
</section>

<section data-dfn-for="PresentationRequest">
  <h2><dfn>PresentationConnection</dfn> interface</h2>
  <pre class="idl">
  interface PresentationConnection : EventTarget {
      
  };
  </pre>
</section>
```

**Comment by marcoscaceres** [comment]
Sorry, there was a typo in the code above.

**Comment by marcoscaceres** [comment]
@tidoust, let me know how you go. I'm happy to help a bit with some refactoring in the presentation spec.

**Comment by tidoust** [comment]
OK. The developer in me would prefer IDL fragments to be linked together, but then the spec reader in me prefers prose to IDL, so that works for me :)

Thanks for the code example, @marcoscaceres ! Updating the spec should be pretty straightforward. We should be able to do it.

**Comment by alvestrand** [comment]
When you introduce new warnings, and claim new patterns, the least you should do is to have a clear description of how to fix the warning. Where's the communication to developers about this new warning and how to fix it?

**Comment by marcoscaceres** [comment]
@alvestrand although the warning is new, the pattern is not. However, I'll make sure to include a link with the warning: https://github.com/w3c/respec/wiki/WebIDL-Guide
